{FCTopology[tp1, {SFAD[k], SFAD[k + p1], SFAD[k + p1 + p2], 
   SFAD[{l + p1 + p2, mt^2}], SFAD[{l + p1, mt^2}], SFAD[{l, mt^2}], 
   SFAD[{k - l, mt^2}]}, {k, l}, {p1, p2}, {Hold[SPD][p1, p1] -> 0, 
   Hold[SPD][p2, p2] -> 0, Hold[SPD][p1, p2] -> s/2}, {}], 
 FCTopology[tp2, {SFAD[{k, mt^2}], SFAD[{k + p2, mt^2}], 
   SFAD[{k + p1 + p2, mt^2}], SFAD[{l + p1 + p2, mt^2}], 
   SFAD[{l + p2, mt^2}], SFAD[{l, mt^2}], SFAD[k - l]}, {k, l}, {p1, p2}, 
  {Hold[SPD][p1, p1] -> 0, Hold[SPD][p2, p2] -> 0, Hold[SPD][p1, p2] -> s/2}, 
  {}], FCTopology[tp3, {SFAD[{k, mt^2}], SFAD[k - l - p1], 
   SFAD[{k + p1 + p2, mt^2}], SFAD[{l + p1 + p2, mt^2}], 
   SFAD[{l + p1, mt^2}], SFAD[{k + p1, mt^2}], SFAD[k - l]}, {k, l}, 
  {p1, p2}, {Hold[SPD][p1, p1] -> 0, Hold[SPD][p2, p2] -> 0, 
   Hold[SPD][p1, p2] -> s/2}, {}]}
