(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"QCD-EPEM",
  Authors -> {"Vladyslav Shtabovenko"},
  Institutions -> {"FeynCalc project"},
  Emails -> {""},
  Date -> "23.06.2026"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
V[5] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "g",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[5] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    PropagatorLabel -> "uq",
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    PropagatorLabel -> "dq",
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\gamma",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} }
}


(*        Definitions       *)

FAGaugeXi[ V[5] ] = FAGaugeXi[G];
FAGaugeXi[ U[5] ] = FAGaugeXi[G];

Mu[ 1, _ ] := FCGV["MU"];
Mu[ 1 ] := FCGV["MU"];
Mu[ 2, _ ] := FCGV["MC"];
Mu[ 2 ] := FCGV["MC"];
Mu[ 3, _ ] := FCGV["MT"];
Mu[ 3 ] := FCGV["MT"];
Md[ 1, _ ] := FCGV["MD"];
Md[ 1 ] := FCGV["MD"];
Md[ 2, _ ] := FCGV["MS"];
Md[ 2 ] := FCGV["MS"];
Md[ 3, _ ] := FCGV["MB"];
Md[ 3 ] := FCGV["MB"];


TheLabel[ V[5, {__}] ] := TheLabel[V[5]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[1] , V[1] ] == {{0, (-I)*(-1 + Zem)}, {0, I*(-1 + Zem)}, {0, 0}},

C[ V[5, {e1x2}] , V[5, {e2x2}] ] == {{0, (-I)*(-1 + ZA)*IndexDelta[e1x2, e2x2]}, {0, I*(-1 + ZA)*IndexDelta[e1x2, e2x2]}, {0, (I*(ZA - Zxi)*IndexDelta[e1x2, e2x2])/(Zxi*FAGaugeXi["G"])}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] ] == {{0, (-I)*(-1 + Zu)*IndexDelta[e1x1, e2x1]}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[5, {e3x2}] ] == {{FAGS*FASUNF[e3x2, e1x1, e2x1], FAGS*(-1 + Sqrt[ZA]*Zg*Zu)*FASUNF[e3x2, e1x1, e2x1]}, {0, 0}},

C[ V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] ] == {{-(FAGS*FASUNF[e1x2, e2x2, e3x2]), -(FAGS*(-1 + ZA^(3/2)*Zg)*FASUNF[e1x2, e2x2, e3x2])}, {FAGS*FASUNF[e1x2, e2x2, e3x2], FAGS*(-1 + ZA^(3/2)*Zg)*FASUNF[e1x2, e2x2, e3x2]}, {FAGS*FASUNF[e1x2, e2x2, e3x2], FAGS*(-1 + ZA^(3/2)*Zg)*FASUNF[e1x2, e2x2, e3x2]}, {-(FAGS*FASUNF[e1x2, e2x2, e3x2]), -(FAGS*(-1 + ZA^(3/2)*Zg)*FASUNF[e1x2, e2x2, e3x2])}, {-(FAGS*FASUNF[e1x2, e2x2, e3x2]), -(FAGS*(-1 + ZA^(3/2)*Zg)*FASUNF[e1x2, e2x2, e3x2])}, {FAGS*FASUNF[e1x2, e2x2, e3x2], FAGS*(-1 + ZA^(3/2)*Zg)*FASUNF[e1x2, e2x2, e3x2]}},

C[ V[5, {e1x2}] , V[5, {e2x2}] , V[5, {e3x2}] , V[5, {e4x2}] ] == {{I*FAGS^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), I*FAGS^2*(-1 + ZA^2*Zg^2)*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2])}, {(-I)*FAGS^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), (-I)*FAGS^2*(-1 + ZA^2*Zg^2)*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2])}, {(-I)*FAGS^2*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), (-I)*FAGS^2*(-1 + ZA^2*Zg^2)*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2])}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{(I/3)*FCGV["EL"]*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {(I/3)*FCGV["EL"]*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] ] == {{0, (-I)*(-1 + Zm*Zpsi)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]*Md[e1x2]}, {0, (-I)*(-1 + Zm*Zpsi)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]*Md[e1x2]}, {0, I*(-1 + Zpsi)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}, {0, I*(-1 + Zpsi)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}, {0, 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{((-2*I)/3)*FCGV["EL"]*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {((-2*I)/3)*FCGV["EL"]*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] ] == {{0, (-I)*(-1 + Zm*Zpsi)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]*Mu[e1x2]}, {0, (-I)*(-1 + Zm*Zpsi)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]*Mu[e1x2]}, {0, I*(-1 + Zpsi)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}, {0, I*(-1 + Zpsi)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[5, {e3x2}] ] == {{(-I)*FAGS*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], (-I)*FAGS*(-1 + Sqrt[ZA]*Zg*Zpsi)*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3]}, {(-I)*FAGS*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], (-I)*FAGS*(-1 + Sqrt[ZA]*Zg*Zpsi)*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3]}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[5, {e3x2}] ] == {{(-I)*FAGS*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], (-I)*FAGS*(-1 + Sqrt[ZA]*Zg*Zpsi)*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3]}, {(-I)*FAGS*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], (-I)*FAGS*(-1 + Sqrt[ZA]*Zg*Zpsi)*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3]}}

}

