(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Yukawa",
  Authors -> {"Vladyslav Shtabovenko"},
  Institutions -> {"FeynCalc project"},
  Emails -> {""},
  Date -> "08.08.2024"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
F[10] == {
    SelfConjugate -> False,
    PropagatorLabel -> "X",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mx,
    Indices -> {} },

S[1] == {
    PropagatorLabel -> "\[Phi]",
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Mphi,
    Indices -> {} }
}


(*        Definitions       *)


Mx[ ___ ] := Mx;
Mphi[ ___ ] := Mphi;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] ] == {{0, (-I)*Mphi^2*(-1 + Zmphi*Zphi)}, {0, (-I)*(-1 + Zphi)}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-I)*la, (-I)*la*(-1 + Zla*Zphi^2)}},

C[ -F[10] , F[10] ] == {{0, (-I)*Mx*(-1 + Zmx*Zx)}, {0, (-I)*Mx*(-1 + Zmx*Zx)}, {0, I*(-1 + Zx)}, {0, I*(-1 + Zx)}, {0, 0}, {0, 0}},

C[ -F[10] , F[10] , S[1] ] == {{(-I)*g, (-I)*g*(-1 + Zg*Sqrt[Zphi]*Zx)}, {(-I)*g, (-I)*g*(-1 + Zg*Sqrt[Zphi]*Zx)}}

}

