BrowserCategory["High Energy Physics", None,

{    Item["Introduction", "FeynCalcBook.nb", 
          IndexTag -> "Short Overview", CopyTag -> "intro"],

     Item["Starting FeynCalc", "FeynCalcBook.nb",
          IndexTag -> "Load FeynCalc", CopyTag ->"start"],

      BrowserCategory["Example Calculations",
        None, {Item["About Example Calculations", "FeynCalcBook.nb",
               IndexTag -> "Example Calculations", CopyTag->"ex"],
               Item["Pair Production", "FeynCalcBook.nb", IndexTag->"Tree level"],
               Item["Moment Integral", "FeynCalcBook.nb", IndexTag->"A moment integral"]}],

    BrowserCategory["Extras",
      None, {
      Item["About Extras", "FeynCalcBook.nb",
           IndexTag->"About Extras"],
      Item["TARCER", "FeynCalcBook.nb", IndexTag->"tarcer"],
      Item["Phi", "FeynCalcBook.nb", IndexTag->"phi"],
      Item["FeynArts", "FeynCalcBook.nb", IndexTag->"fa"]}],


BrowserCategory["Reference Guide", None, {BrowserCategory["Core",
      None, {Item["A", "FeynCalcBook.nb"], Item["A0ToB0", "FeynCalcBook.nb"],
        Item["Abbreviation", "FeynCalcBook.nb"], Item["Anti5", "FeynCalcBook.nb"],
         Item["AntiCommutator", "FeynCalcBook.nb"],
        Item["AntiQuarkField", "FeynCalcBook.nb"],
        Item["Bracket", "FeynCalcBook.nb"], Item["CA", "FeynCalcBook.nb"],
        Item["Cases2", "FeynCalcBook.nb"], Item["CF", "FeynCalcBook.nb"],
        Item["CheckContext", "FeynCalcBook.nb"],
        Item["ChiralityProjector", "FeynCalcBook.nb"],
        Item["ChisholmSpinor", "FeynCalcBook.nb"],
        Item["Collecting", "FeynCalcBook.nb"],
        Item["Commutator", "FeynCalcBook.nb"],
        Item["CommutatorExplicit", "FeynCalcBook.nb"],
        Item["ComplexIndex", "FeynCalcBook.nb"],
        Item["CounterT", "FeynCalcBook.nb"],
        Item["CouplingConstant", "FeynCalcBook.nb"],
        Item["DataType", "FeynCalcBook.nb"],
        Item["DeclareNonCommutative", "FeynCalcBook.nb"],
        Item["DeltaFunction", "FeynCalcBook.nb"],
        Item["DeltaFunctionDoublePrime", "FeynCalcBook.nb"],
        Item["DeltaFunctionPrime", "FeynCalcBook.nb"],
        Item["Dimension", "FeynCalcBook.nb"],
        Item["DimensionalReduction", "FeynCalcBook.nb"],
        Item["DiracBasis", "FeynCalcBook.nb"],
        Item["DiracCanonical", "FeynCalcBook.nb"],
        Item["DiracEquation", "FeynCalcBook.nb"],
        Item["DiracGamma", "FeynCalcBook.nb"],
        Item["DiracGammaCombine", "FeynCalcBook.nb"],
        Item["DiracGammaExpand", "FeynCalcBook.nb"],
        Item["DiracGammaT", "FeynCalcBook.nb"],
        Item["DiracMatrix", "FeynCalcBook.nb"],
        Item["DiracOrder", "FeynCalcBook.nb"],
        Item["DiracReduce", "FeynCalcBook.nb"],
        Item["DiracSigma", "FeynCalcBook.nb"],
        Item["DiracSigmaExplicit", "FeynCalcBook.nb"],
        Item["DiracSimpCombine", "FeynCalcBook.nb"],
        Item["DiracSimplify", "FeynCalcBook.nb"],
        Item["DiracSimplify2", "FeynCalcBook.nb"],
        Item["DiracSlash", "FeynCalcBook.nb"],
        Item["DiracSpinor", "FeynCalcBook.nb"],
        Item["DiracSubstitute67", "FeynCalcBook.nb"],
        Item["DiracTrace", "FeynCalcBook.nb"],
        Item["DiracTraceEvaluate", "FeynCalcBook.nb"],
        Item["DiracTrick", "FeynCalcBook.nb"],
        Item["Divideout", "FeynCalcBook.nb"], Item["DOT", "FeynCalcBook.nb"],
        Item["DotPower", "FeynCalcBook.nb"],
        Item["DotSimplify", "FeynCalcBook.nb"],
        Item["DotSimplifyRelations", "FeynCalcBook.nb"],
        Item["DummyIndex", "FeynCalcBook.nb"], Item["Eps", "FeynCalcBook.nb"],
        Item["EpsContract", "FeynCalcBook.nb"],
        Item["EpsDiscard", "FeynCalcBook.nb"],
        Item["EpsEvaluate", "FeynCalcBook.nb"],
        Item["EpsilonOrder", "FeynCalcBook.nb"],
        Item["Expanding", "FeynCalcBook.nb"],
        Item["ExpandScalarProduct", "FeynCalcBook.nb"],
        Item["ExplicitLorentzIndex", "FeynCalcBook.nb"],
        Item["ExtraFactor", "FeynCalcBook.nb"], Item["F21", "FeynCalcBook.nb"],
        Item["FactorFull", "FeynCalcBook.nb"],
        Item["Factoring", "FeynCalcBook.nb"],
        Item["Factorout", "FeynCalcBook.nb"],
        Item["FactorTime", "FeynCalcBook.nb"], Item["FAD", "FeynCalcBook.nb"],
        Item["FC", "FeynCalcBook.nb"], Item["FCInstall", "FeynCalcBook.nb"],
        Item["FeynAmp", "FeynCalcBook.nb"],
        Item["FeynAmpDenominator", "FeynCalcBook.nb"],
        Item["FeynAmpList", "FeynCalcBook.nb"],
        Item["FeynCalc", "FeynCalcBook.nb"],
        Item["FeynCalcForm", "FeynCalcBook.nb"],
        Item["FeynmanParameterNames", "FeynCalcBook.nb"],
        Item["FI", "FeynCalcBook.nb"], Item["FieldStrength", "FeynCalcBook.nb"],
        Item["FinalSubstitutions", "FeynCalcBook.nb"],
        Item["FORM", "FeynCalcBook.nb"], Item["FORMEpilog", "FeynCalcBook.nb"],
        Item["FORMProlog", "FeynCalcBook.nb"],
        Item["FourVector", "FeynCalcBook.nb"],
        Item["FreeIndex", "FeynCalcBook.nb"], Item["FreeQ2", "FeynCalcBook.nb"],
        Item["FRH", "FeynCalcBook.nb"], Item["FV", "FeynCalcBook.nb"],
        Item["FVD", "FeynCalcBook.nb"], Item["GA", "FeynCalcBook.nb"],
        Item["GA5", "FeynCalcBook.nb"], Item["GAD", "FeynCalcBook.nb"],
        Item["GammaExpand", "FeynCalcBook.nb"], Item["Gauge", "FeynCalcBook.nb"],
        Item["GaugeField", "FeynCalcBook.nb"], Item["GaugeXi", "FeynCalcBook.nb"],
         Item["GluonField", "FeynCalcBook.nb"],
        Item["GrassmannParity", "FeynCalcBook.nb"], Item["GS", "FeynCalcBook.nb"],
         Item["GSD", "FeynCalcBook.nb"], Item["Gstrong", "FeynCalcBook.nb"],
        Item["GTI", "FeynCalcBook.nb"], Item["IFPD", "FeynCalcBook.nb"],
        Item["IFPDOff", "FeynCalcBook.nb"], Item["IFPDOn", "FeynCalcBook.nb"],
        Item["IncludePair", "FeynCalcBook.nb"],
        Item["IndexPosition", "FeynCalcBook.nb"],
        Item["Indices", "FeynCalcBook.nb"],
        Item["InitialSubstitutions", "FeynCalcBook.nb"],
        Item["InsideDiracTrace", "FeynCalcBook.nb"],
        Item["IntegralTable", "FeynCalcBook.nb"],
        Item["Integratedx", "FeynCalcBook.nb"],
        Item["IntermediateSubstitutions", "FeynCalcBook.nb"],
        Item["IsolateHead", "FeynCalcBook.nb"],
        Item["IsolateNames", "FeynCalcBook.nb"],
        Item["IsolatePrint", "FeynCalcBook.nb"],
        Item["IsolateSplit", "FeynCalcBook.nb"],
        Item["KeepOnly", "FeynCalcBook.nb"], Item["KK", "FeynCalcBook.nb"],
        Item["LC", "FeynCalcBook.nb"], Item["LCD", "FeynCalcBook.nb"],
        Item["LeftPartialD", "FeynCalcBook.nb"],
        Item["LeftRightPartialD", "FeynCalcBook.nb"],
        Item["LeftRightPartialD2", "FeynCalcBook.nb"],
        Item["LeptonSpinor", "FeynCalcBook.nb"],
        Item["LeviCivita", "FeynCalcBook.nb"],
        Item["LeviCivitaSign", "FeynCalcBook.nb"], Item["Li2", "FeynCalcBook.nb"],
         Item["Li3", "FeynCalcBook.nb"], Item["Load", "FeynCalcBook.nb"],
        Item["Loop", "FeynCalcBook.nb"], Item["LorentzIndex", "FeynCalcBook.nb"],
        Item["Lower", "FeynCalcBook.nb"], Item["MakeContext", "FeynCalcBook.nb"],
        Item["Mandelstam", "FeynCalcBook.nb"],
        Item["MemoryAvailable", "FeynCalcBook.nb"],
        Item["MemSet", "FeynCalcBook.nb"],
        Item["MetricTensor", "FeynCalcBook.nb"],
        Item["Momentum", "FeynCalcBook.nb"],
        Item["MomentumCombine", "FeynCalcBook.nb"],
        Item["MomentumCombine2", "FeynCalcBook.nb"],
        Item["MomentumExpand", "FeynCalcBook.nb"], Item["MT", "FeynCalcBook.nb"],
        Item["MTD", "FeynCalcBook.nb"],
        Item["NegativeInteger", "FeynCalcBook.nb"], Item["Nf", "FeynCalcBook.nb"],
         Item["NonCommFreeQ", "FeynCalcBook.nb"],
        Item["NonCommQ", "FeynCalcBook.nb"],
        Item["NonCommutative", "FeynCalcBook.nb"],
        Item["NTerms", "FeynCalcBook.nb"],
        Item["NumberOfMetricTensors", "FeynCalcBook.nb"],
        Item["NumericalFactor", "FeynCalcBook.nb"],
        Item["OPE", "FeynCalcBook.nb"], Item["Pair", "FeynCalcBook.nb"],
        Item["PairCollect", "FeynCalcBook.nb"],
        Item["PairContract", "FeynCalcBook.nb"],
        Item["PairContract2", "FeynCalcBook.nb"],
        Item["PairContract3", "FeynCalcBook.nb"],
        Item["PartialD", "FeynCalcBook.nb"],
        Item["PartitHead", "FeynCalcBook.nb"],
        Item["PauliSigma", "FeynCalcBook.nb"],
        Item["PaVeOrderList", "FeynCalcBook.nb"],
        Item["PlusDistribution", "FeynCalcBook.nb"],
        Item["Polarization", "FeynCalcBook.nb"],
        Item["PolarizationVector", "FeynCalcBook.nb"],
        Item["PositiveInteger", "FeynCalcBook.nb"],
        Item["PositiveNumber", "FeynCalcBook.nb"],
        Item["PropagatorDenominator", "FeynCalcBook.nb"],
        Item["QuantumField", "FeynCalcBook.nb"],
        Item["QuarkField", "FeynCalcBook.nb"],
        Item["QuarkMass", "FeynCalcBook.nb"], Item["Rename", "FeynCalcBook.nb"],
        Item["ScalarProduct", "FeynCalcBook.nb"],
        Item["ScalarProductExpand", "FeynCalcBook.nb"],
        Item["SD", "FeynCalcBook.nb"], Item["SmallDelta", "FeynCalcBook.nb"],
        Item["SmallEpsilon", "FeynCalcBook.nb"],
        Item["SmallVariable", "FeynCalcBook.nb"], Item["SO", "FeynCalcBook.nb"],
        Item["SOD", "FeynCalcBook.nb"], Item["SP", "FeynCalcBook.nb"],
        Item["SPC", "FeynCalcBook.nb"], Item["SPD", "FeynCalcBook.nb"],
        Item["Spinor", "FeynCalcBook.nb"], Item["SpinorU", "FeynCalcBook.nb"],
        Item["SpinorUBar", "FeynCalcBook.nb"], Item["SpinorV", "FeynCalcBook.nb"],
         Item["SpinorVBar", "FeynCalcBook.nb"], Item["SPL", "FeynCalcBook.nb"],
        Item["SubContext", "FeynCalcBook.nb"], Item["SUND", "FeynCalcBook.nb"],
        Item["SUNDelta", "FeynCalcBook.nb"],
        Item["SUNDeltaContract", "FeynCalcBook.nb"],
        Item["SUNF", "FeynCalcBook.nb"], Item["SUNF2", "FeynCalcBook.nb"],
        Item["SUNFJacobi", "FeynCalcBook.nb"],
        Item["SUNFToTraces", "FeynCalcBook.nb"],
        Item["SUNIndex", "FeynCalcBook.nb"],
        Item["SUNIndexRename", "FeynCalcBook.nb"],
        Item["SUNN", "FeynCalcBook.nb"], Item["SUNNToCACF", "FeynCalcBook.nb"],
        Item["SUNT", "FeynCalcBook.nb"], Item["SUNTrace", "FeynCalcBook.nb"],
        Item["Tbox", "FeynCalcBook.nb"], Item["TBox", "FeynCalcBook.nb"],
        Item["Tr", "FeynCalcBook.nb"], Item["Tr2", "FeynCalcBook.nb"],
        Item["TraceOfOne", "FeynCalcBook.nb"], Item["Trick", "FeynCalcBook.nb"],
        Item["UnDeclareNonCommutative", "FeynCalcBook.nb"],
        Item["Upper", "FeynCalcBook.nb"], Item["XYT", "FeynCalcBook.nb"],
        Item["$Abbreviations", "FeynCalcBook.nb"],
        Item["$AchmedRoss", "FeynCalcBook.nb"], Item["$AL", "FeynCalcBook.nb"],
        Item["$BreitMaison", "FeynCalcBook.nb"],
        Item["$Color", "FeynCalcBook.nb"], Item["$Covariant", "FeynCalcBook.nb"],
        Item["$FCS", "FeynCalcBook.nb"], Item["$FCT", "FeynCalcBook.nb"],
        Item["$FeynCalcCreationDate", "FeynCalcBook.nb"],
        Item["$FeynCalcStuff", "FeynCalcBook.nb"],
        Item["$FeynCalcVersion", "FeynCalcBook.nb"],
        Item["$FortranContinuationCharacter", "FeynCalcBook.nb"],
        Item["$Kreimer", "FeynCalcBook.nb"], Item["$Larin", "FeynCalcBook.nb"],
        Item["$LimitTo4", "FeynCalcBook.nb"],
        Item["$LorentzIndices", "FeynCalcBook.nb"],
        Item["$MemoryAvailable", "FeynCalcBook.nb"],
        Item["$MIntegrate", "FeynCalcBook.nb"],
        Item["$MomentumIndices", "FeynCalcBook.nb"],
        Item["$MU", "FeynCalcBook.nb"], Item["$NonComm", "FeynCalcBook.nb"],
        Item["$NU", "FeynCalcBook.nb"], Item["$OPEWard", "FeynCalcBook.nb"],
        Item["$PairBrackets", "FeynCalcBook.nb"],
        Item["$SpinorMinimal", "FeynCalcBook.nb"], Item["$V0", "FeynCalcBook.nb"],
         Item["$V3", "FeynCalcBook.nb"], Item["$VeryVerbose", "FeynCalcBook.nb"],
        Item["$West", "FeynCalcBook.nb"]}],
    BrowserCategory["Tools",
      None, {Item["Amputate", "FeynCalcBook.nb"],
        Item["Apart2", "FeynCalcBook.nb"], Item["Calc", "FeynCalcBook.nb"],
        Item["CalculateCounterTerm", "FeynCalcBook.nb"],
        Item["ChangeDimension", "FeynCalcBook.nb"],
        Item["ChargeConjugationMatrixInv", "FeynCalcBook.nb"],
        Item["ChargeConjugationMatrix", "FeynCalcBook.nb"],
        Item["Chisholm", "FeynCalcBook.nb"],
        Item["ClearScalarProducts", "FeynCalcBook.nb"],
        Item["ComplexConjugate", "FeynCalcBook.nb"],
        Item["Contract1", "FeynCalcBook.nb"], Item["Contract", "FeynCalcBook.nb"],
         Item["Convolute", "FeynCalcBook.nb"],
        Item["CovariantD", "FeynCalcBook.nb"],
        Item["CrossProduct", "FeynCalcBook.nb"],
        Item["DotProduct", "FeynCalcBook.nb"],
        Item["EpsChisholm", "FeynCalcBook.nb"],
        Item["Epsilon2", "FeynCalcBook.nb"], Item["Epsilon", "FeynCalcBook.nb"],
        Item["ExpandPartialD", "FeynCalcBook.nb"],
        Item["Explicit", "FeynCalcBook.nb"],
        Item["ExplicitPartialD", "FeynCalcBook.nb"],
        Item["FC2RHI", "FeynCalcBook.nb"], Item["FC2TLI", "FeynCalcBook.nb"],
        Item["FCIntegral", "FeynCalcBook.nb"],
        Item["FermionSpinSum", "FeynCalcBook.nb"],
        Item["FeynAmpDenominatorCombine", "FeynCalcBook.nb"],
        Item["FeynAmpDenominatorSimplify", "FeynCalcBook.nb"],
        Item["FeynAmpDenominatorSplit", "FeynCalcBook.nb"],
        Item["FeynCalc2FORM", "FeynCalcBook.nb"],
        Item["FeynCalcExternal", "FeynCalcBook.nb"],
        Item["FeynCalcInternal", "FeynCalcBook.nb"],
        Item["FeynmanParametrize1", "FeynCalcBook.nb"],
        Item["FeynmanParametrize", "FeynCalcBook.nb"],
        Item["FeynRule", "FeynCalcBook.nb"],
        Item["FORM2FeynCalc", "FeynCalcBook.nb"],
        Item["FourDivergence", "FeynCalcBook.nb"],
        Item["FourLaplacian", "FeynCalcBook.nb"],
        Item["FromTFi", "FeynCalcBook.nb"],
        Item["FunctionalD", "FeynCalcBook.nb"],
        Item["InitialFunction", "FeynCalcBook.nb"],
        Item["IntegrateByParts", "FeynCalcBook.nb"],
        Item["InverseMellin", "FeynCalcBook.nb"],
        Item["ListIntegrals", "FeynCalcBook.nb"],
        Item["OneLoop", "FeynCalcBook.nb"],
        Item["OneLoopSimplify", "FeynCalcBook.nb"],
        Item["PartialFourVector", "FeynCalcBook.nb"],
        Item["PartialIntegrate", "FeynCalcBook.nb"],
        Item["PaVe", "FeynCalcBook.nb"], Item["PaVeOrder", "FeynCalcBook.nb"],
        Item["PaVeReduce", "FeynCalcBook.nb"],
        Item["PolarizationSum", "FeynCalcBook.nb"],
        Item["PolarizationVectorExplicit", "FeynCalcBook.nb"],
        Item["PropagatorDenominatorExplicit", "FeynCalcBook.nb"],
        Item["RHI2FC", "FeynCalcBook.nb"], Item["RHI", "FeynCalcBook.nb"],
        Item["RHM", "FeynCalcBook.nb"], Item["RHO", "FeynCalcBook.nb"],
        Item["RHP", "FeynCalcBook.nb"], Item["RightPartialD", "FeynCalcBook.nb"],
        Item["RussianTrick", "FeynCalcBook.nb"],
        Item["ScalarProductCancel", "FeynCalcBook.nb"],
        Item["Schouten", "FeynCalcBook.nb"],
        Item["SetMandelstam", "FeynCalcBook.nb"],
        Item["SimplifyDeltaFunction", "FeynCalcBook.nb"],
        Item["SimplifyPolyLog", "FeynCalcBook.nb"],
        Item["SMP", "FeynCalcBook.nb"],
        Item["SquareAmplitude", "FeynCalcBook.nb"],
        Item["Tdec", "FeynCalcBook.nb"],
        Item["TensorFunction", "FeynCalcBook.nb"], Item["TFi", "FeynCalcBook.nb"],
         Item["ThreeVector", "FeynCalcBook.nb"], Item["TIDL", "FeynCalcBook.nb"],
        Item["TID", "FeynCalcBook.nb"], Item["ToTFi", "FeynCalcBook.nb"],
        Item["TraceDimension", "FeynCalcBook.nb"],
        Item["TrickIntegrate", "FeynCalcBook.nb"],
        Item["TrickMandelstam", "FeynCalcBook.nb"],
        Item["Uncontract", "FeynCalcBook.nb"], Item["UVPart", "FeynCalcBook.nb"],
        Item["Vectors", "FeynCalcBook.nb"], Item["Write2", "FeynCalcBook.nb"],
        Item["WriteOut", "FeynCalcBook.nb"],
        Item["WriteOutPaVe", "FeynCalcBook.nb"],
        Item["ZeroMomentumInsertion", "FeynCalcBook.nb"]}],
    BrowserCategory["Tables",
      None, {Item["A0", "FeynCalcBook.nb"], Item["Amplitudes", "FeynCalcBook.nb"],
         Item["AnomalousDimension", "FeynCalcBook.nb"],
        Item["B00", "FeynCalcBook.nb"], Item["B0", "FeynCalcBook.nb"],
        Item["B11", "FeynCalcBook.nb"], Item["B1", "FeynCalcBook.nb"],
        Item["BReduce", "FeynCalcBook.nb"], Item["C0", "FeynCalcBook.nb"],
        Item["ConvoluteTable", "FeynCalcBook.nb"],
        Item["CounterTerm", "FeynCalcBook.nb"],
        Item["D0Convention", "FeynCalcBook.nb"], Item["D0", "FeynCalcBook.nb"],
        Item["DB0", "FeynCalcBook.nb"], Item["DB1", "FeynCalcBook.nb"],
        Item["Integrate2", "FeynCalcBook.nb"],
        Item["Integrate3", "FeynCalcBook.nb"],
        Item["Integrate4", "FeynCalcBook.nb"],
        Item["Integrate5", "FeynCalcBook.nb"],
        Item["Lagrangian", "FeynCalcBook.nb"], Item["RTL", "FeynCalcBook.nb"],
        Item["ScalarGluonVertex", "FeynCalcBook.nb"],
        Item["SimplifyGTI", "FeynCalcBook.nb"],
        Item["SMVertex", "FeynCalcBook.nb"],
        Item["SpinPolarizationSum", "FeynCalcBook.nb"],
        Item["SplittingFunction", "FeynCalcBook.nb"]}],
    BrowserCategory["QCD",
      None, {Item["BackgroundGluonVertex", "FeynCalcBook.nb"],
        Item["ExplicitSUNIndex", "FeynCalcBook.nb"],
        Item["GhostPropagator", "FeynCalcBook.nb"],
        Item["GluonGhostVertex", "FeynCalcBook.nb"],
        Item["GluonPropagator", "FeynCalcBook.nb"],
        Item["GluonSelfEnergy", "FeynCalcBook.nb"],
        Item["GluonVertex", "FeynCalcBook.nb"],
        Item["OPE1Loop", "FeynCalcBook.nb"], Item["OPE2AI", "FeynCalcBook.nb"],
        Item["OPE2TID", "FeynCalcBook.nb"], Item["OPEDelta", "FeynCalcBook.nb"],
        Item["OPEi", "FeynCalcBook.nb"], Item["OPEInsert", "FeynCalcBook.nb"],
        Item["OPEIntDelta", "FeynCalcBook.nb"],
        Item["OPEIntegrate2", "FeynCalcBook.nb"],
        Item["OPEIntegrateDelta", "FeynCalcBook.nb"],
        Item["OPEIntegrate", "FeynCalcBook.nb"],
        Item["OPEInt", "FeynCalcBook.nb"], Item["OPEj", "FeynCalcBook.nb"],
        Item["OPEk", "FeynCalcBook.nb"], Item["OPEl", "FeynCalcBook.nb"],
        Item["OPEm", "FeynCalcBook.nb"], Item["OPEn", "FeynCalcBook.nb"],
        Item["OPEo", "FeynCalcBook.nb"],
        Item["OPESumExplicit", "FeynCalcBook.nb"],
        Item["OPESum", "FeynCalcBook.nb"],
        Item["OPESumSimplify", "FeynCalcBook.nb"],
        Item["PowerSimplify", "FeynCalcBook.nb"],
        Item["QCDScalemu", "FeynCalcBook.nb"],
        Item["QuarkGluonVertex", "FeynCalcBook.nb"],
        Item["QuarkPropagator", "FeynCalcBook.nb"],
        Item["QuarkSpinor", "FeynCalcBook.nb"],
        Item["Simplify2", "FeynCalcBook.nb"], Item["Smu", "FeynCalcBook.nb"],
        Item["Sn", "FeynCalcBook.nb"], Item["SubLoop", "FeynCalcBook.nb"],
        Item["SUNSimplify", "FeynCalcBook.nb"],
        Item["SymbolicSum2", "FeynCalcBook.nb"],
        Item["SymbolicSum3", "FeynCalcBook.nb"], Item["Tf", "FeynCalcBook.nb"],
        Item["TLI2FC", "FeynCalcBook.nb"], Item["TLI2", "FeynCalcBook.nb"],
        Item["TLIFP", "FeynCalcBook.nb"], Item["TLIHYP", "FeynCalcBook.nb"],
        Item["TLI", "FeynCalcBook.nb"], Item["ToDistribution", "FeynCalcBook.nb"],
         Item["ToLarin", "FeynCalcBook.nb"],
        Item["Twist2AlienOperator", "FeynCalcBook.nb"],
        Item["Twist2CounterOperator", "FeynCalcBook.nb"],
        Item["Twist2GluonOperator", "FeynCalcBook.nb"],
        Item["Twist2QuarkOperator", "FeynCalcBook.nb"],
        Item["Twist3QuarkOperator", "FeynCalcBook.nb"],
        Item["Twist4GluonOperator", "FeynCalcBook.nb"]}],
    BrowserCategory["General",
      None, {Item["AntiSymmetrize", "FeynCalcBook.nb"],
        Item["Apart1", "FeynCalcBook.nb"], Item["Apart3", "FeynCalcBook.nb"],
        Item["Collect2", "FeynCalcBook.nb"], Item["Collect3", "FeynCalcBook.nb"],
        Item["Combine", "FeynCalcBook.nb"], Item["Expand2", "FeynCalcBook.nb"],
        Item["Factor1", "FeynCalcBook.nb"], Item["Factor2", "FeynCalcBook.nb"],
        Item["Gamma1", "FeynCalcBook.nb"], Item["Gamma2", "FeynCalcBook.nb"],
        Item["Gamma3", "FeynCalcBook.nb"],
        Item["GammaEpsilon", "FeynCalcBook.nb"], Item["Hill", "FeynCalcBook.nb"],
        Item["HypergeometricAC", "FeynCalcBook.nb"],
        Item["HypergeometricIR", "FeynCalcBook.nb"],
        Item["HypergeometricSE", "FeynCalcBook.nb"],
        Item["HypExplicit", "FeynCalcBook.nb"], Item["HypInt", "FeynCalcBook.nb"],
         Item["Isolate", "FeynCalcBook.nb"], Item["Kummer", "FeynCalcBook.nb"],
        Item["Map2", "FeynCalcBook.nb"], Item["Nielsen", "FeynCalcBook.nb"],
        Item["Power2", "FeynCalcBook.nb"], Item["PowerFactor", "FeynCalcBook.nb"],
         Item["Select1", "FeynCalcBook.nb"], Item["Select2", "FeynCalcBook.nb"],
        Item["SelectFree", "FeynCalcBook.nb"],
        Item["SelectNotFree", "FeynCalcBook.nb"],
        Item["Series2", "FeynCalcBook.nb"], Item["Series3", "FeynCalcBook.nb"],
        Item["Solve2", "FeynCalcBook.nb"], Item["Solve3", "FeynCalcBook.nb"],
        Item["SumP", "FeynCalcBook.nb"], Item["SumS", "FeynCalcBook.nb"],
        Item["SumT", "FeynCalcBook.nb"], Item["SymbolSum", "FeynCalcBook.nb"],
        Item["Symmetrize", "FeynCalcBook.nb"],
        Item["ToHypergeometric", "FeynCalcBook.nb"],
        Item["TwoLoopSimplify", "FeynCalcBook.nb"],
        Item["Zeta2", "FeynCalcBook.nb"]}]}]

   }]