{{((-16*I)*(2*CouplingConstant[ChPTPhoton2[4], 4, RenormalizationState[0]]*
      SUNDelta[3, I1]*SUNDelta[3, I2] + CouplingConstant[ChPTPhoton2[4], 5, 
       RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I2] - 
     2*CouplingConstant[ChPTPhoton2[4], 4, RenormalizationState[0]]*
      SUNDelta[I1, I2] - CouplingConstant[ChPTPhoton2[4], 5, 
       RenormalizationState[0]]*SUNDelta[I1, I2]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {((4*I)*(CouplingConstant[ChPTPhoton2[4], 9, RenormalizationState[0]]*
      SUNDelta[3, I1]*SUNDelta[3, I2] - CouplingConstant[ChPTPhoton2[4], 9, 
       RenormalizationState[0]]*SUNDelta[I1, I2]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {((4*I)*(CouplingConstant[ChPTPhoton2[4], 9, RenormalizationState[0]]*
      SUNDelta[3, I1]*SUNDelta[3, I2] - CouplingConstant[ChPTPhoton2[4], 9, 
       RenormalizationState[0]]*SUNDelta[I1, I2]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {((4*I)*(CouplingConstant[ChPTPhoton2[4], 9, RenormalizationState[0]]*
      SUNDelta[3, I1]*SUNDelta[3, I2] - CouplingConstant[ChPTPhoton2[4], 9, 
       RenormalizationState[0]]*SUNDelta[I1, I2]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {((4*I)*(CouplingConstant[ChPTPhoton2[4], 9, RenormalizationState[0]]*
      SUNDelta[3, I1]*SUNDelta[3, I2] - CouplingConstant[ChPTPhoton2[4], 9, 
       RenormalizationState[0]]*SUNDelta[I1, I2]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {((-4*I)*(CouplingConstant[ChPTPhoton2[4], 9, RenormalizationState[0]]*
      SUNDelta[3, I1]*SUNDelta[3, I2] - CouplingConstant[ChPTPhoton2[4], 9, 
       RenormalizationState[0]]*SUNDelta[I1, I2]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {((-4*I)*(CouplingConstant[ChPTPhoton2[4], 9, RenormalizationState[0]]*
      SUNDelta[3, I1]*SUNDelta[3, I2] - CouplingConstant[ChPTPhoton2[4], 9, 
       RenormalizationState[0]]*SUNDelta[I1, I2]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {((-4*I)*(CouplingConstant[ChPTPhoton2[4], 9, RenormalizationState[0]]*
      SUNDelta[3, I1]*SUNDelta[3, I2] - CouplingConstant[ChPTPhoton2[4], 9, 
       RenormalizationState[0]]*SUNDelta[I1, I2]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {((-4*I)*(CouplingConstant[ChPTPhoton2[4], 9, RenormalizationState[0]]*
      SUNDelta[3, I1]*SUNDelta[3, I2] - CouplingConstant[ChPTPhoton2[4], 9, 
       RenormalizationState[0]]*SUNDelta[I1, I2]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {((8*I)*(CouplingConstant[ChPTPhoton2[4], 10, RenormalizationState[0]]*
      SUNDelta[3, I1]*SUNDelta[3, I2] - CouplingConstant[ChPTPhoton2[4], 10, 
       RenormalizationState[0]]*SUNDelta[I1, I2]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {((-8*I)*(CouplingConstant[ChPTPhoton2[4], 10, RenormalizationState[0]]*
      SUNDelta[3, I1]*SUNDelta[3, I2] - CouplingConstant[ChPTPhoton2[4], 10, 
       RenormalizationState[0]]*SUNDelta[I1, I2]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}}
