{{(-2*(SU2F[3, I3, I4]*SUNDelta[I1, I2] + SU2F[3, I2, I4]*SUNDelta[I1, I3] +
	SU2F[3, I1, I4]*SUNDelta[I2, I3]))/
(3*DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2)},
{(2*(SU2F[3, I3, I4]*SUNDelta[I1, I2] - SU2F[3, I2, I3]*SUNDelta[I1, I4] -
	SU2F[3, I1, I3]*SUNDelta[I2, I4]))/
(3*DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2)},
{(2*(SU2F[3, I2, I4]*SUNDelta[I1, I3] + SU2F[3, I2, I3]*SUNDelta[I1, I4] -
	SU2F[3, I1, I2]*SUNDelta[I3, I4]))/
(3*DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2)},
{(2*(SU2F[3, I1, I4]*SUNDelta[I2, I3] + SU2F[3, I1, I3]*SUNDelta[I2, I4] +
	SU2F[3, I1, I2]*SUNDelta[I3, I4]))/
(3*DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2)}}
