{{((-8*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[6, 8, I1])/
(Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]])},
{(((-4*I)/3)*CouplingConstant[ChPTW3[2], 2]*(3*SU3F[3, 6, I1] -
	Sqrt[3]*SU3F[6, 8, I1]))/DecayConstant[PseudoScalar[1],
	RenormalizationState[0]]},
{(((4*I)/3)*CouplingConstant[ChPTW3[2], 2]*(3*SU3F[3, 6, I1] +
	Sqrt[3]*SU3F[6, 8, I1]))/DecayConstant[PseudoScalar[1],
	RenormalizationState[0]]}}
