{{(5*SUNDelta[I1, I4]*SUNDelta[I2, I3] + 5*SUNDelta[I1, I3]*
	 SUNDelta[I2, I4] - 10*SUNDelta[I1, I2]*SUNDelta[I3, I4] -
	3*SUNF[I1, I4, k1]*SUNF[I2, I3, k1] - 3*SUNF[I1, I3, k1]*
	 SUNF[I2, I4, k1])/(12*DecayConstant[PseudoScalar[2],
	 RenormalizationState[0]])},
{(5*SUNDelta[I1, I4]*SUNDelta[I2, I3] - 10*SUNDelta[I1, I3]*
	 SUNDelta[I2, I4] + 5*SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	3*SUNF[I1, I4, k1]*SUNF[I2, I3, k1] - 3*SUNF[I1, I2, k1]*
	 SUNF[I3, I4, k1])/(12*DecayConstant[PseudoScalar[2],
	 RenormalizationState[0]])},
{(-10*SUNDelta[I1, I4]*SUNDelta[I2, I3] + 5*SUNDelta[I1, I3]*
	 SUNDelta[I2, I4] + 5*SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	3*SUNF[I1, I3, k1]*SUNF[I2, I4, k1] + 3*SUNF[I1, I2, k1]*
	 SUNF[I3, I4, k1])/(12*DecayConstant[PseudoScalar[2],
	 RenormalizationState[0]])}}
