{{(3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I1, I2, k1] + 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*SU3D[I1, I3, k1] - 
    6*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*SU3D[I2, I3, k1] - 
    (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I3, k1]*SU3F[6, I1, k1] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I3, k1]*SU3F[6, I2, k1] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I2, k1]*SU3F[6, I3, k1] - 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3F[I1, I2, k1] + 
    3*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I3, k1]*SU3F[I1, I2, k1] - 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*SU3F[I1, I3, k1] + 
    3*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I2, k1]*SU3F[I1, I3, k1] + 
    2*CouplingConstant[ChPTW3[2], 1]*SUNDelta[6, I3]*SUNDelta[I1, I2] + 
    2*CouplingConstant[ChPTW3[2], 1]*SUNDelta[6, I2]*SUNDelta[I1, I3] - 
    4*CouplingConstant[ChPTW3[2], 1]*SUNDelta[6, I1]*SUNDelta[I2, I3])/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I1, I2, k1] - 
    6*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*SU3D[I1, I3, k1] + 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*SU3D[I2, I3, k1] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 
    (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I3, k1]*SU3F[6, I2, k1] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I2, k1]*SU3F[6, I3, k1] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3F[I1, I2, k1] - 
    3*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I3, k1]*SU3F[I1, I2, k1] - 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*SU3F[I2, I3, k1] + 
    3*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I1, k1]*SU3F[I2, I3, k1] + 
    2*CouplingConstant[ChPTW3[2], 1]*SUNDelta[6, I3]*SUNDelta[I1, I2] - 
    4*CouplingConstant[ChPTW3[2], 1]*SUNDelta[6, I2]*SUNDelta[I1, I3] + 
    2*CouplingConstant[ChPTW3[2], 1]*SUNDelta[6, I1]*SUNDelta[I2, I3])/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(-6*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I1, I2, k1] + 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*SU3D[I1, I3, k1] + 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*SU3D[I2, I3, k1] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I3, k1]*SU3F[6, I1, k1] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I3, k1]*SU3F[6, I2, k1] - 
    (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I2, k1]*SU3F[6, I3, k1] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*SU3F[I1, I3, k1] - 
    3*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I2, k1]*SU3F[I1, I3, k1] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*SU3F[I2, I3, k1] - 
    3*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I1, k1]*SU3F[I2, I3, k1] - 
    4*CouplingConstant[ChPTW3[2], 1]*SUNDelta[6, I3]*SUNDelta[I1, I2] + 
    2*CouplingConstant[ChPTW3[2], 1]*SUNDelta[6, I2]*SUNDelta[I1, I3] + 
    2*CouplingConstant[ChPTW3[2], 1]*SUNDelta[6, I1]*SUNDelta[I2, I3])/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(12*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*SU3D[I1, I2, k1] + 
    12*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*SU3D[I1, I3, k1] + 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*SU3D[6, I2, k2]*
     SU3D[I1, k1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*
     SU3D[6, I3, k2]*SU3D[I1, k1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[6, I3, k1]*SU3D[8, I2, k2]*SU3D[I1, k1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*SU3D[8, I3, k2]*
     SU3D[I1, k1, k2] + 12*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*
     SU3D[I2, I3, k1] + 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*
     SU3D[6, I1, k2]*SU3D[I2, k1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I1, k1]*SU3D[6, I3, k2]*SU3D[I2, k1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*SU3D[8, I1, k2]*
     SU3D[I2, k1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I1, k1]*SU3D[8, I3, k2]*SU3D[I2, k1, k2] + 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*SU3D[6, I1, k2]*
     SU3D[I3, k1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*
     SU3D[6, I2, k2]*SU3D[I3, k1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[6, I2, k1]*SU3D[8, I1, k2]*SU3D[I3, k1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3D[8, I2, k2]*
     SU3D[I3, k1, k2] - (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*
     SU3D[I2, k1, k2]*SU3F[3, I1, k2] - (9*I)*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, k1]*SU3D[I3, k1, k2]*SU3F[3, I1, k2] - 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[3, I2, k2] - (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*
     SU3D[I3, k1, k2]*SU3F[3, I2, k2] - (9*I)*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3F[3, I3, k2] - 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*
     SU3F[3, I3, k2] + (12*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k1] + (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*
     SU3D[I2, k1, k2]*SU3F[6, I1, k2] + (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[8, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2] + (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*
     SU3D[I3, k1, k2]*SU3F[6, I1, k2] + (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[8, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*SU3D[I3, k1, k2]*
     SU3F[3, I2, k1]*SU3F[6, I1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*
     SU3D[I2, k1, k2]*SU3F[3, I3, k1]*SU3F[6, I1, k2] + 
    (12*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[I1, I3, k1]*SU3F[6, I2, k1] + 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[I3, k1, k2]*SU3F[3, I1, k2]*
     SU3F[6, I2, k1] + (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*
     SU3D[I1, k1, k2]*SU3F[6, I2, k2] + (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[8, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[6, I2, k2] + (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*
     SU3D[I3, k1, k2]*SU3F[6, I2, k2] + (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[8, I1, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I2, k2] + 9*CouplingConstant[ChPTW3[2], 2]*SU3D[I1, k1, k2]*
     SU3F[3, I3, k1]*SU3F[6, I2, k2] + (12*I)*CouplingConstant[ChPTW3[2], 2]*
     SU3D[I1, I2, k1]*SU3F[6, I3, k1] + 9*CouplingConstant[ChPTW3[2], 2]*
     SU3D[I2, k1, k2]*SU3F[3, I1, k2]*SU3F[6, I3, k1] + 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[I1, k1, k2]*SU3F[3, I2, k2]*
     SU3F[6, I3, k1] + (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*
     SU3D[I1, k1, k2]*SU3F[6, I3, k2] + (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[8, I2, k1]*SU3D[I1, k1, k2]*
     SU3F[6, I3, k2] + (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*
     SU3D[I2, k1, k2]*SU3F[6, I3, k2] + (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[8, I1, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I3, k2] - (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I3, k1]*SU3D[I2, k1, k2]*SU3F[8, I1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*
     SU3D[I3, k1, k2]*SU3F[8, I1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[I3, k1, k2]*SU3F[6, I2, k1]*SU3F[8, I1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[I2, k1, k2]*SU3F[6, I3, k1]*
     SU3F[8, I1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I2, k1] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*
     SU3D[I1, k1, k2]*SU3F[8, I2, k2] - (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3D[I3, k1, k2]*
     SU3F[8, I2, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[I1, k1, k2]*SU3F[6, I3, k1]*SU3F[8, I2, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*
     SU3F[8, I3, k1] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[8, I3, k1] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*
     SU3D[I1, k1, k2]*SU3F[8, I3, k2] - (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*
     SU3F[8, I3, k2] + (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*
     SU3D[6, I2, k2]*SU3F[I1, k1, k2] + (9*I)*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I2, k1]*SU3D[6, I3, k2]*SU3F[I1, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*
     SU3D[8, I2, k2]*SU3F[I1, k1, k2] - (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*SU3D[8, I3, k2]*
     SU3F[I1, k1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*
     SU3F[3, I2, k2]*SU3F[I1, k1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, k1]*SU3F[3, I3, k2]*SU3F[I1, k1, k2] - 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[8, I3, k1]*SU3F[6, I2, k2]*SU3F[I1, k1, k2] + 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I3, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*
     SU3F[6, I3, k2]*SU3F[I1, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I2, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] + 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I2, k1]*SU3F[6, I3, k2]*
     SU3F[I1, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I3, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I3, k1]*
     SU3F[8, I2, k2]*SU3F[I1, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[6, I2, k1]*SU3F[8, I3, k2]*SU3F[I1, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I2, k1]*
     SU3F[8, I3, k2]*SU3F[I1, k1, k2] + (9*I)*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I3, k1]*SU3D[6, I1, k2]*SU3F[I2, k1, k2] + 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*SU3D[6, I3, k2]*
     SU3F[I2, k1, k2] - (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I3, k1]*SU3D[8, I1, k2]*SU3F[I2, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*
     SU3D[8, I3, k2]*SU3F[I2, k1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I3, k1]*SU3F[3, I1, k2]*SU3F[I2, k1, k2] - 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3F[3, I3, k2]*
     SU3F[I2, k1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*
     SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] + 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*
     SU3F[6, I3, k2]*SU3F[I2, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I1, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2] + 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I1, k1]*SU3F[6, I3, k2]*
     SU3F[I2, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I3, k1]*SU3F[8, I1, k2]*SU3F[I2, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I3, k1]*
     SU3F[8, I1, k2]*SU3F[I2, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[6, I1, k1]*SU3F[8, I3, k2]*SU3F[I2, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I1, k1]*
     SU3F[8, I3, k2]*SU3F[I2, k1, k2] + (9*I)*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I2, k1]*SU3D[6, I1, k2]*SU3F[I3, k1, k2] + 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*SU3D[6, I2, k2]*
     SU3F[I3, k1, k2] - (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, k1]*SU3D[8, I1, k2]*SU3F[I3, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*
     SU3D[8, I2, k2]*SU3F[I3, k1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, k1]*SU3F[3, I1, k2]*SU3F[I3, k1, k2] - 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3F[3, I2, k2]*
     SU3F[I3, k1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*
     SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] + 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*
     SU3F[6, I2, k2]*SU3F[I3, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I1, k1]*SU3F[6, I2, k2]*SU3F[I3, k1, k2] + 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I1, k1]*SU3F[6, I2, k2]*
     SU3F[I3, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, k1]*SU3F[8, I1, k2]*SU3F[I3, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I2, k1]*
     SU3F[8, I1, k2]*SU3F[I3, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[6, I1, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I1, k1]*
     SU3F[8, I2, k2]*SU3F[I3, k1, k2] + 12*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, I3]*SUNDelta[3, I1] + 12*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I1, I3]*SUNDelta[3, I2] + 12*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I1, I2]*SUNDelta[3, I3] + 12*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I2, I3]*SUNDelta[6, I1] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I2, I3]*SUNDelta[6, I1] + 12*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I1, I3]*SUNDelta[6, I2] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I1, I3]*SUNDelta[6, I2] + 12*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I1, I2]*SUNDelta[6, I3] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I1, I2]*SUNDelta[6, I3] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, I3]*
     SUNDelta[8, I1] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I1, I3]*SUNDelta[8, I2] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[6, I1, I2]*SUNDelta[8, I3] + 8*CouplingConstant[ChPTW3[2], 2]*
     SUNDelta[6, I3]*SUNDelta[I1, I2] + 8*CouplingConstant[ChPTW3[2], 2]*
     SUNDelta[6, I2]*SUNDelta[I1, I3] + 8*CouplingConstant[ChPTW3[2], 2]*
     SUNDelta[6, I1]*SUNDelta[I2, I3])/
   (27*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(-2*(3*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*SU3D[I1, I2, k1] + 
     (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[7, I3, k1]*SU3D[I1, I2, k1] + 
     3*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*SU3D[I1, I3, k1] + 
     (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[7, I2, k1]*SU3D[I1, I3, k1] + 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*SU3D[8, I2, k2]*
      SU3D[I1, k1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[6, I2, k1]*SU3D[8, I3, k2]*SU3D[I1, k1, k2] + 
     3*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3D[I2, I3, k1] + 
     (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[7, I1, k1]*SU3D[I2, I3, k1] + 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*SU3D[8, I1, k2]*
      SU3D[I2, k1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[6, I1, k1]*SU3D[8, I3, k2]*SU3D[I2, k1, k2] + 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*SU3D[8, I1, k2]*
      SU3D[I3, k1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[6, I1, k1]*SU3D[8, I2, k2]*SU3D[I3, k1, k2] + 
     (3*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[I2, I3, k1]*SU3F[6, I1, k1] + 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[8, I3, k1]*
      SU3D[I2, k1, k2]*SU3F[6, I1, k2] + (3*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 2]*SU3D[8, I2, k1]*SU3D[I3, k1, k2]*
      SU3F[6, I1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[I1, I3, k1]*
      SU3F[6, I2, k1] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[8, I3, k1]*SU3D[I1, k1, k2]*SU3F[6, I2, k2] + 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[8, I1, k1]*
      SU3D[I3, k1, k2]*SU3F[6, I2, k2] + (3*I)*CouplingConstant[ChPTW3[2], 2]*
      SU3D[I1, I2, k1]*SU3F[6, I3, k1] + (3*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 2]*SU3D[8, I2, k1]*SU3D[I1, k1, k2]*
      SU3F[6, I3, k2] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[8, I1, k1]*SU3D[I2, k1, k2]*SU3F[6, I3, k2] - 
     9*CouplingConstant[ChPTW3[2], 2]*SU3D[I2, I3, k1]*SU3F[7, I1, k1] - 
     9*CouplingConstant[ChPTW3[2], 2]*SU3D[I1, I3, k1]*SU3F[7, I2, k1] - 
     9*CouplingConstant[ChPTW3[2], 2]*SU3D[I1, I2, k1]*SU3F[7, I3, k1] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*
      SU3D[I2, k1, k2]*SU3F[8, I1, k2] - (3*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*SU3D[I3, k1, k2]*
      SU3F[8, I1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[I3, k1, k2]*SU3F[6, I2, k1]*SU3F[8, I1, k2] + 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[I2, k1, k2]*
      SU3F[6, I3, k1]*SU3F[8, I1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
       2]*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I2, k1] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*
      SU3D[I1, k1, k2]*SU3F[8, I2, k2] - (3*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3D[I3, k1, k2]*
      SU3F[8, I2, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[I1, k1, k2]*SU3F[6, I3, k1]*SU3F[8, I2, k2] + 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[I2, k1, k2]*
      SU3F[6, I1, k2]*SU3F[8, I3, k1] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
       2]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[8, I3, k1] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*
      SU3D[I1, k1, k2]*SU3F[8, I3, k2] - (3*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*
      SU3F[8, I3, k2] - (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[6, I3, k1]*SU3D[8, I2, k2]*SU3F[I1, k1, k2] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*
      SU3D[8, I3, k2]*SU3F[I1, k1, k2] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[8, I3, k1]*SU3F[6, I2, k2]*
      SU3F[I1, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[8, I2, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*SU3F[8, I2, k2]*
      SU3F[I1, k1, k2] - (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3F[6, I3, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*SU3F[8, I3, k2]*
      SU3F[I1, k1, k2] - (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3F[6, I2, k1]*SU3F[8, I3, k2]*SU3F[I1, k1, k2] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*
      SU3D[8, I1, k2]*SU3F[I2, k1, k2] - (3*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3D[8, I3, k2]*
      SU3F[I2, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[8, I1, k1]*SU3F[6, I3, k2]*
      SU3F[I2, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[6, I3, k1]*SU3F[8, I1, k2]*SU3F[I2, k1, k2] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I3, k1]*
      SU3F[8, I1, k2]*SU3F[I2, k1, k2] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3F[8, I3, k2]*
      SU3F[I2, k1, k2] - (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3F[6, I1, k1]*SU3F[8, I3, k2]*SU3F[I2, k1, k2] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*
      SU3D[8, I1, k2]*SU3F[I3, k1, k2] - (3*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3D[8, I2, k2]*
      SU3F[I3, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[8, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[8, I1, k1]*SU3F[6, I2, k2]*
      SU3F[I3, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[6, I2, k1]*SU3F[8, I1, k2]*SU3F[I3, k1, k2] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I2, k1]*
      SU3F[8, I1, k2]*SU3F[I3, k1, k2] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3F[8, I2, k2]*
      SU3F[I3, k1, k2] - (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3F[6, I1, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] + 
     4*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[8, I2, I3]*
      SUNDelta[6, I1] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[8, I1, I3]*SUNDelta[6, I2] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
       2]*SU3D[8, I1, I2]*SUNDelta[6, I3] + 
     4*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, I3]*
      SUNDelta[8, I1] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
      SU3D[6, I1, I3]*SUNDelta[8, I2] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
       2]*SU3D[6, I1, I2]*SUNDelta[8, I3] + 2*CouplingConstant[ChPTW3[2], 2]*
      SUNDelta[6, I3]*SUNDelta[I1, I2] + (6*I)*CouplingConstant[ChPTW3[2], 2]*
      SUNDelta[7, I3]*SUNDelta[I1, I2] + 2*CouplingConstant[ChPTW3[2], 2]*
      SUNDelta[6, I2]*SUNDelta[I1, I3] + (6*I)*CouplingConstant[ChPTW3[2], 2]*
      SUNDelta[7, I2]*SUNDelta[I1, I3] + 2*CouplingConstant[ChPTW3[2], 2]*
      SUNDelta[6, I1]*SUNDelta[I2, I3] + (6*I)*CouplingConstant[ChPTW3[2], 2]*
      SUNDelta[7, I1]*SUNDelta[I2, I3]))/
   (27*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(-6*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*SU3D[I1, I2, k1] + 
    (18*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[7, I3, k1]*SU3D[I1, I2, k1] - 
    6*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*SU3D[I1, I3, k1] + 
    (18*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[7, I2, k1]*SU3D[I1, I3, k1] - 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*SU3D[6, I2, k2]*
     SU3D[I1, k1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*
     SU3D[6, I3, k2]*SU3D[I1, k1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[6, I3, k1]*SU3D[8, I2, k2]*SU3D[I1, k1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*SU3D[8, I3, k2]*
     SU3D[I1, k1, k2] - 6*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*
     SU3D[I2, I3, k1] + (18*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[7, I1, k1]*
     SU3D[I2, I3, k1] - 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*
     SU3D[6, I1, k2]*SU3D[I2, k1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I1, k1]*SU3D[6, I3, k2]*SU3D[I2, k1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*SU3D[8, I1, k2]*
     SU3D[I2, k1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I1, k1]*SU3D[8, I3, k2]*SU3D[I2, k1, k2] - 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*SU3D[6, I1, k2]*
     SU3D[I3, k1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*
     SU3D[6, I2, k2]*SU3D[I3, k1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[6, I2, k1]*SU3D[8, I1, k2]*SU3D[I3, k1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3D[8, I2, k2]*
     SU3D[I3, k1, k2] + (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*
     SU3D[I2, k1, k2]*SU3F[3, I1, k2] + (9*I)*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, k1]*SU3D[I3, k1, k2]*SU3F[3, I1, k2] + 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[3, I2, k2] + (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*
     SU3D[I3, k1, k2]*SU3F[3, I2, k2] + (9*I)*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3F[3, I3, k2] + 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*
     SU3F[3, I3, k2] - (6*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k1] - (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*
     SU3D[I2, k1, k2]*SU3F[6, I1, k2] + (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[8, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2] - (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*
     SU3D[I3, k1, k2]*SU3F[6, I1, k2] + (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[8, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*SU3D[I3, k1, k2]*
     SU3F[3, I2, k1]*SU3F[6, I1, k2] - 9*CouplingConstant[ChPTW3[2], 2]*
     SU3D[I2, k1, k2]*SU3F[3, I3, k1]*SU3F[6, I1, k2] - 
    (6*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[I1, I3, k1]*SU3F[6, I2, k1] - 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[I3, k1, k2]*SU3F[3, I1, k2]*
     SU3F[6, I2, k1] - (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*
     SU3D[I1, k1, k2]*SU3F[6, I2, k2] + (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[8, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[6, I2, k2] - (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*
     SU3D[I3, k1, k2]*SU3F[6, I2, k2] + (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[8, I1, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I2, k2] - 9*CouplingConstant[ChPTW3[2], 2]*SU3D[I1, k1, k2]*
     SU3F[3, I3, k1]*SU3F[6, I2, k2] - (6*I)*CouplingConstant[ChPTW3[2], 2]*
     SU3D[I1, I2, k1]*SU3F[6, I3, k1] - 9*CouplingConstant[ChPTW3[2], 2]*
     SU3D[I2, k1, k2]*SU3F[3, I1, k2]*SU3F[6, I3, k1] - 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[I1, k1, k2]*SU3F[3, I2, k2]*
     SU3F[6, I3, k1] - (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*
     SU3D[I1, k1, k2]*SU3F[6, I3, k2] + (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[8, I2, k1]*SU3D[I1, k1, k2]*
     SU3F[6, I3, k2] - (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*
     SU3D[I2, k1, k2]*SU3F[6, I3, k2] + (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[8, I1, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I3, k2] - 18*CouplingConstant[ChPTW3[2], 2]*SU3D[I2, I3, k1]*
     SU3F[7, I1, k1] - 18*CouplingConstant[ChPTW3[2], 2]*SU3D[I1, I3, k1]*
     SU3F[7, I2, k1] - 18*CouplingConstant[ChPTW3[2], 2]*SU3D[I1, I2, k1]*
     SU3F[7, I3, k1] - (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I3, k1]*SU3D[I2, k1, k2]*SU3F[8, I1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*
     SU3D[I3, k1, k2]*SU3F[8, I1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[I3, k1, k2]*SU3F[6, I2, k1]*SU3F[8, I1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[I2, k1, k2]*SU3F[6, I3, k1]*
     SU3F[8, I1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I2, k1] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*
     SU3D[I1, k1, k2]*SU3F[8, I2, k2] - (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3D[I3, k1, k2]*
     SU3F[8, I2, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[I1, k1, k2]*SU3F[6, I3, k1]*SU3F[8, I2, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*
     SU3F[8, I3, k1] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[8, I3, k1] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*
     SU3D[I1, k1, k2]*SU3F[8, I3, k2] - (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*
     SU3F[8, I3, k2] - (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*
     SU3D[6, I2, k2]*SU3F[I1, k1, k2] - (9*I)*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I2, k1]*SU3D[6, I3, k2]*SU3F[I1, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*
     SU3D[8, I2, k2]*SU3F[I1, k1, k2] - (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*SU3D[8, I3, k2]*
     SU3F[I1, k1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I3, k1]*
     SU3F[3, I2, k2]*SU3F[I1, k1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, k1]*SU3F[3, I3, k2]*SU3F[I1, k1, k2] + 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[8, I3, k1]*SU3F[6, I2, k2]*SU3F[I1, k1, k2] - 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I3, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*
     SU3F[6, I3, k2]*SU3F[I1, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I2, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] - 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I2, k1]*SU3F[6, I3, k2]*
     SU3F[I1, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I3, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I3, k1]*
     SU3F[8, I2, k2]*SU3F[I1, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[6, I2, k1]*SU3F[8, I3, k2]*SU3F[I1, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I2, k1]*
     SU3F[8, I3, k2]*SU3F[I1, k1, k2] - (9*I)*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I3, k1]*SU3D[6, I1, k2]*SU3F[I2, k1, k2] - 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*SU3D[6, I3, k2]*
     SU3F[I2, k1, k2] - (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I3, k1]*SU3D[8, I1, k2]*SU3F[I2, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*
     SU3D[8, I3, k2]*SU3F[I2, k1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I3, k1]*SU3F[3, I1, k2]*SU3F[I2, k1, k2] + 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3F[3, I3, k2]*
     SU3F[I2, k1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I3, k1]*
     SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*
     SU3F[6, I3, k2]*SU3F[I2, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I1, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2] - 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I1, k1]*SU3F[6, I3, k2]*
     SU3F[I2, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I3, k1]*SU3F[8, I1, k2]*SU3F[I2, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I3, k1]*
     SU3F[8, I1, k2]*SU3F[I2, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[6, I1, k1]*SU3F[8, I3, k2]*SU3F[I2, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I1, k1]*
     SU3F[8, I3, k2]*SU3F[I2, k1, k2] - (9*I)*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I2, k1]*SU3D[6, I1, k2]*SU3F[I3, k1, k2] - 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*SU3D[6, I2, k2]*
     SU3F[I3, k1, k2] - (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, k1]*SU3D[8, I1, k2]*SU3F[I3, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*
     SU3D[8, I2, k2]*SU3F[I3, k1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, k1]*SU3F[3, I1, k2]*SU3F[I3, k1, k2] + 
    9*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*SU3F[3, I2, k2]*
     SU3F[I3, k1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*
     SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] + 9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*
     SU3F[6, I2, k2]*SU3F[I3, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I1, k1]*SU3F[6, I2, k2]*SU3F[I3, k1, k2] - 
    (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I1, k1]*SU3F[6, I2, k2]*
     SU3F[I3, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, k1]*SU3F[8, I1, k2]*SU3F[I3, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I2, k1]*
     SU3F[8, I1, k2]*SU3F[I3, k1, k2] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[6, I1, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3F[6, I1, k1]*
     SU3F[8, I2, k2]*SU3F[I3, k1, k2] - 12*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I2, I3]*SUNDelta[3, I1] - 12*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I1, I3]*SUNDelta[3, I2] - 12*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I1, I2]*SUNDelta[3, I3] - 12*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I2, I3]*SUNDelta[6, I1] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I2, I3]*SUNDelta[6, I1] - 12*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I1, I3]*SUNDelta[6, I2] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I1, I3]*SUNDelta[6, I2] - 12*CouplingConstant[ChPTW3[2], 2]*
     SU3D[3, I1, I2]*SUNDelta[6, I3] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[8, I1, I2]*SUNDelta[6, I3] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, I3]*
     SUNDelta[8, I1] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
     SU3D[6, I1, I3]*SUNDelta[8, I2] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      2]*SU3D[6, I1, I2]*SUNDelta[8, I3] - 4*CouplingConstant[ChPTW3[2], 2]*
     SUNDelta[6, I3]*SUNDelta[I1, I2] + (12*I)*CouplingConstant[ChPTW3[2], 2]*
     SUNDelta[7, I3]*SUNDelta[I1, I2] - 4*CouplingConstant[ChPTW3[2], 2]*
     SUNDelta[6, I2]*SUNDelta[I1, I3] + (12*I)*CouplingConstant[ChPTW3[2], 2]*
     SUNDelta[7, I2]*SUNDelta[I1, I3] - 4*CouplingConstant[ChPTW3[2], 2]*
     SUNDelta[6, I1]*SUNDelta[I2, I3] + (12*I)*CouplingConstant[ChPTW3[2], 2]*
     SUNDelta[7, I1]*SUNDelta[I2, I3])/
   (27*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}}
