{{((-4*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, I2])/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2},
{((-6*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, I2] -
	(9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*SU3D[6, I1, k1] -
	(9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*SU3D[6, I2, k1] +
	18*CouplingConstant[ChPTW3[2], 2]*SU3D[7, I1, I2] +
	(3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*
	SU3D[8, I1, k1] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
	SU3D[6, I1, k1]*SU3D[8, I2, k1] - 9*CouplingConstant[ChPTW3[2], 2]*
	SU3D[6, I2, k1]*SU3F[3, I1, k1] - 9*CouplingConstant[ChPTW3[2], 2]*
	SU3D[6, I1, k1]*SU3F[3, I2, k1] + 9*CouplingConstant[ChPTW3[2], 2]*
	SU3D[3, I2, k1]*SU3F[6, I1, k1] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2],
	2]*SU3D[8, I2, k1]*SU3F[6, I1, k1] -
	(9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I2, k1]*SU3F[6, I1, k1] +
	9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*SU3F[6, I2, k1] -
	3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[8, I1, k1]*
	SU3F[6, I2, k1] - (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I1, k1]*
	SU3F[6, I2, k1] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
	SU3D[6, I2, k1]*SU3F[8, I1, k1] + (3*I)*Sqrt[3]*
	CouplingConstant[ChPTW3[2], 2]*SU3F[6, I2, k1]*SU3F[8, I1, k1] +
	3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*
	SU3F[8, I2, k1] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
	SU3F[6, I1, k1]*SU3F[8, I2, k1] - (6*I)*CouplingConstant[ChPTW3[2], 2]*
	SUNDelta[3, I2]*SUNDelta[6, I1] - (6*I)*CouplingConstant[ChPTW3[2], 2]*
	SUNDelta[3, I1]*SUNDelta[6, I2] + (2*I)*Sqrt[3]*
	CouplingConstant[ChPTW3[2], 2]*SUNDelta[6, I2]*SUNDelta[8, I1] +
	(2*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SUNDelta[6, I1]*
	SUNDelta[8, I2])/(9*DecayConstant[PseudoScalar[1],
	RenormalizationState[0]]^2)},
{((-24*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, I2] +
	(9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I2, k1]*SU3D[6, I1, k1] +
	(9*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*SU3D[6, I2, k1] +
	(3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*
	SU3D[8, I1, k1] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
	SU3D[6, I1, k1]*SU3D[8, I2, k1] + 9*CouplingConstant[ChPTW3[2], 2]*
	SU3D[6, I2, k1]*SU3F[3, I1, k1] + 9*CouplingConstant[ChPTW3[2], 2]*
	SU3D[6, I1, k1]*SU3F[3, I2, k1] - 9*CouplingConstant[ChPTW3[2], 2]*
	SU3D[3, I2, k1]*SU3F[6, I1, k1] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2],
	2]*SU3D[8, I2, k1]*SU3F[6, I1, k1] +
	(9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I2, k1]*SU3F[6, I1, k1] -
	9*CouplingConstant[ChPTW3[2], 2]*SU3D[3, I1, k1]*SU3F[6, I2, k1] -
	3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[8, I1, k1]*
	SU3F[6, I2, k1] + (9*I)*CouplingConstant[ChPTW3[2], 2]*SU3F[3, I1, k1]*
	SU3F[6, I2, k1] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
	SU3D[6, I2, k1]*SU3F[8, I1, k1] + (3*I)*Sqrt[3]*
	CouplingConstant[ChPTW3[2], 2]*SU3F[6, I2, k1]*SU3F[8, I1, k1] +
	3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*
	SU3F[8, I2, k1] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
	SU3F[6, I1, k1]*SU3F[8, I2, k1] + (6*I)*CouplingConstant[ChPTW3[2], 2]*
	SUNDelta[3, I2]*SUNDelta[6, I1] + (6*I)*CouplingConstant[ChPTW3[2], 2]*
	SUNDelta[3, I1]*SUNDelta[6, I2] + (2*I)*Sqrt[3]*
	CouplingConstant[ChPTW3[2], 2]*SUNDelta[6, I2]*SUNDelta[8, I1] +
	(2*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SUNDelta[6, I1]*
	SUNDelta[8, I2])/(9*DecayConstant[PseudoScalar[1],
	RenormalizationState[0]]^2)},
{(2*((-3*I)*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, I2] -
	9*CouplingConstant[ChPTW3[2], 2]*SU3D[7, I1, I2] -
	(3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I2, k1]*
	SU3D[8, I1, k1] - (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
	SU3D[6, I1, k1]*SU3D[8, I2, k1] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2],
	2]*SU3D[8, I2, k1]*SU3F[6, I1, k1] +
	3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[8, I1, k1]*
	SU3F[6, I2, k1] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
	SU3D[6, I2, k1]*SU3F[8, I1, k1] - (3*I)*Sqrt[3]*
	CouplingConstant[ChPTW3[2], 2]*SU3F[6, I2, k1]*SU3F[8, I1, k1] -
	3*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SU3D[6, I1, k1]*
	SU3F[8, I2, k1] - (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*
	SU3F[6, I1, k1]*SU3F[8, I2, k1] - (2*I)*Sqrt[3]*
	CouplingConstant[ChPTW3[2], 2]*SUNDelta[6, I2]*SUNDelta[8, I1] -
	(2*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 2]*SUNDelta[6, I1]*
	SUNDelta[8, I2]))/(9*DecayConstant[PseudoScalar[1],
	RenormalizationState[0]]^2)}}
