{{((-2*I)/9)*CouplingConstant[ChPTW3[2], 2]*
   (6*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, I4, k2] + 
    3*SU3D[6, I2, k1]*SU3D[I1, I4, k2]*SU3D[I3, k1, k2] + 
    6*SU3D[6, I1, k1]*SU3D[I2, I4, k2]*SU3D[I3, k1, k2] + 
    3*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3D[I4, k1, k2] + 
    6*SU3D[6, I1, k1]*SU3D[I2, I3, k2]*SU3D[I4, k1, k2] + 
    (6*I)*SU3D[I2, k1, k2]*SU3D[I3, I4, k1]*SU3F[6, I1, k2] + 
    (6*I)*SU3D[I2, I4, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] + 
    (6*I)*SU3D[I2, I3, k1]*SU3D[I4, k1, k2]*SU3F[6, I1, k2] + 
    (3*I)*SU3D[I1, I4, k1]*SU3D[I3, k1, k2]*SU3F[6, I2, k2] + 
    (3*I)*SU3D[I1, I3, k1]*SU3D[I4, k1, k2]*SU3F[6, I2, k2] + 
    (3*I)*SU3D[I1, I4, k1]*SU3D[I2, k1, k2]*SU3F[6, I3, k2] + 
    (3*I)*SU3D[I1, I2, k1]*SU3D[I4, k1, k2]*SU3F[6, I3, k2] + 
    (3*I)*SU3D[I1, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I4, k2] + 
    (3*I)*SU3D[I1, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I4, k2] + 
    3*SU3D[I4, k1, k2]*SU3F[6, I3, k2]*SU3F[I1, I2, k1] + 
    3*SU3D[I3, k1, k2]*SU3F[6, I4, k2]*SU3F[I1, I2, k1] + 
    3*SU3D[I4, k1, k2]*SU3F[6, I2, k2]*SU3F[I1, I3, k1] + 
    3*SU3D[I2, k1, k2]*SU3F[6, I4, k2]*SU3F[I1, I3, k1] - 
    (3*I)*SU3D[6, I2, k1]*SU3D[I4, k1, k2]*SU3F[I1, I3, k2] + 
    3*SU3D[I3, k1, k2]*SU3F[6, I2, k2]*SU3F[I1, I4, k1] + 
    3*SU3D[I2, k1, k2]*SU3F[6, I3, k2]*SU3F[I1, I4, k1] - 
    (3*I)*SU3D[6, I2, k1]*SU3D[I3, k1, k2]*SU3F[I1, I4, k2] - 
    (6*I)*SU3D[6, I1, k1]*SU3D[I3, I4, k2]*SU3F[I2, k1, k2] - 
    6*SU3D[I3, I4, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 
    3*SU3D[I1, I4, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2] - 
    3*SU3D[I1, I3, k1]*SU3F[6, I4, k2]*SU3F[I2, k1, k2] - 
    (3*I)*SU3F[6, I4, k1]*SU3F[I1, I3, k2]*SU3F[I2, k1, k2] - 
    (3*I)*SU3F[6, I3, k1]*SU3F[I1, I4, k2]*SU3F[I2, k1, k2] - 
    (3*I)*SU3D[6, I2, k1]*SU3D[I1, I4, k2]*SU3F[I3, k1, k2] - 
    (6*I)*SU3D[6, I1, k1]*SU3D[I2, I4, k2]*SU3F[I3, k1, k2] - 
    6*SU3D[I2, I4, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 
    3*SU3D[I1, I4, k1]*SU3F[6, I2, k2]*SU3F[I3, k1, k2] - 
    3*SU3D[I1, I2, k1]*SU3F[6, I4, k2]*SU3F[I3, k1, k2] - 
    (3*I)*SU3F[6, I4, k1]*SU3F[I1, I2, k2]*SU3F[I3, k1, k2] - 
    3*SU3D[6, I2, k1]*SU3F[I1, I4, k2]*SU3F[I3, k1, k2] - 
    (3*I)*SU3F[6, I2, k1]*SU3F[I1, I4, k2]*SU3F[I3, k1, k2] - 
    (3*I)*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3F[I4, k1, k2] - 
    (6*I)*SU3D[6, I1, k1]*SU3D[I2, I3, k2]*SU3F[I4, k1, k2] - 
    6*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*SU3F[I4, k1, k2] - 
    3*SU3D[I1, I3, k1]*SU3F[6, I2, k2]*SU3F[I4, k1, k2] - 
    3*SU3D[I1, I2, k1]*SU3F[6, I3, k2]*SU3F[I4, k1, k2] - 
    (3*I)*SU3F[6, I3, k1]*SU3F[I1, I2, k2]*SU3F[I4, k1, k2] - 
    3*SU3D[6, I2, k1]*SU3F[I1, I3, k2]*SU3F[I4, k1, k2] - 
    (3*I)*SU3F[6, I2, k1]*SU3F[I1, I3, k2]*SU3F[I4, k1, k2] + 
    12*SU3D[6, I2, k1]*SU3D[I3, I4, k1]*SUNDelta[0, I1] + 
    (12*I)*SU3D[I3, I4, k1]*SU3F[6, I2, k1]*SUNDelta[0, I1] + 
    (12*I)*SU3D[I2, I4, k1]*SU3F[6, I3, k1]*SUNDelta[0, I1] + 
    (12*I)*SU3D[I2, I3, k1]*SU3F[6, I4, k1]*SUNDelta[0, I1] + 
    3*SU3D[6, I4, k1]*((-I)*SU3D[I3, k1, k2]*SU3F[I1, I2, k2] - 
      I*SU3D[I2, k1, k2]*SU3F[I1, I3, k2] + SU3D[I1, I3, k2]*
       (SU3D[I2, k1, k2] - I*SU3F[I2, k1, k2]) - SU3F[I1, I3, k2]*
       SU3F[I2, k1, k2] + SU3D[I1, I2, k2]*(SU3D[I3, k1, k2] - 
        I*SU3F[I3, k1, k2]) - SU3F[I1, I2, k2]*SU3F[I3, k1, k2] + 
      4*SU3D[I2, I3, k1]*SUNDelta[0, I1]) + 3*SU3D[6, I3, k1]*
     ((-I)*SU3D[I4, k1, k2]*SU3F[I1, I2, k2] - I*SU3D[I2, k1, k2]*
       SU3F[I1, I4, k2] + SU3D[I1, I4, k2]*(SU3D[I2, k1, k2] - 
        I*SU3F[I2, k1, k2]) - SU3F[I1, I4, k2]*SU3F[I2, k1, k2] + 
      SU3D[I1, I2, k2]*(SU3D[I4, k1, k2] - I*SU3F[I4, k1, k2]) - 
      SU3F[I1, I2, k2]*SU3F[I4, k1, k2] + 4*SU3D[I2, I4, k1]*
       SUNDelta[0, I1]) + 12*SU3D[I2, I3, I4]*SUNDelta[6, I1] + 
    4*SU3D[I1, I3, I4]*SUNDelta[6, I2] + 4*SU3D[I1, I2, I4]*SUNDelta[6, I3] + 
    4*SU3D[I1, I2, I3]*SUNDelta[6, I4] + 4*SU3D[6, I3, I4]*SUNDelta[I1, I2] + 
    4*SU3D[6, I2, I4]*SUNDelta[I1, I3] + 4*SU3D[6, I2, I3]*SUNDelta[I1, I4] + 
    4*SU3D[6, I1, I4]*SUNDelta[I2, I3] + (4*I)*SU3F[6, I1, I4]*
     SUNDelta[I2, I3] + 8*SUNDelta[0, I1]*SUNDelta[6, I4]*SUNDelta[I2, I3] + 
    4*SU3D[6, I1, I3]*SUNDelta[I2, I4] + (4*I)*SU3F[6, I1, I3]*
     SUNDelta[I2, I4] + 8*SUNDelta[0, I1]*SUNDelta[6, I3]*SUNDelta[I2, I4] + 
    4*SU3D[6, I1, I2]*SUNDelta[I3, I4] + (4*I)*SU3F[6, I1, I2]*
     SUNDelta[I3, I4] + 8*SUNDelta[0, I1]*SUNDelta[6, I2]*SUNDelta[I3, I4])}}
