{{((-I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/4)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/4)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4}, 
 {((-I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/4)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/4)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4}, 
 {((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/4)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/4)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4}, 
 {((-I/4)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/4)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4}, 
 {((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/4)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/4)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4}, 
 {((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/6)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/4)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/12)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/4)*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4}, 
 {((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 - ((I/24)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   ((I/24)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
    (Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/24)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   ((I/24)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
    (Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/36)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]^4 + ((I/12)*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
    (Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}}
