{{((-2*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
	QuarkCondensate[RenormalizationState[0]]*
	(2*SUNDelta[0, I1]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
	UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
	UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1],
	RenormalizationState[0]]^3},
{((-2*I)*CouplingConstant[ChPTW3[2], 1]*(CouplingConstant[ChPTW3[4], 22] +
	2*CouplingConstant[ChPTW3[4], 23])*QuarkCondensate[
	RenormalizationState[0]]*(2*SUNDelta[0, I1]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
	UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
	UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1],
	RenormalizationState[0]]^3}}
