{{(((4*I)/3)*(SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] -
	2*SUNDelta[I1, I4]*SUNDelta[I2, I3] - 2*SUNDelta[I1, I3]*
	SUNDelta[I2, I4] + SUNDelta[3, I3]*(SUNDelta[3, I4]*SUNDelta[I1, I2] +
	SUNDelta[3, I2]*SUNDelta[I1, I4] + SUNDelta[3, I1]*SUNDelta[I2, I4]) -
	2*SUNDelta[I1, I2]*SUNDelta[I3, I4] + SUNDelta[3, I2]*
	(SUNDelta[3, I4]*SUNDelta[I1, I3] + SUNDelta[3, I1]*SUNDelta[I3, I4])))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}}
