{{(-4*CouplingConstant[ChPTPhoton2[4], 9, RenormalizationState[0]]*
	SU2F[3, I1, I2])/DecayConstant[PseudoScalar[2], RenormalizationState[0]]^
	2}, {(4*CouplingConstant[ChPTPhoton2[4], 9, RenormalizationState[0]]*
	SU2F[3, I1, I2])/DecayConstant[PseudoScalar[2], RenormalizationState[0]]^
	2}, {(-8*(2*CouplingConstant[ChPTPhoton2[4], 4, RenormalizationState[0]]*
	SU2F[3, I1, I2] + CouplingConstant[ChPTPhoton2[4], 5,
	RenormalizationState[0]]*SU2F[3, I1, I2]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{(8*(2*CouplingConstant[ChPTPhoton2[4], 4, RenormalizationState[0]]*
	SU2F[3, I1, I2] + CouplingConstant[ChPTPhoton2[4], 5,
	RenormalizationState[0]]*SU2F[3, I1, I2]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}}
