{{(2*CouplingConstant[ChPTW3[2], 1]*(CouplingConstant[ChPTW3[4], 20] + 
     CouplingConstant[ChPTW3[4], 26])*UTrace1[UMatrix[UGenerator[6]]*
      UMatrix[UGenerator[I1]]*UMatrix[UGenerator[I2]]])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}, 
 {(2*CouplingConstant[ChPTW3[2], 1]*(CouplingConstant[ChPTW3[4], 20] - 
     CouplingConstant[ChPTW3[4], 26])*UTrace1[UMatrix[UGenerator[6]]*
      UMatrix[UGenerator[I1]]*UMatrix[UGenerator[I2]]])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}, 
 {(4*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 20]*
    UTrace1[UMatrix[UGenerator[6]]*UMatrix[UGenerator[I1]]*
      UMatrix[UGenerator[I2]]])/DecayConstant[PseudoScalar[1], 
     RenormalizationState[0]]^3}, 
 {(-2*CouplingConstant[ChPTW3[2], 1]*(CouplingConstant[ChPTW3[4], 24]*
      UTrace1[UMatrix[UGenerator[6]]*UMatrix[UGenerator[I1]]]*
      (3*UTrace1[UMatrix[UGenerator[3]]*UMatrix[UGenerator[I2]]] + 
       Sqrt[3]*UTrace1[UMatrix[UGenerator[8]]*UMatrix[UGenerator[I2]]]) - 
     (CouplingConstant[ChPTW3[4], 22] + 2*CouplingConstant[ChPTW3[4], 23])*
      (UTrace1[UMatrix[UGenerator[6]]*UMatrix[UGenerator[I1]]*
         UMatrix[UGenerator[I2]]] - 3*UTrace1[UMatrix[UGenerator[3]]*
          UMatrix[UGenerator[6]]*UMatrix[UGenerator[I1]]*
          UMatrix[UGenerator[I2]]] - Sqrt[3]*UTrace1[UMatrix[UGenerator[6]]*
          UMatrix[UGenerator[8]]*UMatrix[UGenerator[I1]]*
          UMatrix[UGenerator[I2]]])))/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(2*CouplingConstant[ChPTW3[2], 1]*(CouplingConstant[ChPTW3[4], 24]*
      UTrace1[UMatrix[UGenerator[6]]*UMatrix[UGenerator[I1]]]*
      (3*UTrace1[UMatrix[UGenerator[3]]*UMatrix[UGenerator[I2]]] - 
       Sqrt[3]*UTrace1[UMatrix[UGenerator[8]]*UMatrix[UGenerator[I2]]]) + 
     (CouplingConstant[ChPTW3[4], 22] + 2*CouplingConstant[ChPTW3[4], 23])*
      (UTrace1[UMatrix[UGenerator[6]]*UMatrix[UGenerator[I1]]*
         UMatrix[UGenerator[I2]]] + 3*UTrace1[UMatrix[UGenerator[3]]*
          UMatrix[UGenerator[6]]*UMatrix[UGenerator[I1]]*
          UMatrix[UGenerator[I2]]] - Sqrt[3]*UTrace1[UMatrix[UGenerator[6]]*
          UMatrix[UGenerator[8]]*UMatrix[UGenerator[I1]]*
          UMatrix[UGenerator[I2]]])))/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(2*CouplingConstant[ChPTW3[2], 1]*
    (2*Sqrt[3]*CouplingConstant[ChPTW3[4], 24]*
      UTrace1[UMatrix[UGenerator[6]]*UMatrix[UGenerator[I1]]]*
      UTrace1[UMatrix[UGenerator[8]]*UMatrix[UGenerator[I2]]] + 
     (CouplingConstant[ChPTW3[4], 22] + 2*CouplingConstant[ChPTW3[4], 23])*
      (UTrace1[UMatrix[UGenerator[6]]*UMatrix[UGenerator[I1]]*
         UMatrix[UGenerator[I2]]] + 2*Sqrt[3]*UTrace1[UMatrix[UGenerator[6]]*
          UMatrix[UGenerator[8]]*UMatrix[UGenerator[I1]]*
          UMatrix[UGenerator[I2]]])))/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}}
