{{(CouplingConstant[ChPTW3[2], 1]*SUNDelta[0, I3]*
     ((-8*I)*CouplingConstant[ChPTW3[4], 5]*
       (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]) - 
      (12*I)*CouplingConstant[ChPTW3[4], 8]*
       (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]])) + 
    CouplingConstant[ChPTW3[2], 1]*((-8*I)*CouplingConstant[ChPTW3[4], 7]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I3]]]]*UTrace1[NonCommutative[
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
      (4*I)*CouplingConstant[ChPTW3[4], 6]*
       (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]) - 
      (4*I)*CouplingConstant[ChPTW3[4], 5]*
       (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(CouplingConstant[ChPTW3[2], 1]*SUNDelta[0, I3]*
     (((8*I)/3)*CouplingConstant[ChPTW3[4], 13]*
       (3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
        Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
             UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
          UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
             UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]])) - 
      ((8*I)/3)*CouplingConstant[ChPTW3[4], 10]*
       (2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[6]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]]]]) - ((4*I)/3)*CouplingConstant[ChPTW3[4], 
        12]*(4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] - 
        6*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[6]]]] - 
        6*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
        2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) + 
      ((2*I)/3)*CouplingConstant[ChPTW3[4], 11]*
       (12*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        3*(-4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
          4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
          3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
             UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
             UMatrix[UGenerator[I2]]]] + 3*UTrace1[NonCommutative[
             UMatrix[UGenerator[3]], UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
          3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
             UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
             UMatrix[UGenerator[6]]]] + 3*UTrace1[NonCommutative[
             UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
             UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
          Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
             UMatrix[UGenerator[I2]]]] + Sqrt[3]*UTrace1[NonCommutative[
             UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
             UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
          Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
             UMatrix[UGenerator[8]]]] + Sqrt[3]*UTrace1[NonCommutative[
             UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
             UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))) + 
    CouplingConstant[ChPTW3[2], 1]*
     (((-4*I)/3)*CouplingConstant[ChPTW3[4], 13]*
       (2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[3]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[3]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[6]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]) - 
      ((2*I)/3)*CouplingConstant[ChPTW3[4], 11]*
       (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]]]]*
         (4*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
             UMatrix[UGenerator[I2]]]] - 
          2*(3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[
                UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
            3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[
                UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
            Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
                UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
              UTrace1[NonCommutative[UMatrix[UGenerator[8]], UMatrix[
                 UGenerator[I2]], UMatrix[UGenerator[I1]]]]))) - 
        2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] - 2*Sqrt[3]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]]]] - 
        6*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]]]]*(UTrace1[NonCommutative[
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
            UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
            UMatrix[UGenerator[I2]]]]) + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]]) - ((2*I)/3)*CouplingConstant[ChPTW3[4], 
        12]*(2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] + 
        4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]] + 
        4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) - 
      ((2*I)/3)*CouplingConstant[ChPTW3[4], 10]*
       (4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] + 
        4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]] + 
        4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + 
        4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(CouplingConstant[ChPTW3[2], 1]*SUNDelta[0, I3]*
     (((-8*I)/3)*CouplingConstant[ChPTW3[4], 13]*
       (3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
             UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
          UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
             UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]])) - 
      ((2*I)/3)*CouplingConstant[ChPTW3[4], 11]*
       (12*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
        4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        12*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        12*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
        9*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + 
        9*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] + 
        9*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[6]]]] + 
        9*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]]]] - 3*Sqrt[3]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] - 3*Sqrt[3]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] - 3*Sqrt[3]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]]]] - 3*Sqrt[3]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]]]]) - ((8*I)/3)*CouplingConstant[ChPTW3[4], 
        10]*(2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[6]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]]]]) - ((4*I)/3)*CouplingConstant[ChPTW3[4], 
        12]*(4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] + 
        6*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[6]]]] + 
        6*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
        2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) + 
    CouplingConstant[ChPTW3[2], 1]*
     (((-4*I)/3)*CouplingConstant[ChPTW3[4], 13]*
       (2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[3]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[3]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[6]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]) - 
      ((2*I)/3)*CouplingConstant[ChPTW3[4], 11]*
       (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]]]]*
         (4*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
             UMatrix[UGenerator[I2]]]] + 6*UTrace1[NonCommutative[
             UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
             UMatrix[UGenerator[I2]]]] + 6*UTrace1[NonCommutative[
             UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
             UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*
           UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
             UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
          2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
             UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]) - 
        2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] - 2*Sqrt[3]*
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]]]] + 
        6*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]]]]*(UTrace1[NonCommutative[
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
            UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
            UMatrix[UGenerator[I2]]]]) + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]]) - ((2*I)/3)*CouplingConstant[ChPTW3[4], 
        12]*(2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] + 
        4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]] + 
        4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) - 
      ((2*I)/3)*CouplingConstant[ChPTW3[4], 10]*
       (4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] + 
        4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]] + 
        4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + 
        4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] - 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
        Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(CouplingConstant[ChPTW3[2], 1]*SUNDelta[0, I3]*
     (((-16*I)*CouplingConstant[ChPTW3[4], 13]*
        (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
            UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
            UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]]))/Sqrt[3] - 
      ((16*I)/3)*CouplingConstant[ChPTW3[4], 10]*
       (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
        Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
            UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
            UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
          UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
            UMatrix[UGenerator[8]]]] + UTrace1[NonCommutative[
            UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) - 
      ((8*I)/3)*CouplingConstant[ChPTW3[4], 12]*
       (2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
        Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
            UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
            UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
          2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
             UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
            UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
          2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
             UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
            UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) - 
      ((4*I)/3)*CouplingConstant[ChPTW3[4], 11]*
       (4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        3*(2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
          2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
          Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
              UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
              UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
              UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
              UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
            UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[
                I1]], UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
            UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[
                I2]], UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])))) + 
    CouplingConstant[ChPTW3[2], 1]*
     (((-8*I)/3)*CouplingConstant[ChPTW3[4], 13]*
       (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
        Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
             UMatrix[UGenerator[I3]]]]*(UTrace1[NonCommutative[
              UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
              UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
              UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
              UMatrix[UGenerator[8]]]]) + 
          UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
             UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
             UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
             UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
             UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]]*
           (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[
                8]], UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
              UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
              UMatrix[UGenerator[8]]]]) + 
          UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
             UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
             UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
             UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
             UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]]*
           UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
          UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
             UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
             UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
             UMatrix[UGenerator[I2]]]])) - 
      ((2*I)/3)*CouplingConstant[ChPTW3[4], 11]*
       (4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]]]]*(UTrace1[NonCommutative[
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
          Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
              UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
            UTrace1[NonCommutative[UMatrix[UGenerator[8]], UMatrix[UGenerator[
                I2]], UMatrix[UGenerator[I1]]]])) + 
        4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]]*(UTrace1[NonCommutative[
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
            UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
            UMatrix[UGenerator[I2]]]]) + 
        3*(UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
            UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
            UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
          UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
            UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
            UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]])) - 
      ((4*I)/3)*CouplingConstant[ChPTW3[4], 12]*
       (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[I3]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]]]]) - ((4*I)/3)*CouplingConstant[ChPTW3[4], 
        10]*(2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + 
        2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I3]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[8]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I3]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I3]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[8]]]] - Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[8]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]]]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}}
