{{((4*I)/27)*(162*CouplingConstant[ChPTVirtualPhotons2[4], 24,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I2]*
	SUNDelta[3, I3]*SUNDelta[3, I4] -
	5*CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] -
	64*CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] -
	5*CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] -
	64*CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] -
	5*CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] -
	64*CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] -
	5*CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] -
	64*CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	74*CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	5*CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] -
	64*CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	74*CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	5*CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] -
	64*CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	74*CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4])},
{((4*I)*(CouplingConstant[ChPTVirtualPhotons2[4], 2,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	CouplingConstant[ChPTVirtualPhotons2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	2*CouplingConstant[ChPTVirtualPhotons2[4], 1, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4},
{((4*I)*(CouplingConstant[ChPTVirtualPhotons2[4], 2,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	2*CouplingConstant[ChPTVirtualPhotons2[4], 1, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	CouplingConstant[ChPTVirtualPhotons2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4},
{((4*I)*(2*CouplingConstant[ChPTVirtualPhotons2[4], 1,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	CouplingConstant[ChPTVirtualPhotons2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	CouplingConstant[ChPTVirtualPhotons2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4},
{(((8*I)/3)*(CouplingConstant[ChPTVirtualPhotons2[4], 3,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	CouplingConstant[ChPTVirtualPhotons2[4], 3, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	CouplingConstant[ChPTVirtualPhotons2[4], 3, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4},
{(((-2*I)/27)*(54*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SU2F[3, I1, I3]*SU2F[3, I2, I4] +
	27*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SU2F[3, I1, I3]*SU2F[3, I2, I4] +
	54*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SU2F[3, I1, I2]*SU2F[3, I3, I4] +
	27*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SU2F[3, I1, I2]*SU2F[3, I3, I4] -
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] +
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] -
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] +
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] +
	144*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I3]*
	SUNDelta[I1, I4] - 72*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I3]*
	SUNDelta[I1, I4] + 108*CouplingConstant[ChPTVirtualPhotons2[4], 12,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I4]*
	SUNDelta[I2, I3] - 20*CouplingConstant[ChPTVirtualPhotons2[4], 11,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	128*CouplingConstant[ChPTVirtualPhotons2[4], 12,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] +
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{(((-2*I)/27)*(54*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SU2F[3, I1, I3]*SU2F[3, I2, I4] +
	27*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SU2F[3, I1, I3]*SU2F[3, I2, I4] +
	54*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SU2F[3, I1, I2]*SU2F[3, I3, I4] +
	27*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SU2F[3, I1, I2]*SU2F[3, I3, I4] -
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] +
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] -
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] +
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] +
	108*CouplingConstant[ChPTVirtualPhotons2[4], 12,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I3]*
	SUNDelta[I1, I4] + 144*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I4]*
	SUNDelta[I2, I3] - 72*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I4]*
	SUNDelta[I2, I3] - 20*CouplingConstant[ChPTVirtualPhotons2[4], 11,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	128*CouplingConstant[ChPTVirtualPhotons2[4], 12,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] +
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{(((-2*I)/27)*(54*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SU2F[3, I1, I4]*SU2F[3, I2, I3] +
	27*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SU2F[3, I1, I4]*SU2F[3, I2, I3] -
	54*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SU2F[3, I1, I2]*SU2F[3, I3, I4] -
	27*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SU2F[3, I1, I2]*SU2F[3, I3, I4] -
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] +
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] +
	144*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I4]*
	SUNDelta[I1, I3] - 72*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I4]*
	SUNDelta[I1, I3] - 36*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I3]*
	SUNDelta[I1, I4] + 18*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I3]*
	SUNDelta[I1, I4] - 36*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I4]*
	SUNDelta[I2, I3] + 18*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I4]*
	SUNDelta[I2, I3] + 10*CouplingConstant[ChPTVirtualPhotons2[4], 11,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	108*CouplingConstant[ChPTVirtualPhotons2[4], 12,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I3]*
	SUNDelta[I2, I4] - 20*CouplingConstant[ChPTVirtualPhotons2[4], 11,
	RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	128*CouplingConstant[ChPTVirtualPhotons2[4], 12,
	RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{(((-2*I)/27)*(54*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SU2F[3, I1, I4]*SU2F[3, I2, I3] +
	27*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SU2F[3, I1, I4]*SU2F[3, I2, I3] -
	54*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SU2F[3, I1, I2]*SU2F[3, I3, I4] -
	27*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SU2F[3, I1, I2]*SU2F[3, I3, I4] -
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] +
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] +
	108*CouplingConstant[ChPTVirtualPhotons2[4], 12,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I4]*
	SUNDelta[I1, I3] - 36*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I3]*
	SUNDelta[I1, I4] + 18*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I3]*
	SUNDelta[I1, I4] - 36*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I4]*
	SUNDelta[I2, I3] + 18*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I4]*
	SUNDelta[I2, I3] + 10*CouplingConstant[ChPTVirtualPhotons2[4], 11,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	144*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I3]*
	SUNDelta[I2, I4] - 72*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I3]*
	SUNDelta[I2, I4] - 20*CouplingConstant[ChPTVirtualPhotons2[4], 11,
	RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	128*CouplingConstant[ChPTVirtualPhotons2[4], 12,
	RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{(((2*I)/27)*(54*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SU2F[3, I1, I4]*SU2F[3, I2, I3] +
	27*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SU2F[3, I1, I4]*SU2F[3, I2, I3] +
	54*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SU2F[3, I1, I3]*SU2F[3, I2, I4] +
	27*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SU2F[3, I1, I3]*SU2F[3, I2, I4] -
	144*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I3]*SUNDelta[3, I4]*
	SUNDelta[I1, I2] + 72*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I3]*SUNDelta[3, I4]*
	SUNDelta[I1, I2] + 36*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I4]*
	SUNDelta[I1, I3] - 18*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I4]*
	SUNDelta[I1, I3] + 36*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I3]*
	SUNDelta[I1, I4] - 18*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I3]*
	SUNDelta[I1, I4] + 36*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I4]*
	SUNDelta[I2, I3] - 18*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I4]*
	SUNDelta[I2, I3] - 10*CouplingConstant[ChPTVirtualPhotons2[4], 11,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	10*CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] -
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] -
	10*CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	10*CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	108*CouplingConstant[ChPTVirtualPhotons2[4], 12,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I2]*
	SUNDelta[I3, I4] + 20*CouplingConstant[ChPTVirtualPhotons2[4], 11,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	128*CouplingConstant[ChPTVirtualPhotons2[4], 12,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{(((2*I)/27)*(54*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SU2F[3, I1, I4]*SU2F[3, I2, I3] +
	27*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SU2F[3, I1, I4]*SU2F[3, I2, I3] +
	54*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SU2F[3, I1, I3]*SU2F[3, I2, I4] +
	27*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SU2F[3, I1, I3]*SU2F[3, I2, I4] -
	108*CouplingConstant[ChPTVirtualPhotons2[4], 12,
	RenormalizationState[0]]*SUNDelta[3, I3]*SUNDelta[3, I4]*
	SUNDelta[I1, I2] + 36*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I4]*
	SUNDelta[I1, I3] - 18*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I4]*
	SUNDelta[I1, I3] + 36*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I3]*
	SUNDelta[I1, I4] - 18*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I3]*
	SUNDelta[I1, I4] + 36*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I4]*
	SUNDelta[I2, I3] - 18*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I4]*
	SUNDelta[I2, I3] - 10*CouplingConstant[ChPTVirtualPhotons2[4], 11,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	10*CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	36*CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] -
	18*CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] -
	10*CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	10*CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	144*CouplingConstant[ChPTVirtualPhotons2[4], 13,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I2]*
	SUNDelta[I3, I4] + 72*CouplingConstant[ChPTVirtualPhotons2[4], 14,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I2]*
	SUNDelta[I3, I4] + 20*CouplingConstant[ChPTVirtualPhotons2[4], 11,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	128*CouplingConstant[ChPTVirtualPhotons2[4], 12,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{(((-4*I)/27)*(90*CouplingConstant[ChPTVirtualPhotons2[4], 16,
	RenormalizationState[0]]*SUNDelta[3, I3]*SUNDelta[3, I4]*
	SUNDelta[I1, I2] + 90*CouplingConstant[ChPTVirtualPhotons2[4], 18,
	RenormalizationState[0]]*SUNDelta[3, I3]*SUNDelta[3, I4]*
	SUNDelta[I1, I2] + 90*CouplingConstant[ChPTVirtualPhotons2[4], 16,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I4]*
	SUNDelta[I1, I3] + 90*CouplingConstant[ChPTVirtualPhotons2[4], 18,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I4]*
	SUNDelta[I1, I3] + 90*CouplingConstant[ChPTVirtualPhotons2[4], 16,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I3]*
	SUNDelta[I1, I4] + 90*CouplingConstant[ChPTVirtualPhotons2[4], 18,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[3, I3]*
	SUNDelta[I1, I4] + 90*CouplingConstant[ChPTVirtualPhotons2[4], 16,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I4]*
	SUNDelta[I2, I3] + 90*CouplingConstant[ChPTVirtualPhotons2[4], 18,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I4]*
	SUNDelta[I2, I3] - 5*CouplingConstant[ChPTVirtualPhotons2[4], 15,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	185*CouplingConstant[ChPTVirtualPhotons2[4], 16,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	CouplingConstant[ChPTVirtualPhotons2[4], 17, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	180*CouplingConstant[ChPTVirtualPhotons2[4], 18,
	RenormalizationState[0]]*SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	90*CouplingConstant[ChPTVirtualPhotons2[4], 16, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] +
	90*CouplingConstant[ChPTVirtualPhotons2[4], 18, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] -
	5*CouplingConstant[ChPTVirtualPhotons2[4], 15, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	185*CouplingConstant[ChPTVirtualPhotons2[4], 16,
	RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	CouplingConstant[ChPTVirtualPhotons2[4], 17, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	180*CouplingConstant[ChPTVirtualPhotons2[4], 18,
	RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	90*CouplingConstant[ChPTVirtualPhotons2[4], 16, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	90*CouplingConstant[ChPTVirtualPhotons2[4], 18, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] -
	5*CouplingConstant[ChPTVirtualPhotons2[4], 15, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] -
	185*CouplingConstant[ChPTVirtualPhotons2[4], 16,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] -
	CouplingConstant[ChPTVirtualPhotons2[4], 17, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] -
	180*CouplingConstant[ChPTVirtualPhotons2[4], 18,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}}
