{{(CouplingConstant[ChPT3[4], 4, RenormalizationState[0]]*
	((20*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/3 -
	(10*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/3 -
	(10*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/3 - 2*SU3F[I1, I3, k5]*
	SU3F[I2, I4, k5] - 2*SU3F[I1, I2, k5]*SU3F[I3, I4, k5] +
	(88*SUNDelta[I1, I4]*SUNDelta[I2, I3])/9 -
	(20*SUNDelta[I1, I3]*SUNDelta[I2, I4])/9 -
	(20*SUNDelta[I1, I2]*SUNDelta[I3, I4])/9) +
	CouplingConstant[ChPT3[4], 5, RenormalizationState[0]]*
	((44*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/9 + 4*SU3D[3, k5, k6]*
	SU3D[I1, I4, k5]*SU3D[I2, I3, k6] -
	(4*SU3D[8, k5, k6]*SU3D[I1, I4, k5]*SU3D[I2, I3, k6])/Sqrt[3] +
	2*SU3D[3, I4, k5]*SU3D[I1, k5, k6]*SU3D[I2, I3, k6] -
	(2*SU3D[8, I4, k5]*SU3D[I1, k5, k6]*SU3D[I2, I3, k6])/Sqrt[3] -
	(10*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/9 - 2*SU3D[3, I3, k5]*
	SU3D[I1, k5, k6]*SU3D[I2, I4, k6] +
	(2*SU3D[8, I3, k5]*SU3D[I1, k5, k6]*SU3D[I2, I4, k6])/Sqrt[3] -
	(SU3D[3, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/3 +
	(SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) +
	(11*SU3D[3, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/3 -
	(11*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) -
	(10*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/9 - 2*SU3D[3, I2, k5]*
	SU3D[I1, k5, k6]*SU3D[I3, I4, k6] +
	(2*SU3D[8, I2, k5]*SU3D[I1, k5, k6]*SU3D[I3, I4, k6])/Sqrt[3] +
	(SU3D[3, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/3 -
	(SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/(3*Sqrt[3]) -
	(SU3D[3, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/3 +
	(SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(11*SU3D[3, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/3 -
	(11*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(SU3D[3, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/3 -
	(SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[3, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/3 +
	(4*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[3, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/3 +
	(4*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) +
	(4*SU3D[3, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/3 -
	(4*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	(I/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[3, I1, k5] -
	(I/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[3, I1, k5] -
	((4*I)/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[3, I1, k5] +
	(I/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[3, I2, k5] -
	((2*I)/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[3, I2, k5] +
	(I/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[3, I3, k5] -
	((2*I)/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[3, I3, k5] -
	(2*I)*SU3D[I1, k5, k6]*SU3D[I2, I3, k6]*SU3F[3, I4, k5] +
	(I/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[3, I4, k5] +
	(I/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[3, I4, k5] -
	(4*I)*SU3D[I1, I4, k3]*SU3D[I2, I3, k6]*SU3F[3, k3, k6] +
	((I/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	((I/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	(((4*I)/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] +
	((2*I)*SU3D[I1, k5, k6]*SU3D[I2, I3, k6]*SU3F[8, I4, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] +
	((4*I)*SU3D[I1, I4, k3]*SU3D[I2, I3, k6]*SU3F[8, k3, k6])/Sqrt[3] +
	((5*I)/3)*SU3D[3, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6] -
	(((5*I)/3)*SU3D[8, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] +
	((2*I)/3)*SU3D[3, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6] -
	(((2*I)/3)*SU3D[8, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] -
	(4*SU3D[I4, k5, k6]*SU3F[3, I3, k5]*SU3F[I1, I2, k6])/3 +
	(5*SU3D[I3, k5, k6]*SU3F[3, I4, k5]*SU3F[I1, I2, k6])/3 +
	(4*SU3D[I4, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) -
	(5*SU3D[I3, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) +
	((5*I)/3)*SU3D[3, I4, k5]*SU3D[I2, k5, k6]*SU3F[I1, I3, k6] -
	(((5*I)/3)*SU3D[8, I4, k5]*SU3D[I2, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] +
	((2*I)/3)*SU3D[3, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6] -
	(((2*I)/3)*SU3D[8, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] -
	(4*SU3D[I4, k5, k6]*SU3F[3, I2, k5]*SU3F[I1, I3, k6])/3 +
	(5*SU3D[I2, k5, k6]*SU3F[3, I4, k5]*SU3F[I1, I3, k6])/3 +
	(4*SU3D[I4, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) -
	(5*SU3D[I2, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) -
	(I/3)*SU3D[3, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6] +
	((I/3)*SU3D[8, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] -
	(I/3)*SU3D[3, I2, k5]*SU3D[I3, k5, k6]*SU3F[I1, I4, k6] +
	((I/3)*SU3D[8, I2, k5]*SU3D[I3, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] -
	(SU3D[I3, k5, k6]*SU3F[3, I2, k5]*SU3F[I1, I4, k6])/3 -
	(SU3D[I2, k5, k6]*SU3F[3, I3, k5]*SU3F[I1, I4, k6])/3 +
	(SU3D[I3, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) +
	(SU3D[I2, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) +
	(2*I)*SU3D[3, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6] -
	((2*I)*SU3D[8, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(2*I)*SU3D[3, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6] +
	((2*I)*SU3D[8, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(2*I)*SU3D[3, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6] +
	((2*I)*SU3D[8, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	2*SU3D[I2, I3, k5]*SU3F[3, I4, k6]*SU3F[I1, k5, k6] +
	(2*SU3D[I2, I3, k5]*SU3F[8, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(2*SU3F[I1, I3, k5]*SU3F[I2, I4, k5])/3 - I*SU3D[3, I1, k5]*
	SU3D[I3, k5, k6]*SU3F[I2, I4, k6] +
	(I*SU3D[8, I1, k5]*SU3D[I3, k5, k6]*SU3F[I2, I4, k6])/Sqrt[3] -
	SU3D[I3, k5, k6]*SU3F[3, I1, k5]*SU3F[I2, I4, k6] +
	2*SU3D[I1, k5, k6]*SU3F[3, I3, k5]*SU3F[I2, I4, k6] +
	(SU3D[I3, k5, k6]*SU3F[8, I1, k5]*SU3F[I2, I4, k6])/Sqrt[3] -
	(2*SU3D[I1, k5, k6]*SU3F[8, I3, k5]*SU3F[I2, I4, k6])/Sqrt[3] +
	(2*I)*SU3F[3, I3, k5]*SU3F[I1, k5, k6]*SU3F[I2, I4, k6] -
	((2*I)*SU3F[8, I3, k5]*SU3F[I1, k5, k6]*SU3F[I2, I4, k6])/Sqrt[3] -
	(I/3)*SU3D[3, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6] +
	((I/3)*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	((11*I)/3)*SU3D[3, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6] -
	(((11*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6])/
	Sqrt[3] + (I/3)*SU3D[3, I1, k5]*SU3D[I3, I4, k6]*SU3F[I2, k5, k6] -
	((I/3)*SU3D[8, I1, k5]*SU3D[I3, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(SU3D[I3, I4, k5]*SU3F[3, I1, k6]*SU3F[I2, k5, k6])/3 +
	(SU3D[I1, I4, k5]*SU3F[3, I3, k6]*SU3F[I2, k5, k6])/3 +
	(SU3D[I1, I3, k5]*SU3F[3, I4, k6]*SU3F[I2, k5, k6])/3 +
	(SU3D[I3, I4, k5]*SU3F[8, I1, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I4, k5]*SU3F[8, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I3, k5]*SU3F[8, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(5*SU3D[3, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/3 +
	(5*SU3D[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	((5*I)/3)*SU3F[3, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6] -
	(((5*I)/3)*SU3F[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	(SU3D[3, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/3 -
	(SU3D[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(I/3)*SU3F[3, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6] +
	((I/3)*SU3F[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(2*SU3F[I1, I2, k5]*SU3F[I3, I4, k5])/3 - I*SU3D[3, I1, k5]*
	SU3D[I2, k5, k6]*SU3F[I3, I4, k6] +
	(I*SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] -
	SU3D[I2, k5, k6]*SU3F[3, I1, k5]*SU3F[I3, I4, k6] +
	2*SU3D[I1, k5, k6]*SU3F[3, I2, k5]*SU3F[I3, I4, k6] +
	(SU3D[I2, k5, k6]*SU3F[8, I1, k5]*SU3F[I3, I4, k6])/Sqrt[3] -
	(2*SU3D[I1, k5, k6]*SU3F[8, I2, k5]*SU3F[I3, I4, k6])/Sqrt[3] +
	(2*I)*SU3F[3, I2, k5]*SU3F[I1, k5, k6]*SU3F[I3, I4, k6] -
	((2*I)*SU3F[8, I2, k5]*SU3F[I1, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] +
	SU3D[3, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6] -
	(SU3D[8, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] -
	I*SU3F[3, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6] +
	(I*SU3F[8, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] -
	(I/3)*SU3D[3, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6] +
	((I/3)*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	((11*I)/3)*SU3D[3, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6] -
	(((11*I)/3)*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6])/
	Sqrt[3] + (I/3)*SU3D[3, I1, k5]*SU3D[I2, I4, k6]*SU3F[I3, k5, k6] -
	((I/3)*SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(SU3D[I2, I4, k5]*SU3F[3, I1, k6]*SU3F[I3, k5, k6])/3 +
	(SU3D[I1, I4, k5]*SU3F[3, I2, k6]*SU3F[I3, k5, k6])/3 +
	(SU3D[I1, I2, k5]*SU3F[3, I4, k6]*SU3F[I3, k5, k6])/3 +
	(SU3D[I2, I4, k5]*SU3F[8, I1, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I4, k5]*SU3F[8, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I2, k5]*SU3F[8, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(5*SU3D[3, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/3 +
	(5*SU3D[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	((5*I)/3)*SU3F[3, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6] -
	(((5*I)/3)*SU3F[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	(SU3D[3, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/3 -
	(SU3D[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(I/3)*SU3F[3, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6] +
	((I/3)*SU3F[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	SU3D[3, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6] -
	(SU3D[8, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	I*SU3F[3, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6] +
	(I*SU3F[8, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	((4*I)/3)*SU3D[3, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6] +
	(((4*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	((4*I)/3)*SU3D[3, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6] +
	(((4*I)/3)*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	((4*I)/3)*SU3D[3, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6] -
	(((4*I)/3)*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(4*SU3D[I2, I3, k5]*SU3F[3, I1, k6]*SU3F[I4, k5, k6])/3 -
	(2*SU3D[I1, I3, k5]*SU3F[3, I2, k6]*SU3F[I4, k5, k6])/3 -
	(2*SU3D[I1, I2, k5]*SU3F[3, I3, k6]*SU3F[I4, k5, k6])/3 +
	(4*SU3D[I2, I3, k5]*SU3F[8, I1, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I3, k5]*SU3F[8, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I2, k5]*SU3F[8, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(2*SU3D[3, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/3 +
	(2*SU3D[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	((4*I)/3)*SU3F[3, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6] +
	(((4*I)/3)*SU3F[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(2*SU3D[3, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/3 +
	(2*SU3D[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	((4*I)/3)*SU3F[3, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6] +
	(((4*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(4*SU3D[I2, I3, I4]*SUNDelta[3, I1])/3 +
	(2*SU3D[I1, I3, I4]*SUNDelta[3, I2])/9 + ((2*I)/3)*SU3F[I1, I3, I4]*
	SUNDelta[3, I2] + (2*SU3D[I1, I2, I4]*SUNDelta[3, I3])/9 +
	((2*I)/3)*SU3F[I1, I2, I4]*SUNDelta[3, I3] +
	(8*SU3D[I1, I2, I3]*SUNDelta[3, I4])/9 -
	(4*SU3D[I2, I3, I4]*SUNDelta[8, I1])/(3*Sqrt[3]) -
	(2*SU3D[I1, I3, I4]*SUNDelta[8, I2])/(9*Sqrt[3]) -
	(((2*I)/3)*SU3F[I1, I3, I4]*SUNDelta[8, I2])/Sqrt[3] -
	(2*SU3D[I1, I2, I4]*SUNDelta[8, I3])/(9*Sqrt[3]) -
	(((2*I)/3)*SU3F[I1, I2, I4]*SUNDelta[8, I3])/Sqrt[3] -
	(8*SU3D[I1, I2, I3]*SUNDelta[8, I4])/(9*Sqrt[3]) -
	(10*SU3D[3, I3, I4]*SUNDelta[I1, I2])/9 +
	(10*SU3D[8, I3, I4]*SUNDelta[I1, I2])/(9*Sqrt[3]) -
	((2*I)/3)*SU3F[3, I3, I4]*SUNDelta[I1, I2] +
	(((2*I)/3)*SU3F[8, I3, I4]*SUNDelta[I1, I2])/Sqrt[3] -
	(10*SU3D[3, I2, I4]*SUNDelta[I1, I3])/9 +
	(10*SU3D[8, I2, I4]*SUNDelta[I1, I3])/(9*Sqrt[3]) -
	((2*I)/3)*SU3F[3, I2, I4]*SUNDelta[I1, I3] +
	(((2*I)/3)*SU3F[8, I2, I4]*SUNDelta[I1, I3])/Sqrt[3] +
	(44*SU3D[3, I1, I4]*SUNDelta[I2, I3])/9 -
	(44*SU3D[8, I1, I4]*SUNDelta[I2, I3])/(9*Sqrt[3]) +
	((4*I)/9)*SU3F[3, I1, I4]*SUNDelta[I2, I3] -
	(((4*I)/9)*SU3F[8, I1, I4]*SUNDelta[I2, I3])/Sqrt[3] +
	(88*SUNDelta[I1, I4]*SUNDelta[I2, I3])/27 -
	(10*SU3D[3, I1, I3]*SUNDelta[I2, I4])/9 +
	(10*SU3D[8, I1, I3]*SUNDelta[I2, I4])/(9*Sqrt[3]) -
	((2*I)/9)*SU3F[3, I1, I3]*SUNDelta[I2, I4] +
	(((2*I)/9)*SU3F[8, I1, I3]*SUNDelta[I2, I4])/Sqrt[3] -
	(20*SUNDelta[I1, I3]*SUNDelta[I2, I4])/27 -
	(10*SU3D[3, I1, I2]*SUNDelta[I3, I4])/9 +
	(10*SU3D[8, I1, I2]*SUNDelta[I3, I4])/(9*Sqrt[3]) -
	((2*I)/9)*SU3F[3, I1, I2]*SUNDelta[I3, I4] +
	(((2*I)/9)*SU3F[8, I1, I2]*SUNDelta[I3, I4])/Sqrt[3] -
	(20*SUNDelta[I1, I2]*SUNDelta[I3, I4])/27))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3},
{(CouplingConstant[ChPT3[4], 4, RenormalizationState[0]]*
	((-10*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/3 +
	(20*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/3 -
	(10*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/3 - 2*SU3F[I1, I4, k5]*
	SU3F[I2, I3, k5] + 2*SU3F[I1, I2, k5]*SU3F[I3, I4, k5] -
	(20*SUNDelta[I1, I4]*SUNDelta[I2, I3])/9 +
	(88*SUNDelta[I1, I3]*SUNDelta[I2, I4])/9 -
	(20*SUNDelta[I1, I2]*SUNDelta[I3, I4])/9) +
	CouplingConstant[ChPT3[4], 5, RenormalizationState[0]]*
	((-10*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/9 - 2*SU3D[3, I4, k5]*
	SU3D[I1, k5, k6]*SU3D[I2, I3, k6] +
	(2*SU3D[8, I4, k5]*SU3D[I1, k5, k6]*SU3D[I2, I3, k6])/Sqrt[3] +
	(44*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/9 + 4*SU3D[3, k5, k6]*
	SU3D[I1, I3, k5]*SU3D[I2, I4, k6] -
	(4*SU3D[8, k5, k6]*SU3D[I1, I3, k5]*SU3D[I2, I4, k6])/Sqrt[3] +
	2*SU3D[3, I3, k5]*SU3D[I1, k5, k6]*SU3D[I2, I4, k6] -
	(2*SU3D[8, I3, k5]*SU3D[I1, k5, k6]*SU3D[I2, I4, k6])/Sqrt[3] +
	(11*SU3D[3, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/3 -
	(11*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) -
	(SU3D[3, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/3 +
	(SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) -
	(10*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/9 - 2*SU3D[3, I2, k5]*
	SU3D[I1, k5, k6]*SU3D[I3, I4, k6] +
	(2*SU3D[8, I2, k5]*SU3D[I1, k5, k6]*SU3D[I3, I4, k6])/Sqrt[3] +
	(SU3D[3, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/3 -
	(SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/(3*Sqrt[3]) -
	(4*SU3D[3, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/3 +
	(4*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[3, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/3 +
	(4*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(4*SU3D[3, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/3 -
	(4*SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) -
	(SU3D[3, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/3 +
	(SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) +
	(11*SU3D[3, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/3 -
	(11*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) +
	(SU3D[3, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/3 -
	(SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	(I/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[3, I1, k5] -
	((4*I)/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[3, I1, k5] -
	(I/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[3, I1, k5] -
	((2*I)/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[3, I2, k5] +
	(I/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[3, I2, k5] -
	(2*I)*SU3D[I1, k5, k6]*SU3D[I2, I4, k6]*SU3F[3, I3, k5] +
	(I/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[3, I3, k5] +
	(I/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[3, I3, k5] +
	(I/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[3, I4, k5] -
	((2*I)/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[3, I4, k5] -
	(4*I)*SU3D[I1, I3, k3]*SU3D[I2, I4, k6]*SU3F[3, k3, k6] +
	((I/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	(((4*I)/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	((I/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] +
	((2*I)*SU3D[I1, k5, k6]*SU3D[I2, I4, k6]*SU3F[8, I3, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] +
	((4*I)*SU3D[I1, I3, k3]*SU3D[I2, I4, k6]*SU3F[8, k3, k6])/Sqrt[3] +
	((2*I)/3)*SU3D[3, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6] -
	(((2*I)/3)*SU3D[8, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] +
	((5*I)/3)*SU3D[3, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6] -
	(((5*I)/3)*SU3D[8, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] +
	(5*SU3D[I4, k5, k6]*SU3F[3, I3, k5]*SU3F[I1, I2, k6])/3 -
	(4*SU3D[I3, k5, k6]*SU3F[3, I4, k5]*SU3F[I1, I2, k6])/3 -
	(5*SU3D[I4, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) +
	(4*SU3D[I3, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) -
	(I/3)*SU3D[3, I4, k5]*SU3D[I2, k5, k6]*SU3F[I1, I3, k6] +
	((I/3)*SU3D[8, I4, k5]*SU3D[I2, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] -
	(I/3)*SU3D[3, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6] +
	((I/3)*SU3D[8, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] -
	(SU3D[I4, k5, k6]*SU3F[3, I2, k5]*SU3F[I1, I3, k6])/3 -
	(SU3D[I2, k5, k6]*SU3F[3, I4, k5]*SU3F[I1, I3, k6])/3 +
	(SU3D[I4, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) +
	(SU3D[I2, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) +
	((5*I)/3)*SU3D[3, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6] -
	(((5*I)/3)*SU3D[8, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] +
	((2*I)/3)*SU3D[3, I2, k5]*SU3D[I3, k5, k6]*SU3F[I1, I4, k6] -
	(((2*I)/3)*SU3D[8, I2, k5]*SU3D[I3, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] -
	(4*SU3D[I3, k5, k6]*SU3F[3, I2, k5]*SU3F[I1, I4, k6])/3 +
	(5*SU3D[I2, k5, k6]*SU3F[3, I3, k5]*SU3F[I1, I4, k6])/3 +
	(4*SU3D[I3, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) -
	(5*SU3D[I2, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) -
	(2*I)*SU3D[3, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6] +
	((2*I)*SU3D[8, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	(2*I)*SU3D[3, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6] -
	((2*I)*SU3D[8, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(2*I)*SU3D[3, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6] +
	((2*I)*SU3D[8, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	2*SU3D[I2, I4, k5]*SU3F[3, I3, k6]*SU3F[I1, k5, k6] +
	(2*SU3D[I2, I4, k5]*SU3F[8, I3, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(2*SU3F[I1, I4, k5]*SU3F[I2, I3, k5])/3 - I*SU3D[3, I1, k5]*
	SU3D[I4, k5, k6]*SU3F[I2, I3, k6] +
	(I*SU3D[8, I1, k5]*SU3D[I4, k5, k6]*SU3F[I2, I3, k6])/Sqrt[3] -
	SU3D[I4, k5, k6]*SU3F[3, I1, k5]*SU3F[I2, I3, k6] +
	2*SU3D[I1, k5, k6]*SU3F[3, I4, k5]*SU3F[I2, I3, k6] +
	(SU3D[I4, k5, k6]*SU3F[8, I1, k5]*SU3F[I2, I3, k6])/Sqrt[3] -
	(2*SU3D[I1, k5, k6]*SU3F[8, I4, k5]*SU3F[I2, I3, k6])/Sqrt[3] +
	(2*I)*SU3F[3, I4, k5]*SU3F[I1, k5, k6]*SU3F[I2, I3, k6] -
	((2*I)*SU3F[8, I4, k5]*SU3F[I1, k5, k6]*SU3F[I2, I3, k6])/Sqrt[3] +
	((11*I)/3)*SU3D[3, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6] -
	(((11*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6])/
	Sqrt[3] - (I/3)*SU3D[3, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6] +
	((I/3)*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	(I/3)*SU3D[3, I1, k5]*SU3D[I3, I4, k6]*SU3F[I2, k5, k6] -
	((I/3)*SU3D[8, I1, k5]*SU3D[I3, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(SU3D[I3, I4, k5]*SU3F[3, I1, k6]*SU3F[I2, k5, k6])/3 +
	(SU3D[I1, I4, k5]*SU3F[3, I3, k6]*SU3F[I2, k5, k6])/3 +
	(SU3D[I1, I3, k5]*SU3F[3, I4, k6]*SU3F[I2, k5, k6])/3 +
	(SU3D[I3, I4, k5]*SU3F[8, I1, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I4, k5]*SU3F[8, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I3, k5]*SU3F[8, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	(SU3D[3, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/3 -
	(SU3D[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(I/3)*SU3F[3, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6] +
	((I/3)*SU3F[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(5*SU3D[3, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/3 +
	(5*SU3D[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	((5*I)/3)*SU3F[3, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6] -
	(((5*I)/3)*SU3F[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	(2*SU3F[I1, I2, k5]*SU3F[I3, I4, k5])/3 + I*SU3D[3, I1, k5]*
	SU3D[I2, k5, k6]*SU3F[I3, I4, k6] -
	(I*SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] +
	SU3D[I2, k5, k6]*SU3F[3, I1, k5]*SU3F[I3, I4, k6] -
	2*SU3D[I1, k5, k6]*SU3F[3, I2, k5]*SU3F[I3, I4, k6] -
	(SU3D[I2, k5, k6]*SU3F[8, I1, k5]*SU3F[I3, I4, k6])/Sqrt[3] +
	(2*SU3D[I1, k5, k6]*SU3F[8, I2, k5]*SU3F[I3, I4, k6])/Sqrt[3] -
	(2*I)*SU3F[3, I2, k5]*SU3F[I1, k5, k6]*SU3F[I3, I4, k6] +
	((2*I)*SU3F[8, I2, k5]*SU3F[I1, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] -
	SU3D[3, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6] +
	(SU3D[8, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] +
	I*SU3F[3, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6] -
	(I*SU3F[8, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] -
	((4*I)/3)*SU3D[3, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6] +
	(((4*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	((4*I)/3)*SU3D[3, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6] +
	(((4*I)/3)*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	((4*I)/3)*SU3D[3, I1, k5]*SU3D[I2, I4, k6]*SU3F[I3, k5, k6] -
	(((4*I)/3)*SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(4*SU3D[I2, I4, k5]*SU3F[3, I1, k6]*SU3F[I3, k5, k6])/3 -
	(2*SU3D[I1, I4, k5]*SU3F[3, I2, k6]*SU3F[I3, k5, k6])/3 -
	(2*SU3D[I1, I2, k5]*SU3F[3, I4, k6]*SU3F[I3, k5, k6])/3 +
	(4*SU3D[I2, I4, k5]*SU3F[8, I1, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I4, k5]*SU3F[8, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I2, k5]*SU3F[8, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(2*SU3D[3, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/3 +
	(2*SU3D[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	((4*I)/3)*SU3F[3, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6] +
	(((4*I)/3)*SU3F[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(2*SU3D[3, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/3 +
	(2*SU3D[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	((4*I)/3)*SU3F[3, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6] +
	(((4*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(I/3)*SU3D[3, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6] +
	((I/3)*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	((11*I)/3)*SU3D[3, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6] -
	(((11*I)/3)*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6])/
	Sqrt[3] + (I/3)*SU3D[3, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6] -
	((I/3)*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(SU3D[I2, I3, k5]*SU3F[3, I1, k6]*SU3F[I4, k5, k6])/3 +
	(SU3D[I1, I3, k5]*SU3F[3, I2, k6]*SU3F[I4, k5, k6])/3 +
	(SU3D[I1, I2, k5]*SU3F[3, I3, k6]*SU3F[I4, k5, k6])/3 +
	(SU3D[I2, I3, k5]*SU3F[8, I1, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I3, k5]*SU3F[8, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I2, k5]*SU3F[8, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(5*SU3D[3, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/3 +
	(5*SU3D[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	((5*I)/3)*SU3F[3, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6] -
	(((5*I)/3)*SU3F[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(SU3D[3, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/3 -
	(SU3D[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(I/3)*SU3F[3, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6] +
	((I/3)*SU3F[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	SU3D[3, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6] -
	(SU3D[8, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	I*SU3F[3, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6] +
	(I*SU3F[8, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(4*SU3D[I2, I3, I4]*SUNDelta[3, I1])/3 +
	(2*SU3D[I1, I3, I4]*SUNDelta[3, I2])/9 - ((2*I)/3)*SU3F[I1, I3, I4]*
	SUNDelta[3, I2] + (8*SU3D[I1, I2, I4]*SUNDelta[3, I3])/9 +
	(2*SU3D[I1, I2, I3]*SUNDelta[3, I4])/9 + ((2*I)/3)*SU3F[I1, I2, I3]*
	SUNDelta[3, I4] - (4*SU3D[I2, I3, I4]*SUNDelta[8, I1])/(3*Sqrt[3]) -
	(2*SU3D[I1, I3, I4]*SUNDelta[8, I2])/(9*Sqrt[3]) +
	(((2*I)/3)*SU3F[I1, I3, I4]*SUNDelta[8, I2])/Sqrt[3] -
	(8*SU3D[I1, I2, I4]*SUNDelta[8, I3])/(9*Sqrt[3]) -
	(2*SU3D[I1, I2, I3]*SUNDelta[8, I4])/(9*Sqrt[3]) -
	(((2*I)/3)*SU3F[I1, I2, I3]*SUNDelta[8, I4])/Sqrt[3] -
	(10*SU3D[3, I3, I4]*SUNDelta[I1, I2])/9 +
	(10*SU3D[8, I3, I4]*SUNDelta[I1, I2])/(9*Sqrt[3]) +
	((2*I)/3)*SU3F[3, I3, I4]*SUNDelta[I1, I2] -
	(((2*I)/3)*SU3F[8, I3, I4]*SUNDelta[I1, I2])/Sqrt[3] -
	(10*SU3D[3, I2, I3]*SUNDelta[I1, I4])/9 +
	(10*SU3D[8, I2, I3]*SUNDelta[I1, I4])/(9*Sqrt[3]) -
	((2*I)/3)*SU3F[3, I2, I3]*SUNDelta[I1, I4] +
	(((2*I)/3)*SU3F[8, I2, I3]*SUNDelta[I1, I4])/Sqrt[3] -
	(10*SU3D[3, I1, I4]*SUNDelta[I2, I3])/9 +
	(10*SU3D[8, I1, I4]*SUNDelta[I2, I3])/(9*Sqrt[3]) -
	((2*I)/9)*SU3F[3, I1, I4]*SUNDelta[I2, I3] +
	(((2*I)/9)*SU3F[8, I1, I4]*SUNDelta[I2, I3])/Sqrt[3] -
	(20*SUNDelta[I1, I4]*SUNDelta[I2, I3])/27 +
	(44*SU3D[3, I1, I3]*SUNDelta[I2, I4])/9 -
	(44*SU3D[8, I1, I3]*SUNDelta[I2, I4])/(9*Sqrt[3]) +
	((4*I)/9)*SU3F[3, I1, I3]*SUNDelta[I2, I4] -
	(((4*I)/9)*SU3F[8, I1, I3]*SUNDelta[I2, I4])/Sqrt[3] +
	(88*SUNDelta[I1, I3]*SUNDelta[I2, I4])/27 -
	(10*SU3D[3, I1, I2]*SUNDelta[I3, I4])/9 +
	(10*SU3D[8, I1, I2]*SUNDelta[I3, I4])/(9*Sqrt[3]) -
	((2*I)/9)*SU3F[3, I1, I2]*SUNDelta[I3, I4] +
	(((2*I)/9)*SU3F[8, I1, I2]*SUNDelta[I3, I4])/Sqrt[3] -
	(20*SUNDelta[I1, I2]*SUNDelta[I3, I4])/27))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3},
{(CouplingConstant[ChPT3[4], 4, RenormalizationState[0]]*
	((20*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/3 -
	(10*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/3 -
	(10*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/3 - 2*SU3F[I1, I3, k5]*
	SU3F[I2, I4, k5] - 2*SU3F[I1, I2, k5]*SU3F[I3, I4, k5] +
	(88*SUNDelta[I1, I4]*SUNDelta[I2, I3])/9 -
	(20*SUNDelta[I1, I3]*SUNDelta[I2, I4])/9 -
	(20*SUNDelta[I1, I2]*SUNDelta[I3, I4])/9) +
	CouplingConstant[ChPT3[4], 5, RenormalizationState[0]]*
	((44*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/9 - 4*SU3D[3, k5, k6]*
	SU3D[I1, I4, k5]*SU3D[I2, I3, k6] -
	(4*SU3D[8, k5, k6]*SU3D[I1, I4, k5]*SU3D[I2, I3, k6])/Sqrt[3] -
	2*SU3D[3, I4, k5]*SU3D[I1, k5, k6]*SU3D[I2, I3, k6] -
	(2*SU3D[8, I4, k5]*SU3D[I1, k5, k6]*SU3D[I2, I3, k6])/Sqrt[3] -
	(10*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/9 + 2*SU3D[3, I3, k5]*
	SU3D[I1, k5, k6]*SU3D[I2, I4, k6] +
	(2*SU3D[8, I3, k5]*SU3D[I1, k5, k6]*SU3D[I2, I4, k6])/Sqrt[3] +
	(SU3D[3, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/3 +
	(SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) -
	(11*SU3D[3, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/3 -
	(11*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) -
	(10*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/9 + 2*SU3D[3, I2, k5]*
	SU3D[I1, k5, k6]*SU3D[I3, I4, k6] +
	(2*SU3D[8, I2, k5]*SU3D[I1, k5, k6]*SU3D[I3, I4, k6])/Sqrt[3] -
	(SU3D[3, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/3 -
	(SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/(3*Sqrt[3]) +
	(SU3D[3, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/3 +
	(SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) -
	(11*SU3D[3, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/3 -
	(11*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) -
	(SU3D[3, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/3 -
	(SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(4*SU3D[3, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/3 +
	(4*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) +
	(4*SU3D[3, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/3 +
	(4*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[3, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/3 -
	(4*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) +
	(I/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[3, I1, k5] +
	(I/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[3, I1, k5] +
	((4*I)/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[3, I1, k5] -
	(I/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[3, I2, k5] +
	((2*I)/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[3, I2, k5] -
	(I/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[3, I3, k5] +
	((2*I)/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[3, I3, k5] +
	(2*I)*SU3D[I1, k5, k6]*SU3D[I2, I3, k6]*SU3F[3, I4, k5] -
	(I/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[3, I4, k5] -
	(I/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[3, I4, k5] +
	(4*I)*SU3D[I1, I4, k3]*SU3D[I2, I3, k6]*SU3F[3, k3, k6] +
	((I/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	((I/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	(((4*I)/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] +
	((2*I)*SU3D[I1, k5, k6]*SU3D[I2, I3, k6]*SU3F[8, I4, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] +
	((4*I)*SU3D[I1, I4, k3]*SU3D[I2, I3, k6]*SU3F[8, k3, k6])/Sqrt[3] -
	((5*I)/3)*SU3D[3, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6] -
	(((5*I)/3)*SU3D[8, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] -
	((2*I)/3)*SU3D[3, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6] -
	(((2*I)/3)*SU3D[8, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] +
	(4*SU3D[I4, k5, k6]*SU3F[3, I3, k5]*SU3F[I1, I2, k6])/3 -
	(5*SU3D[I3, k5, k6]*SU3F[3, I4, k5]*SU3F[I1, I2, k6])/3 +
	(4*SU3D[I4, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) -
	(5*SU3D[I3, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) -
	((5*I)/3)*SU3D[3, I4, k5]*SU3D[I2, k5, k6]*SU3F[I1, I3, k6] -
	(((5*I)/3)*SU3D[8, I4, k5]*SU3D[I2, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] -
	((2*I)/3)*SU3D[3, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6] -
	(((2*I)/3)*SU3D[8, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] +
	(4*SU3D[I4, k5, k6]*SU3F[3, I2, k5]*SU3F[I1, I3, k6])/3 -
	(5*SU3D[I2, k5, k6]*SU3F[3, I4, k5]*SU3F[I1, I3, k6])/3 +
	(4*SU3D[I4, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) -
	(5*SU3D[I2, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) +
	(I/3)*SU3D[3, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6] +
	((I/3)*SU3D[8, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] +
	(I/3)*SU3D[3, I2, k5]*SU3D[I3, k5, k6]*SU3F[I1, I4, k6] +
	((I/3)*SU3D[8, I2, k5]*SU3D[I3, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] +
	(SU3D[I3, k5, k6]*SU3F[3, I2, k5]*SU3F[I1, I4, k6])/3 +
	(SU3D[I2, k5, k6]*SU3F[3, I3, k5]*SU3F[I1, I4, k6])/3 +
	(SU3D[I3, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) +
	(SU3D[I2, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) -
	(2*I)*SU3D[3, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6] -
	((2*I)*SU3D[8, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	(2*I)*SU3D[3, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6] +
	((2*I)*SU3D[8, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	(2*I)*SU3D[3, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6] +
	((2*I)*SU3D[8, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	2*SU3D[I2, I3, k5]*SU3F[3, I4, k6]*SU3F[I1, k5, k6] +
	(2*SU3D[I2, I3, k5]*SU3F[8, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(2*SU3F[I1, I3, k5]*SU3F[I2, I4, k5])/3 + I*SU3D[3, I1, k5]*
	SU3D[I3, k5, k6]*SU3F[I2, I4, k6] +
	(I*SU3D[8, I1, k5]*SU3D[I3, k5, k6]*SU3F[I2, I4, k6])/Sqrt[3] +
	SU3D[I3, k5, k6]*SU3F[3, I1, k5]*SU3F[I2, I4, k6] -
	2*SU3D[I1, k5, k6]*SU3F[3, I3, k5]*SU3F[I2, I4, k6] +
	(SU3D[I3, k5, k6]*SU3F[8, I1, k5]*SU3F[I2, I4, k6])/Sqrt[3] -
	(2*SU3D[I1, k5, k6]*SU3F[8, I3, k5]*SU3F[I2, I4, k6])/Sqrt[3] -
	(2*I)*SU3F[3, I3, k5]*SU3F[I1, k5, k6]*SU3F[I2, I4, k6] -
	((2*I)*SU3F[8, I3, k5]*SU3F[I1, k5, k6]*SU3F[I2, I4, k6])/Sqrt[3] +
	(I/3)*SU3D[3, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6] +
	((I/3)*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	((11*I)/3)*SU3D[3, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6] -
	(((11*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6])/
	Sqrt[3] - (I/3)*SU3D[3, I1, k5]*SU3D[I3, I4, k6]*SU3F[I2, k5, k6] -
	((I/3)*SU3D[8, I1, k5]*SU3D[I3, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	(SU3D[I3, I4, k5]*SU3F[3, I1, k6]*SU3F[I2, k5, k6])/3 -
	(SU3D[I1, I4, k5]*SU3F[3, I3, k6]*SU3F[I2, k5, k6])/3 -
	(SU3D[I1, I3, k5]*SU3F[3, I4, k6]*SU3F[I2, k5, k6])/3 +
	(SU3D[I3, I4, k5]*SU3F[8, I1, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I4, k5]*SU3F[8, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I3, k5]*SU3F[8, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	(5*SU3D[3, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/3 +
	(5*SU3D[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	((5*I)/3)*SU3F[3, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6] -
	(((5*I)/3)*SU3F[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(SU3D[3, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/3 -
	(SU3D[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	(I/3)*SU3F[3, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6] +
	((I/3)*SU3F[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(2*SU3F[I1, I2, k5]*SU3F[I3, I4, k5])/3 + I*SU3D[3, I1, k5]*
	SU3D[I2, k5, k6]*SU3F[I3, I4, k6] +
	(I*SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] +
	SU3D[I2, k5, k6]*SU3F[3, I1, k5]*SU3F[I3, I4, k6] -
	2*SU3D[I1, k5, k6]*SU3F[3, I2, k5]*SU3F[I3, I4, k6] +
	(SU3D[I2, k5, k6]*SU3F[8, I1, k5]*SU3F[I3, I4, k6])/Sqrt[3] -
	(2*SU3D[I1, k5, k6]*SU3F[8, I2, k5]*SU3F[I3, I4, k6])/Sqrt[3] -
	(2*I)*SU3F[3, I2, k5]*SU3F[I1, k5, k6]*SU3F[I3, I4, k6] -
	((2*I)*SU3F[8, I2, k5]*SU3F[I1, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] -
	SU3D[3, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6] -
	(SU3D[8, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] +
	I*SU3F[3, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6] +
	(I*SU3F[8, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] +
	(I/3)*SU3D[3, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6] +
	((I/3)*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	((11*I)/3)*SU3D[3, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6] -
	(((11*I)/3)*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6])/
	Sqrt[3] - (I/3)*SU3D[3, I1, k5]*SU3D[I2, I4, k6]*SU3F[I3, k5, k6] -
	((I/3)*SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	(SU3D[I2, I4, k5]*SU3F[3, I1, k6]*SU3F[I3, k5, k6])/3 -
	(SU3D[I1, I4, k5]*SU3F[3, I2, k6]*SU3F[I3, k5, k6])/3 -
	(SU3D[I1, I2, k5]*SU3F[3, I4, k6]*SU3F[I3, k5, k6])/3 +
	(SU3D[I2, I4, k5]*SU3F[8, I1, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I4, k5]*SU3F[8, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I2, k5]*SU3F[8, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	(5*SU3D[3, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/3 +
	(5*SU3D[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	((5*I)/3)*SU3F[3, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6] -
	(((5*I)/3)*SU3F[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(SU3D[3, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/3 -
	(SU3D[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	(I/3)*SU3F[3, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6] +
	((I/3)*SU3F[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	SU3D[3, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6] -
	(SU3D[8, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	I*SU3F[3, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6] +
	(I*SU3F[8, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	((4*I)/3)*SU3D[3, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6] +
	(((4*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	((4*I)/3)*SU3D[3, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6] +
	(((4*I)/3)*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	((4*I)/3)*SU3D[3, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6] -
	(((4*I)/3)*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(4*SU3D[I2, I3, k5]*SU3F[3, I1, k6]*SU3F[I4, k5, k6])/3 +
	(2*SU3D[I1, I3, k5]*SU3F[3, I2, k6]*SU3F[I4, k5, k6])/3 +
	(2*SU3D[I1, I2, k5]*SU3F[3, I3, k6]*SU3F[I4, k5, k6])/3 +
	(4*SU3D[I2, I3, k5]*SU3F[8, I1, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I3, k5]*SU3F[8, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I2, k5]*SU3F[8, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[3, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/3 +
	(2*SU3D[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	((4*I)/3)*SU3F[3, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6] +
	(((4*I)/3)*SU3F[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(2*SU3D[3, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/3 +
	(2*SU3D[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	((4*I)/3)*SU3F[3, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6] +
	(((4*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(4*SU3D[I2, I3, I4]*SUNDelta[3, I1])/3 -
	(2*SU3D[I1, I3, I4]*SUNDelta[3, I2])/9 - ((2*I)/3)*SU3F[I1, I3, I4]*
	SUNDelta[3, I2] - (2*SU3D[I1, I2, I4]*SUNDelta[3, I3])/9 -
	((2*I)/3)*SU3F[I1, I2, I4]*SUNDelta[3, I3] -
	(8*SU3D[I1, I2, I3]*SUNDelta[3, I4])/9 -
	(4*SU3D[I2, I3, I4]*SUNDelta[8, I1])/(3*Sqrt[3]) -
	(2*SU3D[I1, I3, I4]*SUNDelta[8, I2])/(9*Sqrt[3]) -
	(((2*I)/3)*SU3F[I1, I3, I4]*SUNDelta[8, I2])/Sqrt[3] -
	(2*SU3D[I1, I2, I4]*SUNDelta[8, I3])/(9*Sqrt[3]) -
	(((2*I)/3)*SU3F[I1, I2, I4]*SUNDelta[8, I3])/Sqrt[3] -
	(8*SU3D[I1, I2, I3]*SUNDelta[8, I4])/(9*Sqrt[3]) +
	(10*SU3D[3, I3, I4]*SUNDelta[I1, I2])/9 +
	(10*SU3D[8, I3, I4]*SUNDelta[I1, I2])/(9*Sqrt[3]) +
	((2*I)/3)*SU3F[3, I3, I4]*SUNDelta[I1, I2] +
	(((2*I)/3)*SU3F[8, I3, I4]*SUNDelta[I1, I2])/Sqrt[3] +
	(10*SU3D[3, I2, I4]*SUNDelta[I1, I3])/9 +
	(10*SU3D[8, I2, I4]*SUNDelta[I1, I3])/(9*Sqrt[3]) +
	((2*I)/3)*SU3F[3, I2, I4]*SUNDelta[I1, I3] +
	(((2*I)/3)*SU3F[8, I2, I4]*SUNDelta[I1, I3])/Sqrt[3] -
	(44*SU3D[3, I1, I4]*SUNDelta[I2, I3])/9 -
	(44*SU3D[8, I1, I4]*SUNDelta[I2, I3])/(9*Sqrt[3]) -
	((4*I)/9)*SU3F[3, I1, I4]*SUNDelta[I2, I3] -
	(((4*I)/9)*SU3F[8, I1, I4]*SUNDelta[I2, I3])/Sqrt[3] +
	(88*SUNDelta[I1, I4]*SUNDelta[I2, I3])/27 +
	(10*SU3D[3, I1, I3]*SUNDelta[I2, I4])/9 +
	(10*SU3D[8, I1, I3]*SUNDelta[I2, I4])/(9*Sqrt[3]) +
	((2*I)/9)*SU3F[3, I1, I3]*SUNDelta[I2, I4] +
	(((2*I)/9)*SU3F[8, I1, I3]*SUNDelta[I2, I4])/Sqrt[3] -
	(20*SUNDelta[I1, I3]*SUNDelta[I2, I4])/27 +
	(10*SU3D[3, I1, I2]*SUNDelta[I3, I4])/9 +
	(10*SU3D[8, I1, I2]*SUNDelta[I3, I4])/(9*Sqrt[3]) +
	((2*I)/9)*SU3F[3, I1, I2]*SUNDelta[I3, I4] +
	(((2*I)/9)*SU3F[8, I1, I2]*SUNDelta[I3, I4])/Sqrt[3] -
	(20*SUNDelta[I1, I2]*SUNDelta[I3, I4])/27))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3},
{(CouplingConstant[ChPT3[4], 4, RenormalizationState[0]]*
	((-10*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/3 +
	(20*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/3 -
	(10*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/3 - 2*SU3F[I1, I4, k5]*
	SU3F[I2, I3, k5] + 2*SU3F[I1, I2, k5]*SU3F[I3, I4, k5] -
	(20*SUNDelta[I1, I4]*SUNDelta[I2, I3])/9 +
	(88*SUNDelta[I1, I3]*SUNDelta[I2, I4])/9 -
	(20*SUNDelta[I1, I2]*SUNDelta[I3, I4])/9) +
	CouplingConstant[ChPT3[4], 5, RenormalizationState[0]]*
	((-10*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/9 + 2*SU3D[3, I4, k5]*
	SU3D[I1, k5, k6]*SU3D[I2, I3, k6] +
	(2*SU3D[8, I4, k5]*SU3D[I1, k5, k6]*SU3D[I2, I3, k6])/Sqrt[3] +
	(44*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/9 - 4*SU3D[3, k5, k6]*
	SU3D[I1, I3, k5]*SU3D[I2, I4, k6] -
	(4*SU3D[8, k5, k6]*SU3D[I1, I3, k5]*SU3D[I2, I4, k6])/Sqrt[3] -
	2*SU3D[3, I3, k5]*SU3D[I1, k5, k6]*SU3D[I2, I4, k6] -
	(2*SU3D[8, I3, k5]*SU3D[I1, k5, k6]*SU3D[I2, I4, k6])/Sqrt[3] -
	(11*SU3D[3, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/3 -
	(11*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) +
	(SU3D[3, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/3 +
	(SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) -
	(10*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/9 + 2*SU3D[3, I2, k5]*
	SU3D[I1, k5, k6]*SU3D[I3, I4, k6] +
	(2*SU3D[8, I2, k5]*SU3D[I1, k5, k6]*SU3D[I3, I4, k6])/Sqrt[3] -
	(SU3D[3, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/3 -
	(SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/(3*Sqrt[3]) +
	(4*SU3D[3, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/3 +
	(4*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(4*SU3D[3, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/3 +
	(4*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[3, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/3 -
	(4*SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(SU3D[3, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/3 +
	(SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	(11*SU3D[3, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/3 -
	(11*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	(SU3D[3, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/3 -
	(SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) +
	(I/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[3, I1, k5] +
	((4*I)/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[3, I1, k5] +
	(I/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[3, I1, k5] +
	((2*I)/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[3, I2, k5] -
	(I/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[3, I2, k5] +
	(2*I)*SU3D[I1, k5, k6]*SU3D[I2, I4, k6]*SU3F[3, I3, k5] -
	(I/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[3, I3, k5] -
	(I/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[3, I3, k5] -
	(I/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[3, I4, k5] +
	((2*I)/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[3, I4, k5] +
	(4*I)*SU3D[I1, I3, k3]*SU3D[I2, I4, k6]*SU3F[3, k3, k6] +
	((I/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	(((4*I)/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	((I/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] +
	((2*I)*SU3D[I1, k5, k6]*SU3D[I2, I4, k6]*SU3F[8, I3, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] +
	((4*I)*SU3D[I1, I3, k3]*SU3D[I2, I4, k6]*SU3F[8, k3, k6])/Sqrt[3] -
	((2*I)/3)*SU3D[3, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6] -
	(((2*I)/3)*SU3D[8, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] -
	((5*I)/3)*SU3D[3, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6] -
	(((5*I)/3)*SU3D[8, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] -
	(5*SU3D[I4, k5, k6]*SU3F[3, I3, k5]*SU3F[I1, I2, k6])/3 +
	(4*SU3D[I3, k5, k6]*SU3F[3, I4, k5]*SU3F[I1, I2, k6])/3 -
	(5*SU3D[I4, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) +
	(4*SU3D[I3, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) +
	(I/3)*SU3D[3, I4, k5]*SU3D[I2, k5, k6]*SU3F[I1, I3, k6] +
	((I/3)*SU3D[8, I4, k5]*SU3D[I2, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] +
	(I/3)*SU3D[3, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6] +
	((I/3)*SU3D[8, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] +
	(SU3D[I4, k5, k6]*SU3F[3, I2, k5]*SU3F[I1, I3, k6])/3 +
	(SU3D[I2, k5, k6]*SU3F[3, I4, k5]*SU3F[I1, I3, k6])/3 +
	(SU3D[I4, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) +
	(SU3D[I2, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) -
	((5*I)/3)*SU3D[3, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6] -
	(((5*I)/3)*SU3D[8, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] -
	((2*I)/3)*SU3D[3, I2, k5]*SU3D[I3, k5, k6]*SU3F[I1, I4, k6] -
	(((2*I)/3)*SU3D[8, I2, k5]*SU3D[I3, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] +
	(4*SU3D[I3, k5, k6]*SU3F[3, I2, k5]*SU3F[I1, I4, k6])/3 -
	(5*SU3D[I2, k5, k6]*SU3F[3, I3, k5]*SU3F[I1, I4, k6])/3 +
	(4*SU3D[I3, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) -
	(5*SU3D[I2, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) +
	(2*I)*SU3D[3, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6] +
	((2*I)*SU3D[8, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(2*I)*SU3D[3, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6] -
	((2*I)*SU3D[8, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	(2*I)*SU3D[3, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6] +
	((2*I)*SU3D[8, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	2*SU3D[I2, I4, k5]*SU3F[3, I3, k6]*SU3F[I1, k5, k6] +
	(2*SU3D[I2, I4, k5]*SU3F[8, I3, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(2*SU3F[I1, I4, k5]*SU3F[I2, I3, k5])/3 + I*SU3D[3, I1, k5]*
	SU3D[I4, k5, k6]*SU3F[I2, I3, k6] +
	(I*SU3D[8, I1, k5]*SU3D[I4, k5, k6]*SU3F[I2, I3, k6])/Sqrt[3] +
	SU3D[I4, k5, k6]*SU3F[3, I1, k5]*SU3F[I2, I3, k6] -
	2*SU3D[I1, k5, k6]*SU3F[3, I4, k5]*SU3F[I2, I3, k6] +
	(SU3D[I4, k5, k6]*SU3F[8, I1, k5]*SU3F[I2, I3, k6])/Sqrt[3] -
	(2*SU3D[I1, k5, k6]*SU3F[8, I4, k5]*SU3F[I2, I3, k6])/Sqrt[3] -
	(2*I)*SU3F[3, I4, k5]*SU3F[I1, k5, k6]*SU3F[I2, I3, k6] -
	((2*I)*SU3F[8, I4, k5]*SU3F[I1, k5, k6]*SU3F[I2, I3, k6])/Sqrt[3] -
	((11*I)/3)*SU3D[3, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6] -
	(((11*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6])/
	Sqrt[3] + (I/3)*SU3D[3, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6] +
	((I/3)*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(I/3)*SU3D[3, I1, k5]*SU3D[I3, I4, k6]*SU3F[I2, k5, k6] -
	((I/3)*SU3D[8, I1, k5]*SU3D[I3, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	(SU3D[I3, I4, k5]*SU3F[3, I1, k6]*SU3F[I2, k5, k6])/3 -
	(SU3D[I1, I4, k5]*SU3F[3, I3, k6]*SU3F[I2, k5, k6])/3 -
	(SU3D[I1, I3, k5]*SU3F[3, I4, k6]*SU3F[I2, k5, k6])/3 +
	(SU3D[I3, I4, k5]*SU3F[8, I1, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I4, k5]*SU3F[8, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I3, k5]*SU3F[8, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(SU3D[3, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/3 -
	(SU3D[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	(I/3)*SU3F[3, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6] +
	((I/3)*SU3F[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	(5*SU3D[3, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/3 +
	(5*SU3D[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	((5*I)/3)*SU3F[3, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6] -
	(((5*I)/3)*SU3F[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	(2*SU3F[I1, I2, k5]*SU3F[I3, I4, k5])/3 - I*SU3D[3, I1, k5]*
	SU3D[I2, k5, k6]*SU3F[I3, I4, k6] -
	(I*SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] -
	SU3D[I2, k5, k6]*SU3F[3, I1, k5]*SU3F[I3, I4, k6] +
	2*SU3D[I1, k5, k6]*SU3F[3, I2, k5]*SU3F[I3, I4, k6] -
	(SU3D[I2, k5, k6]*SU3F[8, I1, k5]*SU3F[I3, I4, k6])/Sqrt[3] +
	(2*SU3D[I1, k5, k6]*SU3F[8, I2, k5]*SU3F[I3, I4, k6])/Sqrt[3] +
	(2*I)*SU3F[3, I2, k5]*SU3F[I1, k5, k6]*SU3F[I3, I4, k6] +
	((2*I)*SU3F[8, I2, k5]*SU3F[I1, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] +
	SU3D[3, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6] +
	(SU3D[8, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] -
	I*SU3F[3, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6] -
	(I*SU3F[8, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] +
	((4*I)/3)*SU3D[3, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6] +
	(((4*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	((4*I)/3)*SU3D[3, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6] +
	(((4*I)/3)*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	((4*I)/3)*SU3D[3, I1, k5]*SU3D[I2, I4, k6]*SU3F[I3, k5, k6] -
	(((4*I)/3)*SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	(4*SU3D[I2, I4, k5]*SU3F[3, I1, k6]*SU3F[I3, k5, k6])/3 +
	(2*SU3D[I1, I4, k5]*SU3F[3, I2, k6]*SU3F[I3, k5, k6])/3 +
	(2*SU3D[I1, I2, k5]*SU3F[3, I4, k6]*SU3F[I3, k5, k6])/3 +
	(4*SU3D[I2, I4, k5]*SU3F[8, I1, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I4, k5]*SU3F[8, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I2, k5]*SU3F[8, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[3, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/3 +
	(2*SU3D[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	((4*I)/3)*SU3F[3, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6] +
	(((4*I)/3)*SU3F[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	(2*SU3D[3, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/3 +
	(2*SU3D[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	((4*I)/3)*SU3F[3, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6] +
	(((4*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	(I/3)*SU3D[3, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6] +
	((I/3)*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	((11*I)/3)*SU3D[3, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6] -
	(((11*I)/3)*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6])/
	Sqrt[3] - (I/3)*SU3D[3, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6] -
	((I/3)*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(SU3D[I2, I3, k5]*SU3F[3, I1, k6]*SU3F[I4, k5, k6])/3 -
	(SU3D[I1, I3, k5]*SU3F[3, I2, k6]*SU3F[I4, k5, k6])/3 -
	(SU3D[I1, I2, k5]*SU3F[3, I3, k6]*SU3F[I4, k5, k6])/3 +
	(SU3D[I2, I3, k5]*SU3F[8, I1, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I3, k5]*SU3F[8, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I2, k5]*SU3F[8, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	(5*SU3D[3, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/3 +
	(5*SU3D[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	((5*I)/3)*SU3F[3, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6] -
	(((5*I)/3)*SU3F[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(SU3D[3, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/3 -
	(SU3D[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	(I/3)*SU3F[3, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6] +
	((I/3)*SU3F[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	SU3D[3, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6] -
	(SU3D[8, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	I*SU3F[3, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6] +
	(I*SU3F[8, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(4*SU3D[I2, I3, I4]*SUNDelta[3, I1])/3 -
	(2*SU3D[I1, I3, I4]*SUNDelta[3, I2])/9 + ((2*I)/3)*SU3F[I1, I3, I4]*
	SUNDelta[3, I2] - (8*SU3D[I1, I2, I4]*SUNDelta[3, I3])/9 -
	(2*SU3D[I1, I2, I3]*SUNDelta[3, I4])/9 - ((2*I)/3)*SU3F[I1, I2, I3]*
	SUNDelta[3, I4] - (4*SU3D[I2, I3, I4]*SUNDelta[8, I1])/(3*Sqrt[3]) -
	(2*SU3D[I1, I3, I4]*SUNDelta[8, I2])/(9*Sqrt[3]) +
	(((2*I)/3)*SU3F[I1, I3, I4]*SUNDelta[8, I2])/Sqrt[3] -
	(8*SU3D[I1, I2, I4]*SUNDelta[8, I3])/(9*Sqrt[3]) -
	(2*SU3D[I1, I2, I3]*SUNDelta[8, I4])/(9*Sqrt[3]) -
	(((2*I)/3)*SU3F[I1, I2, I3]*SUNDelta[8, I4])/Sqrt[3] +
	(10*SU3D[3, I3, I4]*SUNDelta[I1, I2])/9 +
	(10*SU3D[8, I3, I4]*SUNDelta[I1, I2])/(9*Sqrt[3]) -
	((2*I)/3)*SU3F[3, I3, I4]*SUNDelta[I1, I2] -
	(((2*I)/3)*SU3F[8, I3, I4]*SUNDelta[I1, I2])/Sqrt[3] +
	(10*SU3D[3, I2, I3]*SUNDelta[I1, I4])/9 +
	(10*SU3D[8, I2, I3]*SUNDelta[I1, I4])/(9*Sqrt[3]) +
	((2*I)/3)*SU3F[3, I2, I3]*SUNDelta[I1, I4] +
	(((2*I)/3)*SU3F[8, I2, I3]*SUNDelta[I1, I4])/Sqrt[3] +
	(10*SU3D[3, I1, I4]*SUNDelta[I2, I3])/9 +
	(10*SU3D[8, I1, I4]*SUNDelta[I2, I3])/(9*Sqrt[3]) +
	((2*I)/9)*SU3F[3, I1, I4]*SUNDelta[I2, I3] +
	(((2*I)/9)*SU3F[8, I1, I4]*SUNDelta[I2, I3])/Sqrt[3] -
	(20*SUNDelta[I1, I4]*SUNDelta[I2, I3])/27 -
	(44*SU3D[3, I1, I3]*SUNDelta[I2, I4])/9 -
	(44*SU3D[8, I1, I3]*SUNDelta[I2, I4])/(9*Sqrt[3]) -
	((4*I)/9)*SU3F[3, I1, I3]*SUNDelta[I2, I4] -
	(((4*I)/9)*SU3F[8, I1, I3]*SUNDelta[I2, I4])/Sqrt[3] +
	(88*SUNDelta[I1, I3]*SUNDelta[I2, I4])/27 +
	(10*SU3D[3, I1, I2]*SUNDelta[I3, I4])/9 +
	(10*SU3D[8, I1, I2]*SUNDelta[I3, I4])/(9*Sqrt[3]) +
	((2*I)/9)*SU3F[3, I1, I2]*SUNDelta[I3, I4] +
	(((2*I)/9)*SU3F[8, I1, I2]*SUNDelta[I3, I4])/Sqrt[3] -
	(20*SUNDelta[I1, I2]*SUNDelta[I3, I4])/27))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3},
{(CouplingConstant[ChPT3[4], 4, RenormalizationState[0]]*
	((20*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/3 -
	(10*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/3 -
	(10*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/3 - 2*SU3F[I1, I3, k5]*
	SU3F[I2, I4, k5] - 2*SU3F[I1, I2, k5]*SU3F[I3, I4, k5] +
	(88*SUNDelta[I1, I4]*SUNDelta[I2, I3])/9 -
	(20*SUNDelta[I1, I3]*SUNDelta[I2, I4])/9 -
	(20*SUNDelta[I1, I2]*SUNDelta[I3, I4])/9) +
	CouplingConstant[ChPT3[4], 5, RenormalizationState[0]]*
	((44*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/9 +
	(8*SU3D[8, k5, k6]*SU3D[I1, I4, k5]*SU3D[I2, I3, k6])/Sqrt[3] +
	(4*SU3D[8, I4, k5]*SU3D[I1, k5, k6]*SU3D[I2, I3, k6])/Sqrt[3] -
	(10*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/9 -
	(4*SU3D[8, I3, k5]*SU3D[I1, k5, k6]*SU3D[I2, I4, k6])/Sqrt[3] -
	(2*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) +
	(22*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) -
	(10*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/9 -
	(4*SU3D[8, I2, k5]*SU3D[I1, k5, k6]*SU3D[I3, I4, k6])/Sqrt[3] +
	(2*SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/(3*Sqrt[3]) -
	(2*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(22*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) -
	(8*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	(8*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) +
	(8*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	(((2*I)/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[8, I1, k5])/Sqrt[3] -
	(((2*I)/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] -
	(((8*I)/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] -
	(((4*I)/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] -
	(((4*I)/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] -
	((4*I)*SU3D[I1, k5, k6]*SU3D[I2, I3, k6]*SU3F[8, I4, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] -
	((8*I)*SU3D[I1, I4, k3]*SU3D[I2, I3, k6]*SU3F[8, k3, k6])/Sqrt[3] +
	(((10*I)/3)*SU3D[8, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6])/
	Sqrt[3] + (((4*I)/3)*SU3D[8, I3, k5]*SU3D[I4, k5, k6]*
		SU3F[I1, I2, k6])/Sqrt[3] - (8*SU3D[I4, k5, k6]*SU3F[8, I3, k5]*
		SU3F[I1, I2, k6])/(3*Sqrt[3]) + (10*SU3D[I3, k5, k6]*SU3F[8, I4, k5]*
		SU3F[I1, I2, k6])/(3*Sqrt[3]) + (((10*I)/3)*SU3D[8, I4, k5]*
		SU3D[I2, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] +
	(((4*I)/3)*SU3D[8, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] -
	(8*SU3D[I4, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) +
	(10*SU3D[I2, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) -
	(((2*I)/3)*SU3D[8, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] -
	(((2*I)/3)*SU3D[8, I2, k5]*SU3D[I3, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] -
	(2*SU3D[I3, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) -
	(2*SU3D[I2, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) +
	((4*I)*SU3D[8, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	((4*I)*SU3D[8, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	((4*I)*SU3D[8, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(4*SU3D[I2, I3, k5]*SU3F[8, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(2*SU3F[I1, I3, k5]*SU3F[I2, I4, k5])/3 -
	((2*I)*SU3D[8, I1, k5]*SU3D[I3, k5, k6]*SU3F[I2, I4, k6])/Sqrt[3] -
	(2*SU3D[I3, k5, k6]*SU3F[8, I1, k5]*SU3F[I2, I4, k6])/Sqrt[3] +
	(4*SU3D[I1, k5, k6]*SU3F[8, I3, k5]*SU3F[I2, I4, k6])/Sqrt[3] +
	((4*I)*SU3F[8, I3, k5]*SU3F[I1, k5, k6]*SU3F[I2, I4, k6])/Sqrt[3] -
	(((2*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	(((22*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6])/
	Sqrt[3] + (((2*I)/3)*SU3D[8, I1, k5]*SU3D[I3, I4, k6]*
		SU3F[I2, k5, k6])/Sqrt[3] - (2*SU3D[I3, I4, k5]*SU3F[8, I1, k6]*
		SU3F[I2, k5, k6])/(3*Sqrt[3]) + (2*SU3D[I1, I4, k5]*SU3F[8, I3, k6]*
		SU3F[I2, k5, k6])/(3*Sqrt[3]) + (2*SU3D[I1, I3, k5]*SU3F[8, I4, k6]*
		SU3F[I2, k5, k6])/(3*Sqrt[3]) - (10*SU3D[8, I4, k5]*SU3F[I1, I3, k6]*
		SU3F[I2, k5, k6])/(3*Sqrt[3]) + (((10*I)/3)*SU3F[8, I4, k5]*
		SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	(2*SU3D[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(((2*I)/3)*SU3F[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(2*SU3F[I1, I2, k5]*SU3F[I3, I4, k5])/3 -
	((2*I)*SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] -
	(2*SU3D[I2, k5, k6]*SU3F[8, I1, k5]*SU3F[I3, I4, k6])/Sqrt[3] +
	(4*SU3D[I1, k5, k6]*SU3F[8, I2, k5]*SU3F[I3, I4, k6])/Sqrt[3] +
	((4*I)*SU3F[8, I2, k5]*SU3F[I1, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] +
	(2*SU3D[8, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] -
	((2*I)*SU3F[8, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] -
	(((2*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	(((22*I)/3)*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6])/
	Sqrt[3] + (((2*I)/3)*SU3D[8, I1, k5]*SU3D[I2, I4, k6]*
		SU3F[I3, k5, k6])/Sqrt[3] - (2*SU3D[I2, I4, k5]*SU3F[8, I1, k6]*
		SU3F[I3, k5, k6])/(3*Sqrt[3]) + (2*SU3D[I1, I4, k5]*SU3F[8, I2, k6]*
		SU3F[I3, k5, k6])/(3*Sqrt[3]) + (2*SU3D[I1, I2, k5]*SU3F[8, I4, k6]*
		SU3F[I3, k5, k6])/(3*Sqrt[3]) - (10*SU3D[8, I4, k5]*SU3F[I1, I2, k6]*
		SU3F[I3, k5, k6])/(3*Sqrt[3]) + (((10*I)/3)*SU3F[8, I4, k5]*
		SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	(2*SU3D[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(((2*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	(2*SU3D[8, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	((2*I)*SU3F[8, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(((8*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(((8*I)/3)*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(((8*I)/3)*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(8*SU3D[I2, I3, k5]*SU3F[8, I1, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[I1, I3, k5]*SU3F[8, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[I1, I2, k5]*SU3F[8, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(((8*I)/3)*SU3F[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(4*SU3D[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(((8*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(8*SU3D[I2, I3, I4]*SUNDelta[8, I1])/(3*Sqrt[3]) +
	(4*SU3D[I1, I3, I4]*SUNDelta[8, I2])/(9*Sqrt[3]) +
	(((4*I)/3)*SU3F[I1, I3, I4]*SUNDelta[8, I2])/Sqrt[3] +
	(4*SU3D[I1, I2, I4]*SUNDelta[8, I3])/(9*Sqrt[3]) +
	(((4*I)/3)*SU3F[I1, I2, I4]*SUNDelta[8, I3])/Sqrt[3] +
	(16*SU3D[I1, I2, I3]*SUNDelta[8, I4])/(9*Sqrt[3]) -
	(20*SU3D[8, I3, I4]*SUNDelta[I1, I2])/(9*Sqrt[3]) -
	(((4*I)/3)*SU3F[8, I3, I4]*SUNDelta[I1, I2])/Sqrt[3] -
	(20*SU3D[8, I2, I4]*SUNDelta[I1, I3])/(9*Sqrt[3]) -
	(((4*I)/3)*SU3F[8, I2, I4]*SUNDelta[I1, I3])/Sqrt[3] +
	(88*SU3D[8, I1, I4]*SUNDelta[I2, I3])/(9*Sqrt[3]) +
	(((8*I)/9)*SU3F[8, I1, I4]*SUNDelta[I2, I3])/Sqrt[3] +
	(88*SUNDelta[I1, I4]*SUNDelta[I2, I3])/27 -
	(20*SU3D[8, I1, I3]*SUNDelta[I2, I4])/(9*Sqrt[3]) -
	(((4*I)/9)*SU3F[8, I1, I3]*SUNDelta[I2, I4])/Sqrt[3] -
	(20*SUNDelta[I1, I3]*SUNDelta[I2, I4])/27 -
	(20*SU3D[8, I1, I2]*SUNDelta[I3, I4])/(9*Sqrt[3]) -
	(((4*I)/9)*SU3F[8, I1, I2]*SUNDelta[I3, I4])/Sqrt[3] -
	(20*SUNDelta[I1, I2]*SUNDelta[I3, I4])/27))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3},
{(CouplingConstant[ChPT3[4], 4, RenormalizationState[0]]*
	((-10*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/3 +
	(20*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/3 -
	(10*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/3 - 2*SU3F[I1, I4, k5]*
	SU3F[I2, I3, k5] + 2*SU3F[I1, I2, k5]*SU3F[I3, I4, k5] -
	(20*SUNDelta[I1, I4]*SUNDelta[I2, I3])/9 +
	(88*SUNDelta[I1, I3]*SUNDelta[I2, I4])/9 -
	(20*SUNDelta[I1, I2]*SUNDelta[I3, I4])/9) +
	CouplingConstant[ChPT3[4], 5, RenormalizationState[0]]*
	((-10*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/9 -
	(4*SU3D[8, I4, k5]*SU3D[I1, k5, k6]*SU3D[I2, I3, k6])/Sqrt[3] +
	(44*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/9 +
	(8*SU3D[8, k5, k6]*SU3D[I1, I3, k5]*SU3D[I2, I4, k6])/Sqrt[3] +
	(4*SU3D[8, I3, k5]*SU3D[I1, k5, k6]*SU3D[I2, I4, k6])/Sqrt[3] +
	(22*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) -
	(2*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) -
	(10*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/9 -
	(4*SU3D[8, I2, k5]*SU3D[I1, k5, k6]*SU3D[I3, I4, k6])/Sqrt[3] +
	(2*SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/(3*Sqrt[3]) -
	(8*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) -
	(8*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(8*SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) -
	(2*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) +
	(22*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	(((2*I)/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[8, I1, k5])/Sqrt[3] -
	(((8*I)/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] -
	(((2*I)/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] -
	(((4*I)/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] -
	((4*I)*SU3D[I1, k5, k6]*SU3D[I2, I4, k6]*SU3F[8, I3, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] -
	(((4*I)/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] -
	((8*I)*SU3D[I1, I3, k3]*SU3D[I2, I4, k6]*SU3F[8, k3, k6])/Sqrt[3] +
	(((4*I)/3)*SU3D[8, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] +
	(((10*I)/3)*SU3D[8, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6])/
	Sqrt[3] + (10*SU3D[I4, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I2, k6])/
	(3*Sqrt[3]) - (8*SU3D[I3, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I2, k6])/
	(3*Sqrt[3]) - (((2*I)/3)*SU3D[8, I4, k5]*SU3D[I2, k5, k6]*
		SU3F[I1, I3, k6])/Sqrt[3] - (((2*I)/3)*SU3D[8, I2, k5]*
		SU3D[I4, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] -
	(2*SU3D[I4, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) -
	(2*SU3D[I2, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) +
	(((10*I)/3)*SU3D[8, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6])/
	Sqrt[3] + (((4*I)/3)*SU3D[8, I2, k5]*SU3D[I3, k5, k6]*
		SU3F[I1, I4, k6])/Sqrt[3] - (8*SU3D[I3, k5, k6]*SU3F[8, I2, k5]*
		SU3F[I1, I4, k6])/(3*Sqrt[3]) + (10*SU3D[I2, k5, k6]*SU3F[8, I3, k5]*
		SU3F[I1, I4, k6])/(3*Sqrt[3]) - ((4*I)*SU3D[8, I4, k5]*
		SU3D[I2, I3, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	((4*I)*SU3D[8, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	((4*I)*SU3D[8, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(4*SU3D[I2, I4, k5]*SU3F[8, I3, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(2*SU3F[I1, I4, k5]*SU3F[I2, I3, k5])/3 -
	((2*I)*SU3D[8, I1, k5]*SU3D[I4, k5, k6]*SU3F[I2, I3, k6])/Sqrt[3] -
	(2*SU3D[I4, k5, k6]*SU3F[8, I1, k5]*SU3F[I2, I3, k6])/Sqrt[3] +
	(4*SU3D[I1, k5, k6]*SU3F[8, I4, k5]*SU3F[I2, I3, k6])/Sqrt[3] +
	((4*I)*SU3F[8, I4, k5]*SU3F[I1, k5, k6]*SU3F[I2, I3, k6])/Sqrt[3] +
	(((22*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6])/
	Sqrt[3] - (((2*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*
		SU3F[I2, k5, k6])/Sqrt[3] + (((2*I)/3)*SU3D[8, I1, k5]*
		SU3D[I3, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(2*SU3D[I3, I4, k5]*SU3F[8, I1, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I4, k5]*SU3F[8, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I3, k5]*SU3F[8, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(((2*I)/3)*SU3F[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(10*SU3D[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	(((10*I)/3)*SU3F[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/
	Sqrt[3] + (2*SU3F[I1, I2, k5]*SU3F[I3, I4, k5])/3 +
	((2*I)*SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] +
	(2*SU3D[I2, k5, k6]*SU3F[8, I1, k5]*SU3F[I3, I4, k6])/Sqrt[3] -
	(4*SU3D[I1, k5, k6]*SU3F[8, I2, k5]*SU3F[I3, I4, k6])/Sqrt[3] -
	((4*I)*SU3F[8, I2, k5]*SU3F[I1, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] -
	(2*SU3D[8, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] +
	((2*I)*SU3F[8, I1, k5]*SU3F[I2, k5, k6]*SU3F[I3, I4, k6])/Sqrt[3] -
	(((8*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(((8*I)/3)*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	(((8*I)/3)*SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(8*SU3D[I2, I4, k5]*SU3F[8, I1, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[I1, I4, k5]*SU3F[8, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[I1, I2, k5]*SU3F[8, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(((8*I)/3)*SU3F[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(4*SU3D[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(((8*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(((2*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(((22*I)/3)*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6])/
	Sqrt[3] + (((2*I)/3)*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*
		SU3F[I4, k5, k6])/Sqrt[3] - (2*SU3D[I2, I3, k5]*SU3F[8, I1, k6]*
		SU3F[I4, k5, k6])/(3*Sqrt[3]) + (2*SU3D[I1, I3, k5]*SU3F[8, I2, k6]*
		SU3F[I4, k5, k6])/(3*Sqrt[3]) + (2*SU3D[I1, I2, k5]*SU3F[8, I3, k6]*
		SU3F[I4, k5, k6])/(3*Sqrt[3]) - (10*SU3D[8, I3, k5]*SU3F[I1, I2, k6]*
		SU3F[I4, k5, k6])/(3*Sqrt[3]) + (((10*I)/3)*SU3F[8, I3, k5]*
		SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(2*SU3D[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(((2*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(2*SU3D[8, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	((2*I)*SU3F[8, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(8*SU3D[I2, I3, I4]*SUNDelta[8, I1])/(3*Sqrt[3]) +
	(4*SU3D[I1, I3, I4]*SUNDelta[8, I2])/(9*Sqrt[3]) -
	(((4*I)/3)*SU3F[I1, I3, I4]*SUNDelta[8, I2])/Sqrt[3] +
	(16*SU3D[I1, I2, I4]*SUNDelta[8, I3])/(9*Sqrt[3]) +
	(4*SU3D[I1, I2, I3]*SUNDelta[8, I4])/(9*Sqrt[3]) +
	(((4*I)/3)*SU3F[I1, I2, I3]*SUNDelta[8, I4])/Sqrt[3] -
	(20*SU3D[8, I3, I4]*SUNDelta[I1, I2])/(9*Sqrt[3]) +
	(((4*I)/3)*SU3F[8, I3, I4]*SUNDelta[I1, I2])/Sqrt[3] -
	(20*SU3D[8, I2, I3]*SUNDelta[I1, I4])/(9*Sqrt[3]) -
	(((4*I)/3)*SU3F[8, I2, I3]*SUNDelta[I1, I4])/Sqrt[3] -
	(20*SU3D[8, I1, I4]*SUNDelta[I2, I3])/(9*Sqrt[3]) -
	(((4*I)/9)*SU3F[8, I1, I4]*SUNDelta[I2, I3])/Sqrt[3] -
	(20*SUNDelta[I1, I4]*SUNDelta[I2, I3])/27 +
	(88*SU3D[8, I1, I3]*SUNDelta[I2, I4])/(9*Sqrt[3]) +
	(((8*I)/9)*SU3F[8, I1, I3]*SUNDelta[I2, I4])/Sqrt[3] +
	(88*SUNDelta[I1, I3]*SUNDelta[I2, I4])/27 -
	(20*SU3D[8, I1, I2]*SUNDelta[I3, I4])/(9*Sqrt[3]) -
	(((4*I)/9)*SU3F[8, I1, I2]*SUNDelta[I3, I4])/Sqrt[3] -
	(20*SUNDelta[I1, I2]*SUNDelta[I3, I4])/27))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3},
{(CouplingConstant[ChPT3[4], 5, RenormalizationState[0]]*
	((-10*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/9 + 2*SU3D[3, I4, k5]*
	SU3D[I1, k5, k6]*SU3D[I2, I3, k6] +
	(2*SU3D[8, I4, k5]*SU3D[I1, k5, k6]*SU3D[I2, I3, k6])/Sqrt[3] -
	(10*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/9 + 2*SU3D[3, I3, k5]*
	SU3D[I1, k5, k6]*SU3D[I2, I4, k6] +
	(2*SU3D[8, I3, k5]*SU3D[I1, k5, k6]*SU3D[I2, I4, k6])/Sqrt[3] +
	(4*SU3D[3, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/3 +
	(4*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) +
	(4*SU3D[3, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/3 +
	(4*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) +
	(44*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/9 - 4*SU3D[3, k5, k6]*
	SU3D[I1, I2, k5]*SU3D[I3, I4, k6] -
	(4*SU3D[8, k5, k6]*SU3D[I1, I2, k5]*SU3D[I3, I4, k6])/Sqrt[3] -
	2*SU3D[3, I2, k5]*SU3D[I1, k5, k6]*SU3D[I3, I4, k6] -
	(2*SU3D[8, I2, k5]*SU3D[I1, k5, k6]*SU3D[I3, I4, k6])/Sqrt[3] -
	(4*SU3D[3, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/3 -
	(4*SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/(3*Sqrt[3]) -
	(11*SU3D[3, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/3 -
	(11*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(SU3D[3, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/3 +
	(SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) -
	(SU3D[3, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/3 -
	(SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) -
	(11*SU3D[3, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/3 -
	(11*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) +
	(SU3D[3, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/3 +
	(SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	(SU3D[3, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/3 -
	(SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) +
	((4*I)/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[3, I1, k5] +
	(I/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[3, I1, k5] +
	(I/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[3, I1, k5] +
	(2*I)*SU3D[I1, k5, k6]*SU3D[I3, I4, k6]*SU3F[3, I2, k5] -
	(I/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[3, I2, k5] -
	(I/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[3, I2, k5] +
	((2*I)/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[3, I3, k5] -
	(I/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[3, I3, k5] +
	((2*I)/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[3, I4, k5] -
	(I/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[3, I4, k5] +
	(4*I)*SU3D[I1, I2, k3]*SU3D[I3, I4, k6]*SU3F[3, k3, k6] +
	(((4*I)/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	((I/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	((I/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	((2*I)*SU3D[I1, k5, k6]*SU3D[I3, I4, k6]*SU3F[8, I2, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] +
	((4*I)*SU3D[I1, I2, k3]*SU3D[I3, I4, k6]*SU3F[8, k3, k6])/Sqrt[3] +
	(I/3)*SU3D[3, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6] +
	((I/3)*SU3D[8, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] +
	(I/3)*SU3D[3, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6] +
	((I/3)*SU3D[8, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] +
	(SU3D[I4, k5, k6]*SU3F[3, I3, k5]*SU3F[I1, I2, k6])/3 +
	(SU3D[I3, k5, k6]*SU3F[3, I4, k5]*SU3F[I1, I2, k6])/3 +
	(SU3D[I4, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) +
	(SU3D[I3, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) -
	((2*I)/3)*SU3D[3, I4, k5]*SU3D[I2, k5, k6]*SU3F[I1, I3, k6] -
	(((2*I)/3)*SU3D[8, I4, k5]*SU3D[I2, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] -
	((5*I)/3)*SU3D[3, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6] -
	(((5*I)/3)*SU3D[8, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] -
	(5*SU3D[I4, k5, k6]*SU3F[3, I2, k5]*SU3F[I1, I3, k6])/3 +
	(4*SU3D[I2, k5, k6]*SU3F[3, I4, k5]*SU3F[I1, I3, k6])/3 -
	(5*SU3D[I4, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) +
	(4*SU3D[I2, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) -
	((2*I)/3)*SU3D[3, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6] -
	(((2*I)/3)*SU3D[8, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] -
	((5*I)/3)*SU3D[3, I2, k5]*SU3D[I3, k5, k6]*SU3F[I1, I4, k6] -
	(((5*I)/3)*SU3D[8, I2, k5]*SU3D[I3, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] -
	(5*SU3D[I3, k5, k6]*SU3F[3, I2, k5]*SU3F[I1, I4, k6])/3 +
	(4*SU3D[I2, k5, k6]*SU3F[3, I3, k5]*SU3F[I1, I4, k6])/3 -
	(5*SU3D[I3, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) +
	(4*SU3D[I2, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) +
	(2*I)*SU3D[3, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6] +
	((2*I)*SU3D[8, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	(2*I)*SU3D[3, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6] +
	((2*I)*SU3D[8, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(2*I)*SU3D[3, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6] -
	((2*I)*SU3D[8, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	2*SU3D[I3, I4, k5]*SU3F[3, I2, k6]*SU3F[I1, k5, k6] +
	(2*SU3D[I3, I4, k5]*SU3F[8, I2, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	(2*SU3F[I1, I4, k5]*SU3F[I2, I3, k5])/3 - I*SU3D[3, I1, k5]*
	SU3D[I4, k5, k6]*SU3F[I2, I3, k6] -
	(I*SU3D[8, I1, k5]*SU3D[I4, k5, k6]*SU3F[I2, I3, k6])/Sqrt[3] -
	SU3D[I4, k5, k6]*SU3F[3, I1, k5]*SU3F[I2, I3, k6] +
	2*SU3D[I1, k5, k6]*SU3F[3, I4, k5]*SU3F[I2, I3, k6] -
	(SU3D[I4, k5, k6]*SU3F[8, I1, k5]*SU3F[I2, I3, k6])/Sqrt[3] +
	(2*SU3D[I1, k5, k6]*SU3F[8, I4, k5]*SU3F[I2, I3, k6])/Sqrt[3] +
	(2*I)*SU3F[3, I4, k5]*SU3F[I1, k5, k6]*SU3F[I2, I3, k6] +
	((2*I)*SU3F[8, I4, k5]*SU3F[I1, k5, k6]*SU3F[I2, I3, k6])/Sqrt[3] +
	(2*SU3F[I1, I3, k5]*SU3F[I2, I4, k5])/3 - I*SU3D[3, I1, k5]*
	SU3D[I3, k5, k6]*SU3F[I2, I4, k6] -
	(I*SU3D[8, I1, k5]*SU3D[I3, k5, k6]*SU3F[I2, I4, k6])/Sqrt[3] -
	SU3D[I3, k5, k6]*SU3F[3, I1, k5]*SU3F[I2, I4, k6] +
	2*SU3D[I1, k5, k6]*SU3F[3, I3, k5]*SU3F[I2, I4, k6] -
	(SU3D[I3, k5, k6]*SU3F[8, I1, k5]*SU3F[I2, I4, k6])/Sqrt[3] +
	(2*SU3D[I1, k5, k6]*SU3F[8, I3, k5]*SU3F[I2, I4, k6])/Sqrt[3] +
	(2*I)*SU3F[3, I3, k5]*SU3F[I1, k5, k6]*SU3F[I2, I4, k6] +
	((2*I)*SU3F[8, I3, k5]*SU3F[I1, k5, k6]*SU3F[I2, I4, k6])/Sqrt[3] +
	((4*I)/3)*SU3D[3, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6] +
	(((4*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	((4*I)/3)*SU3D[3, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6] +
	(((4*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	((4*I)/3)*SU3D[3, I1, k5]*SU3D[I3, I4, k6]*SU3F[I2, k5, k6] -
	(((4*I)/3)*SU3D[8, I1, k5]*SU3D[I3, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	(4*SU3D[I3, I4, k5]*SU3F[3, I1, k6]*SU3F[I2, k5, k6])/3 +
	(2*SU3D[I1, I4, k5]*SU3F[3, I3, k6]*SU3F[I2, k5, k6])/3 +
	(2*SU3D[I1, I3, k5]*SU3F[3, I4, k6]*SU3F[I2, k5, k6])/3 +
	(4*SU3D[I3, I4, k5]*SU3F[8, I1, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I4, k5]*SU3F[8, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I3, k5]*SU3F[8, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[3, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/3 +
	(2*SU3D[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	((4*I)/3)*SU3F[3, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6] +
	(((4*I)/3)*SU3F[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	(2*SU3D[3, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/3 +
	(2*SU3D[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	((4*I)/3)*SU3F[3, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6] +
	(((4*I)/3)*SU3F[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	((11*I)/3)*SU3D[3, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6] -
	(((11*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6])/
	Sqrt[3] + (I/3)*SU3D[3, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6] +
	((I/3)*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(I/3)*SU3D[3, I1, k5]*SU3D[I2, I4, k6]*SU3F[I3, k5, k6] -
	((I/3)*SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	(SU3D[I2, I4, k5]*SU3F[3, I1, k6]*SU3F[I3, k5, k6])/3 -
	(SU3D[I1, I4, k5]*SU3F[3, I2, k6]*SU3F[I3, k5, k6])/3 -
	(SU3D[I1, I2, k5]*SU3F[3, I4, k6]*SU3F[I3, k5, k6])/3 +
	(SU3D[I2, I4, k5]*SU3F[8, I1, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I4, k5]*SU3F[8, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I2, k5]*SU3F[8, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(SU3D[3, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/3 -
	(SU3D[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	(I/3)*SU3F[3, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6] +
	((I/3)*SU3F[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	(5*SU3D[3, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/3 +
	(5*SU3D[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	((5*I)/3)*SU3F[3, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6] -
	(((5*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	SU3D[3, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6] +
	(SU3D[8, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	I*SU3F[3, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6] -
	(I*SU3F[8, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	((11*I)/3)*SU3D[3, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6] -
	(((11*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6])/
	Sqrt[3] + (I/3)*SU3D[3, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6] +
	((I/3)*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(I/3)*SU3D[3, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6] -
	((I/3)*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(SU3D[I2, I3, k5]*SU3F[3, I1, k6]*SU3F[I4, k5, k6])/3 -
	(SU3D[I1, I3, k5]*SU3F[3, I2, k6]*SU3F[I4, k5, k6])/3 -
	(SU3D[I1, I2, k5]*SU3F[3, I3, k6]*SU3F[I4, k5, k6])/3 +
	(SU3D[I2, I3, k5]*SU3F[8, I1, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I3, k5]*SU3F[8, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I2, k5]*SU3F[8, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(SU3D[3, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/3 -
	(SU3D[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	(I/3)*SU3F[3, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6] +
	((I/3)*SU3F[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(5*SU3D[3, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/3 +
	(5*SU3D[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	((5*I)/3)*SU3F[3, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6] -
	(((5*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	SU3D[3, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6] +
	(SU3D[8, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	I*SU3F[3, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6] -
	(I*SU3F[8, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(4*SU3D[I2, I3, I4]*SUNDelta[3, I1])/3 -
	(8*SU3D[I1, I3, I4]*SUNDelta[3, I2])/9 -
	(2*SU3D[I1, I2, I4]*SUNDelta[3, I3])/9 + ((2*I)/3)*SU3F[I1, I2, I4]*
	SUNDelta[3, I3] - (2*SU3D[I1, I2, I3]*SUNDelta[3, I4])/9 +
	((2*I)/3)*SU3F[I1, I2, I3]*SUNDelta[3, I4] -
	(4*SU3D[I2, I3, I4]*SUNDelta[8, I1])/(3*Sqrt[3]) -
	(8*SU3D[I1, I3, I4]*SUNDelta[8, I2])/(9*Sqrt[3]) -
	(2*SU3D[I1, I2, I4]*SUNDelta[8, I3])/(9*Sqrt[3]) +
	(((2*I)/3)*SU3F[I1, I2, I4]*SUNDelta[8, I3])/Sqrt[3] -
	(2*SU3D[I1, I2, I3]*SUNDelta[8, I4])/(9*Sqrt[3]) +
	(((2*I)/3)*SU3F[I1, I2, I3]*SUNDelta[8, I4])/Sqrt[3] +
	(10*SU3D[3, I2, I4]*SUNDelta[I1, I3])/9 +
	(10*SU3D[8, I2, I4]*SUNDelta[I1, I3])/(9*Sqrt[3]) -
	((2*I)/3)*SU3F[3, I2, I4]*SUNDelta[I1, I3] -
	(((2*I)/3)*SU3F[8, I2, I4]*SUNDelta[I1, I3])/Sqrt[3] +
	(10*SU3D[3, I2, I3]*SUNDelta[I1, I4])/9 +
	(10*SU3D[8, I2, I3]*SUNDelta[I1, I4])/(9*Sqrt[3]) -
	((2*I)/3)*SU3F[3, I2, I3]*SUNDelta[I1, I4] -
	(((2*I)/3)*SU3F[8, I2, I3]*SUNDelta[I1, I4])/Sqrt[3] +
	(10*SU3D[3, I1, I4]*SUNDelta[I2, I3])/9 +
	(10*SU3D[8, I1, I4]*SUNDelta[I2, I3])/(9*Sqrt[3]) +
	((2*I)/9)*SU3F[3, I1, I4]*SUNDelta[I2, I3] +
	(((2*I)/9)*SU3F[8, I1, I4]*SUNDelta[I2, I3])/Sqrt[3] -
	(20*SUNDelta[I1, I4]*SUNDelta[I2, I3])/27 +
	(10*SU3D[3, I1, I3]*SUNDelta[I2, I4])/9 +
	(10*SU3D[8, I1, I3]*SUNDelta[I2, I4])/(9*Sqrt[3]) +
	((2*I)/9)*SU3F[3, I1, I3]*SUNDelta[I2, I4] +
	(((2*I)/9)*SU3F[8, I1, I3]*SUNDelta[I2, I4])/Sqrt[3] -
	(20*SUNDelta[I1, I3]*SUNDelta[I2, I4])/27 -
	(44*SU3D[3, I1, I2]*SUNDelta[I3, I4])/9 -
	(44*SU3D[8, I1, I2]*SUNDelta[I3, I4])/(9*Sqrt[3]) -
	((4*I)/9)*SU3F[3, I1, I2]*SUNDelta[I3, I4] -
	(((4*I)/9)*SU3F[8, I1, I2]*SUNDelta[I3, I4])/Sqrt[3] +
	(88*SUNDelta[I1, I2]*SUNDelta[I3, I4])/27) +
	CouplingConstant[ChPT3[4], 4, RenormalizationState[0]]*
	((-10*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/3 -
	(10*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/3 +
	(20*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/3 + 2*SU3F[I1, I4, k5]*
	SU3F[I2, I3, k5] + 2*SU3F[I1, I3, k5]*SU3F[I2, I4, k5] -
	(20*SUNDelta[I1, I4]*SUNDelta[I2, I3])/9 -
	(20*SUNDelta[I1, I3]*SUNDelta[I2, I4])/9 +
	(88*SUNDelta[I1, I2]*SUNDelta[I3, I4])/9))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3},
{(CouplingConstant[ChPT3[4], 5, RenormalizationState[0]]*
	((-10*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/9 - 2*SU3D[3, I4, k5]*
	SU3D[I1, k5, k6]*SU3D[I2, I3, k6] +
	(2*SU3D[8, I4, k5]*SU3D[I1, k5, k6]*SU3D[I2, I3, k6])/Sqrt[3] -
	(10*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/9 - 2*SU3D[3, I3, k5]*
	SU3D[I1, k5, k6]*SU3D[I2, I4, k6] +
	(2*SU3D[8, I3, k5]*SU3D[I1, k5, k6]*SU3D[I2, I4, k6])/Sqrt[3] -
	(4*SU3D[3, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/3 +
	(4*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[3, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/3 +
	(4*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) +
	(44*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/9 + 4*SU3D[3, k5, k6]*
	SU3D[I1, I2, k5]*SU3D[I3, I4, k6] -
	(4*SU3D[8, k5, k6]*SU3D[I1, I2, k5]*SU3D[I3, I4, k6])/Sqrt[3] +
	2*SU3D[3, I2, k5]*SU3D[I1, k5, k6]*SU3D[I3, I4, k6] -
	(2*SU3D[8, I2, k5]*SU3D[I1, k5, k6]*SU3D[I3, I4, k6])/Sqrt[3] +
	(4*SU3D[3, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/3 -
	(4*SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/(3*Sqrt[3]) +
	(11*SU3D[3, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/3 -
	(11*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) -
	(SU3D[3, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/3 +
	(SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(SU3D[3, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/3 -
	(SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(11*SU3D[3, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/3 -
	(11*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	(SU3D[3, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/3 +
	(SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) +
	(SU3D[3, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/3 -
	(SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	((4*I)/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[3, I1, k5] -
	(I/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[3, I1, k5] -
	(I/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[3, I1, k5] -
	(2*I)*SU3D[I1, k5, k6]*SU3D[I3, I4, k6]*SU3F[3, I2, k5] +
	(I/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[3, I2, k5] +
	(I/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[3, I2, k5] -
	((2*I)/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[3, I3, k5] +
	(I/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[3, I3, k5] -
	((2*I)/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[3, I4, k5] +
	(I/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[3, I4, k5] -
	(4*I)*SU3D[I1, I2, k3]*SU3D[I3, I4, k6]*SU3F[3, k3, k6] +
	(((4*I)/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	((I/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	((I/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] +
	((2*I)*SU3D[I1, k5, k6]*SU3D[I3, I4, k6]*SU3F[8, I2, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] -
	((I/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] +
	((4*I)*SU3D[I1, I2, k3]*SU3D[I3, I4, k6]*SU3F[8, k3, k6])/Sqrt[3] -
	(I/3)*SU3D[3, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6] +
	((I/3)*SU3D[8, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] -
	(I/3)*SU3D[3, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6] +
	((I/3)*SU3D[8, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] -
	(SU3D[I4, k5, k6]*SU3F[3, I3, k5]*SU3F[I1, I2, k6])/3 -
	(SU3D[I3, k5, k6]*SU3F[3, I4, k5]*SU3F[I1, I2, k6])/3 +
	(SU3D[I4, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) +
	(SU3D[I3, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) +
	((2*I)/3)*SU3D[3, I4, k5]*SU3D[I2, k5, k6]*SU3F[I1, I3, k6] -
	(((2*I)/3)*SU3D[8, I4, k5]*SU3D[I2, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] +
	((5*I)/3)*SU3D[3, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6] -
	(((5*I)/3)*SU3D[8, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] +
	(5*SU3D[I4, k5, k6]*SU3F[3, I2, k5]*SU3F[I1, I3, k6])/3 -
	(4*SU3D[I2, k5, k6]*SU3F[3, I4, k5]*SU3F[I1, I3, k6])/3 -
	(5*SU3D[I4, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) +
	(4*SU3D[I2, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I3, k6])/(3*Sqrt[3]) +
	((2*I)/3)*SU3D[3, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6] -
	(((2*I)/3)*SU3D[8, I3, k5]*SU3D[I2, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] +
	((5*I)/3)*SU3D[3, I2, k5]*SU3D[I3, k5, k6]*SU3F[I1, I4, k6] -
	(((5*I)/3)*SU3D[8, I2, k5]*SU3D[I3, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] +
	(5*SU3D[I3, k5, k6]*SU3F[3, I2, k5]*SU3F[I1, I4, k6])/3 -
	(4*SU3D[I2, k5, k6]*SU3F[3, I3, k5]*SU3F[I1, I4, k6])/3 -
	(5*SU3D[I3, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) +
	(4*SU3D[I2, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) -
	(2*I)*SU3D[3, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6] +
	((2*I)*SU3D[8, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(2*I)*SU3D[3, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6] +
	((2*I)*SU3D[8, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	(2*I)*SU3D[3, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6] -
	((2*I)*SU3D[8, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	2*SU3D[I3, I4, k5]*SU3F[3, I2, k6]*SU3F[I1, k5, k6] +
	(2*SU3D[I3, I4, k5]*SU3F[8, I2, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	(2*SU3F[I1, I4, k5]*SU3F[I2, I3, k5])/3 + I*SU3D[3, I1, k5]*
	SU3D[I4, k5, k6]*SU3F[I2, I3, k6] -
	(I*SU3D[8, I1, k5]*SU3D[I4, k5, k6]*SU3F[I2, I3, k6])/Sqrt[3] +
	SU3D[I4, k5, k6]*SU3F[3, I1, k5]*SU3F[I2, I3, k6] -
	2*SU3D[I1, k5, k6]*SU3F[3, I4, k5]*SU3F[I2, I3, k6] -
	(SU3D[I4, k5, k6]*SU3F[8, I1, k5]*SU3F[I2, I3, k6])/Sqrt[3] +
	(2*SU3D[I1, k5, k6]*SU3F[8, I4, k5]*SU3F[I2, I3, k6])/Sqrt[3] -
	(2*I)*SU3F[3, I4, k5]*SU3F[I1, k5, k6]*SU3F[I2, I3, k6] +
	((2*I)*SU3F[8, I4, k5]*SU3F[I1, k5, k6]*SU3F[I2, I3, k6])/Sqrt[3] +
	(2*SU3F[I1, I3, k5]*SU3F[I2, I4, k5])/3 + I*SU3D[3, I1, k5]*
	SU3D[I3, k5, k6]*SU3F[I2, I4, k6] -
	(I*SU3D[8, I1, k5]*SU3D[I3, k5, k6]*SU3F[I2, I4, k6])/Sqrt[3] +
	SU3D[I3, k5, k6]*SU3F[3, I1, k5]*SU3F[I2, I4, k6] -
	2*SU3D[I1, k5, k6]*SU3F[3, I3, k5]*SU3F[I2, I4, k6] -
	(SU3D[I3, k5, k6]*SU3F[8, I1, k5]*SU3F[I2, I4, k6])/Sqrt[3] +
	(2*SU3D[I1, k5, k6]*SU3F[8, I3, k5]*SU3F[I2, I4, k6])/Sqrt[3] -
	(2*I)*SU3F[3, I3, k5]*SU3F[I1, k5, k6]*SU3F[I2, I4, k6] +
	((2*I)*SU3F[8, I3, k5]*SU3F[I1, k5, k6]*SU3F[I2, I4, k6])/Sqrt[3] -
	((4*I)/3)*SU3D[3, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6] +
	(((4*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	((4*I)/3)*SU3D[3, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6] +
	(((4*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	((4*I)/3)*SU3D[3, I1, k5]*SU3D[I3, I4, k6]*SU3F[I2, k5, k6] -
	(((4*I)/3)*SU3D[8, I1, k5]*SU3D[I3, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(4*SU3D[I3, I4, k5]*SU3F[3, I1, k6]*SU3F[I2, k5, k6])/3 -
	(2*SU3D[I1, I4, k5]*SU3F[3, I3, k6]*SU3F[I2, k5, k6])/3 -
	(2*SU3D[I1, I3, k5]*SU3F[3, I4, k6]*SU3F[I2, k5, k6])/3 +
	(4*SU3D[I3, I4, k5]*SU3F[8, I1, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I4, k5]*SU3F[8, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I3, k5]*SU3F[8, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(2*SU3D[3, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/3 +
	(2*SU3D[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	((4*I)/3)*SU3F[3, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6] +
	(((4*I)/3)*SU3F[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(2*SU3D[3, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/3 +
	(2*SU3D[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	((4*I)/3)*SU3F[3, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6] +
	(((4*I)/3)*SU3F[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	((11*I)/3)*SU3D[3, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6] -
	(((11*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6])/
	Sqrt[3] - (I/3)*SU3D[3, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6] +
	((I/3)*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	(I/3)*SU3D[3, I1, k5]*SU3D[I2, I4, k6]*SU3F[I3, k5, k6] -
	((I/3)*SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(SU3D[I2, I4, k5]*SU3F[3, I1, k6]*SU3F[I3, k5, k6])/3 +
	(SU3D[I1, I4, k5]*SU3F[3, I2, k6]*SU3F[I3, k5, k6])/3 +
	(SU3D[I1, I2, k5]*SU3F[3, I4, k6]*SU3F[I3, k5, k6])/3 +
	(SU3D[I2, I4, k5]*SU3F[8, I1, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I4, k5]*SU3F[8, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I2, k5]*SU3F[8, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	(SU3D[3, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/3 -
	(SU3D[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(I/3)*SU3F[3, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6] +
	((I/3)*SU3F[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(5*SU3D[3, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/3 +
	(5*SU3D[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	((5*I)/3)*SU3F[3, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6] -
	(((5*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	SU3D[3, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6] +
	(SU3D[8, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	I*SU3F[3, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6] -
	(I*SU3F[8, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] +
	((11*I)/3)*SU3D[3, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6] -
	(((11*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3F[I4, k5, k6])/
	Sqrt[3] - (I/3)*SU3D[3, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6] +
	((I/3)*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(I/3)*SU3D[3, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6] -
	((I/3)*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(SU3D[I2, I3, k5]*SU3F[3, I1, k6]*SU3F[I4, k5, k6])/3 +
	(SU3D[I1, I3, k5]*SU3F[3, I2, k6]*SU3F[I4, k5, k6])/3 +
	(SU3D[I1, I2, k5]*SU3F[3, I3, k6]*SU3F[I4, k5, k6])/3 +
	(SU3D[I2, I3, k5]*SU3F[8, I1, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I3, k5]*SU3F[8, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(SU3D[I1, I2, k5]*SU3F[8, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	(SU3D[3, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/3 -
	(SU3D[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(I/3)*SU3F[3, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6] +
	((I/3)*SU3F[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(5*SU3D[3, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/3 +
	(5*SU3D[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	((5*I)/3)*SU3F[3, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6] -
	(((5*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	SU3D[3, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6] +
	(SU3D[8, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	I*SU3F[3, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6] -
	(I*SU3F[8, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(4*SU3D[I2, I3, I4]*SUNDelta[3, I1])/3 +
	(8*SU3D[I1, I3, I4]*SUNDelta[3, I2])/9 +
	(2*SU3D[I1, I2, I4]*SUNDelta[3, I3])/9 - ((2*I)/3)*SU3F[I1, I2, I4]*
	SUNDelta[3, I3] + (2*SU3D[I1, I2, I3]*SUNDelta[3, I4])/9 -
	((2*I)/3)*SU3F[I1, I2, I3]*SUNDelta[3, I4] -
	(4*SU3D[I2, I3, I4]*SUNDelta[8, I1])/(3*Sqrt[3]) -
	(8*SU3D[I1, I3, I4]*SUNDelta[8, I2])/(9*Sqrt[3]) -
	(2*SU3D[I1, I2, I4]*SUNDelta[8, I3])/(9*Sqrt[3]) +
	(((2*I)/3)*SU3F[I1, I2, I4]*SUNDelta[8, I3])/Sqrt[3] -
	(2*SU3D[I1, I2, I3]*SUNDelta[8, I4])/(9*Sqrt[3]) +
	(((2*I)/3)*SU3F[I1, I2, I3]*SUNDelta[8, I4])/Sqrt[3] -
	(10*SU3D[3, I2, I4]*SUNDelta[I1, I3])/9 +
	(10*SU3D[8, I2, I4]*SUNDelta[I1, I3])/(9*Sqrt[3]) +
	((2*I)/3)*SU3F[3, I2, I4]*SUNDelta[I1, I3] -
	(((2*I)/3)*SU3F[8, I2, I4]*SUNDelta[I1, I3])/Sqrt[3] -
	(10*SU3D[3, I2, I3]*SUNDelta[I1, I4])/9 +
	(10*SU3D[8, I2, I3]*SUNDelta[I1, I4])/(9*Sqrt[3]) +
	((2*I)/3)*SU3F[3, I2, I3]*SUNDelta[I1, I4] -
	(((2*I)/3)*SU3F[8, I2, I3]*SUNDelta[I1, I4])/Sqrt[3] -
	(10*SU3D[3, I1, I4]*SUNDelta[I2, I3])/9 +
	(10*SU3D[8, I1, I4]*SUNDelta[I2, I3])/(9*Sqrt[3]) -
	((2*I)/9)*SU3F[3, I1, I4]*SUNDelta[I2, I3] +
	(((2*I)/9)*SU3F[8, I1, I4]*SUNDelta[I2, I3])/Sqrt[3] -
	(20*SUNDelta[I1, I4]*SUNDelta[I2, I3])/27 -
	(10*SU3D[3, I1, I3]*SUNDelta[I2, I4])/9 +
	(10*SU3D[8, I1, I3]*SUNDelta[I2, I4])/(9*Sqrt[3]) -
	((2*I)/9)*SU3F[3, I1, I3]*SUNDelta[I2, I4] +
	(((2*I)/9)*SU3F[8, I1, I3]*SUNDelta[I2, I4])/Sqrt[3] -
	(20*SUNDelta[I1, I3]*SUNDelta[I2, I4])/27 +
	(44*SU3D[3, I1, I2]*SUNDelta[I3, I4])/9 -
	(44*SU3D[8, I1, I2]*SUNDelta[I3, I4])/(9*Sqrt[3]) +
	((4*I)/9)*SU3F[3, I1, I2]*SUNDelta[I3, I4] -
	(((4*I)/9)*SU3F[8, I1, I2]*SUNDelta[I3, I4])/Sqrt[3] +
	(88*SUNDelta[I1, I2]*SUNDelta[I3, I4])/27) +
	CouplingConstant[ChPT3[4], 4, RenormalizationState[0]]*
	((-10*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/3 -
	(10*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/3 +
	(20*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/3 + 2*SU3F[I1, I4, k5]*
	SU3F[I2, I3, k5] + 2*SU3F[I1, I3, k5]*SU3F[I2, I4, k5] -
	(20*SUNDelta[I1, I4]*SUNDelta[I2, I3])/9 -
	(20*SUNDelta[I1, I3]*SUNDelta[I2, I4])/9 +
	(88*SUNDelta[I1, I2]*SUNDelta[I3, I4])/9))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3},
{(CouplingConstant[ChPT3[4], 5, RenormalizationState[0]]*
	((-10*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/9 -
	(4*SU3D[8, I4, k5]*SU3D[I1, k5, k6]*SU3D[I2, I3, k6])/Sqrt[3] -
	(10*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/9 -
	(4*SU3D[8, I3, k5]*SU3D[I1, k5, k6]*SU3D[I2, I4, k6])/Sqrt[3] -
	(8*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) -
	(8*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3D[I2, k5, k6])/(3*Sqrt[3]) +
	(44*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/9 +
	(8*SU3D[8, k5, k6]*SU3D[I1, I2, k5]*SU3D[I3, I4, k6])/Sqrt[3] +
	(4*SU3D[8, I2, k5]*SU3D[I1, k5, k6]*SU3D[I3, I4, k6])/Sqrt[3] +
	(8*SU3D[8, I1, k5]*SU3D[I2, k5, k6]*SU3D[I3, I4, k6])/(3*Sqrt[3]) +
	(22*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) -
	(2*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[8, I1, k5]*SU3D[I2, I4, k6]*SU3D[I3, k5, k6])/(3*Sqrt[3]) +
	(22*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	(2*SU3D[8, I2, k5]*SU3D[I1, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3D[I4, k5, k6])/(3*Sqrt[3]) -
	(((8*I)/3)*SU3D[I2, k5, k6]*SU3D[I3, I4, k6]*SU3F[8, I1, k5])/Sqrt[3] -
	(((2*I)/3)*SU3D[I2, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] -
	(((2*I)/3)*SU3D[I2, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I1, k5])/Sqrt[3] -
	((4*I)*SU3D[I1, k5, k6]*SU3D[I3, I4, k6]*SU3F[8, I2, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I4, k6]*SU3D[I3, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I3, k6]*SU3D[I4, k5, k6]*SU3F[8, I2, k5])/Sqrt[3] -
	(((4*I)/3)*SU3D[I1, I4, k6]*SU3D[I2, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I2, k6]*SU3D[I4, k5, k6]*SU3F[8, I3, k5])/Sqrt[3] -
	(((4*I)/3)*SU3D[I1, I3, k6]*SU3D[I2, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] +
	(((2*I)/3)*SU3D[I1, I2, k6]*SU3D[I3, k5, k6]*SU3F[8, I4, k5])/Sqrt[3] -
	((8*I)*SU3D[I1, I2, k3]*SU3D[I3, I4, k6]*SU3F[8, k3, k6])/Sqrt[3] -
	(((2*I)/3)*SU3D[8, I4, k5]*SU3D[I3, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] -
	(((2*I)/3)*SU3D[8, I3, k5]*SU3D[I4, k5, k6]*SU3F[I1, I2, k6])/Sqrt[3] -
	(2*SU3D[I4, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) -
	(2*SU3D[I3, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I2, k6])/(3*Sqrt[3]) +
	(((4*I)/3)*SU3D[8, I4, k5]*SU3D[I2, k5, k6]*SU3F[I1, I3, k6])/Sqrt[3] +
	(((10*I)/3)*SU3D[8, I2, k5]*SU3D[I4, k5, k6]*SU3F[I1, I3, k6])/
	Sqrt[3] + (10*SU3D[I4, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I3, k6])/
	(3*Sqrt[3]) - (8*SU3D[I2, k5, k6]*SU3F[8, I4, k5]*SU3F[I1, I3, k6])/
	(3*Sqrt[3]) + (((4*I)/3)*SU3D[8, I3, k5]*SU3D[I2, k5, k6]*
		SU3F[I1, I4, k6])/Sqrt[3] + (((10*I)/3)*SU3D[8, I2, k5]*
		SU3D[I3, k5, k6]*SU3F[I1, I4, k6])/Sqrt[3] +
	(10*SU3D[I3, k5, k6]*SU3F[8, I2, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) -
	(8*SU3D[I2, k5, k6]*SU3F[8, I3, k5]*SU3F[I1, I4, k6])/(3*Sqrt[3]) -
	((4*I)*SU3D[8, I4, k5]*SU3D[I2, I3, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	((4*I)*SU3D[8, I3, k5]*SU3D[I2, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	((4*I)*SU3D[8, I2, k5]*SU3D[I3, I4, k6]*SU3F[I1, k5, k6])/Sqrt[3] -
	(4*SU3D[I3, I4, k5]*SU3F[8, I2, k6]*SU3F[I1, k5, k6])/Sqrt[3] +
	(2*SU3F[I1, I4, k5]*SU3F[I2, I3, k5])/3 +
	((2*I)*SU3D[8, I1, k5]*SU3D[I4, k5, k6]*SU3F[I2, I3, k6])/Sqrt[3] +
	(2*SU3D[I4, k5, k6]*SU3F[8, I1, k5]*SU3F[I2, I3, k6])/Sqrt[3] -
	(4*SU3D[I1, k5, k6]*SU3F[8, I4, k5]*SU3F[I2, I3, k6])/Sqrt[3] -
	((4*I)*SU3F[8, I4, k5]*SU3F[I1, k5, k6]*SU3F[I2, I3, k6])/Sqrt[3] +
	(2*SU3F[I1, I3, k5]*SU3F[I2, I4, k5])/3 +
	((2*I)*SU3D[8, I1, k5]*SU3D[I3, k5, k6]*SU3F[I2, I4, k6])/Sqrt[3] +
	(2*SU3D[I3, k5, k6]*SU3F[8, I1, k5]*SU3F[I2, I4, k6])/Sqrt[3] -
	(4*SU3D[I1, k5, k6]*SU3F[8, I3, k5]*SU3F[I2, I4, k6])/Sqrt[3] -
	((4*I)*SU3F[8, I3, k5]*SU3F[I1, k5, k6]*SU3F[I2, I4, k6])/Sqrt[3] -
	(((8*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(((8*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	(((8*I)/3)*SU3D[8, I1, k5]*SU3D[I3, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(8*SU3D[I3, I4, k5]*SU3F[8, I1, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[I1, I4, k5]*SU3F[8, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[I1, I3, k5]*SU3F[8, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(4*SU3D[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(((8*I)/3)*SU3F[8, I4, k5]*SU3F[I1, I3, k6]*SU3F[I2, k5, k6])/Sqrt[3] -
	(4*SU3D[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/(3*Sqrt[3]) -
	(((8*I)/3)*SU3F[8, I3, k5]*SU3F[I1, I4, k6]*SU3F[I2, k5, k6])/Sqrt[3] +
	(((22*I)/3)*SU3D[8, I4, k5]*SU3D[I1, I2, k6]*SU3F[I3, k5, k6])/
	Sqrt[3] - (((2*I)/3)*SU3D[8, I2, k5]*SU3D[I1, I4, k6]*
		SU3F[I3, k5, k6])/Sqrt[3] + (((2*I)/3)*SU3D[8, I1, k5]*
		SU3D[I2, I4, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(2*SU3D[I2, I4, k5]*SU3F[8, I1, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I4, k5]*SU3F[8, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I2, k5]*SU3F[8, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) -
	(((2*I)/3)*SU3F[8, I4, k5]*SU3F[I1, I2, k6]*SU3F[I3, k5, k6])/Sqrt[3] -
	(10*SU3D[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/(3*Sqrt[3]) +
	(((10*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I4, k6]*SU3F[I3, k5, k6])/
	Sqrt[3] - (2*SU3D[8, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6])/
	Sqrt[3] + ((2*I)*SU3F[8, I1, k5]*SU3F[I2, I4, k6]*SU3F[I3, k5, k6])/
	Sqrt[3] + (((22*I)/3)*SU3D[8, I3, k5]*SU3D[I1, I2, k6]*
		SU3F[I4, k5, k6])/Sqrt[3] - (((2*I)/3)*SU3D[8, I2, k5]*
		SU3D[I1, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] +
	(((2*I)/3)*SU3D[8, I1, k5]*SU3D[I2, I3, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(2*SU3D[I2, I3, k5]*SU3F[8, I1, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I3, k5]*SU3F[8, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[I1, I2, k5]*SU3F[8, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	(2*SU3D[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) -
	(((2*I)/3)*SU3F[8, I3, k5]*SU3F[I1, I2, k6]*SU3F[I4, k5, k6])/Sqrt[3] -
	(10*SU3D[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/(3*Sqrt[3]) +
	(((10*I)/3)*SU3F[8, I2, k5]*SU3F[I1, I3, k6]*SU3F[I4, k5, k6])/
	Sqrt[3] - (2*SU3D[8, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6])/
	Sqrt[3] + ((2*I)*SU3F[8, I1, k5]*SU3F[I2, I3, k6]*SU3F[I4, k5, k6])/
	Sqrt[3] + (8*SU3D[I2, I3, I4]*SUNDelta[8, I1])/(3*Sqrt[3]) +
	(16*SU3D[I1, I3, I4]*SUNDelta[8, I2])/(9*Sqrt[3]) +
	(4*SU3D[I1, I2, I4]*SUNDelta[8, I3])/(9*Sqrt[3]) -
	(((4*I)/3)*SU3F[I1, I2, I4]*SUNDelta[8, I3])/Sqrt[3] +
	(4*SU3D[I1, I2, I3]*SUNDelta[8, I4])/(9*Sqrt[3]) -
	(((4*I)/3)*SU3F[I1, I2, I3]*SUNDelta[8, I4])/Sqrt[3] -
	(20*SU3D[8, I2, I4]*SUNDelta[I1, I3])/(9*Sqrt[3]) +
	(((4*I)/3)*SU3F[8, I2, I4]*SUNDelta[I1, I3])/Sqrt[3] -
	(20*SU3D[8, I2, I3]*SUNDelta[I1, I4])/(9*Sqrt[3]) +
	(((4*I)/3)*SU3F[8, I2, I3]*SUNDelta[I1, I4])/Sqrt[3] -
	(20*SU3D[8, I1, I4]*SUNDelta[I2, I3])/(9*Sqrt[3]) -
	(((4*I)/9)*SU3F[8, I1, I4]*SUNDelta[I2, I3])/Sqrt[3] -
	(20*SUNDelta[I1, I4]*SUNDelta[I2, I3])/27 -
	(20*SU3D[8, I1, I3]*SUNDelta[I2, I4])/(9*Sqrt[3]) -
	(((4*I)/9)*SU3F[8, I1, I3]*SUNDelta[I2, I4])/Sqrt[3] -
	(20*SUNDelta[I1, I3]*SUNDelta[I2, I4])/27 +
	(88*SU3D[8, I1, I2]*SUNDelta[I3, I4])/(9*Sqrt[3]) +
	(((8*I)/9)*SU3F[8, I1, I2]*SUNDelta[I3, I4])/Sqrt[3] +
	(88*SUNDelta[I1, I2]*SUNDelta[I3, I4])/27) +
	CouplingConstant[ChPT3[4], 4, RenormalizationState[0]]*
	((-10*SU3D[I1, I4, k5]*SU3D[I2, I3, k5])/3 -
	(10*SU3D[I1, I3, k5]*SU3D[I2, I4, k5])/3 +
	(20*SU3D[I1, I2, k5]*SU3D[I3, I4, k5])/3 + 2*SU3F[I1, I4, k5]*
	SU3F[I2, I3, k5] + 2*SU3F[I1, I3, k5]*SU3F[I2, I4, k5] -
	(20*SUNDelta[I1, I4]*SUNDelta[I2, I3])/9 -
	(20*SUNDelta[I1, I3]*SUNDelta[I2, I4])/9 +
	(88*SUNDelta[I1, I2]*SUNDelta[I3, I4])/9))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3},
{(CouplingConstant[ChPT3[4], 2, RenormalizationState[0]]*
	(16*SUNDelta[I1, I4]*SUNDelta[I2, I3] + 16*SUNDelta[I1, I3]*
	SUNDelta[I2, I4]) + 32*CouplingConstant[ChPT3[4], 1,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	CouplingConstant[ChPT3[4], 3, RenormalizationState[0]]*
	(16*SU3D[I1, I2, k5]*SU3D[I3, I4, k5] +
	(32*SUNDelta[I1, I2]*SUNDelta[I3, I4])/3))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3},
{(32*CouplingConstant[ChPT3[4], 1, RenormalizationState[0]]*SUNDelta[I1, I3]*
	SUNDelta[I2, I4] + CouplingConstant[ChPT3[4], 3,
	RenormalizationState[0]]*(16*SU3D[I1, I3, k5]*SU3D[I2, I4, k5] +
	(32*SUNDelta[I1, I3]*SUNDelta[I2, I4])/3) +
	CouplingConstant[ChPT3[4], 2, RenormalizationState[0]]*
	(16*SUNDelta[I1, I4]*SUNDelta[I2, I3] + 16*SUNDelta[I1, I2]*
	SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[1],
	RenormalizationState[0]]^3},
{(32*CouplingConstant[ChPT3[4], 1, RenormalizationState[0]]*SUNDelta[I1, I4]*
	SUNDelta[I2, I3] + CouplingConstant[ChPT3[4], 3,
	RenormalizationState[0]]*(16*SU3D[I1, I4, k5]*SU3D[I2, I3, k5] +
	(32*SUNDelta[I1, I4]*SUNDelta[I2, I3])/3) +
	CouplingConstant[ChPT3[4], 2, RenormalizationState[0]]*
	(16*SUNDelta[I1, I3]*SUNDelta[I2, I4] + 16*SUNDelta[I1, I2]*
	SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[1],
	RenormalizationState[0]]^3}}
