{{((-I/3)*(SUNDelta[I1, I4]*SUNDelta[I2, I3] + SUNDelta[I1, I3]*
	SUNDelta[I2, I4] - 2*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{((-I/3)*(SUNDelta[I1, I4]*SUNDelta[I2, I3] + SUNDelta[I1, I3]*
	SUNDelta[I2, I4] - 2*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{((-I/3)*(SUNDelta[I1, I4]*SUNDelta[I2, I3] - 2*SUNDelta[I1, I3]*
	SUNDelta[I2, I4] + SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{((-I/3)*(SUNDelta[I1, I4]*SUNDelta[I2, I3] - 2*SUNDelta[I1, I3]*
	SUNDelta[I2, I4] + SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{((I/3)*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3] - SUNDelta[I1, I3]*
	SUNDelta[I2, I4] - SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{((I/3)*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3] - SUNDelta[I1, I3]*
	SUNDelta[I2, I4] - SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{((I/3)*(SUNDelta[I1, I4]*SUNDelta[I2, I3] + SUNDelta[I1, I3]*
	SUNDelta[I2, I4] + SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}}
