{{(I*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 19]*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] +
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{(I*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 19]*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] +
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{((-I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 19]*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] +
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{((-I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 20]*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] +
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{((I/2)*CouplingConstant[ChPTW3[2], 1]*
	(CouplingConstant[ChPTW3[4], 25]*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] +
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]) -
	(CouplingConstant[ChPTW3[4], 20] - CouplingConstant[ChPTW3[4], 26])*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]])))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{((-I/2)*CouplingConstant[ChPTW3[2], 1]*
	(CouplingConstant[ChPTW3[4], 25]*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] +
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]) +
	(CouplingConstant[ChPTW3[4], 20] + CouplingConstant[ChPTW3[4], 26])*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]])))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{((-I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 20]*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{((I/2)*CouplingConstant[ChPTW3[2], 1]*
	(CouplingConstant[ChPTW3[4], 25]*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]) -
	(CouplingConstant[ChPTW3[4], 20] - CouplingConstant[ChPTW3[4], 26])*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]])))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{((-I/2)*CouplingConstant[ChPTW3[2], 1]*
	(CouplingConstant[ChPTW3[4], 25]*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]) +
	(CouplingConstant[ChPTW3[4], 20] + CouplingConstant[ChPTW3[4], 26])*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]])))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I3]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{-(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I3]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I2]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{-(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I2]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{-(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I3]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I3]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I1]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{-(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I1]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{-(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I1]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I1]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{-(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I2]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I2]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{-(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I1]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I1]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I1]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{-(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I1]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{-(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I3]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I3]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I1]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{-(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
	UMatrix[UGenerator[I1]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{-(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I2]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
	UMatrix[UGenerator[I2]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I1]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{-(CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 32]*
	Eps[\[Mu], \[Nu], \[Rho], \[Sigma]]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
	UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
	UMatrix[UGenerator[I1]]]])/
(2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)},
{((I/24)*CouplingConstant[ChPTW3[2], 1]*
	(4*CouplingConstant[ChPTW3[4], 24]*
	(3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] + Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] + Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I3]]]]*(UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]) +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]]]]*(UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]) -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] - Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] - Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] - Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]) + 2*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] +
	2*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] -
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] -
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] -
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	4*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] +
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] +
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] +
	2*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
	4*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	2*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] -
	3*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] - 3*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] - 3*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] - 3*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]]]] + 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I3]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]]]] + 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I3]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I3]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 3*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
	Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	3*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	6*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 3*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
	Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	3*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	2*CouplingConstant[ChPTW3[4], 21]*
	(4*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] +
	4*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] -
	4*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] -
	4*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{((-I/24)*CouplingConstant[ChPTW3[2], 1]*
	(4*CouplingConstant[ChPTW3[4], 24]*
	(3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I3]]]]*(UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]) -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] + Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] + Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]]]]*
		(-UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]) -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] + Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] + Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]) - 2*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] -
	2*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] +
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] +
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] +
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	4*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] -
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] -
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] -
	2*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] -
	4*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	8*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	2*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] -
	3*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] - 3*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] - 3*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] - 3*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]]]] + 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I3]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]]]] + 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I3]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 3*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
	Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	3*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	6*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 12*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 3*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
	Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	3*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	2*CouplingConstant[ChPTW3[4], 21]*
	(4*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] +
	4*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] -
	4*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] -
	4*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{((-I/12)*CouplingConstant[ChPTW3[2], 1]*
	(4*Sqrt[3]*CouplingConstant[ChPTW3[4], 24]*
	(UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]]]]*(UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]) +
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]]*(UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]) +
	(UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]])*
		(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] -
		UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]])) -
	CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] -
	CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] +
	4*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] +
	4*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] +
	4*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	4*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	2*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] -
	4*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] -
	4*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] -
	CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] -
	2*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	4*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	4*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] -
	Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	2*CouplingConstant[ChPTW3[4], 21]*
	(2*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]]]] +
	2*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]]]] -
	2*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]]]] -
	2*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}}
