{{-(CouplingConstant[ChPTW3[2], 1]*(18*SU3D[6, I4, k6]*SU3D[I1, k6, k7]*
	SU3D[I2, I3, k7] + 18*SU3D[6, I3, k6]*SU3D[I1, k6, k7]*
	SU3D[I2, I4, k7] + 12*SU3D[6, I4, k7]*SU3D[I1, I3, k5]*
	SU3D[I2, k5, k7] + 12*SU3D[6, I3, k7]*SU3D[I1, I4, k5]*
	SU3D[I2, k5, k7] - 18*SU3D[6, I2, k7]*SU3D[I1, k5, k7]*
	SU3D[I3, I4, k5] - 12*SU3D[6, I1, k7]*SU3D[I2, k5, k7]*
	SU3D[I3, I4, k5] - 15*SU3D[6, I4, k7]*SU3D[I1, I2, k5]*
	SU3D[I3, k5, k7] + 3*SU3D[6, I2, k7]*SU3D[I1, I4, k5]*
	SU3D[I3, k5, k7] - 3*SU3D[6, I1, k7]*SU3D[I2, I4, k5]*
	SU3D[I3, k5, k7] - 15*SU3D[6, I3, k7]*SU3D[I1, I2, k5]*
	SU3D[I4, k5, k7] + 3*SU3D[6, I2, k7]*SU3D[I1, I3, k5]*
	SU3D[I4, k5, k7] - 3*SU3D[6, I1, k7]*SU3D[I2, I3, k5]*
	SU3D[I4, k5, k7] - (12*I)*SU3D[I2, k5, k6]*SU3D[I3, I4, k5]*
	SU3F[6, I1, k6] - (3*I)*SU3D[I2, I4, k5]*SU3D[I3, k5, k6]*
	SU3F[6, I1, k6] - (3*I)*SU3D[I2, I3, k5]*SU3D[I4, k5, k6]*
	SU3F[6, I1, k6] - (18*I)*SU3D[I1, k5, k6]*SU3D[I3, I4, k5]*
	SU3F[6, I2, k6] + (3*I)*SU3D[I1, I4, k5]*SU3D[I3, k5, k6]*
	SU3F[6, I2, k6] + (3*I)*SU3D[I1, I3, k5]*SU3D[I4, k5, k6]*
	SU3F[6, I2, k6] + (18*I)*SU3D[I1, k5, k6]*SU3D[I2, I4, k5]*
	SU3F[6, I3, k6] + (12*I)*SU3D[I1, I4, k5]*SU3D[I2, k5, k6]*
	SU3F[6, I3, k6] - (15*I)*SU3D[I1, I2, k5]*SU3D[I4, k5, k6]*
	SU3F[6, I3, k6] + (18*I)*SU3D[I1, k5, k6]*SU3D[I2, I3, k5]*
	SU3F[6, I4, k6] + (12*I)*SU3D[I1, I3, k5]*SU3D[I2, k5, k6]*
	SU3F[6, I4, k6] - (15*I)*SU3D[I1, I2, k5]*SU3D[I3, k5, k6]*
	SU3F[6, I4, k6] - (3*I)*SU3D[6, I4, k6]*SU3D[I3, k5, k6]*
	SU3F[I1, I2, k5] - (3*I)*SU3D[6, I3, k6]*SU3D[I4, k5, k6]*
	SU3F[I1, I2, k5] + 3*SU3D[I4, k5, k6]*SU3F[6, I3, k6]*
	SU3F[I1, I2, k5] + 3*SU3D[I3, k5, k6]*SU3F[6, I4, k6]*
	SU3F[I1, I2, k5] + (6*I)*SU3D[6, I4, k6]*SU3D[I2, k5, k6]*
	SU3F[I1, I3, k5] + (15*I)*SU3D[6, I2, k6]*SU3D[I4, k5, k6]*
	SU3F[I1, I3, k5] - 15*SU3D[I4, k5, k6]*SU3F[6, I2, k6]*
	SU3F[I1, I3, k5] - 6*SU3D[I2, k5, k6]*SU3F[6, I4, k6]*
	SU3F[I1, I3, k5] + (6*I)*SU3D[6, I3, k6]*SU3D[I2, k5, k6]*
	SU3F[I1, I4, k5] + (15*I)*SU3D[6, I2, k6]*SU3D[I3, k5, k6]*
	SU3F[I1, I4, k5] - 15*SU3D[I3, k5, k6]*SU3F[6, I2, k6]*
	SU3F[I1, I4, k5] - 6*SU3D[I2, k5, k6]*SU3F[6, I3, k6]*
	SU3F[I1, I4, k5] + (9*I)*SU3D[6, I4, k7]*SU3D[I2, I3, k5]*
	SU3F[I1, k5, k7] - (9*I)*SU3D[6, I4, k5]*SU3D[I2, I3, k7]*
	SU3F[I1, k5, k7] + (9*I)*SU3D[6, I3, k7]*SU3D[I2, I4, k5]*
	SU3F[I1, k5, k7] - (9*I)*SU3D[6, I3, k5]*SU3D[I2, I4, k7]*
	SU3F[I1, k5, k7] + (18*I)*SU3D[6, I2, k5]*SU3D[I3, I4, k7]*
	SU3F[I1, k5, k7] + 18*SU3D[I3, I4, k5]*SU3F[6, I2, k7]*
	SU3F[I1, k5, k7] - 18*SU3D[I2, I4, k5]*SU3F[6, I3, k7]*
	SU3F[I1, k5, k7] - 18*SU3D[I2, I3, k5]*SU3F[6, I4, k7]*
	SU3F[I1, k5, k7] + (6*I)*SU3D[6, I1, k6]*SU3D[I4, k5, k6]*
	SU3F[I2, I3, k5] - 9*SU3D[I4, k5, k6]*SU3F[6, I1, k6]*
	SU3F[I2, I3, k5] - (9*I)*SU3F[6, I4, k7]*SU3F[I1, k6, k7]*
	SU3F[I2, I3, k6] + (3*I)*SU3D[6, I1, k6]*SU3D[I4, k6, k7]*
	SU3F[I2, I3, k7] - 9*SU3D[6, I4, k5]*SU3F[I1, k5, k7]*
	SU3F[I2, I3, k7] + 9*SU3D[6, I4, k6]*SU3F[I1, k6, k7]*
	SU3F[I2, I3, k7] - (9*I)*SU3F[6, I4, k6]*SU3F[I1, k6, k7]*
	SU3F[I2, I3, k7] + (6*I)*SU3D[6, I1, k6]*SU3D[I3, k5, k6]*
	SU3F[I2, I4, k5] - 9*SU3D[I3, k5, k6]*SU3F[6, I1, k6]*
	SU3F[I2, I4, k5] - (9*I)*SU3F[6, I3, k7]*SU3F[I1, k6, k7]*
	SU3F[I2, I4, k6] + (3*I)*SU3D[6, I1, k6]*SU3D[I3, k6, k7]*
	SU3F[I2, I4, k7] - 9*SU3D[6, I3, k5]*SU3F[I1, k5, k7]*
	SU3F[I2, I4, k7] + 9*SU3D[6, I3, k6]*SU3F[I1, k6, k7]*
	SU3F[I2, I4, k7] - (9*I)*SU3F[6, I3, k6]*SU3F[I1, k6, k7]*
	SU3F[I2, I4, k7] + (3*I)*SU3D[6, I4, k7]*SU3D[I1, I3, k5]*
	SU3F[I2, k5, k7] - (9*I)*SU3D[6, I4, k5]*SU3D[I1, I3, k7]*
	SU3F[I2, k5, k7] + (3*I)*SU3D[6, I3, k7]*SU3D[I1, I4, k5]*
	SU3F[I2, k5, k7] - (9*I)*SU3D[6, I3, k5]*SU3D[I1, I4, k7]*
	SU3F[I2, k5, k7] + (12*I)*SU3D[6, I1, k5]*SU3D[I3, I4, k7]*
	SU3F[I2, k5, k7] + 12*SU3D[I3, I4, k5]*SU3F[6, I1, k7]*
	SU3F[I2, k5, k7] - 12*SU3D[I1, I4, k5]*SU3F[6, I3, k7]*
	SU3F[I2, k5, k7] - 12*SU3D[I1, I3, k5]*SU3F[6, I4, k7]*
	SU3F[I2, k5, k7] + 9*SU3D[6, I4, k5]*SU3F[I1, I3, k7]*
	SU3F[I2, k5, k7] + 9*SU3D[6, I3, k5]*SU3F[I1, I4, k7]*
	SU3F[I2, k5, k7] - 3*SU3D[6, I4, k6]*SU3F[I1, I3, k7]*
	SU3F[I2, k6, k7] + (6*I)*SU3F[6, I4, k6]*SU3F[I1, I3, k7]*
	SU3F[I2, k6, k7] - 3*SU3D[6, I3, k6]*SU3F[I1, I4, k7]*
	SU3F[I2, k6, k7] + (6*I)*SU3F[6, I3, k6]*SU3F[I1, I4, k7]*
	SU3F[I2, k6, k7] + (15*I)*SU3D[6, I4, k5]*SU3D[I1, I2, k7]*
	SU3F[I3, k5, k7] - (3*I)*SU3D[6, I2, k5]*SU3D[I1, I4, k7]*
	SU3F[I3, k5, k7] + (3*I)*SU3D[6, I1, k5]*SU3D[I2, I4, k7]*
	SU3F[I3, k5, k7] + 3*SU3D[I2, I4, k5]*SU3F[6, I1, k7]*
	SU3F[I3, k5, k7] - 3*SU3D[I1, I4, k5]*SU3F[6, I2, k7]*
	SU3F[I3, k5, k7] + 15*SU3D[I1, I2, k5]*SU3F[6, I4, k7]*
	SU3F[I3, k5, k7] - 3*SU3D[6, I4, k5]*SU3F[I1, I2, k7]*
	SU3F[I3, k5, k7] + 15*SU3D[6, I2, k5]*SU3F[I1, I4, k7]*
	SU3F[I3, k5, k7] + 9*SU3D[6, I1, k5]*SU3F[I2, I4, k7]*
	SU3F[I3, k5, k7] - (3*I)*SU3F[6, I4, k6]*SU3F[I1, I2, k7]*
	SU3F[I3, k6, k7] + (15*I)*SU3F[6, I2, k6]*SU3F[I1, I4, k7]*
	SU3F[I3, k6, k7] - (3*I)*SU3F[6, I1, k7]*SU3F[I2, I4, k6]*
	SU3F[I3, k6, k7] + (6*I)*SU3F[6, I1, k6]*SU3F[I2, I4, k7]*
	SU3F[I3, k6, k7] + (15*I)*SU3D[6, I3, k5]*SU3D[I1, I2, k7]*
	SU3F[I4, k5, k7] - (3*I)*SU3D[6, I2, k5]*SU3D[I1, I3, k7]*
	SU3F[I4, k5, k7] + (3*I)*SU3D[6, I1, k5]*SU3D[I2, I3, k7]*
	SU3F[I4, k5, k7] + 3*SU3D[I2, I3, k5]*SU3F[6, I1, k7]*
	SU3F[I4, k5, k7] - 3*SU3D[I1, I3, k5]*SU3F[6, I2, k7]*
	SU3F[I4, k5, k7] + 15*SU3D[I1, I2, k5]*SU3F[6, I3, k7]*
	SU3F[I4, k5, k7] - 3*SU3D[6, I3, k5]*SU3F[I1, I2, k7]*
	SU3F[I4, k5, k7] + 15*SU3D[6, I2, k5]*SU3F[I1, I3, k7]*
	SU3F[I4, k5, k7] + 9*SU3D[6, I1, k5]*SU3F[I2, I3, k7]*
	SU3F[I4, k5, k7] - (3*I)*SU3F[6, I3, k6]*SU3F[I1, I2, k7]*
	SU3F[I4, k6, k7] + (15*I)*SU3F[6, I2, k6]*SU3F[I1, I3, k7]*
	SU3F[I4, k6, k7] - (3*I)*SU3F[6, I1, k7]*SU3F[I2, I3, k6]*
	SU3F[I4, k6, k7] + (6*I)*SU3F[6, I1, k6]*SU3F[I2, I3, k7]*
	SU3F[I4, k6, k7] - 12*SU3D[I2, I3, I4]*SUNDelta[6, I1] -
	8*SU3D[I1, I3, I4]*SUNDelta[6, I2] + 10*SU3D[I1, I2, I4]*
	SUNDelta[6, I3] - (6*I)*SU3F[I1, I2, I4]*SUNDelta[6, I3] +
	10*SU3D[I1, I2, I3]*SUNDelta[6, I4] - (6*I)*SU3F[I1, I2, I3]*
	SUNDelta[6, I4] + 10*SU3D[6, I2, I4]*SUNDelta[I1, I3] -
	(6*I)*SU3F[6, I2, I4]*SUNDelta[I1, I3] + 10*SU3D[6, I2, I3]*
	SUNDelta[I1, I4] - (6*I)*SU3F[6, I2, I3]*SUNDelta[I1, I4] +
	10*SU3D[6, I1, I4]*SUNDelta[I2, I3] - (14*I)*SU3F[6, I1, I4]*
	SUNDelta[I2, I3] + 10*SU3D[6, I1, I3]*SUNDelta[I2, I4] -
	(14*I)*SU3F[6, I1, I3]*SUNDelta[I2, I4] - 20*SU3D[6, I1, I2]*
	SUNDelta[I3, I4] + (4*I)*SU3F[6, I1, I2]*SUNDelta[I3, I4]))/
(18*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)},
{(CouplingConstant[ChPTW3[2], 1]*(-18*SU3D[6, I4, k6]*SU3D[I1, k6, k7]*
	SU3D[I2, I3, k7] + 18*SU3D[6, I3, k7]*SU3D[I1, k5, k7]*
	SU3D[I2, I4, k5] + 15*SU3D[6, I4, k7]*SU3D[I1, I3, k5]*
	SU3D[I2, k5, k7] - 3*SU3D[6, I3, k7]*SU3D[I1, I4, k5]*
	SU3D[I2, k5, k7] + 3*SU3D[6, I1, k7]*SU3D[I2, k5, k7]*
	SU3D[I3, I4, k5] - 18*SU3D[6, I2, k6]*SU3D[I1, k6, k7]*
	SU3D[I3, I4, k7] - 12*SU3D[6, I4, k7]*SU3D[I1, I2, k5]*
	SU3D[I3, k5, k7] - 12*SU3D[6, I2, k7]*SU3D[I1, I4, k5]*
	SU3D[I3, k5, k7] + 12*SU3D[6, I1, k7]*SU3D[I2, I4, k5]*
	SU3D[I3, k5, k7] - 3*SU3D[6, I3, k7]*SU3D[I1, I2, k5]*
	SU3D[I4, k5, k7] + 15*SU3D[6, I2, k7]*SU3D[I1, I3, k5]*
	SU3D[I4, k5, k7] + 3*SU3D[6, I1, k7]*SU3D[I2, I3, k5]*
	SU3D[I4, k5, k7] + (3*I)*SU3D[I2, k5, k6]*SU3D[I3, I4, k5]*
	SU3F[6, I1, k6] + (12*I)*SU3D[I2, I4, k5]*SU3D[I3, k5, k6]*
	SU3F[6, I1, k6] + (3*I)*SU3D[I2, I3, k5]*SU3D[I4, k5, k6]*
	SU3F[6, I1, k6] - (18*I)*SU3D[I1, k5, k6]*SU3D[I3, I4, k5]*
	SU3F[6, I2, k6] - (12*I)*SU3D[I1, I4, k5]*SU3D[I3, k5, k6]*
	SU3F[6, I2, k6] + (15*I)*SU3D[I1, I3, k5]*SU3D[I4, k5, k6]*
	SU3F[6, I2, k6] + (18*I)*SU3D[I1, k5, k6]*SU3D[I2, I4, k5]*
	SU3F[6, I3, k6] - (3*I)*SU3D[I1, I4, k5]*SU3D[I2, k5, k6]*
	SU3F[6, I3, k6] - (3*I)*SU3D[I1, I2, k5]*SU3D[I4, k5, k6]*
	SU3F[6, I3, k6] - (18*I)*SU3D[I1, k5, k6]*SU3D[I2, I3, k5]*
	SU3F[6, I4, k6] + (15*I)*SU3D[I1, I3, k5]*SU3D[I2, k5, k6]*
	SU3F[6, I4, k6] - (12*I)*SU3D[I1, I2, k5]*SU3D[I3, k5, k6]*
	SU3F[6, I4, k6] - (6*I)*SU3D[6, I4, k6]*SU3D[I3, k5, k6]*
	SU3F[I1, I2, k5] - (15*I)*SU3D[6, I3, k6]*SU3D[I4, k5, k6]*
	SU3F[I1, I2, k5] + 15*SU3D[I4, k5, k6]*SU3F[6, I3, k6]*
	SU3F[I1, I2, k5] + 6*SU3D[I3, k5, k6]*SU3F[6, I4, k6]*
	SU3F[I1, I2, k5] + (3*I)*SU3D[6, I4, k6]*SU3D[I2, k5, k6]*
	SU3F[I1, I3, k5] + (3*I)*SU3D[6, I2, k6]*SU3D[I4, k5, k6]*
	SU3F[I1, I3, k5] - 3*SU3D[I4, k5, k6]*SU3F[6, I2, k6]*
	SU3F[I1, I3, k5] - 3*SU3D[I2, k5, k6]*SU3F[6, I4, k6]*
	SU3F[I1, I3, k5] - (15*I)*SU3D[6, I3, k6]*SU3D[I2, k5, k6]*
	SU3F[I1, I4, k5] - (6*I)*SU3D[6, I2, k6]*SU3D[I3, k5, k6]*
	SU3F[I1, I4, k5] + 6*SU3D[I3, k5, k6]*SU3F[6, I2, k6]*
	SU3F[I1, I4, k5] + 15*SU3D[I2, k5, k6]*SU3F[6, I3, k6]*
	SU3F[I1, I4, k5] - (9*I)*SU3D[6, I4, k7]*SU3D[I2, I3, k5]*
	SU3F[I1, k5, k7] + (9*I)*SU3D[6, I4, k5]*SU3D[I2, I3, k7]*
	SU3F[I1, k5, k7] - (18*I)*SU3D[6, I3, k5]*SU3D[I2, I4, k7]*
	SU3F[I1, k5, k7] - (9*I)*SU3D[6, I2, k7]*SU3D[I3, I4, k5]*
	SU3F[I1, k5, k7] + (9*I)*SU3D[6, I2, k5]*SU3D[I3, I4, k7]*
	SU3F[I1, k5, k7] + 18*SU3D[I3, I4, k5]*SU3F[6, I2, k7]*
	SU3F[I1, k5, k7] - 18*SU3D[I2, I4, k5]*SU3F[6, I3, k7]*
	SU3F[I1, k5, k7] + 18*SU3D[I2, I3, k5]*SU3F[6, I4, k7]*
	SU3F[I1, k5, k7] + (6*I)*SU3D[6, I1, k6]*SU3D[I4, k5, k6]*
	SU3F[I2, I3, k5] - 9*SU3D[I4, k5, k6]*SU3F[6, I1, k6]*
	SU3F[I2, I3, k5] - (9*I)*SU3F[6, I4, k7]*SU3F[I1, k6, k7]*
	SU3F[I2, I3, k6] + (3*I)*SU3D[6, I1, k6]*SU3D[I4, k6, k7]*
	SU3F[I2, I3, k7] - 9*SU3D[6, I4, k5]*SU3F[I1, k5, k7]*
	SU3F[I2, I3, k7] + 9*SU3D[6, I4, k6]*SU3F[I1, k6, k7]*
	SU3F[I2, I3, k7] - (9*I)*SU3F[6, I4, k6]*SU3F[I1, k6, k7]*
	SU3F[I2, I3, k7] - (15*I)*SU3D[6, I4, k5]*SU3D[I1, I3, k7]*
	SU3F[I2, k5, k7] + (3*I)*SU3D[6, I3, k5]*SU3D[I1, I4, k7]*
	SU3F[I2, k5, k7] - (3*I)*SU3D[6, I1, k5]*SU3D[I3, I4, k7]*
	SU3F[I2, k5, k7] - 3*SU3D[I3, I4, k5]*SU3F[6, I1, k7]*
	SU3F[I2, k5, k7] + 3*SU3D[I1, I4, k5]*SU3F[6, I3, k7]*
	SU3F[I2, k5, k7] - 15*SU3D[I1, I3, k5]*SU3F[6, I4, k7]*
	SU3F[I2, k5, k7] + 3*SU3D[6, I4, k5]*SU3F[I1, I3, k7]*
	SU3F[I2, k5, k7] - 15*SU3D[6, I3, k5]*SU3F[I1, I4, k7]*
	SU3F[I2, k5, k7] + (3*I)*SU3F[6, I4, k6]*SU3F[I1, I3, k7]*
	SU3F[I2, k6, k7] - (15*I)*SU3F[6, I3, k6]*SU3F[I1, I4, k7]*
	SU3F[I2, k6, k7] - (6*I)*SU3D[6, I1, k6]*SU3D[I2, k5, k6]*
	SU3F[I3, I4, k5] + 9*SU3D[I2, k5, k6]*SU3F[6, I1, k6]*
	SU3F[I3, I4, k5] + (9*I)*SU3F[6, I2, k7]*SU3F[I1, k6, k7]*
	SU3F[I3, I4, k6] + (3*I)*SU3F[6, I1, k7]*SU3F[I2, k6, k7]*
	SU3F[I3, I4, k6] - (3*I)*SU3D[6, I1, k6]*SU3D[I2, k6, k7]*
	SU3F[I3, I4, k7] + 9*SU3D[6, I2, k5]*SU3F[I1, k5, k7]*
	SU3F[I3, I4, k7] - 9*SU3D[6, I2, k6]*SU3F[I1, k6, k7]*
	SU3F[I3, I4, k7] + (9*I)*SU3F[6, I2, k6]*SU3F[I1, k6, k7]*
	SU3F[I3, I4, k7] - 9*SU3D[6, I1, k5]*SU3F[I2, k5, k7]*
	SU3F[I3, I4, k7] - (6*I)*SU3F[6, I1, k6]*SU3F[I2, k6, k7]*
	SU3F[I3, I4, k7] - (3*I)*SU3D[6, I4, k7]*SU3D[I1, I2, k5]*
	SU3F[I3, k5, k7] + (9*I)*SU3D[6, I4, k5]*SU3D[I1, I2, k7]*
	SU3F[I3, k5, k7] - (3*I)*SU3D[6, I2, k7]*SU3D[I1, I4, k5]*
	SU3F[I3, k5, k7] + (9*I)*SU3D[6, I2, k5]*SU3D[I1, I4, k7]*
	SU3F[I3, k5, k7] - (12*I)*SU3D[6, I1, k5]*SU3D[I2, I4, k7]*
	SU3F[I3, k5, k7] - 12*SU3D[I2, I4, k5]*SU3F[6, I1, k7]*
	SU3F[I3, k5, k7] + 12*SU3D[I1, I4, k5]*SU3F[6, I2, k7]*
	SU3F[I3, k5, k7] + 12*SU3D[I1, I2, k5]*SU3F[6, I4, k7]*
	SU3F[I3, k5, k7] - 9*SU3D[6, I4, k5]*SU3F[I1, I2, k7]*
	SU3F[I3, k5, k7] - 9*SU3D[6, I2, k5]*SU3F[I1, I4, k7]*
	SU3F[I3, k5, k7] + 3*SU3D[6, I4, k6]*SU3F[I1, I2, k7]*
	SU3F[I3, k6, k7] - (6*I)*SU3F[6, I4, k6]*SU3F[I1, I2, k7]*
	SU3F[I3, k6, k7] + 3*SU3D[6, I2, k6]*SU3F[I1, I4, k7]*
	SU3F[I3, k6, k7] - (6*I)*SU3F[6, I2, k6]*SU3F[I1, I4, k7]*
	SU3F[I3, k6, k7] + (3*I)*SU3D[6, I3, k5]*SU3D[I1, I2, k7]*
	SU3F[I4, k5, k7] - (15*I)*SU3D[6, I2, k5]*SU3D[I1, I3, k7]*
	SU3F[I4, k5, k7] - (3*I)*SU3D[6, I1, k5]*SU3D[I2, I3, k7]*
	SU3F[I4, k5, k7] - 3*SU3D[I2, I3, k5]*SU3F[6, I1, k7]*
	SU3F[I4, k5, k7] - 15*SU3D[I1, I3, k5]*SU3F[6, I2, k7]*
	SU3F[I4, k5, k7] + 3*SU3D[I1, I2, k5]*SU3F[6, I3, k7]*
	SU3F[I4, k5, k7] - 15*SU3D[6, I3, k5]*SU3F[I1, I2, k7]*
	SU3F[I4, k5, k7] + 3*SU3D[6, I2, k5]*SU3F[I1, I3, k7]*
	SU3F[I4, k5, k7] + 9*SU3D[6, I1, k5]*SU3F[I2, I3, k7]*
	SU3F[I4, k5, k7] - (15*I)*SU3F[6, I3, k6]*SU3F[I1, I2, k7]*
	SU3F[I4, k6, k7] + (3*I)*SU3F[6, I2, k6]*SU3F[I1, I3, k7]*
	SU3F[I4, k6, k7] - (3*I)*SU3F[6, I1, k7]*SU3F[I2, I3, k6]*
	SU3F[I4, k6, k7] + (6*I)*SU3F[6, I1, k6]*SU3F[I2, I3, k7]*
	SU3F[I4, k6, k7] + 12*SU3D[I2, I3, I4]*SUNDelta[6, I1] -
	10*SU3D[I1, I3, I4]*SUNDelta[6, I2] + (6*I)*SU3F[I1, I3, I4]*
	SUNDelta[6, I2] + 8*SU3D[I1, I2, I4]*SUNDelta[6, I3] -
	10*SU3D[I1, I2, I3]*SUNDelta[6, I4] - (6*I)*SU3F[I1, I2, I3]*
	SUNDelta[6, I4] - 10*SU3D[6, I3, I4]*SUNDelta[I1, I2] +
	(6*I)*SU3F[6, I3, I4]*SUNDelta[I1, I2] - 10*SU3D[6, I2, I3]*
	SUNDelta[I1, I4] - (6*I)*SU3F[6, I2, I3]*SUNDelta[I1, I4] -
	10*SU3D[6, I1, I4]*SUNDelta[I2, I3] + (14*I)*SU3F[6, I1, I4]*
	SUNDelta[I2, I3] + 20*SU3D[6, I1, I3]*SUNDelta[I2, I4] -
	(4*I)*SU3F[6, I1, I3]*SUNDelta[I2, I4] - 10*SU3D[6, I1, I2]*
	SUNDelta[I3, I4] + (14*I)*SU3F[6, I1, I2]*SUNDelta[I3, I4]))/
(18*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)},
{(CouplingConstant[ChPTW3[2], 1]*(18*SU3D[6, I4, k7]*SU3D[I1, k5, k7]*
	SU3D[I2, I3, k5] - 18*SU3D[6, I3, k6]*SU3D[I1, k6, k7]*
	SU3D[I2, I4, k7] - 3*SU3D[6, I4, k7]*SU3D[I1, I3, k5]*
	SU3D[I2, k5, k7] + 15*SU3D[6, I3, k7]*SU3D[I1, I4, k5]*
	SU3D[I2, k5, k7] + 3*SU3D[6, I1, k7]*SU3D[I2, k5, k7]*
	SU3D[I3, I4, k5] - 18*SU3D[6, I2, k6]*SU3D[I1, k6, k7]*
	SU3D[I3, I4, k7] - 3*SU3D[6, I4, k7]*SU3D[I1, I2, k5]*
	SU3D[I3, k5, k7] + 15*SU3D[6, I2, k7]*SU3D[I1, I4, k5]*
	SU3D[I3, k5, k7] + 3*SU3D[6, I1, k7]*SU3D[I2, I4, k5]*
	SU3D[I3, k5, k7] - 12*SU3D[6, I3, k7]*SU3D[I1, I2, k5]*
	SU3D[I4, k5, k7] - 12*SU3D[6, I2, k7]*SU3D[I1, I3, k5]*
	SU3D[I4, k5, k7] + 12*SU3D[6, I1, k7]*SU3D[I2, I3, k5]*
	SU3D[I4, k5, k7] + (3*I)*SU3D[I2, k5, k6]*SU3D[I3, I4, k5]*
	SU3F[6, I1, k6] + (3*I)*SU3D[I2, I4, k5]*SU3D[I3, k5, k6]*
	SU3F[6, I1, k6] + (12*I)*SU3D[I2, I3, k5]*SU3D[I4, k5, k6]*
	SU3F[6, I1, k6] - (18*I)*SU3D[I1, k5, k6]*SU3D[I3, I4, k5]*
	SU3F[6, I2, k6] + (15*I)*SU3D[I1, I4, k5]*SU3D[I3, k5, k6]*
	SU3F[6, I2, k6] - (12*I)*SU3D[I1, I3, k5]*SU3D[I4, k5, k6]*
	SU3F[6, I2, k6] - (18*I)*SU3D[I1, k5, k6]*SU3D[I2, I4, k5]*
	SU3F[6, I3, k6] + (15*I)*SU3D[I1, I4, k5]*SU3D[I2, k5, k6]*
	SU3F[6, I3, k6] - (12*I)*SU3D[I1, I2, k5]*SU3D[I4, k5, k6]*
	SU3F[6, I3, k6] + (18*I)*SU3D[I1, k5, k6]*SU3D[I2, I3, k5]*
	SU3F[6, I4, k6] - (3*I)*SU3D[I1, I3, k5]*SU3D[I2, k5, k6]*
	SU3F[6, I4, k6] - (3*I)*SU3D[I1, I2, k5]*SU3D[I3, k5, k6]*
	SU3F[6, I4, k6] - (15*I)*SU3D[6, I4, k6]*SU3D[I3, k5, k6]*
	SU3F[I1, I2, k5] - (6*I)*SU3D[6, I3, k6]*SU3D[I4, k5, k6]*
	SU3F[I1, I2, k5] + 6*SU3D[I4, k5, k6]*SU3F[6, I3, k6]*
	SU3F[I1, I2, k5] + 15*SU3D[I3, k5, k6]*SU3F[6, I4, k6]*
	SU3F[I1, I2, k5] - (15*I)*SU3D[6, I4, k6]*SU3D[I2, k5, k6]*
	SU3F[I1, I3, k5] - (6*I)*SU3D[6, I2, k6]*SU3D[I4, k5, k6]*
	SU3F[I1, I3, k5] + 6*SU3D[I4, k5, k6]*SU3F[6, I2, k6]*
	SU3F[I1, I3, k5] + 15*SU3D[I2, k5, k6]*SU3F[6, I4, k6]*
	SU3F[I1, I3, k5] + (3*I)*SU3D[6, I3, k6]*SU3D[I2, k5, k6]*
	SU3F[I1, I4, k5] + (3*I)*SU3D[6, I2, k6]*SU3D[I3, k5, k6]*
	SU3F[I1, I4, k5] - 3*SU3D[I3, k5, k6]*SU3F[6, I2, k6]*
	SU3F[I1, I4, k5] - 3*SU3D[I2, k5, k6]*SU3F[6, I3, k6]*
	SU3F[I1, I4, k5] - (18*I)*SU3D[6, I4, k5]*SU3D[I2, I3, k7]*
	SU3F[I1, k5, k7] - (9*I)*SU3D[6, I3, k7]*SU3D[I2, I4, k5]*
	SU3F[I1, k5, k7] + (9*I)*SU3D[6, I3, k5]*SU3D[I2, I4, k7]*
	SU3F[I1, k5, k7] - (9*I)*SU3D[6, I2, k7]*SU3D[I3, I4, k5]*
	SU3F[I1, k5, k7] + (9*I)*SU3D[6, I2, k5]*SU3D[I3, I4, k7]*
	SU3F[I1, k5, k7] + 18*SU3D[I3, I4, k5]*SU3F[6, I2, k7]*
	SU3F[I1, k5, k7] + 18*SU3D[I2, I4, k5]*SU3F[6, I3, k7]*
	SU3F[I1, k5, k7] - 18*SU3D[I2, I3, k5]*SU3F[6, I4, k7]*
	SU3F[I1, k5, k7] + (6*I)*SU3D[6, I1, k6]*SU3D[I3, k5, k6]*
	SU3F[I2, I4, k5] - 9*SU3D[I3, k5, k6]*SU3F[6, I1, k6]*
	SU3F[I2, I4, k5] - (9*I)*SU3F[6, I3, k7]*SU3F[I1, k6, k7]*
	SU3F[I2, I4, k6] + (3*I)*SU3D[6, I1, k6]*SU3D[I3, k6, k7]*
	SU3F[I2, I4, k7] - 9*SU3D[6, I3, k5]*SU3F[I1, k5, k7]*
	SU3F[I2, I4, k7] + 9*SU3D[6, I3, k6]*SU3F[I1, k6, k7]*
	SU3F[I2, I4, k7] - (9*I)*SU3F[6, I3, k6]*SU3F[I1, k6, k7]*
	SU3F[I2, I4, k7] + (3*I)*SU3D[6, I4, k5]*SU3D[I1, I3, k7]*
	SU3F[I2, k5, k7] - (15*I)*SU3D[6, I3, k5]*SU3D[I1, I4, k7]*
	SU3F[I2, k5, k7] - (3*I)*SU3D[6, I1, k5]*SU3D[I3, I4, k7]*
	SU3F[I2, k5, k7] - 3*SU3D[I3, I4, k5]*SU3F[6, I1, k7]*
	SU3F[I2, k5, k7] - 15*SU3D[I1, I4, k5]*SU3F[6, I3, k7]*
	SU3F[I2, k5, k7] + 3*SU3D[I1, I3, k5]*SU3F[6, I4, k7]*
	SU3F[I2, k5, k7] - 15*SU3D[6, I4, k5]*SU3F[I1, I3, k7]*
	SU3F[I2, k5, k7] + 3*SU3D[6, I3, k5]*SU3F[I1, I4, k7]*
	SU3F[I2, k5, k7] - (15*I)*SU3F[6, I4, k6]*SU3F[I1, I3, k7]*
	SU3F[I2, k6, k7] + (3*I)*SU3F[6, I3, k6]*SU3F[I1, I4, k7]*
	SU3F[I2, k6, k7] + (6*I)*SU3D[6, I1, k6]*SU3D[I2, k5, k6]*
	SU3F[I3, I4, k5] - 9*SU3D[I2, k5, k6]*SU3F[6, I1, k6]*
	SU3F[I3, I4, k5] - (9*I)*SU3F[6, I2, k7]*SU3F[I1, k6, k7]*
	SU3F[I3, I4, k6] - (3*I)*SU3F[6, I1, k7]*SU3F[I2, k6, k7]*
	SU3F[I3, I4, k6] + (3*I)*SU3D[6, I1, k6]*SU3D[I2, k6, k7]*
	SU3F[I3, I4, k7] - 9*SU3D[6, I2, k5]*SU3F[I1, k5, k7]*
	SU3F[I3, I4, k7] + 9*SU3D[6, I2, k6]*SU3F[I1, k6, k7]*
	SU3F[I3, I4, k7] - (9*I)*SU3F[6, I2, k6]*SU3F[I1, k6, k7]*
	SU3F[I3, I4, k7] + 9*SU3D[6, I1, k5]*SU3F[I2, k5, k7]*
	SU3F[I3, I4, k7] + (6*I)*SU3F[6, I1, k6]*SU3F[I2, k6, k7]*
	SU3F[I3, I4, k7] + (3*I)*SU3D[6, I4, k5]*SU3D[I1, I2, k7]*
	SU3F[I3, k5, k7] - (15*I)*SU3D[6, I2, k5]*SU3D[I1, I4, k7]*
	SU3F[I3, k5, k7] - (3*I)*SU3D[6, I1, k5]*SU3D[I2, I4, k7]*
	SU3F[I3, k5, k7] - 3*SU3D[I2, I4, k5]*SU3F[6, I1, k7]*
	SU3F[I3, k5, k7] - 15*SU3D[I1, I4, k5]*SU3F[6, I2, k7]*
	SU3F[I3, k5, k7] + 3*SU3D[I1, I2, k5]*SU3F[6, I4, k7]*
	SU3F[I3, k5, k7] - 15*SU3D[6, I4, k5]*SU3F[I1, I2, k7]*
	SU3F[I3, k5, k7] + 3*SU3D[6, I2, k5]*SU3F[I1, I4, k7]*
	SU3F[I3, k5, k7] + 9*SU3D[6, I1, k5]*SU3F[I2, I4, k7]*
	SU3F[I3, k5, k7] - (15*I)*SU3F[6, I4, k6]*SU3F[I1, I2, k7]*
	SU3F[I3, k6, k7] + (3*I)*SU3F[6, I2, k6]*SU3F[I1, I4, k7]*
	SU3F[I3, k6, k7] - (3*I)*SU3F[6, I1, k7]*SU3F[I2, I4, k6]*
	SU3F[I3, k6, k7] + (6*I)*SU3F[6, I1, k6]*SU3F[I2, I4, k7]*
	SU3F[I3, k6, k7] - (3*I)*SU3D[6, I3, k7]*SU3D[I1, I2, k5]*
	SU3F[I4, k5, k7] + (9*I)*SU3D[6, I3, k5]*SU3D[I1, I2, k7]*
	SU3F[I4, k5, k7] - (3*I)*SU3D[6, I2, k7]*SU3D[I1, I3, k5]*
	SU3F[I4, k5, k7] + (9*I)*SU3D[6, I2, k5]*SU3D[I1, I3, k7]*
	SU3F[I4, k5, k7] - (12*I)*SU3D[6, I1, k5]*SU3D[I2, I3, k7]*
	SU3F[I4, k5, k7] - 12*SU3D[I2, I3, k5]*SU3F[6, I1, k7]*
	SU3F[I4, k5, k7] + 12*SU3D[I1, I3, k5]*SU3F[6, I2, k7]*
	SU3F[I4, k5, k7] + 12*SU3D[I1, I2, k5]*SU3F[6, I3, k7]*
	SU3F[I4, k5, k7] - 9*SU3D[6, I3, k5]*SU3F[I1, I2, k7]*
	SU3F[I4, k5, k7] - 9*SU3D[6, I2, k5]*SU3F[I1, I3, k7]*
	SU3F[I4, k5, k7] + 3*SU3D[6, I3, k6]*SU3F[I1, I2, k7]*
	SU3F[I4, k6, k7] - (6*I)*SU3F[6, I3, k6]*SU3F[I1, I2, k7]*
	SU3F[I4, k6, k7] + 3*SU3D[6, I2, k6]*SU3F[I1, I3, k7]*
	SU3F[I4, k6, k7] - (6*I)*SU3F[6, I2, k6]*SU3F[I1, I3, k7]*
	SU3F[I4, k6, k7] + 12*SU3D[I2, I3, I4]*SUNDelta[6, I1] -
	10*SU3D[I1, I3, I4]*SUNDelta[6, I2] - (6*I)*SU3F[I1, I3, I4]*
	SUNDelta[6, I2] - 10*SU3D[I1, I2, I4]*SUNDelta[6, I3] -
	(6*I)*SU3F[I1, I2, I4]*SUNDelta[6, I3] + 8*SU3D[I1, I2, I3]*
	SUNDelta[6, I4] - 10*SU3D[6, I3, I4]*SUNDelta[I1, I2] -
	(6*I)*SU3F[6, I3, I4]*SUNDelta[I1, I2] - 10*SU3D[6, I2, I4]*
	SUNDelta[I1, I3] - (6*I)*SU3F[6, I2, I4]*SUNDelta[I1, I3] +
	20*SU3D[6, I1, I4]*SUNDelta[I2, I3] - (4*I)*SU3F[6, I1, I4]*
	SUNDelta[I2, I3] - 10*SU3D[6, I1, I3]*SUNDelta[I2, I4] +
	(14*I)*SU3F[6, I1, I3]*SUNDelta[I2, I4] - 10*SU3D[6, I1, I2]*
	SUNDelta[I3, I4] + (14*I)*SU3F[6, I1, I2]*SUNDelta[I3, I4]))/
(18*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}}
