{{((24*I)*SU3D[I1, I4, k1]*SU3D[I2, I3, k1] - (18*I)*SU3D[3, I4, k1]*
     SU3D[I1, k1, k2]*SU3D[I2, I3, k2] - (6*I)*Sqrt[3]*SU3D[8, I4, k1]*
     SU3D[I1, k1, k2]*SU3D[I2, I3, k2] + (24*I)*SU3D[I1, I3, k1]*
     SU3D[I2, I4, k1] - (18*I)*SU3D[3, I3, k1]*SU3D[I1, k1, k2]*
     SU3D[I2, I4, k2] - (6*I)*Sqrt[3]*SU3D[8, I3, k1]*SU3D[I1, k1, k2]*
     SU3D[I2, I4, k2] - (18*I)*SU3D[3, I4, k1]*SU3D[I1, I3, k2]*
     SU3D[I2, k1, k2] - (6*I)*Sqrt[3]*SU3D[8, I4, k1]*SU3D[I1, I3, k2]*
     SU3D[I2, k1, k2] - (18*I)*SU3D[3, I3, k1]*SU3D[I1, I4, k2]*
     SU3D[I2, k1, k2] - (6*I)*Sqrt[3]*SU3D[8, I3, k1]*SU3D[I1, I4, k2]*
     SU3D[I2, k1, k2] + (24*I)*SU3D[I1, I2, k1]*SU3D[I3, I4, k1] - 
    (18*I)*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*SU3D[I3, I4, k2] - 
    (6*I)*Sqrt[3]*SU3D[8, I2, k1]*SU3D[I1, k1, k2]*SU3D[I3, I4, k2] - 
    (18*I)*SU3D[3, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, I4, k2] - 
    (6*I)*Sqrt[3]*SU3D[8, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, I4, k2] - 
    (18*I)*SU3D[3, I4, k1]*SU3D[I1, I2, k2]*SU3D[I3, k1, k2] - 
    (6*I)*Sqrt[3]*SU3D[8, I4, k1]*SU3D[I1, I2, k2]*SU3D[I3, k1, k2] - 
    (18*I)*SU3D[3, I2, k1]*SU3D[I1, I4, k2]*SU3D[I3, k1, k2] - 
    (6*I)*Sqrt[3]*SU3D[8, I2, k1]*SU3D[I1, I4, k2]*SU3D[I3, k1, k2] - 
    (18*I)*SU3D[3, I1, k1]*SU3D[I2, I4, k2]*SU3D[I3, k1, k2] - 
    (6*I)*Sqrt[3]*SU3D[8, I1, k1]*SU3D[I2, I4, k2]*SU3D[I3, k1, k2] - 
    (18*I)*SU3D[3, I3, k1]*SU3D[I1, I2, k2]*SU3D[I4, k1, k2] - 
    (6*I)*Sqrt[3]*SU3D[8, I3, k1]*SU3D[I1, I2, k2]*SU3D[I4, k1, k2] - 
    (18*I)*SU3D[3, I2, k1]*SU3D[I1, I3, k2]*SU3D[I4, k1, k2] - 
    (6*I)*Sqrt[3]*SU3D[8, I2, k1]*SU3D[I1, I3, k2]*SU3D[I4, k1, k2] - 
    (18*I)*SU3D[3, I1, k1]*SU3D[I2, I3, k2]*SU3D[I4, k1, k2] - 
    (6*I)*Sqrt[3]*SU3D[8, I1, k1]*SU3D[I2, I3, k2]*SU3D[I4, k1, k2] - 
    3*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, I4, k2]*SU3F[8, I1, k1] + 
    3*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, I4, k1]*SU3F[8, I1, k2] - 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I3, I4, k2]*SU3F[8, I2, k1] + 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I3, I4, k1]*SU3F[8, I2, k2] - 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I2, I4, k2]*SU3F[8, I3, k1] + 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I2, I4, k1]*SU3F[8, I3, k2] - 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I2, I3, k2]*SU3F[8, I4, k1] + 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I2, I3, k1]*SU3F[8, I4, k2] + 
    (18*I)*SU3D[I3, I4, k1]*SU3F[3, I2, k2]*SU3F[I1, k1, k2] + 
    (18*I)*SU3D[I2, I4, k1]*SU3F[3, I3, k2]*SU3F[I1, k1, k2] + 
    (18*I)*SU3D[I2, I3, k1]*SU3F[3, I4, k2]*SU3F[I1, k1, k2] + 
    (6*I)*Sqrt[3]*SU3D[I3, I4, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] + 
    (6*I)*Sqrt[3]*SU3D[I2, I4, k1]*SU3F[8, I3, k2]*SU3F[I1, k1, k2] + 
    (6*I)*Sqrt[3]*SU3D[I2, I3, k1]*SU3F[8, I4, k2]*SU3F[I1, k1, k2] + 
    (18*I)*SU3D[I3, I4, k1]*SU3F[3, I1, k2]*SU3F[I2, k1, k2] + 
    (18*I)*SU3D[I1, I4, k1]*SU3F[3, I3, k2]*SU3F[I2, k1, k2] + 
    (18*I)*SU3D[I1, I3, k1]*SU3F[3, I4, k2]*SU3F[I2, k1, k2] + 
    (6*I)*Sqrt[3]*SU3D[I3, I4, k1]*SU3F[8, I1, k2]*SU3F[I2, k1, k2] + 
    (6*I)*Sqrt[3]*SU3D[I1, I4, k1]*SU3F[8, I3, k2]*SU3F[I2, k1, k2] + 
    (6*I)*Sqrt[3]*SU3D[I1, I3, k1]*SU3F[8, I4, k2]*SU3F[I2, k1, k2] + 
    (18*I)*SU3D[I2, I4, k1]*SU3F[3, I1, k2]*SU3F[I3, k1, k2] + 
    (18*I)*SU3D[I1, I4, k1]*SU3F[3, I2, k2]*SU3F[I3, k1, k2] + 
    (18*I)*SU3D[I1, I2, k1]*SU3F[3, I4, k2]*SU3F[I3, k1, k2] + 
    (6*I)*Sqrt[3]*SU3D[I2, I4, k1]*SU3F[8, I1, k2]*SU3F[I3, k1, k2] + 
    (6*I)*Sqrt[3]*SU3D[I1, I4, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] + 
    (6*I)*Sqrt[3]*SU3D[I1, I2, k1]*SU3F[8, I4, k2]*SU3F[I3, k1, k2] + 
    (18*I)*SU3D[I2, I3, k1]*SU3F[3, I1, k2]*SU3F[I4, k1, k2] + 
    (18*I)*SU3D[I1, I3, k1]*SU3F[3, I2, k2]*SU3F[I4, k1, k2] + 
    (18*I)*SU3D[I1, I2, k1]*SU3F[3, I3, k2]*SU3F[I4, k1, k2] + 
    (6*I)*Sqrt[3]*SU3D[I2, I3, k1]*SU3F[8, I1, k2]*SU3F[I4, k1, k2] + 
    (6*I)*Sqrt[3]*SU3D[I1, I3, k1]*SU3F[8, I2, k2]*SU3F[I4, k1, k2] + 
    (6*I)*Sqrt[3]*SU3D[I1, I2, k1]*SU3F[8, I3, k2]*SU3F[I4, k1, k2] - 
    (36*I)*SU3D[I2, I3, I4]*SUNDelta[3, I1] - (36*I)*SU3D[I1, I3, I4]*
     SUNDelta[3, I2] - (36*I)*SU3D[I1, I2, I4]*SUNDelta[3, I3] - 
    (36*I)*SU3D[I1, I2, I3]*SUNDelta[3, I4] - (12*I)*Sqrt[3]*SU3D[I2, I3, I4]*
     SUNDelta[8, I1] - (12*I)*Sqrt[3]*SU3D[I1, I3, I4]*SUNDelta[8, I2] - 
    (12*I)*Sqrt[3]*SU3D[I1, I2, I4]*SUNDelta[8, I3] - 
    (12*I)*Sqrt[3]*SU3D[I1, I2, I3]*SUNDelta[8, I4] - 
    (24*I)*SU3D[3, I3, I4]*SUNDelta[I1, I2] - (8*I)*Sqrt[3]*SU3D[8, I3, I4]*
     SUNDelta[I1, I2] - (24*I)*SU3D[3, I2, I4]*SUNDelta[I1, I3] - 
    (8*I)*Sqrt[3]*SU3D[8, I2, I4]*SUNDelta[I1, I3] - 
    (24*I)*SU3D[3, I2, I3]*SUNDelta[I1, I4] - (8*I)*Sqrt[3]*SU3D[8, I2, I3]*
     SUNDelta[I1, I4] - (24*I)*SU3D[3, I1, I4]*SUNDelta[I2, I3] - 
    (8*I)*Sqrt[3]*SU3D[8, I1, I4]*SUNDelta[I2, I3] + 
    (16*I)*SUNDelta[I1, I4]*SUNDelta[I2, I3] - (24*I)*SU3D[3, I1, I3]*
     SUNDelta[I2, I4] - (8*I)*Sqrt[3]*SU3D[8, I1, I3]*SUNDelta[I2, I4] + 
    (16*I)*SUNDelta[I1, I3]*SUNDelta[I2, I4] - (24*I)*SU3D[3, I1, I2]*
     SUNDelta[I3, I4] - (8*I)*Sqrt[3]*SU3D[8, I1, I2]*SUNDelta[I3, I4] + 
    (16*I)*SUNDelta[I1, I2]*SUNDelta[I3, I4])/
   (216*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)}, 
 {((I/108)*(12*SU3D[I1, I4, k1]*SU3D[I2, I3, k1] + 
     9*SU3D[3, I4, k1]*SU3D[I1, k1, k2]*SU3D[I2, I3, k2] - 
     3*Sqrt[3]*SU3D[8, I4, k1]*SU3D[I1, k1, k2]*SU3D[I2, I3, k2] + 
     12*SU3D[I1, I3, k1]*SU3D[I2, I4, k1] + 9*SU3D[3, I3, k1]*
      SU3D[I1, k1, k2]*SU3D[I2, I4, k2] - 3*Sqrt[3]*SU3D[8, I3, k1]*
      SU3D[I1, k1, k2]*SU3D[I2, I4, k2] + 9*SU3D[3, I4, k1]*SU3D[I1, I3, k2]*
      SU3D[I2, k1, k2] - 3*Sqrt[3]*SU3D[8, I4, k1]*SU3D[I1, I3, k2]*
      SU3D[I2, k1, k2] + 9*SU3D[3, I3, k1]*SU3D[I1, I4, k2]*
      SU3D[I2, k1, k2] - 3*Sqrt[3]*SU3D[8, I3, k1]*SU3D[I1, I4, k2]*
      SU3D[I2, k1, k2] + 12*SU3D[I1, I2, k1]*SU3D[I3, I4, k1] + 
     9*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*SU3D[I3, I4, k2] - 
     3*Sqrt[3]*SU3D[8, I2, k1]*SU3D[I1, k1, k2]*SU3D[I3, I4, k2] + 
     9*SU3D[3, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, I4, k2] - 
     3*Sqrt[3]*SU3D[8, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, I4, k2] + 
     9*SU3D[3, I4, k1]*SU3D[I1, I2, k2]*SU3D[I3, k1, k2] - 
     3*Sqrt[3]*SU3D[8, I4, k1]*SU3D[I1, I2, k2]*SU3D[I3, k1, k2] + 
     9*SU3D[3, I2, k1]*SU3D[I1, I4, k2]*SU3D[I3, k1, k2] - 
     3*Sqrt[3]*SU3D[8, I2, k1]*SU3D[I1, I4, k2]*SU3D[I3, k1, k2] + 
     9*SU3D[3, I1, k1]*SU3D[I2, I4, k2]*SU3D[I3, k1, k2] - 
     3*Sqrt[3]*SU3D[8, I1, k1]*SU3D[I2, I4, k2]*SU3D[I3, k1, k2] + 
     9*SU3D[3, I3, k1]*SU3D[I1, I2, k2]*SU3D[I4, k1, k2] - 
     3*Sqrt[3]*SU3D[8, I3, k1]*SU3D[I1, I2, k2]*SU3D[I4, k1, k2] + 
     9*SU3D[3, I2, k1]*SU3D[I1, I3, k2]*SU3D[I4, k1, k2] - 
     3*Sqrt[3]*SU3D[8, I2, k1]*SU3D[I1, I3, k2]*SU3D[I4, k1, k2] + 
     9*SU3D[3, I1, k1]*SU3D[I2, I3, k2]*SU3D[I4, k1, k2] - 
     3*Sqrt[3]*SU3D[8, I1, k1]*SU3D[I2, I3, k2]*SU3D[I4, k1, k2] - 
     9*SU3D[I3, I4, k1]*SU3F[3, I2, k2]*SU3F[I1, k1, k2] - 
     9*SU3D[I2, I4, k1]*SU3F[3, I3, k2]*SU3F[I1, k1, k2] - 
     9*SU3D[I2, I3, k1]*SU3F[3, I4, k2]*SU3F[I1, k1, k2] + 
     3*Sqrt[3]*SU3D[I3, I4, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] + 
     3*Sqrt[3]*SU3D[I2, I4, k1]*SU3F[8, I3, k2]*SU3F[I1, k1, k2] + 
     3*Sqrt[3]*SU3D[I2, I3, k1]*SU3F[8, I4, k2]*SU3F[I1, k1, k2] - 
     9*SU3D[I3, I4, k1]*SU3F[3, I1, k2]*SU3F[I2, k1, k2] - 
     9*SU3D[I1, I4, k1]*SU3F[3, I3, k2]*SU3F[I2, k1, k2] - 
     9*SU3D[I1, I3, k1]*SU3F[3, I4, k2]*SU3F[I2, k1, k2] + 
     3*Sqrt[3]*SU3D[I3, I4, k1]*SU3F[8, I1, k2]*SU3F[I2, k1, k2] + 
     3*Sqrt[3]*SU3D[I1, I4, k1]*SU3F[8, I3, k2]*SU3F[I2, k1, k2] + 
     3*Sqrt[3]*SU3D[I1, I3, k1]*SU3F[8, I4, k2]*SU3F[I2, k1, k2] - 
     9*SU3D[I2, I4, k1]*SU3F[3, I1, k2]*SU3F[I3, k1, k2] - 
     9*SU3D[I1, I4, k1]*SU3F[3, I2, k2]*SU3F[I3, k1, k2] - 
     9*SU3D[I1, I2, k1]*SU3F[3, I4, k2]*SU3F[I3, k1, k2] + 
     3*Sqrt[3]*SU3D[I2, I4, k1]*SU3F[8, I1, k2]*SU3F[I3, k1, k2] + 
     3*Sqrt[3]*SU3D[I1, I4, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] + 
     3*Sqrt[3]*SU3D[I1, I2, k1]*SU3F[8, I4, k2]*SU3F[I3, k1, k2] - 
     9*SU3D[I2, I3, k1]*SU3F[3, I1, k2]*SU3F[I4, k1, k2] - 
     9*SU3D[I1, I3, k1]*SU3F[3, I2, k2]*SU3F[I4, k1, k2] - 
     9*SU3D[I1, I2, k1]*SU3F[3, I3, k2]*SU3F[I4, k1, k2] + 
     3*Sqrt[3]*SU3D[I2, I3, k1]*SU3F[8, I1, k2]*SU3F[I4, k1, k2] + 
     3*Sqrt[3]*SU3D[I1, I3, k1]*SU3F[8, I2, k2]*SU3F[I4, k1, k2] + 
     3*Sqrt[3]*SU3D[I1, I2, k1]*SU3F[8, I3, k2]*SU3F[I4, k1, k2] + 
     18*SU3D[I2, I3, I4]*SUNDelta[3, I1] + 18*SU3D[I1, I3, I4]*
      SUNDelta[3, I2] + 18*SU3D[I1, I2, I4]*SUNDelta[3, I3] + 
     18*SU3D[I1, I2, I3]*SUNDelta[3, I4] - 6*Sqrt[3]*SU3D[I2, I3, I4]*
      SUNDelta[8, I1] - 6*Sqrt[3]*SU3D[I1, I3, I4]*SUNDelta[8, I2] - 
     6*Sqrt[3]*SU3D[I1, I2, I4]*SUNDelta[8, I3] - 6*Sqrt[3]*SU3D[I1, I2, I3]*
      SUNDelta[8, I4] + 12*SU3D[3, I3, I4]*SUNDelta[I1, I2] - 
     4*Sqrt[3]*SU3D[8, I3, I4]*SUNDelta[I1, I2] + 12*SU3D[3, I2, I4]*
      SUNDelta[I1, I3] - 4*Sqrt[3]*SU3D[8, I2, I4]*SUNDelta[I1, I3] + 
     12*SU3D[3, I2, I3]*SUNDelta[I1, I4] - 4*Sqrt[3]*SU3D[8, I2, I3]*
      SUNDelta[I1, I4] + 12*SU3D[3, I1, I4]*SUNDelta[I2, I3] - 
     4*Sqrt[3]*SU3D[8, I1, I4]*SUNDelta[I2, I3] + 8*SUNDelta[I1, I4]*
      SUNDelta[I2, I3] + 12*SU3D[3, I1, I3]*SUNDelta[I2, I4] - 
     4*Sqrt[3]*SU3D[8, I1, I3]*SUNDelta[I2, I4] + 8*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] + 12*SU3D[3, I1, I2]*SUNDelta[I3, I4] - 
     4*Sqrt[3]*SU3D[8, I1, I2]*SUNDelta[I3, I4] + 8*SUNDelta[I1, I2]*
      SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[1], 
     RenormalizationState[0]]^2}, 
 {((I/54)*(6*SU3D[I1, I4, k1]*SU3D[I2, I3, k1] + 3*Sqrt[3]*SU3D[8, I4, k1]*
      SU3D[I1, k1, k2]*SU3D[I2, I3, k2] + 6*SU3D[I1, I3, k1]*
      SU3D[I2, I4, k1] + 3*Sqrt[3]*SU3D[8, I3, k1]*SU3D[I1, k1, k2]*
      SU3D[I2, I4, k2] + 3*Sqrt[3]*SU3D[8, I4, k1]*SU3D[I1, I3, k2]*
      SU3D[I2, k1, k2] + 3*Sqrt[3]*SU3D[8, I3, k1]*SU3D[I1, I4, k2]*
      SU3D[I2, k1, k2] + 6*SU3D[I1, I2, k1]*SU3D[I3, I4, k1] + 
     3*Sqrt[3]*SU3D[8, I2, k1]*SU3D[I1, k1, k2]*SU3D[I3, I4, k2] + 
     3*Sqrt[3]*SU3D[8, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, I4, k2] + 
     3*Sqrt[3]*SU3D[8, I4, k1]*SU3D[I1, I2, k2]*SU3D[I3, k1, k2] + 
     3*Sqrt[3]*SU3D[8, I2, k1]*SU3D[I1, I4, k2]*SU3D[I3, k1, k2] + 
     3*Sqrt[3]*SU3D[8, I1, k1]*SU3D[I2, I4, k2]*SU3D[I3, k1, k2] + 
     3*Sqrt[3]*SU3D[8, I3, k1]*SU3D[I1, I2, k2]*SU3D[I4, k1, k2] + 
     3*Sqrt[3]*SU3D[8, I2, k1]*SU3D[I1, I3, k2]*SU3D[I4, k1, k2] + 
     3*Sqrt[3]*SU3D[8, I1, k1]*SU3D[I2, I3, k2]*SU3D[I4, k1, k2] - 
     3*Sqrt[3]*SU3D[I3, I4, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] - 
     3*Sqrt[3]*SU3D[I2, I4, k1]*SU3F[8, I3, k2]*SU3F[I1, k1, k2] - 
     3*Sqrt[3]*SU3D[I2, I3, k1]*SU3F[8, I4, k2]*SU3F[I1, k1, k2] - 
     3*Sqrt[3]*SU3D[I3, I4, k1]*SU3F[8, I1, k2]*SU3F[I2, k1, k2] - 
     3*Sqrt[3]*SU3D[I1, I4, k1]*SU3F[8, I3, k2]*SU3F[I2, k1, k2] - 
     3*Sqrt[3]*SU3D[I1, I3, k1]*SU3F[8, I4, k2]*SU3F[I2, k1, k2] - 
     3*Sqrt[3]*SU3D[I2, I4, k1]*SU3F[8, I1, k2]*SU3F[I3, k1, k2] - 
     3*Sqrt[3]*SU3D[I1, I4, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] - 
     3*Sqrt[3]*SU3D[I1, I2, k1]*SU3F[8, I4, k2]*SU3F[I3, k1, k2] - 
     3*Sqrt[3]*SU3D[I2, I3, k1]*SU3F[8, I1, k2]*SU3F[I4, k1, k2] - 
     3*Sqrt[3]*SU3D[I1, I3, k1]*SU3F[8, I2, k2]*SU3F[I4, k1, k2] - 
     3*Sqrt[3]*SU3D[I1, I2, k1]*SU3F[8, I3, k2]*SU3F[I4, k1, k2] + 
     6*Sqrt[3]*SU3D[I2, I3, I4]*SUNDelta[8, I1] + 6*Sqrt[3]*SU3D[I1, I3, I4]*
      SUNDelta[8, I2] + 6*Sqrt[3]*SU3D[I1, I2, I4]*SUNDelta[8, I3] + 
     6*Sqrt[3]*SU3D[I1, I2, I3]*SUNDelta[8, I4] + 4*Sqrt[3]*SU3D[8, I3, I4]*
      SUNDelta[I1, I2] + 4*Sqrt[3]*SU3D[8, I2, I4]*SUNDelta[I1, I3] + 
     4*Sqrt[3]*SU3D[8, I2, I3]*SUNDelta[I1, I4] + 4*Sqrt[3]*SU3D[8, I1, I4]*
      SUNDelta[I2, I3] + 4*SUNDelta[I1, I4]*SUNDelta[I2, I3] + 
     4*Sqrt[3]*SU3D[8, I1, I3]*SUNDelta[I2, I4] + 4*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] + 4*Sqrt[3]*SU3D[8, I1, I2]*SUNDelta[I3, I4] + 
     4*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((I/9)*(6*SU3D[I1, I4, k1]*SU3D[I2, I3, k1] - 3*SU3D[I1, I3, k1]*
      SU3D[I2, I4, k1] - 3*SU3D[I1, I2, k1]*SU3D[I3, I4, k1] + 
     4*SUNDelta[I1, I4]*SUNDelta[I2, I3] - 2*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] - 2*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((I/9)*(6*SU3D[I1, I4, k1]*SU3D[I2, I3, k1] - 3*SU3D[I1, I3, k1]*
      SU3D[I2, I4, k1] - 3*SU3D[I1, I2, k1]*SU3D[I3, I4, k1] + 
     4*SUNDelta[I1, I4]*SUNDelta[I2, I3] - 2*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] - 2*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((-I/9)*(3*SU3D[I1, I4, k1]*SU3D[I2, I3, k1] - 6*SU3D[I1, I3, k1]*
      SU3D[I2, I4, k1] + 3*SU3D[I1, I2, k1]*SU3D[I3, I4, k1] + 
     2*SUNDelta[I1, I4]*SUNDelta[I2, I3] - 4*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] + 2*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((-I/9)*(3*SU3D[I1, I4, k1]*SU3D[I2, I3, k1] - 6*SU3D[I1, I3, k1]*
      SU3D[I2, I4, k1] + 3*SU3D[I1, I2, k1]*SU3D[I3, I4, k1] + 
     2*SUNDelta[I1, I4]*SUNDelta[I2, I3] - 4*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] + 2*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((-I/9)*(3*SU3D[I1, I4, k1]*SU3D[I2, I3, k1] + 3*SU3D[I1, I3, k1]*
      SU3D[I2, I4, k1] - 6*SU3D[I1, I2, k1]*SU3D[I3, I4, k1] + 
     2*SUNDelta[I1, I4]*SUNDelta[I2, I3] + 2*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] - 4*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((-I/9)*(3*SU3D[I1, I4, k1]*SU3D[I2, I3, k1] + 3*SU3D[I1, I3, k1]*
      SU3D[I2, I4, k1] - 6*SU3D[I1, I2, k1]*SU3D[I3, I4, k1] + 
     2*SUNDelta[I1, I4]*SUNDelta[I2, I3] + 2*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] - 4*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}}
