{{(((-2*I)/3)*CouplingConstant[ChPTW3[2], 1]*
	(CouplingConstant[ChPTW3[4], 6]*
	(3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] -
	Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]])) +
	CouplingConstant[ChPTW3[4], 7]*
	(3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]]]] - Sqrt[3]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]])*
	(UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]) +
	2*CouplingConstant[ChPTW3[4], 5]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 3*CouplingConstant[ChPTW3[4], 8]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 2*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 3*CouplingConstant[ChPTW3[4], 8]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 3*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	3*CouplingConstant[ChPTW3[4], 5]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	Sqrt[3]*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	Sqrt[3]*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	3*CouplingConstant[ChPTW3[4], 5]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
	Sqrt[3]*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	3*CouplingConstant[ChPTW3[4], 5]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	Sqrt[3]*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{(((2*I)/3)*CouplingConstant[ChPTW3[2], 1]*
	(CouplingConstant[ChPTW3[4], 6]*
	(3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] +
	Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]])) +
	CouplingConstant[ChPTW3[4], 7]*
	(3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]]]] + Sqrt[3]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]])*
	(UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]) -
	2*CouplingConstant[ChPTW3[4], 5]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] - 3*CouplingConstant[ChPTW3[4], 8]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] - 2*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 3*CouplingConstant[ChPTW3[4], 8]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 3*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	3*CouplingConstant[ChPTW3[4], 5]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	Sqrt[3]*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	Sqrt[3]*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	3*CouplingConstant[ChPTW3[4], 5]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
	Sqrt[3]*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	3*CouplingConstant[ChPTW3[4], 5]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
	Sqrt[3]*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{(((-2*I)/3)*CouplingConstant[ChPTW3[2], 1]*
	(2*Sqrt[3]*CouplingConstant[ChPTW3[4], 6]*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]]) +
	2*Sqrt[3]*CouplingConstant[ChPTW3[4], 7]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]]*
	(UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]) +
	2*CouplingConstant[ChPTW3[4], 5]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 3*CouplingConstant[ChPTW3[4], 8]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 2*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 3*CouplingConstant[ChPTW3[4], 8]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	2*Sqrt[3]*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	2*Sqrt[3]*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	2*Sqrt[3]*CouplingConstant[ChPTW3[4], 5]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{((-I/18)*CouplingConstant[ChPTW3[2], 1]*
	(9*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 8*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 2*CouplingConstant[ChPTW3[4], 13]*
	(-2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] +
	UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]]*
		(-6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]]]] +
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) +
	3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] +
	UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]]*
		(-6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]]]] +
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]])) +
	9*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 8*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 2*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]] + CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] -
	2*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] + CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] -
	18*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	12*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	18*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	12*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	12*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
	24*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] -
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] -
	24*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
	12*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
	12*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
	24*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	24*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	12*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	12*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
	6*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]] + 12*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	6*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]] + CouplingConstant[ChPTW3[4], 11]*
	(3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]]]]*
		(-4*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] -
		4*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) +
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]]*
		(-4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] - 4*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] +
		3*(Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) +
	3*(5*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		5*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] -
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] -
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] - Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] - 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] + 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] - 3*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] -
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]] + 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] - 3*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] -
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]])) + 9*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 9*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 3*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 3*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] - 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[8]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[3]]]] - 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] + 9*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[3]]]] +
	3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] +
	3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] +
	3*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] - 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[8]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[3]]]] - 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] + 9*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[3]]]] +
	3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] +
	3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] +
	3*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]]))/DecayConstant[PseudoScalar[1],
	RenormalizationState[0]]^4},
{((-I/18)*CouplingConstant[ChPTW3[2], 1]*
	(9*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 8*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 2*CouplingConstant[ChPTW3[4], 13]*
	(-2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
	3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] - 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] - 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] - 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] - 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] - 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] +
	UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]]*
		(6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]]]] +
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) -
	3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] - 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] +
	UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]]*
		(6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]]]] +
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]])) +
	9*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 8*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 2*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]] + CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] -
	2*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] + CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] +
	18*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	12*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	18*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	12*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	12*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] +
	24*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] -
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
	24*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
	12*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	12*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
	24*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	24*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
	12*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	12*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	6*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]] - 12*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	6*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] -
	2*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]] + CouplingConstant[ChPTW3[4], 11]*
	(-(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]]*(4*Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] +
		3*(Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[
				UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
			Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[
				UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
			UTrace1[NonCommutative[UMatrix[UGenerator[8]], UMatrix[UGenerator[
				I1]], UMatrix[UGenerator[I2]]]] - UTrace1[NonCommutative[
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], UMatrix[
				UGenerator[I2]]]] - 2*UTrace1[NonCommutative[UMatrix[
				UGenerator[I1]], UMatrix[UGenerator[8]], UMatrix[
				UGenerator[I2]]]] + Sqrt[3]*UTrace1[NonCommutative[UMatrix[
				UGenerator[I1]], UMatrix[UGenerator[I2]], UMatrix[
				UGenerator[3]]]] - UTrace1[NonCommutative[UMatrix[UGenerator[
				I1]], UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
			2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[
				UGenerator[3]], UMatrix[UGenerator[I1]]]] -
			2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[
				UGenerator[8]], UMatrix[UGenerator[I1]]]] +
			Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[
				UGenerator[I1]], UMatrix[UGenerator[3]]]] -
			UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))) +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]]]]*
		(4*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] +
		4*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) +
	3*(5*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		5*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] - Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] + 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] - 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] + 3*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] -
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]] - 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] + 3*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] -
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]])) + 9*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 9*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] - 3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] - 3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 3*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 3*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[8]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[8]]]] - 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] - 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[3]]]] - 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] + 9*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[3]]]] -
	3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] -
	3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] +
	3*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] - 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[3]]]] - 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] + 9*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[3]]]] -
	3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] -
	3*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] +
	3*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]]))/DecayConstant[PseudoScalar[1],
	RenormalizationState[0]]^4},
{((I/9)*CouplingConstant[ChPTW3[2], 1]*
	(-9*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] - 8*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 2*CouplingConstant[ChPTW3[4], 13]*
	(2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*(UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]) + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*(UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]) +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] +
	9*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]) - 9*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 8*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 2*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]] - CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] +
	2*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] - CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] +
	6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	6*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	2*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	2*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]] + CouplingConstant[ChPTW3[4], 11]*
	(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]]*
		(4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] + 4*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] -
		3*(UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) +
	3*(-5*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
		5*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] -
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]]]]*(UTrace1[NonCommutative[
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] + 2*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]]]] + 2*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]]]]) - UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[6]]]] + Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] - 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] + Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]] -
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] + Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]])) +
	9*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 9*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] - 3*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] - 3*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] - 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]]]] - 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 18*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] - 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] - 6*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]]]] - 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] - 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] + 9*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[3]]]] -
	3*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] - 18*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] + 9*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]], UMatrix[UGenerator[3]]]] -
	3*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]]))/DecayConstant[PseudoScalar[1],
	RenormalizationState[0]]^4},
{((-I/18)*CouplingConstant[ChPTW3[2], 1]*
	(9*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 8*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 8*CouplingConstant[ChPTW3[4], 13]*
	(Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*(UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]) +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*(UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]) +
	3*(UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]]]]*(UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]]) +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]]*(UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]]) +
		(UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])*
		(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]))) +
	9*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 8*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] - 2*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]] + CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] -
	2*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] + CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] +
	12*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
	12*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
	16*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
	16*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	16*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	16*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
	8*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]] - 8*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	4*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]] + CouplingConstant[ChPTW3[4], 11]*
	(4*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]]*
		(2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] +
		3*(UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) +
	3*(5*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		5*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]]]] + 4*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] + 4*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]])) + 12*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] + 12*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + 24*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 24*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 24*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 24*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 24*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 24*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 24*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 24*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 24*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 24*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 24*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 24*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] + 24*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 24*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 24*CouplingConstant[ChPTW3[4], 12]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 24*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] - 24*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] + 12*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] -
	24*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[8]]]] + 12*CouplingConstant[ChPTW3[4], 10]*
	UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{((-I/18)*CouplingConstant[ChPTW3[2], 1]*
	(4*CouplingConstant[ChPTW3[4], 13]*
	(Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]]*(UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
		Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) +
	3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] -
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]]*(UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]))) +
	CouplingConstant[ChPTW3[4], 11]*
	(2*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]]*
		(2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] +
		3*(Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
		4*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
		4*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]]]]*
		(2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] + Sqrt[3]*
		(UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) +
	3*(10*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		10*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		4*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] -
		4*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] + 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] - 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] + 3*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]] - 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] + 3*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]])) +
	2*(2*CouplingConstant[ChPTW3[4], 12]*
		(4*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		4*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]]]] + Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]]]] + Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) +
	CouplingConstant[ChPTW3[4], 10]*
		(9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] +
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] +
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]]]] + 12*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
		4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] + 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]]]] + 12*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
		4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] - 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] + 3*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]] - 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] + 3*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] +
		12*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] +
		12*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] +
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]]))))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{((I/18)*CouplingConstant[ChPTW3[2], 1]*
	(4*CouplingConstant[ChPTW3[4], 13]*
	(-(Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]]) -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
	3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]]]]*(UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
		Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) +
	3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[3]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] +
	6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]]]]*(UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]))) +
	CouplingConstant[ChPTW3[4], 11]*
	(6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[3]]]]*
		(2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] + Sqrt[3]*
		(UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) +
	2*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]]]]*
		(-2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] +
		3*(Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] +
		4*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
		4*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) -
	3*(10*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		10*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		4*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] -
		4*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] -
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] -
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] - 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] + 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] - 3*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]] + 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] - 3*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]])) -
	2*(2*CouplingConstant[ChPTW3[4], 12]*
		(4*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		4*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] -
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]]]] -
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]]]] + Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]]]] -
		3*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]]]] + Sqrt[3]*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) +
	CouplingConstant[ChPTW3[4], 10]*
		(9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] +
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] -
		2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] -
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] -
		9*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]]]] + 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]]]] - 12*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] +
		4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] - 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] +
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]]]] - 12*UTrace1[NonCommutative[
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] +
		4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] + 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]]]] - 3*UTrace1[NonCommutative[
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]] + 6*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]]]] - 3*UTrace1[NonCommutative[
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] +
		Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]]]] - 3*Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] -
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] -
		12*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] +
		12*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] +
		6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] +
		12*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[3]], UMatrix[UGenerator[8]]]] -
		3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[3]]]] -
		6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]]))))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}}
