{{((I/24)*(5*SU2F[3, I1, I4]*SU2F[3, I2, I3] + 5*SU2F[3, I1, I3]*
	SU2F[3, I2, I4] + 5*SU2F[3, I1, I2]*SU2F[3, I3, I4] +
	42*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] +
	32*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] +
	22*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] +
	22*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] -
	54*SUNDelta[I1, I4]*SUNDelta[I2, I3] + 32*SUNDelta[3, I1]*
	SUNDelta[3, I3]*SUNDelta[I2, I4] - 64*SUNDelta[I1, I3]*
	SUNDelta[I2, I4] + 42*SUNDelta[3, I1]*SUNDelta[3, I2]*
	SUNDelta[I3, I4] - 74*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}}
