{{(CouplingConstant[ChPTW3[2], 1]*(((-4*I)/9)*SU3D[6, I3, I5]*
	SU3D[I1, I2, I4] - ((4*I)/9)*SU3D[6, I3, I4]*SU3D[I1, I2, I5] -
	((4*I)/9)*SU3D[6, I2, I3]*SU3D[I1, I4, I5] - ((5*I)/9)*SU3D[6, I1, I5]*
	SU3D[I2, I3, I4] - ((5*I)/9)*SU3D[6, I1, I4]*SU3D[I2, I3, I5] +
	I*SU3D[6, I1, I3]*SU3D[I2, I4, I5] - ((5*I)/9)*SU3D[6, I1, I2]*
	SU3D[I3, I4, I5] - (7*SU3D[I3, I4, I5]*SU3F[6, I1, I2])/9 +
	(SU3D[I2, I4, I5]*SU3F[6, I1, I3])/3 -
	(7*SU3D[I2, I3, I5]*SU3F[6, I1, I4])/9 -
	(7*SU3D[I2, I3, I4]*SU3F[6, I1, I5])/9 +
	(2*SU3D[I1, I4, I5]*SU3F[6, I2, I3])/9 -
	(2*SU3D[I1, I2, I5]*SU3F[6, I3, I4])/9 -
	(2*SU3D[I1, I2, I4]*SU3F[6, I3, I5])/9 + SU3D[6, I4, I5]*
	(((2*I)/3)*SU3D[I1, I2, I3] - (2*SU3F[I1, I2, I3])/9) +
	SU3D[6, I2, I5]*(((2*I)/3)*SU3D[I1, I3, I4] + (2*SU3F[I1, I3, I4])/9) +
	SU3D[6, I2, I4]*(((2*I)/3)*SU3D[I1, I3, I5] + (2*SU3F[I1, I3, I5])/9) +
	SU3D[I4, I5, k2]*(SU3D[6, I2, k1]*((-I/2)*SU3F[I1, k2, k3]*
		SU3F[I3, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]) +
	SU3D[6, I1, k1]*((I/6)*SU3F[I2, k2, k3]*SU3F[I3, k1, k3] -
		(I/6)*SU3F[I2, k1, k3]*SU3F[I3, k2, k3])) +
	SU3D[I5, k2, k3]*(SU3D[I3, I4, k1]*((-I/2)*SU3F[6, I2, k2]*
		SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*SU3F[I2, k1, k3]) +
	SU3D[I2, I4, k1]*((I/2)*SU3F[6, I3, k2]*SU3F[I1, k1, k3] +
		(I/6)*SU3F[6, I1, k2]*SU3F[I3, k1, k3]) + SU3D[I1, I4, k1]*
		((-I/6)*SU3F[6, I3, k2]*SU3F[I2, k1, k3] - (I/4)*SU3F[6, I2, k2]*
		SU3F[I3, k1, k3]) + SU3D[I2, I3, k1]*
		((-I/2)*SU3F[6, I4, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I4, k1, k3]) + SU3D[I1, I3, k1]*
		((I/4)*SU3F[6, I4, k2]*SU3F[I2, k1, k3] + (I/4)*SU3F[6, I2, k2]*
		SU3F[I4, k1, k3]) + SU3D[I1, I2, k1]*
		((-I/4)*SU3F[6, I4, k2]*SU3F[I3, k1, k3] - (I/6)*SU3F[6, I3, k2]*
		SU3F[I4, k1, k3])) + SU3D[6, I3, k1]*SU3D[I1, I5, k2]*
	SU3D[I2, k1, k3]*((I/6)*SU3D[I4, k2, k3] - SU3F[I4, k2, k3]/6) +
	SU3D[I5, k1, k2]*((-I/6)*SU3D[I1, I4, k1]*SU3F[6, I3, k3]*
		SU3F[I2, k2, k3] + SU3D[I3, I4, k1]*((I/3)*SU3F[6, I2, k3]*
		SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*SU3F[I2, k2, k3]) +
	SU3F[6, I4, k2]*((SU3F[I1, I3, k3]*SU3F[I2, k1, k3])/12 -
		(SU3F[I1, I2, k3]*SU3F[I3, k1, k3])/12) + SU3D[I2, I4, k1]*
		((-I/3)*SU3F[6, I3, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I3, k2, k3]) + SU3F[6, I4, k3]*
		(-(SU3F[I1, I3, k1]*SU3F[I2, k2, k3])/12 +
		(SU3F[I1, I2, k1]*SU3F[I3, k2, k3])/3) + SU3F[6, I3, k2]*
		(-(SU3F[I1, I4, k3]*SU3F[I2, k1, k3])/6 -
		(SU3F[I1, I2, k3]*SU3F[I4, k1, k3])/6) + SU3F[6, I2, k2]*
		(-(SU3F[I1, I4, k3]*SU3F[I3, k1, k3])/12 +
		(SU3F[I1, I3, k3]*SU3F[I4, k1, k3])/12) + SU3F[6, I1, k2]*
		(-(SU3F[I2, k1, k3]*SU3F[I3, I4, k3])/6 +
		(SU3F[I2, I3, k3]*SU3F[I4, k1, k3])/6) - (I/6)*SU3D[I1, I2, k1]*
		SU3F[6, I3, k3]*SU3F[I4, k2, k3] + SU3D[I2, I3, k1]*
		((I/3)*SU3F[6, I4, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I4, k2, k3]) + SU3D[I1, I3, k1]*
		((I/4)*SU3F[6, I4, k3]*SU3F[I2, k2, k3] + (I/4)*SU3F[6, I2, k3]*
		SU3F[I4, k2, k3]) + SU3F[6, I3, k3]*
		((SU3F[I1, I4, k1]*SU3F[I2, k2, k3])/6 +
		(SU3F[I1, I2, k1]*SU3F[I4, k2, k3])/6) + SU3F[6, I2, k3]*
		((SU3F[I1, I4, k1]*SU3F[I3, k2, k3])/3 -
		(SU3F[I1, I3, k1]*SU3F[I4, k2, k3])/12) + SU3F[6, I1, k3]*
		((SU3F[I2, k2, k3]*SU3F[I3, I4, k1])/6 -
		(SU3F[I2, I3, k1]*SU3F[I4, k2, k3])/6)) +
	SU3D[I1, I5, k2]*(SU3D[6, I2, k1]*(-(SU3D[I4, k1, k3]*SU3F[I3, k2, k3])/
		4 + (I/4)*SU3F[I3, k2, k3]*SU3F[I4, k1, k3]) +
	SU3D[6, I3, k1]*((SU3D[I4, k2, k3]*SU3F[I2, k1, k3])/6 -
		(SU3D[I4, k1, k3]*SU3F[I2, k2, k3])/6 + (I/6)*SU3F[I2, k2, k3]*
		SU3F[I4, k1, k3] + (I/6)*SU3F[I2, k1, k3]*SU3F[I4, k2, k3])) +
	SU3D[I1, k2, k3]*((I/2)*SU3D[6, I4, k1]*SU3D[I2, k1, k2]*
		SU3D[I3, I5, k3] - (I/2)*SU3D[6, I3, k1]*SU3D[I2, k1, k3]*
		SU3D[I4, I5, k2] - (I/2)*SU3D[6, I2, k1]*SU3D[I3, k1, k2]*
		SU3D[I4, I5, k3] + SU3D[6, I3, k1]*((-I/2)*SU3D[I2, I5, k2]*
		SU3D[I4, k1, k3] - (I/2)*SU3D[I2, I4, k2]*SU3D[I5, k1, k3] -
		(SU3D[I4, I5, k3]*SU3F[I2, k1, k2])/2) -
	(SU3D[6, I2, k1]*SU3D[I4, I5, k3]*SU3F[I3, k1, k2])/2 +
	SU3D[6, I2, k1]*SU3D[I3, I5, k3]*((I/2)*SU3D[I4, k1, k2] +
		SU3F[I4, k1, k2]/2) - (SU3D[6, I3, k1]*SU3D[I2, I5, k3]*
		SU3F[I4, k1, k2])/2 + SU3D[6, I4, k1]*
		((-I/2)*SU3D[I2, I5, k3]*SU3D[I3, k1, k2] +
		(SU3D[I3, I5, k3]*SU3F[I2, k1, k2])/2 -
		(SU3D[I2, I5, k3]*SU3F[I3, k1, k2])/2 + SU3D[I2, I3, k3]*
		((I/2)*SU3D[I5, k1, k2] + SU3F[I5, k1, k2]/2)) +
	SU3D[6, I2, k1]*SU3D[I3, I4, k3]*((I/2)*SU3D[I5, k1, k2] +
		SU3F[I5, k1, k2]/2) - (SU3D[6, I3, k1]*SU3D[I2, I4, k3]*
		SU3F[I5, k1, k2])/2) + SU3D[I4, k2, k3]*
	(SU3D[I5, k1, k3]*(-(SU3D[I2, I3, k1]*SU3F[6, I1, k2])/6 +
		(SU3D[I1, I3, k1]*SU3F[6, I2, k2])/4 -
		(SU3D[I1, I2, k1]*SU3F[6, I3, k2])/6) + SU3D[I3, I5, k1]*
		((-I/2)*SU3F[6, I2, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I2, k1, k3]) + SU3D[I2, I5, k1]*
		((I/2)*SU3F[6, I3, k2]*SU3F[I1, k1, k3] + (I/6)*SU3F[6, I1, k2]*
		SU3F[I3, k1, k3]) + SU3D[I1, I5, k1]*
		((-I/6)*SU3F[6, I3, k2]*SU3F[I2, k1, k3] - (I/4)*SU3F[6, I2, k2]*
		SU3F[I3, k1, k3]) + SU3D[I2, I3, k1]*
		((-I/2)*SU3F[6, I5, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I3, k1]*
		((I/4)*SU3F[6, I5, k2]*SU3F[I2, k1, k3] + (I/4)*SU3F[6, I2, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I2, k1]*
		((-I/4)*SU3F[6, I5, k2]*SU3F[I3, k1, k3] - (I/6)*SU3F[6, I3, k2]*
		SU3F[I5, k1, k3])) + SU3D[I3, k2, k3]*
	(-(SU3D[I2, I5, k1]*SU3D[I4, k1, k3]*SU3F[6, I1, k2])/6 -
	(SU3D[I2, I4, k1]*SU3D[I5, k1, k3]*SU3F[6, I1, k2])/6 +
	SU3D[I4, I5, k3]*(-(SU3D[6, I2, k1]*SU3F[I1, k1, k2])/3 -
		(SU3D[6, I1, k1]*SU3F[I2, k1, k2])/6) + SU3D[6, I2, k1]*
		SU3D[I1, I5, k2]*((I/4)*SU3D[I4, k1, k3] + SU3F[I4, k1, k3]/4) +
	SU3D[I2, I5, k1]*((I/2)*SU3F[6, I4, k2]*SU3F[I1, k1, k3] -
		(I/6)*SU3F[6, I1, k2]*SU3F[I4, k1, k3]) + SU3D[6, I1, k1]*
		(SU3D[I2, I5, k2]*((-I/6)*SU3D[I4, k1, k3] - SU3F[I4, k1, k3]/6) +
		SU3D[I2, I4, k2]*((-I/6)*SU3D[I5, k1, k3] - SU3F[I5, k1, k3]/6)) +
	SU3D[6, I2, k1]*SU3D[I1, I4, k2]*((I/4)*SU3D[I5, k1, k3] +
		SU3F[I5, k1, k3]/4) + SU3D[I2, I4, k1]*
		((I/2)*SU3F[6, I5, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I5, k1, k3]) + SU3D[6, I2, k1]*
		(-(SU3D[I5, k1, k2]*SU3F[I1, I4, k3])/12 -
		(SU3D[I4, k1, k2]*SU3F[I1, I5, k3])/12 + (I/12)*SU3F[I1, I5, k2]*
		SU3F[I4, k1, k3] + (I/12)*SU3F[I1, I4, k2]*SU3F[I5, k1, k3])) +
	SU3D[I2, k2, k3]*((I/6)*SU3D[6, I1, k1]*SU3D[I3, k1, k2]*
		SU3D[I4, I5, k3] + SU3D[I5, k1, k3]*
		(-(SU3D[I1, I4, k1]*SU3F[6, I3, k2])/6 +
		(SU3D[I1, I3, k1]*SU3F[6, I4, k2])/4) + SU3D[I4, k1, k3]*
		(-(SU3D[I1, I5, k1]*SU3F[6, I3, k2])/6 +
		(SU3D[I1, I3, k1]*SU3F[6, I5, k2])/4) + SU3D[I3, k1, k3]*
		(-(SU3D[I1, I5, k1]*SU3F[6, I4, k2])/4 -
		(SU3D[I1, I4, k1]*SU3F[6, I5, k2])/4) +
	(SU3D[6, I1, k1]*SU3D[I4, I5, k3]*SU3F[I3, k1, k2])/6 +
	(SU3D[6, I1, k1]*SU3D[I3, I5, k3]*SU3F[I4, k1, k2])/6 +
	SU3D[6, I3, k1]*SU3D[I1, I5, k2]*((I/6)*SU3D[I4, k1, k3] +
		SU3F[I4, k1, k3]/6) + SU3D[I1, I5, k1]*
		((-I/4)*SU3F[6, I4, k2]*SU3F[I3, k1, k3] - (I/6)*SU3F[6, I3, k2]*
		SU3F[I4, k1, k3]) + SU3D[6, I3, k1]*SU3D[I1, I4, k2]*
		((I/6)*SU3D[I5, k1, k3] + SU3F[I5, k1, k3]/6) +
	SU3D[I1, I4, k1]*((-I/4)*SU3F[6, I5, k2]*SU3F[I3, k1, k3] -
		(I/6)*SU3F[6, I3, k2]*SU3F[I5, k1, k3]) + SU3D[I1, I3, k1]*
		((I/4)*SU3F[6, I5, k2]*SU3F[I4, k1, k3] + (I/4)*SU3F[6, I4, k2]*
		SU3F[I5, k1, k3]) + SU3D[6, I4, k1]*
		((SU3D[I5, k1, k2]*SU3F[I1, I3, k3])/12 -
		(SU3D[I3, k1, k2]*SU3F[I1, I5, k3])/3 -
		(SU3D[I3, I5, k3]*SU3F[I1, k1, k2])/3 + (I/3)*SU3F[I1, I5, k2]*
		SU3F[I3, k1, k3] + SU3D[I1, I3, k2]*((-I/4)*SU3D[I5, k1, k3] -
		SU3F[I5, k1, k3]/4) - (I/12)*SU3F[I1, I3, k2]*SU3F[I5, k1, k3]) +
	SU3D[6, I3, k1]*(-(SU3D[I5, k1, k2]*SU3F[I1, I4, k3])/6 -
		(SU3D[I4, k1, k2]*SU3F[I1, I5, k3])/6 +
		(SU3D[I4, I5, k3]*SU3F[I1, k1, k2])/3 + (I/6)*SU3F[I1, I5, k2]*
		SU3F[I4, k1, k3] + (I/6)*SU3F[I1, I4, k2]*SU3F[I5, k1, k3]) +
	SU3D[6, I1, k1]*((I/6)*SU3D[I3, I5, k2]*SU3D[I4, k1, k3] +
		(I/6)*SU3D[I3, I4, k2]*SU3D[I5, k1, k3] -
		(SU3D[I5, k1, k2]*SU3F[I3, I4, k3])/6 -
		(SU3D[I4, k1, k2]*SU3F[I3, I5, k3])/6 + (I/6)*SU3F[I3, I5, k2]*
		SU3F[I4, k1, k3] + (I/6)*SU3F[I3, I4, k2]*SU3F[I5, k1, k3])) +
	SU3D[I3, I4, k3]*((SU3D[6, I1, k1]*SU3D[I2, k2, k3]*SU3F[I5, k1, k2])/
		6 + SU3D[I1, k1, k2]*((SU3D[I5, k2, k3]*SU3F[6, I2, k1])/3 +
		(SU3D[I2, k2, k3]*SU3F[6, I5, k1])/3 - (I/3)*SU3F[6, I5, k1]*
		SU3F[I2, k2, k3] + SU3D[6, I2, k1]*((-I/3)*SU3D[I5, k2, k3] -
		SU3F[I5, k2, k3]/3) - (I/3)*SU3F[6, I2, k1]*SU3F[I5, k2, k3])) +
	SU3D[I1, k1, k2]*(SU3D[I3, k2, k3]*SU3D[I4, I5, k3]*
		((-I/3)*SU3D[6, I2, k1] + SU3F[6, I2, k1]/3) +
	(SU3D[I3, k1, k3]*SU3D[I4, I5, k2]*SU3F[6, I2, k3])/2 +
	(SU3D[I2, I4, k2]*SU3D[I5, k1, k3]*SU3F[6, I3, k3])/2 +
	SU3D[I2, k2, k3]*((-I/3)*SU3D[6, I4, k1]*SU3D[I3, I5, k3] +
		(I/3)*SU3D[6, I3, k1]*SU3D[I4, I5, k3] -
		(SU3D[I4, I5, k3]*SU3F[6, I3, k1])/3 +
		(SU3D[I3, I5, k3]*SU3F[6, I4, k1])/3) + SU3D[I5, k1, k3]*
		(-(SU3D[I3, I4, k2]*SU3F[6, I2, k3])/2 -
		(SU3D[I2, I3, k2]*SU3F[6, I4, k3])/2) + SU3D[I2, I5, k2]*
		((SU3D[I4, k1, k3]*SU3F[6, I3, k3])/2 +
		(SU3D[I3, k1, k3]*SU3F[6, I4, k3])/2) +
	(SU3D[I2, I4, k2]*SU3D[I3, k1, k3]*SU3F[6, I5, k3])/2 +
	SU3D[I4, k1, k3]*(-(SU3D[I3, I5, k2]*SU3F[6, I2, k3])/2 -
		(SU3D[I2, I3, k2]*SU3F[6, I5, k3])/2) + SU3D[I2, k1, k3]*
		((SU3D[I4, I5, k2]*SU3F[6, I3, k3])/2 -
		(SU3D[I3, I5, k2]*SU3F[6, I4, k3])/2 -
		(SU3D[I3, I4, k2]*SU3F[6, I5, k3])/2) +
	(SU3D[6, I3, k1]*SU3D[I4, I5, k3]*SU3F[I2, k2, k3])/3 +
	SU3D[I4, I5, k3]*((I/3)*SU3F[6, I3, k1]*SU3F[I2, k2, k3] -
		(SU3D[6, I2, k1]*SU3F[I3, k2, k3])/3 - (I/3)*SU3F[6, I2, k1]*
		SU3F[I3, k2, k3]) + SU3D[I4, I5, k1]*
		((I/2)*SU3F[6, I3, k3]*SU3F[I2, k2, k3] + (I/2)*SU3F[6, I2, k3]*
		SU3F[I3, k2, k3]) + SU3D[I3, I5, k3]*
		((SU3D[I4, k2, k3]*SU3F[6, I2, k1])/3 - (I/3)*SU3F[6, I4, k1]*
		SU3F[I2, k2, k3] + SU3D[6, I2, k1]*((-I/3)*SU3D[I4, k2, k3] -
		SU3F[I4, k2, k3]/3) - (I/3)*SU3F[6, I2, k1]*SU3F[I4, k2, k3]) +
	SU3D[I3, I5, k1]*((-I/2)*SU3F[6, I4, k3]*SU3F[I2, k2, k3] -
		(I/2)*SU3F[6, I2, k3]*SU3F[I4, k2, k3]) + SU3D[I2, I5, k3]*
		(-(SU3D[I4, k2, k3]*SU3F[6, I3, k1])/3 +
		(SU3D[I3, k2, k3]*SU3F[6, I4, k1])/3 - (I/3)*SU3F[6, I4, k1]*
		SU3F[I3, k2, k3] + SU3D[6, I3, k1]*((I/3)*SU3D[I4, k2, k3] +
		SU3F[I4, k2, k3]/3) + (I/3)*SU3F[6, I3, k1]*SU3F[I4, k2, k3]) +
	SU3D[I2, I5, k1]*((I/2)*SU3F[6, I4, k3]*SU3F[I3, k2, k3] +
		(I/2)*SU3F[6, I3, k3]*SU3F[I4, k2, k3]) + SU3D[6, I4, k1]*
		(-(SU3D[I3, I5, k3]*SU3F[I2, k2, k3])/3 + SU3D[I2, I5, k3]*
		((-I/3)*SU3D[I3, k2, k3] - SU3F[I3, k2, k3]/3) +
		SU3D[I2, I3, k3]*((-I/3)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/3)) +
	SU3D[I3, I4, k1]*((-I/2)*SU3F[6, I5, k3]*SU3F[I2, k2, k3] -
		(I/2)*SU3F[6, I2, k3]*SU3F[I5, k2, k3]) + SU3D[I2, I4, k3]*
		(-(SU3D[I5, k2, k3]*SU3F[6, I3, k1])/3 +
		(SU3D[I3, k2, k3]*SU3F[6, I5, k1])/3 - (I/3)*SU3F[6, I5, k1]*
		SU3F[I3, k2, k3] + SU3D[6, I3, k1]*((I/3)*SU3D[I5, k2, k3] +
		SU3F[I5, k2, k3]/3) + (I/3)*SU3F[6, I3, k1]*SU3F[I5, k2, k3]) +
	SU3D[I2, I4, k1]*((I/2)*SU3F[6, I5, k3]*SU3F[I3, k2, k3] +
		(I/2)*SU3F[6, I3, k3]*SU3F[I5, k2, k3]) + SU3D[I2, I3, k3]*
		((SU3D[I5, k2, k3]*SU3F[6, I4, k1])/3 +
		(SU3D[I4, k2, k3]*SU3F[6, I5, k1])/3 - (I/3)*SU3F[6, I5, k1]*
		SU3F[I4, k2, k3] - (I/3)*SU3F[6, I4, k1]*SU3F[I5, k2, k3]) +
	SU3D[I2, I3, k1]*((-I/2)*SU3F[6, I5, k3]*SU3F[I4, k2, k3] -
		(I/2)*SU3F[6, I4, k3]*SU3F[I5, k2, k3])) +
	SU3D[I3, k1, k2]*(SU3D[I5, k2, k3]*((SU3D[I2, I4, k1]*SU3F[6, I1, k3])/
		6 - (SU3D[I1, I4, k1]*SU3F[6, I2, k3])/4 -
		(SU3D[I1, I2, k1]*SU3F[6, I4, k3])/4 - (I/12)*SU3F[6, I4, k3]*
		SU3F[I1, I2, k1] - (I/12)*SU3F[6, I2, k3]*SU3F[I1, I4, k1]) +
	SU3D[I5, k1, k3]*((-I/3)*SU3F[6, I4, k2]*SU3F[I1, I2, k3] -
		(I/3)*SU3F[6, I2, k2]*SU3F[I1, I4, k3]) + SU3D[I4, k2, k3]*
		((SU3D[I2, I5, k1]*SU3F[6, I1, k3])/6 -
		(SU3D[I1, I5, k1]*SU3F[6, I2, k3])/4 -
		(SU3D[I1, I2, k1]*SU3F[6, I5, k3])/4 - (I/12)*SU3F[6, I5, k3]*
		SU3F[I1, I2, k1] - (I/12)*SU3F[6, I2, k3]*SU3F[I1, I5, k1]) +
	SU3D[I4, k1, k3]*((-I/3)*SU3F[6, I5, k2]*SU3F[I1, I2, k3] -
		(I/3)*SU3F[6, I2, k2]*SU3F[I1, I5, k3]) + SU3D[I4, I5, k3]*
		(-(SU3D[6, I2, k1]*SU3F[I1, k2, k3])/2 - (I/2)*SU3F[6, I2, k1]*
		SU3F[I1, k2, k3] + (SU3D[6, I1, k1]*SU3F[I2, k2, k3])/6 +
		(I/6)*SU3F[6, I1, k1]*SU3F[I2, k2, k3]) + SU3D[I4, I5, k1]*
		((I/3)*SU3F[6, I2, k3]*SU3F[I1, k2, k3] + (I/6)*SU3F[6, I1, k3]*
		SU3F[I2, k2, k3]) + SU3F[6, I5, k2]*
		(-(SU3F[I1, I4, k3]*SU3F[I2, k1, k3])/3 -
		(SU3F[I1, I2, k3]*SU3F[I4, k1, k3])/3) + SU3D[I2, I5, k1]*
		((I/3)*SU3F[6, I4, k3]*SU3F[I1, k2, k3] + (I/6)*SU3F[6, I1, k3]*
		SU3F[I4, k2, k3]) + SU3D[I1, I5, k1]*
		((-I/4)*SU3F[6, I4, k3]*SU3F[I2, k2, k3] - (I/4)*SU3F[6, I2, k3]*
		SU3F[I4, k2, k3]) + SU3F[6, I5, k3]*
		((SU3F[I1, I4, k1]*SU3F[I2, k2, k3])/12 +
		(SU3F[I1, I2, k1]*SU3F[I4, k2, k3])/12) + SU3F[6, I4, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I2, k1, k3])/3 -
		(SU3F[I1, I2, k3]*SU3F[I5, k1, k3])/3) + SU3F[6, I2, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I4, k1, k3])/3 -
		(SU3F[I1, I4, k3]*SU3F[I5, k1, k3])/3) + SU3D[I2, I4, k1]*
		((I/3)*SU3F[6, I5, k3]*SU3F[I1, k2, k3] + (I/6)*SU3F[6, I1, k3]*
		SU3F[I5, k2, k3]) + SU3D[I1, I4, k1]*
		((-I/4)*SU3F[6, I5, k3]*SU3F[I2, k2, k3] - (I/4)*SU3F[6, I2, k3]*
		SU3F[I5, k2, k3]) + SU3D[I1, I2, k1]*
		((-I/4)*SU3F[6, I5, k3]*SU3F[I4, k2, k3] - (I/4)*SU3F[6, I4, k3]*
		SU3F[I5, k2, k3]) + SU3F[6, I4, k3]*
		((SU3F[I1, I5, k1]*SU3F[I2, k2, k3])/12 +
		(SU3F[I1, I2, k1]*SU3F[I5, k2, k3])/12) + SU3F[6, I2, k3]*
		((SU3F[I1, I5, k1]*SU3F[I4, k2, k3])/12 +
		(SU3F[I1, I4, k1]*SU3F[I5, k2, k3])/12) + SU3D[6, I2, k1]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, I4, k3])/3 -
		(SU3D[I4, k2, k3]*SU3F[I1, I5, k3])/3 + (I/3)*SU3F[I1, I5, k3]*
		SU3F[I4, k2, k3] + (I/3)*SU3F[I1, I4, k3]*SU3F[I5, k2, k3])) +
	SU3D[I4, k1, k2]*(SU3D[I5, k2, k3]*(-(SU3D[I2, I3, k1]*SU3F[6, I1, k3])/
		6 + (SU3D[I1, I3, k1]*SU3F[6, I2, k3])/4 -
		(SU3D[I1, I2, k1]*SU3F[6, I3, k3])/6 - (I/6)*SU3F[6, I3, k3]*
		SU3F[I1, I2, k1] + (I/12)*SU3F[6, I2, k3]*SU3F[I1, I3, k1] +
		(I/6)*SU3F[6, I1, k3]*SU3F[I2, I3, k1]) + SU3D[I5, k1, k3]*
		((-I/6)*SU3F[6, I3, k2]*SU3F[I1, I2, k3] + (I/12)*SU3F[6, I2, k2]*
		SU3F[I1, I3, k3] + (I/6)*SU3F[6, I1, k2]*SU3F[I2, I3, k3]) -
	(I/6)*SU3D[I1, I5, k1]*SU3F[6, I3, k3]*SU3F[I2, k2, k3] +
	SU3D[I3, I5, k1]*((I/3)*SU3F[6, I2, k3]*SU3F[I1, k2, k3] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I2, k2, k3]) + SU3F[6, I5, k2]*
		((SU3F[I1, I3, k3]*SU3F[I2, k1, k3])/12 -
		(SU3F[I1, I2, k3]*SU3F[I3, k1, k3])/12) + SU3D[I2, I5, k1]*
		((-I/3)*SU3F[6, I3, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I3, k2, k3]) + SU3F[6, I5, k3]*
		(-(SU3F[I1, I3, k1]*SU3F[I2, k2, k3])/12 +
		(SU3F[I1, I2, k1]*SU3F[I3, k2, k3])/3) + SU3F[6, I3, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I2, k1, k3])/6 -
		(SU3F[I1, I2, k3]*SU3F[I5, k1, k3])/6) + SU3F[6, I2, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I3, k1, k3])/12 +
		(SU3F[I1, I3, k3]*SU3F[I5, k1, k3])/12) + SU3F[6, I1, k2]*
		(-(SU3F[I2, k1, k3]*SU3F[I3, I5, k3])/6 +
		(SU3F[I2, I3, k3]*SU3F[I5, k1, k3])/6) - (I/6)*SU3D[I1, I2, k1]*
		SU3F[6, I3, k3]*SU3F[I5, k2, k3] + SU3D[I2, I3, k1]*
		((I/3)*SU3F[6, I5, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I5, k2, k3]) + SU3D[I1, I3, k1]*
		((I/4)*SU3F[6, I5, k3]*SU3F[I2, k2, k3] + (I/4)*SU3F[6, I2, k3]*
		SU3F[I5, k2, k3]) + SU3F[6, I3, k3]*
		((SU3F[I1, I5, k1]*SU3F[I2, k2, k3])/6 +
		(SU3F[I1, I2, k1]*SU3F[I5, k2, k3])/6) + SU3F[6, I2, k3]*
		((SU3F[I1, I5, k1]*SU3F[I3, k2, k3])/3 -
		(SU3F[I1, I3, k1]*SU3F[I5, k2, k3])/12) + SU3F[6, I1, k3]*
		((SU3F[I2, k2, k3]*SU3F[I3, I5, k1])/6 -
		(SU3F[I2, I3, k1]*SU3F[I5, k2, k3])/6)) +
	SU3D[I1, I4, k2]*(SU3D[6, I2, k1]*(-(SU3D[I5, k1, k3]*SU3F[I3, k2, k3])/
		4 + (I/4)*SU3F[I3, k2, k3]*SU3F[I5, k1, k3]) +
	SU3D[6, I3, k1]*SU3D[I2, k1, k3]*((I/6)*SU3D[I5, k2, k3] -
		SU3F[I5, k2, k3]/6) + SU3D[6, I3, k1]*
		((SU3D[I5, k2, k3]*SU3F[I2, k1, k3])/6 -
		(SU3D[I5, k1, k3]*SU3F[I2, k2, k3])/6 + (I/6)*SU3F[I2, k2, k3]*
		SU3F[I5, k1, k3] + (I/6)*SU3F[I2, k1, k3]*SU3F[I5, k2, k3])) +
	SU3D[I2, k1, k2]*(-(SU3D[I3, k1, k3]*SU3D[I4, I5, k2]*SU3F[6, I1, k3])/
		6 + SU3D[I3, k2, k3]*(SU3D[I4, I5, k3]*((-I/6)*SU3D[6, I1, k1] +
		SU3F[6, I1, k1]/6) - (I/3)*SU3F[6, I5, k3]*SU3F[I1, I4, k1] -
		(I/3)*SU3F[6, I4, k3]*SU3F[I1, I5, k1]) + SU3D[I3, k1, k3]*
		((-I/12)*SU3F[6, I5, k2]*SU3F[I1, I4, k3] - (I/12)*SU3F[6, I4, k2]*
		SU3F[I1, I5, k3]) + SU3D[I5, k2, k3]*
		(-(SU3D[I1, I4, k1]*SU3F[6, I3, k3])/6 +
		(SU3D[I1, I3, k1]*SU3F[6, I4, k3])/4 + (I/12)*SU3F[6, I4, k3]*
		SU3F[I1, I3, k1] - (I/6)*SU3F[6, I3, k3]*SU3F[I1, I4, k1] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I3, I4, k1]) + SU3D[I5, k1, k3]*
		(-(SU3D[I3, I4, k2]*SU3F[6, I1, k3])/6 + (I/12)*SU3F[6, I4, k2]*
		SU3F[I1, I3, k3] - (I/6)*SU3F[6, I3, k2]*SU3F[I1, I4, k3] -
		(I/6)*SU3F[6, I1, k2]*SU3F[I3, I4, k3]) + SU3D[I4, k2, k3]*
		(-(SU3D[I1, I5, k1]*SU3F[6, I3, k3])/6 +
		(SU3D[I1, I3, k1]*SU3F[6, I5, k3])/4 + (I/12)*SU3F[6, I5, k3]*
		SU3F[I1, I3, k1] - (I/6)*SU3F[6, I3, k3]*SU3F[I1, I5, k1] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I3, I5, k1]) + SU3D[I4, k1, k3]*
		(-(SU3D[I3, I5, k2]*SU3F[6, I1, k3])/6 + (I/12)*SU3F[6, I5, k2]*
		SU3F[I1, I3, k3] - (I/6)*SU3F[6, I3, k2]*SU3F[I1, I5, k3] -
		(I/6)*SU3F[6, I1, k2]*SU3F[I3, I5, k3]) + SU3D[I4, I5, k3]*
		((-I/2)*SU3F[6, I3, k1]*SU3F[I1, k2, k3] -
		(SU3D[6, I1, k1]*SU3F[I3, k2, k3])/6 - (I/6)*SU3F[6, I1, k1]*
		SU3F[I3, k2, k3]) + SU3D[I4, I5, k1]*
		((-I/3)*SU3F[6, I3, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I3, k2, k3]) + SU3F[6, I5, k2]*
		(-(SU3F[I1, I4, k3]*SU3F[I3, k1, k3])/12 +
		(SU3F[I1, I3, k3]*SU3F[I4, k1, k3])/12) - (I/6)*SU3D[I1, I5, k1]*
		SU3F[6, I3, k3]*SU3F[I4, k2, k3] + SU3D[I3, I5, k3]*
		(-(SU3D[I4, k2, k3]*SU3F[6, I1, k1])/6 + (I/2)*SU3F[6, I4, k1]*
		SU3F[I1, k2, k3] + SU3D[6, I1, k1]*((I/6)*SU3D[I4, k2, k3] +
		SU3F[I4, k2, k3]/6) + (I/6)*SU3F[6, I1, k1]*SU3F[I4, k2, k3]) +
	SU3D[I3, I5, k1]*((I/3)*SU3F[6, I4, k3]*SU3F[I1, k2, k3] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I4, k2, k3]) + SU3F[6, I5, k3]*
		((SU3F[I1, I4, k1]*SU3F[I3, k2, k3])/3 -
		(SU3F[I1, I3, k1]*SU3F[I4, k2, k3])/12) + SU3F[6, I4, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I3, k1, k3])/12 +
		(SU3F[I1, I3, k3]*SU3F[I5, k1, k3])/12) + SU3F[6, I3, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I1, I4, k3]*SU3F[I5, k1, k3])/6) + SU3F[6, I1, k2]*
		(-(SU3F[I3, I5, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I3, I4, k3]*SU3F[I5, k1, k3])/6) - (I/6)*SU3D[I1, I4, k1]*
		SU3F[6, I3, k3]*SU3F[I5, k2, k3] + SU3D[I3, I4, k3]*
		(-(SU3D[I5, k2, k3]*SU3F[6, I1, k1])/6 + (I/2)*SU3F[6, I5, k1]*
		SU3F[I1, k2, k3] + SU3D[6, I1, k1]*((I/6)*SU3D[I5, k2, k3] +
		SU3F[I5, k2, k3]/6) + (I/6)*SU3F[6, I1, k1]*SU3F[I5, k2, k3]) +
	SU3D[I3, I4, k1]*((I/3)*SU3F[6, I5, k3]*SU3F[I1, k2, k3] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I5, k2, k3]) + SU3D[I1, I3, k1]*
		((I/4)*SU3F[6, I5, k3]*SU3F[I4, k2, k3] + (I/4)*SU3F[6, I4, k3]*
		SU3F[I5, k2, k3]) + SU3F[6, I4, k3]*
		((SU3F[I1, I5, k1]*SU3F[I3, k2, k3])/3 -
		(SU3F[I1, I3, k1]*SU3F[I5, k2, k3])/12) + SU3D[6, I4, k1]*
		((SU3D[I5, k2, k3]*SU3F[I1, I3, k3])/12 -
		(SU3D[I3, k2, k3]*SU3F[I1, I5, k3])/12 +
		(SU3D[I3, I5, k3]*SU3F[I1, k2, k3])/2 + (I/12)*SU3F[I1, I5, k3]*
		SU3F[I3, k2, k3] - (I/12)*SU3F[I1, I3, k3]*SU3F[I5, k2, k3]) +
	SU3F[6, I3, k3]*((SU3F[I1, I5, k1]*SU3F[I4, k2, k3])/6 +
		(SU3F[I1, I4, k1]*SU3F[I5, k2, k3])/6) + SU3D[6, I3, k1]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, I4, k3])/6 -
		(SU3D[I4, k2, k3]*SU3F[I1, I5, k3])/6 -
		(SU3D[I4, I5, k3]*SU3F[I1, k2, k3])/2 + (I/6)*SU3F[I1, I5, k3]*
		SU3F[I4, k2, k3] + (I/6)*SU3F[I1, I4, k3]*SU3F[I5, k2, k3]) +
	SU3F[6, I1, k3]*((SU3F[I3, I5, k1]*SU3F[I4, k2, k3])/6 +
		(SU3F[I3, I4, k1]*SU3F[I5, k2, k3])/6) + SU3D[6, I1, k1]*
		(-(SU3D[I5, k2, k3]*SU3F[I3, I4, k3])/6 -
		(SU3D[I4, k2, k3]*SU3F[I3, I5, k3])/6 + (I/6)*SU3F[I3, I5, k3]*
		SU3F[I4, k2, k3] + (I/6)*SU3F[I3, I4, k3]*SU3F[I5, k2, k3])) +
	SU3F[I1, I5, k1]*((-I/6)*SU3F[I3, I4, k1]*SUNDelta[6, I2] +
	(I/6)*SU3F[I2, I3, k1]*SUNDelta[6, I4]) + SU3F[I1, I4, k1]*
	((-I/6)*SU3F[I3, I5, k1]*SUNDelta[6, I2] + (I/6)*SU3F[I2, I3, k1]*
		SUNDelta[6, I5]) + SU3F[I1, I2, k1]*
	((-I/6)*SU3F[I3, I5, k1]*SUNDelta[6, I4] - (I/6)*SU3F[I3, I4, k1]*
		SUNDelta[6, I5]) + SU3D[I3, I5, k1]*
	(SU3F[6, I4, k2]*((SU3F[I1, k2, k3]*SU3F[I2, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I2, k2, k3])/2) + SU3F[6, I2, k2]*
		((SU3F[I1, k2, k3]*SU3F[I4, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I4, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I4, k2, k3])/6) +
	(5*SU3F[I1, I4, k1]*SUNDelta[6, I2])/18 +
	(5*SU3F[I1, I2, k1]*SUNDelta[6, I4])/18 -
	(SU3F[6, I4, k1]*SUNDelta[I1, I2])/6 -
	(SU3F[6, I2, k1]*SUNDelta[I1, I4])/6) + SU3D[I3, I4, k1]*
	(SU3F[6, I5, k2]*((SU3F[I1, k2, k3]*SU3F[I2, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I2, k2, k3])/2) + SU3F[6, I2, k2]*
		((SU3F[I1, k2, k3]*SU3F[I5, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I5, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I5, k2, k3])/6) +
	(5*SU3F[I1, I5, k1]*SUNDelta[6, I2])/18 +
	(5*SU3F[I1, I2, k1]*SUNDelta[6, I5])/18 -
	(SU3F[6, I5, k1]*SUNDelta[I1, I2])/6 -
	(SU3F[6, I2, k1]*SUNDelta[I1, I5])/6) + SU3D[I2, I3, k1]*
	(SU3F[6, I5, k2]*((SU3F[I1, k2, k3]*SU3F[I4, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I4, k2, k3])/2) + SU3F[6, I4, k2]*
		((SU3F[I1, k2, k3]*SU3F[I5, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I5, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/6) + ((2*I)/9)*SU3D[I4, I5, k1]*
		SUNDelta[6, I1] + ((5*I)/18)*SU3D[I1, I5, k1]*SUNDelta[6, I4] +
	(5*SU3F[I1, I5, k1]*SUNDelta[6, I4])/18 + ((5*I)/18)*SU3D[I1, I4, k1]*
		SUNDelta[6, I5] + (5*SU3F[I1, I4, k1]*SUNDelta[6, I5])/18 -
	(SU3F[6, I5, k1]*SUNDelta[I1, I4])/6 -
	(SU3F[6, I4, k1]*SUNDelta[I1, I5])/6) + SU3D[I4, I5, k1]*
	(SU3F[6, I3, k2]*(-(SU3F[I1, k2, k3]*SU3F[I2, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I2, k2, k3])/2) + SU3F[6, I2, k2]*
		((SU3F[I1, k2, k3]*SU3F[I3, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I3, k2, k3])/2) + SU3F[6, I1, k2]*
		((SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I3, k2, k3])/6) +
	(4*SU3F[I2, I3, k1]*SUNDelta[6, I1])/9 -
	(7*SU3F[I1, I2, k1]*SUNDelta[6, I3])/9 -
	(2*SU3F[6, I3, k1]*SUNDelta[I1, I2])/9 -
	(2*SU3F[6, I1, k1]*SUNDelta[I2, I3])/9) + SU3D[I2, I5, k1]*
	(SU3F[6, I4, k2]*((SU3F[I1, k2, k3]*SU3F[I3, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I3, k2, k3])/2) + SU3F[6, I3, k2]*
		(-(SU3F[I1, k2, k3]*SU3F[I4, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I4, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/6 +
		(SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/6) + ((2*I)/9)*SU3D[I3, I4, k1]*
		SUNDelta[6, I1] - (4*SU3F[I3, I4, k1]*SUNDelta[6, I1])/9 +
	(I/9)*SU3D[I1, I4, k1]*SUNDelta[6, I3] -
	(7*SU3F[I1, I4, k1]*SUNDelta[6, I3])/9 - ((8*I)/9)*SU3D[I1, I3, k1]*
		SUNDelta[6, I4] - (2*SU3F[6, I3, k1]*SUNDelta[I1, I4])/9 -
	(2*SU3F[6, I1, k1]*SUNDelta[I3, I4])/9) + SU3D[I1, I5, k1]*
	(-(SU3F[6, I4, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/4 -
	(SU3F[6, I2, k2]*SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/4 +
	SU3F[6, I3, k2]*(-(SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I4, k2, k3])/6) + ((5*I)/18)*SU3D[I3, I4, k1]*
		SUNDelta[6, I2] + (SU3F[I3, I4, k1]*SUNDelta[6, I2])/6 -
	(SU3F[I2, I3, k1]*SUNDelta[6, I4])/6 -
	(SU3F[6, I4, k1]*SUNDelta[I2, I3])/9 +
	(SU3F[6, I3, k1]*SUNDelta[I2, I4])/9 -
	(SU3F[6, I2, k1]*SUNDelta[I3, I4])/9) + SU3F[6, I5, k1]*
	((-I/3)*SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3] +
	(I/12)*SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3] -
	(I/12)*SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I4, k1, k3] -
	(I/3)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SU3F[I4, k2, k3] +
	SU3F[I2, k1, k3]*((-I/12)*SU3F[I1, I4, k2]*SU3F[I3, k2, k3] +
		(I/12)*SU3F[I1, I3, k2]*SU3F[I4, k2, k3]) + (I/6)*SU3F[I3, I4, k1]*
		SUNDelta[I1, I2] - (I/6)*SU3F[I2, I3, k1]*SUNDelta[I1, I4] +
	((5*I)/9)*SU3F[I1, I4, k1]*SUNDelta[I2, I3] - (I/9)*SU3F[I1, I3, k1]*
		SUNDelta[I2, I4] + ((5*I)/9)*SU3F[I1, I2, k1]*SUNDelta[I3, I4]) +
	SU3D[6, I5, k1]*((SU3D[I2, I4, k2]*SU3D[I3, k1, k3]*SU3F[I1, k2, k3])/
		2 + SU3D[I3, I4, k3]*(-(SU3D[I2, k2, k3]*SU3F[I1, k1, k2])/3 +
		SU3D[I1, k1, k2]*((-I/3)*SU3D[I2, k2, k3] - SU3F[I2, k2, k3]/3)) +
	SU3D[I3, I4, k2]*((I/2)*SU3F[I1, k2, k3]*SU3F[I2, k1, k3] -
		(I/3)*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]) -
	(SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/3 +
	SU3D[I4, k2, k3]*(-(SU3D[I2, I3, k2]*SU3F[I1, k1, k3])/3 -
		(I/12)*SU3F[I1, I3, k2]*SU3F[I2, k1, k3] + (I/3)*SU3F[I1, I2, k2]*
		SU3F[I3, k1, k3]) + SU3D[I4, k1, k3]*
		(-(SU3D[I2, I3, k2]*SU3F[I1, k2, k3])/2 +
		(SU3D[I1, I3, k2]*SU3F[I2, k2, k3])/4 -
		(SU3D[I1, I2, k2]*SU3F[I3, k2, k3])/4) + SU3D[I4, k1, k2]*
		((-I/12)*SU3F[I1, I3, k3]*SU3F[I2, k2, k3] + (I/12)*SU3F[I1, I2, k3]*
		SU3F[I3, k2, k3]) + SU3D[I2, I4, k2]*
		((-I/2)*SU3F[I1, k2, k3]*SU3F[I3, k1, k3] - (I/3)*SU3F[I1, k1, k3]*
		SU3F[I3, k2, k3]) + SU3D[I1, I4, k2]*
		(-(SU3D[I2, k1, k3]*SU3F[I3, k2, k3])/4 + (I/4)*SU3F[I2, k1, k3]*
		SU3F[I3, k2, k3]) + SU3D[I1, k2, k3]*
		((I/2)*SU3D[I2, k1, k2]*SU3D[I3, I4, k3] +
		(SU3D[I3, I4, k3]*SU3F[I2, k1, k2])/2 + SU3D[I2, I4, k3]*
		((-I/2)*SU3D[I3, k1, k2] - SU3F[I3, k1, k2]/2) +
		SU3D[I2, I3, k3]*((I/2)*SU3D[I4, k1, k2] + SU3F[I4, k1, k2]/2)) +
	(SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/12 +
	(I/4)*SU3D[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I4, k1, k3] -
	(SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/12 +
	SU3D[I3, k2, k3]*((I/4)*SU3D[I1, I2, k2]*SU3D[I4, k1, k3] -
		(SU3D[I4, k1, k2]*SU3F[I1, I2, k3])/12 -
		(SU3D[I2, I4, k2]*SU3F[I1, k1, k3])/3 + SU3D[I1, I4, k2]*
		((I/4)*SU3D[I2, k1, k3] + SU3F[I2, k1, k3]/4) +
		(I/12)*SU3F[I1, I4, k2]*SU3F[I2, k1, k3] +
		(SU3D[I1, I2, k2]*SU3F[I4, k1, k3])/4 + (I/12)*SU3F[I1, I2, k2]*
		SU3F[I4, k1, k3]) + SU3D[I2, k2, k3]*
		((-I/4)*SU3D[I1, I3, k2]*SU3D[I4, k1, k3] +
		(SU3D[I4, k1, k2]*SU3F[I1, I3, k3])/12 -
		(SU3D[I3, k1, k2]*SU3F[I1, I4, k3])/3 + (I/3)*SU3F[I1, I4, k2]*
		SU3F[I3, k1, k3] - (SU3D[I1, I3, k2]*SU3F[I4, k1, k3])/4 -
		(I/12)*SU3F[I1, I3, k2]*SU3F[I4, k1, k3]) +
	SU3D[I1, k1, k2]*(SU3D[I2, I4, k3]*((-I/3)*SU3D[I3, k2, k3] -
		SU3F[I3, k2, k3]/3) + SU3D[I2, I3, k3]*((-I/3)*SU3D[I4, k2, k3] -
		SU3F[I4, k2, k3]/3)) + SU3D[I1, I3, k2]*SU3D[I2, k1, k3]*
		((-I/4)*SU3D[I4, k2, k3] + SU3F[I4, k2, k3]/4) -
	(SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/3 +
	SU3D[I3, k1, k2]*(-(SU3D[I4, k2, k3]*SU3F[I1, I2, k3])/3 +
		(I/3)*SU3F[I1, I4, k3]*SU3F[I2, k2, k3] + (I/3)*SU3F[I1, I2, k3]*
		SU3F[I4, k2, k3]) + SU3F[I2, k1, k3]*
		(-(SU3F[I1, I4, k2]*SU3F[I3, k2, k3])/12 +
		(SU3F[I1, I3, k2]*SU3F[I4, k2, k3])/12) + SU3D[I2, k1, k2]*
		((SU3D[I4, k2, k3]*SU3F[I1, I3, k3])/12 -
		(SU3D[I3, k2, k3]*SU3F[I1, I4, k3])/12 +
		(SU3D[I3, I4, k3]*SU3F[I1, k2, k3])/2 + (I/12)*SU3F[I1, I4, k3]*
		SU3F[I3, k2, k3] - (I/12)*SU3F[I1, I3, k3]*SU3F[I4, k2, k3]) +
	SU3D[I2, I3, k2]*((I/2)*SU3F[I1, k2, k3]*SU3F[I4, k1, k3] -
		(I/3)*SU3F[I1, k1, k3]*SU3F[I4, k2, k3]) + SU3D[I1, I3, k2]*
		(-(SU3D[I4, k2, k3]*SU3F[I2, k1, k3])/4 - (I/4)*SU3F[I2, k2, k3]*
		SU3F[I4, k1, k3] - (I/4)*SU3F[I2, k1, k3]*SU3F[I4, k2, k3]) +
	(I/6)*SU3D[I3, I4, k1]*SUNDelta[I1, I2] +
	(SU3F[I3, I4, k1]*SUNDelta[I1, I2])/6 + (I/6)*SU3D[I2, I3, k1]*
		SUNDelta[I1, I4] - (SU3F[I2, I3, k1]*SUNDelta[I1, I4])/6 +
	(I/9)*SU3D[I1, I4, k1]*SUNDelta[I2, I3] +
	(5*SU3F[I1, I4, k1]*SUNDelta[I2, I3])/9 - ((5*I)/9)*SU3D[I1, I3, k1]*
		SUNDelta[I2, I4] - (SU3F[I1, I3, k1]*SUNDelta[I2, I4])/9 +
	(I/9)*SU3D[I1, I2, k1]*SUNDelta[I3, I4] +
	(5*SU3F[I1, I2, k1]*SUNDelta[I3, I4])/9) +
	SUNDelta[6, I5]*(((5*I)/27)*SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	((16*I)/27)*SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	((5*I)/27)*SUNDelta[I1, I2]*SUNDelta[I3, I4]) +
	SU3D[I2, I4, k1]*(SU3F[6, I5, k2]*((SU3F[I1, k2, k3]*SU3F[I3, k1, k3])/
		3 + (SU3F[I1, k1, k3]*SU3F[I3, k2, k3])/2) +
	SU3F[6, I3, k2]*(-(SU3F[I1, k2, k3]*SU3F[I5, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I5, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/6 +
		(SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/6) + ((2*I)/9)*SU3D[I3, I5, k1]*
		SUNDelta[6, I1] - (4*SU3F[I3, I5, k1]*SUNDelta[6, I1])/9 +
	(I/9)*SU3D[I1, I5, k1]*SUNDelta[6, I3] -
	(7*SU3F[I1, I5, k1]*SUNDelta[6, I3])/9 - ((8*I)/9)*SU3D[I1, I3, k1]*
		SUNDelta[6, I5] - (2*SU3F[6, I3, k1]*SUNDelta[I1, I5])/9 -
	(2*SU3F[6, I1, k1]*SUNDelta[I3, I5])/9) + SU3D[I1, I4, k1]*
	(-(SU3F[6, I5, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/4 -
	(SU3F[6, I2, k2]*SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/4 +
	SU3F[6, I3, k2]*(-(SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I5, k2, k3])/6) + ((5*I)/18)*SU3D[I3, I5, k1]*
		SUNDelta[6, I2] + (SU3F[I3, I5, k1]*SUNDelta[6, I2])/6 -
	(SU3F[I2, I3, k1]*SUNDelta[6, I5])/6 -
	(SU3F[6, I5, k1]*SUNDelta[I2, I3])/9 +
	(SU3F[6, I3, k1]*SUNDelta[I2, I5])/9 -
	(SU3F[6, I2, k1]*SUNDelta[I3, I5])/9) + SU3F[6, I4, k1]*
	((-I/3)*SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3] +
	(I/12)*SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*SU3F[I5, k1, k3] -
	(I/12)*SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I5, k1, k3] -
	(I/3)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SU3F[I5, k2, k3] +
	SU3F[I2, k1, k3]*((-I/12)*SU3F[I1, I5, k2]*SU3F[I3, k2, k3] +
		(I/12)*SU3F[I1, I3, k2]*SU3F[I5, k2, k3]) + (I/6)*SU3F[I3, I5, k1]*
		SUNDelta[I1, I2] - (I/6)*SU3F[I2, I3, k1]*SUNDelta[I1, I5] +
	((5*I)/9)*SU3F[I1, I5, k1]*SUNDelta[I2, I3] - (I/9)*SU3F[I1, I3, k1]*
		SUNDelta[I2, I5] + ((5*I)/9)*SU3F[I1, I2, k1]*SUNDelta[I3, I5]) +
	SU3D[6, I4, k1]*(-(SU3D[I2, I3, k2]*SU3D[I5, k1, k3]*SU3F[I1, k2, k3])/
		2 + SU3D[I3, I5, k2]*((I/2)*SU3F[I1, k2, k3]*SU3F[I2, k1, k3] -
		(I/3)*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]) -
	(SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/3 +
	SU3D[I5, k2, k3]*((-I/12)*SU3F[I1, I3, k2]*SU3F[I2, k1, k3] +
		(I/3)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]) + (I/4)*SU3D[I1, I5, k2]*
		SU3F[I2, k1, k3]*SU3F[I3, k2, k3] + SU3D[I5, k1, k2]*
		((-I/12)*SU3F[I1, I3, k3]*SU3F[I2, k2, k3] + (I/12)*SU3F[I1, I2, k3]*
		SU3F[I3, k2, k3]) + SU3D[I2, I5, k2]*
		((SU3D[I3, k1, k3]*SU3F[I1, k2, k3])/2 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I3, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]) +
	(SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/12 -
	(SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/12 +
	SU3D[I3, k2, k3]*((I/4)*SU3D[I1, I5, k2]*SU3D[I2, k1, k3] -
		(SU3D[I5, k1, k2]*SU3F[I1, I2, k3])/12 -
		(SU3D[I2, I5, k2]*SU3F[I1, k1, k3])/3 +
		(SU3D[I1, I5, k2]*SU3F[I2, k1, k3])/4 + (I/12)*SU3F[I1, I5, k2]*
		SU3F[I2, k1, k3] + SU3D[I1, I2, k2]*((I/4)*SU3D[I5, k1, k3] +
		SU3F[I5, k1, k3]/4) + (I/12)*SU3F[I1, I2, k2]*SU3F[I5, k1, k3]) +
	SU3D[I1, I2, k2]*(-(SU3D[I5, k1, k3]*SU3F[I3, k2, k3])/4 +
		(I/4)*SU3F[I3, k2, k3]*SU3F[I5, k1, k3]) + SU3D[I2, k1, k3]*
		(-(SU3D[I1, I5, k2]*SU3F[I3, k2, k3])/4 + SU3D[I1, I3, k2]*
		((-I/4)*SU3D[I5, k2, k3] + SU3F[I5, k2, k3]/4)) -
	(SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/3 +
	SU3D[I3, k1, k2]*(-(SU3D[I5, k2, k3]*SU3F[I1, I2, k3])/3 +
		(I/3)*SU3F[I1, I5, k3]*SU3F[I2, k2, k3] + (I/3)*SU3F[I1, I2, k3]*
		SU3F[I5, k2, k3]) + SU3F[I2, k1, k3]*
		(-(SU3F[I1, I5, k2]*SU3F[I3, k2, k3])/12 +
		(SU3F[I1, I3, k2]*SU3F[I5, k2, k3])/12) + SU3D[I2, I3, k2]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, k1, k3])/3 + (I/2)*SU3F[I1, k2, k3]*
		SU3F[I5, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I5, k2, k3]) +
	SU3D[I1, I3, k2]*(-(SU3D[I5, k2, k3]*SU3F[I2, k1, k3])/4 +
		(SU3D[I5, k1, k3]*SU3F[I2, k2, k3])/4 - (I/4)*SU3F[I2, k2, k3]*
		SU3F[I5, k1, k3] - (I/4)*SU3F[I2, k1, k3]*SU3F[I5, k2, k3]) +
	(I/6)*SU3D[I3, I5, k1]*SUNDelta[I1, I2] +
	(SU3F[I3, I5, k1]*SUNDelta[I1, I2])/6 + (I/6)*SU3D[I2, I3, k1]*
		SUNDelta[I1, I5] - (SU3F[I2, I3, k1]*SUNDelta[I1, I5])/6 +
	(I/9)*SU3D[I1, I5, k1]*SUNDelta[I2, I3] +
	(5*SU3F[I1, I5, k1]*SUNDelta[I2, I3])/9 - ((5*I)/9)*SU3D[I1, I3, k1]*
		SUNDelta[I2, I5] - (SU3F[I1, I3, k1]*SUNDelta[I2, I5])/9 +
	(I/9)*SU3D[I1, I2, k1]*SUNDelta[I3, I5] +
	(5*SU3F[I1, I2, k1]*SUNDelta[I3, I5])/9) +
	SUNDelta[6, I4]*(((5*I)/27)*SUNDelta[I1, I5]*SUNDelta[I2, I3] -
	((16*I)/27)*SUNDelta[I1, I3]*SUNDelta[I2, I5] +
	((5*I)/27)*SUNDelta[I1, I2]*SUNDelta[I3, I5]) +
	SU3D[I1, I3, k1]*(SU3F[6, I5, k2]*((SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/
		4 + (SU3F[I2, k1, k3]*SU3F[I4, k2, k3])/4) +
	SU3F[6, I4, k2]*((SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/4 +
		(SU3F[I2, k1, k3]*SU3F[I5, k2, k3])/4) + SU3F[6, I2, k2]*
		((SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/4 +
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/4) - ((8*I)/9)*SU3D[I4, I5, k1]*
		SUNDelta[6, I2] + (5*SU3F[6, I5, k1]*SUNDelta[I2, I4])/9 +
	(5*SU3F[6, I4, k1]*SUNDelta[I2, I5])/9 +
	(5*SU3F[6, I2, k1]*SUNDelta[I4, I5])/9) + SU3D[I1, I2, k1]*
	(-(SU3F[6, I5, k2]*SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/4 -
	(SU3F[6, I4, k2]*SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/4 +
	SU3F[6, I3, k2]*(-(SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/6) + (I/9)*SU3D[I4, I5, k1]*
		SUNDelta[6, I3] + ((5*I)/18)*SU3D[I3, I5, k1]*SUNDelta[6, I4] +
	(SU3F[I3, I5, k1]*SUNDelta[6, I4])/6 + ((5*I)/18)*SU3D[I3, I4, k1]*
		SUNDelta[6, I5] + (SU3F[I3, I4, k1]*SUNDelta[6, I5])/6 -
	(SU3F[6, I5, k1]*SUNDelta[I3, I4])/9 -
	(SU3F[6, I4, k1]*SUNDelta[I3, I5])/9 +
	(SU3F[6, I3, k1]*SUNDelta[I4, I5])/9) + SU3D[6, I3, k1]*
	(SU3D[I4, I5, k2]*((-I/2)*SU3F[I1, k2, k3]*SU3F[I2, k1, k3] +
		(I/3)*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]) -
	(SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/6 +
	SU3D[I5, k2, k3]*((I/6)*SU3F[I1, I4, k2]*SU3F[I2, k1, k3] +
		(I/6)*SU3F[I1, I2, k2]*SU3F[I4, k1, k3]) + SU3D[I5, k1, k2]*
		((I/6)*SU3F[I1, I4, k3]*SU3F[I2, k2, k3] + (I/6)*SU3F[I1, I2, k3]*
		SU3F[I4, k2, k3]) + SU3D[I2, I5, k2]*
		((SU3D[I4, k2, k3]*SU3F[I1, k1, k3])/3 +
		(SU3D[I4, k1, k3]*SU3F[I1, k2, k3])/2 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I4, k1, k3] + (I/3)*SU3F[I1, k1, k3]*SU3F[I4, k2, k3]) -
	(SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/6 +
	SU3D[I4, k2, k3]*(-(SU3D[I5, k1, k2]*SU3F[I1, I2, k3])/6 +
		(I/6)*SU3F[I1, I5, k2]*SU3F[I2, k1, k3] + (I/6)*SU3F[I1, I2, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I2, k2]*SU3D[I4, k1, k3]*
		((I/6)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/6) +
	SU3D[I4, k1, k2]*(-(SU3D[I5, k2, k3]*SU3F[I1, I2, k3])/6 +
		(I/6)*SU3F[I1, I5, k3]*SU3F[I2, k2, k3] + (I/6)*SU3F[I1, I2, k3]*
		SU3F[I5, k2, k3]) + SU3F[I2, k1, k3]*
		(-(SU3F[I1, I5, k2]*SU3F[I4, k2, k3])/6 -
		(SU3F[I1, I4, k2]*SU3F[I5, k2, k3])/6) + SU3D[I2, I4, k2]*
		((SU3D[I5, k2, k3]*SU3F[I1, k1, k3])/3 +
		(SU3D[I5, k1, k3]*SU3F[I1, k2, k3])/2 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I5, k1, k3] + (I/3)*SU3F[I1, k1, k3]*SU3F[I5, k2, k3]) +
	SU3F[I1, I2, k2]*(-(SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/6) + SU3D[I1, I2, k2]*
		((SU3D[I5, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3D[I5, k1, k3]*SU3F[I4, k2, k3])/6 + SU3D[I4, k2, k3]*
		((I/6)*SU3D[I5, k1, k3] + SU3F[I5, k1, k3]/6) +
		(I/6)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] + (I/6)*SU3F[I4, k1, k3]*
		SU3F[I5, k2, k3]) + ((2*I)/9)*SU3D[I4, I5, k1]*SUNDelta[I1, I2] +
	((2*I)/9)*SU3D[I2, I5, k1]*SUNDelta[I1, I4] +
	((2*I)/9)*SU3D[I2, I4, k1]*SUNDelta[I1, I5] - (I/9)*SU3D[I1, I5, k1]*
		SUNDelta[I2, I4] - (5*SU3F[I1, I5, k1]*SUNDelta[I2, I4])/9 -
	(I/9)*SU3D[I1, I4, k1]*SUNDelta[I2, I5] -
	(5*SU3F[I1, I4, k1]*SUNDelta[I2, I5])/9 - (I/9)*SU3D[I1, I2, k1]*
		SUNDelta[I4, I5] - (5*SU3F[I1, I2, k1]*SUNDelta[I4, I5])/9) +
	SU3F[6, I3, k1]*((-I/6)*SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*
		SU3F[I4, k1, k3] - (I/6)*SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*
		SU3F[I5, k1, k3] + SU3F[I2, k1, k3]*((-I/6)*SU3F[I1, I5, k2]*
		SU3F[I4, k2, k3] - (I/6)*SU3F[I1, I4, k2]*SU3F[I5, k2, k3]) +
	SU3F[I1, I2, k2]*((-I/6)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] -
		(I/6)*SU3F[I4, k1, k3]*SU3F[I5, k2, k3]) -
	((5*I)/9)*SU3F[I1, I5, k1]*SUNDelta[I2, I4] -
	((5*I)/9)*SU3F[I1, I4, k1]*SUNDelta[I2, I5] -
	((5*I)/9)*SU3F[I1, I2, k1]*SUNDelta[I4, I5]) +
	SU3D[6, I2, k1]*(-(SU3D[I3, I4, k2]*SU3D[I5, k1, k3]*SU3F[I1, k2, k3])/
		2 + SU3D[I5, k2, k3]*((I/3)*SU3F[I1, I4, k2]*SU3F[I3, k1, k3] -
		(I/12)*SU3F[I1, I3, k2]*SU3F[I4, k1, k3]) +
	SU3D[I5, k1, k2]*((I/12)*SU3F[I1, I4, k3]*SU3F[I3, k2, k3] -
		(I/12)*SU3F[I1, I3, k3]*SU3F[I4, k2, k3]) +
	SU3D[I3, I5, k2]*(-(SU3D[I4, k2, k3]*SU3F[I1, k1, k3])/3 +
		(I/2)*SU3F[I1, k2, k3]*SU3F[I4, k1, k3] - (I/3)*SU3F[I1, k1, k3]*
		SU3F[I4, k2, k3]) + SU3F[I1, I5, k2]*
		(-(SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/12 -
		(SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/3) + SU3D[I4, k2, k3]*
		((SU3D[I5, k1, k2]*SU3F[I1, I3, k3])/12 + (I/3)*SU3F[I1, I5, k2]*
		SU3F[I3, k1, k3] - (I/12)*SU3F[I1, I3, k2]*SU3F[I5, k1, k3]) +
	SU3D[I4, k1, k3]*(-(SU3D[I3, I5, k2]*SU3F[I1, k2, k3])/2 +
		SU3D[I1, I3, k2]*((-I/4)*SU3D[I5, k2, k3] + SU3F[I5, k2, k3]/4)) +
	SU3D[I4, k1, k2]*((SU3D[I5, k2, k3]*SU3F[I1, I3, k3])/12 +
		(I/12)*SU3F[I1, I5, k3]*SU3F[I3, k2, k3] - (I/12)*SU3F[I1, I3, k3]*
		SU3F[I5, k2, k3]) + SU3D[I3, I4, k2]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, k1, k3])/3 + (I/2)*SU3F[I1, k2, k3]*
		SU3F[I5, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I5, k2, k3]) +
	SU3F[I1, I4, k2]*(-(SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/12 -
		(SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/3) + SU3D[I1, I3, k2]*
		(-(SU3D[I5, k2, k3]*SU3F[I4, k1, k3])/4 +
		(SU3D[I5, k1, k3]*SU3F[I4, k2, k3])/4 + SU3D[I4, k2, k3]*
		((-I/4)*SU3D[I5, k1, k3] - SU3F[I5, k1, k3]/4) -
		(I/4)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] - (I/4)*SU3F[I4, k1, k3]*
		SU3F[I5, k2, k3]) + SU3F[I1, I3, k2]*
		((SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/12 +
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/12) + (I/6)*SU3D[I3, I5, k1]*
		SUNDelta[I1, I4] + (SU3F[I3, I5, k1]*SUNDelta[I1, I4])/6 +
	(I/6)*SU3D[I3, I4, k1]*SUNDelta[I1, I5] +
	(SU3F[I3, I4, k1]*SUNDelta[I1, I5])/6 + (I/9)*SU3D[I1, I5, k1]*
		SUNDelta[I3, I4] + (5*SU3F[I1, I5, k1]*SUNDelta[I3, I4])/9 +
	(I/9)*SU3D[I1, I4, k1]*SUNDelta[I3, I5] +
	(5*SU3F[I1, I4, k1]*SUNDelta[I3, I5])/9 - ((5*I)/9)*SU3D[I1, I3, k1]*
		SUNDelta[I4, I5] - (SU3F[I1, I3, k1]*SUNDelta[I4, I5])/9) +
	SU3F[6, I2, k1]*(SU3F[I1, I5, k2]*((-I/12)*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3] - (I/3)*SU3F[I3, k1, k3]*SU3F[I4, k2, k3]) +
	SU3F[I1, I4, k2]*((-I/12)*SU3F[I3, k2, k3]*SU3F[I5, k1, k3] -
		(I/3)*SU3F[I3, k1, k3]*SU3F[I5, k2, k3]) + SU3F[I1, I3, k2]*
		((I/12)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] + (I/12)*SU3F[I4, k1, k3]*
		SU3F[I5, k2, k3]) + (I/6)*SU3F[I3, I5, k1]*SUNDelta[I1, I4] +
	(I/6)*SU3F[I3, I4, k1]*SUNDelta[I1, I5] + ((5*I)/9)*SU3F[I1, I5, k1]*
		SUNDelta[I3, I4] + ((5*I)/9)*SU3F[I1, I4, k1]*SUNDelta[I3, I5] -
	(I/9)*SU3F[I1, I3, k1]*SUNDelta[I4, I5]) +
	SU3F[6, I1, k1]*((I/6)*SU3F[I2, I3, k2]*SU3F[I4, k2, k3]*
		SU3F[I5, k1, k3] + SU3F[I2, k2, k3]*((-I/6)*SU3F[I3, I5, k2]*
		SU3F[I4, k1, k3] - (I/6)*SU3F[I3, I4, k2]*SU3F[I5, k1, k3]) +
	(I/6)*SU3F[I2, I3, k2]*SU3F[I4, k1, k3]*SU3F[I5, k2, k3] +
	SU3F[I2, k1, k2]*((I/6)*SU3F[I3, I5, k3]*SU3F[I4, k2, k3] +
		(I/6)*SU3F[I3, I4, k3]*SU3F[I5, k2, k3]) -
	((2*I)/9)*SU3F[I3, I5, k1]*SUNDelta[I2, I4] -
	((2*I)/9)*SU3F[I3, I4, k1]*SUNDelta[I2, I5] +
	((2*I)/9)*SU3F[I2, I3, k1]*SUNDelta[I4, I5]) +
	SU3D[6, I1, k1]*(SU3D[I5, k2, k3]*((I/6)*SU3F[I2, k1, k3]*
		SU3F[I3, I4, k2] - (I/6)*SU3F[I2, I3, k2]*SU3F[I4, k1, k3]) +
	SU3D[I5, k1, k3]*(-(SU3D[I3, I4, k2]*SU3F[I2, k2, k3])/6 -
		(SU3D[I2, I3, k2]*SU3F[I4, k2, k3])/6) + SU3D[I5, k1, k2]*
		((I/6)*SU3F[I2, k2, k3]*SU3F[I3, I4, k3] - (I/6)*SU3F[I2, I3, k3]*
		SU3F[I4, k2, k3]) + SU3D[I3, I5, k2]*
		((SU3D[I4, k2, k3]*SU3F[I2, k1, k3])/6 + (I/6)*SU3F[I2, k2, k3]*
		SU3F[I4, k1, k3] + (I/6)*SU3F[I2, k1, k3]*SU3F[I4, k2, k3]) +
	SU3D[I2, I5, k2]*(SU3D[I4, k2, k3]*((I/6)*SU3D[I3, k1, k3] +
		SU3F[I3, k1, k3]/6) + (SU3D[I4, k1, k3]*SU3F[I3, k2, k3])/6 -
		(I/6)*SU3F[I3, k2, k3]*SU3F[I4, k1, k3] -
		(SU3D[I3, k1, k3]*SU3F[I4, k2, k3])/6 + (I/6)*SU3F[I3, k1, k3]*
		SU3F[I4, k2, k3]) + (SU3F[I2, I3, k2]*SU3F[I4, k2, k3]*
		SU3F[I5, k1, k3])/6 + SU3D[I4, k2, k3]*
		((I/6)*SU3D[I2, I3, k2]*SU3D[I5, k1, k3] +
		(SU3D[I5, k1, k2]*SU3F[I2, I3, k3])/6 + (I/6)*SU3F[I2, k1, k3]*
		SU3F[I3, I5, k2] + (SU3D[I2, I3, k2]*SU3F[I5, k1, k3])/6 -
		(I/6)*SU3F[I2, I3, k2]*SU3F[I5, k1, k3]) + SU3F[I2, k2, k3]*
		(-(SU3F[I3, I5, k2]*SU3F[I4, k1, k3])/6 -
		(SU3F[I3, I4, k2]*SU3F[I5, k1, k3])/6) + SU3D[I4, k1, k3]*
		(-(SU3D[I3, I5, k2]*SU3F[I2, k2, k3])/6 + SU3D[I2, I3, k2]*
		((I/6)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/6)) +
	SU3D[I2, I4, k2]*SU3D[I3, k1, k3]*((I/6)*SU3D[I5, k2, k3] -
		SU3F[I5, k2, k3]/6) + (SU3F[I2, I3, k2]*SU3F[I4, k1, k3]*
		SU3F[I5, k2, k3])/6 + SU3D[I4, k1, k2]*
		((SU3D[I5, k2, k3]*SU3F[I2, I3, k3])/6 + (I/6)*SU3F[I2, k2, k3]*
		SU3F[I3, I5, k3] - (I/6)*SU3F[I2, I3, k3]*SU3F[I5, k2, k3]) +
	SU3D[I3, I4, k2]*((SU3D[I5, k2, k3]*SU3F[I2, k1, k3])/6 +
		(I/6)*SU3F[I2, k2, k3]*SU3F[I5, k1, k3] + (I/6)*SU3F[I2, k1, k3]*
		SU3F[I5, k2, k3]) + SU3F[I2, k1, k2]*
		((SU3F[I3, I5, k3]*SU3F[I4, k2, k3])/6 +
		(SU3F[I3, I4, k3]*SU3F[I5, k2, k3])/6) + SU3D[I2, I4, k2]*
		((SU3D[I5, k2, k3]*SU3F[I3, k1, k3])/6 +
		(SU3D[I5, k1, k3]*SU3F[I3, k2, k3])/6 - (I/6)*SU3F[I3, k2, k3]*
		SU3F[I5, k1, k3] + (I/6)*SU3F[I3, k1, k3]*SU3F[I5, k2, k3]) +
	SU3D[I2, I3, k2]*((SU3D[I5, k2, k3]*SU3F[I4, k1, k3])/6 +
		(I/6)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] + (I/6)*SU3F[I4, k1, k3]*
		SU3F[I5, k2, k3]) + ((2*I)/9)*SU3D[I4, I5, k1]*SUNDelta[I2, I3] -
	(2*SU3F[I3, I5, k1]*SUNDelta[I2, I4])/9 -
	(2*SU3F[I3, I4, k1]*SUNDelta[I2, I5])/9 + ((2*I)/9)*SU3D[I2, I5, k1]*
		SUNDelta[I3, I4] + ((2*I)/9)*SU3D[I2, I4, k1]*SUNDelta[I3, I5] +
	(2*SU3F[I2, I3, k1]*SUNDelta[I4, I5])/9) +
	SUNDelta[6, I3]*(((2*I)/27)*SUNDelta[I1, I5]*SUNDelta[I2, I4] +
	((2*I)/27)*SUNDelta[I1, I4]*SUNDelta[I2, I5] +
	((2*I)/27)*SUNDelta[I1, I2]*SUNDelta[I4, I5]) +
	SUNDelta[6, I2]*(((5*I)/27)*SUNDelta[I1, I5]*SUNDelta[I3, I4] +
	((5*I)/27)*SUNDelta[I1, I4]*SUNDelta[I3, I5] -
	((16*I)/27)*SUNDelta[I1, I3]*SUNDelta[I4, I5]) +
	SUNDelta[6, I1]*(((4*I)/27)*SUNDelta[I2, I5]*SUNDelta[I3, I4] +
	((4*I)/27)*SUNDelta[I2, I4]*SUNDelta[I3, I5] +
	((4*I)/27)*SUNDelta[I2, I3]*SUNDelta[I4, I5])))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{(CouplingConstant[ChPTW3[2], 1]*(((-4*I)/9)*SU3D[6, I2, I5]*
	SU3D[I1, I3, I4] - ((4*I)/9)*SU3D[6, I2, I4]*SU3D[I1, I3, I5] -
	((4*I)/9)*SU3D[6, I2, I3]*SU3D[I1, I4, I5] - ((5*I)/9)*SU3D[6, I1, I5]*
	SU3D[I2, I3, I4] - ((5*I)/9)*SU3D[6, I1, I4]*SU3D[I2, I3, I5] -
	((5*I)/9)*SU3D[6, I1, I3]*SU3D[I2, I4, I5] +
	I*SU3D[6, I1, I2]*SU3D[I3, I4, I5] + (SU3D[I3, I4, I5]*SU3F[6, I1, I2])/
	3 - (7*SU3D[I2, I4, I5]*SU3F[6, I1, I3])/9 -
	(7*SU3D[I2, I3, I5]*SU3F[6, I1, I4])/9 -
	(7*SU3D[I2, I3, I4]*SU3F[6, I1, I5])/9 -
	(2*SU3D[I1, I4, I5]*SU3F[6, I2, I3])/9 -
	(2*SU3D[I1, I3, I5]*SU3F[6, I2, I4])/9 -
	(2*SU3D[I1, I3, I4]*SU3F[6, I2, I5])/9 + SU3D[6, I4, I5]*
	(((2*I)/3)*SU3D[I1, I2, I3] + (2*SU3F[I1, I2, I3])/9) +
	SU3D[6, I3, I5]*(((2*I)/3)*SU3D[I1, I2, I4] + (2*SU3F[I1, I2, I4])/9) +
	SU3D[6, I3, I4]*(((2*I)/3)*SU3D[I1, I2, I5] + (2*SU3F[I1, I2, I5])/9) +
	SU3D[I4, I5, k2]*(SU3D[6, I3, k1]*((-I/2)*SU3F[I1, k2, k3]*
		SU3F[I2, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]) +
	SU3D[6, I1, k1]*((-I/6)*SU3F[I2, k2, k3]*SU3F[I3, k1, k3] +
		(I/6)*SU3F[I2, k1, k3]*SU3F[I3, k2, k3])) +
	SU3D[I5, k2, k3]*(SU3D[I3, I4, k1]*((I/2)*SU3F[6, I2, k2]*
		SU3F[I1, k1, k3] + (I/6)*SU3F[6, I1, k2]*SU3F[I2, k1, k3]) +
	SU3D[I2, I4, k1]*((-I/2)*SU3F[6, I3, k2]*SU3F[I1, k1, k3] -
		(I/6)*SU3F[6, I1, k2]*SU3F[I3, k1, k3]) + SU3D[I1, I4, k1]*
		((-I/4)*SU3F[6, I3, k2]*SU3F[I2, k1, k3] - (I/6)*SU3F[6, I2, k2]*
		SU3F[I3, k1, k3]) + SU3D[I2, I3, k1]*
		((-I/2)*SU3F[6, I4, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I4, k1, k3]) + SU3D[I1, I3, k1]*
		((-I/4)*SU3F[6, I4, k2]*SU3F[I2, k1, k3] - (I/6)*SU3F[6, I2, k2]*
		SU3F[I4, k1, k3]) + SU3D[I1, I2, k1]*
		((I/4)*SU3F[6, I4, k2]*SU3F[I3, k1, k3] + (I/4)*SU3F[6, I3, k2]*
		SU3F[I4, k1, k3])) + SU3D[I5, k1, k2]*
	(SU3D[I3, I4, k1]*((-I/3)*SU3F[6, I2, k3]*SU3F[I1, k2, k3] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I2, k2, k3]) + SU3F[6, I4, k2]*
		(-(SU3F[I1, I3, k3]*SU3F[I2, k1, k3])/12 +
		(SU3F[I1, I2, k3]*SU3F[I3, k1, k3])/12) - (I/6)*SU3D[I1, I4, k1]*
		SU3F[6, I2, k3]*SU3F[I3, k2, k3] + SU3D[I2, I4, k1]*
		((I/3)*SU3F[6, I3, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I3, k2, k3]) + SU3F[6, I4, k3]*
		((SU3F[I1, I3, k1]*SU3F[I2, k2, k3])/3 -
		(SU3F[I1, I2, k1]*SU3F[I3, k2, k3])/12) + SU3F[6, I3, k2]*
		(-(SU3F[I1, I4, k3]*SU3F[I2, k1, k3])/12 +
		(SU3F[I1, I2, k3]*SU3F[I4, k1, k3])/12) + SU3F[6, I2, k2]*
		(-(SU3F[I1, I4, k3]*SU3F[I3, k1, k3])/6 -
		(SU3F[I1, I3, k3]*SU3F[I4, k1, k3])/6) + SU3F[6, I1, k2]*
		(-(SU3F[I2, I4, k3]*SU3F[I3, k1, k3])/6 -
		(SU3F[I2, I3, k3]*SU3F[I4, k1, k3])/6) - (I/6)*SU3D[I1, I3, k1]*
		SU3F[6, I2, k3]*SU3F[I4, k2, k3] + SU3D[I2, I3, k1]*
		((I/3)*SU3F[6, I4, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I4, k2, k3]) + SU3D[I1, I2, k1]*
		((I/4)*SU3F[6, I4, k3]*SU3F[I3, k2, k3] + (I/4)*SU3F[6, I3, k3]*
		SU3F[I4, k2, k3]) + SU3F[6, I3, k3]*
		((SU3F[I1, I4, k1]*SU3F[I2, k2, k3])/3 -
		(SU3F[I1, I2, k1]*SU3F[I4, k2, k3])/12) + SU3F[6, I2, k3]*
		((SU3F[I1, I4, k1]*SU3F[I3, k2, k3])/6 +
		(SU3F[I1, I3, k1]*SU3F[I4, k2, k3])/6) + SU3F[6, I1, k3]*
		((SU3F[I2, I4, k1]*SU3F[I3, k2, k3])/6 +
		(SU3F[I2, I3, k1]*SU3F[I4, k2, k3])/6)) +
	SU3D[I1, I5, k2]*(SU3D[6, I2, k1]*SU3D[I3, k2, k3]*
		((I/6)*SU3D[I4, k1, k3] + SU3F[I4, k1, k3]/6) +
	SU3D[6, I3, k1]*(-(SU3D[I4, k1, k3]*SU3F[I2, k2, k3])/4 +
		(I/4)*SU3F[I2, k2, k3]*SU3F[I4, k1, k3]) + SU3D[6, I2, k1]*
		((SU3D[I4, k2, k3]*SU3F[I3, k1, k3])/6 -
		(SU3D[I4, k1, k3]*SU3F[I3, k2, k3])/6 + (I/6)*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3] + (I/6)*SU3F[I3, k1, k3]*SU3F[I4, k2, k3])) +
	SU3D[I1, k2, k3]*((-I/2)*SU3D[6, I2, k1]*SU3D[I3, k1, k3]*
		SU3D[I4, I5, k2] + SU3D[I2, k1, k2]*((-I/2)*SU3D[6, I4, k1]*
		SU3D[I3, I5, k3] - (I/2)*SU3D[6, I3, k1]*SU3D[I4, I5, k3]) -
	(SU3D[6, I3, k1]*SU3D[I4, I5, k3]*SU3F[I2, k1, k2])/2 +
	SU3D[6, I2, k1]*((-I/2)*SU3D[I3, I5, k2]*SU3D[I4, k1, k3] -
		(I/2)*SU3D[I3, I4, k2]*SU3D[I5, k1, k3] -
		(SU3D[I4, I5, k3]*SU3F[I3, k1, k2])/2) + SU3D[6, I3, k1]*
		SU3D[I2, I5, k3]*((I/2)*SU3D[I4, k1, k2] + SU3F[I4, k1, k2]/2) -
	(SU3D[6, I2, k1]*SU3D[I3, I5, k3]*SU3F[I4, k1, k2])/2 +
	SU3D[6, I4, k1]*((I/2)*SU3D[I2, I5, k3]*SU3D[I3, k1, k2] -
		(SU3D[I3, I5, k3]*SU3F[I2, k1, k2])/2 +
		(SU3D[I2, I5, k3]*SU3F[I3, k1, k2])/2 + SU3D[I2, I3, k3]*
		((I/2)*SU3D[I5, k1, k2] + SU3F[I5, k1, k2]/2)) +
	SU3D[6, I3, k1]*SU3D[I2, I4, k3]*((I/2)*SU3D[I5, k1, k2] +
		SU3F[I5, k1, k2]/2) - (SU3D[6, I2, k1]*SU3D[I3, I4, k3]*
		SU3F[I5, k1, k2])/2) + SU3D[I4, k2, k3]*
	(SU3D[I5, k1, k3]*(-(SU3D[I2, I3, k1]*SU3F[6, I1, k2])/6 -
		(SU3D[I1, I3, k1]*SU3F[6, I2, k2])/6 +
		(SU3D[I1, I2, k1]*SU3F[6, I3, k2])/4) + SU3D[I3, I5, k1]*
		((I/2)*SU3F[6, I2, k2]*SU3F[I1, k1, k3] + (I/6)*SU3F[6, I1, k2]*
		SU3F[I2, k1, k3]) + SU3D[I2, I5, k1]*
		((-I/2)*SU3F[6, I3, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I3, k1, k3]) + SU3D[I1, I5, k1]*
		((-I/4)*SU3F[6, I3, k2]*SU3F[I2, k1, k3] - (I/6)*SU3F[6, I2, k2]*
		SU3F[I3, k1, k3]) + SU3D[I2, I3, k1]*
		((-I/2)*SU3F[6, I5, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I3, k1]*
		((-I/4)*SU3F[6, I5, k2]*SU3F[I2, k1, k3] - (I/6)*SU3F[6, I2, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I2, k1]*
		((I/4)*SU3F[6, I5, k2]*SU3F[I3, k1, k3] + (I/4)*SU3F[6, I3, k2]*
		SU3F[I5, k1, k3])) + SU3D[I2, k2, k3]*
	((-I/6)*SU3D[6, I1, k1]*SU3D[I3, k1, k2]*SU3D[I4, I5, k3] -
	(SU3D[6, I1, k1]*SU3D[I4, I5, k3]*SU3F[I3, k1, k2])/6 +
	SU3D[6, I1, k1]*SU3D[I3, I5, k3]*((-I/6)*SU3D[I4, k1, k2] -
		SU3F[I4, k1, k2]/6) + SU3D[6, I3, k1]*SU3D[I1, I5, k2]*
		((I/4)*SU3D[I4, k1, k3] + SU3F[I4, k1, k3]/4) +
	SU3D[6, I3, k1]*SU3D[I1, I4, k2]*((I/4)*SU3D[I5, k1, k3] +
		SU3F[I5, k1, k3]/4) + SU3D[6, I4, k1]*
		((I/4)*SU3D[I1, I5, k2]*SU3D[I3, k1, k3] -
		(SU3D[I5, k1, k2]*SU3F[I1, I3, k3])/12 -
		(SU3D[I3, k1, k2]*SU3F[I1, I5, k3])/12 -
		(SU3D[I3, I5, k3]*SU3F[I1, k1, k2])/3 +
		(SU3D[I1, I5, k2]*SU3F[I3, k1, k3])/4 + (I/12)*SU3F[I1, I5, k2]*
		SU3F[I3, k1, k3] + SU3D[I1, I3, k2]*((I/4)*SU3D[I5, k1, k3] +
		SU3F[I5, k1, k3]/4) + (I/12)*SU3F[I1, I3, k2]*SU3F[I5, k1, k3]) +
	SU3D[6, I3, k1]*(-(SU3D[I5, k1, k2]*SU3F[I1, I4, k3])/12 -
		(SU3D[I4, k1, k2]*SU3F[I1, I5, k3])/12 -
		(SU3D[I4, I5, k3]*SU3F[I1, k1, k2])/3 + (I/12)*SU3F[I1, I5, k2]*
		SU3F[I4, k1, k3] + (I/12)*SU3F[I1, I4, k2]*SU3F[I5, k1, k3])) +
	SU3D[I3, k2, k3]*(SU3D[I5, k1, k3]*(-(SU3D[I2, I4, k1]*SU3F[6, I1, k2])/
		6 - (SU3D[I1, I4, k1]*SU3F[6, I2, k2])/6 +
		(SU3D[I1, I2, k1]*SU3F[6, I4, k2])/4) + SU3D[I4, k1, k3]*
		(-(SU3D[I2, I5, k1]*SU3F[6, I1, k2])/6 -
		(SU3D[I1, I5, k1]*SU3F[6, I2, k2])/6 +
		(SU3D[I1, I2, k1]*SU3F[6, I5, k2])/4) +
	(SU3D[6, I1, k1]*SU3D[I4, I5, k3]*SU3F[I2, k1, k2])/6 +
	SU3D[I2, I5, k1]*((-I/2)*SU3F[6, I4, k2]*SU3F[I1, k1, k3] -
		(I/6)*SU3F[6, I1, k2]*SU3F[I4, k1, k3]) + SU3D[I1, I5, k1]*
		((-I/4)*SU3F[6, I4, k2]*SU3F[I2, k1, k3] - (I/6)*SU3F[6, I2, k2]*
		SU3F[I4, k1, k3]) + SU3D[I2, I4, k1]*
		((-I/2)*SU3F[6, I5, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I4, k1]*
		((-I/4)*SU3F[6, I5, k2]*SU3F[I2, k1, k3] - (I/6)*SU3F[6, I2, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I2, k1]*
		((I/4)*SU3F[6, I5, k2]*SU3F[I4, k1, k3] + (I/4)*SU3F[6, I4, k2]*
		SU3F[I5, k1, k3]) + SU3D[6, I2, k1]*
		(-(SU3D[I5, k1, k2]*SU3F[I1, I4, k3])/6 -
		(SU3D[I4, k1, k2]*SU3F[I1, I5, k3])/6 +
		(SU3D[I4, I5, k3]*SU3F[I1, k1, k2])/3 + (I/6)*SU3F[I1, I5, k2]*
		SU3F[I4, k1, k3] + (I/6)*SU3F[I1, I4, k2]*SU3F[I5, k1, k3]) +
	SU3D[6, I1, k1]*((I/6)*SU3D[I2, I5, k2]*SU3D[I4, k1, k3] +
		(I/6)*SU3D[I2, I4, k2]*SU3D[I5, k1, k3] -
		(SU3D[I5, k1, k2]*SU3F[I2, I4, k3])/6 -
		(SU3D[I4, k1, k2]*SU3F[I2, I5, k3])/6 +
		(SU3D[I2, I5, k2]*SU3F[I4, k1, k3])/6 + (I/6)*SU3F[I2, I5, k2]*
		SU3F[I4, k1, k3] + (SU3D[I2, I4, k2]*SU3F[I5, k1, k3])/6 +
		(I/6)*SU3F[I2, I4, k2]*SU3F[I5, k1, k3])) +
	SU3D[I3, k1, k3]*(SU3D[6, I2, k1]*SU3D[I1, I5, k2]*
		((I/6)*SU3D[I4, k2, k3] - SU3F[I4, k2, k3]/6) +
	SU3D[6, I1, k1]*(SU3D[I2, I5, k2]*((I/6)*SU3D[I4, k2, k3] -
		SU3F[I4, k2, k3]/6) + SU3D[I2, I4, k2]*((I/6)*SU3D[I5, k2, k3] -
		SU3F[I5, k2, k3]/6))) + SU3D[I3, I4, k3]*
	(SU3D[6, I1, k1]*SU3D[I2, k2, k3]*((-I/6)*SU3D[I5, k1, k2] -
		SU3F[I5, k1, k2]/6) + SU3D[I1, k1, k2]*
		(-(SU3D[I5, k2, k3]*SU3F[6, I2, k1])/3 +
		(SU3D[I2, k2, k3]*SU3F[6, I5, k1])/3 - (I/3)*SU3F[6, I5, k1]*
		SU3F[I2, k2, k3] + SU3D[6, I2, k1]*((I/3)*SU3D[I5, k2, k3] +
		SU3F[I5, k2, k3]/3) + (I/3)*SU3F[6, I2, k1]*SU3F[I5, k2, k3])) +
	SU3D[I1, k1, k2]*(SU3D[I3, k2, k3]*((I/3)*SU3D[6, I2, k1]*
		SU3D[I4, I5, k3] - (SU3D[I4, I5, k3]*SU3F[6, I2, k1])/3) +
	(SU3D[I2, k1, k3]*SU3D[I4, I5, k2]*SU3F[6, I3, k3])/2 +
	SU3D[I2, k2, k3]*((-I/3)*SU3D[6, I4, k1]*SU3D[I3, I5, k3] -
		(I/3)*SU3D[6, I3, k1]*SU3D[I4, I5, k3] +
		(SU3D[I4, I5, k3]*SU3F[6, I3, k1])/3 +
		(SU3D[I3, I5, k3]*SU3F[6, I4, k1])/3) +
	(SU3D[I2, k1, k3]*SU3D[I3, I5, k2]*SU3F[6, I4, k3])/2 +
	SU3D[I5, k1, k3]*((SU3D[I3, I4, k2]*SU3F[6, I2, k3])/2 -
		(SU3D[I2, I4, k2]*SU3F[6, I3, k3])/2 -
		(SU3D[I2, I3, k2]*SU3F[6, I4, k3])/2) +
	(SU3D[I2, k1, k3]*SU3D[I3, I4, k2]*SU3F[6, I5, k3])/2 +
	SU3D[I4, k1, k3]*((SU3D[I3, I5, k2]*SU3F[6, I2, k3])/2 -
		(SU3D[I2, I5, k2]*SU3F[6, I3, k3])/2 -
		(SU3D[I2, I3, k2]*SU3F[6, I5, k3])/2) + SU3D[I3, k1, k3]*
		((SU3D[I4, I5, k2]*SU3F[6, I2, k3])/2 -
		(SU3D[I2, I5, k2]*SU3F[6, I4, k3])/2 -
		(SU3D[I2, I4, k2]*SU3F[6, I5, k3])/2) -
	(SU3D[6, I3, k1]*SU3D[I4, I5, k3]*SU3F[I2, k2, k3])/3 +
	(SU3D[6, I2, k1]*SU3D[I4, I5, k3]*SU3F[I3, k2, k3])/3 +
	SU3D[I4, I5, k3]*((-I/3)*SU3F[6, I3, k1]*SU3F[I2, k2, k3] +
		(I/3)*SU3F[6, I2, k1]*SU3F[I3, k2, k3]) + SU3D[I4, I5, k1]*
		((I/2)*SU3F[6, I3, k3]*SU3F[I2, k2, k3] + (I/2)*SU3F[6, I2, k3]*
		SU3F[I3, k2, k3]) + SU3D[I3, I5, k3]*
		(-(SU3D[I4, k2, k3]*SU3F[6, I2, k1])/3 - (I/3)*SU3F[6, I4, k1]*
		SU3F[I2, k2, k3] + SU3D[6, I2, k1]*((I/3)*SU3D[I4, k2, k3] +
		SU3F[I4, k2, k3]/3) + (I/3)*SU3F[6, I2, k1]*SU3F[I4, k2, k3]) +
	SU3D[I3, I5, k1]*((I/2)*SU3F[6, I4, k3]*SU3F[I2, k2, k3] +
		(I/2)*SU3F[6, I2, k3]*SU3F[I4, k2, k3]) + SU3D[I2, I5, k3]*
		((SU3D[I4, k2, k3]*SU3F[6, I3, k1])/3 +
		(SU3D[I3, k2, k3]*SU3F[6, I4, k1])/3 - (I/3)*SU3F[6, I4, k1]*
		SU3F[I3, k2, k3] + SU3D[6, I3, k1]*((-I/3)*SU3D[I4, k2, k3] -
		SU3F[I4, k2, k3]/3) - (I/3)*SU3F[6, I3, k1]*SU3F[I4, k2, k3]) +
	SU3D[I2, I5, k1]*((-I/2)*SU3F[6, I4, k3]*SU3F[I3, k2, k3] -
		(I/2)*SU3F[6, I3, k3]*SU3F[I4, k2, k3]) + SU3D[6, I4, k1]*
		(-(SU3D[I3, I5, k3]*SU3F[I2, k2, k3])/3 + SU3D[I2, I5, k3]*
		((-I/3)*SU3D[I3, k2, k3] - SU3F[I3, k2, k3]/3) +
		SU3D[I2, I3, k3]*((-I/3)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/3)) +
	SU3D[I3, I4, k1]*((I/2)*SU3F[6, I5, k3]*SU3F[I2, k2, k3] +
		(I/2)*SU3F[6, I2, k3]*SU3F[I5, k2, k3]) + SU3D[I2, I4, k3]*
		((SU3D[I5, k2, k3]*SU3F[6, I3, k1])/3 +
		(SU3D[I3, k2, k3]*SU3F[6, I5, k1])/3 - (I/3)*SU3F[6, I5, k1]*
		SU3F[I3, k2, k3] + SU3D[6, I3, k1]*((-I/3)*SU3D[I5, k2, k3] -
		SU3F[I5, k2, k3]/3) - (I/3)*SU3F[6, I3, k1]*SU3F[I5, k2, k3]) +
	SU3D[I2, I4, k1]*((-I/2)*SU3F[6, I5, k3]*SU3F[I3, k2, k3] -
		(I/2)*SU3F[6, I3, k3]*SU3F[I5, k2, k3]) + SU3D[I2, I3, k3]*
		((SU3D[I5, k2, k3]*SU3F[6, I4, k1])/3 +
		(SU3D[I4, k2, k3]*SU3F[6, I5, k1])/3 - (I/3)*SU3F[6, I5, k1]*
		SU3F[I4, k2, k3] - (I/3)*SU3F[6, I4, k1]*SU3F[I5, k2, k3]) +
	SU3D[I2, I3, k1]*((-I/2)*SU3F[6, I5, k3]*SU3F[I4, k2, k3] -
		(I/2)*SU3F[6, I4, k3]*SU3F[I5, k2, k3])) +
	SU3D[I2, k1, k2]*(SU3D[I5, k2, k3]*(-(SU3D[I1, I4, k1]*SU3F[6, I3, k3])/
		4 - (SU3D[I1, I3, k1]*SU3F[6, I4, k3])/4 - (I/12)*SU3F[6, I4, k3]*
		SU3F[I1, I3, k1] - (I/12)*SU3F[6, I3, k3]*SU3F[I1, I4, k1]) +
	SU3D[I5, k1, k3]*((SU3D[I3, I4, k2]*SU3F[6, I1, k3])/6 -
		(I/3)*SU3F[6, I4, k2]*SU3F[I1, I3, k3] - (I/3)*SU3F[6, I3, k2]*
		SU3F[I1, I4, k3]) + SU3D[I4, k2, k3]*
		(-(SU3D[I1, I5, k1]*SU3F[6, I3, k3])/4 -
		(SU3D[I1, I3, k1]*SU3F[6, I5, k3])/4 - (I/12)*SU3F[6, I5, k3]*
		SU3F[I1, I3, k1] - (I/12)*SU3F[6, I3, k3]*SU3F[I1, I5, k1]) +
	SU3D[I3, k2, k3]*(SU3D[I4, I5, k3]*((I/6)*SU3D[6, I1, k1] -
		SU3F[6, I1, k1]/6) - (SU3D[I1, I5, k1]*SU3F[6, I4, k3])/4 -
		(SU3D[I1, I4, k1]*SU3F[6, I5, k3])/4 - (I/12)*SU3F[6, I5, k3]*
		SU3F[I1, I4, k1] - (I/12)*SU3F[6, I4, k3]*SU3F[I1, I5, k1]) +
	SU3D[I4, k1, k3]*((SU3D[I3, I5, k2]*SU3F[6, I1, k3])/6 -
		(I/3)*SU3F[6, I5, k2]*SU3F[I1, I3, k3] - (I/3)*SU3F[6, I3, k2]*
		SU3F[I1, I5, k3]) + SU3D[I3, k1, k3]*
		((SU3D[I4, I5, k2]*SU3F[6, I1, k3])/6 - (I/3)*SU3F[6, I5, k2]*
		SU3F[I1, I4, k3] - (I/3)*SU3F[6, I4, k2]*SU3F[I1, I5, k3]) +
	SU3D[I4, I5, k3]*((-I/2)*SU3F[6, I3, k1]*SU3F[I1, k2, k3] +
		(SU3D[6, I1, k1]*SU3F[I3, k2, k3])/6 + (I/6)*SU3F[6, I1, k1]*
		SU3F[I3, k2, k3]) + SU3D[I4, I5, k1]*
		((I/3)*SU3F[6, I3, k3]*SU3F[I1, k2, k3] + (I/6)*SU3F[6, I1, k3]*
		SU3F[I3, k2, k3]) + SU3F[6, I5, k2]*
		(-(SU3F[I1, I4, k3]*SU3F[I3, k1, k3])/3 -
		(SU3F[I1, I3, k3]*SU3F[I4, k1, k3])/3) + SU3D[I3, I5, k3]*
		(-(SU3D[I4, k2, k3]*SU3F[6, I1, k1])/6 - (I/2)*SU3F[6, I4, k1]*
		SU3F[I1, k2, k3] + SU3D[6, I1, k1]*((I/6)*SU3D[I4, k2, k3] +
		SU3F[I4, k2, k3]/6) + (I/6)*SU3F[6, I1, k1]*SU3F[I4, k2, k3]) +
	SU3D[I3, I5, k1]*((I/3)*SU3F[6, I4, k3]*SU3F[I1, k2, k3] +
		(I/6)*SU3F[6, I1, k3]*SU3F[I4, k2, k3]) + SU3D[I1, I5, k1]*
		((-I/4)*SU3F[6, I4, k3]*SU3F[I3, k2, k3] - (I/4)*SU3F[6, I3, k3]*
		SU3F[I4, k2, k3]) + SU3F[6, I5, k3]*
		((SU3F[I1, I4, k1]*SU3F[I3, k2, k3])/12 +
		(SU3F[I1, I3, k1]*SU3F[I4, k2, k3])/12) + SU3F[6, I4, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I3, k1, k3])/3 -
		(SU3F[I1, I3, k3]*SU3F[I5, k1, k3])/3) + SU3F[6, I3, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I4, k1, k3])/3 -
		(SU3F[I1, I4, k3]*SU3F[I5, k1, k3])/3) + SU3D[I3, I4, k3]*
		(-(SU3D[I5, k2, k3]*SU3F[6, I1, k1])/6 - (I/2)*SU3F[6, I5, k1]*
		SU3F[I1, k2, k3] + SU3D[6, I1, k1]*((I/6)*SU3D[I5, k2, k3] +
		SU3F[I5, k2, k3]/6) + (I/6)*SU3F[6, I1, k1]*SU3F[I5, k2, k3]) +
	SU3D[I3, I4, k1]*((I/3)*SU3F[6, I5, k3]*SU3F[I1, k2, k3] +
		(I/6)*SU3F[6, I1, k3]*SU3F[I5, k2, k3]) + SU3D[I1, I4, k1]*
		((-I/4)*SU3F[6, I5, k3]*SU3F[I3, k2, k3] - (I/4)*SU3F[6, I3, k3]*
		SU3F[I5, k2, k3]) + SU3D[I1, I3, k1]*
		((-I/4)*SU3F[6, I5, k3]*SU3F[I4, k2, k3] - (I/4)*SU3F[6, I4, k3]*
		SU3F[I5, k2, k3]) + SU3F[6, I4, k3]*
		((SU3F[I1, I5, k1]*SU3F[I3, k2, k3])/12 +
		(SU3F[I1, I3, k1]*SU3F[I5, k2, k3])/12) + SU3D[6, I4, k1]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, I3, k3])/3 -
		(SU3D[I3, k2, k3]*SU3F[I1, I5, k3])/3 -
		(SU3D[I3, I5, k3]*SU3F[I1, k2, k3])/2 + (I/3)*SU3F[I1, I5, k3]*
		SU3F[I3, k2, k3] + (I/3)*SU3F[I1, I3, k3]*SU3F[I5, k2, k3]) +
	SU3F[6, I3, k3]*((SU3F[I1, I5, k1]*SU3F[I4, k2, k3])/12 +
		(SU3F[I1, I4, k1]*SU3F[I5, k2, k3])/12) + SU3D[6, I3, k1]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, I4, k3])/3 -
		(SU3D[I4, k2, k3]*SU3F[I1, I5, k3])/3 -
		(SU3D[I4, I5, k3]*SU3F[I1, k2, k3])/2 + (I/3)*SU3F[I1, I5, k3]*
		SU3F[I4, k2, k3] + (I/3)*SU3F[I1, I4, k3]*SU3F[I5, k2, k3])) +
	SU3D[I4, k1, k2]*(SU3D[I5, k2, k3]*(-(SU3D[I2, I3, k1]*SU3F[6, I1, k3])/
		6 - (SU3D[I1, I3, k1]*SU3F[6, I2, k3])/6 +
		(SU3D[I1, I2, k1]*SU3F[6, I3, k3])/4 + (I/12)*SU3F[6, I3, k3]*
		SU3F[I1, I2, k1] - (I/6)*SU3F[6, I2, k3]*SU3F[I1, I3, k1] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I2, I3, k1]) + SU3D[I5, k1, k3]*
		((I/12)*SU3F[6, I3, k2]*SU3F[I1, I2, k3] - (I/6)*SU3F[6, I2, k2]*
		SU3F[I1, I3, k3] - (I/6)*SU3F[6, I1, k2]*SU3F[I2, I3, k3]) +
	SU3D[I3, I5, k1]*((-I/3)*SU3F[6, I2, k3]*SU3F[I1, k2, k3] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I2, k2, k3]) + SU3F[6, I5, k2]*
		(-(SU3F[I1, I3, k3]*SU3F[I2, k1, k3])/12 +
		(SU3F[I1, I2, k3]*SU3F[I3, k1, k3])/12) - (I/6)*SU3D[I1, I5, k1]*
		SU3F[6, I2, k3]*SU3F[I3, k2, k3] + SU3D[I2, I5, k1]*
		((I/3)*SU3F[6, I3, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I3, k2, k3]) + SU3F[6, I5, k3]*
		((SU3F[I1, I3, k1]*SU3F[I2, k2, k3])/3 -
		(SU3F[I1, I2, k1]*SU3F[I3, k2, k3])/12) + SU3F[6, I3, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I2, k1, k3])/12 +
		(SU3F[I1, I2, k3]*SU3F[I5, k1, k3])/12) + SU3F[6, I2, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I3, k1, k3])/6 -
		(SU3F[I1, I3, k3]*SU3F[I5, k1, k3])/6) + SU3F[6, I1, k2]*
		(-(SU3F[I2, I5, k3]*SU3F[I3, k1, k3])/6 -
		(SU3F[I2, I3, k3]*SU3F[I5, k1, k3])/6) - (I/6)*SU3D[I1, I3, k1]*
		SU3F[6, I2, k3]*SU3F[I5, k2, k3] + SU3D[I2, I3, k1]*
		((I/3)*SU3F[6, I5, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I5, k2, k3]) + SU3D[I1, I2, k1]*
		((I/4)*SU3F[6, I5, k3]*SU3F[I3, k2, k3] + (I/4)*SU3F[6, I3, k3]*
		SU3F[I5, k2, k3]) + SU3F[6, I3, k3]*
		((SU3F[I1, I5, k1]*SU3F[I2, k2, k3])/3 -
		(SU3F[I1, I2, k1]*SU3F[I5, k2, k3])/12) + SU3F[6, I2, k3]*
		((SU3F[I1, I5, k1]*SU3F[I3, k2, k3])/6 +
		(SU3F[I1, I3, k1]*SU3F[I5, k2, k3])/6) + SU3F[6, I1, k3]*
		((SU3F[I2, I5, k1]*SU3F[I3, k2, k3])/6 +
		(SU3F[I2, I3, k1]*SU3F[I5, k2, k3])/6)) +
	SU3D[I3, k1, k2]*(SU3D[I5, k2, k3]*(-(SU3D[I2, I4, k1]*SU3F[6, I1, k3])/
		6 - (SU3D[I1, I4, k1]*SU3F[6, I2, k3])/6 +
		(SU3D[I1, I2, k1]*SU3F[6, I4, k3])/4 + (I/12)*SU3F[6, I4, k3]*
		SU3F[I1, I2, k1] - (I/6)*SU3F[6, I2, k3]*SU3F[I1, I4, k1] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I2, I4, k1]) + SU3D[I5, k1, k3]*
		((I/12)*SU3F[6, I4, k2]*SU3F[I1, I2, k3] - (I/6)*SU3F[6, I2, k2]*
		SU3F[I1, I4, k3] - (I/6)*SU3F[6, I1, k2]*SU3F[I2, I4, k3]) +
	SU3D[I4, k2, k3]*(-(SU3D[I2, I5, k1]*SU3F[6, I1, k3])/6 -
		(SU3D[I1, I5, k1]*SU3F[6, I2, k3])/6 +
		(SU3D[I1, I2, k1]*SU3F[6, I5, k3])/4 + (I/12)*SU3F[6, I5, k3]*
		SU3F[I1, I2, k1] - (I/6)*SU3F[6, I2, k3]*SU3F[I1, I5, k1] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I2, I5, k1]) + SU3D[I4, k1, k3]*
		((I/12)*SU3F[6, I5, k2]*SU3F[I1, I2, k3] - (I/6)*SU3F[6, I2, k2]*
		SU3F[I1, I5, k3] - (I/6)*SU3F[6, I1, k2]*SU3F[I2, I5, k3]) +
	SU3D[I4, I5, k3]*((-I/2)*SU3F[6, I2, k1]*SU3F[I1, k2, k3] -
		(SU3D[6, I1, k1]*SU3F[I2, k2, k3])/6 - (I/6)*SU3F[6, I1, k1]*
		SU3F[I2, k2, k3]) + SU3D[I4, I5, k1]*
		((-I/3)*SU3F[6, I2, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I2, k2, k3]) + SU3F[6, I5, k2]*
		(-(SU3F[I1, I4, k3]*SU3F[I2, k1, k3])/12 +
		(SU3F[I1, I2, k3]*SU3F[I4, k1, k3])/12) - (I/6)*SU3D[I1, I5, k1]*
		SU3F[6, I2, k3]*SU3F[I4, k2, k3] + SU3D[I2, I5, k1]*
		((I/3)*SU3F[6, I4, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I4, k2, k3]) + SU3F[6, I5, k3]*
		((SU3F[I1, I4, k1]*SU3F[I2, k2, k3])/3 -
		(SU3F[I1, I2, k1]*SU3F[I4, k2, k3])/12) + SU3F[6, I4, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I2, k1, k3])/12 +
		(SU3F[I1, I2, k3]*SU3F[I5, k1, k3])/12) + SU3F[6, I2, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I1, I4, k3]*SU3F[I5, k1, k3])/6) + SU3F[6, I1, k2]*
		(-(SU3F[I2, I5, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I2, I4, k3]*SU3F[I5, k1, k3])/6) - (I/6)*SU3D[I1, I4, k1]*
		SU3F[6, I2, k3]*SU3F[I5, k2, k3] + SU3D[I2, I4, k1]*
		((I/3)*SU3F[6, I5, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I5, k2, k3]) + SU3D[I1, I2, k1]*
		((I/4)*SU3F[6, I5, k3]*SU3F[I4, k2, k3] + (I/4)*SU3F[6, I4, k3]*
		SU3F[I5, k2, k3]) + SU3F[6, I4, k3]*
		((SU3F[I1, I5, k1]*SU3F[I2, k2, k3])/3 -
		(SU3F[I1, I2, k1]*SU3F[I5, k2, k3])/12) + SU3F[6, I2, k3]*
		((SU3F[I1, I5, k1]*SU3F[I4, k2, k3])/6 +
		(SU3F[I1, I4, k1]*SU3F[I5, k2, k3])/6) + SU3D[6, I2, k1]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, I4, k3])/6 -
		(SU3D[I4, k2, k3]*SU3F[I1, I5, k3])/6 -
		(SU3D[I4, I5, k3]*SU3F[I1, k2, k3])/2 + (I/6)*SU3F[I1, I5, k3]*
		SU3F[I4, k2, k3] + (I/6)*SU3F[I1, I4, k3]*SU3F[I5, k2, k3]) +
	SU3F[6, I1, k3]*((SU3F[I2, I5, k1]*SU3F[I4, k2, k3])/6 +
		(SU3F[I2, I4, k1]*SU3F[I5, k2, k3])/6) + SU3D[6, I1, k1]*
		(-(SU3D[I5, k2, k3]*SU3F[I2, I4, k3])/6 -
		(SU3D[I4, k2, k3]*SU3F[I2, I5, k3])/6 + (I/6)*SU3F[I2, I5, k3]*
		SU3F[I4, k2, k3] + (I/6)*SU3F[I2, I4, k3]*SU3F[I5, k2, k3])) +
	SU3D[I1, I4, k2]*(SU3D[6, I2, k1]*SU3D[I3, k2, k3]*
		((I/6)*SU3D[I5, k1, k3] + SU3F[I5, k1, k3]/6) +
	SU3D[6, I3, k1]*(-(SU3D[I5, k1, k3]*SU3F[I2, k2, k3])/4 +
		(I/4)*SU3F[I2, k2, k3]*SU3F[I5, k1, k3]) + SU3D[6, I2, k1]*
		SU3D[I3, k1, k3]*((I/6)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/6) +
	SU3D[6, I2, k1]*((SU3D[I5, k2, k3]*SU3F[I3, k1, k3])/6 -
		(SU3D[I5, k1, k3]*SU3F[I3, k2, k3])/6 + (I/6)*SU3F[I3, k2, k3]*
		SU3F[I5, k1, k3] + (I/6)*SU3F[I3, k1, k3]*SU3F[I5, k2, k3])) +
	SU3F[I1, I5, k1]*((-I/6)*SU3F[I2, I4, k1]*SUNDelta[6, I3] -
	(I/6)*SU3F[I2, I3, k1]*SUNDelta[6, I4]) + SU3F[I1, I4, k1]*
	((-I/6)*SU3F[I2, I5, k1]*SUNDelta[6, I3] - (I/6)*SU3F[I2, I3, k1]*
		SUNDelta[6, I5]) + SU3F[I1, I3, k1]*
	((-I/6)*SU3F[I2, I5, k1]*SUNDelta[6, I4] - (I/6)*SU3F[I2, I4, k1]*
		SUNDelta[6, I5]) + SU3D[I2, I5, k1]*
	(SU3F[6, I4, k2]*((SU3F[I1, k2, k3]*SU3F[I3, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I3, k2, k3])/2) + SU3F[6, I3, k2]*
		((SU3F[I1, k2, k3]*SU3F[I4, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I4, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/6) + ((2*I)/9)*SU3D[I3, I4, k1]*
		SUNDelta[6, I1] + ((5*I)/18)*SU3D[I1, I4, k1]*SUNDelta[6, I3] +
	(5*SU3F[I1, I4, k1]*SUNDelta[6, I3])/18 + ((5*I)/18)*SU3D[I1, I3, k1]*
		SUNDelta[6, I4] + (5*SU3F[I1, I3, k1]*SUNDelta[6, I4])/18 -
	(SU3F[6, I4, k1]*SUNDelta[I1, I3])/6 -
	(SU3F[6, I3, k1]*SUNDelta[I1, I4])/6) + SU3D[I2, I4, k1]*
	(SU3F[6, I5, k2]*((SU3F[I1, k2, k3]*SU3F[I3, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I3, k2, k3])/2) + SU3F[6, I3, k2]*
		((SU3F[I1, k2, k3]*SU3F[I5, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I5, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/6) + ((2*I)/9)*SU3D[I3, I5, k1]*
		SUNDelta[6, I1] + ((5*I)/18)*SU3D[I1, I5, k1]*SUNDelta[6, I3] +
	(5*SU3F[I1, I5, k1]*SUNDelta[6, I3])/18 + ((5*I)/18)*SU3D[I1, I3, k1]*
		SUNDelta[6, I5] + (5*SU3F[I1, I3, k1]*SUNDelta[6, I5])/18 -
	(SU3F[6, I5, k1]*SUNDelta[I1, I3])/6 -
	(SU3F[6, I3, k1]*SUNDelta[I1, I5])/6) + SU3D[I2, I3, k1]*
	(SU3F[6, I5, k2]*((SU3F[I1, k2, k3]*SU3F[I4, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I4, k2, k3])/2) + SU3F[6, I4, k2]*
		((SU3F[I1, k2, k3]*SU3F[I5, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I5, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/6) + ((2*I)/9)*SU3D[I4, I5, k1]*
		SUNDelta[6, I1] + ((5*I)/18)*SU3D[I1, I5, k1]*SUNDelta[6, I4] +
	(5*SU3F[I1, I5, k1]*SUNDelta[6, I4])/18 + ((5*I)/18)*SU3D[I1, I4, k1]*
		SUNDelta[6, I5] + (5*SU3F[I1, I4, k1]*SUNDelta[6, I5])/18 -
	(SU3F[6, I5, k1]*SUNDelta[I1, I4])/6 -
	(SU3F[6, I4, k1]*SUNDelta[I1, I5])/6) + SU3D[I4, I5, k1]*
	(SU3F[6, I3, k2]*((SU3F[I1, k2, k3]*SU3F[I2, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I2, k2, k3])/2) + SU3F[6, I2, k2]*
		(-(SU3F[I1, k2, k3]*SU3F[I3, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I3, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/6 +
		(SU3F[I2, k1, k3]*SU3F[I3, k2, k3])/6) -
	(4*SU3F[I2, I3, k1]*SUNDelta[6, I1])/9 -
	(7*SU3F[I1, I3, k1]*SUNDelta[6, I2])/9 -
	(2*SU3F[6, I2, k1]*SUNDelta[I1, I3])/9 -
	(2*SU3F[6, I1, k1]*SUNDelta[I2, I3])/9) + SU3D[I3, I5, k1]*
	(SU3F[6, I4, k2]*((SU3F[I1, k2, k3]*SU3F[I2, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I2, k2, k3])/2) + SU3F[6, I2, k2]*
		(-(SU3F[I1, k2, k3]*SU3F[I4, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I4, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/6 +
		(SU3F[I2, k1, k3]*SU3F[I4, k2, k3])/6) -
	(4*SU3F[I2, I4, k1]*SUNDelta[6, I1])/9 -
	(7*SU3F[I1, I4, k1]*SUNDelta[6, I2])/9 -
	(2*SU3F[6, I2, k1]*SUNDelta[I1, I4])/9 -
	(2*SU3F[6, I1, k1]*SUNDelta[I2, I4])/9) + SU3D[I3, I4, k1]*
	(SU3F[6, I5, k2]*((SU3F[I1, k2, k3]*SU3F[I2, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I2, k2, k3])/2) + SU3F[6, I2, k2]*
		(-(SU3F[I1, k2, k3]*SU3F[I5, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I5, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/6 +
		(SU3F[I2, k1, k3]*SU3F[I5, k2, k3])/6) -
	(4*SU3F[I2, I5, k1]*SUNDelta[6, I1])/9 -
	(7*SU3F[I1, I5, k1]*SUNDelta[6, I2])/9 -
	(2*SU3F[6, I2, k1]*SUNDelta[I1, I5])/9 -
	(2*SU3F[6, I1, k1]*SUNDelta[I2, I5])/9) + SU3D[I1, I5, k1]*
	(-(SU3F[6, I4, k2]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3])/4 -
	(SU3F[6, I3, k2]*SU3F[I2, k1, k3]*SU3F[I4, k2, k3])/4 +
	SU3F[6, I2, k2]*(-(SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/6) + (I/9)*SU3D[I3, I4, k1]*
		SUNDelta[6, I2] + (SU3F[I2, I4, k1]*SUNDelta[6, I3])/6 +
	(SU3F[I2, I3, k1]*SUNDelta[6, I4])/6 -
	(SU3F[6, I4, k1]*SUNDelta[I2, I3])/9 -
	(SU3F[6, I3, k1]*SUNDelta[I2, I4])/9 +
	(SU3F[6, I2, k1]*SUNDelta[I3, I4])/9) + SU3D[6, I5, k1]*
	(SU3D[I3, I4, k3]*(-(SU3D[I2, k2, k3]*SU3F[I1, k1, k2])/3 +
		SU3D[I1, k1, k2]*((-I/3)*SU3D[I2, k2, k3] - SU3F[I2, k2, k3]/3)) +
	SU3D[I3, I4, k2]*((-I/2)*SU3F[I1, k2, k3]*SU3F[I2, k1, k3] -
		(I/3)*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]) -
	(SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/12 +
	SU3D[I4, k2, k3]*(-(SU3D[I2, I3, k2]*SU3F[I1, k1, k3])/3 +
		(I/3)*SU3F[I1, I3, k2]*SU3F[I2, k1, k3] - (I/12)*SU3F[I1, I2, k2]*
		SU3F[I3, k1, k3]) + SU3D[I1, I4, k2]*
		(-(SU3D[I3, k1, k3]*SU3F[I2, k2, k3])/4 + (I/4)*SU3F[I2, k2, k3]*
		SU3F[I3, k1, k3]) + SU3D[I4, k1, k3]*
		(-(SU3D[I2, I3, k2]*SU3F[I1, k2, k3])/2 +
		(SU3D[I1, I2, k2]*SU3F[I3, k2, k3])/4) + SU3D[I4, k1, k2]*
		((I/12)*SU3F[I1, I3, k3]*SU3F[I2, k2, k3] - (I/12)*SU3F[I1, I2, k3]*
		SU3F[I3, k2, k3]) + SU3D[I2, I4, k2]*
		((I/2)*SU3F[I1, k2, k3]*SU3F[I3, k1, k3] - (I/3)*SU3F[I1, k1, k3]*
		SU3F[I3, k2, k3]) + SU3D[I1, k2, k3]*
		((-I/2)*SU3D[I2, k1, k2]*SU3D[I3, I4, k3] -
		(SU3D[I3, I4, k3]*SU3F[I2, k1, k2])/2 + SU3D[I2, I4, k3]*
		((I/2)*SU3D[I3, k1, k2] + SU3F[I3, k1, k2]/2) +
		SU3D[I2, I3, k3]*((I/2)*SU3D[I4, k1, k2] + SU3F[I4, k1, k2]/2)) -
	(SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/12 +
	(SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/12 +
	SU3D[I3, k2, k3]*((-I/4)*SU3D[I1, I2, k2]*SU3D[I4, k1, k3] +
		(SU3D[I4, k1, k2]*SU3F[I1, I2, k3])/12 -
		(SU3D[I2, I4, k2]*SU3F[I1, k1, k3])/3 + (I/3)*SU3F[I1, I4, k2]*
		SU3F[I2, k1, k3] - (SU3D[I1, I2, k2]*SU3F[I4, k1, k3])/4 -
		(I/12)*SU3F[I1, I2, k2]*SU3F[I4, k1, k3]) +
	SU3D[I2, k2, k3]*(-(SU3D[I4, k1, k2]*SU3F[I1, I3, k3])/12 -
		(SU3D[I3, k1, k2]*SU3F[I1, I4, k3])/12 + SU3D[I1, I4, k2]*
		((I/4)*SU3D[I3, k1, k3] + SU3F[I3, k1, k3]/4) +
		(I/12)*SU3F[I1, I4, k2]*SU3F[I3, k1, k3] + SU3D[I1, I3, k2]*
		((I/4)*SU3D[I4, k1, k3] + SU3F[I4, k1, k3]/4) +
		(I/12)*SU3F[I1, I3, k2]*SU3F[I4, k1, k3]) +
	SU3D[I1, I3, k2]*(-(SU3D[I4, k1, k3]*SU3F[I2, k2, k3])/4 +
		(I/4)*SU3F[I2, k2, k3]*SU3F[I4, k1, k3]) + SU3D[I1, k1, k2]*
		(SU3D[I2, I4, k3]*((-I/3)*SU3D[I3, k2, k3] - SU3F[I3, k2, k3]/3) +
		SU3D[I2, I3, k3]*((-I/3)*SU3D[I4, k2, k3] - SU3F[I4, k2, k3]/3)) +
	SU3D[I3, k1, k3]*(-(SU3D[I2, I4, k2]*SU3F[I1, k2, k3])/2 +
		SU3D[I1, I2, k2]*((-I/4)*SU3D[I4, k2, k3] + SU3F[I4, k2, k3]/4)) +
	(SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/12 +
	SU3D[I3, k1, k2]*((SU3D[I4, k2, k3]*SU3F[I1, I2, k3])/12 +
		(I/12)*SU3F[I1, I4, k3]*SU3F[I2, k2, k3] - (I/12)*SU3F[I1, I2, k3]*
		SU3F[I4, k2, k3]) + SU3F[I2, k1, k3]*
		(-(SU3F[I1, I4, k2]*SU3F[I3, k2, k3])/3 -
		(SU3F[I1, I3, k2]*SU3F[I4, k2, k3])/3) + SU3D[I2, k1, k2]*
		(-(SU3D[I4, k2, k3]*SU3F[I1, I3, k3])/3 -
		(SU3D[I3, k2, k3]*SU3F[I1, I4, k3])/3 -
		(SU3D[I3, I4, k3]*SU3F[I1, k2, k3])/2 + (I/3)*SU3F[I1, I4, k3]*
		SU3F[I3, k2, k3] + (I/3)*SU3F[I1, I3, k3]*SU3F[I4, k2, k3]) +
	SU3D[I2, I3, k2]*((I/2)*SU3F[I1, k2, k3]*SU3F[I4, k1, k3] -
		(I/3)*SU3F[I1, k1, k3]*SU3F[I4, k2, k3]) + SU3D[I1, I2, k2]*
		(-(SU3D[I4, k2, k3]*SU3F[I3, k1, k3])/4 - (I/4)*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3] - (I/4)*SU3F[I3, k1, k3]*SU3F[I4, k2, k3]) +
	(I/6)*SU3D[I2, I4, k1]*SUNDelta[I1, I3] +
	(SU3F[I2, I4, k1]*SUNDelta[I1, I3])/6 + (I/6)*SU3D[I2, I3, k1]*
		SUNDelta[I1, I4] + (SU3F[I2, I3, k1]*SUNDelta[I1, I4])/6 +
	(I/9)*SU3D[I1, I4, k1]*SUNDelta[I2, I3] +
	(5*SU3F[I1, I4, k1]*SUNDelta[I2, I3])/9 + (I/9)*SU3D[I1, I3, k1]*
		SUNDelta[I2, I4] + (5*SU3F[I1, I3, k1]*SUNDelta[I2, I4])/9 -
	((5*I)/9)*SU3D[I1, I2, k1]*SUNDelta[I3, I4] -
	(SU3F[I1, I2, k1]*SUNDelta[I3, I4])/9) + SU3F[6, I5, k1]*
	((-I/12)*SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3] -
	(I/12)*SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3] +
	(I/12)*SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I4, k1, k3] +
	(I/12)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SU3F[I4, k2, k3] +
	SU3F[I2, k1, k3]*((-I/3)*SU3F[I1, I4, k2]*SU3F[I3, k2, k3] -
		(I/3)*SU3F[I1, I3, k2]*SU3F[I4, k2, k3]) + (I/6)*SU3F[I2, I4, k1]*
		SUNDelta[I1, I3] + (I/6)*SU3F[I2, I3, k1]*SUNDelta[I1, I4] +
	((5*I)/9)*SU3F[I1, I4, k1]*SUNDelta[I2, I3] +
	((5*I)/9)*SU3F[I1, I3, k1]*SUNDelta[I2, I4] - (I/9)*SU3F[I1, I2, k1]*
		SUNDelta[I3, I4]) + SUNDelta[6, I5]*
	(((5*I)/27)*SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	((5*I)/27)*SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	((16*I)/27)*SUNDelta[I1, I2]*SUNDelta[I3, I4]) +
	SU3D[I1, I4, k1]*(-(SU3F[6, I5, k2]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3])/
		4 - (SU3F[6, I3, k2]*SU3F[I2, k1, k3]*SU3F[I5, k2, k3])/4 +
	SU3F[6, I2, k2]*(-(SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/6) + (I/9)*SU3D[I3, I5, k1]*
		SUNDelta[6, I2] + (SU3F[I2, I5, k1]*SUNDelta[6, I3])/6 +
	(SU3F[I2, I3, k1]*SUNDelta[6, I5])/6 -
	(SU3F[6, I5, k1]*SUNDelta[I2, I3])/9 -
	(SU3F[6, I3, k1]*SUNDelta[I2, I5])/9 +
	(SU3F[6, I2, k1]*SUNDelta[I3, I5])/9) + SU3D[6, I4, k1]*
	(-(SU3D[I2, I3, k2]*SU3D[I5, k1, k3]*SU3F[I1, k2, k3])/2 +
	SU3D[I3, I5, k2]*((-I/2)*SU3F[I1, k2, k3]*SU3F[I2, k1, k3] -
		(I/3)*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]) + (I/4)*SU3D[I1, I5, k2]*
		SU3F[I2, k2, k3]*SU3F[I3, k1, k3] -
	(SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/12 +
	SU3D[I5, k2, k3]*((I/3)*SU3F[I1, I3, k2]*SU3F[I2, k1, k3] -
		(I/12)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]) +
	SU3D[I5, k1, k2]*((I/12)*SU3F[I1, I3, k3]*SU3F[I2, k2, k3] -
		(I/12)*SU3F[I1, I2, k3]*SU3F[I3, k2, k3]) +
	SU3D[I2, I5, k2]*((I/2)*SU3F[I1, k2, k3]*SU3F[I3, k1, k3] -
		(I/3)*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]) -
	(SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/12 +
	(SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/12 +
	SU3D[I3, k2, k3]*((SU3D[I5, k1, k2]*SU3F[I1, I2, k3])/12 -
		(SU3D[I2, I5, k2]*SU3F[I1, k1, k3])/3 + (I/3)*SU3F[I1, I5, k2]*
		SU3F[I2, k1, k3] + SU3D[I1, I2, k2]*((-I/4)*SU3D[I5, k1, k3] -
		SU3F[I5, k1, k3]/4) - (I/12)*SU3F[I1, I2, k2]*SU3F[I5, k1, k3]) +
	SU3D[I1, I3, k2]*(-(SU3D[I5, k1, k3]*SU3F[I2, k2, k3])/4 +
		(I/4)*SU3F[I2, k2, k3]*SU3F[I5, k1, k3]) + SU3D[I3, k1, k3]*
		(-(SU3D[I2, I5, k2]*SU3F[I1, k2, k3])/2 -
		(SU3D[I1, I5, k2]*SU3F[I2, k2, k3])/4 + SU3D[I1, I2, k2]*
		((-I/4)*SU3D[I5, k2, k3] + SU3F[I5, k2, k3]/4)) +
	(SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/12 +
	SU3D[I3, k1, k2]*((SU3D[I5, k2, k3]*SU3F[I1, I2, k3])/12 +
		(I/12)*SU3F[I1, I5, k3]*SU3F[I2, k2, k3] - (I/12)*SU3F[I1, I2, k3]*
		SU3F[I5, k2, k3]) + SU3F[I2, k1, k3]*
		(-(SU3F[I1, I5, k2]*SU3F[I3, k2, k3])/3 -
		(SU3F[I1, I3, k2]*SU3F[I5, k2, k3])/3) + SU3D[I2, I3, k2]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, k1, k3])/3 + (I/2)*SU3F[I1, k2, k3]*
		SU3F[I5, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I5, k2, k3]) +
	SU3D[I1, I2, k2]*(-(SU3D[I5, k2, k3]*SU3F[I3, k1, k3])/4 +
		(SU3D[I5, k1, k3]*SU3F[I3, k2, k3])/4 - (I/4)*SU3F[I3, k2, k3]*
		SU3F[I5, k1, k3] - (I/4)*SU3F[I3, k1, k3]*SU3F[I5, k2, k3]) +
	(I/6)*SU3D[I2, I5, k1]*SUNDelta[I1, I3] +
	(SU3F[I2, I5, k1]*SUNDelta[I1, I3])/6 + (I/6)*SU3D[I2, I3, k1]*
		SUNDelta[I1, I5] + (SU3F[I2, I3, k1]*SUNDelta[I1, I5])/6 +
	(I/9)*SU3D[I1, I5, k1]*SUNDelta[I2, I3] +
	(5*SU3F[I1, I5, k1]*SUNDelta[I2, I3])/9 + (I/9)*SU3D[I1, I3, k1]*
		SUNDelta[I2, I5] + (5*SU3F[I1, I3, k1]*SUNDelta[I2, I5])/9 -
	((5*I)/9)*SU3D[I1, I2, k1]*SUNDelta[I3, I5] -
	(SU3F[I1, I2, k1]*SUNDelta[I3, I5])/9) + SU3F[6, I4, k1]*
	((-I/12)*SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3] -
	(I/12)*SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*SU3F[I5, k1, k3] +
	(I/12)*SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I5, k1, k3] +
	(I/12)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SU3F[I5, k2, k3] +
	SU3F[I2, k1, k3]*((-I/3)*SU3F[I1, I5, k2]*SU3F[I3, k2, k3] -
		(I/3)*SU3F[I1, I3, k2]*SU3F[I5, k2, k3]) + (I/6)*SU3F[I2, I5, k1]*
		SUNDelta[I1, I3] + (I/6)*SU3F[I2, I3, k1]*SUNDelta[I1, I5] +
	((5*I)/9)*SU3F[I1, I5, k1]*SUNDelta[I2, I3] +
	((5*I)/9)*SU3F[I1, I3, k1]*SUNDelta[I2, I5] - (I/9)*SU3F[I1, I2, k1]*
		SUNDelta[I3, I5]) + SUNDelta[6, I4]*
	(((5*I)/27)*SUNDelta[I1, I5]*SUNDelta[I2, I3] +
	((5*I)/27)*SUNDelta[I1, I3]*SUNDelta[I2, I5] -
	((16*I)/27)*SUNDelta[I1, I2]*SUNDelta[I3, I5]) +
	SU3D[I1, I3, k1]*(-(SU3F[6, I5, k2]*SU3F[I2, k1, k3]*SU3F[I4, k2, k3])/
		4 - (SU3F[6, I4, k2]*SU3F[I2, k1, k3]*SU3F[I5, k2, k3])/4 +
	SU3F[6, I2, k2]*(-(SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/6) + (I/9)*SU3D[I4, I5, k1]*
		SUNDelta[6, I2] + (SU3F[I2, I5, k1]*SUNDelta[6, I4])/6 +
	(SU3F[I2, I4, k1]*SUNDelta[6, I5])/6 -
	(SU3F[6, I5, k1]*SUNDelta[I2, I4])/9 -
	(SU3F[6, I4, k1]*SUNDelta[I2, I5])/9 +
	(SU3F[6, I2, k1]*SUNDelta[I4, I5])/9) + SU3D[I1, I2, k1]*
	(SU3F[6, I5, k2]*((SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/4 +
		(SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/4) + SU3F[6, I4, k2]*
		((SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/4 +
		(SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/4) + SU3F[6, I3, k2]*
		((SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/4 +
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/4) - ((8*I)/9)*SU3D[I4, I5, k1]*
		SUNDelta[6, I3] - ((8*I)/9)*SU3D[I3, I5, k1]*SUNDelta[6, I4] -
	((8*I)/9)*SU3D[I3, I4, k1]*SUNDelta[6, I5] +
	(5*SU3F[6, I5, k1]*SUNDelta[I3, I4])/9 +
	(5*SU3F[6, I4, k1]*SUNDelta[I3, I5])/9 +
	(5*SU3F[6, I3, k1]*SUNDelta[I4, I5])/9) +
	SU3D[6, I3, k1]*(-(SU3D[I2, I4, k2]*SU3D[I5, k1, k3]*SU3F[I1, k2, k3])/
		2 - (SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/12 +
	SU3D[I5, k2, k3]*((I/3)*SU3F[I1, I4, k2]*SU3F[I2, k1, k3] -
		(I/12)*SU3F[I1, I2, k2]*SU3F[I4, k1, k3]) +
	SU3D[I5, k1, k2]*((I/12)*SU3F[I1, I4, k3]*SU3F[I2, k2, k3] -
		(I/12)*SU3F[I1, I2, k3]*SU3F[I4, k2, k3]) +
	SU3D[I2, I5, k2]*(-(SU3D[I4, k2, k3]*SU3F[I1, k1, k3])/3 +
		(I/2)*SU3F[I1, k2, k3]*SU3F[I4, k1, k3] - (I/3)*SU3F[I1, k1, k3]*
		SU3F[I4, k2, k3]) - (SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*
		SU3F[I5, k1, k3])/12 + SU3D[I4, k2, k3]*
		((SU3D[I5, k1, k2]*SU3F[I1, I2, k3])/12 + (I/3)*SU3F[I1, I5, k2]*
		SU3F[I2, k1, k3] - (I/12)*SU3F[I1, I2, k2]*SU3F[I5, k1, k3]) +
	SU3D[I4, k1, k3]*(-(SU3D[I2, I5, k2]*SU3F[I1, k2, k3])/2 +
		SU3D[I1, I2, k2]*((-I/4)*SU3D[I5, k2, k3] + SU3F[I5, k2, k3]/4)) +
	SU3D[I4, k1, k2]*((SU3D[I5, k2, k3]*SU3F[I1, I2, k3])/12 +
		(I/12)*SU3F[I1, I5, k3]*SU3F[I2, k2, k3] - (I/12)*SU3F[I1, I2, k3]*
		SU3F[I5, k2, k3]) + SU3F[I2, k1, k3]*
		(-(SU3F[I1, I5, k2]*SU3F[I4, k2, k3])/3 -
		(SU3F[I1, I4, k2]*SU3F[I5, k2, k3])/3) + SU3D[I2, I4, k2]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, k1, k3])/3 + (I/2)*SU3F[I1, k2, k3]*
		SU3F[I5, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I5, k2, k3]) +
	SU3D[I1, I2, k2]*(-(SU3D[I5, k2, k3]*SU3F[I4, k1, k3])/4 +
		(SU3D[I5, k1, k3]*SU3F[I4, k2, k3])/4 + SU3D[I4, k2, k3]*
		((-I/4)*SU3D[I5, k1, k3] - SU3F[I5, k1, k3]/4) -
		(I/4)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] - (I/4)*SU3F[I4, k1, k3]*
		SU3F[I5, k2, k3]) + SU3F[I1, I2, k2]*
		((SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/12 +
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/12) + (I/6)*SU3D[I2, I5, k1]*
		SUNDelta[I1, I4] + (SU3F[I2, I5, k1]*SUNDelta[I1, I4])/6 +
	(I/6)*SU3D[I2, I4, k1]*SUNDelta[I1, I5] +
	(SU3F[I2, I4, k1]*SUNDelta[I1, I5])/6 + (I/9)*SU3D[I1, I5, k1]*
		SUNDelta[I2, I4] + (5*SU3F[I1, I5, k1]*SUNDelta[I2, I4])/9 +
	(I/9)*SU3D[I1, I4, k1]*SUNDelta[I2, I5] +
	(5*SU3F[I1, I4, k1]*SUNDelta[I2, I5])/9 - ((5*I)/9)*SU3D[I1, I2, k1]*
		SUNDelta[I4, I5] - (SU3F[I1, I2, k1]*SUNDelta[I4, I5])/9) +
	SU3F[6, I3, k1]*((-I/12)*SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*
		SU3F[I4, k1, k3] - (I/12)*SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*
		SU3F[I5, k1, k3] + SU3F[I2, k1, k3]*((-I/3)*SU3F[I1, I5, k2]*
		SU3F[I4, k2, k3] - (I/3)*SU3F[I1, I4, k2]*SU3F[I5, k2, k3]) +
	SU3F[I1, I2, k2]*((I/12)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] +
		(I/12)*SU3F[I4, k1, k3]*SU3F[I5, k2, k3]) + (I/6)*SU3F[I2, I5, k1]*
		SUNDelta[I1, I4] + (I/6)*SU3F[I2, I4, k1]*SUNDelta[I1, I5] +
	((5*I)/9)*SU3F[I1, I5, k1]*SUNDelta[I2, I4] +
	((5*I)/9)*SU3F[I1, I4, k1]*SUNDelta[I2, I5] - (I/9)*SU3F[I1, I2, k1]*
		SUNDelta[I4, I5]) + SU3D[6, I2, k1]*
	((SU3D[I3, I5, k2]*SU3D[I4, k1, k3]*SU3F[I1, k2, k3])/2 +
	(SU3D[I3, I4, k2]*SU3D[I5, k1, k3]*SU3F[I1, k2, k3])/2 +
	SU3D[I4, I5, k2]*((-I/2)*SU3F[I1, k2, k3]*SU3F[I3, k1, k3] +
		(I/3)*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]) + SU3D[I5, k2, k3]*
		((I/6)*SU3F[I1, I4, k2]*SU3F[I3, k1, k3] + (I/6)*SU3F[I1, I3, k2]*
		SU3F[I4, k1, k3]) + SU3D[I5, k1, k2]*
		((I/6)*SU3F[I1, I4, k3]*SU3F[I3, k2, k3] + (I/6)*SU3F[I1, I3, k3]*
		SU3F[I4, k2, k3]) + SU3D[I3, I5, k2]*
		((SU3D[I4, k2, k3]*SU3F[I1, k1, k3])/3 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I4, k1, k3] + (I/3)*SU3F[I1, k1, k3]*SU3F[I4, k2, k3]) +
	SU3F[I1, I5, k2]*(-(SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/6) + SU3D[I4, k2, k3]*
		(-(SU3D[I5, k1, k2]*SU3F[I1, I3, k3])/6 + (I/6)*SU3F[I1, I5, k2]*
		SU3F[I3, k1, k3] + (I/6)*SU3F[I1, I3, k2]*SU3F[I5, k1, k3]) +
	SU3D[I4, k1, k2]*(-(SU3D[I5, k2, k3]*SU3F[I1, I3, k3])/6 +
		(I/6)*SU3F[I1, I5, k3]*SU3F[I3, k2, k3] + (I/6)*SU3F[I1, I3, k3]*
		SU3F[I5, k2, k3]) + SU3D[I3, I4, k2]*
		((SU3D[I5, k2, k3]*SU3F[I1, k1, k3])/3 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I5, k1, k3] + (I/3)*SU3F[I1, k1, k3]*SU3F[I5, k2, k3]) +
	SU3F[I1, I4, k2]*(-(SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/6) + SU3F[I1, I3, k2]*
		(-(SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/6) + SU3D[I1, I3, k2]*
		((SU3D[I5, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3D[I5, k1, k3]*SU3F[I4, k2, k3])/6 + SU3D[I4, k2, k3]*
		((I/6)*SU3D[I5, k1, k3] + SU3F[I5, k1, k3]/6) +
		(I/6)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] + SU3D[I4, k1, k3]*
		((I/6)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/6) +
		(I/6)*SU3F[I4, k1, k3]*SU3F[I5, k2, k3]) +
	((2*I)/9)*SU3D[I4, I5, k1]*SUNDelta[I1, I3] +
	((2*I)/9)*SU3D[I3, I5, k1]*SUNDelta[I1, I4] +
	((2*I)/9)*SU3D[I3, I4, k1]*SUNDelta[I1, I5] - (I/9)*SU3D[I1, I5, k1]*
		SUNDelta[I3, I4] - (5*SU3F[I1, I5, k1]*SUNDelta[I3, I4])/9 -
	(I/9)*SU3D[I1, I4, k1]*SUNDelta[I3, I5] -
	(5*SU3F[I1, I4, k1]*SUNDelta[I3, I5])/9 - (I/9)*SU3D[I1, I3, k1]*
		SUNDelta[I4, I5] - (5*SU3F[I1, I3, k1]*SUNDelta[I4, I5])/9) +
	SU3F[6, I2, k1]*(SU3F[I1, I5, k2]*((-I/6)*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3] - (I/6)*SU3F[I3, k1, k3]*SU3F[I4, k2, k3]) +
	SU3F[I1, I4, k2]*((-I/6)*SU3F[I3, k2, k3]*SU3F[I5, k1, k3] -
		(I/6)*SU3F[I3, k1, k3]*SU3F[I5, k2, k3]) + SU3F[I1, I3, k2]*
		((-I/6)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] - (I/6)*SU3F[I4, k1, k3]*
		SU3F[I5, k2, k3]) - ((5*I)/9)*SU3F[I1, I5, k1]*SUNDelta[I3, I4] -
	((5*I)/9)*SU3F[I1, I4, k1]*SUNDelta[I3, I5] -
	((5*I)/9)*SU3F[I1, I3, k1]*SUNDelta[I4, I5]) +
	SU3D[6, I1, k1]*(-(SU3F[I2, I5, k2]*SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/
		6 + SU3D[I5, k2, k3]*((I/6)*SU3F[I2, I4, k2]*SU3F[I3, k1, k3] +
		(I/6)*SU3F[I2, I3, k2]*SU3F[I4, k1, k3]) + SU3D[I5, k1, k3]*
		((SU3D[I3, I4, k2]*SU3F[I2, k2, k3])/6 -
		(SU3D[I2, I4, k2]*SU3F[I3, k2, k3])/6 -
		(SU3D[I2, I3, k2]*SU3F[I4, k2, k3])/6) + SU3D[I5, k1, k2]*
		((I/6)*SU3F[I2, I4, k3]*SU3F[I3, k2, k3] + (I/6)*SU3F[I2, I3, k3]*
		SU3F[I4, k2, k3]) + SU3D[I3, I5, k2]*
		((SU3D[I4, k2, k3]*SU3F[I2, k1, k3])/6 - (I/6)*SU3F[I2, k2, k3]*
		SU3F[I4, k1, k3] + (I/6)*SU3F[I2, k1, k3]*SU3F[I4, k2, k3]) +
	SU3D[I2, I5, k2]*((SU3D[I4, k2, k3]*SU3F[I3, k1, k3])/6 +
		(I/6)*SU3F[I3, k2, k3]*SU3F[I4, k1, k3] + (I/6)*SU3F[I3, k1, k3]*
		SU3F[I4, k2, k3]) - (SU3F[I2, I4, k2]*SU3F[I3, k2, k3]*
		SU3F[I5, k1, k3])/6 - (SU3F[I2, I3, k2]*SU3F[I4, k2, k3]*
		SU3F[I5, k1, k3])/6 + SU3D[I4, k2, k3]*
		((I/6)*SU3D[I2, I3, k2]*SU3D[I5, k1, k3] -
		(SU3D[I5, k1, k2]*SU3F[I2, I3, k3])/6 + (I/6)*SU3F[I2, I5, k2]*
		SU3F[I3, k1, k3] + (SU3D[I2, I3, k2]*SU3F[I5, k1, k3])/6 +
		(I/6)*SU3F[I2, I3, k2]*SU3F[I5, k1, k3]) + SU3D[I4, k1, k3]*
		((SU3D[I3, I5, k2]*SU3F[I2, k2, k3])/6 -
		(SU3D[I2, I5, k2]*SU3F[I3, k2, k3])/6 + SU3D[I2, I3, k2]*
		((I/6)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/6)) -
	(SU3F[I2, I3, k2]*SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/6 +
	SU3D[I4, k1, k2]*(-(SU3D[I5, k2, k3]*SU3F[I2, I3, k3])/6 +
		(I/6)*SU3F[I2, I5, k3]*SU3F[I3, k2, k3] + (I/6)*SU3F[I2, I3, k3]*
		SU3F[I5, k2, k3]) + SU3F[I3, k1, k3]*
		(-(SU3F[I2, I5, k2]*SU3F[I4, k2, k3])/6 -
		(SU3F[I2, I4, k2]*SU3F[I5, k2, k3])/6) + SU3D[I3, I4, k2]*
		((SU3D[I5, k2, k3]*SU3F[I2, k1, k3])/6 - (I/6)*SU3F[I2, k2, k3]*
		SU3F[I5, k1, k3] + (I/6)*SU3F[I2, k1, k3]*SU3F[I5, k2, k3]) +
	SU3D[I2, I4, k2]*((SU3D[I5, k2, k3]*SU3F[I3, k1, k3])/6 +
		(I/6)*SU3F[I3, k2, k3]*SU3F[I5, k1, k3] + (I/6)*SU3F[I3, k1, k3]*
		SU3F[I5, k2, k3]) + SU3D[I2, I3, k2]*
		((SU3D[I5, k2, k3]*SU3F[I4, k1, k3])/6 + (I/6)*SU3F[I4, k2, k3]*
		SU3F[I5, k1, k3] + (I/6)*SU3F[I4, k1, k3]*SU3F[I5, k2, k3]) +
	((2*I)/9)*SU3D[I4, I5, k1]*SUNDelta[I2, I3] +
	((2*I)/9)*SU3D[I3, I5, k1]*SUNDelta[I2, I4] +
	((2*I)/9)*SU3D[I3, I4, k1]*SUNDelta[I2, I5] -
	(2*SU3F[I2, I5, k1]*SUNDelta[I3, I4])/9 -
	(2*SU3F[I2, I4, k1]*SUNDelta[I3, I5])/9 -
	(2*SU3F[I2, I3, k1]*SUNDelta[I4, I5])/9) +
	SU3F[6, I1, k1]*((-I/6)*SU3F[I2, I5, k2]*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3] - (I/6)*SU3F[I2, I4, k2]*SU3F[I3, k2, k3]*
		SU3F[I5, k1, k3] - (I/6)*SU3F[I2, I3, k2]*SU3F[I4, k2, k3]*
		SU3F[I5, k1, k3] - (I/6)*SU3F[I2, I3, k2]*SU3F[I4, k1, k3]*
		SU3F[I5, k2, k3] + SU3F[I3, k1, k3]*((-I/6)*SU3F[I2, I5, k2]*
		SU3F[I4, k2, k3] - (I/6)*SU3F[I2, I4, k2]*SU3F[I5, k2, k3]) -
	((2*I)/9)*SU3F[I2, I5, k1]*SUNDelta[I3, I4] -
	((2*I)/9)*SU3F[I2, I4, k1]*SUNDelta[I3, I5] -
	((2*I)/9)*SU3F[I2, I3, k1]*SUNDelta[I4, I5]) +
	SUNDelta[6, I3]*(((5*I)/27)*SUNDelta[I1, I5]*SUNDelta[I2, I4] +
	((5*I)/27)*SUNDelta[I1, I4]*SUNDelta[I2, I5] -
	((16*I)/27)*SUNDelta[I1, I2]*SUNDelta[I4, I5]) +
	SUNDelta[6, I2]*(((2*I)/27)*SUNDelta[I1, I5]*SUNDelta[I3, I4] +
	((2*I)/27)*SUNDelta[I1, I4]*SUNDelta[I3, I5] +
	((2*I)/27)*SUNDelta[I1, I3]*SUNDelta[I4, I5]) +
	SUNDelta[6, I1]*(((4*I)/27)*SUNDelta[I2, I5]*SUNDelta[I3, I4] +
	((4*I)/27)*SUNDelta[I2, I4]*SUNDelta[I3, I5] +
	((4*I)/27)*SUNDelta[I2, I3]*SUNDelta[I4, I5])))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{(CouplingConstant[ChPTW3[2], 1]*(((-4*I)/9)*SU3D[6, I4, I5]*
	SU3D[I1, I2, I3] - ((4*I)/9)*SU3D[6, I3, I4]*SU3D[I1, I2, I5] -
	((4*I)/9)*SU3D[6, I2, I4]*SU3D[I1, I3, I5] - ((5*I)/9)*SU3D[6, I1, I5]*
	SU3D[I2, I3, I4] + I*SU3D[6, I1, I4]*SU3D[I2, I3, I5] -
	((5*I)/9)*SU3D[6, I1, I3]*SU3D[I2, I4, I5] - ((5*I)/9)*SU3D[6, I1, I2]*
	SU3D[I3, I4, I5] - (7*SU3D[I3, I4, I5]*SU3F[6, I1, I2])/9 -
	(7*SU3D[I2, I4, I5]*SU3F[6, I1, I3])/9 +
	(SU3D[I2, I3, I5]*SU3F[6, I1, I4])/3 -
	(7*SU3D[I2, I3, I4]*SU3F[6, I1, I5])/9 +
	(2*SU3D[I1, I3, I5]*SU3F[6, I2, I4])/9 +
	(2*SU3D[I1, I2, I5]*SU3F[6, I3, I4])/9 -
	(2*SU3D[I1, I2, I3]*SU3F[6, I4, I5])/9 + SU3D[6, I3, I5]*
	(((2*I)/3)*SU3D[I1, I2, I4] - (2*SU3F[I1, I2, I4])/9) +
	SU3D[6, I2, I5]*(((2*I)/3)*SU3D[I1, I3, I4] - (2*SU3F[I1, I3, I4])/9) +
	SU3D[6, I2, I3]*(((2*I)/3)*SU3D[I1, I4, I5] + (2*SU3F[I1, I4, I5])/9) +
	SU3D[I4, I5, k2]*(SU3D[6, I3, k1]*((I/2)*SU3F[I1, k2, k3]*
		SU3F[I2, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]) +
	SU3D[6, I2, k1]*((I/2)*SU3F[I1, k2, k3]*SU3F[I3, k1, k3] -
		(I/3)*SU3F[I1, k1, k3]*SU3F[I3, k2, k3])) +
	SU3D[I5, k2, k3]*(SU3D[I3, I4, k1]*((-I/2)*SU3F[6, I2, k2]*
		SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*SU3F[I2, k1, k3]) +
	SU3D[I2, I4, k1]*((-I/2)*SU3F[6, I3, k2]*SU3F[I1, k1, k3] -
		(I/6)*SU3F[6, I1, k2]*SU3F[I3, k1, k3]) + SU3D[I1, I4, k1]*
		((I/4)*SU3F[6, I3, k2]*SU3F[I2, k1, k3] + (I/4)*SU3F[6, I2, k2]*
		SU3F[I3, k1, k3]) + SU3D[I2, I3, k1]*
		((I/2)*SU3F[6, I4, k2]*SU3F[I1, k1, k3] + (I/6)*SU3F[6, I1, k2]*
		SU3F[I4, k1, k3]) + SU3D[I1, I3, k1]*
		((-I/6)*SU3F[6, I4, k2]*SU3F[I2, k1, k3] - (I/4)*SU3F[6, I2, k2]*
		SU3F[I4, k1, k3]) + SU3D[I1, I2, k1]*
		((-I/6)*SU3F[6, I4, k2]*SU3F[I3, k1, k3] - (I/4)*SU3F[6, I3, k2]*
		SU3F[I4, k1, k3])) + SU3D[I5, k1, k2]*
	((-I/6)*SU3D[I1, I3, k1]*SU3F[6, I4, k3]*SU3F[I2, k2, k3] +
	SU3D[I3, I4, k1]*((I/3)*SU3F[6, I2, k3]*SU3F[I1, k2, k3] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I2, k2, k3]) + SU3F[6, I4, k2]*
		(-(SU3F[I1, I3, k3]*SU3F[I2, k1, k3])/6 -
		(SU3F[I1, I2, k3]*SU3F[I3, k1, k3])/6) + SU3F[6, I1, k2]*
		((SU3F[I2, k1, k3]*SU3F[I3, I4, k3])/6 +
		(SU3F[I2, I4, k3]*SU3F[I3, k1, k3])/6) - (I/6)*SU3D[I1, I2, k1]*
		SU3F[6, I4, k3]*SU3F[I3, k2, k3] + SU3D[I2, I4, k1]*
		((I/3)*SU3F[6, I3, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I3, k2, k3]) + SU3D[I1, I4, k1]*
		((I/4)*SU3F[6, I3, k3]*SU3F[I2, k2, k3] + (I/4)*SU3F[6, I2, k3]*
		SU3F[I3, k2, k3]) + SU3F[6, I4, k3]*
		((SU3F[I1, I3, k1]*SU3F[I2, k2, k3])/6 +
		(SU3F[I1, I2, k1]*SU3F[I3, k2, k3])/6) + SU3F[6, I1, k3]*
		(-(SU3F[I2, k2, k3]*SU3F[I3, I4, k1])/6 -
		(SU3F[I2, I4, k1]*SU3F[I3, k2, k3])/6) + SU3F[6, I3, k2]*
		((SU3F[I1, I4, k3]*SU3F[I2, k1, k3])/12 -
		(SU3F[I1, I2, k3]*SU3F[I4, k1, k3])/12) + SU3F[6, I2, k2]*
		((SU3F[I1, I4, k3]*SU3F[I3, k1, k3])/12 -
		(SU3F[I1, I3, k3]*SU3F[I4, k1, k3])/12) + SU3D[I2, I3, k1]*
		((-I/3)*SU3F[6, I4, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I4, k2, k3]) + SU3F[6, I3, k3]*
		(-(SU3F[I1, I4, k1]*SU3F[I2, k2, k3])/12 +
		(SU3F[I1, I2, k1]*SU3F[I4, k2, k3])/3) + SU3F[6, I2, k3]*
		(-(SU3F[I1, I4, k1]*SU3F[I3, k2, k3])/12 +
		(SU3F[I1, I3, k1]*SU3F[I4, k2, k3])/3)) +
	SU3D[I3, I5, k2]*(SU3D[6, I2, k1]*(-(SU3D[I4, k2, k3]*SU3F[I1, k1, k3])/
		3 + (SU3D[I4, k1, k3]*SU3F[I1, k2, k3])/2 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I4, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I4, k2, k3]) +
	SU3D[6, I1, k1]*(-(SU3D[I4, k2, k3]*SU3F[I2, k1, k3])/6 -
		(SU3D[I4, k1, k3]*SU3F[I2, k2, k3])/6 + (I/6)*SU3F[I2, k2, k3]*
		SU3F[I4, k1, k3] - (I/6)*SU3F[I2, k1, k3]*SU3F[I4, k2, k3])) +
	SU3D[I2, I5, k2]*(SU3D[6, I1, k1]*SU3D[I3, k2, k3]*
		((I/6)*SU3D[I4, k1, k3] + SU3F[I4, k1, k3]/6) +
	SU3D[6, I1, k1]*SU3D[I3, k1, k3]*((-I/6)*SU3D[I4, k2, k3] +
		SU3F[I4, k2, k3]/6) + SU3D[6, I3, k1]*
		(-(SU3D[I4, k2, k3]*SU3F[I1, k1, k3])/3 +
		(SU3D[I4, k1, k3]*SU3F[I1, k2, k3])/2 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I4, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I4, k2, k3]) +
	SU3D[6, I1, k1]*(-(SU3D[I4, k2, k3]*SU3F[I3, k1, k3])/6 -
		(SU3D[I4, k1, k3]*SU3F[I3, k2, k3])/6 + (I/6)*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3] - (I/6)*SU3F[I3, k1, k3]*SU3F[I4, k2, k3])) +
	SU3D[I1, I5, k2]*(SU3D[6, I3, k1]*((SU3D[I4, k2, k3]*SU3F[I2, k1, k3])/
		4 + (I/4)*SU3F[I2, k1, k3]*SU3F[I4, k2, k3]) +
	SU3D[6, I2, k1]*((SU3D[I4, k2, k3]*SU3F[I3, k1, k3])/4 +
		(I/4)*SU3F[I3, k1, k3]*SU3F[I4, k2, k3])) +
	SU3D[I1, k2, k3]*((I/2)*SU3D[6, I3, k1]*SU3D[I2, k1, k2]*
		SU3D[I4, I5, k3] + (I/2)*SU3D[6, I2, k1]*SU3D[I3, k1, k2]*
		SU3D[I4, I5, k3] + (SU3D[6, I3, k1]*SU3D[I4, I5, k3]*
		SU3F[I2, k1, k2])/2 + (SU3D[6, I2, k1]*SU3D[I4, I5, k3]*
		SU3F[I3, k1, k2])/2 + SU3D[6, I3, k1]*SU3D[I2, I5, k3]*
		((-I/2)*SU3D[I4, k1, k2] - SU3F[I4, k1, k2]/2) +
	SU3D[6, I2, k1]*SU3D[I3, I5, k3]*((-I/2)*SU3D[I4, k1, k2] -
		SU3F[I4, k1, k2]/2) + SU3D[6, I3, k1]*SU3D[I2, I4, k3]*
		((I/2)*SU3D[I5, k1, k2] + SU3F[I5, k1, k2]/2) +
	SU3D[6, I2, k1]*SU3D[I3, I4, k3]*((I/2)*SU3D[I5, k1, k2] +
		SU3F[I5, k1, k2]/2) + SU3D[6, I4, k1]*
		((-I/2)*SU3D[I2, k1, k3]*SU3D[I3, I5, k2] - (I/2)*SU3D[I2, I5, k2]*
		SU3D[I3, k1, k3] - (I/2)*SU3D[I2, I3, k2]*SU3D[I5, k1, k3] -
		(SU3D[I3, I5, k3]*SU3F[I2, k1, k2])/2 -
		(SU3D[I2, I5, k3]*SU3F[I3, k1, k2])/2 -
		(SU3D[I2, I3, k3]*SU3F[I5, k1, k2])/2)) +
	SU3D[I4, k2, k3]*(-(SU3D[I2, I3, k1]*SU3D[I5, k1, k3]*SU3F[6, I1, k2])/
		6 + SU3D[I3, I5, k1]*((I/2)*SU3F[6, I2, k2]*SU3F[I1, k1, k3] -
		(I/6)*SU3F[6, I1, k2]*SU3F[I2, k1, k3]) + SU3D[I2, I5, k1]*
		((I/2)*SU3F[6, I3, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I3, k1, k3]) + SU3D[I2, I3, k1]*
		((I/2)*SU3F[6, I5, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I5, k1, k3])) + SU3D[I3, k2, k3]*
	(SU3D[I5, k1, k3]*(-(SU3D[I2, I4, k1]*SU3F[6, I1, k2])/6 +
		(SU3D[I1, I4, k1]*SU3F[6, I2, k2])/4 -
		(SU3D[I1, I2, k1]*SU3F[6, I4, k2])/6) + SU3D[I4, k1, k3]*
		((SU3D[I2, I5, k1]*SU3F[6, I1, k2])/6 -
		(SU3D[I1, I5, k1]*SU3F[6, I2, k2])/4 -
		(SU3D[I1, I2, k1]*SU3F[6, I5, k2])/4) -
	(SU3D[6, I2, k1]*SU3D[I4, I5, k3]*SU3F[I1, k1, k2])/3 +
	SU3D[I2, I5, k1]*((I/2)*SU3F[6, I4, k2]*SU3F[I1, k1, k3] +
		(I/6)*SU3F[6, I1, k2]*SU3F[I4, k1, k3]) + SU3D[I1, I5, k1]*
		((-I/6)*SU3F[6, I4, k2]*SU3F[I2, k1, k3] - (I/4)*SU3F[6, I2, k2]*
		SU3F[I4, k1, k3]) + SU3D[I2, I4, k1]*
		((-I/2)*SU3F[6, I5, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I4, k1]*
		((I/4)*SU3F[6, I5, k2]*SU3F[I2, k1, k3] + (I/4)*SU3F[6, I2, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I2, k1]*
		((-I/4)*SU3F[6, I5, k2]*SU3F[I4, k1, k3] - (I/6)*SU3F[6, I4, k2]*
		SU3F[I5, k1, k3]) + SU3D[6, I2, k1]*
		((SU3D[I5, k1, k2]*SU3F[I1, I4, k3])/12 -
		(SU3D[I4, k1, k2]*SU3F[I1, I5, k3])/3 + (I/3)*SU3F[I1, I5, k2]*
		SU3F[I4, k1, k3] - (I/12)*SU3F[I1, I4, k2]*SU3F[I5, k1, k3]) +
	SU3D[6, I1, k1]*((I/6)*SU3D[I2, I4, k2]*SU3D[I5, k1, k3] +
		(SU3D[I5, k1, k2]*SU3F[I2, I4, k3])/6 +
		(SU3D[I4, I5, k3]*SU3F[I2, k1, k2])/6 + (I/6)*SU3F[I2, k1, k3]*
		SU3F[I4, I5, k2] + (SU3D[I2, I4, k2]*SU3F[I5, k1, k3])/6 -
		(I/6)*SU3F[I2, I4, k2]*SU3F[I5, k1, k3])) +
	SU3D[I2, k2, k3]*(SU3D[I5, k1, k3]*((SU3D[I1, I4, k1]*SU3F[6, I3, k2])/
		4 - (SU3D[I1, I3, k1]*SU3F[6, I4, k2])/6) +
	SU3D[I4, k1, k3]*(-(SU3D[I1, I5, k1]*SU3F[6, I3, k2])/4 -
		(SU3D[I1, I3, k1]*SU3F[6, I5, k2])/4) + SU3D[I3, k1, k3]*
		((I/6)*SU3D[6, I1, k1]*SU3D[I4, I5, k2] -
		(SU3D[I1, I5, k1]*SU3F[6, I4, k2])/6 +
		(SU3D[I1, I4, k1]*SU3F[6, I5, k2])/4) -
	(SU3D[6, I1, k1]*SU3D[I3, k1, k2]*SU3F[I4, I5, k3])/6 +
	SU3D[6, I1, k1]*SU3D[I3, I5, k3]*((I/6)*SU3D[I4, k1, k2] +
		SU3F[I4, k1, k2]/6) + SU3D[I1, I5, k1]*
		((-I/6)*SU3F[6, I4, k2]*SU3F[I3, k1, k3] - (I/4)*SU3F[6, I3, k2]*
		SU3F[I4, k1, k3]) + SU3D[6, I3, k1]*SU3D[I1, I4, k2]*
		((-I/4)*SU3D[I5, k1, k3] - SU3F[I5, k1, k3]/4) +
	SU3D[I1, I4, k1]*((I/4)*SU3F[6, I5, k2]*SU3F[I3, k1, k3] +
		(I/4)*SU3F[6, I3, k2]*SU3F[I5, k1, k3]) + SU3D[I1, I3, k1]*
		((-I/4)*SU3F[6, I5, k2]*SU3F[I4, k1, k3] - (I/6)*SU3F[6, I4, k2]*
		SU3F[I5, k1, k3]) + SU3D[6, I4, k1]*
		((I/6)*SU3D[I1, I5, k2]*SU3D[I3, k1, k3] -
		(SU3D[I5, k1, k2]*SU3F[I1, I3, k3])/6 -
		(SU3D[I3, k1, k2]*SU3F[I1, I5, k3])/6 +
		(SU3D[I3, I5, k3]*SU3F[I1, k1, k2])/3 +
		(SU3D[I1, I5, k2]*SU3F[I3, k1, k3])/6 + (I/6)*SU3F[I1, I5, k2]*
		SU3F[I3, k1, k3] + SU3D[I1, I3, k2]*((I/6)*SU3D[I5, k1, k3] +
		SU3F[I5, k1, k3]/6) + (I/6)*SU3F[I1, I3, k2]*SU3F[I5, k1, k3]) +
	SU3D[6, I3, k1]*((SU3D[I5, k1, k2]*SU3F[I1, I4, k3])/12 -
		(SU3D[I4, k1, k2]*SU3F[I1, I5, k3])/3 -
		(SU3D[I4, I5, k3]*SU3F[I1, k1, k2])/3 + (I/3)*SU3F[I1, I5, k2]*
		SU3F[I4, k1, k3] - (I/12)*SU3F[I1, I4, k2]*SU3F[I5, k1, k3]) +
	SU3D[6, I1, k1]*((I/6)*SU3D[I3, I4, k2]*SU3D[I5, k1, k3] +
		(SU3D[I5, k1, k2]*SU3F[I3, I4, k3])/6 +
		(SU3D[I4, I5, k3]*SU3F[I3, k1, k2])/6 + (I/6)*SU3F[I3, k1, k3]*
		SU3F[I4, I5, k2] - (I/6)*SU3F[I3, I4, k2]*SU3F[I5, k1, k3])) +
	SU3D[I3, k1, k3]*(SU3D[6, I2, k1]*SU3D[I1, I5, k2]*
		((I/4)*SU3D[I4, k2, k3] - SU3F[I4, k2, k3]/4) +
	SU3D[6, I1, k1]*SU3D[I2, I4, k2]*((I/6)*SU3D[I5, k2, k3] -
		SU3F[I5, k2, k3]/6) + SU3D[6, I2, k1]*SU3D[I1, I4, k2]*
		((-I/4)*SU3D[I5, k2, k3] + SU3F[I5, k2, k3]/4)) +
	SU3D[I2, k1, k3]*(SU3D[6, I3, k1]*SU3D[I1, I5, k2]*
		((I/4)*SU3D[I4, k2, k3] - SU3F[I4, k2, k3]/4) +
	SU3D[6, I3, k1]*SU3D[I1, I4, k2]*((-I/4)*SU3D[I5, k2, k3] +
		SU3F[I5, k2, k3]/4)) + SU3D[I3, I4, k3]*
	((SU3D[6, I1, k1]*SU3D[I2, k2, k3]*SU3F[I5, k1, k2])/6 +
	SU3D[I1, k1, k2]*((SU3D[I5, k2, k3]*SU3F[6, I2, k1])/3 +
		(SU3D[I2, k2, k3]*SU3F[6, I5, k1])/3 - (I/3)*SU3F[6, I5, k1]*
		SU3F[I2, k2, k3] + SU3D[6, I2, k1]*((-I/3)*SU3D[I5, k2, k3] -
		SU3F[I5, k2, k3]/3) - (I/3)*SU3F[6, I2, k1]*SU3F[I5, k2, k3])) +
	SU3D[I1, k1, k2]*((SU3D[I3, I5, k2]*SU3D[I4, k1, k3]*SU3F[6, I2, k3])/
		2 + SU3D[I5, k1, k3]*(-(SU3D[I3, I4, k2]*SU3F[6, I2, k3])/2 -
		(SU3D[I2, I4, k2]*SU3F[6, I3, k3])/2) + SU3D[I3, k2, k3]*
		(SU3D[I4, I5, k3]*((-I/3)*SU3D[6, I2, k1] + SU3F[6, I2, k1]/3) -
		(SU3D[I2, I5, k3]*SU3F[6, I4, k1])/3) + SU3D[I2, k2, k3]*
		((I/3)*SU3D[6, I4, k1]*SU3D[I3, I5, k3] - (I/3)*SU3D[6, I3, k1]*
		SU3D[I4, I5, k3] + (SU3D[I4, I5, k3]*SU3F[6, I3, k1])/3 -
		(SU3D[I3, I5, k3]*SU3F[6, I4, k1])/3) +
	(SU3D[I2, I3, k2]*SU3D[I5, k1, k3]*SU3F[6, I4, k3])/2 +
	SU3D[I2, I5, k2]*((SU3D[I4, k1, k3]*SU3F[6, I3, k3])/2 +
		(SU3D[I3, k1, k3]*SU3F[6, I4, k3])/2) +
	(SU3D[I2, I3, k2]*SU3D[I4, k1, k3]*SU3F[6, I5, k3])/2 +
	SU3D[I3, k1, k3]*(-(SU3D[I4, I5, k2]*SU3F[6, I2, k3])/2 -
		(SU3D[I2, I4, k2]*SU3F[6, I5, k3])/2) + SU3D[I2, k1, k3]*
		(-(SU3D[I4, I5, k2]*SU3F[6, I3, k3])/2 +
		(SU3D[I3, I5, k2]*SU3F[6, I4, k3])/2 -
		(SU3D[I3, I4, k2]*SU3F[6, I5, k3])/2) -
	(SU3D[6, I3, k1]*SU3D[I4, I5, k3]*SU3F[I2, k2, k3])/3 +
	SU3D[I4, I5, k3]*((-I/3)*SU3F[6, I3, k1]*SU3F[I2, k2, k3] -
		(SU3D[6, I2, k1]*SU3F[I3, k2, k3])/3 - (I/3)*SU3F[6, I2, k1]*
		SU3F[I3, k2, k3]) + SU3D[I4, I5, k1]*
		((-I/2)*SU3F[6, I3, k3]*SU3F[I2, k2, k3] - (I/2)*SU3F[6, I2, k3]*
		SU3F[I3, k2, k3]) + SU3D[I3, I5, k3]*
		((SU3D[I4, k2, k3]*SU3F[6, I2, k1])/3 + (I/3)*SU3F[6, I4, k1]*
		SU3F[I2, k2, k3] + SU3D[6, I2, k1]*((-I/3)*SU3D[I4, k2, k3] -
		SU3F[I4, k2, k3]/3) - (I/3)*SU3F[6, I2, k1]*SU3F[I4, k2, k3]) +
	SU3D[I3, I5, k1]*((I/2)*SU3F[6, I4, k3]*SU3F[I2, k2, k3] +
		(I/2)*SU3F[6, I2, k3]*SU3F[I4, k2, k3]) + SU3D[I2, I5, k3]*
		((SU3D[I4, k2, k3]*SU3F[6, I3, k1])/3 + (I/3)*SU3F[6, I4, k1]*
		SU3F[I3, k2, k3] + SU3D[6, I3, k1]*((-I/3)*SU3D[I4, k2, k3] -
		SU3F[I4, k2, k3]/3) - (I/3)*SU3F[6, I3, k1]*SU3F[I4, k2, k3]) +
	SU3D[I2, I5, k1]*((I/2)*SU3F[6, I4, k3]*SU3F[I3, k2, k3] +
		(I/2)*SU3F[6, I3, k3]*SU3F[I4, k2, k3]) + SU3D[6, I4, k1]*
		((I/3)*SU3D[I2, I5, k3]*SU3D[I3, k2, k3] +
		(SU3D[I3, I5, k3]*SU3F[I2, k2, k3])/3 +
		(SU3D[I2, I5, k3]*SU3F[I3, k2, k3])/3 + SU3D[I2, I3, k3]*
		((I/3)*SU3D[I5, k2, k3] + SU3F[I5, k2, k3]/3)) +
	SU3D[I3, I4, k1]*((-I/2)*SU3F[6, I5, k3]*SU3F[I2, k2, k3] -
		(I/2)*SU3F[6, I2, k3]*SU3F[I5, k2, k3]) + SU3D[I2, I4, k3]*
		((SU3D[I5, k2, k3]*SU3F[6, I3, k1])/3 +
		(SU3D[I3, k2, k3]*SU3F[6, I5, k1])/3 - (I/3)*SU3F[6, I5, k1]*
		SU3F[I3, k2, k3] + SU3D[6, I3, k1]*((-I/3)*SU3D[I5, k2, k3] -
		SU3F[I5, k2, k3]/3) - (I/3)*SU3F[6, I3, k1]*SU3F[I5, k2, k3]) +
	SU3D[I2, I4, k1]*((-I/2)*SU3F[6, I5, k3]*SU3F[I3, k2, k3] -
		(I/2)*SU3F[6, I3, k3]*SU3F[I5, k2, k3]) + SU3D[I2, I3, k3]*
		(-(SU3D[I5, k2, k3]*SU3F[6, I4, k1])/3 +
		(SU3D[I4, k2, k3]*SU3F[6, I5, k1])/3 - (I/3)*SU3F[6, I5, k1]*
		SU3F[I4, k2, k3] + (I/3)*SU3F[6, I4, k1]*SU3F[I5, k2, k3]) +
	SU3D[I2, I3, k1]*((I/2)*SU3F[6, I5, k3]*SU3F[I4, k2, k3] +
		(I/2)*SU3F[6, I4, k3]*SU3F[I5, k2, k3])) +
	SU3D[I4, k1, k2]*(SU3D[I5, k2, k3]*((SU3D[I2, I3, k1]*SU3F[6, I1, k3])/
		6 - (SU3D[I1, I3, k1]*SU3F[6, I2, k3])/4 -
		(SU3D[I1, I2, k1]*SU3F[6, I3, k3])/4 - (I/12)*SU3F[6, I3, k3]*
		SU3F[I1, I2, k1] - (I/12)*SU3F[6, I2, k3]*SU3F[I1, I3, k1]) +
	SU3D[I5, k1, k3]*((-I/3)*SU3F[6, I3, k2]*SU3F[I1, I2, k3] -
		(I/3)*SU3F[6, I2, k2]*SU3F[I1, I3, k3]) + SU3D[I3, I5, k1]*
		((I/3)*SU3F[6, I2, k3]*SU3F[I1, k2, k3] + (I/6)*SU3F[6, I1, k3]*
		SU3F[I2, k2, k3]) + SU3F[6, I5, k2]*
		(-(SU3F[I1, I3, k3]*SU3F[I2, k1, k3])/3 -
		(SU3F[I1, I2, k3]*SU3F[I3, k1, k3])/3) + SU3D[I2, I5, k1]*
		((I/3)*SU3F[6, I3, k3]*SU3F[I1, k2, k3] + (I/6)*SU3F[6, I1, k3]*
		SU3F[I3, k2, k3]) + SU3D[I1, I5, k1]*
		((-I/4)*SU3F[6, I3, k3]*SU3F[I2, k2, k3] - (I/4)*SU3F[6, I2, k3]*
		SU3F[I3, k2, k3]) + SU3F[6, I5, k3]*
		((SU3F[I1, I3, k1]*SU3F[I2, k2, k3])/12 +
		(SU3F[I1, I2, k1]*SU3F[I3, k2, k3])/12) + SU3F[6, I3, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I2, k1, k3])/3 -
		(SU3F[I1, I2, k3]*SU3F[I5, k1, k3])/3) + SU3F[6, I2, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I3, k1, k3])/3 -
		(SU3F[I1, I3, k3]*SU3F[I5, k1, k3])/3) + SU3D[I2, I3, k1]*
		((I/3)*SU3F[6, I5, k3]*SU3F[I1, k2, k3] + (I/6)*SU3F[6, I1, k3]*
		SU3F[I5, k2, k3]) + SU3D[I1, I3, k1]*
		((-I/4)*SU3F[6, I5, k3]*SU3F[I2, k2, k3] - (I/4)*SU3F[6, I2, k3]*
		SU3F[I5, k2, k3]) + SU3D[I1, I2, k1]*
		((-I/4)*SU3F[6, I5, k3]*SU3F[I3, k2, k3] - (I/4)*SU3F[6, I3, k3]*
		SU3F[I5, k2, k3]) + SU3F[6, I3, k3]*
		((SU3F[I1, I5, k1]*SU3F[I2, k2, k3])/12 +
		(SU3F[I1, I2, k1]*SU3F[I5, k2, k3])/12) + SU3F[6, I2, k3]*
		((SU3F[I1, I5, k1]*SU3F[I3, k2, k3])/12 +
		(SU3F[I1, I3, k1]*SU3F[I5, k2, k3])/12)) +
	SU3D[I3, k1, k2]*(SU3D[I4, k2, k3]*(-(SU3D[I2, I5, k1]*SU3F[6, I1, k3])/
		6 - (I/3)*SU3F[6, I5, k3]*SU3F[I1, I2, k1] - (I/3)*SU3F[6, I2, k3]*
		SU3F[I1, I5, k1]) + SU3D[I4, k1, k3]*
		((-I/12)*SU3F[6, I5, k2]*SU3F[I1, I2, k3] - (I/12)*SU3F[6, I2, k2]*
		SU3F[I1, I5, k3]) + SU3D[I5, k2, k3]*
		(-(SU3D[I2, I4, k1]*SU3F[6, I1, k3])/6 +
		(SU3D[I1, I4, k1]*SU3F[6, I2, k3])/4 -
		(SU3D[I1, I2, k1]*SU3F[6, I4, k3])/6 - (I/6)*SU3F[6, I4, k3]*
		SU3F[I1, I2, k1] + (I/12)*SU3F[6, I2, k3]*SU3F[I1, I4, k1] +
		(I/6)*SU3F[6, I1, k3]*SU3F[I2, I4, k1]) + SU3D[I5, k1, k3]*
		((-I/6)*SU3F[6, I4, k2]*SU3F[I1, I2, k3] + (I/12)*SU3F[6, I2, k2]*
		SU3F[I1, I4, k3] + (I/6)*SU3F[6, I1, k2]*SU3F[I2, I4, k3]) -
	(I/6)*SU3D[I1, I5, k1]*SU3F[6, I4, k3]*SU3F[I2, k2, k3] +
	SU3D[I4, I5, k3]*((SU3D[6, I2, k1]*SU3F[I1, k2, k3])/2 +
		(I/2)*SU3F[6, I2, k1]*SU3F[I1, k2, k3] + (I/6)*SU3F[6, I1, k1]*
		SU3F[I2, k2, k3]) + SU3D[I4, I5, k1]*
		((I/3)*SU3F[6, I2, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I2, k2, k3]) + SU3F[6, I5, k2]*
		((SU3F[I1, I4, k3]*SU3F[I2, k1, k3])/12 -
		(SU3F[I1, I2, k3]*SU3F[I4, k1, k3])/12) + SU3D[I2, I5, k1]*
		((-I/3)*SU3F[6, I4, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I4, k2, k3]) + SU3F[6, I5, k3]*
		(-(SU3F[I1, I4, k1]*SU3F[I2, k2, k3])/12 +
		(SU3F[I1, I2, k1]*SU3F[I4, k2, k3])/3) + SU3F[6, I4, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I2, k1, k3])/6 -
		(SU3F[I1, I2, k3]*SU3F[I5, k1, k3])/6) + SU3F[6, I2, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I4, k1, k3])/12 +
		(SU3F[I1, I4, k3]*SU3F[I5, k1, k3])/12) + SU3F[6, I1, k2]*
		(-(SU3F[I2, k1, k3]*SU3F[I4, I5, k3])/6 +
		(SU3F[I2, I4, k3]*SU3F[I5, k1, k3])/6) - (I/6)*SU3D[I1, I2, k1]*
		SU3F[6, I4, k3]*SU3F[I5, k2, k3] + SU3D[I2, I4, k1]*
		((I/3)*SU3F[6, I5, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I5, k2, k3]) + SU3D[I1, I4, k1]*
		((I/4)*SU3F[6, I5, k3]*SU3F[I2, k2, k3] + (I/4)*SU3F[6, I2, k3]*
		SU3F[I5, k2, k3]) + SU3F[6, I4, k3]*
		((SU3F[I1, I5, k1]*SU3F[I2, k2, k3])/6 +
		(SU3F[I1, I2, k1]*SU3F[I5, k2, k3])/6) + SU3F[6, I2, k3]*
		((SU3F[I1, I5, k1]*SU3F[I4, k2, k3])/3 -
		(SU3F[I1, I4, k1]*SU3F[I5, k2, k3])/12) + SU3D[6, I2, k1]*
		((SU3D[I5, k2, k3]*SU3F[I1, I4, k3])/12 -
		(SU3D[I4, k2, k3]*SU3F[I1, I5, k3])/12 + (I/12)*SU3F[I1, I5, k3]*
		SU3F[I4, k2, k3] - (I/12)*SU3F[I1, I4, k3]*SU3F[I5, k2, k3]) +
	SU3F[6, I1, k3]*((SU3F[I2, k2, k3]*SU3F[I4, I5, k1])/6 -
		(SU3F[I2, I4, k1]*SU3F[I5, k2, k3])/6) + SU3D[6, I1, k1]*
		((SU3D[I5, k2, k3]*SU3F[I2, I4, k3])/6 +
		(SU3D[I4, I5, k3]*SU3F[I2, k2, k3])/6 + (I/6)*SU3F[I2, k2, k3]*
		SU3F[I4, I5, k3] - (I/6)*SU3F[I2, I4, k3]*SU3F[I5, k2, k3])) +
	SU3D[I2, k1, k2]*(-(SU3D[I3, I5, k2]*SU3D[I4, k1, k3]*SU3F[6, I1, k3])/
		6 + SU3D[I4, k2, k3]*((-I/3)*SU3F[6, I5, k3]*SU3F[I1, I3, k1] -
		(I/3)*SU3F[6, I3, k3]*SU3F[I1, I5, k1]) + SU3D[I4, k1, k3]*
		((-I/12)*SU3F[6, I5, k2]*SU3F[I1, I3, k3] - (I/12)*SU3F[6, I3, k2]*
		SU3F[I1, I5, k3]) + SU3D[I5, k2, k3]*
		((SU3D[I1, I4, k1]*SU3F[6, I3, k3])/4 -
		(SU3D[I1, I3, k1]*SU3F[6, I4, k3])/6 - (I/6)*SU3F[6, I4, k3]*
		SU3F[I1, I3, k1] + (I/12)*SU3F[6, I3, k3]*SU3F[I1, I4, k1] +
		(I/6)*SU3F[6, I1, k3]*SU3F[I3, I4, k1]) + SU3D[I5, k1, k3]*
		(-(SU3D[I3, I4, k2]*SU3F[6, I1, k3])/6 - (I/6)*SU3F[6, I4, k2]*
		SU3F[I1, I3, k3] + (I/12)*SU3F[6, I3, k2]*SU3F[I1, I4, k3] +
		(I/6)*SU3F[6, I1, k2]*SU3F[I3, I4, k3]) - (I/6)*SU3D[I1, I5, k1]*
		SU3F[6, I4, k3]*SU3F[I3, k2, k3] + SU3D[I4, I5, k3]*
		((I/2)*SU3F[6, I3, k1]*SU3F[I1, k2, k3] + (I/6)*SU3F[6, I1, k1]*
		SU3F[I3, k2, k3]) + SU3D[I4, I5, k1]*
		((I/3)*SU3F[6, I3, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I3, k2, k3]) + SU3D[I3, k2, k3]*
		(-(SU3D[I4, I5, k3]*SU3F[6, I1, k1])/6 -
		(SU3D[I1, I5, k1]*SU3F[6, I4, k3])/6 +
		(SU3D[I1, I4, k1]*SU3F[6, I5, k3])/4 + (I/12)*SU3F[6, I5, k3]*
		SU3F[I1, I4, k1] - (I/6)*SU3F[6, I4, k3]*SU3F[I1, I5, k1] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I4, I5, k1] + SU3D[6, I1, k1]*
		((I/6)*SU3D[I4, I5, k3] - SU3F[I4, I5, k3]/6)) +
	SU3D[I3, k1, k3]*(-(SU3D[I4, I5, k2]*SU3F[6, I1, k3])/6 +
		(I/12)*SU3F[6, I5, k2]*SU3F[I1, I4, k3] - (I/6)*SU3F[6, I4, k2]*
		SU3F[I1, I5, k3] - (I/6)*SU3F[6, I1, k2]*SU3F[I4, I5, k3]) +
	SU3F[6, I5, k2]*((SU3F[I1, I4, k3]*SU3F[I3, k1, k3])/12 -
		(SU3F[I1, I3, k3]*SU3F[I4, k1, k3])/12) + SU3D[I3, I5, k3]*
		((SU3D[I4, k2, k3]*SU3F[6, I1, k1])/6 - (I/2)*SU3F[6, I4, k1]*
		SU3F[I1, k2, k3] + SU3D[6, I1, k1]*((-I/6)*SU3D[I4, k2, k3] -
		SU3F[I4, k2, k3]/6) - (I/6)*SU3F[6, I1, k1]*SU3F[I4, k2, k3]) +
	SU3D[I3, I5, k1]*((-I/3)*SU3F[6, I4, k3]*SU3F[I1, k2, k3] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I4, k2, k3]) + SU3F[6, I5, k3]*
		(-(SU3F[I1, I4, k1]*SU3F[I3, k2, k3])/12 +
		(SU3F[I1, I3, k1]*SU3F[I4, k2, k3])/3) + SU3F[6, I4, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I3, k1, k3])/6 -
		(SU3F[I1, I3, k3]*SU3F[I5, k1, k3])/6) + SU3F[6, I3, k2]*
		(-(SU3F[I1, I5, k3]*SU3F[I4, k1, k3])/12 +
		(SU3F[I1, I4, k3]*SU3F[I5, k1, k3])/12) + SU3F[6, I1, k2]*
		(-(SU3F[I3, k1, k3]*SU3F[I4, I5, k3])/6 +
		(SU3F[I3, I4, k3]*SU3F[I5, k1, k3])/6) - (I/6)*SU3D[I1, I3, k1]*
		SU3F[6, I4, k3]*SU3F[I5, k2, k3] + SU3D[I3, I4, k3]*
		(-(SU3D[I5, k2, k3]*SU3F[6, I1, k1])/6 + (I/2)*SU3F[6, I5, k1]*
		SU3F[I1, k2, k3] + SU3D[6, I1, k1]*((I/6)*SU3D[I5, k2, k3] +
		SU3F[I5, k2, k3]/6) + (I/6)*SU3F[6, I1, k1]*SU3F[I5, k2, k3]) +
	SU3D[I3, I4, k1]*((I/3)*SU3F[6, I5, k3]*SU3F[I1, k2, k3] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I5, k2, k3]) + SU3D[I1, I4, k1]*
		((I/4)*SU3F[6, I5, k3]*SU3F[I3, k2, k3] + (I/4)*SU3F[6, I3, k3]*
		SU3F[I5, k2, k3]) + SU3F[6, I4, k3]*
		((SU3F[I1, I5, k1]*SU3F[I3, k2, k3])/6 +
		(SU3F[I1, I3, k1]*SU3F[I5, k2, k3])/6) + SU3D[6, I4, k1]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, I3, k3])/6 -
		(SU3D[I3, k2, k3]*SU3F[I1, I5, k3])/6 -
		(SU3D[I3, I5, k3]*SU3F[I1, k2, k3])/2 + (I/6)*SU3F[I1, I5, k3]*
		SU3F[I3, k2, k3] + (I/6)*SU3F[I1, I3, k3]*SU3F[I5, k2, k3]) +
	SU3F[6, I3, k3]*((SU3F[I1, I5, k1]*SU3F[I4, k2, k3])/3 -
		(SU3F[I1, I4, k1]*SU3F[I5, k2, k3])/12) + SU3D[6, I3, k1]*
		((SU3D[I5, k2, k3]*SU3F[I1, I4, k3])/12 -
		(SU3D[I4, k2, k3]*SU3F[I1, I5, k3])/12 +
		(SU3D[I4, I5, k3]*SU3F[I1, k2, k3])/2 + (I/12)*SU3F[I1, I5, k3]*
		SU3F[I4, k2, k3] - (I/12)*SU3F[I1, I4, k3]*SU3F[I5, k2, k3]) +
	SU3F[6, I1, k3]*((SU3F[I3, k2, k3]*SU3F[I4, I5, k1])/6 -
		(SU3F[I3, I4, k1]*SU3F[I5, k2, k3])/6) + SU3D[6, I1, k1]*
		((SU3D[I5, k2, k3]*SU3F[I3, I4, k3])/6 +
		(SU3D[I4, I5, k3]*SU3F[I3, k2, k3])/6 + (I/6)*SU3F[I3, k2, k3]*
		SU3F[I4, I5, k3] - (I/6)*SU3F[I3, I4, k3]*SU3F[I5, k2, k3])) +
	SU3D[I1, I4, k2]*(SU3D[6, I2, k1]*SU3D[I3, k2, k3]*
		((-I/4)*SU3D[I5, k1, k3] - SU3F[I5, k1, k3]/4) +
	SU3D[6, I3, k1]*(-(SU3D[I5, k2, k3]*SU3F[I2, k1, k3])/4 +
		(SU3D[I5, k1, k3]*SU3F[I2, k2, k3])/4 - (I/4)*SU3F[I2, k2, k3]*
		SU3F[I5, k1, k3] - (I/4)*SU3F[I2, k1, k3]*SU3F[I5, k2, k3]) +
	SU3D[6, I2, k1]*(-(SU3D[I5, k2, k3]*SU3F[I3, k1, k3])/4 +
		(SU3D[I5, k1, k3]*SU3F[I3, k2, k3])/4 - (I/4)*SU3F[I3, k2, k3]*
		SU3F[I5, k1, k3] - (I/4)*SU3F[I3, k1, k3]*SU3F[I5, k2, k3])) +
	SU3F[I1, I5, k1]*((I/6)*SU3F[I3, I4, k1]*SUNDelta[6, I2] +
	(I/6)*SU3F[I2, I4, k1]*SUNDelta[6, I3]) + SU3F[I1, I3, k1]*
	((-I/6)*SU3F[I4, I5, k1]*SUNDelta[6, I2] + (I/6)*SU3F[I2, I4, k1]*
		SUNDelta[6, I5]) + SU3F[I1, I2, k1]*
	((-I/6)*SU3F[I4, I5, k1]*SUNDelta[6, I3] + (I/6)*SU3F[I3, I4, k1]*
		SUNDelta[6, I5]) + SU3D[I4, I5, k1]*
	(SU3F[6, I3, k2]*((SU3F[I1, k2, k3]*SU3F[I2, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I2, k2, k3])/2) + SU3F[6, I2, k2]*
		((SU3F[I1, k2, k3]*SU3F[I3, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I3, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I3, k2, k3])/6) +
	(5*SU3F[I1, I3, k1]*SUNDelta[6, I2])/18 +
	(5*SU3F[I1, I2, k1]*SUNDelta[6, I3])/18 -
	(SU3F[6, I3, k1]*SUNDelta[I1, I2])/6 -
	(SU3F[6, I2, k1]*SUNDelta[I1, I3])/6) + SU3D[I3, I4, k1]*
	(SU3F[6, I5, k2]*((SU3F[I1, k2, k3]*SU3F[I2, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I2, k2, k3])/2) + SU3F[6, I2, k2]*
		((SU3F[I1, k2, k3]*SU3F[I5, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I5, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I5, k2, k3])/6) +
	(5*SU3F[I1, I5, k1]*SUNDelta[6, I2])/18 +
	(5*SU3F[I1, I2, k1]*SUNDelta[6, I5])/18 -
	(SU3F[6, I5, k1]*SUNDelta[I1, I2])/6 -
	(SU3F[6, I2, k1]*SUNDelta[I1, I5])/6) + SU3D[I2, I4, k1]*
	(SU3F[6, I5, k2]*((SU3F[I1, k2, k3]*SU3F[I3, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I3, k2, k3])/2) + SU3F[6, I3, k2]*
		((SU3F[I1, k2, k3]*SU3F[I5, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I5, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/6) + ((2*I)/9)*SU3D[I3, I5, k1]*
		SUNDelta[6, I1] + ((5*I)/18)*SU3D[I1, I5, k1]*SUNDelta[6, I3] +
	(5*SU3F[I1, I5, k1]*SUNDelta[6, I3])/18 + ((5*I)/18)*SU3D[I1, I3, k1]*
		SUNDelta[6, I5] + (5*SU3F[I1, I3, k1]*SUNDelta[6, I5])/18 -
	(SU3F[6, I5, k1]*SUNDelta[I1, I3])/6 -
	(SU3F[6, I3, k1]*SUNDelta[I1, I5])/6) + SU3D[I3, I5, k1]*
	(SU3F[6, I4, k2]*(-(SU3F[I1, k2, k3]*SU3F[I2, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I2, k2, k3])/2) + SU3F[6, I2, k2]*
		((SU3F[I1, k2, k3]*SU3F[I4, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I4, k2, k3])/2) + SU3F[6, I1, k2]*
		((SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I4, k2, k3])/6) +
	(4*SU3F[I2, I4, k1]*SUNDelta[6, I1])/9 -
	(7*SU3F[I1, I2, k1]*SUNDelta[6, I4])/9 -
	(2*SU3F[6, I4, k1]*SUNDelta[I1, I2])/9 -
	(2*SU3F[6, I1, k1]*SUNDelta[I2, I4])/9) + SU3D[I2, I5, k1]*
	(SU3F[6, I4, k2]*(-(SU3F[I1, k2, k3]*SU3F[I3, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I3, k2, k3])/2) + SU3F[6, I3, k2]*
		((SU3F[I1, k2, k3]*SU3F[I4, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I4, k2, k3])/2) + SU3F[6, I1, k2]*
		((SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/6) + ((2*I)/9)*SU3D[I3, I4, k1]*
		SUNDelta[6, I1] + (4*SU3F[I3, I4, k1]*SUNDelta[6, I1])/9 -
	((8*I)/9)*SU3D[I1, I4, k1]*SUNDelta[6, I3] + (I/9)*SU3D[I1, I3, k1]*
		SUNDelta[6, I4] - (7*SU3F[I1, I3, k1]*SUNDelta[6, I4])/9 -
	(2*SU3F[6, I4, k1]*SUNDelta[I1, I3])/9 -
	(2*SU3F[6, I1, k1]*SUNDelta[I3, I4])/9) + SU3D[I1, I5, k1]*
	(SU3F[6, I4, k2]*(-(SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I3, k2, k3])/6) -
	(SU3F[6, I3, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/4 -
	(SU3F[6, I2, k2]*SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/4 +
	((5*I)/18)*SU3D[I3, I4, k1]*SUNDelta[6, I2] -
	(SU3F[I3, I4, k1]*SUNDelta[6, I2])/6 -
	(SU3F[I2, I4, k1]*SUNDelta[6, I3])/6 +
	(SU3F[6, I4, k1]*SUNDelta[I2, I3])/9 -
	(SU3F[6, I3, k1]*SUNDelta[I2, I4])/9 -
	(SU3F[6, I2, k1]*SUNDelta[I3, I4])/9) + SU3F[6, I5, k1]*
	((I/12)*SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3] -
	(I/3)*SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3] -
	(I/3)*SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I4, k1, k3] -
	(I/12)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SU3F[I4, k2, k3] +
	SU3F[I2, k1, k3]*((I/12)*SU3F[I1, I4, k2]*SU3F[I3, k2, k3] -
		(I/12)*SU3F[I1, I3, k2]*SU3F[I4, k2, k3]) - (I/6)*SU3F[I3, I4, k1]*
		SUNDelta[I1, I2] - (I/6)*SU3F[I2, I4, k1]*SUNDelta[I1, I3] -
	(I/9)*SU3F[I1, I4, k1]*SUNDelta[I2, I3] + ((5*I)/9)*SU3F[I1, I3, k1]*
		SUNDelta[I2, I4] + ((5*I)/9)*SU3F[I1, I2, k1]*SUNDelta[I3, I4]) +
	SU3D[6, I5, k1]*((SU3D[I2, I3, k2]*SU3D[I4, k1, k3]*SU3F[I1, k2, k3])/
		2 + SU3D[I3, I4, k3]*(-(SU3D[I2, k2, k3]*SU3F[I1, k1, k2])/3 +
		SU3D[I1, k1, k2]*((-I/3)*SU3D[I2, k2, k3] - SU3F[I2, k2, k3]/3)) +
	SU3D[I3, I4, k2]*((I/2)*SU3F[I1, k2, k3]*SU3F[I2, k1, k3] -
		(I/3)*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]) +
	(SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/12 +
	SU3D[I4, k2, k3]*(-(SU3D[I2, I3, k2]*SU3F[I1, k1, k3])/3 +
		(SU3D[I1, I3, k2]*SU3F[I2, k1, k3])/4 + (I/12)*SU3F[I1, I3, k2]*
		SU3F[I2, k1, k3] + (SU3D[I1, I2, k2]*SU3F[I3, k1, k3])/4 +
		(I/12)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]) +
	SU3D[I4, k1, k2]*((I/3)*SU3F[I1, I3, k3]*SU3F[I2, k2, k3] +
		(I/3)*SU3F[I1, I2, k3]*SU3F[I3, k2, k3]) + SU3D[I2, I4, k2]*
		((I/2)*SU3F[I1, k2, k3]*SU3F[I3, k1, k3] - (I/3)*SU3F[I1, k1, k3]*
		SU3F[I3, k2, k3]) + SU3D[I1, I4, k2]*
		(-(SU3D[I3, k2, k3]*SU3F[I2, k1, k3])/4 - (I/4)*SU3F[I2, k2, k3]*
		SU3F[I3, k1, k3] - (I/4)*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]) +
	SU3D[I1, k2, k3]*((I/2)*SU3D[I2, k1, k2]*SU3D[I3, I4, k3] +
		(SU3D[I3, I4, k3]*SU3F[I2, k1, k2])/2 + SU3D[I2, I4, k3]*
		((I/2)*SU3D[I3, k1, k2] + SU3F[I3, k1, k2]/2) +
		SU3D[I2, I3, k3]*((-I/2)*SU3D[I4, k1, k2] - SU3F[I4, k1, k2]/2)) -
	(SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/3 -
	(SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/3 +
	SU3D[I3, k2, k3]*(-(SU3D[I4, k1, k2]*SU3F[I1, I2, k3])/3 -
		(SU3D[I2, I4, k2]*SU3F[I1, k1, k3])/3 - (I/12)*SU3F[I1, I4, k2]*
		SU3F[I2, k1, k3] + (I/3)*SU3F[I1, I2, k2]*SU3F[I4, k1, k3]) +
	SU3D[I2, k2, k3]*((-I/4)*SU3D[I1, I4, k2]*SU3D[I3, k1, k3] -
		(SU3D[I4, k1, k2]*SU3F[I1, I3, k3])/3 +
		(SU3D[I3, k1, k2]*SU3F[I1, I4, k3])/12 -
		(SU3D[I1, I4, k2]*SU3F[I3, k1, k3])/4 - (I/12)*SU3F[I1, I4, k2]*
		SU3F[I3, k1, k3] + (I/3)*SU3F[I1, I3, k2]*SU3F[I4, k1, k3]) +
	SU3D[I1, k1, k2]*(SU3D[I2, I4, k3]*((-I/3)*SU3D[I3, k2, k3] -
		SU3F[I3, k2, k3]/3) + SU3D[I2, I3, k3]*((-I/3)*SU3D[I4, k2, k3] -
		SU3F[I4, k2, k3]/3)) + (I/4)*SU3D[I1, I3, k2]*SU3F[I2, k1, k3]*
		SU3F[I4, k2, k3] + (I/4)*SU3D[I1, I2, k2]*SU3F[I3, k1, k3]*
		SU3F[I4, k2, k3] - (SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*
		SU3F[I4, k2, k3])/12 + SU3D[I3, k1, k3]*
		((I/4)*SU3D[I1, I2, k2]*SU3D[I4, k2, k3] -
		(SU3D[I2, I4, k2]*SU3F[I1, k2, k3])/2 +
		(SU3D[I1, I4, k2]*SU3F[I2, k2, k3])/4 -
		(SU3D[I1, I2, k2]*SU3F[I4, k2, k3])/4) + SU3D[I2, k1, k3]*
		((I/4)*SU3D[I1, I3, k2]*SU3D[I4, k2, k3] + SU3D[I1, I4, k2]*
		((-I/4)*SU3D[I3, k2, k3] + SU3F[I3, k2, k3]/4) -
		(SU3D[I1, I3, k2]*SU3F[I4, k2, k3])/4) + SU3D[I3, k1, k2]*
		(-(SU3D[I4, k2, k3]*SU3F[I1, I2, k3])/12 - (I/12)*SU3F[I1, I4, k3]*
		SU3F[I2, k2, k3] + (I/12)*SU3F[I1, I2, k3]*SU3F[I4, k2, k3]) +
	SU3F[I2, k1, k3]*((SU3F[I1, I4, k2]*SU3F[I3, k2, k3])/12 -
		(SU3F[I1, I3, k2]*SU3F[I4, k2, k3])/12) + SU3D[I2, k1, k2]*
		(-(SU3D[I4, k2, k3]*SU3F[I1, I3, k3])/12 +
		(SU3D[I3, k2, k3]*SU3F[I1, I4, k3])/12 +
		(SU3D[I3, I4, k3]*SU3F[I1, k2, k3])/2 - (I/12)*SU3F[I1, I4, k3]*
		SU3F[I3, k2, k3] + (I/12)*SU3F[I1, I3, k3]*SU3F[I4, k2, k3]) +
	SU3D[I2, I3, k2]*((-I/2)*SU3F[I1, k2, k3]*SU3F[I4, k1, k3] -
		(I/3)*SU3F[I1, k1, k3]*SU3F[I4, k2, k3]) + (I/6)*SU3D[I3, I4, k1]*
		SUNDelta[I1, I2] - (SU3F[I3, I4, k1]*SUNDelta[I1, I2])/6 +
	(I/6)*SU3D[I2, I4, k1]*SUNDelta[I1, I3] -
	(SU3F[I2, I4, k1]*SUNDelta[I1, I3])/6 - ((5*I)/9)*SU3D[I1, I4, k1]*
		SUNDelta[I2, I3] - (SU3F[I1, I4, k1]*SUNDelta[I2, I3])/9 +
	(I/9)*SU3D[I1, I3, k1]*SUNDelta[I2, I4] +
	(5*SU3F[I1, I3, k1]*SUNDelta[I2, I4])/9 + (I/9)*SU3D[I1, I2, k1]*
		SUNDelta[I3, I4] + (5*SU3F[I1, I2, k1]*SUNDelta[I3, I4])/9) +
	SUNDelta[6, I5]*(((-16*I)/27)*SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	((5*I)/27)*SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	((5*I)/27)*SUNDelta[I1, I2]*SUNDelta[I3, I4]) +
	SU3D[I1, I4, k1]*(SU3F[6, I5, k2]*((SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/
		4 + (SU3F[I2, k1, k3]*SU3F[I3, k2, k3])/4) +
	SU3F[6, I3, k2]*((SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/4 +
		(SU3F[I2, k1, k3]*SU3F[I5, k2, k3])/4) + SU3F[6, I2, k2]*
		((SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/4 +
		(SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/4) - ((8*I)/9)*SU3D[I3, I5, k1]*
		SUNDelta[6, I2] + (5*SU3F[6, I5, k1]*SUNDelta[I2, I3])/9 +
	(5*SU3F[6, I3, k1]*SUNDelta[I2, I5])/9 +
	(5*SU3F[6, I2, k1]*SUNDelta[I3, I5])/9) +
	SU3D[6, I4, k1]*(SU3D[I3, I5, k2]*((-I/2)*SU3F[I1, k2, k3]*
		SU3F[I2, k1, k3] + (I/3)*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]) -
	(SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/6 +
	SU3D[I5, k2, k3]*((I/6)*SU3F[I1, I3, k2]*SU3F[I2, k1, k3] +
		(I/6)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]) + SU3D[I5, k1, k2]*
		((I/6)*SU3F[I1, I3, k3]*SU3F[I2, k2, k3] + (I/6)*SU3F[I1, I2, k3]*
		SU3F[I3, k2, k3]) + SU3D[I2, I5, k2]*
		((SU3D[I3, k2, k3]*SU3F[I1, k1, k3])/3 +
		(SU3D[I3, k1, k3]*SU3F[I1, k2, k3])/2 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I3, k1, k3] + (I/3)*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]) +
	SU3D[I1, I5, k2]*((SU3D[I3, k2, k3]*SU3F[I2, k1, k3])/6 +
		(I/6)*SU3F[I2, k2, k3]*SU3F[I3, k1, k3] + (I/6)*SU3F[I2, k1, k3]*
		SU3F[I3, k2, k3]) - (SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*
		SU3F[I5, k1, k3])/6 - (SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*
		SU3F[I5, k1, k3])/6 + SU3D[I3, k2, k3]*
		(-(SU3D[I5, k1, k2]*SU3F[I1, I2, k3])/6 + (I/6)*SU3F[I1, I5, k2]*
		SU3F[I2, k1, k3] + SU3D[I1, I2, k2]*((I/6)*SU3D[I5, k1, k3] +
		SU3F[I5, k1, k3]/6) + (I/6)*SU3F[I1, I2, k2]*SU3F[I5, k1, k3]) +
	SU3D[I3, k1, k3]*(-(SU3D[I1, I5, k2]*SU3F[I2, k2, k3])/6 +
		SU3D[I1, I2, k2]*((I/6)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/6)) +
	SU3D[I2, k1, k3]*(SU3D[I1, I5, k2]*((I/6)*SU3D[I3, k2, k3] -
		SU3F[I3, k2, k3]/6) + SU3D[I1, I3, k2]*((I/6)*SU3D[I5, k2, k3] -
		SU3F[I5, k2, k3]/6)) - (SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*
		SU3F[I5, k2, k3])/6 + SU3D[I3, k1, k2]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, I2, k3])/6 + (I/6)*SU3F[I1, I5, k3]*
		SU3F[I2, k2, k3] + (I/6)*SU3F[I1, I2, k3]*SU3F[I5, k2, k3]) +
	SU3F[I2, k1, k3]*(-(SU3F[I1, I5, k2]*SU3F[I3, k2, k3])/6 -
		(SU3F[I1, I3, k2]*SU3F[I5, k2, k3])/6) + SU3D[I2, I3, k2]*
		((SU3D[I5, k2, k3]*SU3F[I1, k1, k3])/3 +
		(SU3D[I5, k1, k3]*SU3F[I1, k2, k3])/2 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I5, k1, k3] + (I/3)*SU3F[I1, k1, k3]*SU3F[I5, k2, k3]) +
	SU3D[I1, I3, k2]*((SU3D[I5, k2, k3]*SU3F[I2, k1, k3])/6 -
		(SU3D[I5, k1, k3]*SU3F[I2, k2, k3])/6 + (I/6)*SU3F[I2, k2, k3]*
		SU3F[I5, k1, k3] + (I/6)*SU3F[I2, k1, k3]*SU3F[I5, k2, k3]) +
	SU3D[I1, I2, k2]*((SU3D[I5, k2, k3]*SU3F[I3, k1, k3])/6 -
		(SU3D[I5, k1, k3]*SU3F[I3, k2, k3])/6 + (I/6)*SU3F[I3, k2, k3]*
		SU3F[I5, k1, k3] + (I/6)*SU3F[I3, k1, k3]*SU3F[I5, k2, k3]) +
	((2*I)/9)*SU3D[I3, I5, k1]*SUNDelta[I1, I2] +
	((2*I)/9)*SU3D[I2, I5, k1]*SUNDelta[I1, I3] +
	((2*I)/9)*SU3D[I2, I3, k1]*SUNDelta[I1, I5] - (I/9)*SU3D[I1, I5, k1]*
		SUNDelta[I2, I3] - (5*SU3F[I1, I5, k1]*SUNDelta[I2, I3])/9 -
	(I/9)*SU3D[I1, I3, k1]*SUNDelta[I2, I5] -
	(5*SU3F[I1, I3, k1]*SUNDelta[I2, I5])/9 - (I/9)*SU3D[I1, I2, k1]*
		SUNDelta[I3, I5] - (5*SU3F[I1, I2, k1]*SUNDelta[I3, I5])/9) +
	SU3F[6, I4, k1]*((-I/6)*SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*
		SU3F[I3, k1, k3] - (I/6)*SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*
		SU3F[I5, k1, k3] - (I/6)*SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*
		SU3F[I5, k1, k3] - (I/6)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*
		SU3F[I5, k2, k3] + SU3F[I2, k1, k3]*((-I/6)*SU3F[I1, I5, k2]*
		SU3F[I3, k2, k3] - (I/6)*SU3F[I1, I3, k2]*SU3F[I5, k2, k3]) -
	((5*I)/9)*SU3F[I1, I5, k1]*SUNDelta[I2, I3] -
	((5*I)/9)*SU3F[I1, I3, k1]*SUNDelta[I2, I5] -
	((5*I)/9)*SU3F[I1, I2, k1]*SUNDelta[I3, I5]) +
	SU3F[6, I1, k1]*((I/6)*SU3F[I2, I4, k2]*SU3F[I3, k2, k3]*
		SU3F[I5, k1, k3] + SU3F[I2, k2, k3]*((-I/6)*SU3F[I3, k1, k3]*
		SU3F[I4, I5, k2] + (I/6)*SU3F[I3, I4, k2]*SU3F[I5, k1, k3]) +
	(I/6)*SU3F[I2, I4, k2]*SU3F[I3, k1, k3]*SU3F[I5, k2, k3] +
	SU3F[I2, k1, k2]*((I/6)*SU3F[I3, k2, k3]*SU3F[I4, I5, k3] -
		(I/6)*SU3F[I3, I4, k3]*SU3F[I5, k2, k3]) -
	((2*I)/9)*SU3F[I4, I5, k1]*SUNDelta[I2, I3] +
	((2*I)/9)*SU3F[I3, I4, k1]*SUNDelta[I2, I5] +
	((2*I)/9)*SU3F[I2, I4, k1]*SUNDelta[I3, I5]) +
	SUNDelta[6, I4]*(((2*I)/27)*SUNDelta[I1, I5]*SUNDelta[I2, I3] +
	((2*I)/27)*SUNDelta[I1, I3]*SUNDelta[I2, I5] +
	((2*I)/27)*SUNDelta[I1, I2]*SUNDelta[I3, I5]) +
	SU3D[6, I1, k1]*(SU3D[I5, k2, k3]*((-I/6)*SU3F[I2, k1, k3]*
		SU3F[I3, I4, k2] - (I/6)*SU3F[I2, I4, k2]*SU3F[I3, k1, k3]) +
	SU3D[I5, k1, k3]*(-(SU3D[I3, I4, k2]*SU3F[I2, k2, k3])/6 -
		(SU3D[I2, I4, k2]*SU3F[I3, k2, k3])/6) + SU3D[I5, k1, k2]*
		((-I/6)*SU3F[I2, k2, k3]*SU3F[I3, I4, k3] - (I/6)*SU3F[I2, I4, k3]*
		SU3F[I3, k2, k3]) + SU3D[I4, I5, k2]*
		((I/6)*SU3F[I2, k2, k3]*SU3F[I3, k1, k3] + (I/6)*SU3F[I2, k1, k3]*
		SU3F[I3, k2, k3]) + SU3D[I2, I3, k2]*SU3D[I4, k2, k3]*
		((-I/6)*SU3D[I5, k1, k3] - SU3F[I5, k1, k3]/6) +
	(SU3F[I2, I4, k2]*SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/6 +
	SU3F[I2, k2, k3]*(-(SU3F[I3, k1, k3]*SU3F[I4, I5, k2])/6 +
		(SU3F[I3, I4, k2]*SU3F[I5, k1, k3])/6) + SU3D[I2, I3, k2]*
		SU3D[I4, k1, k3]*((I/6)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/6) +
	(SU3F[I2, I4, k2]*SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/6 +
	SU3D[I3, I4, k2]*((SU3D[I5, k2, k3]*SU3F[I2, k1, k3])/6 +
		(I/6)*SU3F[I2, k2, k3]*SU3F[I5, k1, k3] + (I/6)*SU3F[I2, k1, k3]*
		SU3F[I5, k2, k3]) + SU3F[I2, k1, k2]*
		((SU3F[I3, k2, k3]*SU3F[I4, I5, k3])/6 -
		(SU3F[I3, I4, k3]*SU3F[I5, k2, k3])/6) + SU3D[I2, I4, k2]*
		((SU3D[I5, k2, k3]*SU3F[I3, k1, k3])/6 + (I/6)*SU3F[I3, k2, k3]*
		SU3F[I5, k1, k3] + (I/6)*SU3F[I3, k1, k3]*SU3F[I5, k2, k3]) +
	SU3D[I2, I3, k2]*((SU3D[I5, k2, k3]*SU3F[I4, k1, k3])/6 +
		(SU3D[I5, k1, k3]*SU3F[I4, k2, k3])/6 - (I/6)*SU3F[I4, k2, k3]*
		SU3F[I5, k1, k3] + (I/6)*SU3F[I4, k1, k3]*SU3F[I5, k2, k3]) -
	(2*SU3F[I4, I5, k1]*SUNDelta[I2, I3])/9 + ((2*I)/9)*SU3D[I3, I5, k1]*
		SUNDelta[I2, I4] + (2*SU3F[I3, I4, k1]*SUNDelta[I2, I5])/9 +
	((2*I)/9)*SU3D[I2, I5, k1]*SUNDelta[I3, I4] +
	(2*SU3F[I2, I4, k1]*SUNDelta[I3, I5])/9 + ((2*I)/9)*SU3D[I2, I3, k1]*
		SUNDelta[I4, I5]) + SU3D[I2, I3, k1]*
	(SU3F[6, I5, k2]*((SU3F[I1, k2, k3]*SU3F[I4, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I4, k2, k3])/2) + SU3F[6, I4, k2]*
		(-(SU3F[I1, k2, k3]*SU3F[I5, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I5, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/6 +
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/6) + ((2*I)/9)*SU3D[I4, I5, k1]*
		SUNDelta[6, I1] - (4*SU3F[I4, I5, k1]*SUNDelta[6, I1])/9 +
	(I/9)*SU3D[I1, I5, k1]*SUNDelta[6, I4] -
	(7*SU3F[I1, I5, k1]*SUNDelta[6, I4])/9 - ((8*I)/9)*SU3D[I1, I4, k1]*
		SUNDelta[6, I5] - (2*SU3F[6, I4, k1]*SUNDelta[I1, I5])/9 -
	(2*SU3F[6, I1, k1]*SUNDelta[I4, I5])/9) + SU3D[I1, I3, k1]*
	(-(SU3F[6, I5, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/4 -
	(SU3F[6, I2, k2]*SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/4 +
	SU3F[6, I4, k2]*(-(SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I5, k2, k3])/6) + ((5*I)/18)*SU3D[I4, I5, k1]*
		SUNDelta[6, I2] + (SU3F[I4, I5, k1]*SUNDelta[6, I2])/6 -
	(SU3F[I2, I4, k1]*SUNDelta[6, I5])/6 -
	(SU3F[6, I5, k1]*SUNDelta[I2, I4])/9 +
	(SU3F[6, I4, k1]*SUNDelta[I2, I5])/9 -
	(SU3F[6, I2, k1]*SUNDelta[I4, I5])/9) + SU3D[I1, I2, k1]*
	(-(SU3F[6, I5, k2]*SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/4 -
	(SU3F[6, I3, k2]*SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/4 +
	SU3F[6, I4, k2]*(-(SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/6) + ((5*I)/18)*SU3D[I4, I5, k1]*
		SUNDelta[6, I3] + (SU3F[I4, I5, k1]*SUNDelta[6, I3])/6 +
	(I/9)*SU3D[I3, I5, k1]*SUNDelta[6, I4] + ((5*I)/18)*SU3D[I3, I4, k1]*
		SUNDelta[6, I5] - (SU3F[I3, I4, k1]*SUNDelta[6, I5])/6 -
	(SU3F[6, I5, k1]*SUNDelta[I3, I4])/9 +
	(SU3F[6, I4, k1]*SUNDelta[I3, I5])/9 -
	(SU3F[6, I3, k1]*SUNDelta[I4, I5])/9) + SU3F[6, I3, k1]*
	((-I/3)*SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3] +
	(I/12)*SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*SU3F[I5, k1, k3] +
	SU3F[I2, k1, k3]*((-I/12)*SU3F[I1, I5, k2]*SU3F[I4, k2, k3] +
		(I/12)*SU3F[I1, I4, k2]*SU3F[I5, k2, k3]) +
	SU3F[I1, I2, k2]*((-I/12)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] -
		(I/3)*SU3F[I4, k1, k3]*SU3F[I5, k2, k3]) + (I/6)*SU3F[I4, I5, k1]*
		SUNDelta[I1, I2] - (I/6)*SU3F[I2, I4, k1]*SUNDelta[I1, I5] +
	((5*I)/9)*SU3F[I1, I5, k1]*SUNDelta[I2, I4] - (I/9)*SU3F[I1, I4, k1]*
		SUNDelta[I2, I5] + ((5*I)/9)*SU3F[I1, I2, k1]*SUNDelta[I4, I5]) +
	SU3D[6, I3, k1]*(-(SU3D[I2, I4, k2]*SU3D[I5, k1, k3]*SU3F[I1, k2, k3])/
		2 - (SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/3 +
	SU3D[I5, k2, k3]*((-I/12)*SU3F[I1, I4, k2]*SU3F[I2, k1, k3] +
		(I/3)*SU3F[I1, I2, k2]*SU3F[I4, k1, k3]) + SU3D[I5, k1, k2]*
		((-I/12)*SU3F[I1, I4, k3]*SU3F[I2, k2, k3] + (I/12)*SU3F[I1, I2, k3]*
		SU3F[I4, k2, k3]) + (SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*
		SU3F[I5, k1, k3])/12 + SU3D[I4, k2, k3]*
		(-(SU3D[I5, k1, k2]*SU3F[I1, I2, k3])/12 + (I/12)*SU3F[I1, I5, k2]*
		SU3F[I2, k1, k3] + SU3D[I1, I2, k2]*((I/4)*SU3D[I5, k1, k3] +
		SU3F[I5, k1, k3]/4) + (I/12)*SU3F[I1, I2, k2]*SU3F[I5, k1, k3]) +
	SU3D[I1, I2, k2]*(-(SU3D[I5, k1, k3]*SU3F[I4, k2, k3])/4 +
		(I/4)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3]) + SU3D[I4, k1, k2]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, I2, k3])/3 + (I/3)*SU3F[I1, I5, k3]*
		SU3F[I2, k2, k3] + (I/3)*SU3F[I1, I2, k3]*SU3F[I5, k2, k3]) +
	SU3F[I2, k1, k3]*(-(SU3F[I1, I5, k2]*SU3F[I4, k2, k3])/12 +
		(SU3F[I1, I4, k2]*SU3F[I5, k2, k3])/12) + SU3D[I2, I4, k2]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, k1, k3])/3 + (I/2)*SU3F[I1, k2, k3]*
		SU3F[I5, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I5, k2, k3]) +
	SU3F[I1, I2, k2]*(-(SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/12 -
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/3) + (I/6)*SU3D[I4, I5, k1]*
		SUNDelta[I1, I2] + (SU3F[I4, I5, k1]*SUNDelta[I1, I2])/6 +
	(I/6)*SU3D[I2, I4, k1]*SUNDelta[I1, I5] -
	(SU3F[I2, I4, k1]*SUNDelta[I1, I5])/6 + (I/9)*SU3D[I1, I5, k1]*
		SUNDelta[I2, I4] + (5*SU3F[I1, I5, k1]*SUNDelta[I2, I4])/9 -
	((5*I)/9)*SU3D[I1, I4, k1]*SUNDelta[I2, I5] -
	(SU3F[I1, I4, k1]*SUNDelta[I2, I5])/9 + (I/9)*SU3D[I1, I2, k1]*
		SUNDelta[I4, I5] + (5*SU3F[I1, I2, k1]*SUNDelta[I4, I5])/9) +
	SU3F[6, I2, k1]*(SU3F[I1, I5, k2]*((-I/3)*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3] - (I/12)*SU3F[I3, k1, k3]*SU3F[I4, k2, k3]) +
	SU3F[I1, I4, k2]*((I/12)*SU3F[I3, k2, k3]*SU3F[I5, k1, k3] +
		(I/12)*SU3F[I3, k1, k3]*SU3F[I5, k2, k3]) +
	SU3F[I1, I3, k2]*((-I/12)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] -
		(I/3)*SU3F[I4, k1, k3]*SU3F[I5, k2, k3]) + (I/6)*SU3F[I4, I5, k1]*
		SUNDelta[I1, I3] - (I/6)*SU3F[I3, I4, k1]*SUNDelta[I1, I5] +
	((5*I)/9)*SU3F[I1, I5, k1]*SUNDelta[I3, I4] - (I/9)*SU3F[I1, I4, k1]*
		SUNDelta[I3, I5] + ((5*I)/9)*SU3F[I1, I3, k1]*SUNDelta[I4, I5]) +
	SU3D[6, I2, k1]*(-(SU3D[I3, I4, k2]*SU3D[I5, k1, k3]*SU3F[I1, k2, k3])/
		2 + SU3D[I5, k2, k3]*((-I/12)*SU3F[I1, I4, k2]*SU3F[I3, k1, k3] +
		(I/3)*SU3F[I1, I3, k2]*SU3F[I4, k1, k3]) + SU3D[I5, k1, k2]*
		((-I/12)*SU3F[I1, I4, k3]*SU3F[I3, k2, k3] + (I/12)*SU3F[I1, I3, k3]*
		SU3F[I4, k2, k3]) + SU3F[I1, I5, k2]*
		(-(SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/3 -
		(SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/12) + SU3D[I4, k2, k3]*
		(-(SU3D[I5, k1, k2]*SU3F[I1, I3, k3])/12 + (I/12)*SU3F[I1, I5, k2]*
		SU3F[I3, k1, k3] + SU3D[I1, I3, k2]*((I/4)*SU3D[I5, k1, k3] +
		SU3F[I5, k1, k3]/4) + (I/12)*SU3F[I1, I3, k2]*SU3F[I5, k1, k3]) +
	SU3D[I1, I3, k2]*(-(SU3D[I5, k1, k3]*SU3F[I4, k2, k3])/4 +
		(I/4)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3]) + SU3D[I4, k1, k2]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, I3, k3])/3 + (I/3)*SU3F[I1, I5, k3]*
		SU3F[I3, k2, k3] + (I/3)*SU3F[I1, I3, k3]*SU3F[I5, k2, k3]) +
	SU3D[I3, I4, k2]*(-(SU3D[I5, k2, k3]*SU3F[I1, k1, k3])/3 +
		(I/2)*SU3F[I1, k2, k3]*SU3F[I5, k1, k3] - (I/3)*SU3F[I1, k1, k3]*
		SU3F[I5, k2, k3]) + SU3F[I1, I4, k2]*
		((SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/12 +
		(SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/12) + SU3F[I1, I3, k2]*
		(-(SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/12 -
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/3) + (I/6)*SU3D[I4, I5, k1]*
		SUNDelta[I1, I3] + (SU3F[I4, I5, k1]*SUNDelta[I1, I3])/6 +
	(I/6)*SU3D[I3, I4, k1]*SUNDelta[I1, I5] -
	(SU3F[I3, I4, k1]*SUNDelta[I1, I5])/6 + (I/9)*SU3D[I1, I5, k1]*
		SUNDelta[I3, I4] + (5*SU3F[I1, I5, k1]*SUNDelta[I3, I4])/9 -
	((5*I)/9)*SU3D[I1, I4, k1]*SUNDelta[I3, I5] -
	(SU3F[I1, I4, k1]*SUNDelta[I3, I5])/9 + (I/9)*SU3D[I1, I3, k1]*
		SUNDelta[I4, I5] + (5*SU3F[I1, I3, k1]*SUNDelta[I4, I5])/9) +
	SUNDelta[6, I3]*(((5*I)/27)*SUNDelta[I1, I5]*SUNDelta[I2, I4] -
	((16*I)/27)*SUNDelta[I1, I4]*SUNDelta[I2, I5] +
	((5*I)/27)*SUNDelta[I1, I2]*SUNDelta[I4, I5]) +
	SUNDelta[6, I2]*(((5*I)/27)*SUNDelta[I1, I5]*SUNDelta[I3, I4] -
	((16*I)/27)*SUNDelta[I1, I4]*SUNDelta[I3, I5] +
	((5*I)/27)*SUNDelta[I1, I3]*SUNDelta[I4, I5]) +
	SUNDelta[6, I1]*(((4*I)/27)*SUNDelta[I2, I5]*SUNDelta[I3, I4] +
	((4*I)/27)*SUNDelta[I2, I4]*SUNDelta[I3, I5] +
	((4*I)/27)*SUNDelta[I2, I3]*SUNDelta[I4, I5])))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4},
{(CouplingConstant[ChPTW3[2], 1]*(((-4*I)/9)*SU3D[6, I4, I5]*
	SU3D[I1, I2, I3] - ((4*I)/9)*SU3D[6, I3, I5]*SU3D[I1, I2, I4] -
	((4*I)/9)*SU3D[6, I2, I5]*SU3D[I1, I3, I4] +
	I*SU3D[6, I1, I5]*SU3D[I2, I3, I4] - ((5*I)/9)*SU3D[6, I1, I4]*
	SU3D[I2, I3, I5] - ((5*I)/9)*SU3D[6, I1, I3]*SU3D[I2, I4, I5] -
	((5*I)/9)*SU3D[6, I1, I2]*SU3D[I3, I4, I5] -
	(7*SU3D[I3, I4, I5]*SU3F[6, I1, I2])/9 -
	(7*SU3D[I2, I4, I5]*SU3F[6, I1, I3])/9 -
	(7*SU3D[I2, I3, I5]*SU3F[6, I1, I4])/9 +
	(SU3D[I2, I3, I4]*SU3F[6, I1, I5])/3 +
	(2*SU3D[I1, I3, I4]*SU3F[6, I2, I5])/9 +
	(2*SU3D[I1, I2, I4]*SU3F[6, I3, I5])/9 +
	(2*SU3D[I1, I2, I3]*SU3F[6, I4, I5])/9 + SU3D[6, I3, I4]*
	(((2*I)/3)*SU3D[I1, I2, I5] - (2*SU3F[I1, I2, I5])/9) +
	SU3D[6, I2, I4]*(((2*I)/3)*SU3D[I1, I3, I5] - (2*SU3F[I1, I3, I5])/9) +
	SU3D[6, I2, I3]*(((2*I)/3)*SU3D[I1, I4, I5] - (2*SU3F[I1, I4, I5])/9) +
	SU3D[I4, I5, k2]*(SU3D[6, I3, k1]*((I/2)*SU3F[I1, k2, k3]*
		SU3F[I2, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]) +
	SU3D[6, I2, k1]*((I/2)*SU3F[I1, k2, k3]*SU3F[I3, k1, k3] -
		(I/3)*SU3F[I1, k1, k3]*SU3F[I3, k2, k3])) +
	SU3D[I5, k2, k3]*(SU3D[I3, I4, k1]*((I/2)*SU3F[6, I2, k2]*
		SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*SU3F[I2, k1, k3]) +
	SU3D[I2, I4, k1]*((I/2)*SU3F[6, I3, k2]*SU3F[I1, k1, k3] -
		(I/6)*SU3F[6, I1, k2]*SU3F[I3, k1, k3]) + SU3D[I2, I3, k1]*
		((I/2)*SU3F[6, I4, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I4, k1, k3])) + SU3D[I5, k1, k2]*
	(SU3D[I3, I4, k1]*((I/3)*SU3F[6, I2, k3]*SU3F[I1, k2, k3] +
		(I/6)*SU3F[6, I1, k3]*SU3F[I2, k2, k3]) + SU3F[6, I4, k2]*
		(-(SU3F[I1, I3, k3]*SU3F[I2, k1, k3])/3 -
		(SU3F[I1, I2, k3]*SU3F[I3, k1, k3])/3) + SU3D[I2, I4, k1]*
		((I/3)*SU3F[6, I3, k3]*SU3F[I1, k2, k3] + (I/6)*SU3F[6, I1, k3]*
		SU3F[I3, k2, k3]) + SU3D[I1, I4, k1]*
		((-I/4)*SU3F[6, I3, k3]*SU3F[I2, k2, k3] - (I/4)*SU3F[6, I2, k3]*
		SU3F[I3, k2, k3]) + SU3F[6, I4, k3]*
		((SU3F[I1, I3, k1]*SU3F[I2, k2, k3])/12 +
		(SU3F[I1, I2, k1]*SU3F[I3, k2, k3])/12) + SU3F[6, I3, k2]*
		(-(SU3F[I1, I4, k3]*SU3F[I2, k1, k3])/3 -
		(SU3F[I1, I2, k3]*SU3F[I4, k1, k3])/3) + SU3F[6, I2, k2]*
		(-(SU3F[I1, I4, k3]*SU3F[I3, k1, k3])/3 -
		(SU3F[I1, I3, k3]*SU3F[I4, k1, k3])/3) + SU3D[I2, I3, k1]*
		((I/3)*SU3F[6, I4, k3]*SU3F[I1, k2, k3] + (I/6)*SU3F[6, I1, k3]*
		SU3F[I4, k2, k3]) + SU3D[I1, I3, k1]*
		((-I/4)*SU3F[6, I4, k3]*SU3F[I2, k2, k3] - (I/4)*SU3F[6, I2, k3]*
		SU3F[I4, k2, k3]) + SU3D[I1, I2, k1]*
		((-I/4)*SU3F[6, I4, k3]*SU3F[I3, k2, k3] - (I/4)*SU3F[6, I3, k3]*
		SU3F[I4, k2, k3]) + SU3F[6, I3, k3]*
		((SU3F[I1, I4, k1]*SU3F[I2, k2, k3])/12 +
		(SU3F[I1, I2, k1]*SU3F[I4, k2, k3])/12) + SU3F[6, I2, k3]*
		((SU3F[I1, I4, k1]*SU3F[I3, k2, k3])/12 +
		(SU3F[I1, I3, k1]*SU3F[I4, k2, k3])/12)) +
	SU3D[I1, I5, k2]*(SU3D[6, I2, k1]*SU3D[I3, k2, k3]*
		((-I/4)*SU3D[I4, k1, k3] - SU3F[I4, k1, k3]/4) +
	SU3D[6, I3, k1]*(-(SU3D[I4, k2, k3]*SU3F[I2, k1, k3])/4 +
		(SU3D[I4, k1, k3]*SU3F[I2, k2, k3])/4 - (I/4)*SU3F[I2, k2, k3]*
		SU3F[I4, k1, k3] - (I/4)*SU3F[I2, k1, k3]*SU3F[I4, k2, k3]) +
	SU3D[6, I2, k1]*(-(SU3D[I4, k2, k3]*SU3F[I3, k1, k3])/4 +
		(SU3D[I4, k1, k3]*SU3F[I3, k2, k3])/4 - (I/4)*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3] - (I/4)*SU3F[I3, k1, k3]*SU3F[I4, k2, k3])) +
	SU3D[I1, k2, k3]*((I/2)*SU3D[6, I3, k1]*SU3D[I2, k1, k2]*
		SU3D[I4, I5, k3] + (I/2)*SU3D[6, I2, k1]*SU3D[I3, k1, k2]*
		SU3D[I4, I5, k3] + (SU3D[6, I3, k1]*SU3D[I4, I5, k3]*
		SU3F[I2, k1, k2])/2 + (SU3D[6, I2, k1]*SU3D[I4, I5, k3]*
		SU3F[I3, k1, k2])/2 + SU3D[6, I3, k1]*SU3D[I2, I5, k3]*
		((I/2)*SU3D[I4, k1, k2] + SU3F[I4, k1, k2]/2) +
	SU3D[6, I2, k1]*SU3D[I3, I5, k3]*((I/2)*SU3D[I4, k1, k2] +
		SU3F[I4, k1, k2]/2) + SU3D[6, I4, k1]*
		((I/2)*SU3D[I2, k1, k2]*SU3D[I3, I5, k3] +
		(SU3D[I3, I5, k3]*SU3F[I2, k1, k2])/2 + SU3D[I2, I5, k3]*
		((I/2)*SU3D[I3, k1, k2] + SU3F[I3, k1, k2]/2) +
		SU3D[I2, I3, k3]*((-I/2)*SU3D[I5, k1, k2] - SU3F[I5, k1, k2]/2)) +
	SU3D[6, I3, k1]*SU3D[I2, I4, k3]*((-I/2)*SU3D[I5, k1, k2] -
		SU3F[I5, k1, k2]/2) + SU3D[6, I2, k1]*SU3D[I3, I4, k3]*
		((-I/2)*SU3D[I5, k1, k2] - SU3F[I5, k1, k2]/2)) +
	SU3D[I4, k2, k3]*(SU3D[I5, k1, k3]*((SU3D[I2, I3, k1]*SU3F[6, I1, k2])/
		6 - (SU3D[I1, I3, k1]*SU3F[6, I2, k2])/4 -
		(SU3D[I1, I2, k1]*SU3F[6, I3, k2])/4) + SU3D[I3, I5, k1]*
		((-I/2)*SU3F[6, I2, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I2, k1, k3]) + SU3D[I2, I5, k1]*
		((-I/2)*SU3F[6, I3, k2]*SU3F[I1, k1, k3] - (I/6)*SU3F[6, I1, k2]*
		SU3F[I3, k1, k3]) + SU3D[I1, I5, k1]*
		((I/4)*SU3F[6, I3, k2]*SU3F[I2, k1, k3] + (I/4)*SU3F[6, I2, k2]*
		SU3F[I3, k1, k3]) + SU3D[I2, I3, k1]*
		((I/2)*SU3F[6, I5, k2]*SU3F[I1, k1, k3] + (I/6)*SU3F[6, I1, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I3, k1]*
		((-I/6)*SU3F[6, I5, k2]*SU3F[I2, k1, k3] - (I/4)*SU3F[6, I2, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I2, k1]*
		((-I/6)*SU3F[6, I5, k2]*SU3F[I3, k1, k3] - (I/4)*SU3F[6, I3, k2]*
		SU3F[I5, k1, k3])) + SU3D[I3, k2, k3]*
	(SU3D[I5, k1, k3]*((SU3D[I2, I4, k1]*SU3F[6, I1, k2])/6 -
		(SU3D[I1, I4, k1]*SU3F[6, I2, k2])/4 -
		(SU3D[I1, I2, k1]*SU3F[6, I4, k2])/4) + SU3D[I4, k1, k3]*
		(-(SU3D[I2, I5, k1]*SU3F[6, I1, k2])/6 +
		(SU3D[I1, I5, k1]*SU3F[6, I2, k2])/4 -
		(SU3D[I1, I2, k1]*SU3F[6, I5, k2])/6) -
	(SU3D[6, I2, k1]*SU3D[I4, I5, k3]*SU3F[I1, k1, k2])/3 +
	SU3D[I2, I5, k1]*((-I/2)*SU3F[6, I4, k2]*SU3F[I1, k1, k3] -
		(I/6)*SU3F[6, I1, k2]*SU3F[I4, k1, k3]) + SU3D[I1, I5, k1]*
		((I/4)*SU3F[6, I4, k2]*SU3F[I2, k1, k3] + (I/4)*SU3F[6, I2, k2]*
		SU3F[I4, k1, k3]) + SU3D[6, I1, k1]*
		((I/6)*SU3D[I2, I5, k2]*SU3D[I4, k1, k3] +
		(SU3D[I4, k1, k2]*SU3F[I2, I5, k3])/6 +
		(SU3D[I4, I5, k3]*SU3F[I2, k1, k2])/6 - (I/6)*SU3F[I2, k1, k3]*
		SU3F[I4, I5, k2] + (SU3D[I2, I5, k2]*SU3F[I4, k1, k3])/6 -
		(I/6)*SU3F[I2, I5, k2]*SU3F[I4, k1, k3]) + SU3D[I2, I4, k1]*
		((I/2)*SU3F[6, I5, k2]*SU3F[I1, k1, k3] + (I/6)*SU3F[6, I1, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I4, k1]*
		((-I/6)*SU3F[6, I5, k2]*SU3F[I2, k1, k3] - (I/4)*SU3F[6, I2, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I2, k1]*
		((-I/6)*SU3F[6, I5, k2]*SU3F[I4, k1, k3] - (I/4)*SU3F[6, I4, k2]*
		SU3F[I5, k1, k3]) + SU3D[6, I2, k1]*
		(-(SU3D[I5, k1, k2]*SU3F[I1, I4, k3])/3 +
		(SU3D[I4, k1, k2]*SU3F[I1, I5, k3])/12 - (I/12)*SU3F[I1, I5, k2]*
		SU3F[I4, k1, k3] + (I/3)*SU3F[I1, I4, k2]*SU3F[I5, k1, k3])) +
	SU3D[I2, k2, k3]*(SU3D[I5, k1, k3]*(-(SU3D[I1, I4, k1]*SU3F[6, I3, k2])/
		4 - (SU3D[I1, I3, k1]*SU3F[6, I4, k2])/4) +
	SU3D[I4, k1, k3]*((SU3D[I1, I5, k1]*SU3F[6, I3, k2])/4 -
		(SU3D[I1, I3, k1]*SU3F[6, I5, k2])/6) + SU3D[I3, k1, k3]*
		((I/6)*SU3D[6, I1, k1]*SU3D[I4, I5, k2] +
		(SU3D[I1, I5, k1]*SU3F[6, I4, k2])/4 -
		(SU3D[I1, I4, k1]*SU3F[6, I5, k2])/6) +
	(SU3D[6, I1, k1]*SU3D[I3, k1, k2]*SU3F[I4, I5, k3])/6 +
	(SU3D[6, I1, k1]*SU3D[I3, I5, k3]*SU3F[I4, k1, k2])/6 +
	SU3D[6, I3, k1]*SU3D[I1, I5, k2]*((-I/4)*SU3D[I4, k1, k3] -
		SU3F[I4, k1, k3]/4) + SU3D[I1, I5, k1]*
		((I/4)*SU3F[6, I4, k2]*SU3F[I3, k1, k3] + (I/4)*SU3F[6, I3, k2]*
		SU3F[I4, k1, k3]) + SU3D[6, I1, k1]*
		((I/6)*SU3D[I3, I5, k2]*SU3D[I4, k1, k3] +
		(SU3D[I4, k1, k2]*SU3F[I3, I5, k3])/6 +
		(SU3D[I4, I5, k3]*SU3F[I3, k1, k2])/6 - (I/6)*SU3F[I3, k1, k3]*
		SU3F[I4, I5, k2] - (I/6)*SU3F[I3, I5, k2]*SU3F[I4, k1, k3]) +
	SU3D[6, I1, k1]*SU3D[I3, I4, k3]*((I/6)*SU3D[I5, k1, k2] +
		SU3F[I5, k1, k2]/6) + SU3D[I1, I4, k1]*
		((-I/6)*SU3F[6, I5, k2]*SU3F[I3, k1, k3] - (I/4)*SU3F[6, I3, k2]*
		SU3F[I5, k1, k3]) + SU3D[I1, I3, k1]*
		((-I/6)*SU3F[6, I5, k2]*SU3F[I4, k1, k3] - (I/4)*SU3F[6, I4, k2]*
		SU3F[I5, k1, k3]) + SU3D[6, I4, k1]*
		((-I/4)*SU3D[I1, I5, k2]*SU3D[I3, k1, k3] -
		(SU3D[I5, k1, k2]*SU3F[I1, I3, k3])/3 +
		(SU3D[I3, k1, k2]*SU3F[I1, I5, k3])/12 -
		(SU3D[I3, I5, k3]*SU3F[I1, k1, k2])/3 -
		(SU3D[I1, I5, k2]*SU3F[I3, k1, k3])/4 - (I/12)*SU3F[I1, I5, k2]*
		SU3F[I3, k1, k3] + (I/3)*SU3F[I1, I3, k2]*SU3F[I5, k1, k3]) +
	SU3D[6, I3, k1]*(-(SU3D[I5, k1, k2]*SU3F[I1, I4, k3])/3 +
		(SU3D[I4, k1, k2]*SU3F[I1, I5, k3])/12 -
		(SU3D[I4, I5, k3]*SU3F[I1, k1, k2])/3 - (I/12)*SU3F[I1, I5, k2]*
		SU3F[I4, k1, k3] + (I/3)*SU3F[I1, I4, k2]*SU3F[I5, k1, k3])) +
	SU3D[I3, k1, k3]*(SU3D[6, I1, k1]*SU3D[I2, I5, k2]*
		((I/6)*SU3D[I4, k2, k3] - SU3F[I4, k2, k3]/6) +
	SU3D[6, I2, k1]*SU3D[I1, I5, k2]*((-I/4)*SU3D[I4, k2, k3] +
		SU3F[I4, k2, k3]/4) + SU3D[6, I2, k1]*SU3D[I1, I4, k2]*
		((I/4)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/4)) +
	SU3D[I2, k1, k3]*(SU3D[I1, k1, k2]*(-(SU3D[I4, I5, k2]*SU3F[6, I3, k3])/
		2 - (SU3D[I3, I5, k2]*SU3F[6, I4, k3])/2) +
	(SU3D[I1, k1, k2]*SU3D[I3, I4, k2]*SU3F[6, I5, k3])/2 +
	SU3D[6, I3, k1]*SU3D[I1, I5, k2]*((-I/4)*SU3D[I4, k2, k3] +
		SU3F[I4, k2, k3]/4) + SU3D[6, I4, k1]*
		(SU3D[I1, I5, k2]*((-I/4)*SU3D[I3, k2, k3] + SU3F[I3, k2, k3]/4) +
		SU3D[I1, I3, k2]*((I/4)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/4)) +
	SU3D[6, I3, k1]*SU3D[I1, I4, k2]*((I/4)*SU3D[I5, k2, k3] -
		SU3F[I5, k2, k3]/4)) + SU3D[I2, k1, k2]*SU3D[I3, I4, k3]*
	((SU3D[I5, k2, k3]*SU3F[6, I1, k1])/6 - (I/2)*SU3F[6, I5, k1]*
		SU3F[I1, k2, k3] + SU3D[6, I1, k1]*((-I/6)*SU3D[I5, k2, k3] -
		SU3F[I5, k2, k3]/6) - (I/6)*SU3F[6, I1, k1]*SU3F[I5, k2, k3]) +
	SU3D[I1, k1, k2]*(SU3D[I3, k2, k3]*SU3D[I4, I5, k3]*
		((-I/3)*SU3D[6, I2, k1] + SU3F[6, I2, k1]/3) +
	SU3D[I4, k1, k3]*(-(SU3D[I3, I5, k2]*SU3F[6, I2, k3])/2 -
		(SU3D[I2, I5, k2]*SU3F[6, I3, k3])/2) + SU3D[I3, k1, k3]*
		(-(SU3D[I4, I5, k2]*SU3F[6, I2, k3])/2 -
		(SU3D[I2, I5, k2]*SU3F[6, I4, k3])/2) + SU3D[I2, k2, k3]*
		((-I/3)*SU3D[6, I4, k1]*SU3D[I3, I5, k3] - (I/3)*SU3D[6, I3, k1]*
		SU3D[I4, I5, k3] + (SU3D[I4, I5, k3]*SU3F[6, I3, k1])/3 +
		(SU3D[I3, I5, k3]*SU3F[6, I4, k1])/3 -
		(SU3D[I3, I4, k3]*SU3F[6, I5, k1])/3) + SU3D[I2, I4, k2]*
		((SU3D[I5, k1, k3]*SU3F[6, I3, k3])/2 +
		(SU3D[I3, k1, k3]*SU3F[6, I5, k3])/2) + SU3D[I2, I3, k2]*
		((SU3D[I5, k1, k3]*SU3F[6, I4, k3])/2 +
		(SU3D[I4, k1, k3]*SU3F[6, I5, k3])/2) -
	(SU3D[6, I3, k1]*SU3D[I4, I5, k3]*SU3F[I2, k2, k3])/3 +
	SU3D[I4, I5, k3]*((-I/3)*SU3F[6, I3, k1]*SU3F[I2, k2, k3] -
		(SU3D[6, I2, k1]*SU3F[I3, k2, k3])/3 - (I/3)*SU3F[6, I2, k1]*
		SU3F[I3, k2, k3]) + SU3D[I4, I5, k1]*
		((-I/2)*SU3F[6, I3, k3]*SU3F[I2, k2, k3] - (I/2)*SU3F[6, I2, k3]*
		SU3F[I3, k2, k3]) + SU3D[I3, I5, k3]*
		((SU3D[I4, k2, k3]*SU3F[6, I2, k1])/3 - (I/3)*SU3F[6, I4, k1]*
		SU3F[I2, k2, k3] + SU3D[6, I2, k1]*((-I/3)*SU3D[I4, k2, k3] -
		SU3F[I4, k2, k3]/3) - (I/3)*SU3F[6, I2, k1]*SU3F[I4, k2, k3]) +
	SU3D[I3, I5, k1]*((-I/2)*SU3F[6, I4, k3]*SU3F[I2, k2, k3] -
		(I/2)*SU3F[6, I2, k3]*SU3F[I4, k2, k3]) + SU3D[I2, I5, k3]*
		((SU3D[I4, k2, k3]*SU3F[6, I3, k1])/3 +
		(SU3D[I3, k2, k3]*SU3F[6, I4, k1])/3 - (I/3)*SU3F[6, I4, k1]*
		SU3F[I3, k2, k3] + SU3D[6, I3, k1]*((-I/3)*SU3D[I4, k2, k3] -
		SU3F[I4, k2, k3]/3) - (I/3)*SU3F[6, I3, k1]*SU3F[I4, k2, k3]) +
	SU3D[I2, I5, k1]*((-I/2)*SU3F[6, I4, k3]*SU3F[I3, k2, k3] -
		(I/2)*SU3F[6, I3, k3]*SU3F[I4, k2, k3]) + SU3D[6, I4, k1]*
		(-(SU3D[I3, I5, k3]*SU3F[I2, k2, k3])/3 + SU3D[I2, I5, k3]*
		((-I/3)*SU3D[I3, k2, k3] - SU3F[I3, k2, k3]/3) +
		SU3D[I2, I3, k3]*((-I/3)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/3)) +
	SU3D[I3, I4, k3]*((SU3D[I5, k2, k3]*SU3F[6, I2, k1])/3 +
		(I/3)*SU3F[6, I5, k1]*SU3F[I2, k2, k3] + SU3D[6, I2, k1]*
		((-I/3)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/3) -
		(I/3)*SU3F[6, I2, k1]*SU3F[I5, k2, k3]) + SU3D[I3, I4, k1]*
		((I/2)*SU3F[6, I5, k3]*SU3F[I2, k2, k3] + (I/2)*SU3F[6, I2, k3]*
		SU3F[I5, k2, k3]) + SU3D[I2, I4, k3]*
		((SU3D[I5, k2, k3]*SU3F[6, I3, k1])/3 -
		(SU3D[I3, k2, k3]*SU3F[6, I5, k1])/3 + (I/3)*SU3F[6, I5, k1]*
		SU3F[I3, k2, k3] + SU3D[6, I3, k1]*((-I/3)*SU3D[I5, k2, k3] -
		SU3F[I5, k2, k3]/3) - (I/3)*SU3F[6, I3, k1]*SU3F[I5, k2, k3]) +
	SU3D[I2, I4, k1]*((I/2)*SU3F[6, I5, k3]*SU3F[I3, k2, k3] +
		(I/2)*SU3F[6, I3, k3]*SU3F[I5, k2, k3]) + SU3D[I2, I3, k3]*
		((SU3D[I5, k2, k3]*SU3F[6, I4, k1])/3 -
		(SU3D[I4, k2, k3]*SU3F[6, I5, k1])/3 + (I/3)*SU3F[6, I5, k1]*
		SU3F[I4, k2, k3] - (I/3)*SU3F[6, I4, k1]*SU3F[I5, k2, k3]) +
	SU3D[I2, I3, k1]*((I/2)*SU3F[6, I5, k3]*SU3F[I4, k2, k3] +
		(I/2)*SU3F[6, I4, k3]*SU3F[I5, k2, k3])) +
	SU3D[I4, k1, k2]*(SU3D[I5, k2, k3]*(-(SU3D[I2, I3, k1]*SU3F[6, I1, k3])/
		6 - (I/3)*SU3F[6, I3, k3]*SU3F[I1, I2, k1] - (I/3)*SU3F[6, I2, k3]*
		SU3F[I1, I3, k1]) + SU3D[I5, k1, k3]*
		((-I/12)*SU3F[6, I3, k2]*SU3F[I1, I2, k3] - (I/12)*SU3F[6, I2, k2]*
		SU3F[I1, I3, k3]) - (I/6)*SU3D[I1, I3, k1]*SU3F[6, I5, k3]*
		SU3F[I2, k2, k3] + SU3D[I3, I5, k1]*((I/3)*SU3F[6, I2, k3]*
		SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*SU3F[I2, k2, k3]) +
	SU3F[6, I5, k2]*(-(SU3F[I1, I3, k3]*SU3F[I2, k1, k3])/6 -
		(SU3F[I1, I2, k3]*SU3F[I3, k1, k3])/6) + SU3F[6, I1, k2]*
		((SU3F[I2, k1, k3]*SU3F[I3, I5, k3])/6 +
		(SU3F[I2, I5, k3]*SU3F[I3, k1, k3])/6) - (I/6)*SU3D[I1, I2, k1]*
		SU3F[6, I5, k3]*SU3F[I3, k2, k3] + SU3D[I2, I5, k1]*
		((I/3)*SU3F[6, I3, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I3, k2, k3]) + SU3D[I1, I5, k1]*
		((I/4)*SU3F[6, I3, k3]*SU3F[I2, k2, k3] + (I/4)*SU3F[6, I2, k3]*
		SU3F[I3, k2, k3]) + SU3F[6, I5, k3]*
		((SU3F[I1, I3, k1]*SU3F[I2, k2, k3])/6 +
		(SU3F[I1, I2, k1]*SU3F[I3, k2, k3])/6) + SU3F[6, I1, k3]*
		(-(SU3F[I2, k2, k3]*SU3F[I3, I5, k1])/6 -
		(SU3F[I2, I5, k1]*SU3F[I3, k2, k3])/6) + SU3F[6, I3, k2]*
		((SU3F[I1, I5, k3]*SU3F[I2, k1, k3])/12 -
		(SU3F[I1, I2, k3]*SU3F[I5, k1, k3])/12) + SU3F[6, I2, k2]*
		((SU3F[I1, I5, k3]*SU3F[I3, k1, k3])/12 -
		(SU3F[I1, I3, k3]*SU3F[I5, k1, k3])/12) + SU3D[I2, I3, k1]*
		((-I/3)*SU3F[6, I5, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I5, k2, k3]) + SU3F[6, I3, k3]*
		(-(SU3F[I1, I5, k1]*SU3F[I2, k2, k3])/12 +
		(SU3F[I1, I2, k1]*SU3F[I5, k2, k3])/3) + SU3F[6, I2, k3]*
		(-(SU3F[I1, I5, k1]*SU3F[I3, k2, k3])/12 +
		(SU3F[I1, I3, k1]*SU3F[I5, k2, k3])/3)) +
	SU3D[I3, k1, k2]*(SU3D[I5, k2, k3]*(-(SU3D[I2, I4, k1]*SU3F[6, I1, k3])/
		6 - (I/3)*SU3F[6, I4, k3]*SU3F[I1, I2, k1] - (I/3)*SU3F[6, I2, k3]*
		SU3F[I1, I4, k1]) + SU3D[I5, k1, k3]*
		((-I/12)*SU3F[6, I4, k2]*SU3F[I1, I2, k3] - (I/12)*SU3F[6, I2, k2]*
		SU3F[I1, I4, k3]) + SU3D[I4, k2, k3]*
		(-(SU3D[I2, I5, k1]*SU3F[6, I1, k3])/6 +
		(SU3D[I1, I5, k1]*SU3F[6, I2, k3])/4 -
		(SU3D[I1, I2, k1]*SU3F[6, I5, k3])/6 - (I/6)*SU3F[6, I5, k3]*
		SU3F[I1, I2, k1] + (I/12)*SU3F[6, I2, k3]*SU3F[I1, I5, k1] +
		(I/6)*SU3F[6, I1, k3]*SU3F[I2, I5, k1]) + SU3D[I4, k1, k3]*
		((-I/6)*SU3F[6, I5, k2]*SU3F[I1, I2, k3] + (I/12)*SU3F[6, I2, k2]*
		SU3F[I1, I5, k3] + (I/6)*SU3F[6, I1, k2]*SU3F[I2, I5, k3]) -
	(I/6)*SU3D[I1, I4, k1]*SU3F[6, I5, k3]*SU3F[I2, k2, k3] +
	SU3D[I4, I5, k3]*((SU3D[6, I2, k1]*SU3F[I1, k2, k3])/2 +
		(I/2)*SU3F[6, I2, k1]*SU3F[I1, k2, k3] + (I/6)*SU3F[6, I1, k1]*
		SU3F[I2, k2, k3]) + SU3D[I4, I5, k1]*
		((I/3)*SU3F[6, I2, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I2, k2, k3]) + SU3F[6, I5, k2]*
		(-(SU3F[I1, I4, k3]*SU3F[I2, k1, k3])/6 -
		(SU3F[I1, I2, k3]*SU3F[I4, k1, k3])/6) + SU3F[6, I1, k2]*
		((SU3F[I2, k1, k3]*SU3F[I4, I5, k3])/6 +
		(SU3F[I2, I5, k3]*SU3F[I4, k1, k3])/6) - (I/6)*SU3D[I1, I2, k1]*
		SU3F[6, I5, k3]*SU3F[I4, k2, k3] + SU3D[I2, I5, k1]*
		((I/3)*SU3F[6, I4, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I4, k2, k3]) + SU3D[I1, I5, k1]*
		((I/4)*SU3F[6, I4, k3]*SU3F[I2, k2, k3] + (I/4)*SU3F[6, I2, k3]*
		SU3F[I4, k2, k3]) + SU3F[6, I5, k3]*
		((SU3F[I1, I4, k1]*SU3F[I2, k2, k3])/6 +
		(SU3F[I1, I2, k1]*SU3F[I4, k2, k3])/6) + SU3F[6, I1, k3]*
		(-(SU3F[I2, k2, k3]*SU3F[I4, I5, k1])/6 -
		(SU3F[I2, I5, k1]*SU3F[I4, k2, k3])/6) + SU3D[6, I1, k1]*
		((SU3D[I4, k2, k3]*SU3F[I2, I5, k3])/6 +
		(SU3D[I4, I5, k3]*SU3F[I2, k2, k3])/6 - (I/6)*SU3F[I2, k2, k3]*
		SU3F[I4, I5, k3] - (I/6)*SU3F[I2, I5, k3]*SU3F[I4, k2, k3]) +
	SU3F[6, I4, k2]*((SU3F[I1, I5, k3]*SU3F[I2, k1, k3])/12 -
		(SU3F[I1, I2, k3]*SU3F[I5, k1, k3])/12) + SU3F[6, I2, k2]*
		((SU3F[I1, I5, k3]*SU3F[I4, k1, k3])/12 -
		(SU3F[I1, I4, k3]*SU3F[I5, k1, k3])/12) + SU3D[I2, I4, k1]*
		((-I/3)*SU3F[6, I5, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I5, k2, k3]) + SU3F[6, I4, k3]*
		(-(SU3F[I1, I5, k1]*SU3F[I2, k2, k3])/12 +
		(SU3F[I1, I2, k1]*SU3F[I5, k2, k3])/3) + SU3F[6, I2, k3]*
		(-(SU3F[I1, I5, k1]*SU3F[I4, k2, k3])/12 +
		(SU3F[I1, I4, k1]*SU3F[I5, k2, k3])/3) + SU3D[6, I2, k1]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, I4, k3])/12 +
		(SU3D[I4, k2, k3]*SU3F[I1, I5, k3])/12 - (I/12)*SU3F[I1, I5, k3]*
		SU3F[I4, k2, k3] + (I/12)*SU3F[I1, I4, k3]*SU3F[I5, k2, k3])) +
	SU3D[I2, k1, k2]*(SU3D[I5, k2, k3]*((-I/3)*SU3F[6, I4, k3]*
		SU3F[I1, I3, k1] - (I/3)*SU3F[6, I3, k3]*SU3F[I1, I4, k1]) +
	SU3D[I5, k1, k3]*((-I/12)*SU3F[6, I4, k2]*SU3F[I1, I3, k3] -
		(I/12)*SU3F[6, I3, k2]*SU3F[I1, I4, k3]) + SU3D[I4, k2, k3]*
		((SU3D[I1, I5, k1]*SU3F[6, I3, k3])/4 -
		(SU3D[I1, I3, k1]*SU3F[6, I5, k3])/6 - (I/6)*SU3F[6, I5, k3]*
		SU3F[I1, I3, k1] + (I/12)*SU3F[6, I3, k3]*SU3F[I1, I5, k1] +
		(I/6)*SU3F[6, I1, k3]*SU3F[I3, I5, k1]) + SU3D[I4, k1, k3]*
		(-(SU3D[I3, I5, k2]*SU3F[6, I1, k3])/6 - (I/6)*SU3F[6, I5, k2]*
		SU3F[I1, I3, k3] + (I/12)*SU3F[6, I3, k2]*SU3F[I1, I5, k3] +
		(I/6)*SU3F[6, I1, k2]*SU3F[I3, I5, k3]) - (I/6)*SU3D[I1, I4, k1]*
		SU3F[6, I5, k3]*SU3F[I3, k2, k3] + SU3D[I4, I5, k3]*
		((I/2)*SU3F[6, I3, k1]*SU3F[I1, k2, k3] + (I/6)*SU3F[6, I1, k1]*
		SU3F[I3, k2, k3]) + SU3D[I4, I5, k1]*
		((I/3)*SU3F[6, I3, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I3, k2, k3]) + SU3D[I3, k2, k3]*
		(-(SU3D[I4, I5, k3]*SU3F[6, I1, k1])/6 +
		(SU3D[I1, I5, k1]*SU3F[6, I4, k3])/4 -
		(SU3D[I1, I4, k1]*SU3F[6, I5, k3])/6 - (I/6)*SU3F[6, I5, k3]*
		SU3F[I1, I4, k1] + (I/12)*SU3F[6, I4, k3]*SU3F[I1, I5, k1] +
		(I/6)*SU3F[6, I1, k3]*SU3F[I4, I5, k1] + SU3D[6, I1, k1]*
		((I/6)*SU3D[I4, I5, k3] + SU3F[I4, I5, k3]/6)) +
	SU3D[I3, k1, k3]*(-(SU3D[I4, I5, k2]*SU3F[6, I1, k3])/6 -
		(I/6)*SU3F[6, I5, k2]*SU3F[I1, I4, k3] + (I/12)*SU3F[6, I4, k2]*
		SU3F[I1, I5, k3] + (I/6)*SU3F[6, I1, k2]*SU3F[I4, I5, k3]) +
	SU3F[6, I5, k2]*(-(SU3F[I1, I4, k3]*SU3F[I3, k1, k3])/6 -
		(SU3F[I1, I3, k3]*SU3F[I4, k1, k3])/6) + SU3F[6, I1, k2]*
		((SU3F[I3, k1, k3]*SU3F[I4, I5, k3])/6 +
		(SU3F[I3, I5, k3]*SU3F[I4, k1, k3])/6) - (I/6)*SU3D[I1, I3, k1]*
		SU3F[6, I5, k3]*SU3F[I4, k2, k3] + SU3D[I3, I5, k3]*
		(-(SU3D[I4, k2, k3]*SU3F[6, I1, k1])/6 + (I/2)*SU3F[6, I4, k1]*
		SU3F[I1, k2, k3] + SU3D[6, I1, k1]*((I/6)*SU3D[I4, k2, k3] +
		SU3F[I4, k2, k3]/6) + (I/6)*SU3F[6, I1, k1]*SU3F[I4, k2, k3]) +
	SU3D[I3, I5, k1]*((I/3)*SU3F[6, I4, k3]*SU3F[I1, k2, k3] -
		(I/6)*SU3F[6, I1, k3]*SU3F[I4, k2, k3]) + SU3D[I1, I5, k1]*
		((I/4)*SU3F[6, I4, k3]*SU3F[I3, k2, k3] + (I/4)*SU3F[6, I3, k3]*
		SU3F[I4, k2, k3]) + SU3F[6, I5, k3]*
		((SU3F[I1, I4, k1]*SU3F[I3, k2, k3])/6 +
		(SU3F[I1, I3, k1]*SU3F[I4, k2, k3])/6) + SU3F[6, I1, k3]*
		(-(SU3F[I3, k2, k3]*SU3F[I4, I5, k1])/6 -
		(SU3F[I3, I5, k1]*SU3F[I4, k2, k3])/6) + SU3D[6, I1, k1]*
		((SU3D[I4, k2, k3]*SU3F[I3, I5, k3])/6 +
		(SU3D[I4, I5, k3]*SU3F[I3, k2, k3])/6 - (I/6)*SU3F[I3, k2, k3]*
		SU3F[I4, I5, k3] - (I/6)*SU3F[I3, I5, k3]*SU3F[I4, k2, k3]) +
	SU3F[6, I4, k2]*((SU3F[I1, I5, k3]*SU3F[I3, k1, k3])/12 -
		(SU3F[I1, I3, k3]*SU3F[I5, k1, k3])/12) + SU3F[6, I3, k2]*
		((SU3F[I1, I5, k3]*SU3F[I4, k1, k3])/12 -
		(SU3F[I1, I4, k3]*SU3F[I5, k1, k3])/12) + SU3D[I3, I4, k1]*
		((-I/3)*SU3F[6, I5, k3]*SU3F[I1, k2, k3] - (I/6)*SU3F[6, I1, k3]*
		SU3F[I5, k2, k3]) + SU3F[6, I4, k3]*
		(-(SU3F[I1, I5, k1]*SU3F[I3, k2, k3])/12 +
		(SU3F[I1, I3, k1]*SU3F[I5, k2, k3])/3) + SU3F[6, I3, k3]*
		(-(SU3F[I1, I5, k1]*SU3F[I4, k2, k3])/12 +
		(SU3F[I1, I4, k1]*SU3F[I5, k2, k3])/3) + SU3D[6, I3, k1]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, I4, k3])/12 +
		(SU3D[I4, k2, k3]*SU3F[I1, I5, k3])/12 +
		(SU3D[I4, I5, k3]*SU3F[I1, k2, k3])/2 - (I/12)*SU3F[I1, I5, k3]*
		SU3F[I4, k2, k3] + (I/12)*SU3F[I1, I4, k3]*SU3F[I5, k2, k3])) +
	SU3D[I3, I4, k2]*(-(SU3D[I2, k1, k2]*SU3D[I5, k1, k3]*SU3F[6, I1, k3])/
		6 + (SU3D[I1, k1, k2]*SU3D[I5, k1, k3]*SU3F[6, I2, k3])/2 +
	SU3D[6, I2, k1]*(-(SU3D[I5, k2, k3]*SU3F[I1, k1, k3])/3 +
		(SU3D[I5, k1, k3]*SU3F[I1, k2, k3])/2 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I5, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I5, k2, k3]) +
	SU3D[6, I1, k1]*(-(SU3D[I5, k2, k3]*SU3F[I2, k1, k3])/6 -
		(SU3D[I5, k1, k3]*SU3F[I2, k2, k3])/6 + (I/6)*SU3F[I2, k2, k3]*
		SU3F[I5, k1, k3] - (I/6)*SU3F[I2, k1, k3]*SU3F[I5, k2, k3])) +
	SU3D[I2, I4, k2]*(SU3D[6, I1, k1]*SU3D[I3, k2, k3]*
		((I/6)*SU3D[I5, k1, k3] + SU3F[I5, k1, k3]/6) +
	SU3D[6, I1, k1]*SU3D[I3, k1, k3]*((-I/6)*SU3D[I5, k2, k3] +
		SU3F[I5, k2, k3]/6) + SU3D[6, I3, k1]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, k1, k3])/3 +
		(SU3D[I5, k1, k3]*SU3F[I1, k2, k3])/2 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I5, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I5, k2, k3]) +
	SU3D[6, I1, k1]*(-(SU3D[I5, k2, k3]*SU3F[I3, k1, k3])/6 -
		(SU3D[I5, k1, k3]*SU3F[I3, k2, k3])/6 + (I/6)*SU3F[I3, k2, k3]*
		SU3F[I5, k1, k3] - (I/6)*SU3F[I3, k1, k3]*SU3F[I5, k2, k3])) +
	SU3D[I1, I4, k2]*(SU3D[6, I3, k1]*((SU3D[I5, k2, k3]*SU3F[I2, k1, k3])/
		4 + (I/4)*SU3F[I2, k1, k3]*SU3F[I5, k2, k3]) +
	SU3D[6, I2, k1]*((SU3D[I5, k2, k3]*SU3F[I3, k1, k3])/4 +
		(I/4)*SU3F[I3, k1, k3]*SU3F[I5, k2, k3])) +
	SU3F[I1, I4, k1]*((I/6)*SU3F[I3, I5, k1]*SUNDelta[6, I2] +
	(I/6)*SU3F[I2, I5, k1]*SUNDelta[6, I3]) + SU3F[I1, I3, k1]*
	((I/6)*SU3F[I4, I5, k1]*SUNDelta[6, I2] + (I/6)*SU3F[I2, I5, k1]*
		SUNDelta[6, I4]) + SU3F[I1, I2, k1]*
	((I/6)*SU3F[I4, I5, k1]*SUNDelta[6, I3] + (I/6)*SU3F[I3, I5, k1]*
		SUNDelta[6, I4]) + SU3D[I4, I5, k1]*
	(SU3F[6, I3, k2]*((SU3F[I1, k2, k3]*SU3F[I2, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I2, k2, k3])/2) + SU3F[6, I2, k2]*
		((SU3F[I1, k2, k3]*SU3F[I3, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I3, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I3, k2, k3])/6) +
	(5*SU3F[I1, I3, k1]*SUNDelta[6, I2])/18 +
	(5*SU3F[I1, I2, k1]*SUNDelta[6, I3])/18 -
	(SU3F[6, I3, k1]*SUNDelta[I1, I2])/6 -
	(SU3F[6, I2, k1]*SUNDelta[I1, I3])/6) + SU3D[I3, I5, k1]*
	(SU3F[6, I4, k2]*((SU3F[I1, k2, k3]*SU3F[I2, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I2, k2, k3])/2) + SU3F[6, I2, k2]*
		((SU3F[I1, k2, k3]*SU3F[I4, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I4, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I4, k2, k3])/6) +
	(5*SU3F[I1, I4, k1]*SUNDelta[6, I2])/18 +
	(5*SU3F[I1, I2, k1]*SUNDelta[6, I4])/18 -
	(SU3F[6, I4, k1]*SUNDelta[I1, I2])/6 -
	(SU3F[6, I2, k1]*SUNDelta[I1, I4])/6) + SU3D[I2, I5, k1]*
	(SU3F[6, I4, k2]*((SU3F[I1, k2, k3]*SU3F[I3, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I3, k2, k3])/2) + SU3F[6, I3, k2]*
		((SU3F[I1, k2, k3]*SU3F[I4, k1, k3])/3 -
		(SU3F[I1, k1, k3]*SU3F[I4, k2, k3])/2) + SU3F[6, I1, k2]*
		(-(SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/6) + ((2*I)/9)*SU3D[I3, I4, k1]*
		SUNDelta[6, I1] + ((5*I)/18)*SU3D[I1, I4, k1]*SUNDelta[6, I3] +
	(5*SU3F[I1, I4, k1]*SUNDelta[6, I3])/18 + ((5*I)/18)*SU3D[I1, I3, k1]*
		SUNDelta[6, I4] + (5*SU3F[I1, I3, k1]*SUNDelta[6, I4])/18 -
	(SU3F[6, I4, k1]*SUNDelta[I1, I3])/6 -
	(SU3F[6, I3, k1]*SUNDelta[I1, I4])/6) + SU3D[I3, I4, k1]*
	(SU3F[6, I5, k2]*(-(SU3F[I1, k2, k3]*SU3F[I2, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I2, k2, k3])/2) + SU3F[6, I2, k2]*
		((SU3F[I1, k2, k3]*SU3F[I5, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I5, k2, k3])/2) + SU3F[6, I1, k2]*
		((SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I5, k2, k3])/6) +
	(4*SU3F[I2, I5, k1]*SUNDelta[6, I1])/9 -
	(7*SU3F[I1, I2, k1]*SUNDelta[6, I5])/9 -
	(2*SU3F[6, I5, k1]*SUNDelta[I1, I2])/9 -
	(2*SU3F[6, I1, k1]*SUNDelta[I2, I5])/9) + SU3D[I1, I5, k1]*
	(SU3F[6, I4, k2]*((SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/4 +
		(SU3F[I2, k1, k3]*SU3F[I3, k2, k3])/4) + SU3F[6, I3, k2]*
		((SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/4 +
		(SU3F[I2, k1, k3]*SU3F[I4, k2, k3])/4) + SU3F[6, I2, k2]*
		((SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/4 +
		(SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/4) - ((8*I)/9)*SU3D[I3, I4, k1]*
		SUNDelta[6, I2] + (5*SU3F[6, I4, k1]*SUNDelta[I2, I3])/9 +
	(5*SU3F[6, I3, k1]*SUNDelta[I2, I4])/9 +
	(5*SU3F[6, I2, k1]*SUNDelta[I3, I4])/9) +
	SU3D[6, I5, k1]*(-(SU3D[I2, k1, k2]*SU3D[I3, I4, k3]*SU3F[I1, k2, k3])/
		2 + SU3D[I3, I4, k2]*((-I/2)*SU3F[I1, k2, k3]*SU3F[I2, k1, k3] +
		(I/3)*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]) -
	(SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/6 +
	SU3D[I4, k2, k3]*((I/6)*SU3F[I1, I3, k2]*SU3F[I2, k1, k3] +
		(I/6)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]) + SU3D[I4, k1, k3]*
		(-(SU3D[I1, I3, k2]*SU3F[I2, k2, k3])/6 -
		(SU3D[I1, I2, k2]*SU3F[I3, k2, k3])/6) + SU3D[I4, k1, k2]*
		((I/6)*SU3F[I1, I3, k3]*SU3F[I2, k2, k3] + (I/6)*SU3F[I1, I2, k3]*
		SU3F[I3, k2, k3]) + SU3D[I2, I4, k2]*
		((SU3D[I3, k2, k3]*SU3F[I1, k1, k3])/3 +
		(SU3D[I3, k1, k3]*SU3F[I1, k2, k3])/2 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I3, k1, k3] + (I/3)*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]) +
	SU3D[I1, I4, k2]*((SU3D[I3, k2, k3]*SU3F[I2, k1, k3])/6 +
		(I/6)*SU3F[I2, k2, k3]*SU3F[I3, k1, k3] + (I/6)*SU3F[I2, k1, k3]*
		SU3F[I3, k2, k3]) + SU3D[I1, k2, k3]*
		((-I/2)*SU3D[I2, k1, k3]*SU3D[I3, I4, k2] - (I/2)*SU3D[I2, I4, k2]*
		SU3D[I3, k1, k3] - (I/2)*SU3D[I2, I3, k2]*SU3D[I4, k1, k3] -
		(SU3D[I3, I4, k3]*SU3F[I2, k1, k2])/2 -
		(SU3D[I2, I4, k3]*SU3F[I3, k1, k2])/2 -
		(SU3D[I2, I3, k3]*SU3F[I4, k1, k2])/2) -
	(SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/6 -
	(SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/6 +
	SU3D[I3, k2, k3]*((I/6)*SU3D[I1, I2, k2]*SU3D[I4, k1, k3] -
		(SU3D[I4, k1, k2]*SU3F[I1, I2, k3])/6 + (I/6)*SU3F[I1, I4, k2]*
		SU3F[I2, k1, k3] + (SU3D[I1, I2, k2]*SU3F[I4, k1, k3])/6 +
		(I/6)*SU3F[I1, I2, k2]*SU3F[I4, k1, k3]) + SU3D[I2, k2, k3]*
		((I/6)*SU3D[I1, I4, k2]*SU3D[I3, k1, k3] + (I/6)*SU3D[I1, I3, k2]*
		SU3D[I4, k1, k3] - (SU3D[I4, k1, k2]*SU3F[I1, I3, k3])/6 -
		(SU3D[I3, k1, k2]*SU3F[I1, I4, k3])/6 +
		(SU3D[I3, I4, k3]*SU3F[I1, k1, k2])/3 +
		(SU3D[I1, I4, k2]*SU3F[I3, k1, k3])/6 + (I/6)*SU3F[I1, I4, k2]*
		SU3F[I3, k1, k3] + (SU3D[I1, I3, k2]*SU3F[I4, k1, k3])/6 +
		(I/6)*SU3F[I1, I3, k2]*SU3F[I4, k1, k3]) + SU3D[I3, k1, k3]*
		(-(SU3D[I1, I4, k2]*SU3F[I2, k2, k3])/6 + SU3D[I1, I2, k2]*
		((I/6)*SU3D[I4, k2, k3] - SU3F[I4, k2, k3]/6)) +
	SU3D[I2, k1, k3]*(SU3D[I1, I4, k2]*((I/6)*SU3D[I3, k2, k3] -
		SU3F[I3, k2, k3]/6) + SU3D[I1, I3, k2]*((I/6)*SU3D[I4, k2, k3] -
		SU3F[I4, k2, k3]/6)) + SU3D[I1, k1, k2]*
		((I/3)*SU3D[I2, k2, k3]*SU3D[I3, I4, k3] +
		(SU3D[I3, I4, k3]*SU3F[I2, k2, k3])/3 + SU3D[I2, I4, k3]*
		((I/3)*SU3D[I3, k2, k3] + SU3F[I3, k2, k3]/3) +
		SU3D[I2, I3, k3]*((I/3)*SU3D[I4, k2, k3] + SU3F[I4, k2, k3]/3)) -
	(SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/6 +
	SU3D[I3, k1, k2]*(-(SU3D[I4, k2, k3]*SU3F[I1, I2, k3])/6 +
		(I/6)*SU3F[I1, I4, k3]*SU3F[I2, k2, k3] + (I/6)*SU3F[I1, I2, k3]*
		SU3F[I4, k2, k3]) + SU3F[I2, k1, k3]*
		(-(SU3F[I1, I4, k2]*SU3F[I3, k2, k3])/6 -
		(SU3F[I1, I3, k2]*SU3F[I4, k2, k3])/6) + SU3D[I2, k1, k2]*
		(-(SU3D[I4, k2, k3]*SU3F[I1, I3, k3])/6 -
		(SU3D[I3, k2, k3]*SU3F[I1, I4, k3])/6 + (I/6)*SU3F[I1, I4, k3]*
		SU3F[I3, k2, k3] + (I/6)*SU3F[I1, I3, k3]*SU3F[I4, k2, k3]) +
	SU3D[I2, I3, k2]*((SU3D[I4, k2, k3]*SU3F[I1, k1, k3])/3 +
		(SU3D[I4, k1, k3]*SU3F[I1, k2, k3])/2 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I4, k1, k3] + (I/3)*SU3F[I1, k1, k3]*SU3F[I4, k2, k3]) +
	SU3D[I1, I3, k2]*((SU3D[I4, k2, k3]*SU3F[I2, k1, k3])/6 +
		(I/6)*SU3F[I2, k2, k3]*SU3F[I4, k1, k3] + (I/6)*SU3F[I2, k1, k3]*
		SU3F[I4, k2, k3]) + SU3D[I1, I2, k2]*
		((SU3D[I4, k2, k3]*SU3F[I3, k1, k3])/6 + (I/6)*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3] + (I/6)*SU3F[I3, k1, k3]*SU3F[I4, k2, k3]) +
	((2*I)/9)*SU3D[I3, I4, k1]*SUNDelta[I1, I2] +
	((2*I)/9)*SU3D[I2, I4, k1]*SUNDelta[I1, I3] +
	((2*I)/9)*SU3D[I2, I3, k1]*SUNDelta[I1, I4] - (I/9)*SU3D[I1, I4, k1]*
		SUNDelta[I2, I3] - (5*SU3F[I1, I4, k1]*SUNDelta[I2, I3])/9 -
	(I/9)*SU3D[I1, I3, k1]*SUNDelta[I2, I4] -
	(5*SU3F[I1, I3, k1]*SUNDelta[I2, I4])/9 - (I/9)*SU3D[I1, I2, k1]*
		SUNDelta[I3, I4] - (5*SU3F[I1, I2, k1]*SUNDelta[I3, I4])/9) +
	SU3F[6, I5, k1]*((-I/6)*SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*
		SU3F[I3, k1, k3] - (I/6)*SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*
		SU3F[I4, k1, k3] - (I/6)*SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3] - (I/6)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*
		SU3F[I4, k2, k3] + SU3F[I2, k1, k3]*((-I/6)*SU3F[I1, I4, k2]*
		SU3F[I3, k2, k3] - (I/6)*SU3F[I1, I3, k2]*SU3F[I4, k2, k3]) -
	((5*I)/9)*SU3F[I1, I4, k1]*SUNDelta[I2, I3] -
	((5*I)/9)*SU3F[I1, I3, k1]*SUNDelta[I2, I4] -
	((5*I)/9)*SU3F[I1, I2, k1]*SUNDelta[I3, I4]) +
	SU3F[6, I1, k1]*((I/6)*SU3F[I2, I5, k2]*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3] + SU3F[I2, k2, k3]*((I/6)*SU3F[I3, k1, k3]*
		SU3F[I4, I5, k2] + (I/6)*SU3F[I3, I5, k2]*SU3F[I4, k1, k3]) +
	(I/6)*SU3F[I2, I5, k2]*SU3F[I3, k1, k3]*SU3F[I4, k2, k3] +
	SU3F[I2, k1, k2]*((-I/6)*SU3F[I3, k2, k3]*SU3F[I4, I5, k3] -
		(I/6)*SU3F[I3, I5, k3]*SU3F[I4, k2, k3]) +
	((2*I)/9)*SU3F[I4, I5, k1]*SUNDelta[I2, I3] +
	((2*I)/9)*SU3F[I3, I5, k1]*SUNDelta[I2, I4] +
	((2*I)/9)*SU3F[I2, I5, k1]*SUNDelta[I3, I4]) +
	SUNDelta[6, I5]*(((2*I)/27)*SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	((2*I)/27)*SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	((2*I)/27)*SUNDelta[I1, I2]*SUNDelta[I3, I4]) +
	SU3D[I2, I4, k1]*(SU3F[6, I5, k2]*(-(SU3F[I1, k2, k3]*SU3F[I3, k1, k3])/
		3 + (SU3F[I1, k1, k3]*SU3F[I3, k2, k3])/2) +
	SU3F[6, I3, k2]*((SU3F[I1, k2, k3]*SU3F[I5, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I5, k2, k3])/2) + SU3F[6, I1, k2]*
		((SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/6) + ((2*I)/9)*SU3D[I3, I5, k1]*
		SUNDelta[6, I1] + (4*SU3F[I3, I5, k1]*SUNDelta[6, I1])/9 -
	((8*I)/9)*SU3D[I1, I5, k1]*SUNDelta[6, I3] + (I/9)*SU3D[I1, I3, k1]*
		SUNDelta[6, I5] - (7*SU3F[I1, I3, k1]*SUNDelta[6, I5])/9 -
	(2*SU3F[6, I5, k1]*SUNDelta[I1, I3])/9 -
	(2*SU3F[6, I1, k1]*SUNDelta[I3, I5])/9) + SU3D[I1, I4, k1]*
	(SU3F[6, I5, k2]*(-(SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I3, k2, k3])/6) -
	(SU3F[6, I3, k2]*SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/4 -
	(SU3F[6, I2, k2]*SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/4 +
	((5*I)/18)*SU3D[I3, I5, k1]*SUNDelta[6, I2] -
	(SU3F[I3, I5, k1]*SUNDelta[6, I2])/6 -
	(SU3F[I2, I5, k1]*SUNDelta[6, I3])/6 +
	(SU3F[6, I5, k1]*SUNDelta[I2, I3])/9 -
	(SU3F[6, I3, k1]*SUNDelta[I2, I5])/9 -
	(SU3F[6, I2, k1]*SUNDelta[I3, I5])/9) + SU3F[6, I4, k1]*
	((I/12)*SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3] -
	(I/3)*SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*SU3F[I5, k1, k3] -
	(I/3)*SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I5, k1, k3] -
	(I/12)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SU3F[I5, k2, k3] +
	SU3F[I2, k1, k3]*((I/12)*SU3F[I1, I5, k2]*SU3F[I3, k2, k3] -
		(I/12)*SU3F[I1, I3, k2]*SU3F[I5, k2, k3]) - (I/6)*SU3F[I3, I5, k1]*
		SUNDelta[I1, I2] - (I/6)*SU3F[I2, I5, k1]*SUNDelta[I1, I3] -
	(I/9)*SU3F[I1, I5, k1]*SUNDelta[I2, I3] + ((5*I)/9)*SU3F[I1, I3, k1]*
		SUNDelta[I2, I5] + ((5*I)/9)*SU3F[I1, I2, k1]*SUNDelta[I3, I5]) +
	SU3D[6, I4, k1]*(SU3D[I3, I5, k2]*((I/2)*SU3F[I1, k2, k3]*
		SU3F[I2, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]) +
	(SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3])/12 +
	SU3D[I5, k2, k3]*((I/12)*SU3F[I1, I3, k2]*SU3F[I2, k1, k3] +
		(I/12)*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]) +
	SU3D[I5, k1, k2]*((I/3)*SU3F[I1, I3, k3]*SU3F[I2, k2, k3] +
		(I/3)*SU3F[I1, I2, k3]*SU3F[I3, k2, k3]) + SU3D[I2, I5, k2]*
		((I/2)*SU3F[I1, k2, k3]*SU3F[I3, k1, k3] - (I/3)*SU3F[I1, k1, k3]*
		SU3F[I3, k2, k3]) + SU3D[I1, I5, k2]*
		(-(SU3D[I3, k2, k3]*SU3F[I2, k1, k3])/4 - (I/4)*SU3F[I2, k2, k3]*
		SU3F[I3, k1, k3] - (I/4)*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]) -
	(SU3F[I1, I3, k2]*SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/3 -
	(SU3F[I1, I2, k2]*SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/3 +
	SU3D[I3, k2, k3]*(-(SU3D[I5, k1, k2]*SU3F[I1, I2, k3])/3 -
		(SU3D[I2, I5, k2]*SU3F[I1, k1, k3])/3 - (I/12)*SU3F[I1, I5, k2]*
		SU3F[I2, k1, k3] + (I/3)*SU3F[I1, I2, k2]*SU3F[I5, k1, k3]) +
	SU3D[I3, k1, k3]*(-(SU3D[I2, I5, k2]*SU3F[I1, k2, k3])/2 +
		(SU3D[I1, I5, k2]*SU3F[I2, k2, k3])/4 + SU3D[I1, I2, k2]*
		((I/4)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/4)) -
	(SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/12 +
	SU3D[I3, k1, k2]*(-(SU3D[I5, k2, k3]*SU3F[I1, I2, k3])/12 -
		(I/12)*SU3F[I1, I5, k3]*SU3F[I2, k2, k3] + (I/12)*SU3F[I1, I2, k3]*
		SU3F[I5, k2, k3]) + SU3F[I2, k1, k3]*
		((SU3F[I1, I5, k2]*SU3F[I3, k2, k3])/12 -
		(SU3F[I1, I3, k2]*SU3F[I5, k2, k3])/12) + SU3D[I2, k1, k2]*
		(-(SU3D[I5, k2, k3]*SU3F[I1, I3, k3])/12 +
		(SU3D[I3, k2, k3]*SU3F[I1, I5, k3])/12 +
		(SU3D[I3, I5, k3]*SU3F[I1, k2, k3])/2 - (I/12)*SU3F[I1, I5, k3]*
		SU3F[I3, k2, k3] + (I/12)*SU3F[I1, I3, k3]*SU3F[I5, k2, k3]) +
	SU3D[I2, I3, k2]*(-(SU3D[I5, k2, k3]*SU3F[I1, k1, k3])/3 +
		(SU3D[I5, k1, k3]*SU3F[I1, k2, k3])/2 - (I/2)*SU3F[I1, k2, k3]*
		SU3F[I5, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I5, k2, k3]) +
	SU3D[I1, I3, k2]*((SU3D[I5, k2, k3]*SU3F[I2, k1, k3])/4 +
		(I/4)*SU3F[I2, k1, k3]*SU3F[I5, k2, k3]) + SU3D[I1, I2, k2]*
		((SU3D[I5, k2, k3]*SU3F[I3, k1, k3])/4 + (I/4)*SU3F[I3, k1, k3]*
		SU3F[I5, k2, k3]) + (I/6)*SU3D[I3, I5, k1]*SUNDelta[I1, I2] -
	(SU3F[I3, I5, k1]*SUNDelta[I1, I2])/6 + (I/6)*SU3D[I2, I5, k1]*
		SUNDelta[I1, I3] - (SU3F[I2, I5, k1]*SUNDelta[I1, I3])/6 -
	((5*I)/9)*SU3D[I1, I5, k1]*SUNDelta[I2, I3] -
	(SU3F[I1, I5, k1]*SUNDelta[I2, I3])/9 + (I/9)*SU3D[I1, I3, k1]*
		SUNDelta[I2, I5] + (5*SU3F[I1, I3, k1]*SUNDelta[I2, I5])/9 +
	(I/9)*SU3D[I1, I2, k1]*SUNDelta[I3, I5] +
	(5*SU3F[I1, I2, k1]*SUNDelta[I3, I5])/9) +
	SUNDelta[6, I4]*(((-16*I)/27)*SUNDelta[I1, I5]*SUNDelta[I2, I3] +
	((5*I)/27)*SUNDelta[I1, I3]*SUNDelta[I2, I5] +
	((5*I)/27)*SUNDelta[I1, I2]*SUNDelta[I3, I5]) +
	SU3D[6, I1, k1]*(SU3D[I4, k2, k3]*((-I/6)*SU3F[I2, k1, k3]*
		SU3F[I3, I5, k2] - (I/6)*SU3F[I2, I5, k2]*SU3F[I3, k1, k3]) +
	SU3D[I4, k1, k3]*(-(SU3D[I3, I5, k2]*SU3F[I2, k2, k3])/6 -
		(SU3D[I2, I5, k2]*SU3F[I3, k2, k3])/6) + SU3D[I4, k1, k2]*
		((-I/6)*SU3F[I2, k2, k3]*SU3F[I3, I5, k3] - (I/6)*SU3F[I2, I5, k3]*
		SU3F[I3, k2, k3]) + SU3D[I4, I5, k2]*
		((I/6)*SU3F[I2, k2, k3]*SU3F[I3, k1, k3] + (I/6)*SU3F[I2, k1, k3]*
		SU3F[I3, k2, k3]) + (SU3F[I2, I5, k2]*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3])/6 + SU3F[I2, k2, k3]*
		((SU3F[I3, k1, k3]*SU3F[I4, I5, k2])/6 +
		(SU3F[I3, I5, k2]*SU3F[I4, k1, k3])/6) +
	(SU3F[I2, I5, k2]*SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/6 +
	SU3D[I3, I5, k2]*((SU3D[I4, k2, k3]*SU3F[I2, k1, k3])/6 +
		(I/6)*SU3F[I2, k2, k3]*SU3F[I4, k1, k3] + (I/6)*SU3F[I2, k1, k3]*
		SU3F[I4, k2, k3]) + SU3F[I2, k1, k2]*
		(-(SU3F[I3, k2, k3]*SU3F[I4, I5, k3])/6 -
		(SU3F[I3, I5, k3]*SU3F[I4, k2, k3])/6) + SU3D[I2, I5, k2]*
		((SU3D[I4, k2, k3]*SU3F[I3, k1, k3])/6 + (I/6)*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3] + (I/6)*SU3F[I3, k1, k3]*SU3F[I4, k2, k3]) +
	SU3D[I2, I3, k2]*(-(SU3D[I5, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3D[I5, k1, k3]*SU3F[I4, k2, k3])/6 + SU3D[I4, k2, k3]*
		((I/6)*SU3D[I5, k1, k3] + SU3F[I5, k1, k3]/6) +
		(I/6)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] + SU3D[I4, k1, k3]*
		((-I/6)*SU3D[I5, k2, k3] + SU3F[I5, k2, k3]/6) -
		(I/6)*SU3F[I4, k1, k3]*SU3F[I5, k2, k3]) +
	(2*SU3F[I4, I5, k1]*SUNDelta[I2, I3])/9 +
	(2*SU3F[I3, I5, k1]*SUNDelta[I2, I4])/9 + ((2*I)/9)*SU3D[I3, I4, k1]*
		SUNDelta[I2, I5] + (2*SU3F[I2, I5, k1]*SUNDelta[I3, I4])/9 +
	((2*I)/9)*SU3D[I2, I4, k1]*SUNDelta[I3, I5] +
	((2*I)/9)*SU3D[I2, I3, k1]*SUNDelta[I4, I5]) +
	SU3D[I2, I3, k1]*(SU3F[6, I5, k2]*(-(SU3F[I1, k2, k3]*SU3F[I4, k1, k3])/
		3 + (SU3F[I1, k1, k3]*SU3F[I4, k2, k3])/2) +
	SU3F[6, I4, k2]*((SU3F[I1, k2, k3]*SU3F[I5, k1, k3])/3 +
		(SU3F[I1, k1, k3]*SU3F[I5, k2, k3])/2) + SU3F[6, I1, k2]*
		((SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/6 -
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/6) + ((2*I)/9)*SU3D[I4, I5, k1]*
		SUNDelta[6, I1] + (4*SU3F[I4, I5, k1]*SUNDelta[6, I1])/9 -
	((8*I)/9)*SU3D[I1, I5, k1]*SUNDelta[6, I4] + (I/9)*SU3D[I1, I4, k1]*
		SUNDelta[6, I5] - (7*SU3F[I1, I4, k1]*SUNDelta[6, I5])/9 -
	(2*SU3F[6, I5, k1]*SUNDelta[I1, I4])/9 -
	(2*SU3F[6, I1, k1]*SUNDelta[I4, I5])/9) + SU3D[I1, I3, k1]*
	(SU3F[6, I5, k2]*(-(SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I2, k1, k3]*SU3F[I4, k2, k3])/6) -
	(SU3F[6, I4, k2]*SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/4 -
	(SU3F[6, I2, k2]*SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/4 +
	((5*I)/18)*SU3D[I4, I5, k1]*SUNDelta[6, I2] -
	(SU3F[I4, I5, k1]*SUNDelta[6, I2])/6 -
	(SU3F[I2, I5, k1]*SUNDelta[6, I4])/6 +
	(SU3F[6, I5, k1]*SUNDelta[I2, I4])/9 -
	(SU3F[6, I4, k1]*SUNDelta[I2, I5])/9 -
	(SU3F[6, I2, k1]*SUNDelta[I4, I5])/9) + SU3D[I1, I2, k1]*
	(SU3F[6, I5, k2]*(-(SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/6 -
		(SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/6) -
	(SU3F[6, I4, k2]*SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/4 -
	(SU3F[6, I3, k2]*SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/4 +
	((5*I)/18)*SU3D[I4, I5, k1]*SUNDelta[6, I3] -
	(SU3F[I4, I5, k1]*SUNDelta[6, I3])/6 + ((5*I)/18)*SU3D[I3, I5, k1]*
		SUNDelta[6, I4] - (SU3F[I3, I5, k1]*SUNDelta[6, I4])/6 +
	(I/9)*SU3D[I3, I4, k1]*SUNDelta[6, I5] +
	(SU3F[6, I5, k1]*SUNDelta[I3, I4])/9 -
	(SU3F[6, I4, k1]*SUNDelta[I3, I5])/9 -
	(SU3F[6, I3, k1]*SUNDelta[I4, I5])/9) + SU3F[6, I3, k1]*
	((I/12)*SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3] -
	(I/3)*SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*SU3F[I5, k1, k3] +
	SU3F[I2, k1, k3]*((I/12)*SU3F[I1, I5, k2]*SU3F[I4, k2, k3] -
		(I/12)*SU3F[I1, I4, k2]*SU3F[I5, k2, k3]) +
	SU3F[I1, I2, k2]*((-I/3)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] -
		(I/12)*SU3F[I4, k1, k3]*SU3F[I5, k2, k3]) - (I/6)*SU3F[I4, I5, k1]*
		SUNDelta[I1, I2] - (I/6)*SU3F[I2, I5, k1]*SUNDelta[I1, I4] -
	(I/9)*SU3F[I1, I5, k1]*SUNDelta[I2, I4] + ((5*I)/9)*SU3F[I1, I4, k1]*
		SUNDelta[I2, I5] + ((5*I)/9)*SU3F[I1, I2, k1]*SUNDelta[I4, I5]) +
	SU3D[6, I3, k1]*((SU3F[I1, I5, k2]*SU3F[I2, k2, k3]*SU3F[I4, k1, k3])/
		12 + SU3D[I5, k2, k3]*((I/12)*SU3F[I1, I4, k2]*SU3F[I2, k1, k3] +
		(I/12)*SU3F[I1, I2, k2]*SU3F[I4, k1, k3]) +
	SU3D[I5, k1, k2]*((I/3)*SU3F[I1, I4, k3]*SU3F[I2, k2, k3] +
		(I/3)*SU3F[I1, I2, k3]*SU3F[I4, k2, k3]) + SU3D[I2, I5, k2]*
		(-(SU3D[I4, k2, k3]*SU3F[I1, k1, k3])/3 + (I/2)*SU3F[I1, k2, k3]*
		SU3F[I4, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I4, k2, k3]) -
	(SU3F[I1, I4, k2]*SU3F[I2, k2, k3]*SU3F[I5, k1, k3])/3 +
	SU3D[I4, k2, k3]*(-(SU3D[I5, k1, k2]*SU3F[I1, I2, k3])/3 -
		(I/12)*SU3F[I1, I5, k2]*SU3F[I2, k1, k3] + (I/3)*SU3F[I1, I2, k2]*
		SU3F[I5, k1, k3]) + SU3D[I4, k1, k3]*
		(-(SU3D[I2, I5, k2]*SU3F[I1, k2, k3])/2 + SU3D[I1, I2, k2]*
		((I/4)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/4)) +
	SU3D[I4, k1, k2]*(-(SU3D[I5, k2, k3]*SU3F[I1, I2, k3])/12 -
		(I/12)*SU3F[I1, I5, k3]*SU3F[I2, k2, k3] + (I/12)*SU3F[I1, I2, k3]*
		SU3F[I5, k2, k3]) + SU3F[I2, k1, k3]*
		((SU3F[I1, I5, k2]*SU3F[I4, k2, k3])/12 -
		(SU3F[I1, I4, k2]*SU3F[I5, k2, k3])/12) + SU3F[I1, I2, k2]*
		(-(SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/3 -
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/12) + SU3D[I1, I2, k2]*
		((SU3D[I5, k2, k3]*SU3F[I4, k1, k3])/4 + (I/4)*SU3F[I4, k1, k3]*
		SU3F[I5, k2, k3]) + (I/6)*SU3D[I4, I5, k1]*SUNDelta[I1, I2] -
	(SU3F[I4, I5, k1]*SUNDelta[I1, I2])/6 + (I/6)*SU3D[I2, I5, k1]*
		SUNDelta[I1, I4] - (SU3F[I2, I5, k1]*SUNDelta[I1, I4])/6 -
	((5*I)/9)*SU3D[I1, I5, k1]*SUNDelta[I2, I4] -
	(SU3F[I1, I5, k1]*SUNDelta[I2, I4])/9 + (I/9)*SU3D[I1, I4, k1]*
		SUNDelta[I2, I5] + (5*SU3F[I1, I4, k1]*SUNDelta[I2, I5])/9 +
	(I/9)*SU3D[I1, I2, k1]*SUNDelta[I4, I5] +
	(5*SU3F[I1, I2, k1]*SUNDelta[I4, I5])/9) +
	SU3F[6, I2, k1]*(SU3F[I1, I5, k2]*((I/12)*SU3F[I3, k2, k3]*
		SU3F[I4, k1, k3] + (I/12)*SU3F[I3, k1, k3]*SU3F[I4, k2, k3]) +
	SU3F[I1, I4, k2]*((-I/3)*SU3F[I3, k2, k3]*SU3F[I5, k1, k3] -
		(I/12)*SU3F[I3, k1, k3]*SU3F[I5, k2, k3]) +
	SU3F[I1, I3, k2]*((-I/3)*SU3F[I4, k2, k3]*SU3F[I5, k1, k3] -
		(I/12)*SU3F[I4, k1, k3]*SU3F[I5, k2, k3]) - (I/6)*SU3F[I4, I5, k1]*
		SUNDelta[I1, I3] - (I/6)*SU3F[I3, I5, k1]*SUNDelta[I1, I4] -
	(I/9)*SU3F[I1, I5, k1]*SUNDelta[I3, I4] + ((5*I)/9)*SU3F[I1, I4, k1]*
		SUNDelta[I3, I5] + ((5*I)/9)*SU3F[I1, I3, k1]*SUNDelta[I4, I5]) +
	SU3D[6, I2, k1]*(SU3D[I5, k2, k3]*((I/12)*SU3F[I1, I4, k2]*
		SU3F[I3, k1, k3] + (I/12)*SU3F[I1, I3, k2]*SU3F[I4, k1, k3]) +
	SU3D[I5, k1, k2]*((I/3)*SU3F[I1, I4, k3]*SU3F[I3, k2, k3] +
		(I/3)*SU3F[I1, I3, k3]*SU3F[I4, k2, k3]) + SU3D[I3, I5, k2]*
		(-(SU3D[I4, k2, k3]*SU3F[I1, k1, k3])/3 + (I/2)*SU3F[I1, k2, k3]*
		SU3F[I4, k1, k3] - (I/3)*SU3F[I1, k1, k3]*SU3F[I4, k2, k3]) +
	SU3F[I1, I5, k2]*((SU3F[I3, k2, k3]*SU3F[I4, k1, k3])/12 +
		(SU3F[I3, k1, k3]*SU3F[I4, k2, k3])/12) + SU3D[I4, k2, k3]*
		(-(SU3D[I5, k1, k2]*SU3F[I1, I3, k3])/3 - (I/12)*SU3F[I1, I5, k2]*
		SU3F[I3, k1, k3] + (I/3)*SU3F[I1, I3, k2]*SU3F[I5, k1, k3]) +
	SU3D[I4, k1, k3]*(-(SU3D[I3, I5, k2]*SU3F[I1, k2, k3])/2 +
		SU3D[I1, I3, k2]*((I/4)*SU3D[I5, k2, k3] - SU3F[I5, k2, k3]/4)) +
	SU3D[I4, k1, k2]*(-(SU3D[I5, k2, k3]*SU3F[I1, I3, k3])/12 -
		(I/12)*SU3F[I1, I5, k3]*SU3F[I3, k2, k3] + (I/12)*SU3F[I1, I3, k3]*
		SU3F[I5, k2, k3]) + SU3F[I1, I4, k2]*
		(-(SU3F[I3, k2, k3]*SU3F[I5, k1, k3])/3 -
		(SU3F[I3, k1, k3]*SU3F[I5, k2, k3])/12) + SU3F[I1, I3, k2]*
		(-(SU3F[I4, k2, k3]*SU3F[I5, k1, k3])/3 -
		(SU3F[I4, k1, k3]*SU3F[I5, k2, k3])/12) + SU3D[I1, I3, k2]*
		((SU3D[I5, k2, k3]*SU3F[I4, k1, k3])/4 + (I/4)*SU3F[I4, k1, k3]*
		SU3F[I5, k2, k3]) + (I/6)*SU3D[I4, I5, k1]*SUNDelta[I1, I3] -
	(SU3F[I4, I5, k1]*SUNDelta[I1, I3])/6 + (I/6)*SU3D[I3, I5, k1]*
		SUNDelta[I1, I4] - (SU3F[I3, I5, k1]*SUNDelta[I1, I4])/6 -
	((5*I)/9)*SU3D[I1, I5, k1]*SUNDelta[I3, I4] -
	(SU3F[I1, I5, k1]*SUNDelta[I3, I4])/9 + (I/9)*SU3D[I1, I4, k1]*
		SUNDelta[I3, I5] + (5*SU3F[I1, I4, k1]*SUNDelta[I3, I5])/9 +
	(I/9)*SU3D[I1, I3, k1]*SUNDelta[I4, I5] +
	(5*SU3F[I1, I3, k1]*SUNDelta[I4, I5])/9) +
	SUNDelta[6, I3]*(((-16*I)/27)*SUNDelta[I1, I5]*SUNDelta[I2, I4] +
	((5*I)/27)*SUNDelta[I1, I4]*SUNDelta[I2, I5] +
	((5*I)/27)*SUNDelta[I1, I2]*SUNDelta[I4, I5]) +
	SUNDelta[6, I2]*(((-16*I)/27)*SUNDelta[I1, I5]*SUNDelta[I3, I4] +
	((5*I)/27)*SUNDelta[I1, I4]*SUNDelta[I3, I5] +
	((5*I)/27)*SUNDelta[I1, I3]*SUNDelta[I4, I5]) +
	SUNDelta[6, I1]*(((4*I)/27)*SUNDelta[I2, I5]*SUNDelta[I3, I4] +
	((4*I)/27)*SUNDelta[I2, I4]*SUNDelta[I3, I5] +
	((4*I)/27)*SUNDelta[I2, I3]*SUNDelta[I4, I5])))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}}
