{{(((-32*I)/3)*(3*CouplingConstant[ChPT3[4], 8, RenormalizationState[0]]*
	SU3D[3, I1, I2] + Sqrt[3]*CouplingConstant[ChPT3[4], 8,
	RenormalizationState[0]]*SU3D[8, I1, I2] -
	3*CouplingConstant[ChPT3[4], 6, RenormalizationState[0]]*
	SUNDelta[I1, I2] - CouplingConstant[ChPT3[4], 8,
	RenormalizationState[0]]*SUNDelta[I1, I2]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]},
{(((32*I)/3)*(3*CouplingConstant[ChPT3[4], 8, RenormalizationState[0]]*
	SU3D[3, I1, I2] - Sqrt[3]*CouplingConstant[ChPT3[4], 8,
	RenormalizationState[0]]*SU3D[8, I1, I2] +
	3*CouplingConstant[ChPT3[4], 6, RenormalizationState[0]]*
	SUNDelta[I1, I2] + CouplingConstant[ChPT3[4], 8,
	RenormalizationState[0]]*SUNDelta[I1, I2]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]},
{(((32*I)/3)*(2*Sqrt[3]*CouplingConstant[ChPT3[4], 8,
	RenormalizationState[0]]*SU3D[8, I1, I2] +
	3*CouplingConstant[ChPT3[4], 6, RenormalizationState[0]]*
	SUNDelta[I1, I2] + CouplingConstant[ChPT3[4], 8,
	RenormalizationState[0]]*SUNDelta[I1, I2]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]}}
