{{((8*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 11]*
	SUNDelta[7, I1])/DecayConstant[PseudoScalar[1], RenormalizationState[0]]^
	3}, {((-8*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4],
	11]*SUNDelta[7, I1])/DecayConstant[PseudoScalar[1],
	RenormalizationState[0]]^3},
{((8*I)*(2*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 10]*
	SUNDelta[7, I1] + CouplingConstant[ChPTW3[2], 1]*
	CouplingConstant[ChPTW3[4], 11]*SUNDelta[7, I1]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3},
{((-8*I)*(2*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 10]*
	SUNDelta[7, I1] + CouplingConstant[ChPTW3[2], 1]*
	CouplingConstant[ChPTW3[4], 11]*SUNDelta[7, I1]))/
DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}}
