{{(-18*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I1, k1, k2]*
     SU3D[I2, I3, k2] - 18*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*
     SU3D[I1, k1, k2]*SU3D[I2, I4, k2] - 12*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I4, k1]*SU3D[I1, I3, k2]*SU3D[I2, k1, k2] - 
    12*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I1, I4, k2]*
     SU3D[I2, k1, k2] + 18*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I1, k1, k2]*SU3D[I3, I4, k2] + 12*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, I4, k2] + 
    15*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I1, I2, k2]*
     SU3D[I3, k1, k2] - 3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I1, I4, k2]*SU3D[I3, k1, k2] + 3*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I2, I4, k2]*SU3D[I3, k1, k2] + 
    15*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*
     SU3D[I4, k1, k2] - 3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I1, I3, k2]*SU3D[I4, k1, k2] + 3*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I2, I3, k2]*SU3D[I4, k1, k2] + 
    (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, k1, k2]*SU3D[I3, I4, k1]*
     SU3F[6, I1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I4, k1]*
     SU3D[I3, k1, k2]*SU3F[6, I1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I2, I3, k1]*SU3D[I4, k1, k2]*SU3F[6, I1, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, k1, k2]*SU3D[I3, I4, k1]*
     SU3F[6, I2, k2] - (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I4, k1]*
     SU3D[I3, k1, k2]*SU3F[6, I2, k2] - (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I3, k1]*SU3D[I4, k1, k2]*SU3F[6, I2, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, k1, k2]*SU3D[I2, I4, k1]*
     SU3F[6, I3, k2] - (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I4, k1]*
     SU3D[I2, k1, k2]*SU3F[6, I3, k2] + (15*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I2, k1]*SU3D[I4, k1, k2]*SU3F[6, I3, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I4, k2] - (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I3, k1]*
     SU3D[I2, k1, k2]*SU3F[6, I4, k2] + (15*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I4, k2] - 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[I4, k1, k2]*SU3F[6, I3, k2]*
     SU3F[I1, I2, k1] - 3*CouplingConstant[ChPTW3[2], 1]*SU3D[I3, k1, k2]*
     SU3F[6, I4, k2]*SU3F[I1, I2, k1] + (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I4, k1]*SU3D[I3, k1, k2]*SU3F[I1, I2, k2] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I4, k1, k2]*
     SU3F[I1, I2, k2] + 15*CouplingConstant[ChPTW3[2], 1]*SU3D[I4, k1, k2]*
     SU3F[6, I2, k2]*SU3F[I1, I3, k1] + 6*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I2, k1, k2]*SU3F[6, I4, k2]*SU3F[I1, I3, k1] - 
    (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I2, k1, k2]*
     SU3F[I1, I3, k2] - (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I4, k1, k2]*SU3F[I1, I3, k2] + 15*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I3, k1, k2]*SU3F[6, I2, k2]*SU3F[I1, I4, k1] + 
    6*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, k1, k2]*SU3F[6, I3, k2]*
     SU3F[I1, I4, k1] - (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*
     SU3D[I2, k1, k2]*SU3F[I1, I4, k2] - 
    (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[I1, I4, k2] + (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*
     SU3D[I2, I3, k2]*SU3F[I1, k1, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I2, I4, k2]*
     SU3F[I1, k1, k2] - (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I3, I4, k2]*SU3F[I1, k1, k2] - 18*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I3, I4, k1]*SU3F[6, I2, k2]*SU3F[I1, k1, k2] + 
    18*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I4, k1]*SU3F[6, I3, k2]*
     SU3F[I1, k1, k2] + 18*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I3, k1]*
     SU3F[6, I4, k2]*SU3F[I1, k1, k2] + 9*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I4, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1] - 
    (9*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*SU3D[I4, k1, k2]*
     SU3F[I2, I3, k2] + 9*CouplingConstant[ChPTW3[2], 1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2]*SU3F[I2, I4, k1] - (9*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I3, k1, k2]*SU3F[I2, I4, k2] + 
    (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I1, I3, k2]*
     SU3F[I2, k1, k2] + (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*
     SU3D[I1, I4, k2]*SU3F[I2, k1, k2] - 
    (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*SU3D[I3, I4, k2]*
     SU3F[I2, k1, k2] - 12*CouplingConstant[ChPTW3[2], 1]*SU3D[I3, I4, k1]*
     SU3F[6, I1, k2]*SU3F[I2, k1, k2] + 12*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I4, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I3, k1]*SU3F[6, I4, k2]*
     SU3F[I2, k1, k2] - 6*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*
     SU3F[I1, I3, k2]*SU3F[I2, k1, k2] - (6*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I4, k1]*SU3F[I1, I3, k2]*SU3F[I2, k1, k2] - 
    6*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3F[I1, I4, k2]*
     SU3F[I2, k1, k2] - (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I3, k1]*
     SU3F[I1, I4, k2]*SU3F[I2, k1, k2] - 
    (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I1, I2, k2]*
     SU3F[I3, k1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I1, I4, k2]*SU3F[I3, k1, k2] - (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I2, I4, k2]*SU3F[I3, k1, k2] - 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I4, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] + 3*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I4, k1]*
     SU3F[6, I2, k2]*SU3F[I3, k1, k2] - 15*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I2, k1]*SU3F[6, I4, k2]*SU3F[I3, k1, k2] + 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3F[I1, I2, k2]*
     SU3F[I3, k1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I4, k1]*
     SU3F[I1, I2, k2]*SU3F[I3, k1, k2] - 15*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I2, k1]*SU3F[I1, I4, k2]*SU3F[I3, k1, k2] - 
    (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I2, k1]*SU3F[I1, I4, k2]*
     SU3F[I3, k1, k2] - 9*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*
     SU3F[I2, I4, k2]*SU3F[I3, k1, k2] - (9*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I1, k1]*SU3F[I2, I4, k2]*SU3F[I3, k1, k2] - 
    (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*
     SU3F[I4, k1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I1, I3, k2]*SU3F[I4, k1, k2] - (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I2, I3, k2]*SU3F[I4, k1, k2] - 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I4, k1, k2] + 3*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I3, k1]*
     SU3F[6, I2, k2]*SU3F[I4, k1, k2] - 15*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I2, k1]*SU3F[6, I3, k2]*SU3F[I4, k1, k2] + 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3F[I1, I2, k2]*
     SU3F[I4, k1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I3, k1]*
     SU3F[I1, I2, k2]*SU3F[I4, k1, k2] - 15*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I2, k1]*SU3F[I1, I3, k2]*SU3F[I4, k1, k2] - 
    (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I2, k1]*SU3F[I1, I3, k2]*
     SU3F[I4, k1, k2] - 9*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*
     SU3F[I2, I3, k2]*SU3F[I4, k1, k2] - (9*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I1, k1]*SU3F[I2, I3, k2]*SU3F[I4, k1, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I3, I4]*SUNDelta[6, I1] + 
    8*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I3, I4]*SUNDelta[6, I2] - 
    10*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I2, I4]*SUNDelta[6, I3] + 
    (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[I1, I2, I4]*SUNDelta[6, I3] - 
    10*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I2, I3]*SUNDelta[6, I4] + 
    (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[I1, I2, I3]*SUNDelta[6, I4] - 
    10*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, I4]*SUNDelta[I1, I3] + 
    (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I2, I4]*SUNDelta[I1, I3] - 
    10*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, I3]*SUNDelta[I1, I4] + 
    (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I2, I3]*SUNDelta[I1, I4] - 
    10*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, I4]*SUNDelta[I2, I3] + 
    (14*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I1, I4]*SUNDelta[I2, I3] - 
    10*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, I3]*SUNDelta[I2, I4] + 
    (14*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I1, I3]*SUNDelta[I2, I4] + 
    20*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, I2]*SUNDelta[I3, I4] - 
    (4*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I1, I2]*SUNDelta[I3, I4])/
   (18*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(-18*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I1, k1, k2]*
     SU3D[I2, I3, k2] + 18*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*
     SU3D[I1, k1, k2]*SU3D[I2, I4, k2] + 15*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I4, k1]*SU3D[I1, I3, k2]*SU3D[I2, k1, k2] - 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I1, I4, k2]*
     SU3D[I2, k1, k2] - 18*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I1, k1, k2]*SU3D[I3, I4, k2] + 3*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, I4, k2] - 
    12*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I1, I2, k2]*
     SU3D[I3, k1, k2] - 12*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I1, I4, k2]*SU3D[I3, k1, k2] + 12*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I2, I4, k2]*SU3D[I3, k1, k2] - 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*
     SU3D[I4, k1, k2] + 15*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I1, I3, k2]*SU3D[I4, k1, k2] + 3*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I2, I3, k2]*SU3D[I4, k1, k2] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, k1, k2]*SU3D[I3, I4, k1]*
     SU3F[6, I1, k2] + (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I4, k1]*
     SU3D[I3, k1, k2]*SU3F[6, I1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I2, I3, k1]*SU3D[I4, k1, k2]*SU3F[6, I1, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, k1, k2]*SU3D[I3, I4, k1]*
     SU3F[6, I2, k2] - (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I4, k1]*
     SU3D[I3, k1, k2]*SU3F[6, I2, k2] + (15*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I3, k1]*SU3D[I4, k1, k2]*SU3F[6, I2, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, k1, k2]*SU3D[I2, I4, k1]*
     SU3F[6, I3, k2] - (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I4, k1]*
     SU3D[I2, k1, k2]*SU3F[6, I3, k2] - (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I2, k1]*SU3D[I4, k1, k2]*SU3F[6, I3, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I4, k2] + (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I3, k1]*
     SU3D[I2, k1, k2]*SU3F[6, I4, k2] - (12*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I4, k2] + 
    15*CouplingConstant[ChPTW3[2], 1]*SU3D[I4, k1, k2]*SU3F[6, I3, k2]*
     SU3F[I1, I2, k1] + 6*CouplingConstant[ChPTW3[2], 1]*SU3D[I3, k1, k2]*
     SU3F[6, I4, k2]*SU3F[I1, I2, k1] - (6*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I4, k1]*SU3D[I3, k1, k2]*SU3F[I1, I2, k2] - 
    (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I4, k1, k2]*
     SU3F[I1, I2, k2] - 3*CouplingConstant[ChPTW3[2], 1]*SU3D[I4, k1, k2]*
     SU3F[6, I2, k2]*SU3F[I1, I3, k1] - 3*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I2, k1, k2]*SU3F[6, I4, k2]*SU3F[I1, I3, k1] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I2, k1, k2]*
     SU3F[I1, I3, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I4, k1, k2]*SU3F[I1, I3, k2] + 6*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I3, k1, k2]*SU3F[6, I2, k2]*SU3F[I1, I4, k1] + 
    15*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, k1, k2]*SU3F[6, I3, k2]*
     SU3F[I1, I4, k1] - (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*
     SU3D[I2, k1, k2]*SU3F[I1, I4, k2] - (6*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I2, k1]*SU3D[I3, k1, k2]*SU3F[I1, I4, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I2, I3, k2]*
     SU3F[I1, k1, k2] - (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*
     SU3D[I2, I4, k2]*SU3F[I1, k1, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*SU3D[I3, I4, k2]*
     SU3F[I1, k1, k2] + 18*CouplingConstant[ChPTW3[2], 1]*SU3D[I3, I4, k1]*
     SU3F[6, I2, k2]*SU3F[I1, k1, k2] - 18*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I2, I4, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] + 
    18*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I3, k1]*SU3F[6, I4, k2]*
     SU3F[I1, k1, k2] - 9*CouplingConstant[ChPTW3[2], 1]*SU3D[I4, k1, k2]*
     SU3F[6, I1, k2]*SU3F[I2, I3, k1] + (9*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I4, k1, k2]*SU3F[I2, I3, k2] - 
    (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I1, I3, k2]*
     SU3F[I2, k1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*
     SU3D[I1, I4, k2]*SU3F[I2, k1, k2] - (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I3, I4, k2]*SU3F[I2, k1, k2] - 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[I3, I4, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] + 3*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I4, k1]*
     SU3F[6, I3, k2]*SU3F[I2, k1, k2] - 15*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I3, k1]*SU3F[6, I4, k2]*SU3F[I2, k1, k2] + 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3F[I1, I3, k2]*
     SU3F[I2, k1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I4, k1]*
     SU3F[I1, I3, k2]*SU3F[I2, k1, k2] - 15*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I3, k1]*SU3F[I1, I4, k2]*SU3F[I2, k1, k2] - 
    (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I3, k1]*SU3F[I1, I4, k2]*
     SU3F[I2, k1, k2] + 9*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2]*SU3F[I3, I4, k1] - (9*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3F[I3, I4, k2] - 
    9*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*SU3F[I2, k1, k2]*
     SU3F[I3, I4, k2] - (9*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I1, k1]*
     SU3F[I2, k1, k2]*SU3F[I3, I4, k2] + 
    (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I1, I2, k2]*
     SU3F[I3, k1, k2] + (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I1, I4, k2]*SU3F[I3, k1, k2] - 
    (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*SU3D[I2, I4, k2]*
     SU3F[I3, k1, k2] - 12*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I4, k1]*
     SU3F[6, I1, k2]*SU3F[I3, k1, k2] + 12*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I4, k1]*SU3F[6, I2, k2]*SU3F[I3, k1, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I2, k1]*SU3F[6, I4, k2]*
     SU3F[I3, k1, k2] - 6*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*
     SU3F[I1, I2, k2]*SU3F[I3, k1, k2] - (6*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I4, k1]*SU3F[I1, I2, k2]*SU3F[I3, k1, k2] - 
    6*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*SU3F[I1, I4, k2]*
     SU3F[I3, k1, k2] - (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I2, k1]*
     SU3F[I1, I4, k2]*SU3F[I3, k1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I3, k1]*SU3D[I1, I2, k2]*SU3F[I4, k1, k2] - 
    (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*
     SU3F[I4, k1, k2] - (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*
     SU3D[I2, I3, k2]*SU3F[I4, k1, k2] - 3*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I2, I3, k1]*SU3F[6, I1, k2]*SU3F[I4, k1, k2] - 
    15*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I3, k1]*SU3F[6, I2, k2]*
     SU3F[I4, k1, k2] + 3*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I2, k1]*
     SU3F[6, I3, k2]*SU3F[I4, k1, k2] - 15*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I3, k1]*SU3F[I1, I2, k2]*SU3F[I4, k1, k2] - 
    (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I3, k1]*SU3F[I1, I2, k2]*
     SU3F[I4, k1, k2] + 3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3F[I1, I3, k2]*SU3F[I4, k1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I2, k1]*SU3F[I1, I3, k2]*SU3F[I4, k1, k2] + 
    9*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*SU3F[I2, I3, k2]*
     SU3F[I4, k1, k2] + (9*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I1, k1]*
     SU3F[I2, I3, k2]*SU3F[I4, k1, k2] + 12*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I2, I3, I4]*SUNDelta[6, I1] - 10*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I3, I4]*SUNDelta[6, I2] + (6*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[I1, I3, I4]*SUNDelta[6, I2] + 8*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I2, I4]*SUNDelta[6, I3] - 10*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I2, I3]*SUNDelta[6, I4] - (6*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[I1, I2, I3]*SUNDelta[6, I4] - 10*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I3, I4]*SUNDelta[I1, I2] + (6*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I3, I4]*SUNDelta[I1, I2] - 10*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I2, I3]*SUNDelta[I1, I4] - (6*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I2, I3]*SUNDelta[I1, I4] - 10*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, I4]*SUNDelta[I2, I3] + (14*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I1, I4]*SUNDelta[I2, I3] + 20*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, I3]*SUNDelta[I2, I4] - (4*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I1, I3]*SUNDelta[I2, I4] - 10*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, I2]*SUNDelta[I3, I4] + (14*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I1, I2]*SUNDelta[I3, I4])/
   (18*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(18*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I1, k1, k2]*
     SU3D[I2, I3, k2] - 18*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*
     SU3D[I1, k1, k2]*SU3D[I2, I4, k2] - 3*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I4, k1]*SU3D[I1, I3, k2]*SU3D[I2, k1, k2] + 
    15*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I1, I4, k2]*
     SU3D[I2, k1, k2] - 18*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I1, k1, k2]*SU3D[I3, I4, k2] + 3*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, I4, k2] - 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I1, I2, k2]*
     SU3D[I3, k1, k2] + 15*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I1, I4, k2]*SU3D[I3, k1, k2] + 3*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I2, I4, k2]*SU3D[I3, k1, k2] - 
    12*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*
     SU3D[I4, k1, k2] - 12*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I1, I3, k2]*SU3D[I4, k1, k2] + 12*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I2, I3, k2]*SU3D[I4, k1, k2] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, k1, k2]*SU3D[I3, I4, k1]*
     SU3F[6, I1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I4, k1]*
     SU3D[I3, k1, k2]*SU3F[6, I1, k2] + (12*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I2, I3, k1]*SU3D[I4, k1, k2]*SU3F[6, I1, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, k1, k2]*SU3D[I3, I4, k1]*
     SU3F[6, I2, k2] + (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I4, k1]*
     SU3D[I3, k1, k2]*SU3F[6, I2, k2] - (12*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I3, k1]*SU3D[I4, k1, k2]*SU3F[6, I2, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, k1, k2]*SU3D[I2, I4, k1]*
     SU3F[6, I3, k2] + (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I4, k1]*
     SU3D[I2, k1, k2]*SU3F[6, I3, k2] - (12*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I2, k1]*SU3D[I4, k1, k2]*SU3F[6, I3, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I4, k2] - (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I3, k1]*
     SU3D[I2, k1, k2]*SU3F[6, I4, k2] - (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I4, k2] + 
    6*CouplingConstant[ChPTW3[2], 1]*SU3D[I4, k1, k2]*SU3F[6, I3, k2]*
     SU3F[I1, I2, k1] + 15*CouplingConstant[ChPTW3[2], 1]*SU3D[I3, k1, k2]*
     SU3F[6, I4, k2]*SU3F[I1, I2, k1] - (15*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I4, k1]*SU3D[I3, k1, k2]*SU3F[I1, I2, k2] - 
    (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I4, k1, k2]*
     SU3F[I1, I2, k2] + 6*CouplingConstant[ChPTW3[2], 1]*SU3D[I4, k1, k2]*
     SU3F[6, I2, k2]*SU3F[I1, I3, k1] + 15*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I2, k1, k2]*SU3F[6, I4, k2]*SU3F[I1, I3, k1] - 
    (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I2, k1, k2]*
     SU3F[I1, I3, k2] - (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I4, k1, k2]*SU3F[I1, I3, k2] - 3*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I3, k1, k2]*SU3F[6, I2, k2]*SU3F[I1, I4, k1] - 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, k1, k2]*SU3F[6, I3, k2]*
     SU3F[I1, I4, k1] + (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*
     SU3D[I2, k1, k2]*SU3F[I1, I4, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I2, k1]*SU3D[I3, k1, k2]*SU3F[I1, I4, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I2, I3, k2]*
     SU3F[I1, k1, k2] + (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*
     SU3D[I2, I4, k2]*SU3F[I1, k1, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*SU3D[I3, I4, k2]*
     SU3F[I1, k1, k2] + 18*CouplingConstant[ChPTW3[2], 1]*SU3D[I3, I4, k1]*
     SU3F[6, I2, k2]*SU3F[I1, k1, k2] + 18*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I2, I4, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] - 
    18*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I3, k1]*SU3F[6, I4, k2]*
     SU3F[I1, k1, k2] - 9*CouplingConstant[ChPTW3[2], 1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2]*SU3F[I2, I4, k1] + (9*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I3, k1, k2]*SU3F[I2, I4, k2] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3D[I1, I3, k2]*
     SU3F[I2, k1, k2] - (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*
     SU3D[I1, I4, k2]*SU3F[I2, k1, k2] - (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I3, I4, k2]*SU3F[I2, k1, k2] - 
    3*CouplingConstant[ChPTW3[2], 1]*SU3D[I3, I4, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] - 15*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I4, k1]*
     SU3F[6, I3, k2]*SU3F[I2, k1, k2] + 3*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I3, k1]*SU3F[6, I4, k2]*SU3F[I2, k1, k2] - 
    15*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I4, k1]*SU3F[I1, I3, k2]*
     SU3F[I2, k1, k2] - (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I4, k1]*
     SU3F[I1, I3, k2]*SU3F[I2, k1, k2] + 3*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I3, k1]*SU3F[I1, I4, k2]*SU3F[I2, k1, k2] + 
    (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I3, k1]*SU3F[I1, I4, k2]*
     SU3F[I2, k1, k2] - 9*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2]*SU3F[I3, I4, k1] + (9*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3F[I3, I4, k2] + 
    9*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*SU3F[I2, k1, k2]*
     SU3F[I3, I4, k2] + (9*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I1, k1]*
     SU3F[I2, k1, k2]*SU3F[I3, I4, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I4, k1]*SU3D[I1, I2, k2]*SU3F[I3, k1, k2] - 
    (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*SU3D[I1, I4, k2]*
     SU3F[I3, k1, k2] - (3*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*
     SU3D[I2, I4, k2]*SU3F[I3, k1, k2] - 3*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I2, I4, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 
    15*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I4, k1]*SU3F[6, I2, k2]*
     SU3F[I3, k1, k2] + 3*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I2, k1]*
     SU3F[6, I4, k2]*SU3F[I3, k1, k2] - 15*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I4, k1]*SU3F[I1, I2, k2]*SU3F[I3, k1, k2] - 
    (15*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I4, k1]*SU3F[I1, I2, k2]*
     SU3F[I3, k1, k2] + 3*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3F[I1, I4, k2]*SU3F[I3, k1, k2] + (3*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I2, k1]*SU3F[I1, I4, k2]*SU3F[I3, k1, k2] + 
    9*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*SU3F[I2, I4, k2]*
     SU3F[I3, k1, k2] + (9*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I1, k1]*
     SU3F[I2, I4, k2]*SU3F[I3, k1, k2] + 
    (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*
     SU3F[I4, k1, k2] + (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*
     SU3D[I1, I3, k2]*SU3F[I4, k1, k2] - 
    (12*I)*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I1, k1]*SU3D[I2, I3, k2]*
     SU3F[I4, k1, k2] - 12*CouplingConstant[ChPTW3[2], 1]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k2]*SU3F[I4, k1, k2] + 12*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I3, k1]*SU3F[6, I2, k2]*SU3F[I4, k1, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*SU3D[I1, I2, k1]*SU3F[6, I3, k2]*
     SU3F[I4, k1, k2] - 6*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I3, k1]*
     SU3F[I1, I2, k2]*SU3F[I4, k1, k2] - (6*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I3, k1]*SU3F[I1, I2, k2]*SU3F[I4, k1, k2] - 
    6*CouplingConstant[ChPTW3[2], 1]*SU3D[6, I2, k1]*SU3F[I1, I3, k2]*
     SU3F[I4, k1, k2] - (6*I)*CouplingConstant[ChPTW3[2], 1]*SU3F[6, I2, k1]*
     SU3F[I1, I3, k2]*SU3F[I4, k1, k2] + 12*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I2, I3, I4]*SUNDelta[6, I1] - 10*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I3, I4]*SUNDelta[6, I2] - (6*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[I1, I3, I4]*SUNDelta[6, I2] - 10*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I2, I4]*SUNDelta[6, I3] - (6*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[I1, I2, I4]*SUNDelta[6, I3] + 8*CouplingConstant[ChPTW3[2], 1]*
     SU3D[I1, I2, I3]*SUNDelta[6, I4] - 10*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I3, I4]*SUNDelta[I1, I2] - (6*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I3, I4]*SUNDelta[I1, I2] - 10*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I2, I4]*SUNDelta[I1, I3] - (6*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I2, I4]*SUNDelta[I1, I3] + 20*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, I4]*SUNDelta[I2, I3] - (4*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I1, I4]*SUNDelta[I2, I3] - 10*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, I3]*SUNDelta[I2, I4] + (14*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I1, I3]*SUNDelta[I2, I4] - 10*CouplingConstant[ChPTW3[2], 1]*
     SU3D[6, I1, I2]*SUNDelta[I3, I4] + (14*I)*CouplingConstant[ChPTW3[2], 1]*
     SU3F[6, I1, I2]*SUNDelta[I3, I4])/
   (18*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}}
