{{((16*I)*(2*CouplingConstant[ChPT2[4], 1, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	CouplingConstant[ChPT2[4], 3, RenormalizationState[0]]*SUNDelta[I1, I4]*
	SUNDelta[I2, I3] + CouplingConstant[ChPT2[4], 2,
	RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	CouplingConstant[ChPT2[4], 2, RenormalizationState[0]]*SUNDelta[I1, I2]*
	SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2],
	RenormalizationState[0]]^4},
{((16*I)*(CouplingConstant[ChPT2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	2*CouplingConstant[ChPT2[4], 1, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	CouplingConstant[ChPT2[4], 3, RenormalizationState[0]]*SUNDelta[I1, I3]*
	SUNDelta[I2, I4] + CouplingConstant[ChPT2[4], 2,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4},
{((16*I)*(CouplingConstant[ChPT2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	CouplingConstant[ChPT2[4], 2, RenormalizationState[0]]*SUNDelta[I1, I3]*
	SUNDelta[I2, I4] + 2*CouplingConstant[ChPT2[4], 1,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	CouplingConstant[ChPT2[4], 3, RenormalizationState[0]]*SUNDelta[I1, I2]*
	SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2],
	RenormalizationState[0]]^4},
{(((8*I)/3)*(10*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	5*CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I3]*
	SUNDelta[I2, I4] - 2*CouplingConstant[ChPT2[4], 4,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] -
	CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I2]*
	SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2],
	RenormalizationState[0]]^4},
{(((8*I)/3)*(10*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	5*CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I3]*
	SUNDelta[I2, I4] - 2*CouplingConstant[ChPT2[4], 4,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] -
	CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I2]*
	SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2],
	RenormalizationState[0]]^4},
{(((-8*I)/3)*(2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I4]*
	SUNDelta[I2, I3] - 10*CouplingConstant[ChPT2[4], 4,
	RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	5*CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I2]*
	SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2],
	RenormalizationState[0]]^4},
{(((-8*I)/3)*(2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I4]*
	SUNDelta[I2, I3] - 10*CouplingConstant[ChPT2[4], 4,
	RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	5*CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I2]*
	SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2],
	RenormalizationState[0]]^4},
{(((-8*I)/3)*(2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I4]*
	SUNDelta[I2, I3] + 2*CouplingConstant[ChPT2[4], 4,
	RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I3]*
	SUNDelta[I2, I4] - 10*CouplingConstant[ChPT2[4], 4,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] -
	5*CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4},
{(((-8*I)/3)*(2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I4]*
	SUNDelta[I2, I3] + 2*CouplingConstant[ChPT2[4], 4,
	RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I3]*
	SUNDelta[I2, I4] - 10*CouplingConstant[ChPT2[4], 4,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] -
	5*CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4},
{(((64*I)/3)*(2*CouplingConstant[ChPT2[4], 6, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	CouplingConstant[ChPT2[4], 8, RenormalizationState[0]]*SUNDelta[I1, I4]*
	SUNDelta[I2, I3] + 2*CouplingConstant[ChPT2[4], 6,
	RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	CouplingConstant[ChPT2[4], 8, RenormalizationState[0]]*SUNDelta[I1, I3]*
	SUNDelta[I2, I4] + 2*CouplingConstant[ChPT2[4], 6,
	RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	CouplingConstant[ChPT2[4], 8, RenormalizationState[0]]*SUNDelta[I1, I2]*
	SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2],
	RenormalizationState[0]]^4},
{(((-2*I)/27)*(54*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SU2F[3, I1, I3]*SU2F[3, I2, I4] - 27*CouplingConstant[ChPTEM2[4], 4,
	RenormalizationState[0]]*SU2F[3, I1, I3]*SU2F[3, I2, I4] +
	54*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SU2F[3, I1, I2]*SU2F[3, I3, I4] - 27*CouplingConstant[ChPTEM2[4], 4,
	RenormalizationState[0]]*SU2F[3, I1, I2]*SU2F[3, I3, I4] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] +
	144*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] +
	72*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] +
	108*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] -
	128*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	20*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] +
	10*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	10*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{(((-2*I)/27)*(54*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SU2F[3, I1, I3]*SU2F[3, I2, I4] - 27*CouplingConstant[ChPTEM2[4], 4,
	RenormalizationState[0]]*SU2F[3, I1, I3]*SU2F[3, I2, I4] +
	54*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SU2F[3, I1, I2]*SU2F[3, I3, I4] - 27*CouplingConstant[ChPTEM2[4], 4,
	RenormalizationState[0]]*SU2F[3, I1, I2]*SU2F[3, I3, I4] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] +
	108*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] +
	144*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] +
	72*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] -
	128*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	20*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] +
	10*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	10*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{(((-2*I)/27)*(54*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SU2F[3, I1, I4]*SU2F[3, I2, I3] - 27*CouplingConstant[ChPTEM2[4], 4,
	RenormalizationState[0]]*SU2F[3, I1, I4]*SU2F[3, I2, I3] -
	54*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SU2F[3, I1, I2]*SU2F[3, I3, I4] + 27*CouplingConstant[ChPTEM2[4], 4,
	RenormalizationState[0]]*SU2F[3, I1, I2]*SU2F[3, I3, I4] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] +
	144*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] +
	72*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] +
	10*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	10*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	108*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] -
	128*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	20*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{(((-2*I)/27)*(54*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SU2F[3, I1, I4]*SU2F[3, I2, I3] - 27*CouplingConstant[ChPTEM2[4], 4,
	RenormalizationState[0]]*SU2F[3, I1, I4]*SU2F[3, I2, I3] -
	54*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SU2F[3, I1, I2]*SU2F[3, I3, I4] + 27*CouplingConstant[ChPTEM2[4], 4,
	RenormalizationState[0]]*SU2F[3, I1, I2]*SU2F[3, I3, I4] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] +
	108*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] +
	10*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	10*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	144*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] +
	72*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] -
	128*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	20*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] -
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	10*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{(((2*I)/27)*(54*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SU2F[3, I1, I4]*SU2F[3, I2, I3] - 27*CouplingConstant[ChPTEM2[4], 4,
	RenormalizationState[0]]*SU2F[3, I1, I4]*SU2F[3, I2, I3] +
	54*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SU2F[3, I1, I3]*SU2F[3, I2, I4] - 27*CouplingConstant[ChPTEM2[4], 4,
	RenormalizationState[0]]*SU2F[3, I1, I3]*SU2F[3, I2, I4] -
	144*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] -
	72*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] +
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] +
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] +
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] +
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] +
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] +
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] -
	10*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	10*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] +
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] -
	10*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	10*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	108*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	128*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	20*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{(((2*I)/27)*(54*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SU2F[3, I1, I4]*SU2F[3, I2, I3] - 27*CouplingConstant[ChPTEM2[4], 4,
	RenormalizationState[0]]*SU2F[3, I1, I4]*SU2F[3, I2, I3] +
	54*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SU2F[3, I1, I3]*SU2F[3, I2, I4] - 27*CouplingConstant[ChPTEM2[4], 4,
	RenormalizationState[0]]*SU2F[3, I1, I3]*SU2F[3, I2, I4] -
	108*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] +
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] +
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] +
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] +
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] +
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] +
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] -
	10*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	10*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	36*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] +
	18*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] -
	10*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	10*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	144*CouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] -
	72*CouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] +
	128*CouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] +
	20*CouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2},
{(((-20*I)/27)*(18*CouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]]*
	SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2] +
	18*CouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3] +
	18*CouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]]*
	SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4] +
	18*CouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3] -
	37*CouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] -
	CouplingConstant[ChPTEM2[4], 11, RenormalizationState[0]]*
	SUNDelta[I1, I4]*SUNDelta[I2, I3] +
	18*CouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4] -
	37*CouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] -
	CouplingConstant[ChPTEM2[4], 11, RenormalizationState[0]]*
	SUNDelta[I1, I3]*SUNDelta[I2, I4] +
	18*CouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]]*
	SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4] -
	37*CouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4] -
	CouplingConstant[ChPTEM2[4], 11, RenormalizationState[0]]*
	SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}}
