{{((-32*I)*CouplingConstant[ChPTW3[2], 1]*
    (2*CouplingConstant[ChPTW3[4], 12]*SU3D[6, I1, I2] - 
     2*CouplingConstant[ChPTW3[4], 36]*SU3D[6, I1, I2] + 
     2*CouplingConstant[ChPTW3[4], 12]*SUNDelta[0, I2]*SUNDelta[6, I1] + 
     3*CouplingConstant[ChPTW3[4], 13]*SUNDelta[0, I2]*SUNDelta[6, I1] - 
     2*CouplingConstant[ChPTW3[4], 36]*SUNDelta[0, I2]*SUNDelta[6, I1] + 
     2*CouplingConstant[ChPTW3[4], 12]*SUNDelta[0, I1]*SUNDelta[6, I2] + 
     3*CouplingConstant[ChPTW3[4], 13]*SUNDelta[0, I1]*SUNDelta[6, I2] - 
     2*CouplingConstant[ChPTW3[4], 36]*SUNDelta[0, I1]*SUNDelta[6, I2]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}}
