{{(-4*CouplingConstant[ChPTPhotonsLeptons3[4], 9, RenormalizationState[0]]*
	(3*SU3F[3, I1, I2] + Sqrt[3]*SU3F[8, I1, I2]))/
(3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)},
{(4*CouplingConstant[ChPTPhotonsLeptons3[4], 9, RenormalizationState[0]]*
	(3*SU3F[3, I1, I2] + Sqrt[3]*SU3F[8, I1, I2]))/
(3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)},
{(4*((-3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, I2] +
	I*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, I2] -
	(3*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, I1, k3] +
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, I2, k3] +
	(3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, I2, k3] +
	18*CouplingConstant[ChPTPhotonsLeptons3[4], 4, RenormalizationState[0]]*
	SU3F[3, I1, I2] + 9*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, I2] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3F[3, I1, k3] -
	3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[3, I2, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 4,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[8, I1, I2] -
	3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3F[8, I1, k3] +
	3*CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3D[8, I2, k3]*SU3F[8, I1, k3] + (3*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3F[3, I2, k3]*SU3F[8, I1, k3] -
	3*CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3D[8, I1, k3]*SU3F[8, I2, k3] +
	(3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[8, I1, k3]*SU3F[8, I2, k3] -
	(2*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[8, I1] +
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[8, I2] +
	(2*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[8, I1]*SUNDelta[8, I2] -
	(2*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[I1, I2]))/
(9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)},
{(-4*((3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, I2] -
	I*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, I2] -
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, I1, k3] +
	(3*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, I2, k3] -
	(3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, I2, k3] +
	18*CouplingConstant[ChPTPhotonsLeptons3[4], 4, RenormalizationState[0]]*
	SU3F[3, I1, I2] + 9*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, I2] +
	3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3F[3, I1, k3] -
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[3, I2, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 4,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	3*CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3D[8, I2, k3]*SU3F[8, I1, k3] + 3*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*SU3D[3, I1, k3]*
	SU3F[8, I2, k3] - 3*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[8, I2, k3] -
	(3*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[8, I2, k3] -
	(3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[8, I1, k3]*SU3F[8, I2, k3] -
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[8, I1] +
	(2*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[8, I2] -
	(2*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[8, I1]*SUNDelta[8, I2] +
	(2*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[I1, I2]))/
(9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)},
{(2*((9*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, I2, k3] -
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, I2] +
	(9*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, I1, k3] -
	(9*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, I2, k3] -
	(3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, I2, k3] +
	36*CouplingConstant[ChPTPhotonsLeptons3[4], 4, RenormalizationState[0]]*
	SU3F[3, I1, I2] + 12*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, I2] +
	9*CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3D[3, I2, k3]*SU3F[3, I1, k3] - 9*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*SU3D[8, I2, k3]*
	SU3F[3, I1, k3] - 9*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3F[3, I2, k3] +
	3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[3, I2, k3] +
	(9*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[3, I2, k3] +
	12*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 4,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	8*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	9*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3F[8, I1, k3] -
	3*CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3D[8, I2, k3]*SU3F[8, I1, k3] - (3*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3F[3, I2, k3]*SU3F[8, I1, k3] - 3*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*SU3D[3, I1, k3]*
	SU3F[8, I2, k3] + 3*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[8, I2, k3] +
	(3*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[8, I2, k3] -
	(3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[8, I1, k3]*SU3F[8, I2, k3] +
	(6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I2] +
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[8, I1] -
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[8, I2] -
	(2*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[8, I1]*SUNDelta[8, I2] -
	(4*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[I1, I2]))/
(9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)},
{(-2*((-9*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, I2, k3] +
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, I2] +
	(9*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, I1, k3] -
	(9*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, I2, k3] +
	(3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, I2, k3] +
	36*CouplingConstant[ChPTPhotonsLeptons3[4], 4, RenormalizationState[0]]*
	SU3F[3, I1, I2] + 12*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, I2] +
	9*CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3D[3, I2, k3]*SU3F[3, I1, k3] - 3*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*SU3D[8, I2, k3]*
	SU3F[3, I1, k3] - 9*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3F[3, I2, k3] +
	9*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[3, I2, k3] -
	(9*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[3, I2, k3] +
	12*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 4,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	8*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3F[8, I1, k3] -
	3*CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3D[8, I2, k3]*SU3F[8, I1, k3] - (3*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3F[3, I2, k3]*SU3F[8, I1, k3] - 9*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*SU3D[3, I1, k3]*
	SU3F[8, I2, k3] + 3*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[8, I2, k3] +
	(3*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[8, I2, k3] +
	(3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[8, I1, k3]*SU3F[8, I2, k3] -
	(6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I2] +
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[8, I1] -
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[8, I2] +
	(2*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[8, I1]*SUNDelta[8, I2] +
	(4*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[I1, I2]))/
(9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)},
{(-2*((-6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, I2] +
	(9*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, I2, k3] -
	(2*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, I2] +
	(3*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, I1, k3] +
	(3*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, I2, k3] +
	(3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, I2, k3] +
	36*CouplingConstant[ChPTPhotonsLeptons3[4], 4, RenormalizationState[0]]*
	SU3F[3, I1, I2] + 6*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, I2] -
	9*CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3D[3, I2, k3]*SU3F[3, I1, k3] - 3*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*SU3D[8, I2, k3]*
	SU3F[3, I1, k3] + 9*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3F[3, I2, k3] +
	3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[3, I2, k3] +
	(9*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[3, I2, k3] +
	12*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 4,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	2*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[8, I1, I2] -
	3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3F[8, I1, k3] -
	3*CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3D[8, I2, k3]*SU3F[8, I1, k3] + (3*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3F[3, I2, k3]*SU3F[8, I1, k3] + 3*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*SU3D[3, I1, k3]*
	SU3F[8, I2, k3] + 3*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[8, I2, k3] +
	(3*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[8, I2, k3] +
	(3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[8, I1, k3]*SU3F[8, I2, k3] +
	(6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I2] +
	(2*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[8, I1] +
	(2*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[8, I2] +
	(2*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[8, I1]*SUNDelta[8, I2] -
	(8*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[I1, I2]))/
(9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)},
{(2*((6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, I2] -
	(9*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, I2, k3] +
	(2*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, I2] -
	(3*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, I1, k3] -
	(3*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, I2, k3] -
	(3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, I2, k3] +
	36*CouplingConstant[ChPTPhotonsLeptons3[4], 4, RenormalizationState[0]]*
	SU3F[3, I1, I2] + 6*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, I2] -
	9*CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3D[3, I2, k3]*SU3F[3, I1, k3] - 3*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*SU3D[8, I2, k3]*
	SU3F[3, I1, k3] + 9*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3F[3, I2, k3] +
	3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[3, I2, k3] -
	(9*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[3, I2, k3] +
	12*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 4,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	2*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[8, I1, I2] -
	3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3F[8, I1, k3] -
	3*CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3D[8, I2, k3]*SU3F[8, I1, k3] - (3*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*
	SU3F[3, I2, k3]*SU3F[8, I1, k3] + 3*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 5, RenormalizationState[0]]*SU3D[3, I1, k3]*
	SU3F[8, I2, k3] + 3*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[8, I2, k3] -
	(3*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[8, I2, k3] -
	(3*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SU3F[8, I1, k3]*SU3F[8, I2, k3] -
	(6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I2] -
	(2*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[8, I1] -
	(2*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[8, I2] -
	(2*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[8, I1]*SUNDelta[8, I2] +
	(8*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 5,
	RenormalizationState[0]]*SUNDelta[I1, I2]))/
(9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)},
{((-12*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, I2] -
	(12*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I1, I2] +
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, I2, k3] +
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, I2, k3] -
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I1, I2] -
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I1, I2] +
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, I1, k3] +
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, I1, k3] -
	(9*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I2, k4]*SU3D[3, k3, k4]*
	SU3D[8, I1, k3] - (9*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[3, I2, k4]*SU3D[3, k3, k4]*
	SU3D[8, I1, k3] + (9*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[3, k3, k4]*
	SU3D[8, I1, k4] + (9*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[3, k3, k4]*
	SU3D[8, I1, k4] + (6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, I2, k3] +
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, I2, k3] +
	(6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, I2, k3] +
	(6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, I2, k3] +
	144*CouplingConstant[ChPTPhotonsLeptons3[4], 13, RenormalizationState[0]]*
	SU3F[3, I1, I2] + 144*CouplingConstant[ChPTPhotonsLeptons3[4], 14,
	RenormalizationState[0]]*SU3F[3, I1, I2] +
	60*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3F[3, I1, I2] + 60*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[3, I1, I2] +
	18*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[3, I2, k3]*SU3F[3, I1, k3] +
	18*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I2, k3]*SU3F[3, I1, k3] -
	27*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[3, I2, k4]*SU3D[3, k3, k4]*SU3F[3, I1, k3] -
	27*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I2, k4]*SU3D[3, k3, k4]*SU3F[3, I1, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3F[3, I1, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3F[3, I1, k3] -
	9*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[8, I2, k4]*SU3D[8, k3, k4]*SU3F[3, I1, k3] -
	9*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[8, I2, k4]*SU3D[8, k3, k4]*SU3F[3, I1, k3] +
	27*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[3, I2, k3]*SU3D[3, k3, k4]*SU3F[3, I1, k4] +
	27*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I2, k3]*SU3D[3, k3, k4]*SU3F[3, I1, k4] +
	9*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[8, I2, k3]*SU3D[8, k3, k4]*SU3F[3, I1, k4] +
	9*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[8, I2, k3]*SU3D[8, k3, k4]*SU3F[3, I1, k4] +
	18*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[3, I1, k3]*SU3F[3, I2, k3] +
	18*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I1, k3]*SU3F[3, I2, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[3, I2, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[3, I2, k3] -
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[3, I2, k3] -
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[3, I2, k3] +
	(54*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3F[3, I1, k4]*
	SU3F[3, I2, k3] + (54*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3F[3, I1, k4]*
	SU3F[3, I2, k3] + (18*I)*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*SU3D[8, k3, k4]*
	SU3F[3, I1, k4]*SU3F[3, I2, k3] + (18*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[8, k3, k4]*SU3F[3, I1, k4]*SU3F[3, I2, k3] -
	54*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[3, I1, k3]*SU3D[3, k3, k4]*SU3F[3, I2, k4] -
	54*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I1, k3]*SU3D[3, k3, k4]*SU3F[3, I2, k4] -
	18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3D[8, I1, k3]*
	SU3F[3, I2, k4] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[3, k3, k4]*SU3D[8, I1, k3]*
	SU3F[3, I2, k4] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, k3, k4]*
	SU3F[3, I2, k4] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, k3, k4]*
	SU3F[3, I2, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, k3, k4]*
	SU3F[3, I2, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, k3, k4]*
	SU3F[3, I2, k4] - 54*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[3, I1, k4]*SU3F[3, I2, k2]*
	SU3F[3, k2, k4] - 54*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[3, I1, k4]*SU3F[3, I2, k2]*
	SU3F[3, k2, k4] + (54*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, k2]*SU3F[3, I2, k4]*
	SU3F[3, k2, k4] + (54*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I1, k2]*SU3F[3, I2, k4]*
	SU3F[3, k2, k4] + (18*I)*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*SU3D[8, I1, k2]*
	SU3F[3, I2, k4]*SU3F[3, k2, k4] + (18*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[8, I1, k2]*SU3F[3, I2, k4]*SU3F[3, k2, k4] +
	48*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 13,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	48*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 14,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	20*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	20*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3F[8, I1, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3F[8, I1, k3] -
	9*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I2, k4]*SU3D[3, k3, k4]*
	SU3F[8, I1, k3] - 9*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I2, k4]*SU3D[3, k3, k4]*
	SU3F[8, I1, k3] + 6*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3F[8, I1, k3] +
	6*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[8, I2, k3]*SU3F[8, I1, k3] -
	3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I2, k4]*SU3D[8, k3, k4]*
	SU3F[8, I1, k3] - 3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I2, k4]*SU3D[8, k3, k4]*
	SU3F[8, I1, k3] - (6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3F[3, I2, k3]*SU3F[8, I1, k3] -
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[3, I2, k3]*SU3F[8, I1, k3] +
	9*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[3, k3, k4]*
	SU3F[8, I1, k4] + 9*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[3, k3, k4]*
	SU3F[8, I1, k4] + 3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3D[8, k3, k4]*
	SU3F[8, I1, k4] + 3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3D[8, k3, k4]*
	SU3F[8, I1, k4] + (18*I)*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*SU3D[3, k3, k4]*
	SU3F[3, I2, k3]*SU3F[8, I1, k4] + (18*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, k3, k4]*SU3F[3, I2, k3]*SU3F[8, I1, k4] +
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, k3, k4]*SU3F[3, I2, k3]*
	SU3F[8, I1, k4] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, k3, k4]*SU3F[3, I2, k3]*
	SU3F[8, I1, k4] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3F[3, I2, k3]*SU3F[3, k3, k4]*
	SU3F[8, I1, k4] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3F[3, I2, k3]*SU3F[3, k3, k4]*
	SU3F[8, I1, k4] + 6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3F[8, I2, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3F[8, I2, k3] +
	6*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[8, I1, k3]*SU3F[8, I2, k3] +
	6*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[8, I1, k3]*SU3F[8, I2, k3] - (6*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3F[3, I1, k3]*SU3F[8, I2, k3] - (6*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3F[3, I1, k3]*SU3F[8, I2, k3] + (18*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[3, k3, k4]*SU3F[3, I1, k4]*SU3F[8, I2, k3] +
	(18*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3F[3, I1, k4]*
	SU3F[8, I2, k3] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, k3, k4]*SU3F[3, I1, k4]*
	SU3F[8, I2, k3] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, k3, k4]*SU3F[3, I1, k4]*
	SU3F[8, I2, k3] - (6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[8, I1, k3]*SU3F[8, I2, k3] -
	(6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[8, I1, k3]*SU3F[8, I2, k3] +
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3F[8, I1, k4]*
	SU3F[8, I2, k3] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3F[8, I1, k4]*
	SU3F[8, I2, k3] + (6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3D[8, k3, k4]*SU3F[8, I1, k4]*
	SU3F[8, I2, k3] + (6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[8, k3, k4]*SU3F[8, I1, k4]*
	SU3F[8, I2, k3] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[3, k3, k4]*SU3F[8, I1, k4]*
	SU3F[8, I2, k3] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[3, k3, k4]*SU3F[8, I1, k4]*
	SU3F[8, I2, k3] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, k3, k4]*
	SU3F[8, I2, k4] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, k3, k4]*
	SU3F[8, I2, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3D[8, I1, k3]*
	SU3F[8, I2, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3D[8, I1, k3]*
	SU3F[8, I2, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, k3, k4]*
	SU3F[8, I2, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, k3, k4]*
	SU3F[8, I2, k4] - 6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, k3, k4]*
	SU3F[8, I2, k4] - 6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, k3, k4]*
	SU3F[8, I2, k4] + (18*I)*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*SU3D[3, I1, k3]*
	SU3F[3, k3, k4]*SU3F[8, I2, k4] + (18*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I1, k3]*SU3F[3, k3, k4]*SU3F[8, I2, k4] +
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[3, k3, k4]*
	SU3F[8, I2, k4] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[3, k3, k4]*
	SU3F[8, I2, k4] + 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[3, k3, k4]*
	SU3F[8, I2, k4] + 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[3, k3, k4]*
	SU3F[8, I2, k4] + (18*I)*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*SU3D[3, I1, k2]*
	SU3F[3, I2, k4]*SU3F[8, k2, k4] + (18*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I1, k2]*SU3F[3, I2, k4]*SU3F[8, k2, k4] +
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I1, k2]*SU3F[3, I2, k4]*
	SU3F[8, k2, k4] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I1, k2]*SU3F[3, I2, k4]*
	SU3F[8, k2, k4] + 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3F[3, I1, k2]*SU3F[3, I2, k4]*
	SU3F[8, k2, k4] + 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3F[3, I1, k2]*SU3F[3, I2, k4]*
	SU3F[8, k2, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[3, I2, k2]*SU3F[8, I1, k4]*
	SU3F[8, k2, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[3, I2, k2]*SU3F[8, I1, k4]*
	SU3F[8, k2, k4] - 6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[8, I1, k4]*SU3F[8, I2, k2]*
	SU3F[8, k2, k4] - 6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[8, I1, k4]*SU3F[8, I2, k2]*
	SU3F[8, k2, k4] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, k2]*SU3F[8, I2, k4]*
	SU3F[8, k2, k4] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I1, k2]*SU3F[8, I2, k4]*
	SU3F[8, k2, k4] + (6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3D[8, I1, k2]*SU3F[8, I2, k4]*
	SU3F[8, k2, k4] + (6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[8, I1, k2]*SU3F[8, I2, k4]*
	SU3F[8, k2, k4] + 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[3, I1, k2]*SU3F[8, I2, k4]*
	SU3F[8, k2, k4] + 18*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[3, I1, k2]*SU3F[8, I2, k4]*
	SU3F[8, k2, k4] + (12*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I2] +
	(12*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I2] +
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[8, I1] +
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[8, I1] +
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[8, I2] +
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[8, I2] +
	(4*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SUNDelta[8, I1]*SUNDelta[8, I2] +
	(4*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SUNDelta[8, I1]*SUNDelta[8, I2] -
	(16*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SUNDelta[I1, I2] -
	(16*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SUNDelta[I1, I2])/54},
{((-12*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, I2] -
	(12*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I1, I2] +
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, I2, k3] +
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, I2, k3] -
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I1, I2] -
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I1, I2] +
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, I1, k3] +
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, I1, k3] +
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, I2, k3] +
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[8, I2, k3] -
	(9*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, k4]*SU3D[3, k3, k4]*
	SU3D[8, I2, k3] - (9*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[3, I1, k4]*SU3D[3, k3, k4]*
	SU3D[8, I2, k3] + (6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, I2, k3] +
	(6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, I2, k3] +
	(9*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, k3, k4]*
	SU3D[8, I2, k4] + (9*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, k3, k4]*
	SU3D[8, I2, k4] - 144*CouplingConstant[ChPTPhotonsLeptons3[4], 13,
	RenormalizationState[0]]*SU3F[3, I1, I2] -
	144*CouplingConstant[ChPTPhotonsLeptons3[4], 14, RenormalizationState[0]]*
	SU3F[3, I1, I2] - 60*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[3, I1, I2] -
	60*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3F[3, I1, I2] + 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3F[3, I1, k3] +
	18*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I2, k3]*SU3F[3, I1, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3F[3, I1, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3F[3, I1, k3] -
	54*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[3, I2, k3]*SU3D[3, k3, k4]*SU3F[3, I1, k4] -
	54*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I2, k3]*SU3D[3, k3, k4]*SU3F[3, I1, k4] -
	18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3D[8, I2, k3]*
	SU3F[3, I1, k4] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[3, k3, k4]*SU3D[8, I2, k3]*
	SU3F[3, I1, k4] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, k3, k4]*
	SU3F[3, I1, k4] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, k3, k4]*
	SU3F[3, I1, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3D[8, k3, k4]*
	SU3F[3, I1, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3D[8, k3, k4]*
	SU3F[3, I1, k4] + 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3F[3, I2, k3] +
	18*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I1, k3]*SU3F[3, I2, k3] -
	27*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[3, I1, k4]*SU3D[3, k3, k4]*SU3F[3, I2, k3] -
	27*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I1, k4]*SU3D[3, k3, k4]*SU3F[3, I2, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[3, I2, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[3, I2, k3] -
	9*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[8, I1, k4]*SU3D[8, k3, k4]*SU3F[3, I2, k3] -
	9*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[8, I1, k4]*SU3D[8, k3, k4]*SU3F[3, I2, k3] -
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[3, I2, k3] -
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[3, I2, k3] +
	27*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[3, I1, k3]*SU3D[3, k3, k4]*SU3F[3, I2, k4] +
	27*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I1, k3]*SU3D[3, k3, k4]*SU3F[3, I2, k4] +
	9*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[8, I1, k3]*SU3D[8, k3, k4]*SU3F[3, I2, k4] +
	9*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[8, I1, k3]*SU3D[8, k3, k4]*SU3F[3, I2, k4] +
	(54*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3F[3, I1, k3]*
	SU3F[3, I2, k4] + (54*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3F[3, I1, k3]*
	SU3F[3, I2, k4] + (18*I)*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*SU3D[8, k3, k4]*
	SU3F[3, I1, k3]*SU3F[3, I2, k4] + (18*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[8, k3, k4]*SU3F[3, I1, k3]*SU3F[3, I2, k4] +
	(54*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I2, k2]*SU3F[3, I1, k4]*
	SU3F[3, k2, k4] + (54*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I2, k2]*SU3F[3, I1, k4]*
	SU3F[3, k2, k4] + (18*I)*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*SU3D[8, I2, k2]*
	SU3F[3, I1, k4]*SU3F[3, k2, k4] + (18*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[8, I2, k2]*SU3F[3, I1, k4]*SU3F[3, k2, k4] -
	54*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3F[3, I1, k2]*SU3F[3, I2, k4]*SU3F[3, k2, k4] -
	54*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3F[3, I1, k2]*SU3F[3, I2, k4]*SU3F[3, k2, k4] -
	48*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 13,
	RenormalizationState[0]]*SU3F[8, I1, I2] -
	48*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 14,
	RenormalizationState[0]]*SU3F[8, I1, I2] -
	20*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[8, I1, I2] -
	20*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[8, I1, I2] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3F[8, I1, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3F[8, I1, k3] +
	6*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[8, I2, k3]*SU3F[8, I1, k3] +
	6*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[8, I2, k3]*SU3F[8, I1, k3] - (6*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3F[3, I2, k3]*SU3F[8, I1, k3] - (6*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3F[3, I2, k3]*SU3F[8, I1, k3] + (18*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*
	SU3D[3, k3, k4]*SU3F[3, I2, k4]*SU3F[8, I1, k3] +
	(18*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3F[3, I2, k4]*
	SU3F[8, I1, k3] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, k3, k4]*SU3F[3, I2, k4]*
	SU3F[8, I1, k3] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, k3, k4]*SU3F[3, I2, k4]*
	SU3F[8, I1, k3] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[3, k3, k4]*
	SU3F[8, I1, k4] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[3, k3, k4]*
	SU3F[8, I1, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3D[8, I2, k3]*
	SU3F[8, I1, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3D[8, I2, k3]*
	SU3F[8, I1, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, k3, k4]*
	SU3F[8, I1, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I2, k3]*SU3D[8, k3, k4]*
	SU3F[8, I1, k4] - 6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3D[8, k3, k4]*
	SU3F[8, I1, k4] - 6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3D[8, k3, k4]*
	SU3F[8, I1, k4] + (18*I)*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*SU3D[3, I2, k3]*
	SU3F[3, k3, k4]*SU3F[8, I1, k4] + (18*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I2, k3]*SU3F[3, k3, k4]*SU3F[8, I1, k4] +
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3F[3, k3, k4]*
	SU3F[8, I1, k4] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I2, k3]*SU3F[3, k3, k4]*
	SU3F[8, I1, k4] + 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3F[3, I2, k3]*SU3F[3, k3, k4]*
	SU3F[8, I1, k4] + 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3F[3, I2, k3]*SU3F[3, k3, k4]*
	SU3F[8, I1, k4] + 6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3F[8, I2, k3] +
	6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3F[8, I2, k3] -
	9*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, k4]*SU3D[3, k3, k4]*
	SU3F[8, I2, k3] - 9*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I1, k4]*SU3D[3, k3, k4]*
	SU3F[8, I2, k3] + 6*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3F[8, I2, k3] +
	6*CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[8, I1, k3]*SU3F[8, I2, k3] -
	3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I1, k4]*SU3D[8, k3, k4]*
	SU3F[8, I2, k3] - 3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I1, k4]*SU3D[8, k3, k4]*
	SU3F[8, I2, k3] - (6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[8, I2, k3] -
	(6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[8, I2, k3] -
	(6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[8, I1, k3]*SU3F[8, I2, k3] -
	(6*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[8, I1, k3]*SU3F[8, I2, k3] +
	9*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, k3, k4]*
	SU3F[8, I2, k4] + 9*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I1, k3]*SU3D[3, k3, k4]*
	SU3F[8, I2, k4] + 3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, k3, k4]*
	SU3F[8, I2, k4] + 3*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I1, k3]*SU3D[8, k3, k4]*
	SU3F[8, I2, k4] + (18*I)*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*SU3D[3, k3, k4]*
	SU3F[3, I1, k3]*SU3F[8, I2, k4] + (18*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, k3, k4]*SU3F[3, I1, k3]*SU3F[8, I2, k4] +
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, k3, k4]*SU3F[3, I1, k3]*
	SU3F[8, I2, k4] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, k3, k4]*SU3F[3, I1, k3]*
	SU3F[8, I2, k4] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[3, k3, k4]*
	SU3F[8, I2, k4] - 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3F[3, I1, k3]*SU3F[3, k3, k4]*
	SU3F[8, I2, k4] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3F[8, I1, k3]*
	SU3F[8, I2, k4] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, k3, k4]*SU3F[8, I1, k3]*
	SU3F[8, I2, k4] + (6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3D[8, k3, k4]*SU3F[8, I1, k3]*
	SU3F[8, I2, k4] + (6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[8, k3, k4]*SU3F[8, I1, k3]*
	SU3F[8, I2, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[3, k3, k4]*SU3F[8, I1, k3]*
	SU3F[8, I2, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[3, k3, k4]*SU3F[8, I1, k3]*
	SU3F[8, I2, k4] + (18*I)*Sqrt[3]*CouplingConstant[
	ChPTPhotonsLeptons3[4], 17, RenormalizationState[0]]*SU3D[3, I2, k2]*
	SU3F[3, I1, k4]*SU3F[8, k2, k4] + (18*I)*Sqrt[3]*
	CouplingConstant[ChPTPhotonsLeptons3[4], 18, RenormalizationState[0]]*
	SU3D[3, I2, k2]*SU3F[3, I1, k4]*SU3F[8, k2, k4] +
	(18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[8, I2, k2]*SU3F[3, I1, k4]*
	SU3F[8, k2, k4] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[8, I2, k2]*SU3F[3, I1, k4]*
	SU3F[8, k2, k4] + 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3F[3, I1, k4]*SU3F[3, I2, k2]*
	SU3F[8, k2, k4] + 18*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3F[3, I1, k4]*SU3F[3, I2, k2]*
	SU3F[8, k2, k4] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3D[3, I2, k2]*SU3F[8, I1, k4]*
	SU3F[8, k2, k4] + (18*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3D[3, I2, k2]*SU3F[8, I1, k4]*
	SU3F[8, k2, k4] + (6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	17, RenormalizationState[0]]*SU3D[8, I2, k2]*SU3F[8, I1, k4]*
	SU3F[8, k2, k4] + (6*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4],
	18, RenormalizationState[0]]*SU3D[8, I2, k2]*SU3F[8, I1, k4]*
	SU3F[8, k2, k4] + 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[3, I2, k2]*SU3F[8, I1, k4]*
	SU3F[8, k2, k4] + 18*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[3, I2, k2]*SU3F[8, I1, k4]*
	SU3F[8, k2, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[3, I1, k2]*SU3F[8, I2, k4]*
	SU3F[8, k2, k4] - 18*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[3, I1, k2]*SU3F[8, I2, k4]*
	SU3F[8, k2, k4] - 6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SU3F[8, I1, k2]*SU3F[8, I2, k4]*
	SU3F[8, k2, k4] - 6*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SU3F[8, I1, k2]*SU3F[8, I2, k4]*
	SU3F[8, k2, k4] + (12*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I2] +
	(12*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[3, I2] +
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[8, I1] +
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SUNDelta[3, I2]*SUNDelta[8, I1] +
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[8, I2] +
	(4*I)*Sqrt[3]*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SUNDelta[3, I1]*SUNDelta[8, I2] +
	(4*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SUNDelta[8, I1]*SUNDelta[8, I2] +
	(4*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SUNDelta[8, I1]*SUNDelta[8, I2] -
	(16*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 17,
	RenormalizationState[0]]*SUNDelta[I1, I2] -
	(16*I)*CouplingConstant[ChPTPhotonsLeptons3[4], 18,
	RenormalizationState[0]]*SUNDelta[I1, I2])/54}}
