{{(4*CouplingConstant[ChPTW3[2], 1]*(3*CouplingConstant[ChPTW3[4], 11]*
	(2*Sqrt[3]*SUNDelta[0, I2]*
		(-UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) +
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]) +
	2*CouplingConstant[ChPTW3[4], 10]*(2*Sqrt[3]*SUNDelta[0, I2]*
		(-UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] +
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) +
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[I1]]]] + Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] + Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] - Sqrt[3]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]])))/
(3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)},
{(4*CouplingConstant[ChPTW3[2], 1]*(3*CouplingConstant[ChPTW3[4], 11]*
	(SUNDelta[0, I2]*(3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] -
		3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] +
		Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) +
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]) +
	CouplingConstant[ChPTW3[4], 10]*(2*SUNDelta[0, I2]*
		(3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] -
		3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] +
		Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) +
	2*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	2*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[6]]]] + Sqrt[3]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + Sqrt[3]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]])))/
(3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)},
{(4*CouplingConstant[ChPTW3[2], 1]*(3*CouplingConstant[ChPTW3[4], 11]*
	(SUNDelta[0, I2]*(-3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
		3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] +
		Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) +
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]) +
	CouplingConstant[ChPTW3[4], 10]*
	(SUNDelta[0, I2]*(-6*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] +
		6*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] +
		2*Sqrt[3]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] -
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
			UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])) +
	2*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] -
	2*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[I2]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I2]]]] -
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]]]] +
	3*UTrace1[NonCommutative[UMatrix[UGenerator[3]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]],
		UMatrix[UGenerator[6]]]] + Sqrt[3]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] -
	Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]],
		UMatrix[UGenerator[I2]]]] - Sqrt[3]*
		UTrace1[NonCommutative[UMatrix[UGenerator[6]],
		UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]]]] + Sqrt[3]*UTrace1[NonCommutative[
		UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]],
		UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]])))/
(3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}}
