{{(-16*I*(2*SUNDelta[3, I1]*SUNDelta[3, I2]*UCouplingConstant[ChPT2Photon[4], 
       4, RenormalizationState[0]] - 2*SUNDelta[I1, I2]*
      UCouplingConstant[ChPT2Photon[4], 4, RenormalizationState[0]] + 
     SUNDelta[3, I1]*SUNDelta[3, I2]*UCouplingConstant[ChPT2Photon[4], 5, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*UCouplingConstant[
       ChPT2Photon[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(4*I*(SUNDelta[3, I1]*SUNDelta[3, I2]*UCouplingConstant[ChPT2Photon[4], 9, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*UCouplingConstant[
       ChPT2Photon[4], 9, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(4*I*(SUNDelta[3, I1]*SUNDelta[3, I2]*UCouplingConstant[ChPT2Photon[4], 9, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*UCouplingConstant[
       ChPT2Photon[4], 9, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(4*I*(SUNDelta[3, I1]*SUNDelta[3, I2]*UCouplingConstant[ChPT2Photon[4], 9, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*UCouplingConstant[
       ChPT2Photon[4], 9, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(4*I*(SUNDelta[3, I1]*SUNDelta[3, I2]*UCouplingConstant[ChPT2Photon[4], 9, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*UCouplingConstant[
       ChPT2Photon[4], 9, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(-4*I*(SUNDelta[3, I1]*SUNDelta[3, I2]*UCouplingConstant[ChPT2Photon[4], 9, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*UCouplingConstant[
       ChPT2Photon[4], 9, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(-4*I*(SUNDelta[3, I1]*SUNDelta[3, I2]*UCouplingConstant[ChPT2Photon[4], 9, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*UCouplingConstant[
       ChPT2Photon[4], 9, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(-4*I*(SUNDelta[3, I1]*SUNDelta[3, I2]*UCouplingConstant[ChPT2Photon[4], 9, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*UCouplingConstant[
       ChPT2Photon[4], 9, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(-4*I*(SUNDelta[3, I1]*SUNDelta[3, I2]*UCouplingConstant[ChPT2Photon[4], 9, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*UCouplingConstant[
       ChPT2Photon[4], 9, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(8*I*(SUNDelta[3, I1]*SUNDelta[3, I2]*UCouplingConstant[ChPT2Photon[4], 10, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*UCouplingConstant[
       ChPT2Photon[4], 10, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(-8*I*(SUNDelta[3, I1]*SUNDelta[3, I2]*UCouplingConstant[ChPT2Photon[4], 
       10, RenormalizationState[0]] - SUNDelta[I1, I2]*
      UCouplingConstant[ChPT2Photon[4], 10, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}}
