{{((-4*I)*QuarkCondensate[RenormalizationState[0]]*
    CouplingConstant[ChPTW3[2], 1]*(2*CouplingConstant[ChPTW3[4], 7]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]]]] + 
     CouplingConstant[ChPTW3[4], 6]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + CouplingConstant[ChPTW3[4], 6]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     2*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 5]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
     3*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 8]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
     2*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 5]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
     3*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 8]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
     CouplingConstant[ChPTW3[4], 5]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     CouplingConstant[ChPTW3[4], 5]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     CouplingConstant[ChPTW3[4], 5]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
     CouplingConstant[ChPTW3[4], 5]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(((-2*I)/3)*QuarkCondensate[RenormalizationState[0]]*
    CouplingConstant[ChPTW3[2], 1]*
    (12*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 13]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]]) - 
     4*Sqrt[3]*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 13]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]) + 
     12*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     4*CouplingConstant[ChPTW3[4], 11]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]]]] + 4*CouplingConstant[ChPTW3[4], 13]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]) + 
     4*SUNDelta[0, I3]*(2*CouplingConstant[ChPTW3[4], 10] + 
       3*CouplingConstant[ChPTW3[4], 11] + 2*CouplingConstant[ChPTW3[4], 
         12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]]) + 
     6*CouplingConstant[ChPTW3[4], 13]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[I2]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[3]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[I1]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[3]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[6]]]]) - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       13]*(UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[I2]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[6]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[I1]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[6]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[6]]]]) + 6*CouplingConstant[ChPTW3[4], 11]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[6]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[3]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[3]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]])) - 
     2*Sqrt[3]*CouplingConstant[ChPTW3[4], 11]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[6]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
          UMatrix[UGenerator[6]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]])) + 12*SUNDelta[0, I3]*
      CouplingConstant[ChPTW3[4], 12]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]]) - 
     4*Sqrt[3]*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 12]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]]) + 
     3*SUNDelta[0, I3]*(4*CouplingConstant[ChPTW3[4], 10] + 
       3*CouplingConstant[ChPTW3[4], 11] + 2*CouplingConstant[ChPTW3[4], 
         12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[6]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]]) - 
     Sqrt[3]*SUNDelta[0, I3]*(4*CouplingConstant[ChPTW3[4], 10] + 
       3*CouplingConstant[ChPTW3[4], 11] + 2*CouplingConstant[ChPTW3[4], 
         12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]]) - 
     Sqrt[3]*SUNDelta[0, I3]*(4*CouplingConstant[ChPTW3[4], 10] + 
       3*CouplingConstant[ChPTW3[4], 11] + 2*CouplingConstant[ChPTW3[4], 
         12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]]]]) + 
     4*CouplingConstant[ChPTW3[4], 12]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]) + 
     (4*CouplingConstant[ChPTW3[4], 10] + 3*CouplingConstant[ChPTW3[4], 
         11] + 2*CouplingConstant[ChPTW3[4], 12])*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]]) - 
     3*(CouplingConstant[ChPTW3[4], 10] - CouplingConstant[ChPTW3[4], 12])*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]]) + 
     Sqrt[3]*(CouplingConstant[ChPTW3[4], 10] - CouplingConstant[ChPTW3[4], 
        12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) + 
     3*CouplingConstant[ChPTW3[4], 12]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]]]]) + 
     3*CouplingConstant[ChPTW3[4], 10]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]]) - 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]]) - 
     Sqrt[3]*(CouplingConstant[ChPTW3[4], 10] + CouplingConstant[ChPTW3[4], 
        12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]]]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(((2*I)/3)*QuarkCondensate[RenormalizationState[0]]*
    CouplingConstant[ChPTW3[2], 1]*
    (12*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 13]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]]) + 
     4*Sqrt[3]*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 13]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]) + 
     12*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     4*CouplingConstant[ChPTW3[4], 11]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]]]] - 4*CouplingConstant[ChPTW3[4], 13]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]) - 
     4*SUNDelta[0, I3]*(2*CouplingConstant[ChPTW3[4], 10] + 
       3*CouplingConstant[ChPTW3[4], 11] + 2*CouplingConstant[ChPTW3[4], 
         12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]]) + 
     6*CouplingConstant[ChPTW3[4], 13]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[I2]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[3]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[I1]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[6]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[3]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[3]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[6]]]]) + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       13]*(UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[I2]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[6]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[I1]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[6]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[6]]]]) + 6*CouplingConstant[ChPTW3[4], 11]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[6]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
           UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[3]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[3]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]])) + 
     2*Sqrt[3]*CouplingConstant[ChPTW3[4], 11]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[6]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
          UMatrix[UGenerator[6]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]])) + 12*SUNDelta[0, I3]*
      CouplingConstant[ChPTW3[4], 12]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]]) + 
     4*Sqrt[3]*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 12]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]]) + 
     3*SUNDelta[0, I3]*(4*CouplingConstant[ChPTW3[4], 10] + 
       3*CouplingConstant[ChPTW3[4], 11] + 2*CouplingConstant[ChPTW3[4], 
         12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[6]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]]) + 
     Sqrt[3]*SUNDelta[0, I3]*(4*CouplingConstant[ChPTW3[4], 10] + 
       3*CouplingConstant[ChPTW3[4], 11] + 2*CouplingConstant[ChPTW3[4], 
         12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]]) + 
     Sqrt[3]*SUNDelta[0, I3]*(4*CouplingConstant[ChPTW3[4], 10] + 
       3*CouplingConstant[ChPTW3[4], 11] + 2*CouplingConstant[ChPTW3[4], 
         12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]]]]) - 
     4*CouplingConstant[ChPTW3[4], 12]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]) - 
     (4*CouplingConstant[ChPTW3[4], 10] + 3*CouplingConstant[ChPTW3[4], 
         11] + 2*CouplingConstant[ChPTW3[4], 12])*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]]) - 
     3*(CouplingConstant[ChPTW3[4], 10] - CouplingConstant[ChPTW3[4], 12])*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]]) - 
     Sqrt[3]*(CouplingConstant[ChPTW3[4], 10] - CouplingConstant[ChPTW3[4], 
        12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) + 
     3*CouplingConstant[ChPTW3[4], 12]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]]]]) + 
     3*CouplingConstant[ChPTW3[4], 10]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[3]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]]) + 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]]) + 
     Sqrt[3]*(CouplingConstant[ChPTW3[4], 10] + CouplingConstant[ChPTW3[4], 
        12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]]]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(((-2*I)/3)*QuarkCondensate[RenormalizationState[0]]*
    CouplingConstant[ChPTW3[2], 1]*(8*Sqrt[3]*SUNDelta[0, I3]*
      CouplingConstant[ChPTW3[4], 13]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]) + 
     8*Sqrt[3]*SUNDelta[0, I3]*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     4*CouplingConstant[ChPTW3[4], 11]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]]]] + 4*CouplingConstant[ChPTW3[4], 13]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]) + 
     4*SUNDelta[0, I3]*(2*CouplingConstant[ChPTW3[4], 10] + 
       3*CouplingConstant[ChPTW3[4], 11] + 2*CouplingConstant[ChPTW3[4], 
         12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]]) + 
     4*Sqrt[3]*CouplingConstant[ChPTW3[4], 13]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[I2]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[6]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[I1]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[8]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[6]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[8]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[6]]]]) + 4*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       11]*(UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
          UMatrix[UGenerator[6]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[8]]]]) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
          UMatrix[UGenerator[6]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
           UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]])) + 8*Sqrt[3]*SUNDelta[0, I3]*
      CouplingConstant[ChPTW3[4], 12]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]]) + 
     2*Sqrt[3]*SUNDelta[0, I3]*(4*CouplingConstant[ChPTW3[4], 10] + 
       3*CouplingConstant[ChPTW3[4], 11] + 2*CouplingConstant[ChPTW3[4], 
         12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]]) + 
     2*Sqrt[3]*SUNDelta[0, I3]*(4*CouplingConstant[ChPTW3[4], 10] + 
       3*CouplingConstant[ChPTW3[4], 11] + 2*CouplingConstant[ChPTW3[4], 
         12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]]]]) + 
     4*CouplingConstant[ChPTW3[4], 12]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]) + 
     (4*CouplingConstant[ChPTW3[4], 10] + 3*CouplingConstant[ChPTW3[4], 
         11] + 2*CouplingConstant[ChPTW3[4], 12])*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]]) - 
     2*Sqrt[3]*(CouplingConstant[ChPTW3[4], 10] - CouplingConstant[
        ChPTW3[4], 12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]) + 
     2*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]]) + 
     2*Sqrt[3]*(CouplingConstant[ChPTW3[4], 10] + CouplingConstant[
        ChPTW3[4], 12])*(UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[6]]]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}}
