{{((4*I)*(2*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 1, RenormalizationState[0]] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 2, RenormalizationState[0]] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 2, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((4*I)*(2*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 1, RenormalizationState[0]] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 2, RenormalizationState[0]] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 2, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((4*I)*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 1, RenormalizationState[0]] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 2, RenormalizationState[0]] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 2, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {(((8*I)/3)*(SUNDelta[I1, I4]*SUNDelta[I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 3, RenormalizationState[0]] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 3, RenormalizationState[0]] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 3, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {(((-2*I)/27)*(10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[
        0]] + 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 11, RenormalizationState[0]] - 
     20*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 11, RenormalizationState[0]] + 
     10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] + 
     10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] + 
     108*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[
        0]] - 128*SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[
        0]] - 54*SU2F[3, I1, I4]*SU2F[3, I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 13, RenormalizationState[0]] - 
     54*SU2F[3, I1, I3]*SU2F[3, I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 13, RenormalizationState[0]] + 
     144*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 36*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 36*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 27*SU2F[3, I1, I4]*SU2F[3, I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 14, RenormalizationState[0]] - 
     27*SU2F[3, I1, I3]*SU2F[3, I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 14, RenormalizationState[0]] - 
     72*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 18*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 18*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 18*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 18*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]]))/DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(((-2*I)/27)*(10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[
        0]] - 20*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 11, RenormalizationState[0]] + 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 11, RenormalizationState[0]] + 
     10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] + 
     108*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[
        0]] - 128*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[
        0]] + 10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] + 
     54*SU2F[3, I1, I4]*SU2F[3, I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 13, RenormalizationState[0]] - 
     54*SU2F[3, I1, I2]*SU2F[3, I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 13, RenormalizationState[0]] - 
     36*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] + 144*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 36*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] + 27*SU2F[3, I1, I4]*SU2F[3, I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 14, RenormalizationState[0]] - 
     27*SU2F[3, I1, I2]*SU2F[3, I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 14, RenormalizationState[0]] + 
     18*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] - 72*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 18*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 18*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 18*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]]))/DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(((2*I)/27)*(20*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[
        0]] - 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 11, RenormalizationState[0]] - 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 11, RenormalizationState[0]] - 
     108*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[
        0]] + 128*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[
        0]] - 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] - 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] - 
     54*SU2F[3, I1, I3]*SU2F[3, I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 13, RenormalizationState[0]] - 
     54*SU2F[3, I1, I2]*SU2F[3, I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 13, RenormalizationState[0]] + 
     36*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] + 36*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 144*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] + 36*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] + 36*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 27*SU2F[3, I1, I3]*SU2F[3, I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 14, RenormalizationState[0]] - 
     27*SU2F[3, I1, I2]*SU2F[3, I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 14, RenormalizationState[0]] - 
     18*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] - 18*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 72*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]]))/DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(((2*I)/27)*(20*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[
        0]] - 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 11, RenormalizationState[0]] - 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 11, RenormalizationState[0]] - 
     108*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[
        0]] + 128*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[
        0]] - 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] - 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] - 
     54*SU2F[3, I1, I3]*SU2F[3, I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 13, RenormalizationState[0]] - 
     54*SU2F[3, I1, I2]*SU2F[3, I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 13, RenormalizationState[0]] + 
     36*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] + 36*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 144*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] + 36*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] + 36*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 27*SU2F[3, I1, I3]*SU2F[3, I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 14, RenormalizationState[0]] - 
     27*SU2F[3, I1, I2]*SU2F[3, I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 14, RenormalizationState[0]] - 
     18*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] - 18*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 72*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]]))/DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(((-2*I)/27)*(10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[
        0]] - 20*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 11, RenormalizationState[0]] + 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 11, RenormalizationState[0]] + 
     108*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[
        0]] + 10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] - 
     128*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] + 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] + 
     54*SU2F[3, I1, I4]*SU2F[3, I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 13, RenormalizationState[0]] - 
     54*SU2F[3, I1, I2]*SU2F[3, I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 13, RenormalizationState[0]] - 
     36*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 36*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] + 144*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] + 27*SU2F[3, I1, I4]*SU2F[3, I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 14, RenormalizationState[0]] - 
     27*SU2F[3, I1, I2]*SU2F[3, I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 14, RenormalizationState[0]] + 
     18*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 18*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 18*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] - 72*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 18*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]]))/DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(((-2*I)/27)*(10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[
        0]] + 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 11, RenormalizationState[0]] - 
     20*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 11, RenormalizationState[0]] + 
     108*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTVirtualPhotons2[4], 12, RenormalizationState[
        0]] + 10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] + 
     10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] - 
     128*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 12, RenormalizationState[0]] - 
     54*SU2F[3, I1, I4]*SU2F[3, I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 13, RenormalizationState[0]] - 
     54*SU2F[3, I1, I3]*SU2F[3, I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 13, RenormalizationState[0]] - 
     36*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 36*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] + 144*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 13, RenormalizationState[
        0]] - 27*SU2F[3, I1, I4]*SU2F[3, I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 14, RenormalizationState[0]] - 
     27*SU2F[3, I1, I3]*SU2F[3, I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 14, RenormalizationState[0]] + 
     18*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 18*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 18*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] + 18*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]] - 72*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 14, RenormalizationState[
        0]]))/DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(((4*I)/27)*(5*SUNDelta[I1, I4]*SUNDelta[I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 15, RenormalizationState[0]] + 
     5*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 15, RenormalizationState[0]] + 
     5*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 15, RenormalizationState[0]] - 
     90*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTVirtualPhotons2[4], 16, RenormalizationState[
        0]] - 90*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 16, RenormalizationState[
        0]] - 90*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 16, RenormalizationState[
        0]] - 90*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 16, RenormalizationState[
        0]] + 185*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 16, RenormalizationState[
        0]] - 90*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 16, RenormalizationState[
        0]] + 185*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 16, RenormalizationState[
        0]] - 90*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 16, RenormalizationState[
        0]] + 185*SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 16, RenormalizationState[
        0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*CouplingConstant[
       ChPTVirtualPhotons2[4], 17, RenormalizationState[0]] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 17, RenormalizationState[0]] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
       ChPTVirtualPhotons2[4], 17, RenormalizationState[0]] - 
     90*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTVirtualPhotons2[4], 18, RenormalizationState[
        0]] - 90*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 18, RenormalizationState[
        0]] - 90*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 18, RenormalizationState[
        0]] - 90*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 18, RenormalizationState[
        0]] + 180*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTVirtualPhotons2[4], 18, RenormalizationState[
        0]] - 90*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 18, RenormalizationState[
        0]] + 180*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 18, RenormalizationState[
        0]] - 90*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 18, RenormalizationState[
        0]] + 180*SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      CouplingConstant[ChPTVirtualPhotons2[4], 18, RenormalizationState[
        0]]))/DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {((-4*I)/27)*(5*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]] + 
    5*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
     CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]] + 
    5*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
     CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]] + 
    5*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
     CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]] - 
    10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*CouplingConstant[
      ChPTVirtualPhotons2[4], 23, RenormalizationState[0]] + 
    5*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
     CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]] - 
    10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
      ChPTVirtualPhotons2[4], 23, RenormalizationState[0]] + 
    5*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
     CouplingConstant[ChPTVirtualPhotons2[4], 23, RenormalizationState[0]] - 
    10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
      ChPTVirtualPhotons2[4], 23, RenormalizationState[0]] - 
    162*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[3, I4]*
     CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]] + 
    64*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]] + 
    64*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
     CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]] + 
    64*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
     CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]] + 
    64*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
     CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]] - 
    74*SUNDelta[I1, I4]*SUNDelta[I2, I3]*CouplingConstant[
      ChPTVirtualPhotons2[4], 24, RenormalizationState[0]] + 
    64*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
     CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]] - 
    74*SUNDelta[I1, I3]*SUNDelta[I2, I4]*CouplingConstant[
      ChPTVirtualPhotons2[4], 24, RenormalizationState[0]] + 
    64*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
     CouplingConstant[ChPTVirtualPhotons2[4], 24, RenormalizationState[0]] - 
    74*SUNDelta[I1, I2]*SUNDelta[I3, I4]*CouplingConstant[
      ChPTVirtualPhotons2[4], 24, RenormalizationState[0]])}}
