{{(-(Sqrt[2]*FermiConstant*VUD*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[1, I3]*SUNDelta[J1, J2]) - 
    I*Sqrt[2]*FermiConstant*VUD*DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]*SUNDelta[2, I3]*SUNDelta[J1, J2] - 
    Sqrt[2]*FermiConstant*VUS*DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]*SUNDelta[4, I3]*SUNDelta[J1, J2] - 
    I*Sqrt[2]*FermiConstant*VUS*DecayConstant[PseudoScalar[1], 
      RenormalizationState[0]]*SUNDelta[5, I3]*SUNDelta[J1, J2])/2}}
