{{(-4*(Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 4, 
       RenormalizationState[0]]*SUNDelta[1, I3]*SUNDelta[J1, J2] - 
     Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*SUNDelta[1, I3]*SUNDelta[J1, J2] + 
     I*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 4, 
       RenormalizationState[0]]*SUNDelta[2, I3]*SUNDelta[J1, J2] - 
     I*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*SUNDelta[2, I3]*SUNDelta[J1, J2] + 
     Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 4, 
       RenormalizationState[0]]*SUNDelta[4, I3]*SUNDelta[J1, J2] + 
     Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*SUNDelta[4, I3]*SUNDelta[J1, J2] + 
     I*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 4, 
       RenormalizationState[0]]*SUNDelta[5, I3]*SUNDelta[J1, J2] + 
     I*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*SUNDelta[5, I3]*SUNDelta[J1, J2]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]}, 
 {(-4*(Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 4, 
       RenormalizationState[0]]*SUNDelta[1, I3]*SUNDelta[J1, J2] + 
     Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*SUNDelta[1, I3]*SUNDelta[J1, J2] + 
     I*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 4, 
       RenormalizationState[0]]*SUNDelta[2, I3]*SUNDelta[J1, J2] + 
     I*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*SUNDelta[2, I3]*SUNDelta[J1, J2] + 
     Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 4, 
       RenormalizationState[0]]*SUNDelta[4, I3]*SUNDelta[J1, J2] - 
     Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*SUNDelta[4, I3]*SUNDelta[J1, J2] + 
     I*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 4, 
       RenormalizationState[0]]*SUNDelta[5, I3]*SUNDelta[J1, J2] - 
     I*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*SUNDelta[5, I3]*SUNDelta[J1, J2]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]}, 
 {(-4*(Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 4, 
       RenormalizationState[0]]*SUNDelta[1, I3]*SUNDelta[J1, J2] + 
     Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*SUNDelta[1, I3]*SUNDelta[J1, J2] + 
     I*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 4, 
       RenormalizationState[0]]*SUNDelta[2, I3]*SUNDelta[J1, J2] + 
     I*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*SUNDelta[2, I3]*SUNDelta[J1, J2] + 
     Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 4, 
       RenormalizationState[0]]*SUNDelta[4, I3]*SUNDelta[J1, J2] + 
     Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*SUNDelta[4, I3]*SUNDelta[J1, J2] + 
     I*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 4, 
       RenormalizationState[0]]*SUNDelta[5, I3]*SUNDelta[J1, J2] + 
     I*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*SUNDelta[5, I3]*SUNDelta[J1, J2]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]}, 
 {(-2*(6*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 
       13, RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[1, I3]*SUNDelta[J1, J2] + 
     6*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 14, 
       RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[1, I3]*SUNDelta[J1, J2] + 
     5*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 17, 
       RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[1, I3]*SUNDelta[J1, J2] + 
     5*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 18, 
       RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[1, I3]*SUNDelta[J1, J2] - 
     3*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 32, 
       RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[1, I3]*SUNDelta[J1, J2] - 
     9*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 33, 
       RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[1, I3]*SUNDelta[J1, J2] + 
     (6*I)*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 
       13, RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[2, I3]*SUNDelta[J1, J2] + 
     (6*I)*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 
       14, RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[2, I3]*SUNDelta[J1, J2] + 
     (5*I)*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 
       17, RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[2, I3]*SUNDelta[J1, J2] + 
     (5*I)*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 
       18, RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[2, I3]*SUNDelta[J1, J2] - 
     (3*I)*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 
       32, RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[2, I3]*SUNDelta[J1, J2] - 
     (9*I)*Sqrt[2]*FermiConstant*VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 
       33, RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[2, I3]*SUNDelta[J1, J2] + 
     6*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 13, 
       RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[4, I3]*SUNDelta[J1, J2] + 
     6*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 14, 
       RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[4, I3]*SUNDelta[J1, J2] + 
     5*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 17, 
       RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[4, I3]*SUNDelta[J1, J2] + 
     5*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 18, 
       RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[4, I3]*SUNDelta[J1, J2] - 
     3*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 32, 
       RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[4, I3]*SUNDelta[J1, J2] - 
     9*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 33, 
       RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[4, I3]*SUNDelta[J1, J2] + 
     (6*I)*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 
       13, RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[5, I3]*SUNDelta[J1, J2] + 
     (6*I)*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 
       14, RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[5, I3]*SUNDelta[J1, J2] + 
     (5*I)*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 
       17, RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[5, I3]*SUNDelta[J1, J2] + 
     (5*I)*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 
       18, RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[5, I3]*SUNDelta[J1, J2] - 
     (3*I)*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 
       32, RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[5, I3]*SUNDelta[J1, J2] - 
     (9*I)*Sqrt[2]*FermiConstant*VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 
       33, RenormalizationState[0]]*DecayConstant[PseudoScalar[1], 
       RenormalizationState[0]]*SUNDelta[5, I3]*SUNDelta[J1, J2]))/9}}
