{{((-3*I*SU3D[6, I3, k1]*SU3D[I1, I2, k1] + 6*I*SU3D[6, I2, k1]*
      SU3D[I1, I3, k1] - 3*I*SU3D[6, I1, k1]*SU3D[I2, I3, k1] + 
     3*SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 6*SU3D[I1, I3, k1]*
      SU3F[6, I2, k1] + 3*SU3D[I1, I2, k1]*SU3F[6, I3, k1] + 
     3*SU3D[6, I3, k1]*SU3F[I1, I2, k1] + 3*I*SU3F[6, I3, k1]*
      SU3F[I1, I2, k1] - 3*SU3D[6, I1, k1]*SU3F[I2, I3, k1] - 
     3*I*SU3F[6, I1, k1]*SU3F[I2, I3, k1] - 2*I*SUNDelta[6, I3]*
      SUNDelta[I1, I2] + 4*I*SUNDelta[6, I2]*SUNDelta[I1, I3] - 
     2*I*SUNDelta[6, I1]*SUNDelta[I2, I3])*CouplingConstant[ChPTW3[2], 1])/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)}, 
 {((6*I*SU3D[6, I3, k1]*SU3D[I1, I2, k1] - 3*I*SU3D[6, I2, k1]*
      SU3D[I1, I3, k1] - 3*I*SU3D[6, I1, k1]*SU3D[I2, I3, k1] + 
     3*SU3D[I2, I3, k1]*SU3F[6, I1, k1] + 3*SU3D[I1, I3, k1]*
      SU3F[6, I2, k1] - 6*SU3D[I1, I2, k1]*SU3F[6, I3, k1] + 
     3*SU3D[6, I2, k1]*SU3F[I1, I3, k1] + 3*I*SU3F[6, I2, k1]*
      SU3F[I1, I3, k1] + 3*SU3D[6, I1, k1]*SU3F[I2, I3, k1] + 
     3*I*SU3F[6, I1, k1]*SU3F[I2, I3, k1] + 4*I*SUNDelta[6, I3]*
      SUNDelta[I1, I2] - 2*I*SUNDelta[6, I2]*SUNDelta[I1, I3] - 
     2*I*SUNDelta[6, I1]*SUNDelta[I2, I3])*CouplingConstant[ChPTW3[2], 1])/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)}}
