{{((64*I)*(2*CouplingConstant[ChPT2[4], 6, RenormalizationState[0]]*
      SUNDelta[0, I3]*SUNDelta[I1, I2] + CouplingConstant[ChPT2[4], 8, 
       RenormalizationState[0]]*SUNDelta[0, I3]*SUNDelta[I1, I2] + 
     2*CouplingConstant[ChPT2[4], 7, RenormalizationState[0]]*SUNDelta[0, I1]*
      SUNDelta[I2, I3] + CouplingConstant[ChPT2[4], 8, 
       RenormalizationState[0]]*SUNDelta[0, I1]*SUNDelta[I2, I3]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]}}
