{{(-2*CouplingConstant[ChPTVirtualPhotons2[4], 6, RenormalizationState[0]]*
    SU2F[3, I1, I2])/DecayConstant[PseudoScalar[2], RenormalizationState[0]]^
    2}, {(2*CouplingConstant[ChPTVirtualPhotons2[4], 6, 
     RenormalizationState[0]]*SU2F[3, I1, I2])/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(20*(CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[0]]*
      SU2F[3, I1, I2] + CouplingConstant[ChPTVirtualPhotons2[4], 12, 
       RenormalizationState[0]]*SU2F[3, I1, I2]))/9}, 
 {(-20*(CouplingConstant[ChPTVirtualPhotons2[4], 11, RenormalizationState[0]]*
      SU2F[3, I1, I2] + CouplingConstant[ChPTVirtualPhotons2[4], 12, 
       RenormalizationState[0]]*SU2F[3, I1, I2]))/9}}
