{{(-2*I*QuarkCondensate[RenormalizationState[0]]*UCouplingConstant[ChPTW3[2], 
     1]*UCouplingConstant[ChPTW3[4], 22]*
    (UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}, 
 {(-2*I*QuarkCondensate[RenormalizationState[0]]*UCouplingConstant[ChPTW3[2], 
     1]*(UCouplingConstant[ChPTW3[4], 22] + 
     2*UCouplingConstant[ChPTW3[4], 23])*
    (UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}}
