{{(2*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 20]*
    (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}, 
 {(CouplingConstant[ChPTW3[2], 1]*(CouplingConstant[ChPTW3[4], 20] - 
     CouplingConstant[ChPTW3[4], 26])*
    (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}, 
 {(CouplingConstant[ChPTW3[2], 1]*(CouplingConstant[ChPTW3[4], 20] + 
     CouplingConstant[ChPTW3[4], 26])*
    (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}, 
 {-(CouplingConstant[ChPTW3[2], 1]*(6*CouplingConstant[ChPTW3[4], 24]*
       UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
      2*CouplingConstant[ChPTW3[4], 24]*UTrace1[NonCommutative[
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]*
       (Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
           UMatrix[UGenerator[I2]]]] + 
        3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[3]]]] + Sqrt[3]*UTrace1[NonCommutative[
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]) - 
      2*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]]]] - 4*CouplingConstant[ChPTW3[4], 23]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
      4*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]]]] - 2*CouplingConstant[ChPTW3[4], 22]*
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
      3*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      6*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
        23]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[I1]]]] + 3*CouplingConstant[ChPTW3[4], 22]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 23]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I2]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
        23]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I2]]]] + 3*CouplingConstant[ChPTW3[4], 22]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 23]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[3]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[8]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
        23]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[8]]]] + 6*CouplingConstant[ChPTW3[4], 21]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 23]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
        21]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
        23]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 21]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[3]]]] - 3*CouplingConstant[ChPTW3[4], 22]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
        21]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]]]] - 6*CouplingConstant[ChPTW3[4], 21]*
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I1]]]] + 3*CouplingConstant[ChPTW3[4], 22]*
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
         UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
        21]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 21]*
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[3]]]] + 3*CouplingConstant[ChPTW3[4], 22]*
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
        21]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
       UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[8]]]]))/
   (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(CouplingConstant[ChPTW3[2], 1]*(6*CouplingConstant[ChPTW3[4], 24]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] - 
     2*CouplingConstant[ChPTW3[4], 24]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]*
      (Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
          UMatrix[UGenerator[I2]]]] - 
       3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[3]]]] + Sqrt[3]*UTrace1[NonCommutative[
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]) + 
     2*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 4*CouplingConstant[ChPTW3[4], 23]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     4*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 2*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
     3*CouplingConstant[ChPTW3[4], 22]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     6*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       23]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 3*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 23]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       23]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + 3*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 6*CouplingConstant[ChPTW3[4], 23]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 6*CouplingConstant[ChPTW3[4], 21]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 23]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       21]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       23]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] - 6*CouplingConstant[ChPTW3[4], 21]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 3*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 21]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 6*CouplingConstant[ChPTW3[4], 21]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + 3*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       21]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 21]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 3*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 21]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]]))/
   (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(CouplingConstant[ChPTW3[2], 1]*
    (2*Sqrt[3]*CouplingConstant[ChPTW3[4], 24]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]) + 
     (CouplingConstant[ChPTW3[4], 22] + 2*CouplingConstant[ChPTW3[4], 23])*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     2*CouplingConstant[ChPTW3[4], 23]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       23]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       23]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 23]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 21]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       23]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       21]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 21]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       21]*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 22]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]]))/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}}
