{{(SU2F[3, I3, k1]*SU2F[I1, k1, k2]*SU2F[I2, I4, k2] + 
    SU2F[3, I3, k1]*SU2F[I1, I4, k2]*SU2F[I2, k1, k2] + 
    SU2F[3, I2, k1]*SU2F[I1, k1, k2]*SU2F[I3, I4, k2] + 
    SU2F[3, I1, k1]*SU2F[I2, k1, k2]*SU2F[I3, I4, k2] + 
    SU2F[3, I2, k1]*SU2F[I1, I4, k2]*SU2F[I3, k1, k2] + 
    SU2F[3, I1, k1]*SU2F[I2, I4, k2]*SU2F[I3, k1, k2] + 
    6*SU2F[3, I3, I4]*SUNDelta[I1, I2] + 6*SU2F[3, I2, I4]*SUNDelta[I1, I3] + 
    6*SU2F[3, I1, I4]*SUNDelta[I2, I3])/
   (12*DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2)}, 
 {(SU2F[3, I4, k1]*SU2F[I1, k1, k2]*SU2F[I2, I3, k2] + 
    SU2F[3, I4, k1]*SU2F[I1, I3, k2]*SU2F[I2, k1, k2] - 
    SU2F[3, I2, k1]*SU2F[I1, k1, k2]*SU2F[I3, I4, k2] - 
    SU2F[3, I1, k1]*SU2F[I2, k1, k2]*SU2F[I3, I4, k2] + 
    SU2F[3, I2, k1]*SU2F[I1, I3, k2]*SU2F[I4, k1, k2] + 
    SU2F[3, I1, k1]*SU2F[I2, I3, k2]*SU2F[I4, k1, k2] - 
    6*SU2F[3, I3, I4]*SUNDelta[I1, I2] + 6*SU2F[3, I2, I3]*SUNDelta[I1, I4] + 
    6*SU2F[3, I1, I3]*SUNDelta[I2, I4])/
   (12*DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2)}, 
 {(-(SU2F[3, I4, k1]*SU2F[I1, k1, k2]*SU2F[I2, I3, k2]) - 
    SU2F[3, I3, k1]*SU2F[I1, k1, k2]*SU2F[I2, I4, k2] + 
    SU2F[3, I4, k1]*SU2F[I1, I2, k2]*SU2F[I3, k1, k2] - 
    SU2F[3, I1, k1]*SU2F[I2, I4, k2]*SU2F[I3, k1, k2] + 
    SU2F[3, I3, k1]*SU2F[I1, I2, k2]*SU2F[I4, k1, k2] - 
    SU2F[3, I1, k1]*SU2F[I2, I3, k2]*SU2F[I4, k1, k2] - 
    6*SU2F[3, I2, I4]*SUNDelta[I1, I3] - 6*SU2F[3, I2, I3]*SUNDelta[I1, I4] + 
    6*SU2F[3, I1, I2]*SUNDelta[I3, I4])/
   (12*DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2)}, 
 {(-(SU2F[3, I4, k1]*SU2F[I1, I3, k2]*SU2F[I2, k1, k2]) - 
    SU2F[3, I3, k1]*SU2F[I1, I4, k2]*SU2F[I2, k1, k2] - 
    SU2F[3, I4, k1]*SU2F[I1, I2, k2]*SU2F[I3, k1, k2] - 
    SU2F[3, I2, k1]*SU2F[I1, I4, k2]*SU2F[I3, k1, k2] - 
    SU2F[3, I3, k1]*SU2F[I1, I2, k2]*SU2F[I4, k1, k2] - 
    SU2F[3, I2, k1]*SU2F[I1, I3, k2]*SU2F[I4, k1, k2] - 
    6*SU2F[3, I1, I4]*SUNDelta[I2, I3] - 6*SU2F[3, I1, I3]*SUNDelta[I2, I4] - 
    6*SU2F[3, I1, I2]*SUNDelta[I3, I4])/
   (12*DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2)}}
