{{((I/24)*(UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((-I/24)*(UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]]]] - UTrace1[NonCommutative[
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((-I/24)*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]]]] - UTrace1[NonCommutative[
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((-I/24)*(UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((-I/24)*(UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((-I/24)*(UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((I/144)*(UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((I/144)*(UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((I/144)*(UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {((I/144)*CouplingConstant[ChPTPhotonsLeptons3[2], RenormalizationState[0]]*
    (Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] - 
     4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] - 
     4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + 6*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
     6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
     6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] - 
     4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] - 
     4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 6*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
     6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
     6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] - 
     4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] - 
     4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 6*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
     6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
     6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     4*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 6*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 6*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     6*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 4*Sqrt[3]*
      UTrace1[NonCommutative[UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 
     9*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]] - 
     6*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 
     2*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 
     3*UTrace1[NonCommutative[UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[3]]]] + UTrace1[NonCommutative[
       UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[8]], UMatrix[UGenerator[8]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}}
