{{(-I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/4*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/4*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(-I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/4*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/4*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/4*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/4*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(-I/4*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/4*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/4*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/4*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/6*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/4*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/12*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/4*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/12*SU3Delta[6, k1]*SU3Delta[8, k2]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    (Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {(I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/24*SU3Delta[6, k1]*SU3Delta[8, k2]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    (Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4) - 
   (I/24*SU3Delta[3, k1]*SU3Delta[6, k2]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 + 
   (I/36*SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4 - 
   (I/24*SU3Delta[6, k1]*SU3Delta[8, k2]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[k2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    (Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4) + 
   (I/24*SU3Delta[3, k1]*SU3Delta[6, k2]*CouplingConstant[ChPTW3[2], 2]*
     (UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[k1]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[k1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I4]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
      UTrace1[NonCommutative[UMatrix[UGenerator[k2]], 
        UMatrix[UGenerator[k1]], UMatrix[UGenerator[I4]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + UTrace1[NonCommutative[
        UMatrix[UGenerator[k2]], UMatrix[UGenerator[k1]], 
        UMatrix[UGenerator[I4]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}}
