{{(16*I*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 1, 
       RenormalizationState[0]] + SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 2, RenormalizationState[0]] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 2, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 3, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {(16*I*(2*SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 1, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 2, RenormalizationState[0]] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 2, 
       RenormalizationState[0]] + SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 3, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {(16*I*(2*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 1, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 2, RenormalizationState[0]] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 2, 
       RenormalizationState[0]] + SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 3, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((8*I)/3*(10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       4, RenormalizationState[0]] - 2*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 4, RenormalizationState[0]] - 
     2*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]] + 5*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]] - 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 5, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((8*I)/3*(10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       4, RenormalizationState[0]] - 2*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 4, RenormalizationState[0]] - 
     2*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]] + 5*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]] - 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 5, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-8*I)/3*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       4, RenormalizationState[0]] - 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 4, RenormalizationState[0]] + 
     2*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]] - 
     5*SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 5, 
       RenormalizationState[0]] + SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-8*I)/3*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       4, RenormalizationState[0]] - 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 4, RenormalizationState[0]] + 
     2*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]] - 
     5*SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 5, 
       RenormalizationState[0]] + SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-8*I)/3*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       4, RenormalizationState[0]] + 2*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 4, RenormalizationState[0]] - 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 5, 
       RenormalizationState[0]] - 5*SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-8*I)/3*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       4, RenormalizationState[0]] + 2*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 4, RenormalizationState[0]] - 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 5, 
       RenormalizationState[0]] - 5*SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((64*I)/3*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       6, RenormalizationState[0]] + 2*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 6, RenormalizationState[0]] + 
     2*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 6, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 8, RenormalizationState[0]] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 8, 
       RenormalizationState[0]] + SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 8, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-2*I)/27*(108*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]] - 
     128*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 2, 
       RenormalizationState[0]] + 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]] + 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 2, 
       RenormalizationState[0]] + 54*SU2F[3, I1, I3]*SU2F[3, I2, I4]*
      UCouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]] + 
     54*SU2F[3, I1, I2]*SU2F[3, I3, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I3]*SUNDelta[3, I4]*
      SUNDelta[I1, I2]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I2]*SUNDelta[3, I4]*
      SUNDelta[I1, I3]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] + 144*SUNDelta[3, I2]*SUNDelta[3, I3]*
      SUNDelta[I1, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I3]*
      SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I2]*
      SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 27*SU2F[3, I1, I3]*SU2F[3, I2, I4]*
      UCouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]] - 
     27*SU2F[3, I1, I2]*SU2F[3, I3, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I3]*SUNDelta[3, I4]*
      SUNDelta[I1, I2]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I2]*SUNDelta[3, I4]*
      SUNDelta[I1, I3]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] + 72*SUNDelta[3, I2]*SUNDelta[3, I3]*
      SUNDelta[I1, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I3]*
      SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I2]*
      SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 20*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]] + 
     10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 10, 
       RenormalizationState[0]] + 10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-2*I)/27*(108*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      UCouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]] - 
     128*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 2, 
       RenormalizationState[0]] + 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]] + 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 2, 
       RenormalizationState[0]] + 54*SU2F[3, I1, I3]*SU2F[3, I2, I4]*
      UCouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]] + 
     54*SU2F[3, I1, I2]*SU2F[3, I3, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I3]*SUNDelta[3, I4]*
      SUNDelta[I1, I2]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I2]*SUNDelta[3, I4]*
      SUNDelta[I1, I3]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] + 144*SUNDelta[3, I1]*SUNDelta[3, I4]*
      SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I3]*
      SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I2]*
      SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 27*SU2F[3, I1, I3]*SU2F[3, I2, I4]*
      UCouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]] - 
     27*SU2F[3, I1, I2]*SU2F[3, I3, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I3]*SUNDelta[3, I4]*
      SUNDelta[I1, I2]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I2]*SUNDelta[3, I4]*
      SUNDelta[I1, I3]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] + 72*SUNDelta[3, I1]*SUNDelta[3, I4]*
      SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I3]*
      SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I2]*
      SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 20*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]] + 
     10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 10, 
       RenormalizationState[0]] + 10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-2*I)/27*(10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[
       ChPTEM2[4], 2, RenormalizationState[0]] + 108*SUNDelta[3, I1]*
      SUNDelta[3, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 2, 
       RenormalizationState[0]] - 128*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]] + 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 2, 
       RenormalizationState[0]] + 54*SU2F[3, I1, I4]*SU2F[3, I2, I3]*
      UCouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]] - 
     54*SU2F[3, I1, I2]*SU2F[3, I3, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I3]*SUNDelta[3, I4]*
      SUNDelta[I1, I2]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] + 144*SUNDelta[3, I2]*SUNDelta[3, I4]*
      SUNDelta[I1, I3]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I2]*SUNDelta[3, I3]*
      SUNDelta[I1, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I4]*
      SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I2]*
      SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 27*SU2F[3, I1, I4]*SU2F[3, I2, I3]*
      UCouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]] + 
     27*SU2F[3, I1, I2]*SU2F[3, I3, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I3]*SUNDelta[3, I4]*
      SUNDelta[I1, I2]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] + 72*SUNDelta[3, I2]*SUNDelta[3, I4]*
      SUNDelta[I1, I3]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I2]*SUNDelta[3, I3]*
      SUNDelta[I1, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I4]*
      SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I2]*
      SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] + 10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]] - 
     20*SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 10, 
       RenormalizationState[0]] + 10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-2*I)/27*(108*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      UCouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]] + 
     10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 2, 
       RenormalizationState[0]] - 128*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]] + 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 2, 
       RenormalizationState[0]] + 54*SU2F[3, I1, I4]*SU2F[3, I2, I3]*
      UCouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]] - 
     54*SU2F[3, I1, I2]*SU2F[3, I3, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I3]*SUNDelta[3, I4]*
      SUNDelta[I1, I2]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I2]*SUNDelta[3, I3]*
      SUNDelta[I1, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I4]*
      SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] + 144*SUNDelta[3, I1]*SUNDelta[3, I3]*
      SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I2]*
      SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 27*SU2F[3, I1, I4]*SU2F[3, I2, I3]*
      UCouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]] + 
     27*SU2F[3, I1, I2]*SU2F[3, I3, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I3]*SUNDelta[3, I4]*
      SUNDelta[I1, I2]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I2]*SUNDelta[3, I3]*
      SUNDelta[I1, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I4]*
      SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] + 72*SUNDelta[3, I1]*SUNDelta[3, I3]*
      SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I2]*
      SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] + 10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]] - 
     20*SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 10, 
       RenormalizationState[0]] + 10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-2*I)/27*(10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[
       ChPTEM2[4], 2, RenormalizationState[0]] + 10*SUNDelta[I1, I3]*
      SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 2, 
       RenormalizationState[0]] + 108*SUNDelta[3, I1]*SUNDelta[3, I2]*
      SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 2, 
       RenormalizationState[0]] - 128*SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]] - 
     54*SU2F[3, I1, I4]*SU2F[3, I2, I3]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 54*SU2F[3, I1, I3]*SU2F[3, I2, I4]*
      UCouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]] + 
     144*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      UCouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]] - 
     36*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      UCouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]] - 
     36*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      UCouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]] - 
     36*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]] - 
     36*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]] + 
     27*SU2F[3, I1, I4]*SU2F[3, I2, I3]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] + 27*SU2F[3, I1, I3]*SU2F[3, I2, I4]*
      UCouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]] + 
     72*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      UCouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]] - 
     18*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      UCouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]] - 
     18*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      UCouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]] - 
     18*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]] - 
     18*SUNDelta[3, I1]*SUNDelta[3, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]] + 
     10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 10, 
       RenormalizationState[0]] + 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]] - 
     20*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 10, 
       RenormalizationState[0]]))/DecayConstant[PseudoScalar[2], 
     RenormalizationState[0]]^4}, 
 {((-2*I)/27*(108*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      UCouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]] + 
     10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 2, 
       RenormalizationState[0]] + 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPTEM2[4], 2, RenormalizationState[0]] - 
     128*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 2, 
       RenormalizationState[0]] - 54*SU2F[3, I1, I4]*SU2F[3, I2, I3]*
      UCouplingConstant[ChPTEM2[4], 3, RenormalizationState[0]] - 
     54*SU2F[3, I1, I3]*SU2F[3, I2, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I2]*SUNDelta[3, I4]*
      SUNDelta[I1, I3]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I2]*SUNDelta[3, I3]*
      SUNDelta[I1, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I4]*
      SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] - 36*SUNDelta[3, I1]*SUNDelta[3, I3]*
      SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] + 144*SUNDelta[3, I1]*SUNDelta[3, I2]*
      SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 3, 
       RenormalizationState[0]] + 27*SU2F[3, I1, I4]*SU2F[3, I2, I3]*
      UCouplingConstant[ChPTEM2[4], 4, RenormalizationState[0]] + 
     27*SU2F[3, I1, I3]*SU2F[3, I2, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I2]*SUNDelta[3, I4]*
      SUNDelta[I1, I3]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I2]*SUNDelta[3, I3]*
      SUNDelta[I1, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I4]*
      SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] - 18*SUNDelta[3, I1]*SUNDelta[3, I3]*
      SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] + 72*SUNDelta[3, I1]*SUNDelta[3, I2]*
      SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 4, 
       RenormalizationState[0]] + 10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]] + 
     10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 10, 
       RenormalizationState[0]] - 20*SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPTEM2[4], 10, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-20*I)/27*(18*SUNDelta[3, I3]*SUNDelta[3, I4]*SUNDelta[I1, I2]*
      UCouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]] + 
     18*SUNDelta[3, I2]*SUNDelta[3, I4]*SUNDelta[I1, I3]*
      UCouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]] + 
     18*SUNDelta[3, I2]*SUNDelta[3, I3]*SUNDelta[I1, I4]*
      UCouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]] + 
     18*SUNDelta[3, I1]*SUNDelta[3, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]] - 
     37*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPTEM2[4], 7, 
       RenormalizationState[0]] + 18*SUNDelta[3, I1]*SUNDelta[3, I3]*
      SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 7, 
       RenormalizationState[0]] - 37*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]] + 
     18*SUNDelta[3, I1]*SUNDelta[3, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPTEM2[4], 7, RenormalizationState[0]] - 
     37*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPTEM2[4], 7, 
       RenormalizationState[0]] - SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPTEM2[4], 11, RenormalizationState[0]] - 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPTEM2[4], 11, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPTEM2[4], 11, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}}
