{{(8*I*SU3Delta[7, I1]*CouplingConstant[ChPTW3[2], 1]*
    CouplingConstant[ChPTW3[4], 11])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}, 
 {(-8*I*SU3Delta[7, I1]*CouplingConstant[ChPTW3[2], 1]*
    CouplingConstant[ChPTW3[4], 11])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}, 
 {(8*I*(2*SU3Delta[7, I1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 10] + SU3Delta[7, I1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 11]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}, 
 {(-8*I*(2*SU3Delta[7, I1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 10] + SU3Delta[7, I1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 11]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}}
