{{((-4*I)/3*QuarkCondensate[RenormalizationState[0]]*
    UCouplingConstant[ChPTW3[2], 1]*(3*UCouplingConstant[ChPTW3[4], 13]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[4], 11]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + Sqrt[3]*UCouplingConstant[ChPTW3[4], 11]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UCouplingConstant[ChPTW3[4], 13]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]*
      (Sqrt[3]*UTrace1[FANonCommutative[UMatrix[UGenerator[8]], 
          UMatrix[UGenerator[I2]]]] + 
       3*UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[3]]]] + Sqrt[3]*UTrace1[FANonCommutative[
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]) + 
     3*UCouplingConstant[ChPTW3[4], 11]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + Sqrt[3]*UCouplingConstant[ChPTW3[4], 11]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     2*UCouplingConstant[ChPTW3[4], 10]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - 3*UCouplingConstant[ChPTW3[4], 11]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     2*UCouplingConstant[ChPTW3[4], 12]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - 2*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     3*UCouplingConstant[ChPTW3[4], 11]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 2*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[4], 10]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     3*UCouplingConstant[ChPTW3[4], 10]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[4], 12]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + Sqrt[3]*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + Sqrt[3]*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 3*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] + Sqrt[3]*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + 3*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 3*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + Sqrt[3]*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + Sqrt[3]*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 3*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + Sqrt[3]*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] + 3*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + Sqrt[3]*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]]))/DecayConstant[PseudoScalar[1], 
     RenormalizationState[0]]^3}, 
 {((4*I)/3*QuarkCondensate[RenormalizationState[0]]*
    UCouplingConstant[ChPTW3[2], 1]*(3*UCouplingConstant[ChPTW3[4], 13]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[4], 11]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - Sqrt[3]*UCouplingConstant[ChPTW3[4], 11]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     UCouplingConstant[ChPTW3[4], 13]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]*
      (Sqrt[3]*UTrace1[FANonCommutative[UMatrix[UGenerator[8]], 
          UMatrix[UGenerator[I2]]]] - 
       3*UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[3]]]] + Sqrt[3]*UTrace1[FANonCommutative[
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]) + 
     3*UCouplingConstant[ChPTW3[4], 11]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - Sqrt[3]*UCouplingConstant[ChPTW3[4], 11]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     2*UCouplingConstant[ChPTW3[4], 10]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 3*UCouplingConstant[ChPTW3[4], 11]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     2*UCouplingConstant[ChPTW3[4], 12]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 2*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[4], 11]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 2*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[4], 10]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     3*UCouplingConstant[ChPTW3[4], 10]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[4], 12]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - Sqrt[3]*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - Sqrt[3]*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 3*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] - Sqrt[3]*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + 3*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 3*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - Sqrt[3]*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - Sqrt[3]*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 3*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] - Sqrt[3]*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] + 3*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - Sqrt[3]*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]]))/DecayConstant[PseudoScalar[1], 
     RenormalizationState[0]]^3}, 
 {((4*I)/3*QuarkCondensate[RenormalizationState[0]]*
    UCouplingConstant[ChPTW3[2], 1]*
    (2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 13]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]]*
      (UTrace1[FANonCommutative[UMatrix[UGenerator[8]], 
         UMatrix[UGenerator[I2]]]] + UTrace1[FANonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]) + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 11]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]]]]*
      (UTrace1[FANonCommutative[UMatrix[UGenerator[I1]], 
         UMatrix[UGenerator[I2]]]] + UTrace1[FANonCommutative[
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]) + 
     2*UCouplingConstant[ChPTW3[4], 10]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 3*UCouplingConstant[ChPTW3[4], 11]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     2*UCouplingConstant[ChPTW3[4], 12]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 2*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[4], 11]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 2*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 10]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       10]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       12]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       12]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       10]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 12]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       10]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]]))/DecayConstant[PseudoScalar[1], 
     RenormalizationState[0]]^3}}
