{{(2*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
    (3*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     3*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] - 
     Sqrt[3]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(2*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
    (-3*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     3*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] - 
     Sqrt[3]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(4*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
    (-UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
   (Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}}
