{{((16*I)*(2*CouplingConstant[ChPT2[4], 1, RenormalizationState[0]]*
      SUNDelta[I1, I4]*SUNDelta[I2, I3] + 
     CouplingConstant[ChPT2[4], 3, RenormalizationState[0]]*SUNDelta[I1, I4]*
      SUNDelta[I2, I3] + CouplingConstant[ChPT2[4], 2, 
       RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] + 
     CouplingConstant[ChPT2[4], 2, RenormalizationState[0]]*SUNDelta[I1, I2]*
      SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2], 
     RenormalizationState[0]]^4}, 
 {((16*I)*(CouplingConstant[ChPT2[4], 2, RenormalizationState[0]]*
      SUNDelta[I1, I4]*SUNDelta[I2, I3] + 
     2*CouplingConstant[ChPT2[4], 1, RenormalizationState[0]]*
      SUNDelta[I1, I3]*SUNDelta[I2, I4] + 
     CouplingConstant[ChPT2[4], 3, RenormalizationState[0]]*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] + CouplingConstant[ChPT2[4], 2, 
       RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((16*I)*(CouplingConstant[ChPT2[4], 2, RenormalizationState[0]]*
      SUNDelta[I1, I4]*SUNDelta[I2, I3] + 
     CouplingConstant[ChPT2[4], 2, RenormalizationState[0]]*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] + 2*CouplingConstant[ChPT2[4], 1, 
       RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] + 
     CouplingConstant[ChPT2[4], 3, RenormalizationState[0]]*SUNDelta[I1, I2]*
      SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2], 
     RenormalizationState[0]]^4}, 
 {(((8*I)/3)*(10*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
      SUNDelta[I1, I4]*SUNDelta[I2, I3] + 
     5*CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*
      SUNDelta[I1, I4]*SUNDelta[I2, I3] - 
     2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
      SUNDelta[I1, I3]*SUNDelta[I2, I4] - 
     CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] - 2*CouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] - 
     CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I2]*
      SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2], 
     RenormalizationState[0]]^4}, 
 {(((8*I)/3)*(10*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
      SUNDelta[I1, I4]*SUNDelta[I2, I3] + 
     5*CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*
      SUNDelta[I1, I4]*SUNDelta[I2, I3] - 
     2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
      SUNDelta[I1, I3]*SUNDelta[I2, I4] - 
     CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] - 2*CouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] - 
     CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I2]*
      SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2], 
     RenormalizationState[0]]^4}, 
 {(((-8*I)/3)*(2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
      SUNDelta[I1, I4]*SUNDelta[I2, I3] + 
     CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I4]*
      SUNDelta[I2, I3] - 10*CouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] - 
     5*CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*
      SUNDelta[I1, I3]*SUNDelta[I2, I4] + 
     2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
      SUNDelta[I1, I2]*SUNDelta[I3, I4] + 
     CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I2]*
      SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2], 
     RenormalizationState[0]]^4}, 
 {(((-8*I)/3)*(2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
      SUNDelta[I1, I4]*SUNDelta[I2, I3] + 
     CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I4]*
      SUNDelta[I2, I3] - 10*CouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] - 
     5*CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*
      SUNDelta[I1, I3]*SUNDelta[I2, I4] + 
     2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
      SUNDelta[I1, I2]*SUNDelta[I3, I4] + 
     CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I2]*
      SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2], 
     RenormalizationState[0]]^4}, 
 {(((-8*I)/3)*(2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
      SUNDelta[I1, I4]*SUNDelta[I2, I3] + 
     CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I4]*
      SUNDelta[I2, I3] + 2*CouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] + 
     CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] - 10*CouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] - 
     5*CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*
      SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {(((-8*I)/3)*(2*CouplingConstant[ChPT2[4], 4, RenormalizationState[0]]*
      SUNDelta[I1, I4]*SUNDelta[I2, I3] + 
     CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I4]*
      SUNDelta[I2, I3] + 2*CouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] + 
     CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] - 10*CouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] - 
     5*CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]*
      SUNDelta[I1, I2]*SUNDelta[I3, I4]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {(((64*I)/3)*(2*CouplingConstant[ChPT2[4], 6, RenormalizationState[0]]*
      SUNDelta[I1, I4]*SUNDelta[I2, I3] + 
     CouplingConstant[ChPT2[4], 8, RenormalizationState[0]]*SUNDelta[I1, I4]*
      SUNDelta[I2, I3] + 2*CouplingConstant[ChPT2[4], 6, 
       RenormalizationState[0]]*SUNDelta[I1, I3]*SUNDelta[I2, I4] + 
     CouplingConstant[ChPT2[4], 8, RenormalizationState[0]]*SUNDelta[I1, I3]*
      SUNDelta[I2, I4] + 2*CouplingConstant[ChPT2[4], 6, 
       RenormalizationState[0]]*SUNDelta[I1, I2]*SUNDelta[I3, I4] + 
     CouplingConstant[ChPT2[4], 8, RenormalizationState[0]]*SUNDelta[I1, I2]*
      SUNDelta[I3, I4]))/DecayConstant[PseudoScalar[2], 
     RenormalizationState[0]]^4}}
