{{((32*I)/3*(3*SU3Delta[I1, I2]*CouplingConstant[ChPT3[4], 6, 
       RenormalizationState[0]] - 3*SU3D[3, I1, I2]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] - 
     Sqrt[3]*SU3D[8, I1, I2]*CouplingConstant[ChPT3[4], 8, 
       RenormalizationState[0]] + SU3Delta[I1, I2]*CouplingConstant[
       ChPT3[4], 8, RenormalizationState[0]]))/DecayConstant[PseudoScalar[1], 
    RenormalizationState[0]]}, 
 {((32*I)/3*(3*SU3Delta[I1, I2]*CouplingConstant[ChPT3[4], 6, 
       RenormalizationState[0]] + 3*SU3D[3, I1, I2]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] - 
     Sqrt[3]*SU3D[8, I1, I2]*CouplingConstant[ChPT3[4], 8, 
       RenormalizationState[0]] + SU3Delta[I1, I2]*CouplingConstant[
       ChPT3[4], 8, RenormalizationState[0]]))/DecayConstant[PseudoScalar[1], 
    RenormalizationState[0]]}, 
 {((32*I)/3*(3*SU3Delta[I1, I2]*CouplingConstant[ChPT3[4], 6, 
       RenormalizationState[0]] + 2*Sqrt[3]*SU3D[8, I1, I2]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] + 
     SU3Delta[I1, I2]*CouplingConstant[ChPT3[4], 8, RenormalizationState[
        0]]))/DecayConstant[PseudoScalar[1], RenormalizationState[0]]}}
