{{-(SUNDelta[6, si10]*UCouplingConstant[ChPTW3[2], 1]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[si10]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]])/
    (2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si10]*UCouplingConstant[ChPTW3[2], 1]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si10]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]]]])/
    (2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si9]*UCouplingConstant[ChPTW3[2], 1]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si9]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]]]])/
    (2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si9]*UCouplingConstant[ChPTW3[2], 1]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si9]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]]]])/
    (2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {-(SUNDelta[6, si10]*UCouplingConstant[ChPTW3[2], 1]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[si10]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]])/
    (2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si10]*UCouplingConstant[ChPTW3[2], 1]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si10]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]]]])/
    (2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si9]*UCouplingConstant[ChPTW3[2], 1]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si9]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]]]])/
    (2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si9]*UCouplingConstant[ChPTW3[2], 1]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si9]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]]]])/
    (2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {-(SUNDelta[6, si10]*UCouplingConstant[ChPTW3[2], 1]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[si10]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]])/
    (2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si10]*UCouplingConstant[ChPTW3[2], 1]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si10]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]]]])/
    (2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si9]*UCouplingConstant[ChPTW3[2], 1]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si9]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]]]])/
    (2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si9]*UCouplingConstant[ChPTW3[2], 1]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si9]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]]]])/
    (2*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(SUNDelta[6, si15]*SUNDelta[8, si16]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si15]], 
       UMatrix[UGenerator[si16]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]])/
    (3*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si15]*SUNDelta[8, si16]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si15]], 
       UMatrix[UGenerator[si16]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]])/
    (3*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si15]*SUNDelta[8, si16]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si15]], 
       UMatrix[UGenerator[si16]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]])/
    (3*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si15]*SUNDelta[8, si16]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si15]], 
       UMatrix[UGenerator[si16]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]])/
    (3*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si15]*SUNDelta[8, si16]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si15]], 
       UMatrix[UGenerator[si16]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]])/
    (3*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si15]*SUNDelta[8, si16]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si15]], 
       UMatrix[UGenerator[si16]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]])/
    (3*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si25]*SUNDelta[8, si26]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si25]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[si26]]]])/
    (3*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si25]*SUNDelta[8, si26]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si25]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[si26]]]])/
    (3*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si25]*SUNDelta[8, si26]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si25]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[si26]]]])/
    (3*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si25]*SUNDelta[8, si26]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si25]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[si26]]]])/
    (3*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si25]*SUNDelta[8, si26]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si25]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[si26]]]])/
    (3*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si25]*SUNDelta[8, si26]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si25]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[si26]]]])/
    (3*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(SUNDelta[3, si12]*SUNDelta[6, si11]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si11]], 
       UMatrix[UGenerator[si12]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[3, si12]*SUNDelta[6, si11]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si11]], 
       UMatrix[UGenerator[si12]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[3, si12]*SUNDelta[6, si11]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si11]], 
       UMatrix[UGenerator[si12]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[3, si12]*SUNDelta[6, si11]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si11]], 
       UMatrix[UGenerator[si12]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[3, si12]*SUNDelta[6, si11]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si11]], 
       UMatrix[UGenerator[si12]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[3, si12]*SUNDelta[6, si11]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si11]], 
       UMatrix[UGenerator[si12]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si17]*SUNDelta[8, si18]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si17]], 
       UMatrix[UGenerator[si18]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si17]*SUNDelta[8, si18]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si17]], 
       UMatrix[UGenerator[si18]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si17]*SUNDelta[8, si18]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si17]], 
       UMatrix[UGenerator[si18]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si17]*SUNDelta[8, si18]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si17]], 
       UMatrix[UGenerator[si18]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si17]*SUNDelta[8, si18]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si17]], 
       UMatrix[UGenerator[si18]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si17]*SUNDelta[8, si18]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si17]], 
       UMatrix[UGenerator[si18]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[3, si22]*SUNDelta[6, si21]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si21]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[si22]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[3, si22]*SUNDelta[6, si21]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si21]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[si22]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[3, si22]*SUNDelta[6, si21]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si21]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[si22]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[3, si22]*SUNDelta[6, si21]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si21]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[si22]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[3, si22]*SUNDelta[6, si21]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si21]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[si22]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[3, si22]*SUNDelta[6, si21]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si21]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[si22]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si27]*SUNDelta[8, si28]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si27]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[si28]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si27]*SUNDelta[8, si28]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si27]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[si28]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si27]*SUNDelta[8, si28]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si27]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[si28]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si27]*SUNDelta[8, si28]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si27]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[si28]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si27]*SUNDelta[8, si28]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si27]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[si28]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si27]*SUNDelta[8, si28]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si27]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[si28]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {-(SUNDelta[3, si14]*SUNDelta[6, si13]*UCouplingConstant[ChPTW3[2], 2]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[si13]], 
        UMatrix[UGenerator[si14]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[3, si14]*SUNDelta[6, si13]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si13]], 
       UMatrix[UGenerator[si14]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[3, si14]*SUNDelta[6, si13]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si13]], 
       UMatrix[UGenerator[si14]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[3, si14]*SUNDelta[6, si13]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si13]], 
       UMatrix[UGenerator[si14]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[3, si14]*SUNDelta[6, si13]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si13]], 
       UMatrix[UGenerator[si14]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[3, si14]*SUNDelta[6, si13]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si13]], 
       UMatrix[UGenerator[si14]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si19]*SUNDelta[8, si20]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si19]], 
       UMatrix[UGenerator[si20]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si19]*SUNDelta[8, si20]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si19]], 
       UMatrix[UGenerator[si20]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si19]*SUNDelta[8, si20]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si19]], 
       UMatrix[UGenerator[si20]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si19]*SUNDelta[8, si20]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si19]], 
       UMatrix[UGenerator[si20]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si19]*SUNDelta[8, si20]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si19]], 
       UMatrix[UGenerator[si20]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) - 
   (SUNDelta[6, si19]*SUNDelta[8, si20]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si19]], 
       UMatrix[UGenerator[si20]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[3, si24]*SUNDelta[6, si23]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si23]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[si24]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[3, si24]*SUNDelta[6, si23]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si23]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[si24]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[3, si24]*SUNDelta[6, si23]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si23]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[si24]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[3, si24]*SUNDelta[6, si23]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si23]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[si24]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[3, si24]*SUNDelta[6, si23]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si23]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[si24]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[3, si24]*SUNDelta[6, si23]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si23]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[si24]]]])/
    (6*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si29]*SUNDelta[8, si30]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si29]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[si30]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si29]*SUNDelta[8, si30]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si29]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[si30]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si29]*SUNDelta[8, si30]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si29]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[si30]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si29]*SUNDelta[8, si30]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si29]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[si30]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si29]*SUNDelta[8, si30]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si29]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[si30]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3) + 
   (SUNDelta[6, si29]*SUNDelta[8, si30]*UCouplingConstant[ChPTW3[2], 2]*
     UTrace1[FANonCommutative[UMatrix[UGenerator[si29]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[si30]]]])/
    (6*Sqrt[3]*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}}
