{{(-18*SU3D[6, I4, k1]*SU3D[I1, k1, k2]*SU3D[I2, I3, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 18*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*
     SU3D[I2, I4, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    12*SU3D[6, I4, k1]*SU3D[I1, I3, k2]*SU3D[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 12*SU3D[6, I3, k1]*SU3D[I1, I4, k2]*
     SU3D[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    18*SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3D[I3, I4, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 12*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*
     SU3D[I3, I4, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    15*SU3D[6, I4, k1]*SU3D[I1, I2, k2]*SU3D[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 3*SU3D[6, I2, k1]*SU3D[I1, I4, k2]*
     SU3D[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[6, I1, k1]*SU3D[I2, I4, k2]*SU3D[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 15*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*
     SU3D[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3D[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*SU3D[6, I1, k1]*SU3D[I2, I3, k2]*
     SU3D[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    12*I*SU3D[I2, k1, k2]*SU3D[I3, I4, k1]*SU3F[6, I1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3D[I2, I4, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[I2, I3, k1]*SU3D[I4, k1, k2]*SU3F[6, I1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 18*I*SU3D[I1, k1, k2]*SU3D[I3, I4, k1]*
     SU3F[6, I2, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*I*SU3D[I1, I4, k1]*SU3D[I3, k1, k2]*SU3F[6, I2, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 3*I*SU3D[I1, I3, k1]*SU3D[I4, k1, k2]*
     SU3F[6, I2, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    18*I*SU3D[I1, k1, k2]*SU3D[I2, I4, k1]*SU3F[6, I3, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 12*I*SU3D[I1, I4, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I3, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    15*I*SU3D[I1, I2, k1]*SU3D[I4, k1, k2]*SU3F[6, I3, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 18*I*SU3D[I1, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I4, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    12*I*SU3D[I1, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I4, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 15*I*SU3D[I1, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I4, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*SU3D[I4, k1, k2]*SU3F[6, I3, k2]*SU3F[I1, I2, k1]*
     UCouplingConstant[ChPTW3[2], 1] - 3*SU3D[I3, k1, k2]*SU3F[6, I4, k2]*
     SU3F[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[6, I4, k1]*SU3D[I3, k1, k2]*SU3F[I1, I2, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3D[6, I3, k1]*SU3D[I4, k1, k2]*
     SU3F[I1, I2, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    15*SU3D[I4, k1, k2]*SU3F[6, I2, k2]*SU3F[I1, I3, k1]*
     UCouplingConstant[ChPTW3[2], 1] + 6*SU3D[I2, k1, k2]*SU3F[6, I4, k2]*
     SU3F[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    6*I*SU3D[6, I4, k1]*SU3D[I2, k1, k2]*SU3F[I1, I3, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*I*SU3D[6, I2, k1]*SU3D[I4, k1, k2]*
     SU3F[I1, I3, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    15*SU3D[I3, k1, k2]*SU3F[6, I2, k2]*SU3F[I1, I4, k1]*
     UCouplingConstant[ChPTW3[2], 1] + 6*SU3D[I2, k1, k2]*SU3F[6, I3, k2]*
     SU3F[I1, I4, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    6*I*SU3D[6, I3, k1]*SU3D[I2, k1, k2]*SU3F[I1, I4, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*I*SU3D[6, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[I1, I4, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    18*I*SU3D[6, I4, k1]*SU3D[I2, I3, k2]*SU3F[I1, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 18*I*SU3D[6, I3, k1]*SU3D[I2, I4, k2]*
     SU3F[I1, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    18*I*SU3D[6, I2, k1]*SU3D[I3, I4, k2]*SU3F[I1, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 18*SU3D[I3, I4, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    18*SU3D[I2, I4, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 18*SU3D[I2, I3, k1]*SU3F[6, I4, k2]*
     SU3F[I1, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    9*SU3D[I4, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1]*
     UCouplingConstant[ChPTW3[2], 1] - 9*I*SU3D[6, I1, k1]*SU3D[I4, k1, k2]*
     SU3F[I2, I3, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    9*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I4, k1]*
     UCouplingConstant[ChPTW3[2], 1] - 9*I*SU3D[6, I1, k1]*SU3D[I3, k1, k2]*
     SU3F[I2, I4, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    12*I*SU3D[6, I4, k1]*SU3D[I1, I3, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 12*I*SU3D[6, I3, k1]*SU3D[I1, I4, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    12*I*SU3D[6, I1, k1]*SU3D[I3, I4, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 12*SU3D[I3, I4, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    12*SU3D[I1, I4, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 12*SU3D[I1, I3, k1]*SU3F[6, I4, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    6*SU3D[6, I4, k1]*SU3F[I1, I3, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 6*I*SU3F[6, I4, k1]*SU3F[I1, I3, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    6*SU3D[6, I3, k1]*SU3F[I1, I4, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 6*I*SU3F[6, I3, k1]*SU3F[I1, I4, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    15*I*SU3D[6, I4, k1]*SU3D[I1, I2, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3D[6, I2, k1]*SU3D[I1, I4, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*I*SU3D[6, I1, k1]*SU3D[I2, I4, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 3*SU3D[I2, I4, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[I1, I4, k1]*SU3F[6, I2, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*SU3D[I1, I2, k1]*SU3F[6, I4, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[6, I4, k1]*SU3F[I1, I2, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3F[6, I4, k1]*SU3F[I1, I2, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    15*SU3D[6, I2, k1]*SU3F[I1, I4, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*I*SU3F[6, I2, k1]*SU3F[I1, I4, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    9*SU3D[6, I1, k1]*SU3F[I2, I4, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 9*I*SU3F[6, I1, k1]*SU3F[I2, I4, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    15*I*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*I*SU3D[6, I1, k1]*SU3D[I2, I3, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 3*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[I1, I3, k1]*SU3F[6, I2, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*SU3D[I1, I2, k1]*SU3F[6, I3, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[6, I3, k1]*SU3F[I1, I2, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3F[6, I3, k1]*SU3F[I1, I2, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    15*SU3D[6, I2, k1]*SU3F[I1, I3, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*I*SU3F[6, I2, k1]*SU3F[I1, I3, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    9*SU3D[6, I1, k1]*SU3F[I2, I3, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 9*I*SU3F[6, I1, k1]*SU3F[I2, I3, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    12*SU3D[I2, I3, I4]*SU3Delta[6, I1]*UCouplingConstant[ChPTW3[2], 1] + 
    8*SU3D[I1, I3, I4]*SU3Delta[6, I2]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[I1, I2, I4]*SU3Delta[6, I3]*UCouplingConstant[ChPTW3[2], 1] + 
    6*I*SU3F[I1, I2, I4]*SU3Delta[6, I3]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[I1, I2, I3]*SU3Delta[6, I4]*UCouplingConstant[ChPTW3[2], 1] + 
    6*I*SU3F[I1, I2, I3]*SU3Delta[6, I4]*UCouplingConstant[ChPTW3[2], 1] + 
    20*SU3D[6, I3, I4]*SU3Delta[I1, I2]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[6, I2, I4]*SU3Delta[I1, I3]*UCouplingConstant[ChPTW3[2], 1] + 
    6*I*SU3F[6, I2, I4]*SU3Delta[I1, I3]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[6, I2, I3]*SU3Delta[I1, I4]*UCouplingConstant[ChPTW3[2], 1] + 
    6*I*SU3F[6, I2, I3]*SU3Delta[I1, I4]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[6, I1, I4]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 1] + 
    14*I*SU3F[6, I1, I4]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[6, I1, I3]*SU3Delta[I2, I4]*UCouplingConstant[ChPTW3[2], 1] + 
    14*I*SU3F[6, I1, I3]*SU3Delta[I2, I4]*UCouplingConstant[ChPTW3[2], 1] + 
    20*SU3D[6, I1, I2]*SU3Delta[I3, I4]*UCouplingConstant[ChPTW3[2], 1] - 
    4*I*SU3F[6, I1, I2]*SU3Delta[I3, I4]*UCouplingConstant[ChPTW3[2], 1])/
   (18*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(-18*SU3D[6, I4, k1]*SU3D[I1, k1, k2]*SU3D[I2, I3, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 18*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*
     SU3D[I2, I4, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    15*SU3D[6, I4, k1]*SU3D[I1, I3, k2]*SU3D[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 3*SU3D[6, I3, k1]*SU3D[I1, I4, k2]*
     SU3D[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    18*SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3D[I3, I4, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*
     SU3D[I3, I4, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    12*SU3D[6, I4, k1]*SU3D[I1, I2, k2]*SU3D[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 12*SU3D[6, I2, k1]*SU3D[I1, I4, k2]*
     SU3D[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    12*SU3D[6, I1, k1]*SU3D[I2, I4, k2]*SU3D[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 3*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*
     SU3D[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    15*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3D[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*SU3D[6, I1, k1]*SU3D[I2, I3, k2]*
     SU3D[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[I2, k1, k2]*SU3D[I3, I4, k1]*SU3F[6, I1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 12*I*SU3D[I2, I4, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[I2, I3, k1]*SU3D[I4, k1, k2]*SU3F[6, I1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 18*I*SU3D[I1, k1, k2]*SU3D[I3, I4, k1]*
     SU3F[6, I2, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    12*I*SU3D[I1, I4, k1]*SU3D[I3, k1, k2]*SU3F[6, I2, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 15*I*SU3D[I1, I3, k1]*SU3D[I4, k1, k2]*
     SU3F[6, I2, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    18*I*SU3D[I1, k1, k2]*SU3D[I2, I4, k1]*SU3F[6, I3, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 3*I*SU3D[I1, I4, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I3, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*I*SU3D[I1, I2, k1]*SU3D[I4, k1, k2]*SU3F[6, I3, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 18*I*SU3D[I1, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I4, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    15*I*SU3D[I1, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I4, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 12*I*SU3D[I1, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I4, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    15*SU3D[I4, k1, k2]*SU3F[6, I3, k2]*SU3F[I1, I2, k1]*
     UCouplingConstant[ChPTW3[2], 1] + 6*SU3D[I3, k1, k2]*SU3F[6, I4, k2]*
     SU3F[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    6*I*SU3D[6, I4, k1]*SU3D[I3, k1, k2]*SU3F[I1, I2, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*I*SU3D[6, I3, k1]*SU3D[I4, k1, k2]*
     SU3F[I1, I2, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*SU3D[I4, k1, k2]*SU3F[6, I2, k2]*SU3F[I1, I3, k1]*
     UCouplingConstant[ChPTW3[2], 1] - 3*SU3D[I2, k1, k2]*SU3F[6, I4, k2]*
     SU3F[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[6, I4, k1]*SU3D[I2, k1, k2]*SU3F[I1, I3, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3D[6, I2, k1]*SU3D[I4, k1, k2]*
     SU3F[I1, I3, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    6*SU3D[I3, k1, k2]*SU3F[6, I2, k2]*SU3F[I1, I4, k1]*
     UCouplingConstant[ChPTW3[2], 1] + 15*SU3D[I2, k1, k2]*SU3F[6, I3, k2]*
     SU3F[I1, I4, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    15*I*SU3D[6, I3, k1]*SU3D[I2, k1, k2]*SU3F[I1, I4, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 6*I*SU3D[6, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[I1, I4, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    18*I*SU3D[6, I4, k1]*SU3D[I2, I3, k2]*SU3F[I1, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 18*I*SU3D[6, I3, k1]*SU3D[I2, I4, k2]*
     SU3F[I1, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    18*I*SU3D[6, I2, k1]*SU3D[I3, I4, k2]*SU3F[I1, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 18*SU3D[I3, I4, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    18*SU3D[I2, I4, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 18*SU3D[I2, I3, k1]*SU3F[6, I4, k2]*
     SU3F[I1, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    9*SU3D[I4, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1]*
     UCouplingConstant[ChPTW3[2], 1] + 9*I*SU3D[6, I1, k1]*SU3D[I4, k1, k2]*
     SU3F[I2, I3, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    15*I*SU3D[6, I4, k1]*SU3D[I1, I3, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3D[6, I3, k1]*SU3D[I1, I4, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*I*SU3D[6, I1, k1]*SU3D[I3, I4, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 3*SU3D[I3, I4, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[I1, I4, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*SU3D[I1, I3, k1]*SU3F[6, I4, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[6, I4, k1]*SU3F[I1, I3, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3F[6, I4, k1]*SU3F[I1, I3, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    15*SU3D[6, I3, k1]*SU3F[I1, I4, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*I*SU3F[6, I3, k1]*SU3F[I1, I4, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    9*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[I3, I4, k1]*
     UCouplingConstant[ChPTW3[2], 1] - 9*I*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*
     SU3F[I3, I4, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    9*SU3D[6, I1, k1]*SU3F[I2, k1, k2]*SU3F[I3, I4, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 9*I*SU3F[6, I1, k1]*SU3F[I2, k1, k2]*
     SU3F[I3, I4, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    12*I*SU3D[6, I4, k1]*SU3D[I1, I2, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 12*I*SU3D[6, I2, k1]*SU3D[I1, I4, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    12*I*SU3D[6, I1, k1]*SU3D[I2, I4, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 12*SU3D[I2, I4, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    12*SU3D[I1, I4, k1]*SU3F[6, I2, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 12*SU3D[I1, I2, k1]*SU3F[6, I4, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    6*SU3D[6, I4, k1]*SU3F[I1, I2, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 6*I*SU3F[6, I4, k1]*SU3F[I1, I2, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    6*SU3D[6, I2, k1]*SU3F[I1, I4, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 6*I*SU3F[6, I2, k1]*SU3F[I1, I4, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*I*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*I*SU3D[6, I1, k1]*SU3D[I2, I3, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 3*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    15*SU3D[I1, I3, k1]*SU3F[6, I2, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*SU3D[I1, I2, k1]*SU3F[6, I3, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    15*SU3D[6, I3, k1]*SU3F[I1, I2, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*I*SU3F[6, I3, k1]*SU3F[I1, I2, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[6, I2, k1]*SU3F[I1, I3, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3F[6, I2, k1]*SU3F[I1, I3, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    9*SU3D[6, I1, k1]*SU3F[I2, I3, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 9*I*SU3F[6, I1, k1]*SU3F[I2, I3, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    12*SU3D[I2, I3, I4]*SU3Delta[6, I1]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[I1, I3, I4]*SU3Delta[6, I2]*UCouplingConstant[ChPTW3[2], 1] + 
    6*I*SU3F[I1, I3, I4]*SU3Delta[6, I2]*UCouplingConstant[ChPTW3[2], 1] + 
    8*SU3D[I1, I2, I4]*SU3Delta[6, I3]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[I1, I2, I3]*SU3Delta[6, I4]*UCouplingConstant[ChPTW3[2], 1] - 
    6*I*SU3F[I1, I2, I3]*SU3Delta[6, I4]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[6, I3, I4]*SU3Delta[I1, I2]*UCouplingConstant[ChPTW3[2], 1] + 
    6*I*SU3F[6, I3, I4]*SU3Delta[I1, I2]*UCouplingConstant[ChPTW3[2], 1] + 
    20*SU3D[6, I2, I4]*SU3Delta[I1, I3]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[6, I2, I3]*SU3Delta[I1, I4]*UCouplingConstant[ChPTW3[2], 1] - 
    6*I*SU3F[6, I2, I3]*SU3Delta[I1, I4]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[6, I1, I4]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 1] + 
    14*I*SU3F[6, I1, I4]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 1] + 
    20*SU3D[6, I1, I3]*SU3Delta[I2, I4]*UCouplingConstant[ChPTW3[2], 1] - 
    4*I*SU3F[6, I1, I3]*SU3Delta[I2, I4]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[6, I1, I2]*SU3Delta[I3, I4]*UCouplingConstant[ChPTW3[2], 1] + 
    14*I*SU3F[6, I1, I2]*SU3Delta[I3, I4]*UCouplingConstant[ChPTW3[2], 1])/
   (18*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(18*SU3D[6, I4, k1]*SU3D[I1, k1, k2]*SU3D[I2, I3, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 18*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*
     SU3D[I2, I4, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*SU3D[6, I4, k1]*SU3D[I1, I3, k2]*SU3D[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 15*SU3D[6, I3, k1]*SU3D[I1, I4, k2]*
     SU3D[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    18*SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3D[I3, I4, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*
     SU3D[I3, I4, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*SU3D[6, I4, k1]*SU3D[I1, I2, k2]*SU3D[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 15*SU3D[6, I2, k1]*SU3D[I1, I4, k2]*
     SU3D[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[6, I1, k1]*SU3D[I2, I4, k2]*SU3D[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 12*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*
     SU3D[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    12*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3D[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 12*SU3D[6, I1, k1]*SU3D[I2, I3, k2]*
     SU3D[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[I2, k1, k2]*SU3D[I3, I4, k1]*SU3F[6, I1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3D[I2, I4, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    12*I*SU3D[I2, I3, k1]*SU3D[I4, k1, k2]*SU3F[6, I1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 18*I*SU3D[I1, k1, k2]*SU3D[I3, I4, k1]*
     SU3F[6, I2, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    15*I*SU3D[I1, I4, k1]*SU3D[I3, k1, k2]*SU3F[6, I2, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 12*I*SU3D[I1, I3, k1]*SU3D[I4, k1, k2]*
     SU3F[6, I2, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    18*I*SU3D[I1, k1, k2]*SU3D[I2, I4, k1]*SU3F[6, I3, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 15*I*SU3D[I1, I4, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I3, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    12*I*SU3D[I1, I2, k1]*SU3D[I4, k1, k2]*SU3F[6, I3, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 18*I*SU3D[I1, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I4, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*I*SU3D[I1, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I4, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 3*I*SU3D[I1, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I4, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    6*SU3D[I4, k1, k2]*SU3F[6, I3, k2]*SU3F[I1, I2, k1]*
     UCouplingConstant[ChPTW3[2], 1] + 15*SU3D[I3, k1, k2]*SU3F[6, I4, k2]*
     SU3F[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    15*I*SU3D[6, I4, k1]*SU3D[I3, k1, k2]*SU3F[I1, I2, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 6*I*SU3D[6, I3, k1]*SU3D[I4, k1, k2]*
     SU3F[I1, I2, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    6*SU3D[I4, k1, k2]*SU3F[6, I2, k2]*SU3F[I1, I3, k1]*
     UCouplingConstant[ChPTW3[2], 1] + 15*SU3D[I2, k1, k2]*SU3F[6, I4, k2]*
     SU3F[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    15*I*SU3D[6, I4, k1]*SU3D[I2, k1, k2]*SU3F[I1, I3, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 6*I*SU3D[6, I2, k1]*SU3D[I4, k1, k2]*
     SU3F[I1, I3, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*SU3D[I3, k1, k2]*SU3F[6, I2, k2]*SU3F[I1, I4, k1]*
     UCouplingConstant[ChPTW3[2], 1] - 3*SU3D[I2, k1, k2]*SU3F[6, I3, k2]*
     SU3F[I1, I4, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[6, I3, k1]*SU3D[I2, k1, k2]*SU3F[I1, I4, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3D[6, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[I1, I4, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    18*I*SU3D[6, I4, k1]*SU3D[I2, I3, k2]*SU3F[I1, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 18*I*SU3D[6, I3, k1]*SU3D[I2, I4, k2]*
     SU3F[I1, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    18*I*SU3D[6, I2, k1]*SU3D[I3, I4, k2]*SU3F[I1, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 18*SU3D[I3, I4, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    18*SU3D[I2, I4, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 18*SU3D[I2, I3, k1]*SU3F[6, I4, k2]*
     SU3F[I1, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    9*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I4, k1]*
     UCouplingConstant[ChPTW3[2], 1] + 9*I*SU3D[6, I1, k1]*SU3D[I3, k1, k2]*
     SU3F[I2, I4, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[6, I4, k1]*SU3D[I1, I3, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*I*SU3D[6, I3, k1]*SU3D[I1, I4, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*I*SU3D[6, I1, k1]*SU3D[I3, I4, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 3*SU3D[I3, I4, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    15*SU3D[I1, I4, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*SU3D[I1, I3, k1]*SU3F[6, I4, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    15*SU3D[6, I4, k1]*SU3F[I1, I3, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*I*SU3F[6, I4, k1]*SU3F[I1, I3, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[6, I3, k1]*SU3F[I1, I4, k2]*SU3F[I2, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3F[6, I3, k1]*SU3F[I1, I4, k2]*
     SU3F[I2, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    9*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[I3, I4, k1]*
     UCouplingConstant[ChPTW3[2], 1] + 9*I*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*
     SU3F[I3, I4, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    9*SU3D[6, I1, k1]*SU3F[I2, k1, k2]*SU3F[I3, I4, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 9*I*SU3F[6, I1, k1]*SU3F[I2, k1, k2]*
     SU3F[I3, I4, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[6, I4, k1]*SU3D[I1, I2, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*I*SU3D[6, I2, k1]*SU3D[I1, I4, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    3*I*SU3D[6, I1, k1]*SU3D[I2, I4, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 3*SU3D[I2, I4, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    15*SU3D[I1, I4, k1]*SU3F[6, I2, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*SU3D[I1, I2, k1]*SU3F[6, I4, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    15*SU3D[6, I4, k1]*SU3F[I1, I2, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 15*I*SU3F[6, I4, k1]*SU3F[I1, I2, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[6, I2, k1]*SU3F[I1, I4, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 3*I*SU3F[6, I2, k1]*SU3F[I1, I4, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    9*SU3D[6, I1, k1]*SU3F[I2, I4, k2]*SU3F[I3, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 9*I*SU3F[6, I1, k1]*SU3F[I2, I4, k2]*
     SU3F[I3, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    12*I*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 12*I*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    12*I*SU3D[6, I1, k1]*SU3D[I2, I3, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 12*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    12*SU3D[I1, I3, k1]*SU3F[6, I2, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] + 12*SU3D[I1, I2, k1]*SU3F[6, I3, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    6*SU3D[6, I3, k1]*SU3F[I1, I2, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 6*I*SU3F[6, I3, k1]*SU3F[I1, I2, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] - 
    6*SU3D[6, I2, k1]*SU3F[I1, I3, k2]*SU3F[I4, k1, k2]*
     UCouplingConstant[ChPTW3[2], 1] - 6*I*SU3F[6, I2, k1]*SU3F[I1, I3, k2]*
     SU3F[I4, k1, k2]*UCouplingConstant[ChPTW3[2], 1] + 
    12*SU3D[I2, I3, I4]*SU3Delta[6, I1]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[I1, I3, I4]*SU3Delta[6, I2]*UCouplingConstant[ChPTW3[2], 1] - 
    6*I*SU3F[I1, I3, I4]*SU3Delta[6, I2]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[I1, I2, I4]*SU3Delta[6, I3]*UCouplingConstant[ChPTW3[2], 1] - 
    6*I*SU3F[I1, I2, I4]*SU3Delta[6, I3]*UCouplingConstant[ChPTW3[2], 1] + 
    8*SU3D[I1, I2, I3]*SU3Delta[6, I4]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[6, I3, I4]*SU3Delta[I1, I2]*UCouplingConstant[ChPTW3[2], 1] - 
    6*I*SU3F[6, I3, I4]*SU3Delta[I1, I2]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[6, I2, I4]*SU3Delta[I1, I3]*UCouplingConstant[ChPTW3[2], 1] - 
    6*I*SU3F[6, I2, I4]*SU3Delta[I1, I3]*UCouplingConstant[ChPTW3[2], 1] + 
    20*SU3D[6, I2, I3]*SU3Delta[I1, I4]*UCouplingConstant[ChPTW3[2], 1] + 
    20*SU3D[6, I1, I4]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 1] - 
    4*I*SU3F[6, I1, I4]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[6, I1, I3]*SU3Delta[I2, I4]*UCouplingConstant[ChPTW3[2], 1] + 
    14*I*SU3F[6, I1, I3]*SU3Delta[I2, I4]*UCouplingConstant[ChPTW3[2], 1] - 
    10*SU3D[6, I1, I2]*SU3Delta[I3, I4]*UCouplingConstant[ChPTW3[2], 1] + 
    14*I*SU3F[6, I1, I2]*SU3Delta[I3, I4]*UCouplingConstant[ChPTW3[2], 1])/
   (18*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}}
