{{(2*I*(UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 20]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 20]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(2*I*(UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 20]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 20]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(-I/6*(6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     2*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     4*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     2*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     4*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 6*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] + 3*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     3*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + 6*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 6*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(I/6*(6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     2*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     4*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     2*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     4*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 6*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] + 3*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     3*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + 6*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 6*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(I/3*(2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[
       ChPTW3[4], 24]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     2*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     2*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       21]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       23]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       21]*UTrace1[FANonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(-I/6*(6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
     2*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     4*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     2*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     4*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 6*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] + 6*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     3*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 6*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + 3*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(I/6*(6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     2*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     4*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     2*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     4*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 6*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] + 6*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     3*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 6*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + 3*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     6*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(I/3*(2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[
       ChPTW3[4], 24]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     2*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     2*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       21]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] + Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       23]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 
       21]*UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[2], 1]*
      UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}}
