{{((-16*I)*(SU3D[I1, I2, I3]*CouplingConstant[ChPT3[4], 5, 
       RenormalizationState[0]] + SUNDelta[0, I3]*SUNDelta[I1, I2]*
      (3*CouplingConstant[ChPT3[4], 4, RenormalizationState[0]] + 
       CouplingConstant[ChPT3[4], 5, RenormalizationState[0]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {(((8*I)/9)*(36*Sqrt[3]*SU3D[8, I1, I2]*SUNDelta[0, I3]*
      CouplingConstant[ChPT3[4], 6, RenormalizationState[0]] - 
     72*SUNDelta[0, I3]*SUNDelta[I1, I2]*CouplingConstant[ChPT3[4], 6, 
       RenormalizationState[0]] + 72*SUNDelta[3, I2]*SUNDelta[I1, I3]*
      CouplingConstant[ChPT3[4], 7, RenormalizationState[0]] + 
     24*Sqrt[3]*SUNDelta[8, I2]*SUNDelta[I1, I3]*CouplingConstant[ChPT3[4], 
       7, RenormalizationState[0]] + 72*SUNDelta[3, I1]*SUNDelta[I2, I3]*
      CouplingConstant[ChPT3[4], 7, RenormalizationState[0]] + 
     24*Sqrt[3]*SUNDelta[8, I1]*SUNDelta[I2, I3]*CouplingConstant[ChPT3[4], 
       7, RenormalizationState[0]] + 18*SU3D[3, I3, k1]*SU3D[I1, I2, k1]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] + 
     6*Sqrt[3]*SU3D[8, I3, k1]*SU3D[I1, I2, k1]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 27*SU3D[3, I2, k1]*SU3D[I1, I3, k1]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] + 
     9*Sqrt[3]*SU3D[8, I2, k1]*SU3D[I1, I3, k1]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 27*SU3D[3, I1, k1]*SU3D[I2, I3, k1]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] + 
     9*Sqrt[3]*SU3D[8, I1, k1]*SU3D[I2, I3, k1]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 9*SU3F[3, I2, k1]*SU3F[I1, I3, k1]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] + 
     3*Sqrt[3]*SU3F[8, I2, k1]*SU3F[I1, I3, k1]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 9*SU3F[3, I1, k1]*SU3F[I2, I3, k1]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] + 
     3*Sqrt[3]*SU3F[8, I1, k1]*SU3F[I2, I3, k1]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 24*Sqrt[3]*SU3D[8, I1, I2]*
      SUNDelta[0, I3]*CouplingConstant[ChPT3[4], 8, RenormalizationState[
        0]] - 24*SUNDelta[0, I3]*SUNDelta[I1, I2]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 12*SUNDelta[3, I3]*SUNDelta[I1, I2]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] + 
     4*Sqrt[3]*SUNDelta[8, I3]*SUNDelta[I1, I2]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 18*SUNDelta[3, I2]*SUNDelta[I1, I3]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] + 
     6*Sqrt[3]*SUNDelta[8, I2]*SUNDelta[I1, I3]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 18*SUNDelta[3, I1]*SUNDelta[I2, I3]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] + 
     6*Sqrt[3]*SUNDelta[8, I1]*SUNDelta[I2, I3]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] - 12*SU3D[I1, I2, I3]*
      (3*CouplingConstant[ChPT3[4], 6, RenormalizationState[0]] + 
       2*CouplingConstant[ChPT3[4], 8, RenormalizationState[0]]) + 
     36*SU3D[3, I1, I2]*SUNDelta[0, I3]*
      (3*CouplingConstant[ChPT3[4], 6, RenormalizationState[0]] + 
       2*CouplingConstant[ChPT3[4], 8, RenormalizationState[0]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {(((-8*I)/9)*(-36*Sqrt[3]*SU3D[8, I1, I2]*SUNDelta[0, I3]*
      CouplingConstant[ChPT3[4], 6, RenormalizationState[0]] + 
     72*SUNDelta[0, I3]*SUNDelta[I1, I2]*CouplingConstant[ChPT3[4], 6, 
       RenormalizationState[0]] + 72*SUNDelta[3, I2]*SUNDelta[I1, I3]*
      CouplingConstant[ChPT3[4], 7, RenormalizationState[0]] - 
     24*Sqrt[3]*SUNDelta[8, I2]*SUNDelta[I1, I3]*CouplingConstant[ChPT3[4], 
       7, RenormalizationState[0]] + 72*SUNDelta[3, I1]*SUNDelta[I2, I3]*
      CouplingConstant[ChPT3[4], 7, RenormalizationState[0]] - 
     24*Sqrt[3]*SUNDelta[8, I1]*SUNDelta[I2, I3]*CouplingConstant[ChPT3[4], 
       7, RenormalizationState[0]] + 18*SU3D[3, I3, k1]*SU3D[I1, I2, k1]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] - 
     6*Sqrt[3]*SU3D[8, I3, k1]*SU3D[I1, I2, k1]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 27*SU3D[3, I2, k1]*SU3D[I1, I3, k1]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] - 
     9*Sqrt[3]*SU3D[8, I2, k1]*SU3D[I1, I3, k1]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 27*SU3D[3, I1, k1]*SU3D[I2, I3, k1]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] - 
     9*Sqrt[3]*SU3D[8, I1, k1]*SU3D[I2, I3, k1]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 9*SU3F[3, I2, k1]*SU3F[I1, I3, k1]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] - 
     3*Sqrt[3]*SU3F[8, I2, k1]*SU3F[I1, I3, k1]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 9*SU3F[3, I1, k1]*SU3F[I2, I3, k1]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] - 
     3*Sqrt[3]*SU3F[8, I1, k1]*SU3F[I2, I3, k1]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] - 24*Sqrt[3]*SU3D[8, I1, I2]*
      SUNDelta[0, I3]*CouplingConstant[ChPT3[4], 8, RenormalizationState[
        0]] + 24*SUNDelta[0, I3]*SUNDelta[I1, I2]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 12*SUNDelta[3, I3]*SUNDelta[I1, I2]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] - 
     4*Sqrt[3]*SUNDelta[8, I3]*SUNDelta[I1, I2]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 18*SUNDelta[3, I2]*SUNDelta[I1, I3]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] - 
     6*Sqrt[3]*SUNDelta[8, I2]*SUNDelta[I1, I3]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 18*SUNDelta[3, I1]*SUNDelta[I2, I3]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] - 
     6*Sqrt[3]*SUNDelta[8, I1]*SUNDelta[I2, I3]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 12*SU3D[I1, I2, I3]*
      (3*CouplingConstant[ChPT3[4], 6, RenormalizationState[0]] + 
       2*CouplingConstant[ChPT3[4], 8, RenormalizationState[0]]) + 
     36*SU3D[3, I1, I2]*SUNDelta[0, I3]*
      (3*CouplingConstant[ChPT3[4], 6, RenormalizationState[0]] + 
       2*CouplingConstant[ChPT3[4], 8, RenormalizationState[0]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {(((-16*I)/9)*(36*SUNDelta[0, I3]*SUNDelta[I1, I2]*
      CouplingConstant[ChPT3[4], 6, RenormalizationState[0]] + 
     24*Sqrt[3]*SUNDelta[8, I2]*SUNDelta[I1, I3]*CouplingConstant[ChPT3[4], 
       7, RenormalizationState[0]] + 24*Sqrt[3]*SUNDelta[8, I1]*
      SUNDelta[I2, I3]*CouplingConstant[ChPT3[4], 7, 
       RenormalizationState[0]] + 6*Sqrt[3]*SU3D[8, I3, k1]*SU3D[I1, I2, k1]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] + 
     9*Sqrt[3]*SU3D[8, I2, k1]*SU3D[I1, I3, k1]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 9*Sqrt[3]*SU3D[8, I1, k1]*
      SU3D[I2, I3, k1]*CouplingConstant[ChPT3[4], 8, 
       RenormalizationState[0]] + 3*Sqrt[3]*SU3F[8, I2, k1]*SU3F[I1, I3, k1]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] + 
     3*Sqrt[3]*SU3F[8, I1, k1]*SU3F[I2, I3, k1]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 12*SUNDelta[0, I3]*SUNDelta[I1, I2]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] + 
     4*Sqrt[3]*SUNDelta[8, I3]*SUNDelta[I1, I2]*CouplingConstant[ChPT3[4], 
       8, RenormalizationState[0]] + 6*Sqrt[3]*SUNDelta[8, I2]*
      SUNDelta[I1, I3]*CouplingConstant[ChPT3[4], 8, 
       RenormalizationState[0]] + 6*Sqrt[3]*SUNDelta[8, I1]*SUNDelta[I2, I3]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]] + 
     6*SU3D[I1, I2, I3]*(3*CouplingConstant[ChPT3[4], 6, 
         RenormalizationState[0]] + 2*CouplingConstant[ChPT3[4], 8, 
         RenormalizationState[0]]) + 12*Sqrt[3]*SU3D[8, I1, I2]*
      SUNDelta[0, I3]*(3*CouplingConstant[ChPT3[4], 6, RenormalizationState[
          0]] + 2*CouplingConstant[ChPT3[4], 8, RenormalizationState[0]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}}
