{{((4*I)/45*(SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] - 
     4*SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] - 
     4*SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] - 
     4*SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((4*I)/45*(SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] - 
     4*SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] - 
     4*SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] - 
     4*SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-4*I)/45*(4*SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] + 
     4*SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] - 
     SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] - 
     SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] - 
     SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] - 
     SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] - 
     SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] - 
     SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] - 
     SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] - 
     SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] - 
     SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] - 
     SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] - 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] - 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] + 
     4*SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {(-I/15*(SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((4*I)/45*(SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] - 
     4*SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] - 
     4*SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] - 
     4*SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((4*I)/45*(SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] - 
     4*SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] - 
     4*SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] - 
     4*SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((4*I)/45*(SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] - 
     4*SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] - 
     4*SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] - 
     4*SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((4*I)/45*(SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] - 
     4*SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] - 
     4*SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] - 
     4*SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((4*I)/45*(SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] - 
     4*SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] - 
     4*SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] - 
     4*SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((4*I)/45*(SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] - 
     4*SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] - 
     4*SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] - 
     4*SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-4*I)/45*(4*SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] - 
     SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] - 
     SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] - 
     SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] - 
     SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] + 
     4*SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] - 
     SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] - 
     SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] - 
     SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] - 
     SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] + 
     4*SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] - 
     SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] - 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] - 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] - 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((4*I)/45*(SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] - 
     4*SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] - 
     4*SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] - 
     4*SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((4*I)/45*(SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] - 
     4*SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] - 
     4*SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] - 
     4*SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((4*I)/45*(SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] - 
     4*SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] - 
     4*SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] - 
     4*SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((4*I)/45*(SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] - 
     4*SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] - 
     4*SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] + 
     SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] - 
     4*SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] + 
     SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] + 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-4*I)/45*(4*SUNDelta[I1, I6]*SUNDelta[I2, I5]*SUNDelta[I3, I4] - 
     SUNDelta[I1, I5]*SUNDelta[I2, I6]*SUNDelta[I3, I4] + 
     4*SUNDelta[I1, I6]*SUNDelta[I2, I4]*SUNDelta[I3, I5] - 
     SUNDelta[I1, I4]*SUNDelta[I2, I6]*SUNDelta[I3, I5] - 
     SUNDelta[I1, I5]*SUNDelta[I2, I4]*SUNDelta[I3, I6] - 
     SUNDelta[I1, I4]*SUNDelta[I2, I5]*SUNDelta[I3, I6] + 
     4*SUNDelta[I1, I6]*SUNDelta[I2, I3]*SUNDelta[I4, I5] - 
     SUNDelta[I1, I3]*SUNDelta[I2, I6]*SUNDelta[I4, I5] - 
     SUNDelta[I1, I2]*SUNDelta[I3, I6]*SUNDelta[I4, I5] - 
     SUNDelta[I1, I5]*SUNDelta[I2, I3]*SUNDelta[I4, I6] - 
     SUNDelta[I1, I3]*SUNDelta[I2, I5]*SUNDelta[I4, I6] - 
     SUNDelta[I1, I2]*SUNDelta[I3, I5]*SUNDelta[I4, I6] - 
     SUNDelta[I1, I4]*SUNDelta[I2, I3]*SUNDelta[I5, I6] - 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*SUNDelta[I5, I6] - 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*SUNDelta[I5, I6]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}}
