{{(-4*I*SU3D[6, I1, I2]*CouplingConstant[ChPTW3[2], 1])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2}, 
 {(2*(-3*I*SU3D[6, I1, I2]*CouplingConstant[ChPTW3[2], 2] - 
     9*SU3D[7, I1, I2]*CouplingConstant[ChPTW3[2], 2] - 
     2*I*Sqrt[3]*SU3Delta[6, I2]*SU3Delta[8, I1]*CouplingConstant[ChPTW3[2], 
       2] - 2*I*Sqrt[3]*SU3Delta[6, I1]*SU3Delta[8, I2]*
      CouplingConstant[ChPTW3[2], 2] + 3*I*Sqrt[3]*SU3F[6, I2, k2]*
      SU3F[I1, k1, k2]*SU3Delta[8, k1]*CouplingConstant[ChPTW3[2], 2] + 
     3*I*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k1, k2]*SU3Delta[8, k1]*
      CouplingConstant[ChPTW3[2], 2] - 3*I*Sqrt[3]*SU3D[6, I2, k1]*
      SU3D[I1, k1, k2]*SU3Delta[8, k2]*CouplingConstant[ChPTW3[2], 2] - 
     3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3Delta[8, k2]*
      CouplingConstant[ChPTW3[2], 2] + 3*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3F[6, I1, k1]*SU3Delta[8, k2]*CouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k1]*SU3Delta[8, k2]*
      CouplingConstant[ChPTW3[2], 2] - 3*Sqrt[3]*SU3D[6, I2, k1]*
      SU3F[I1, k1, k2]*SU3Delta[8, k2]*CouplingConstant[ChPTW3[2], 2] - 
     3*Sqrt[3]*SU3D[6, I1, k1]*SU3F[I2, k1, k2]*SU3Delta[8, k2]*
      CouplingConstant[ChPTW3[2], 2]))/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)}, 
 {(-24*I*SU3D[6, I1, I2]*CouplingConstant[ChPTW3[2], 2] + 
    6*I*SU3Delta[3, I2]*SU3Delta[6, I1]*CouplingConstant[ChPTW3[2], 2] + 
    6*I*SU3Delta[3, I1]*SU3Delta[6, I2]*CouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[I2, k1, k2]*SU3F[3, I1, k2]*SU3Delta[6, k1]*
     CouplingConstant[ChPTW3[2], 2] + 9*SU3D[I1, k1, k2]*SU3F[3, I2, k2]*
     SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2] - 
    9*I*SU3F[3, I2, k2]*SU3F[I1, k1, k2]*SU3Delta[6, k1]*
     CouplingConstant[ChPTW3[2], 2] - 9*I*SU3F[3, I1, k2]*SU3F[I2, k1, k2]*
     SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*SU3Delta[6, k2]*
     CouplingConstant[ChPTW3[2], 2] + 9*I*SU3D[3, I1, k1]*SU3D[I2, k1, k2]*
     SU3Delta[6, k2]*CouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[3, I2, k1]*SU3F[I1, k1, k2]*SU3Delta[6, k2]*
     CouplingConstant[ChPTW3[2], 2] - 9*SU3D[3, I1, k1]*SU3F[I2, k1, k2]*
     SU3Delta[6, k2]*CouplingConstant[ChPTW3[2], 2] + 
    2*I*Sqrt[3]*SU3Delta[6, I2]*SU3Delta[8, I1]*CouplingConstant[ChPTW3[2], 
      2] + 2*I*Sqrt[3]*SU3Delta[6, I1]*SU3Delta[8, I2]*
     CouplingConstant[ChPTW3[2], 2] - 3*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2]*SU3Delta[8, k1]*CouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3Delta[8, k1]*
     CouplingConstant[ChPTW3[2], 2] - 3*I*Sqrt[3]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2]*SU3Delta[8, k1]*CouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k1, k2]*SU3Delta[8, k1]*
     CouplingConstant[ChPTW3[2], 2] + 3*I*Sqrt[3]*SU3D[6, I2, k1]*
     SU3D[I1, k1, k2]*SU3Delta[8, k2]*CouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3Delta[8, k2]*
     CouplingConstant[ChPTW3[2], 2] + 3*Sqrt[3]*SU3D[6, I2, k1]*
     SU3F[I1, k1, k2]*SU3Delta[8, k2]*CouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I1, k1]*SU3F[I2, k1, k2]*SU3Delta[8, k2]*
     CouplingConstant[ChPTW3[2], 2])/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)}, 
 {(-6*I*SU3D[6, I1, I2]*CouplingConstant[ChPTW3[2], 2] + 
    18*SU3D[7, I1, I2]*CouplingConstant[ChPTW3[2], 2] - 
    6*I*SU3Delta[3, I2]*SU3Delta[6, I1]*CouplingConstant[ChPTW3[2], 2] - 
    6*I*SU3Delta[3, I1]*SU3Delta[6, I2]*CouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[I2, k1, k2]*SU3F[3, I1, k2]*SU3Delta[6, k1]*
     CouplingConstant[ChPTW3[2], 2] - 9*SU3D[I1, k1, k2]*SU3F[3, I2, k2]*
     SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3F[3, I2, k2]*SU3F[I1, k1, k2]*SU3Delta[6, k1]*
     CouplingConstant[ChPTW3[2], 2] + 9*I*SU3F[3, I1, k2]*SU3F[I2, k1, k2]*
     SU3Delta[6, k1]*CouplingConstant[ChPTW3[2], 2] - 
    9*I*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*SU3Delta[6, k2]*
     CouplingConstant[ChPTW3[2], 2] - 9*I*SU3D[3, I1, k1]*SU3D[I2, k1, k2]*
     SU3Delta[6, k2]*CouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[3, I2, k1]*SU3F[I1, k1, k2]*SU3Delta[6, k2]*
     CouplingConstant[ChPTW3[2], 2] + 9*SU3D[3, I1, k1]*SU3F[I2, k1, k2]*
     SU3Delta[6, k2]*CouplingConstant[ChPTW3[2], 2] + 
    2*I*Sqrt[3]*SU3Delta[6, I2]*SU3Delta[8, I1]*CouplingConstant[ChPTW3[2], 
      2] + 2*I*Sqrt[3]*SU3Delta[6, I1]*SU3Delta[8, I2]*
     CouplingConstant[ChPTW3[2], 2] - 3*I*Sqrt[3]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2]*SU3Delta[8, k1]*CouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k1, k2]*SU3Delta[8, k1]*
     CouplingConstant[ChPTW3[2], 2] + 3*I*Sqrt[3]*SU3D[6, I2, k1]*
     SU3D[I1, k1, k2]*SU3Delta[8, k2]*CouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3Delta[8, k2]*
     CouplingConstant[ChPTW3[2], 2] - 3*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k1]*SU3Delta[8, k2]*CouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k1]*SU3Delta[8, k2]*
     CouplingConstant[ChPTW3[2], 2] + 3*Sqrt[3]*SU3D[6, I2, k1]*
     SU3F[I1, k1, k2]*SU3Delta[8, k2]*CouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I1, k1]*SU3F[I2, k1, k2]*SU3Delta[8, k2]*
     CouplingConstant[ChPTW3[2], 2])/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^2)}}
