{{(4*QuarkCondensate[RenormalizationState[0]]*CouplingConstant[ChPTW3[2], 1]*
    ((2*CouplingConstant[ChPTW3[4], 10] + 3*CouplingConstant[ChPTW3[4], 
         11])*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     2*SUNDelta[0, I2]*((CouplingConstant[ChPTW3[4], 10] + 
         3*CouplingConstant[ChPTW3[4], 11])*UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] - 
       (CouplingConstant[ChPTW3[4], 10] + 3*CouplingConstant[ChPTW3[4], 
           11])*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]] + Sqrt[3]*
        (2*CouplingConstant[ChPTW3[4], 10] + 3*CouplingConstant[ChPTW3[4], 
           11])*(UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
         UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
           UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]])) - 
     2*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]] - 3*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       10]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] - 2*Sqrt[3]*CouplingConstant[ChPTW3[4], 
       10]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]]))/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(4*QuarkCondensate[RenormalizationState[0]]*CouplingConstant[ChPTW3[2], 1]*
    ((2*CouplingConstant[ChPTW3[4], 10] + 3*CouplingConstant[ChPTW3[4], 
         11])*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     SUNDelta[0, I2]*(2*(CouplingConstant[ChPTW3[4], 10] + 
         3*CouplingConstant[ChPTW3[4], 11])*UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] - 
       2*(CouplingConstant[ChPTW3[4], 10] + 3*CouplingConstant[ChPTW3[4], 
           11])*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]] + (2*CouplingConstant[ChPTW3[4], 10] + 
         3*CouplingConstant[ChPTW3[4], 11])*
        (3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] - 
         Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
         3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
            UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] + 
         Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
            UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]])) - 
     2*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]] - 3*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] + 
     3*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + 3*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] - 3*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] - 3*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]]))/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(4*QuarkCondensate[RenormalizationState[0]]*CouplingConstant[ChPTW3[2], 1]*
    ((2*CouplingConstant[ChPTW3[4], 10] + 3*CouplingConstant[ChPTW3[4], 
         11])*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     SUNDelta[0, I2]*(2*(CouplingConstant[ChPTW3[4], 10] + 
         3*CouplingConstant[ChPTW3[4], 11])*UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] - 
       2*(CouplingConstant[ChPTW3[4], 10] + 3*CouplingConstant[ChPTW3[4], 
           11])*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[6]]]] - (2*CouplingConstant[ChPTW3[4], 10] + 
         3*CouplingConstant[ChPTW3[4], 11])*
        (3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
         Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
         3*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
            UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]] - 
         Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
            UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]])) - 
     2*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]] - 3*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]]]] - 
     3*CouplingConstant[ChPTW3[4], 10]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] - 3*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + 3*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + 3*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 10]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]]))/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}}
