{{(3*SU3D[6, I3, k1]*SU3D[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[6, I2, k1]*SU3D[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    6*SU3D[6, I1, k1]*SU3D[I2, I3, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    6*I*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    3*I*SU3D[6, I3, k1]*SU3F[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3F[6, I3, k1]*SU3F[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    3*I*SU3D[6, I2, k1]*SU3F[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3F[6, I2, k1]*SU3F[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    2*SU3Delta[6, I3]*SU3Delta[I1, I2]*UCouplingConstant[ChPTW3[2], 1] + 
    2*SU3Delta[6, I2]*SU3Delta[I1, I3]*UCouplingConstant[ChPTW3[2], 1] - 
    4*SU3Delta[6, I1]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 1])/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(3*SU3D[6, I3, k1]*SU3D[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    6*SU3D[6, I2, k1]*SU3D[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[6, I1, k1]*SU3D[I2, I3, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    6*I*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[6, I3, k1]*SU3F[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    3*SU3F[6, I3, k1]*SU3F[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    3*I*SU3D[6, I1, k1]*SU3F[I2, I3, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3F[6, I1, k1]*SU3F[I2, I3, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    2*SU3Delta[6, I3]*SU3Delta[I1, I2]*UCouplingConstant[ChPTW3[2], 1] - 
    4*SU3Delta[6, I2]*SU3Delta[I1, I3]*UCouplingConstant[ChPTW3[2], 1] + 
    2*SU3Delta[6, I1]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 1])/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(-6*SU3D[6, I3, k1]*SU3D[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[6, I2, k1]*SU3D[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*SU3D[6, I1, k1]*SU3D[I2, I3, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    6*I*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[6, I2, k1]*SU3F[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    3*SU3F[6, I2, k1]*SU3F[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 1] + 
    3*I*SU3D[6, I1, k1]*SU3F[I2, I3, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    3*SU3F[6, I1, k1]*SU3F[I2, I3, k1]*UCouplingConstant[ChPTW3[2], 1] - 
    4*SU3Delta[6, I3]*SU3Delta[I1, I2]*UCouplingConstant[ChPTW3[2], 1] + 
    2*SU3Delta[6, I2]*SU3Delta[I1, I3]*UCouplingConstant[ChPTW3[2], 1] + 
    2*SU3Delta[6, I1]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 1])/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(12*SU3D[6, I3, k1]*SU3D[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    12*SU3D[6, I2, k1]*SU3D[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    12*SU3D[6, I1, k1]*SU3D[I2, I3, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    12*I*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    12*I*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    12*I*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    12*SU3D[6, I2, I3]*SU3Delta[3, I1]*UCouplingConstant[ChPTW3[2], 2] + 
    12*SU3D[6, I1, I3]*SU3Delta[3, I2]*UCouplingConstant[ChPTW3[2], 2] + 
    12*SU3D[6, I1, I2]*SU3Delta[3, I3]*UCouplingConstant[ChPTW3[2], 2] + 
    12*SU3D[3, I2, I3]*SU3Delta[6, I1]*UCouplingConstant[ChPTW3[2], 2] + 
    4*Sqrt[3]*SU3D[8, I2, I3]*SU3Delta[6, I1]*UCouplingConstant[ChPTW3[2], 
      2] + 12*SU3D[3, I1, I3]*SU3Delta[6, I2]*UCouplingConstant[ChPTW3[2], 
      2] + 4*Sqrt[3]*SU3D[8, I1, I3]*SU3Delta[6, I2]*
     UCouplingConstant[ChPTW3[2], 2] + 12*SU3D[3, I1, I2]*SU3Delta[6, I3]*
     UCouplingConstant[ChPTW3[2], 2] + 4*Sqrt[3]*SU3D[8, I1, I2]*
     SU3Delta[6, I3]*UCouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[I3, k1, k2]*SU3F[3, I2, k3]*SU3F[I1, k2, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] - 9*SU3D[I2, k1, k2]*SU3F[3, I3, k3]*
     SU3F[I1, k2, k3]*SU3Delta[6, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    9*I*SU3F[3, I3, k2]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] - 9*SU3D[I3, k1, k2]*SU3F[3, I1, k3]*
     SU3F[I2, k2, k3]*SU3Delta[6, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[I1, k1, k2]*SU3F[3, I3, k3]*SU3F[I2, k2, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] - 9*I*SU3F[3, I3, k2]*SU3F[I1, k1, k3]*
     SU3F[I2, k2, k3]*SU3Delta[6, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    9*I*SU3F[3, I2, k2]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] - 9*I*SU3F[3, I1, k2]*SU3F[I2, k2, k3]*
     SU3F[I3, k1, k3]*SU3Delta[6, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[I2, k1, k2]*SU3F[3, I1, k3]*SU3F[I3, k2, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] - 9*SU3D[I1, k1, k2]*SU3F[3, I2, k3]*
     SU3F[I3, k2, k3]*SU3Delta[6, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    9*I*SU3F[3, I2, k2]*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] - 9*I*SU3F[3, I1, k2]*SU3F[I2, k1, k3]*
     SU3F[I3, k2, k3]*SU3Delta[6, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[3, I3, k1]*SU3D[I1, k2, k3]*SU3D[I2, k1, k3]*SU3Delta[6, k2]*
     UCouplingConstant[ChPTW3[2], 2] + 9*SU3D[3, I2, k1]*SU3D[I1, k2, k3]*
     SU3D[I3, k1, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[3, I1, k1]*SU3D[I2, k2, k3]*SU3D[I3, k1, k3]*SU3Delta[6, k2]*
     UCouplingConstant[ChPTW3[2], 2] - 9*I*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*
     SU3F[3, I1, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    9*I*SU3D[I1, k1, k2]*SU3D[I3, k1, k3]*SU3F[3, I2, k3]*SU3Delta[6, k2]*
     UCouplingConstant[ChPTW3[2], 2] - 9*I*SU3D[I1, k1, k2]*SU3D[I2, k1, k3]*
     SU3F[3, I3, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[3, I3, k1]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SU3Delta[6, k2]*
     UCouplingConstant[ChPTW3[2], 2] + 9*SU3D[3, I3, k1]*SU3F[I1, k1, k3]*
     SU3F[I2, k2, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[3, I2, k1]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SU3Delta[6, k2]*
     UCouplingConstant[ChPTW3[2], 2] + 9*SU3D[3, I1, k1]*SU3F[I2, k2, k3]*
     SU3F[I3, k1, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[3, I2, k1]*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*SU3Delta[6, k2]*
     UCouplingConstant[ChPTW3[2], 2] + 9*SU3D[3, I1, k1]*SU3F[I2, k1, k3]*
     SU3F[I3, k2, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[3, I3, k1]*SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] + 9*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*
     SU3D[I3, k2, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[3, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, k2, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] - 9*I*SU3D[I2, k1, k2]*SU3D[I3, k2, k3]*
     SU3F[3, I1, k1]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    9*I*SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*SU3F[3, I2, k1]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] - 9*I*SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*
     SU3F[3, I3, k1]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3D[3, I3, k1]*SU3D[I2, k2, k3]*SU3F[I1, k1, k2]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] + 9*I*SU3D[3, I2, k1]*SU3D[I3, k2, k3]*
     SU3F[I1, k1, k2]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[I3, k1, k2]*SU3F[3, I2, k2]*SU3F[I1, k1, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] + 9*SU3D[I2, k1, k2]*SU3F[3, I3, k2]*
     SU3F[I1, k1, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*SU3F[I1, k2, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] + 9*I*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[I1, k2, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3D[3, I3, k1]*SU3D[I1, k2, k3]*SU3F[I2, k1, k2]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] + 9*I*SU3D[3, I1, k1]*SU3D[I3, k2, k3]*
     SU3F[I2, k1, k2]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[I1, k1, k2]*SU3F[3, I3, k2]*SU3F[I2, k1, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] + 9*I*SU3D[3, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[I2, k2, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3D[3, I1, k1]*SU3D[I3, k1, k2]*SU3F[I2, k2, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] + 9*SU3D[I3, k1, k2]*SU3F[3, I1, k1]*
     SU3F[I2, k2, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3D[3, I2, k1]*SU3D[I1, k2, k3]*SU3F[I3, k1, k2]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] + 9*I*SU3D[3, I1, k1]*SU3D[I2, k2, k3]*
     SU3F[I3, k1, k2]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*SU3F[I3, k2, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] + 9*I*SU3D[3, I1, k1]*SU3D[I2, k1, k2]*
     SU3F[I3, k2, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[I2, k1, k2]*SU3F[3, I1, k1]*SU3F[I3, k2, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] + 9*SU3D[I1, k1, k2]*SU3F[3, I2, k1]*
     SU3F[I3, k2, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    4*Sqrt[3]*SU3D[6, I2, I3]*SU3Delta[8, I1]*UCouplingConstant[ChPTW3[2], 
      2] + 4*Sqrt[3]*SU3D[6, I1, I3]*SU3Delta[8, I2]*
     UCouplingConstant[ChPTW3[2], 2] + 4*Sqrt[3]*SU3D[6, I1, I2]*
     SU3Delta[8, I3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k2, k3]*SU3F[6, I1, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*SU3F[6, I2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*SU3F[6, I3, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k3]*SU3F[I1, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k3]*SU3F[I1, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3F[6, I3, k2]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k3]*SU3F[I2, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k3]*SU3F[I2, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3F[6, I3, k2]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3F[6, I2, k2]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k3]*SU3F[I3, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k3]*SU3F[I3, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3F[6, I2, k2]*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k2, k3]*SU3D[I2, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k2, k3]*SU3D[I3, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k2, k3]*SU3D[I3, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I2, k2, k3]*SU3F[I1, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I3, k2, k3]*SU3F[I1, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k2, k3]*SU3F[I2, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I3, k2, k3]*SU3F[I2, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I3, k1]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I3, k1]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k2, k3]*SU3F[I3, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k2, k3]*SU3F[I3, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I2, k1]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I1, k1]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I2, k1]*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I1, k1]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k2]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I2, k2]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I2, k1, k3]*SU3F[6, I3, k2]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I2, k1, k2]*SU3F[I1, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I3, k1, k2]*SU3F[I1, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k1]*SU3F[I1, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k1]*SU3F[I1, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, k1, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*SU3F[I2, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I3, k1, k2]*SU3F[I2, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k1]*SU3F[I2, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[I3, k1, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[I3, k1, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3F[I3, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3F[I3, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    8*SU3Delta[6, I3]*SU3Delta[I1, I2]*UCouplingConstant[ChPTW3[2], 2] + 
    8*SU3Delta[6, I2]*SU3Delta[I1, I3]*UCouplingConstant[ChPTW3[2], 2] + 
    8*SU3Delta[6, I1]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 2])/
   (27*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(-2*(3*SU3D[6, I3, k1]*SU3D[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     9*I*SU3D[7, I3, k1]*SU3D[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*SU3D[6, I2, k1]*SU3D[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     9*I*SU3D[7, I2, k1]*SU3D[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*SU3D[6, I1, k1]*SU3D[I2, I3, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     9*I*SU3D[7, I1, k1]*SU3D[I2, I3, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*UCouplingConstant[ChPTW3[2], 2] - 
     9*SU3D[I2, I3, k1]*SU3F[7, I1, k1]*UCouplingConstant[ChPTW3[2], 2] - 
     9*SU3D[I1, I3, k1]*SU3F[7, I2, k1]*UCouplingConstant[ChPTW3[2], 2] - 
     9*SU3D[I1, I2, k1]*SU3F[7, I3, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     4*Sqrt[3]*SU3D[8, I2, I3]*SU3Delta[6, I1]*UCouplingConstant[ChPTW3[2], 
       2] + 4*Sqrt[3]*SU3D[8, I1, I3]*SU3Delta[6, I2]*
      UCouplingConstant[ChPTW3[2], 2] + 4*Sqrt[3]*SU3D[8, I1, I2]*
      SU3Delta[6, I3]*UCouplingConstant[ChPTW3[2], 2] + 
     4*Sqrt[3]*SU3D[6, I2, I3]*SU3Delta[8, I1]*UCouplingConstant[ChPTW3[2], 
       2] + 4*Sqrt[3]*SU3D[6, I1, I3]*SU3Delta[8, I2]*
      UCouplingConstant[ChPTW3[2], 2] + 4*Sqrt[3]*SU3D[6, I1, I2]*
      SU3Delta[8, I3]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k2, k3]*SU3F[6, I1, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*SU3F[6, I2, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*SU3F[6, I3, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
     3*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k3]*SU3F[I1, k2, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
     3*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k3]*SU3F[I1, k2, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*Sqrt[3]*SU3F[6, I3, k2]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
     3*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k3]*SU3F[I2, k2, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
     3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k3]*SU3F[I2, k2, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*Sqrt[3]*SU3F[6, I3, k2]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*Sqrt[3]*SU3F[6, I2, k2]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
     3*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k3]*SU3F[I3, k2, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
     3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k3]*SU3F[I3, k2, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*Sqrt[3]*SU3F[6, I2, k2]*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*
      SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k2, k3]*SU3D[I2, k1, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k2, k3]*SU3D[I3, k1, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k2, k3]*SU3D[I3, k1, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
     3*I*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I2, k2, k3]*SU3F[I1, k1, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
     3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I3, k2, k3]*SU3F[I1, k1, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
     3*I*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k2, k3]*SU3F[I2, k1, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
     3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I3, k2, k3]*SU3F[I2, k1, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[6, I3, k1]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[6, I3, k1]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
     3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k2, k3]*SU3F[I3, k1, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
     3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k2, k3]*SU3F[I3, k1, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[6, I2, k1]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[6, I1, k1]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[6, I2, k1]*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[6, I1, k1]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*
      SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, k2, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k2]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I2, k2]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
     3*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I2, k1, k3]*SU3F[6, I3, k2]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
     3*I*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I2, k1, k2]*SU3F[I1, k2, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
     3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I3, k1, k2]*SU3F[I1, k2, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k1]*SU3F[I1, k2, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k1]*SU3F[I1, k2, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, k1, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
     3*I*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*SU3F[I2, k2, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
     3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I3, k1, k2]*SU3F[I2, k2, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k1]*SU3F[I2, k2, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[I3, k1, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
     3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[I3, k1, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
     3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3F[I3, k2, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
     3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3F[I3, k2, k3]*
      SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
     2*SU3Delta[6, I3]*SU3Delta[I1, I2]*UCouplingConstant[ChPTW3[2], 2] + 
     6*I*SU3Delta[7, I3]*SU3Delta[I1, I2]*UCouplingConstant[ChPTW3[2], 2] + 
     2*SU3Delta[6, I2]*SU3Delta[I1, I3]*UCouplingConstant[ChPTW3[2], 2] + 
     6*I*SU3Delta[7, I2]*SU3Delta[I1, I3]*UCouplingConstant[ChPTW3[2], 2] + 
     2*SU3Delta[6, I1]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 2] + 
     6*I*SU3Delta[7, I1]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 2]))/
   (27*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(-6*SU3D[6, I3, k1]*SU3D[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    18*I*SU3D[7, I3, k1]*SU3D[I1, I2, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    6*SU3D[6, I2, k1]*SU3D[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    18*I*SU3D[7, I2, k1]*SU3D[I1, I3, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    6*SU3D[6, I1, k1]*SU3D[I2, I3, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    18*I*SU3D[7, I1, k1]*SU3D[I2, I3, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    6*I*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    6*I*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    6*I*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    18*SU3D[I2, I3, k1]*SU3F[7, I1, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    18*SU3D[I1, I3, k1]*SU3F[7, I2, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    18*SU3D[I1, I2, k1]*SU3F[7, I3, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    12*SU3D[6, I2, I3]*SU3Delta[3, I1]*UCouplingConstant[ChPTW3[2], 2] - 
    12*SU3D[6, I1, I3]*SU3Delta[3, I2]*UCouplingConstant[ChPTW3[2], 2] - 
    12*SU3D[6, I1, I2]*SU3Delta[3, I3]*UCouplingConstant[ChPTW3[2], 2] - 
    12*SU3D[3, I2, I3]*SU3Delta[6, I1]*UCouplingConstant[ChPTW3[2], 2] + 
    4*Sqrt[3]*SU3D[8, I2, I3]*SU3Delta[6, I1]*UCouplingConstant[ChPTW3[2], 
      2] - 12*SU3D[3, I1, I3]*SU3Delta[6, I2]*UCouplingConstant[ChPTW3[2], 
      2] + 4*Sqrt[3]*SU3D[8, I1, I3]*SU3Delta[6, I2]*
     UCouplingConstant[ChPTW3[2], 2] - 12*SU3D[3, I1, I2]*SU3Delta[6, I3]*
     UCouplingConstant[ChPTW3[2], 2] + 4*Sqrt[3]*SU3D[8, I1, I2]*
     SU3Delta[6, I3]*UCouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3D[I2, k1, k2]*SU3D[I3, k2, k3]*SU3F[3, I1, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] + 9*I*SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*
     SU3F[3, I2, k3]*SU3Delta[6, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*SU3F[3, I3, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] + 9*SU3D[I3, k1, k2]*SU3F[3, I2, k3]*
     SU3F[I1, k2, k3]*SU3Delta[6, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[I2, k1, k2]*SU3F[3, I3, k3]*SU3F[I1, k2, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] + 9*I*SU3F[3, I3, k2]*SU3F[I1, k2, k3]*
     SU3F[I2, k1, k3]*SU3Delta[6, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[I3, k1, k2]*SU3F[3, I1, k3]*SU3F[I2, k2, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] + 9*SU3D[I1, k1, k2]*SU3F[3, I3, k3]*
     SU3F[I2, k2, k3]*SU3Delta[6, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3F[3, I3, k2]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] + 9*I*SU3F[3, I2, k2]*SU3F[I1, k2, k3]*
     SU3F[I3, k1, k3]*SU3Delta[6, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3F[3, I1, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] + 9*SU3D[I2, k1, k2]*SU3F[3, I1, k3]*
     SU3F[I3, k2, k3]*SU3Delta[6, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    9*SU3D[I1, k1, k2]*SU3F[3, I2, k3]*SU3F[I3, k2, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] + 9*I*SU3F[3, I2, k2]*SU3F[I1, k1, k3]*
     SU3F[I3, k2, k3]*SU3Delta[6, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3F[3, I1, k2]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*SU3Delta[6, k1]*
     UCouplingConstant[ChPTW3[2], 2] - 9*SU3D[3, I3, k1]*SU3D[I1, k2, k3]*
     SU3D[I2, k1, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[3, I2, k1]*SU3D[I1, k2, k3]*SU3D[I3, k1, k3]*SU3Delta[6, k2]*
     UCouplingConstant[ChPTW3[2], 2] - 9*SU3D[3, I1, k1]*SU3D[I2, k2, k3]*
     SU3D[I3, k1, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    9*I*SU3D[3, I3, k1]*SU3D[I2, k2, k3]*SU3F[I1, k1, k3]*SU3Delta[6, k2]*
     UCouplingConstant[ChPTW3[2], 2] - 9*I*SU3D[3, I2, k1]*SU3D[I3, k2, k3]*
     SU3F[I1, k1, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    9*I*SU3D[3, I3, k1]*SU3D[I1, k2, k3]*SU3F[I2, k1, k3]*SU3Delta[6, k2]*
     UCouplingConstant[ChPTW3[2], 2] - 9*I*SU3D[3, I1, k1]*SU3D[I3, k2, k3]*
     SU3F[I2, k1, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[3, I3, k1]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SU3Delta[6, k2]*
     UCouplingConstant[ChPTW3[2], 2] - 9*SU3D[3, I3, k1]*SU3F[I1, k1, k3]*
     SU3F[I2, k2, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    9*I*SU3D[3, I2, k1]*SU3D[I1, k2, k3]*SU3F[I3, k1, k3]*SU3Delta[6, k2]*
     UCouplingConstant[ChPTW3[2], 2] - 9*I*SU3D[3, I1, k1]*SU3D[I2, k2, k3]*
     SU3F[I3, k1, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[3, I2, k1]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SU3Delta[6, k2]*
     UCouplingConstant[ChPTW3[2], 2] - 9*SU3D[3, I1, k1]*SU3F[I2, k2, k3]*
     SU3F[I3, k1, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[3, I2, k1]*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*SU3Delta[6, k2]*
     UCouplingConstant[ChPTW3[2], 2] - 9*SU3D[3, I1, k1]*SU3F[I2, k1, k3]*
     SU3F[I3, k2, k3]*SU3Delta[6, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[3, I3, k1]*SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] - 9*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*
     SU3D[I3, k2, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[3, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, k2, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] + 9*I*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*
     SU3F[3, I1, k2]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    9*I*SU3D[I1, k1, k2]*SU3D[I3, k1, k3]*SU3F[3, I2, k2]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] + 9*I*SU3D[I1, k1, k2]*SU3D[I2, k1, k3]*
     SU3F[3, I3, k2]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[I3, k1, k2]*SU3F[3, I2, k2]*SU3F[I1, k1, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] - 9*SU3D[I2, k1, k2]*SU3F[3, I3, k2]*
     SU3F[I1, k1, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    9*I*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*SU3F[I1, k2, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] - 9*I*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[I1, k2, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[I1, k1, k2]*SU3F[3, I3, k2]*SU3F[I2, k1, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] - 9*I*SU3D[3, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[I2, k2, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    9*I*SU3D[3, I1, k1]*SU3D[I3, k1, k2]*SU3F[I2, k2, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] - 9*SU3D[I3, k1, k2]*SU3F[3, I1, k1]*
     SU3F[I2, k2, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    9*I*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*SU3F[I3, k2, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] - 9*I*SU3D[3, I1, k1]*SU3D[I2, k1, k2]*
     SU3F[I3, k2, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    9*SU3D[I2, k1, k2]*SU3F[3, I1, k1]*SU3F[I3, k2, k3]*SU3Delta[6, k3]*
     UCouplingConstant[ChPTW3[2], 2] - 9*SU3D[I1, k1, k2]*SU3F[3, I2, k1]*
     SU3F[I3, k2, k3]*SU3Delta[6, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    4*Sqrt[3]*SU3D[6, I2, I3]*SU3Delta[8, I1]*UCouplingConstant[ChPTW3[2], 
      2] + 4*Sqrt[3]*SU3D[6, I1, I3]*SU3Delta[8, I2]*
     UCouplingConstant[ChPTW3[2], 2] + 4*Sqrt[3]*SU3D[6, I1, I2]*
     SU3Delta[8, I3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k2, k3]*SU3F[6, I1, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*SU3F[6, I2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*SU3F[6, I3, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k3]*SU3F[I1, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k3]*SU3F[I1, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3F[6, I3, k2]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k3]*SU3F[I2, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k3]*SU3F[I2, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3F[6, I3, k2]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3F[6, I2, k2]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k3]*SU3F[I3, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k3]*SU3F[I3, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3F[6, I2, k2]*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*
     SU3Delta[8, k1]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I2, k2, k3]*SU3F[I1, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I3, k2, k3]*SU3F[I1, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k2, k3]*SU3F[I2, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I3, k2, k3]*SU3F[I2, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I3, k1]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I3, k1]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k2, k3]*SU3F[I3, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k2, k3]*SU3F[I3, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I2, k1]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I1, k1]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I2, k1]*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I1, k1]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*
     SU3Delta[8, k2]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k2, k3]*SU3D[I2, k1, k2]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k2, k3]*SU3D[I3, k1, k2]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k2, k3]*SU3D[I3, k1, k2]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k2]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I2, k2]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I2, k1, k3]*SU3F[6, I3, k2]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I2, k1, k2]*SU3F[I1, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I3, k1, k2]*SU3F[I1, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k1]*SU3F[I1, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k1]*SU3F[I1, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, k1, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*SU3F[I2, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I3, k1, k2]*SU3F[I2, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k1]*SU3F[I2, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[I3, k1, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] + 
    3*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[I3, k1, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3F[I3, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    3*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3F[I3, k2, k3]*
     SU3Delta[8, k3]*UCouplingConstant[ChPTW3[2], 2] - 
    4*SU3Delta[6, I3]*SU3Delta[I1, I2]*UCouplingConstant[ChPTW3[2], 2] + 
    12*I*SU3Delta[7, I3]*SU3Delta[I1, I2]*UCouplingConstant[ChPTW3[2], 2] - 
    4*SU3Delta[6, I2]*SU3Delta[I1, I3]*UCouplingConstant[ChPTW3[2], 2] + 
    12*I*SU3Delta[7, I2]*SU3Delta[I1, I3]*UCouplingConstant[ChPTW3[2], 2] - 
    4*SU3Delta[6, I1]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 2] + 
    12*I*SU3Delta[7, I1]*SU3Delta[I2, I3]*UCouplingConstant[ChPTW3[2], 2])/
   (27*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}}
