{{(4*QuarkCondensate[RenormalizationState[0]]*CouplingConstant[ChPTW3[2], 1]*
    CouplingConstant[ChPTW3[4], 21]*
    (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}, 
 {(2*QuarkCondensate[RenormalizationState[0]]*CouplingConstant[ChPTW3[2], 1]*
    CouplingConstant[ChPTW3[4], 22]*
    (SUNDelta[0, I3]*(-UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]]]] + UTrace1[NonCommutative[
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[6]]]]) - 
     UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}}
