{{(-8*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
    CouplingConstant[ChPTW3[4], 20])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(-8*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
    CouplingConstant[ChPTW3[4], 20])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(-2*(24*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 8*Sqrt[3]*SU3F[6, I2, I3]*
      SUNDelta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 8*Sqrt[3]*SU3F[6, I1, I2]*
      SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3D[I1, k1, k2]*
      SU3D[I3, k2, k3]*SU3F[6, I2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     12*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k3]*SU3F[I1, k2, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3F[6, I2, k2]*
      SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     12*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k3]*SU3F[I3, k2, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3F[6, I2, k2]*
      SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     24*Sqrt[3]*SU3D[I1, I3, k1]*SU3D[k1, k2, k3]*SU3F[6, I2, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 24*I*Sqrt[3]*SU3D[I1, I3, k1]*
      SU3F[6, I2, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     12*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I2, k2]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 12*I*Sqrt[3]*SU3D[I3, k1, k2]*
      SU3F[6, I2, k2]*SU3F[I1, k1, k3]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
     12*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[I3, k1, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 24*SUNDelta[7, I2]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     24*Sqrt[3]*SU3F[6, I2, I3]*SUNDelta[8, I1]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 6] - 24*Sqrt[3]*SU3F[6, I1, I2]*
      SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 6] + 72*SUNDelta[7, I2]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 7] + 
     36*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 8] + 6*I*SU3D[6, I3, k1]*SU3D[I1, I2, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     6*I*SU3D[6, I2, k1]*SU3D[I1, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 18*SU3D[7, I2, k1]*SU3D[I1, I3, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
     6*I*SU3D[6, I1, k1]*SU3D[I2, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 6*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
     6*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 6*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     18*I*SU3D[I1, I3, k1]*SU3F[7, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 6*SU3D[6, I3, k1]*SU3F[I1, I2, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     6*I*SU3F[6, I3, k1]*SU3F[I1, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 6*SU3D[6, I1, k1]*SU3F[I2, I3, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
     6*I*SU3F[6, I1, k1]*SU3F[I2, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 8*I*Sqrt[3]*SU3D[8, I2, I3]*
      SUNDelta[6, I1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 8*I*Sqrt[3]*SU3D[8, I1, I3]*
      SUNDelta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 8*I*Sqrt[3]*SU3D[8, I1, I2]*
      SUNDelta[6, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 16*I*Sqrt[3]*SU3D[6, I1, I3]*
      SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 12*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3D[I3, k2, k3]*SU3F[6, I1, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     12*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k3]*SU3F[I1, k2, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 12*I*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3F[6, I1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
     12*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k2, k3]*SU3D[I3, k1, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 12*Sqrt[3]*SU3D[I1, I3, k1]*
      SU3D[k1, k2, k3]*SU3F[6, I2, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
     12*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I2, k2, k3]*SU3F[I1, k1, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 12*Sqrt[3]*SU3D[6, I1, k1]*
      SU3D[I2, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     12*I*Sqrt[3]*SU3D[I1, I3, k1]*SU3F[6, I2, k3]*SU3F[k1, k2, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 12*I*Sqrt[3]*SU3D[6, I3, k1]*
      SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     12*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3D[k1, k2, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 12*Sqrt[3]*SU3D[I1, k1, k2]*
      SU3D[I2, k1, k3]*SU3F[6, I3, k2]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     12*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3F[k1, k2, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 4*I*SUNDelta[6, I3]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
     4*I*SUNDelta[6, I1]*SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 4*Sqrt[3]*SU3F[8, I1, I3]*
      SUNDelta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] + 3*I*Sqrt[3]*SU3D[I3, k1, k2]*
      SU3F[6, k2, k3]*SU3F[I1, I2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
     3*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k3]*SU3F[I1, k2, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
      SU3F[6, I1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     6*Sqrt[3]*SU3F[6, k2, k3]*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 6*Sqrt[3]*SU3F[6, I2, k2]*
      SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
     12*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] + 3*Sqrt[3]*SU3D[I1, I2, k1]*
      SU3D[I3, k2, k3]*SU3F[6, k1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
     3*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, k1, k3]*SU3F[I1, I2, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 3*Sqrt[3]*SU3D[6, I2, k1]*
      SU3D[I3, k2, k3]*SU3F[I1, k1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     3*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k3]*SU3F[I1, k1, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] + 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
      SU3F[6, I1, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     6*I*Sqrt[3]*SU3D[I1, I2, k1]*SU3F[6, k1, k3]*SU3F[I3, k2, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 6*I*Sqrt[3]*SU3D[6, I2, k1]*
      SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
     3*Sqrt[3]*SU3D[I1, I2, k1]*SU3D[I3, k2, k3]*SU3F[6, k1, k2]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] + 3*Sqrt[3]*SU3D[6, I2, k1]*
      SU3D[I3, k2, k3]*SU3F[I1, k1, k2]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     3*Sqrt[3]*SU3D[6, k1, k2]*SU3D[I1, I2, k2]*SU3F[I3, k1, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] + 12*I*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3F[6, I1, k2]*SU3F[I3, k1, k3]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     6*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[I3, k1, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 6*I*Sqrt[3]*SU3D[6, k1, k2]*
      SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     3*Sqrt[3]*SU3D[6, k1, k2]*SU3D[I1, I2, k1]*SU3F[I3, k2, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 6*Sqrt[3]*SU3D[6, I2, k1]*
      SU3D[I1, k1, k2]*SU3F[I3, k2, k3]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     I*SUNDelta[6, I3]*SUNDelta[I1, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 3*SUNDelta[7, I3]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     2*I*Sqrt[3]*SU3D[6, I3, k1]*SUNDelta[8, k1]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
     2*Sqrt[3]*SU3F[6, I3, k1]*SUNDelta[8, k1]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     6*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 4*Sqrt[3]*SU3F[6, I1, I3]*
      SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 2*Sqrt[3]*SU3F[6, I1, I2]*
      SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 3*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3D[I3, k2, k3]*SU3F[6, I1, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
     3*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3F[6, I1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
     3*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, I3, k3]*SU3F[k1, k2, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 3*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3D[I3, k1, k3]*SU3F[6, I1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
     3*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k3]*SU3F[I2, k1, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3F[6, I1, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
     3*I*Sqrt[3]*SU3D[I2, I3, k1]*SU3F[6, I1, k3]*SU3F[k1, k2, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 3*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3D[I3, k1, k3]*SU3F[6, I1, k2]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
     3*Sqrt[3]*SU3D[I2, I3, k1]*SU3D[k1, k2, k3]*SU3F[6, I1, k2]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[k1, k2, k3]*
      SU3F[6, I1, k2]*SU3F[I2, I3, k1]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
     3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[I3, k1, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 2*Sqrt[3]*SU3F[6, I1, k1]*
      SUNDelta[8, k1]*SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 12*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
     8*Sqrt[3]*SU3F[6, I1, I3]*SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 23] + 4*Sqrt[3]*SU3F[6, I1, I2]*
      SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 6*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3D[I3, k2, k3]*SU3F[6, I1, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
     6*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3F[6, I1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
     6*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, I3, k3]*SU3F[k1, k2, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 6*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3D[I3, k1, k3]*SU3F[6, I1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
     6*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k3]*SU3F[I2, k1, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3F[6, I1, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
     6*I*Sqrt[3]*SU3D[I2, I3, k1]*SU3F[6, I1, k3]*SU3F[k1, k2, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 6*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3D[I3, k1, k3]*SU3F[6, I1, k2]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
     6*Sqrt[3]*SU3D[I2, I3, k1]*SU3D[k1, k2, k3]*SU3F[6, I1, k2]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[k1, k2, k3]*
      SU3F[6, I1, k2]*SU3F[I2, I3, k1]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
     6*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[I3, k1, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 4*Sqrt[3]*SU3F[6, I1, k1]*
      SUNDelta[8, k1]*SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 24*Sqrt[3]*SU3F[6, I1, I3]*
      SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 24]))/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {(-48*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 24*SU3F[6, I2, I3]*SUNDelta[3, I1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    24*SU3F[6, I1, I2]*SUNDelta[3, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*SU3F[3, I3, k2]*SU3F[I1, k2, k3]*
     SU3F[I2, k1, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*SU3F[3, I1, k2]*SU3F[I2, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 72*I*SU3D[I1, I3, k1]*SU3F[3, k1, k3]*
     SU3F[I2, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*I*SU3D[3, I3, k1]*SU3F[I1, k1, k3]*
     SU3F[I2, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*I*SU3D[3, I1, k1]*SU3F[I2, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 72*SU3D[3, k1, k2]*SU3D[I1, I3, k2]*
     SU3F[I2, k1, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*SU3D[3, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[I2, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*SU3D[3, I1, k1]*SU3D[I3, k1, k2]*
     SU3F[I2, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*I*SU3D[I3, k1, k2]*SU3F[3, I1, k1]*
     SU3F[I2, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*I*SU3D[I1, k1, k2]*SU3F[3, I3, k1]*
     SU3F[I2, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 8*Sqrt[3]*SU3F[6, I2, I3]*
     SUNDelta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 8*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3D[I1, k1, k2]*
     SU3D[I3, k2, k3]*SU3F[6, I2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    12*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k3]*SU3F[I1, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3F[6, I2, k2]*
     SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    12*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k3]*SU3F[I3, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    24*Sqrt[3]*SU3D[I1, I3, k1]*SU3D[k1, k2, k3]*SU3F[6, I2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 24*I*Sqrt[3]*SU3D[I1, I3, k1]*
     SU3F[6, I2, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    12*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I2, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 12*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I2, k2]*SU3F[I1, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
    12*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[I3, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 48*SUNDelta[7, I2]*SUNDelta[I1, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
    72*SU3F[6, I2, I3]*SUNDelta[3, I1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6] + 72*SU3F[6, I1, I2]*SUNDelta[3, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6] + 
    24*Sqrt[3]*SU3F[6, I2, I3]*SUNDelta[8, I1]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 6] - 24*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6] + 144*SUNDelta[7, I2]*SUNDelta[I1, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 7] - 
    72*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 8] - 12*I*SU3D[6, I3, k1]*SU3D[I1, I2, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*I*SU3D[6, I2, k1]*SU3D[I1, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 36*SU3D[7, I2, k1]*SU3D[I1, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*SU3D[6, I1, k1]*SU3D[I2, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*I*SU3D[I1, I3, k1]*SU3F[7, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*SU3D[6, I3, k1]*SU3F[I1, I2, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*I*SU3F[6, I3, k1]*SU3F[I1, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*SU3D[6, I1, k1]*SU3F[I2, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*SU3F[6, I1, k1]*SU3F[I2, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 48*I*SU3D[6, I1, I3]*SUNDelta[3, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    24*I*SU3D[3, I2, I3]*SUNDelta[6, I1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 8*I*Sqrt[3]*SU3D[8, I2, I3]*
     SUNDelta[6, I1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 24*I*SU3D[3, I1, I3]*SUNDelta[6, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    8*I*Sqrt[3]*SU3D[8, I1, I3]*SUNDelta[6, I2]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 9] - 24*I*SU3D[3, I1, I2]*
     SUNDelta[6, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 8*I*Sqrt[3]*SU3D[8, I1, I2]*
     SUNDelta[6, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 36*I*SU3D[3, I2, k1]*SU3D[I1, k2, k3]*
     SU3D[I3, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 36*SU3D[I1, I3, k1]*SU3D[I2, k2, k3]*
     SU3F[3, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 36*SU3D[3, I2, k1]*SU3D[I3, k2, k3]*
     SU3F[I1, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 36*I*SU3D[I1, I3, k1]*SU3F[3, k1, k3]*
     SU3F[I2, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 36*SU3D[3, I2, k1]*SU3D[I1, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 36*I*SU3D[3, I2, k1]*SU3F[I1, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 36*I*SU3D[3, I2, k1]*SU3F[I1, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 36*I*SU3D[3, k1, k2]*SU3D[I1, I3, k2]*
     SU3D[I2, k1, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 36*I*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*
     SU3D[I3, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 36*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 36*SU3D[3, k1, k2]*SU3D[I1, I3, k2]*
     SU3F[I2, k1, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 36*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*
     SU3F[I3, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 16*I*Sqrt[3]*SU3D[6, I1, I3]*
     SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k2, k3]*SU3F[6, I1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k3]*SU3F[I1, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k2, k3]*SU3D[I3, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*Sqrt[3]*SU3D[I1, I3, k1]*
     SU3D[k1, k2, k3]*SU3F[6, I2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I2, k2, k3]*SU3F[I1, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*Sqrt[3]*SU3D[6, I1, k1]*
     SU3D[I2, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*Sqrt[3]*SU3D[I1, I3, k1]*SU3F[6, I2, k3]*SU3F[k1, k2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*I*Sqrt[3]*SU3D[6, I3, k1]*
     SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3D[k1, k2, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*Sqrt[3]*SU3D[I1, k1, k2]*
     SU3D[I2, k1, k3]*SU3F[6, I3, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3F[k1, k2, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 8*I*SUNDelta[6, I3]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    8*I*SUNDelta[6, I1]*SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*SU3F[3, I1, I3]*SUNDelta[6, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    4*Sqrt[3]*SU3F[8, I1, I3]*SUNDelta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*SU3F[3, I3, k2]*SU3F[I1, k2, k3]*
     SU3F[I2, k1, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 36*SU3F[3, I3, k2]*SU3F[I1, k1, k3]*
     SU3F[I2, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*SU3F[3, I3, k2]*SU3F[I1, I2, k3]*
     SU3F[k1, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*I*SU3D[k1, k2, k3]*SU3F[3, I3, k1]*
     SU3F[I1, I2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*I*SU3D[I2, k1, k2]*SU3F[3, I3, k3]*
     SU3F[I1, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*I*SU3D[I1, I2, k1]*SU3F[3, I3, k3]*
     SU3F[k1, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*
     SU3F[3, I3, k1]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*SU3D[I1, I2, k1]*SU3D[k1, k2, k3]*
     SU3F[3, I3, k2]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 36*I*SU3D[I2, k1, k2]*SU3F[3, I3, k1]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*I*SU3D[I1, k1, k2]*SU3F[3, I3, k1]*
     SU3F[I2, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 3*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, k2, k3]*SU3F[I1, I2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    3*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k3]*SU3F[I1, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*Sqrt[3]*SU3F[6, k2, k3]*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*Sqrt[3]*SU3F[6, I2, k2]*
     SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    12*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 3*Sqrt[3]*SU3D[I1, I2, k1]*
     SU3D[I3, k2, k3]*SU3F[6, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    3*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, k1, k3]*SU3F[I1, I2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 3*Sqrt[3]*SU3D[6, I2, k1]*
     SU3D[I3, k2, k3]*SU3F[I1, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    3*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k3]*SU3F[I1, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*I*Sqrt[3]*SU3D[I1, I2, k1]*SU3F[6, k1, k3]*SU3F[I3, k2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*I*Sqrt[3]*SU3D[6, I2, k1]*
     SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    3*Sqrt[3]*SU3D[I1, I2, k1]*SU3D[I3, k2, k3]*SU3F[6, k1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 3*Sqrt[3]*SU3D[6, I2, k1]*
     SU3D[I3, k2, k3]*SU3F[I1, k1, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*Sqrt[3]*SU3D[6, k1, k2]*SU3D[I1, I2, k2]*SU3F[I3, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 12*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2]*SU3F[I3, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[I3, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*I*Sqrt[3]*SU3D[6, k1, k2]*
     SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3F[I3, k2, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 2*I*SUNDelta[6, I3]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*I*SU3D[3, I3, k1]*SUNDelta[6, k1]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*SU3F[3, I3, k1]*SUNDelta[6, k1]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*SUNDelta[7, I3]*SUNDelta[I1, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 2*I*Sqrt[3]*SU3D[6, I3, k1]*
     SUNDelta[8, k1]*SUNDelta[I1, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 2*Sqrt[3]*SU3F[6, I3, k1]*
     SUNDelta[8, k1]*SUNDelta[I1, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 12*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    12*SU3F[6, I1, I3]*SUNDelta[3, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 6*SU3F[6, I1, I2]*SUNDelta[3, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    9*SU3F[3, k2, k3]*SU3F[I1, k1, k3]*SU3F[I2, I3, k2]*SUNDelta[6, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    9*SU3F[3, I3, k2]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*SUNDelta[6, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    9*I*SU3D[I2, I3, k1]*SU3F[3, k1, k3]*SU3F[I1, k2, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    9*I*SU3D[3, I3, k1]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    18*I*SU3D[3, I2, k1]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    9*SU3D[3, k1, k2]*SU3D[I2, I3, k2]*SU3F[I1, k1, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    9*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    18*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    9*I*SU3D[I2, k1, k2]*SU3F[3, I3, k1]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    9*I*SU3D[3, k1, k2]*SU3F[I1, k2, k3]*SU3F[I2, I3, k1]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    4*Sqrt[3]*SU3F[6, I1, I3]*SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 2*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k2, k3]*SU3F[6, I1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    3*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    3*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, I3, k3]*SU3F[k1, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k1, k3]*SU3F[6, I1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    3*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k3]*SU3F[I2, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    3*I*Sqrt[3]*SU3D[I2, I3, k1]*SU3F[6, I1, k3]*SU3F[k1, k2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k1, k3]*SU3F[6, I1, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    3*Sqrt[3]*SU3D[I2, I3, k1]*SU3D[k1, k2, k3]*SU3F[6, I1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[k1, k2, k3]*
     SU3F[6, I1, k2]*SU3F[I2, I3, k1]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[I3, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 6*SU3F[3, I1, k1]*SUNDelta[6, k1]*
     SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 2*Sqrt[3]*SU3F[6, I1, k1]*
     SUNDelta[8, k1]*SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 24*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    24*SU3F[6, I1, I3]*SUNDelta[3, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 12*SU3F[6, I1, I2]*SUNDelta[3, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    18*SU3F[3, k2, k3]*SU3F[I1, k1, k3]*SU3F[I2, I3, k2]*SUNDelta[6, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    18*SU3F[3, I3, k2]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*SUNDelta[6, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    18*I*SU3D[I2, I3, k1]*SU3F[3, k1, k3]*SU3F[I1, k2, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    18*I*SU3D[3, I3, k1]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    36*I*SU3D[3, I2, k1]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    18*SU3D[3, k1, k2]*SU3D[I2, I3, k2]*SU3F[I1, k1, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    18*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    36*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    18*I*SU3D[I2, k1, k2]*SU3F[3, I3, k1]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    18*I*SU3D[3, k1, k2]*SU3F[I1, k2, k3]*SU3F[I2, I3, k1]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    8*Sqrt[3]*SU3F[6, I1, I3]*SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 4*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k2, k3]*SU3F[6, I1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    6*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    6*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, I3, k3]*SU3F[k1, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k1, k3]*SU3F[6, I1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    6*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k3]*SU3F[I2, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    6*I*Sqrt[3]*SU3D[I2, I3, k1]*SU3F[6, I1, k3]*SU3F[k1, k2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k1, k3]*SU3F[6, I1, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    6*Sqrt[3]*SU3D[I2, I3, k1]*SU3D[k1, k2, k3]*SU3F[6, I1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[k1, k2, k3]*
     SU3F[6, I1, k2]*SU3F[I2, I3, k1]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    6*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[I3, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 12*SU3F[3, I1, k1]*SUNDelta[6, k1]*
     SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 4*Sqrt[3]*SU3F[6, I1, k1]*
     SUNDelta[8, k1]*SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 72*SU3F[6, I1, I3]*SUNDelta[3, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 24] + 
    24*Sqrt[3]*SU3F[6, I1, I3]*SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 24])/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {(-48*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 24*SU3F[6, I2, I3]*SUNDelta[3, I1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
    24*SU3F[6, I1, I2]*SUNDelta[3, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*SU3F[3, I3, k2]*SU3F[I1, k2, k3]*
     SU3F[I2, k1, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*SU3F[3, I1, k2]*SU3F[I2, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 72*I*SU3D[I1, I3, k1]*SU3F[3, k1, k3]*
     SU3F[I2, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*I*SU3D[3, I3, k1]*SU3F[I1, k1, k3]*
     SU3F[I2, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*I*SU3D[3, I1, k1]*SU3F[I2, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 72*SU3D[3, k1, k2]*SU3D[I1, I3, k2]*
     SU3F[I2, k1, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*SU3D[3, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[I2, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*SU3D[3, I1, k1]*SU3D[I3, k1, k2]*
     SU3F[I2, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*I*SU3D[I3, k1, k2]*SU3F[3, I1, k1]*
     SU3F[I2, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*I*SU3D[I1, k1, k2]*SU3F[3, I3, k1]*
     SU3F[I2, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 8*Sqrt[3]*SU3F[6, I2, I3]*
     SUNDelta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 8*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3D[I1, k1, k2]*
     SU3D[I3, k2, k3]*SU3F[6, I2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    12*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k3]*SU3F[I1, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3F[6, I2, k2]*
     SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    12*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k3]*SU3F[I3, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    24*Sqrt[3]*SU3D[I1, I3, k1]*SU3D[k1, k2, k3]*SU3F[6, I2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 24*I*Sqrt[3]*SU3D[I1, I3, k1]*
     SU3F[6, I2, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    12*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I2, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 12*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I2, k2]*SU3F[I1, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
    12*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[I3, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 72*SU3F[6, I2, I3]*SUNDelta[3, I1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6] - 
    72*SU3F[6, I1, I2]*SUNDelta[3, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6] + 24*Sqrt[3]*SU3F[6, I2, I3]*
     SUNDelta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6] - 24*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6] - 72*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 8] - 
    12*I*SU3D[6, I3, k1]*SU3D[I1, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 48*I*SU3D[6, I2, k1]*SU3D[I1, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*SU3D[6, I1, k1]*SU3D[I2, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    48*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*SU3D[6, I3, k1]*SU3F[I1, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*I*SU3F[6, I3, k1]*SU3F[I1, I2, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*SU3D[6, I1, k1]*SU3F[I2, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*I*SU3F[6, I1, k1]*SU3F[I2, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    48*I*SU3D[6, I1, I3]*SUNDelta[3, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 24*I*SU3D[3, I2, I3]*SUNDelta[6, I1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    8*I*Sqrt[3]*SU3D[8, I2, I3]*SUNDelta[6, I1]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 9] - 24*I*SU3D[3, I1, I3]*
     SUNDelta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 8*I*Sqrt[3]*SU3D[8, I1, I3]*
     SUNDelta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 24*I*SU3D[3, I1, I2]*SUNDelta[6, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    8*I*Sqrt[3]*SU3D[8, I1, I2]*SUNDelta[6, I3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 9] + 36*I*SU3D[3, I2, k1]*
     SU3D[I1, k2, k3]*SU3D[I3, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    36*SU3D[I1, I3, k1]*SU3D[I2, k2, k3]*SU3F[3, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*SU3D[3, I2, k1]*SU3D[I3, k2, k3]*SU3F[I1, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*I*SU3D[I1, I3, k1]*SU3F[3, k1, k3]*SU3F[I2, k2, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*SU3D[3, I2, k1]*SU3D[I1, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    36*I*SU3D[3, I2, k1]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    36*I*SU3D[3, I2, k1]*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*I*SU3D[3, k1, k2]*SU3D[I1, I3, k2]*SU3D[I2, k1, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    36*I*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    36*SU3D[3, k1, k2]*SU3D[I1, I3, k2]*SU3F[I2, k1, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*SU3F[I3, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    16*I*Sqrt[3]*SU3D[6, I1, I3]*SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 9] - 12*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k2, k3]*SU3F[6, I1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k3]*SU3F[I1, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k2, k3]*SU3D[I3, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*Sqrt[3]*SU3D[I1, I3, k1]*
     SU3D[k1, k2, k3]*SU3F[6, I2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I2, k2, k3]*SU3F[I1, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*Sqrt[3]*SU3D[6, I1, k1]*
     SU3D[I2, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*Sqrt[3]*SU3D[I1, I3, k1]*SU3F[6, I2, k3]*SU3F[k1, k2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*I*Sqrt[3]*SU3D[6, I3, k1]*
     SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3D[k1, k2, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*Sqrt[3]*SU3D[I1, k1, k2]*
     SU3D[I2, k1, k3]*SU3F[6, I3, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3F[k1, k2, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 8*I*SUNDelta[6, I3]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    48*I*SUNDelta[6, I2]*SUNDelta[I1, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 8*I*SUNDelta[6, I1]*SUNDelta[I2, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*SU3F[3, I1, I3]*SUNDelta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 4*Sqrt[3]*SU3F[8, I1, I3]*
     SUNDelta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*I*SU3D[I2, k1, k2]*SU3F[3, I3, k3]*
     SU3F[I1, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*SU3F[3, I3, k2]*SU3F[I1, k2, k3]*
     SU3F[I2, k1, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 36*SU3F[3, I3, k2]*SU3F[I1, k1, k3]*
     SU3F[I2, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*SU3F[3, I3, k2]*SU3F[I1, I2, k3]*
     SU3F[k1, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*I*SU3D[k1, k2, k3]*SU3F[3, I3, k1]*
     SU3F[I1, I2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*I*SU3D[I1, I2, k1]*SU3F[3, I3, k3]*
     SU3F[k1, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*
     SU3F[3, I3, k1]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*SU3D[I1, I2, k1]*SU3D[k1, k2, k3]*
     SU3F[3, I3, k2]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 36*I*SU3D[I2, k1, k2]*SU3F[3, I3, k1]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*I*SU3D[I1, k1, k2]*SU3F[3, I3, k1]*
     SU3F[I2, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 3*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, k2, k3]*SU3F[I1, I2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    3*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k3]*SU3F[I1, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*Sqrt[3]*SU3F[6, k2, k3]*SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*Sqrt[3]*SU3F[6, I2, k2]*
     SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    12*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 3*Sqrt[3]*SU3D[I1, I2, k1]*
     SU3D[I3, k2, k3]*SU3F[6, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    3*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, k1, k3]*SU3F[I1, I2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 3*Sqrt[3]*SU3D[6, I2, k1]*
     SU3D[I3, k2, k3]*SU3F[I1, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    3*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I2, k3]*SU3F[I1, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*I*Sqrt[3]*SU3D[I1, I2, k1]*SU3F[6, k1, k3]*SU3F[I3, k2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*I*Sqrt[3]*SU3D[6, I2, k1]*
     SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    3*Sqrt[3]*SU3D[I1, I2, k1]*SU3D[I3, k2, k3]*SU3F[6, k1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 3*Sqrt[3]*SU3D[6, I2, k1]*
     SU3D[I3, k2, k3]*SU3F[I1, k1, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*Sqrt[3]*SU3D[6, k1, k2]*SU3D[I1, I2, k2]*SU3F[I3, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 12*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2]*SU3F[I3, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[I3, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*I*Sqrt[3]*SU3D[6, k1, k2]*
     SU3F[I1, I2, k2]*SU3F[I3, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3F[I3, k2, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 4*I*SUNDelta[6, I3]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*I*SU3D[3, I3, k1]*SUNDelta[6, k1]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*SU3F[3, I3, k1]*SUNDelta[6, k1]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    2*I*Sqrt[3]*SU3D[6, I3, k1]*SUNDelta[8, k1]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    2*Sqrt[3]*SU3F[6, I3, k1]*SUNDelta[8, k1]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    12*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 12*SU3F[6, I1, I3]*SUNDelta[3, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    6*SU3F[6, I1, I2]*SUNDelta[3, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 9*SU3F[3, k2, k3]*SU3F[I1, k1, k3]*
     SU3F[I2, I3, k2]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 9*SU3F[3, I3, k2]*SU3F[I1, k1, k3]*
     SU3F[I2, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 9*I*SU3D[I2, I3, k1]*SU3F[3, k1, k3]*
     SU3F[I1, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 9*I*SU3D[3, I3, k1]*SU3F[I1, k2, k3]*
     SU3F[I2, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 18*I*SU3D[3, I2, k1]*SU3F[I1, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 9*SU3D[3, k1, k2]*SU3D[I2, I3, k2]*
     SU3F[I1, k1, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 9*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 18*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 9*I*SU3D[I2, k1, k2]*SU3F[3, I3, k1]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 9*I*SU3D[3, k1, k2]*SU3F[I1, k2, k3]*
     SU3F[I2, I3, k1]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 4*Sqrt[3]*SU3F[6, I1, I3]*
     SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 2*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k2, k3]*SU3F[6, I1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    3*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    3*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, I3, k3]*SU3F[k1, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k1, k3]*SU3F[6, I1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    3*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k3]*SU3F[I2, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    3*I*Sqrt[3]*SU3D[I2, I3, k1]*SU3F[6, I1, k3]*SU3F[k1, k2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k1, k3]*SU3F[6, I1, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    3*Sqrt[3]*SU3D[I2, I3, k1]*SU3D[k1, k2, k3]*SU3F[6, I1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[k1, k2, k3]*
     SU3F[6, I1, k2]*SU3F[I2, I3, k1]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[I3, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 6*SU3F[3, I1, k1]*SUNDelta[6, k1]*
     SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 2*Sqrt[3]*SU3F[6, I1, k1]*
     SUNDelta[8, k1]*SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 24*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    24*SU3F[6, I1, I3]*SUNDelta[3, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 12*SU3F[6, I1, I2]*SUNDelta[3, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    18*SU3F[3, k2, k3]*SU3F[I1, k1, k3]*SU3F[I2, I3, k2]*SUNDelta[6, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    18*SU3F[3, I3, k2]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*SUNDelta[6, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    18*I*SU3D[I2, I3, k1]*SU3F[3, k1, k3]*SU3F[I1, k2, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    18*I*SU3D[3, I3, k1]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    36*I*SU3D[3, I2, k1]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    18*SU3D[3, k1, k2]*SU3D[I2, I3, k2]*SU3F[I1, k1, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    18*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    36*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    18*I*SU3D[I2, k1, k2]*SU3F[3, I3, k1]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    18*I*SU3D[3, k1, k2]*SU3F[I1, k2, k3]*SU3F[I2, I3, k1]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    8*Sqrt[3]*SU3F[6, I1, I3]*SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 4*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k2, k3]*SU3F[6, I1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    6*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k2, k3]*SU3F[I3, k1, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    6*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, I3, k3]*SU3F[k1, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k1, k3]*SU3F[6, I1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    6*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k3]*SU3F[I2, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    6*I*Sqrt[3]*SU3D[I2, I3, k1]*SU3F[6, I1, k3]*SU3F[k1, k2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k1, k3]*SU3F[6, I1, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    6*Sqrt[3]*SU3D[I2, I3, k1]*SU3D[k1, k2, k3]*SU3F[6, I1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[k1, k2, k3]*
     SU3F[6, I1, k2]*SU3F[I2, I3, k1]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    6*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[I3, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 12*SU3F[3, I1, k1]*SUNDelta[6, k1]*
     SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 4*Sqrt[3]*SU3F[6, I1, k1]*
     SUNDelta[8, k1]*SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 72*SU3F[6, I1, I3]*SUNDelta[3, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 24] + 
    24*Sqrt[3]*SU3F[6, I1, I3]*SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 24])/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {(-2*(24*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 8*Sqrt[3]*SU3F[6, I2, I3]*
      SUNDelta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 8*Sqrt[3]*SU3F[6, I1, I3]*
      SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3D[I1, k1, k2]*
      SU3D[I2, k2, k3]*SU3F[6, I3, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     12*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k3]*SU3F[I1, k2, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3F[6, I3, k2]*
      SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     12*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k3]*SU3F[I2, k2, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3F[6, I3, k2]*
      SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     24*Sqrt[3]*SU3D[I1, I2, k1]*SU3D[k1, k2, k3]*SU3F[6, I3, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 24*I*Sqrt[3]*SU3D[I1, I2, k1]*
      SU3F[6, I3, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     12*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I2, k1, k3]*SU3F[6, I3, k2]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 12*I*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3F[6, I3, k2]*SU3F[I1, k1, k3]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
     12*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k2]*SU3F[I2, k1, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 24*SUNDelta[7, I3]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
     24*Sqrt[3]*SU3F[6, I2, I3]*SUNDelta[8, I1]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 6] - 24*Sqrt[3]*SU3F[6, I1, I3]*
      SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 6] + 72*SUNDelta[7, I3]*SUNDelta[I1, I2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 7] + 
     36*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 8] - 6*I*SU3D[6, I3, k1]*SU3D[I1, I2, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     18*SU3D[7, I3, k1]*SU3D[I1, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 6*I*SU3D[6, I2, k1]*SU3D[I1, I3, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
     6*I*SU3D[6, I1, k1]*SU3D[I2, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 6*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     6*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 6*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     18*I*SU3D[I1, I2, k1]*SU3F[7, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 6*SU3D[6, I2, k1]*SU3F[I1, I3, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     6*I*SU3F[6, I2, k1]*SU3F[I1, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 6*SU3D[6, I1, k1]*SU3F[I2, I3, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     6*I*SU3F[6, I1, k1]*SU3F[I2, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 8*I*Sqrt[3]*SU3D[8, I2, I3]*
      SUNDelta[6, I1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 8*I*Sqrt[3]*SU3D[8, I1, I3]*
      SUNDelta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 8*I*Sqrt[3]*SU3D[8, I1, I2]*
      SUNDelta[6, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 16*I*Sqrt[3]*SU3D[6, I1, I2]*
      SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 12*I*Sqrt[3]*SU3D[I3, k1, k2]*
      SU3F[6, I2, k3]*SU3F[I1, k2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     12*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k3]*SU3F[I2, k2, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 12*Sqrt[3]*SU3D[I1, I2, k1]*
      SU3D[k1, k2, k3]*SU3F[6, I3, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
     12*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I3, k2, k3]*SU3F[I1, k1, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 12*Sqrt[3]*SU3D[6, I1, k1]*
      SU3D[I3, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     12*I*Sqrt[3]*SU3D[I1, I2, k1]*SU3F[6, I3, k3]*SU3F[k1, k2, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 12*I*Sqrt[3]*SU3D[6, I2, k1]*
      SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
     12*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, k2, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 12*I*Sqrt[3]*SU3D[6, I3, k1]*
      SU3D[I1, I2, k2]*SU3D[k1, k2, k3]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     12*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k2]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] - 12*Sqrt[3]*SU3D[I1, k1, k2]*
      SU3D[I3, k1, k3]*SU3F[6, I2, k2]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
     12*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*SU3F[k1, k2, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 4*I*SUNDelta[6, I2]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
     4*I*SUNDelta[6, I1]*SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9] + 4*Sqrt[3]*SU3F[8, I1, I2]*
      SUNDelta[6, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 6*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3D[I3, k2, k3]*SU3F[6, I1, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, k2, k3]*SU3F[I1, I3, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 3*I*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3F[6, I3, k3]*SU3F[I1, k2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     6*Sqrt[3]*SU3F[6, k2, k3]*SU3F[I1, I3, k2]*SU3F[I2, k1, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 6*Sqrt[3]*SU3F[6, I3, k2]*
      SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
     6*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k3]*SU3F[I3, k2, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 12*Sqrt[3]*SU3F[6, I1, k2]*
      SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     6*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] + 3*Sqrt[3]*SU3D[I1, I3, k1]*
      SU3D[I2, k2, k3]*SU3F[6, k1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
     3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, k1, k3]*SU3F[I1, I3, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 3*Sqrt[3]*SU3D[6, I3, k1]*
      SU3D[I2, k2, k3]*SU3F[I1, k1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k3]*SU3F[I1, k1, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] + 6*I*Sqrt[3]*SU3D[I1, I3, k1]*
      SU3F[6, k1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
     6*I*Sqrt[3]*SU3D[6, I3, k1]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] + 6*I*Sqrt[3]*SU3D[I2, k1, k2]*
      SU3F[6, I1, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
     3*Sqrt[3]*SU3D[I1, I3, k1]*SU3D[I2, k2, k3]*SU3F[6, k1, k2]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] + 3*Sqrt[3]*SU3D[6, I3, k1]*
      SU3D[I2, k2, k3]*SU3F[I1, k1, k2]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     3*Sqrt[3]*SU3D[6, k1, k2]*SU3D[I1, I3, k2]*SU3F[I2, k1, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] + 12*I*Sqrt[3]*SU3D[I3, k1, k2]*
      SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     6*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k2]*SU3F[I2, k1, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 6*I*Sqrt[3]*SU3D[6, k1, k2]*
      SU3F[I1, I3, k2]*SU3F[I2, k1, k3]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     3*Sqrt[3]*SU3D[6, k1, k2]*SU3D[I1, I3, k1]*SU3F[I2, k2, k3]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 6*Sqrt[3]*SU3D[6, I3, k1]*
      SU3D[I1, k1, k2]*SU3F[I2, k2, k3]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     I*SUNDelta[6, I2]*SUNDelta[I1, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 21] - 3*SUNDelta[7, I2]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     2*I*Sqrt[3]*SU3D[6, I2, k1]*SUNDelta[8, k1]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
     2*Sqrt[3]*SU3F[6, I2, k1]*SUNDelta[8, k1]*SUNDelta[I1, I3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
     6*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 2*Sqrt[3]*SU3F[6, I1, I3]*
      SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 4*Sqrt[3]*SU3F[6, I1, I2]*
      SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I3, k1, k2]*
      SU3F[6, I1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
     3*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] - 3*Sqrt[3]*SU3F[6, I1, k2]*
      SU3F[I2, I3, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
     3*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I3, k1, k2]*
      SU3F[6, I1, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
     3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k3]*SU3F[I3, k1, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] - 3*I*Sqrt[3]*SU3D[I2, I3, k1]*
      SU3F[6, I1, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
     6*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k2]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 3*Sqrt[3]*SU3D[I2, I3, k1]*
      SU3D[k1, k2, k3]*SU3F[6, I1, k2]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
     3*I*Sqrt[3]*SU3D[k1, k2, k3]*SU3F[6, I1, k2]*SU3F[I2, I3, k1]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I3, k1, k2]*
      SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
     2*Sqrt[3]*SU3F[6, I1, k1]*SUNDelta[8, k1]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
     12*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 4*Sqrt[3]*SU3F[6, I1, I3]*
      SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 8*Sqrt[3]*SU3F[6, I1, I2]*
      SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
      SU3F[6, I1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
     6*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*
      SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] - 6*Sqrt[3]*SU3F[6, I1, k2]*
      SU3F[I2, I3, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
     6*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
      SU3F[6, I1, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
     6*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k3]*SU3F[I3, k1, k3]*
      SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] - 6*I*Sqrt[3]*SU3D[I2, I3, k1]*
      SU3F[6, I1, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
     12*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k2]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 6*Sqrt[3]*SU3D[I2, I3, k1]*
      SU3D[k1, k2, k3]*SU3F[6, I1, k2]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
     6*I*Sqrt[3]*SU3D[k1, k2, k3]*SU3F[6, I1, k2]*SU3F[I2, I3, k1]*
      SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
      SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SUNDelta[8, k3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
     4*Sqrt[3]*SU3F[6, I1, k1]*SUNDelta[8, k1]*SUNDelta[I2, I3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
     24*Sqrt[3]*SU3F[6, I1, I2]*SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 24]))/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {(-48*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 24*SU3F[6, I2, I3]*SUNDelta[3, I1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    24*SU3F[6, I1, I3]*SUNDelta[3, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*SU3F[3, I2, k2]*SU3F[I1, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*SU3F[3, I1, k2]*SU3F[I2, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 72*I*SU3D[I1, I2, k1]*SU3F[3, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*I*SU3D[3, I2, k1]*SU3F[I1, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*I*SU3D[3, I1, k1]*SU3F[I2, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 72*SU3D[3, k1, k2]*SU3D[I1, I2, k2]*
     SU3F[I3, k1, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*
     SU3F[I3, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*SU3D[3, I1, k1]*SU3D[I2, k1, k2]*
     SU3F[I3, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*I*SU3D[I2, k1, k2]*SU3F[3, I1, k1]*
     SU3F[I3, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*I*SU3D[I1, k1, k2]*SU3F[3, I2, k1]*
     SU3F[I3, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 8*Sqrt[3]*SU3F[6, I2, I3]*
     SUNDelta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 8*Sqrt[3]*SU3F[6, I1, I3]*
     SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3D[I1, k1, k2]*
     SU3D[I2, k2, k3]*SU3F[6, I3, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    12*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k3]*SU3F[I1, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3F[6, I3, k2]*
     SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    12*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k3]*SU3F[I2, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3F[6, I3, k2]*
     SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    24*Sqrt[3]*SU3D[I1, I2, k1]*SU3D[k1, k2, k3]*SU3F[6, I3, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 24*I*Sqrt[3]*SU3D[I1, I2, k1]*
     SU3F[6, I3, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    12*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I2, k1, k3]*SU3F[6, I3, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 12*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I3, k2]*SU3F[I1, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
    12*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k2]*SU3F[I2, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 48*SUNDelta[7, I3]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    72*SU3F[6, I2, I3]*SUNDelta[3, I1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6] + 72*SU3F[6, I1, I3]*SUNDelta[3, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6] - 
    24*Sqrt[3]*SU3F[6, I2, I3]*SUNDelta[8, I1]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 6] - 24*Sqrt[3]*SU3F[6, I1, I3]*
     SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6] + 144*SUNDelta[7, I3]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 7] - 
    72*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 8] + 12*I*SU3D[6, I3, k1]*SU3D[I1, I2, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*SU3D[7, I3, k1]*SU3D[I1, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*I*SU3D[6, I2, k1]*SU3D[I1, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*SU3D[6, I1, k1]*SU3D[I2, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*I*SU3D[I1, I2, k1]*SU3F[7, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*SU3D[6, I2, k1]*SU3F[I1, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*I*SU3F[6, I2, k1]*SU3F[I1, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*SU3D[6, I1, k1]*SU3F[I2, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*I*SU3F[6, I1, k1]*SU3F[I2, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 48*I*SU3D[6, I1, I2]*SUNDelta[3, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    24*I*SU3D[3, I2, I3]*SUNDelta[6, I1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 8*I*Sqrt[3]*SU3D[8, I2, I3]*
     SUNDelta[6, I1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 24*I*SU3D[3, I1, I3]*SUNDelta[6, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    8*I*Sqrt[3]*SU3D[8, I1, I3]*SUNDelta[6, I2]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 9] + 24*I*SU3D[3, I1, I2]*
     SUNDelta[6, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 8*I*Sqrt[3]*SU3D[8, I1, I2]*
     SUNDelta[6, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 36*I*SU3D[3, I3, k1]*SU3D[I1, k2, k3]*
     SU3D[I2, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 36*SU3D[I1, I2, k1]*SU3D[I3, k2, k3]*
     SU3F[3, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 36*SU3D[3, I3, k1]*SU3D[I2, k2, k3]*
     SU3F[I1, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 36*SU3D[3, I3, k1]*SU3D[I1, k2, k3]*
     SU3F[I2, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 36*I*SU3D[3, I3, k1]*SU3F[I1, k2, k3]*
     SU3F[I2, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 36*I*SU3D[3, I3, k1]*SU3F[I1, k1, k3]*
     SU3F[I2, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 36*I*SU3D[I1, I2, k1]*SU3F[3, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 36*I*SU3D[3, I3, k1]*SU3D[I1, k1, k2]*
     SU3D[I2, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 36*I*SU3D[3, k1, k2]*SU3D[I1, I2, k2]*
     SU3D[I3, k1, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 36*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 36*SU3D[3, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[I2, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 36*SU3D[3, k1, k2]*SU3D[I1, I2, k2]*
     SU3F[I3, k1, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 16*I*Sqrt[3]*SU3D[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I2, k3]*SU3F[I1, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k3]*SU3F[I2, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*Sqrt[3]*SU3D[I1, I2, k1]*
     SU3D[k1, k2, k3]*SU3F[6, I3, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I3, k2, k3]*SU3F[I1, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*Sqrt[3]*SU3D[6, I1, k1]*
     SU3D[I3, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*Sqrt[3]*SU3D[I1, I2, k1]*SU3F[6, I3, k3]*SU3F[k1, k2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*I*Sqrt[3]*SU3D[6, I2, k1]*
     SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, k2, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*I*Sqrt[3]*SU3D[6, I3, k1]*
     SU3D[I1, I2, k2]*SU3D[k1, k2, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*Sqrt[3]*SU3D[I1, k1, k2]*
     SU3D[I3, k1, k3]*SU3F[6, I2, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*SU3F[k1, k2, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 8*I*SUNDelta[6, I2]*SUNDelta[I1, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    8*I*SUNDelta[6, I1]*SUNDelta[I2, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*SU3F[3, I1, I2]*SUNDelta[6, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    4*Sqrt[3]*SU3F[8, I1, I2]*SUNDelta[6, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*SU3F[3, I2, k2]*SU3F[I1, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 36*SU3F[3, I2, k2]*SU3F[I1, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*SU3F[3, I2, k2]*SU3F[I1, I3, k3]*
     SU3F[k1, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*I*SU3D[k1, k2, k3]*SU3F[3, I2, k1]*
     SU3F[I1, I3, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*I*SU3D[I3, k1, k2]*SU3F[3, I2, k3]*
     SU3F[I1, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*I*SU3D[I1, I3, k1]*SU3F[3, I2, k3]*
     SU3F[k1, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*
     SU3F[3, I2, k1]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*SU3D[I1, I3, k1]*SU3D[k1, k2, k3]*
     SU3F[3, I2, k2]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 36*I*SU3D[I3, k1, k2]*SU3F[3, I2, k1]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*I*SU3D[I1, k1, k2]*SU3F[3, I2, k1]*
     SU3F[I3, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k2, k3]*SU3F[6, I1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, k2, k3]*SU3F[I1, I3, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 3*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I3, k3]*SU3F[I1, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*Sqrt[3]*SU3F[6, k2, k3]*SU3F[I1, I3, k2]*SU3F[I2, k1, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*Sqrt[3]*SU3F[6, I3, k2]*
     SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k3]*SU3F[I3, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 12*Sqrt[3]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 3*Sqrt[3]*SU3D[I1, I3, k1]*
     SU3D[I2, k2, k3]*SU3F[6, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, k1, k3]*SU3F[I1, I3, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 3*Sqrt[3]*SU3D[6, I3, k1]*
     SU3D[I2, k2, k3]*SU3F[I1, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k3]*SU3F[I1, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 6*I*Sqrt[3]*SU3D[I1, I3, k1]*
     SU3F[6, k1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*I*Sqrt[3]*SU3D[6, I3, k1]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 6*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    3*Sqrt[3]*SU3D[I1, I3, k1]*SU3D[I2, k2, k3]*SU3F[6, k1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 3*Sqrt[3]*SU3D[6, I3, k1]*
     SU3D[I2, k2, k3]*SU3F[I1, k1, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*Sqrt[3]*SU3D[6, k1, k2]*SU3D[I1, I3, k2]*SU3F[I2, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 12*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k2]*SU3F[I2, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*I*Sqrt[3]*SU3D[6, k1, k2]*
     SU3F[I1, I3, k2]*SU3F[I2, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*SU3F[I2, k2, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 2*I*SUNDelta[6, I2]*SUNDelta[I1, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*I*SU3D[3, I2, k1]*SUNDelta[6, k1]*SUNDelta[I1, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*SU3F[3, I2, k1]*SUNDelta[6, k1]*SUNDelta[I1, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*SUNDelta[7, I2]*SUNDelta[I1, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 2*I*Sqrt[3]*SU3D[6, I2, k1]*
     SUNDelta[8, k1]*SUNDelta[I1, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 2*Sqrt[3]*SU3F[6, I2, k1]*
     SUNDelta[8, k1]*SUNDelta[I1, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 12*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    6*SU3F[6, I1, I3]*SUNDelta[3, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 12*SU3F[6, I1, I2]*SUNDelta[3, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    9*SU3F[3, k2, k3]*SU3F[I1, k1, k3]*SU3F[I2, I3, k2]*SUNDelta[6, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    9*SU3F[3, I2, k2]*SU3F[I1, k1, k3]*SU3F[I3, k2, k3]*SUNDelta[6, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    9*I*SU3D[I2, I3, k1]*SU3F[3, k1, k3]*SU3F[I1, k2, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    18*I*SU3D[3, I3, k1]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    9*I*SU3D[3, I2, k1]*SU3F[I1, k2, k3]*SU3F[I3, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    9*SU3D[3, k1, k2]*SU3D[I2, I3, k2]*SU3F[I1, k1, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    18*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    9*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    9*I*SU3D[I3, k1, k2]*SU3F[3, I2, k1]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    9*I*SU3D[3, k1, k2]*SU3F[I1, k2, k3]*SU3F[I2, I3, k1]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    2*Sqrt[3]*SU3F[6, I1, I3]*SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 4*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    3*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 3*Sqrt[3]*SU3F[6, I1, k2]*
     SU3F[I2, I3, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    3*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k3]*SU3F[I3, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 3*I*Sqrt[3]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    6*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*Sqrt[3]*SU3D[I2, I3, k1]*
     SU3D[k1, k2, k3]*SU3F[6, I1, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    3*I*Sqrt[3]*SU3D[k1, k2, k3]*SU3F[6, I1, k2]*SU3F[I2, I3, k1]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    6*SU3F[3, I1, k1]*SUNDelta[6, k1]*SUNDelta[I2, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    2*Sqrt[3]*SU3F[6, I1, k1]*SUNDelta[8, k1]*SUNDelta[I2, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    24*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 12*SU3F[6, I1, I3]*SUNDelta[3, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    24*SU3F[6, I1, I2]*SUNDelta[3, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 18*SU3F[3, k2, k3]*SU3F[I1, k1, k3]*
     SU3F[I2, I3, k2]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 18*SU3F[3, I2, k2]*SU3F[I1, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 18*I*SU3D[I2, I3, k1]*SU3F[3, k1, k3]*
     SU3F[I1, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 36*I*SU3D[3, I3, k1]*SU3F[I1, k2, k3]*
     SU3F[I2, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 18*I*SU3D[3, I2, k1]*SU3F[I1, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 18*SU3D[3, k1, k2]*SU3D[I2, I3, k2]*
     SU3F[I1, k1, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 36*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 18*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 18*I*SU3D[I3, k1, k2]*SU3F[3, I2, k1]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 18*I*SU3D[3, k1, k2]*SU3F[I1, k2, k3]*
     SU3F[I2, I3, k1]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 4*Sqrt[3]*SU3F[6, I1, I3]*
     SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 8*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    6*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 6*Sqrt[3]*SU3F[6, I1, k2]*
     SU3F[I2, I3, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    6*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    6*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k3]*SU3F[I3, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 6*I*Sqrt[3]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    12*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*Sqrt[3]*SU3D[I2, I3, k1]*
     SU3D[k1, k2, k3]*SU3F[6, I1, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    6*I*Sqrt[3]*SU3D[k1, k2, k3]*SU3F[6, I1, k2]*SU3F[I2, I3, k1]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    12*SU3F[3, I1, k1]*SUNDelta[6, k1]*SUNDelta[I2, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    4*Sqrt[3]*SU3F[6, I1, k1]*SUNDelta[8, k1]*SUNDelta[I2, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    72*SU3F[6, I1, I2]*SUNDelta[3, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 24] + 24*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 24])/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {(-48*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 24*SU3F[6, I2, I3]*SUNDelta[3, I1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
    24*SU3F[6, I1, I3]*SUNDelta[3, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*SU3F[3, I2, k2]*SU3F[I1, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*SU3F[3, I1, k2]*SU3F[I2, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 72*I*SU3D[I1, I2, k1]*SU3F[3, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*I*SU3D[3, I2, k1]*SU3F[I1, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*I*SU3D[3, I1, k1]*SU3F[I2, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 72*SU3D[3, k1, k2]*SU3D[I1, I2, k2]*
     SU3F[I3, k1, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*
     SU3F[I3, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 36*SU3D[3, I1, k1]*SU3D[I2, k1, k2]*
     SU3F[I3, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*I*SU3D[I2, k1, k2]*SU3F[3, I1, k1]*
     SU3F[I3, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 36*I*SU3D[I1, k1, k2]*SU3F[3, I2, k1]*
     SU3F[I3, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 8*Sqrt[3]*SU3F[6, I2, I3]*
     SUNDelta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 8*Sqrt[3]*SU3F[6, I1, I3]*
     SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3D[I1, k1, k2]*
     SU3D[I2, k2, k3]*SU3F[6, I3, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    12*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k3]*SU3F[I1, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3F[6, I3, k2]*
     SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    12*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k3]*SU3F[I2, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] + 12*Sqrt[3]*SU3F[6, I3, k2]*
     SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    24*Sqrt[3]*SU3D[I1, I2, k1]*SU3D[k1, k2, k3]*SU3F[6, I3, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 24*I*Sqrt[3]*SU3D[I1, I2, k1]*
     SU3F[6, I3, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
    12*Sqrt[3]*SU3D[I1, k1, k2]*SU3D[I2, k1, k3]*SU3F[6, I3, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 12*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I3, k2]*SU3F[I1, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
    12*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k2]*SU3F[I2, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5] - 72*SU3F[6, I2, I3]*SUNDelta[3, I1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6] - 
    72*SU3F[6, I1, I3]*SUNDelta[3, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6] - 24*Sqrt[3]*SU3F[6, I2, I3]*
     SUNDelta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6] - 24*Sqrt[3]*SU3F[6, I1, I3]*
     SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6] - 72*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 8] + 
    48*I*SU3D[6, I3, k1]*SU3D[I1, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*I*SU3D[6, I2, k1]*SU3D[I1, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*SU3D[6, I1, k1]*SU3D[I2, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*SU3D[I1, I3, k1]*SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 48*SU3D[I1, I2, k1]*SU3F[6, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*SU3D[6, I2, k1]*SU3F[I1, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*I*SU3F[6, I2, k1]*SU3F[I1, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*SU3D[6, I1, k1]*SU3F[I2, I3, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*I*SU3F[6, I1, k1]*SU3F[I2, I3, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    48*I*SU3D[6, I1, I2]*SUNDelta[3, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 24*I*SU3D[3, I2, I3]*SUNDelta[6, I1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    8*I*Sqrt[3]*SU3D[8, I2, I3]*SUNDelta[6, I1]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 9] + 24*I*SU3D[3, I1, I3]*
     SUNDelta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 8*I*Sqrt[3]*SU3D[8, I1, I3]*
     SUNDelta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 24*I*SU3D[3, I1, I2]*SUNDelta[6, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    8*I*Sqrt[3]*SU3D[8, I1, I2]*SUNDelta[6, I3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 9] + 36*I*SU3D[3, I3, k1]*
     SU3D[I1, k2, k3]*SU3D[I2, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    36*SU3D[I1, I2, k1]*SU3D[I3, k2, k3]*SU3F[3, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*SU3D[3, I3, k1]*SU3D[I2, k2, k3]*SU3F[I1, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*SU3D[3, I3, k1]*SU3D[I1, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    36*I*SU3D[3, I3, k1]*SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    36*I*SU3D[3, I3, k1]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*I*SU3D[I1, I2, k1]*SU3F[3, k1, k3]*SU3F[I3, k2, k3]*SUNDelta[6, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    36*I*SU3D[3, I3, k1]*SU3D[I1, k1, k2]*SU3D[I2, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*I*SU3D[3, k1, k2]*SU3D[I1, I2, k2]*SU3D[I3, k1, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*SU3F[I1, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    36*SU3D[3, I3, k1]*SU3D[I1, k1, k2]*SU3F[I2, k2, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    36*SU3D[3, k1, k2]*SU3D[I1, I2, k2]*SU3F[I3, k1, k3]*SUNDelta[6, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    16*I*Sqrt[3]*SU3D[6, I1, I2]*SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 9] - 12*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I2, k3]*SU3F[I1, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*Sqrt[3]*SU3D[I3, k1, k2]*SU3F[6, I1, k3]*SU3F[I2, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*Sqrt[3]*SU3D[I1, I2, k1]*
     SU3D[k1, k2, k3]*SU3F[6, I3, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*Sqrt[3]*SU3D[6, I2, k1]*SU3D[I3, k2, k3]*SU3F[I1, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*Sqrt[3]*SU3D[6, I1, k1]*
     SU3D[I3, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*I*Sqrt[3]*SU3D[I1, I2, k1]*SU3F[6, I3, k3]*SU3F[k1, k2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 12*I*Sqrt[3]*SU3D[6, I2, k1]*
     SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*I*Sqrt[3]*SU3D[6, I1, k1]*SU3D[I2, k1, k2]*SU3D[I3, k2, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*I*Sqrt[3]*SU3D[6, I3, k1]*
     SU3D[I1, I2, k2]*SU3D[k1, k2, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 12*Sqrt[3]*SU3D[I1, k1, k2]*
     SU3D[I3, k1, k3]*SU3F[6, I2, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    12*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*SU3F[k1, k2, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] + 48*I*SUNDelta[6, I3]*SUNDelta[I1, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] - 
    8*I*SUNDelta[6, I2]*SUNDelta[I1, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9] - 8*I*SUNDelta[6, I1]*SUNDelta[I2, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9] + 
    12*SU3F[3, I1, I2]*SUNDelta[6, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 4*Sqrt[3]*SU3F[8, I1, I2]*
     SUNDelta[6, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*I*SU3D[I3, k1, k2]*SU3F[3, I2, k3]*
     SU3F[I1, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*SU3F[3, I2, k2]*SU3F[I1, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 36*SU3F[3, I2, k2]*SU3F[I1, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*SU3F[3, I2, k2]*SU3F[I1, I3, k3]*
     SU3F[k1, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*I*SU3D[k1, k2, k3]*SU3F[3, I2, k1]*
     SU3F[I1, I3, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*I*SU3D[I1, I3, k1]*SU3F[3, I2, k3]*
     SU3F[k1, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 18*SU3D[I1, k1, k2]*SU3D[I3, k2, k3]*
     SU3F[3, I2, k1]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*SU3D[I1, I3, k1]*SU3D[k1, k2, k3]*
     SU3F[3, I2, k2]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 36*I*SU3D[I3, k1, k2]*SU3F[3, I2, k1]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 18*I*SU3D[I1, k1, k2]*SU3F[3, I2, k1]*
     SU3F[I3, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3D[I3, k2, k3]*SU3F[6, I1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, k2, k3]*SU3F[I1, I3, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 3*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I3, k3]*SU3F[I1, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*Sqrt[3]*SU3F[6, k2, k3]*SU3F[I1, I3, k2]*SU3F[I2, k1, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*Sqrt[3]*SU3F[6, I3, k2]*
     SU3F[I1, k2, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k3]*SU3F[I3, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 12*Sqrt[3]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 3*Sqrt[3]*SU3D[I1, I3, k1]*
     SU3D[I2, k2, k3]*SU3F[6, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, k1, k3]*SU3F[I1, I3, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 3*Sqrt[3]*SU3D[6, I3, k1]*
     SU3D[I2, k2, k3]*SU3F[I1, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I3, k3]*SU3F[I1, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 6*I*Sqrt[3]*SU3D[I1, I3, k1]*
     SU3F[6, k1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*I*Sqrt[3]*SU3D[6, I3, k1]*SU3F[I1, k1, k3]*SU3F[I2, k2, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 6*I*Sqrt[3]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I3, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    3*Sqrt[3]*SU3D[I1, I3, k1]*SU3D[I2, k2, k3]*SU3F[6, k1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 3*Sqrt[3]*SU3D[6, I3, k1]*
     SU3D[I2, k2, k3]*SU3F[I1, k1, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*Sqrt[3]*SU3D[6, k1, k2]*SU3D[I1, I3, k2]*SU3F[I2, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 12*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*I*Sqrt[3]*SU3D[I1, k1, k2]*SU3F[6, I3, k2]*SU3F[I2, k1, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] - 6*I*Sqrt[3]*SU3D[6, k1, k2]*
     SU3F[I1, I3, k2]*SU3F[I2, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    6*Sqrt[3]*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*SU3F[I2, k2, k3]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21] + 4*I*SUNDelta[6, I2]*SUNDelta[I1, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*I*SU3D[3, I2, k1]*SUNDelta[6, k1]*SUNDelta[I1, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    6*SU3F[3, I2, k1]*SUNDelta[6, k1]*SUNDelta[I1, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] + 
    2*I*Sqrt[3]*SU3D[6, I2, k1]*SUNDelta[8, k1]*SUNDelta[I1, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    2*Sqrt[3]*SU3F[6, I2, k1]*SUNDelta[8, k1]*SUNDelta[I1, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21] - 
    12*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 6*SU3F[6, I1, I3]*SUNDelta[3, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    12*SU3F[6, I1, I2]*SUNDelta[3, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 9*SU3F[3, k2, k3]*SU3F[I1, k1, k3]*
     SU3F[I2, I3, k2]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 9*SU3F[3, I2, k2]*SU3F[I1, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 9*I*SU3D[I2, I3, k1]*SU3F[3, k1, k3]*
     SU3F[I1, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 18*I*SU3D[3, I3, k1]*SU3F[I1, k2, k3]*
     SU3F[I2, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 9*I*SU3D[3, I2, k1]*SU3F[I1, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 9*SU3D[3, k1, k2]*SU3D[I2, I3, k2]*
     SU3F[I1, k1, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 18*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 9*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 9*I*SU3D[I3, k1, k2]*SU3F[3, I2, k1]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 9*I*SU3D[3, k1, k2]*SU3F[I1, k2, k3]*
     SU3F[I2, I3, k1]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 2*Sqrt[3]*SU3F[6, I1, I3]*
     SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 4*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    3*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 3*Sqrt[3]*SU3F[6, I1, k2]*
     SU3F[I2, I3, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    3*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    3*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k3]*SU3F[I3, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] - 3*I*Sqrt[3]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    6*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*Sqrt[3]*SU3D[I2, I3, k1]*
     SU3D[k1, k2, k3]*SU3F[6, I1, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    3*I*Sqrt[3]*SU3D[k1, k2, k3]*SU3F[6, I1, k2]*SU3F[I2, I3, k1]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22] + 3*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    6*SU3F[3, I1, k1]*SUNDelta[6, k1]*SUNDelta[I2, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] + 
    2*Sqrt[3]*SU3F[6, I1, k1]*SUNDelta[8, k1]*SUNDelta[I2, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22] - 
    24*SU3D[I2, I3, k1]*SU3F[6, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 12*SU3F[6, I1, I3]*SUNDelta[3, I2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    24*SU3F[6, I1, I2]*SUNDelta[3, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 18*SU3F[3, k2, k3]*SU3F[I1, k1, k3]*
     SU3F[I2, I3, k2]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 18*SU3F[3, I2, k2]*SU3F[I1, k1, k3]*
     SU3F[I3, k2, k3]*SUNDelta[6, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 18*I*SU3D[I2, I3, k1]*SU3F[3, k1, k3]*
     SU3F[I1, k2, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 36*I*SU3D[3, I3, k1]*SU3F[I1, k2, k3]*
     SU3F[I2, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 18*I*SU3D[3, I2, k1]*SU3F[I1, k2, k3]*
     SU3F[I3, k1, k3]*SUNDelta[6, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 18*SU3D[3, k1, k2]*SU3D[I2, I3, k2]*
     SU3F[I1, k1, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 36*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 18*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 18*I*SU3D[I3, k1, k2]*SU3F[3, I2, k1]*
     SU3F[I1, k2, k3]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 18*I*SU3D[3, k1, k2]*SU3F[I1, k2, k3]*
     SU3F[I2, I3, k1]*SUNDelta[6, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 4*Sqrt[3]*SU3F[6, I1, I3]*
     SUNDelta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 8*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I2, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    6*Sqrt[3]*SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SU3F[I3, k2, k3]*
     SUNDelta[8, k1]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 6*Sqrt[3]*SU3F[6, I1, k2]*
     SU3F[I2, I3, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k1]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    6*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k3]*SU3F[I2, k1, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    6*I*Sqrt[3]*SU3D[I2, k1, k2]*SU3F[6, I1, k3]*SU3F[I3, k1, k3]*
     SUNDelta[8, k2]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] - 6*I*Sqrt[3]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k3]*SU3F[k1, k2, k3]*SUNDelta[8, k2]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    12*Sqrt[3]*SU3D[I2, k1, k2]*SU3D[I3, k1, k3]*SU3F[6, I1, k2]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*Sqrt[3]*SU3D[I2, I3, k1]*
     SU3D[k1, k2, k3]*SU3F[6, I1, k2]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    6*I*Sqrt[3]*SU3D[k1, k2, k3]*SU3F[6, I1, k2]*SU3F[I2, I3, k1]*
     SUNDelta[8, k3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23] + 6*I*Sqrt[3]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2]*SU3F[I2, k1, k3]*SUNDelta[8, k3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] - 
    12*SU3F[3, I1, k1]*SUNDelta[6, k1]*SUNDelta[I2, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    4*Sqrt[3]*SU3F[6, I1, k1]*SUNDelta[8, k1]*SUNDelta[I2, I3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23] + 
    72*SU3F[6, I1, I2]*SUNDelta[3, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 24] + 24*Sqrt[3]*SU3F[6, I1, I2]*
     SUNDelta[8, I3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 24])/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}}
