{{(2*(-6*SU3D[6, I1, k1]*SU3D[I2, I3, k1] - 6*I*SU3D[I2, I3, k1]*
      SU3F[6, I1, k1] + 3*I*SU3D[I1, I3, k1]*SU3F[6, I2, k1] + 
     3*I*SU3D[I1, I2, k1]*SU3F[6, I3, k1] + 3*SU3D[6, I3, k1]*
      (SU3D[I1, I2, k1] - I*SU3F[I1, I2, k1]) + 3*SU3F[6, I3, k1]*
      SU3F[I1, I2, k1] + 3*SU3D[6, I2, k1]*(SU3D[I1, I3, k1] - 
       I*SU3F[I1, I3, k1]) + 3*SU3F[6, I2, k1]*SU3F[I1, I3, k1] + 
     2*SU3Delta[6, I3]*SU3Delta[I1, I2] + 2*SU3Delta[6, I2]*
      SU3Delta[I1, I3] - 4*SU3Delta[6, I1]*SU3Delta[I2, I3])*
    UCouplingConstant[ChPTW3[2], 2])/(3*DecayConstant[PseudoScalar[1], 
     RenormalizationState[0]])}}
