{{(-8*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 20]*
    SU3D[I2, I3, k1]*SU3F[6, I1, k1])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(-8*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 20]*
    SU3D[I2, I3, k1]*SU3F[6, I1, k1])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(2*((3*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[6, I3, k1]*SU3D[I1, I2, k1] + (3*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3D[6, I3, k1]*SU3D[I1, I2, k1] - 
     (3*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[6, I2, k1]*SU3D[I1, I3, k1] - (3*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3D[6, I2, k1]*SU3D[I1, I3, k1] + 
     3*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[I1, I3, k1]*SU3F[6, I2, k1] + 3*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3D[I1, I3, k1]*SU3F[6, I2, k1] - 
     3*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[I1, I2, k1]*SU3F[6, I3, k1] - 3*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3D[I1, I2, k1]*SU3F[6, I3, k1] + 
     3*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[6, I3, k1]*SU3F[I1, I2, k1] - 3*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3D[6, I3, k1]*SU3F[I1, I2, k1] + 
     (3*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3F[6, I3, k1]*SU3F[I1, I2, k1] - (3*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3F[6, I3, k1]*SU3F[I1, I2, k1] - 
     3*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[6, I2, k1]*SU3F[I1, I3, k1] + 3*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3D[6, I2, k1]*SU3F[I1, I3, k1] - 
     (3*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3F[6, I2, k1]*SU3F[I1, I3, k1] + (3*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3F[6, I2, k1]*SU3F[I1, I3, k1] + 
     6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[6, I1, k1]*SU3F[I2, I3, k1] + (6*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 16]*SU3F[6, I1, k1]*SU3F[I2, I3, k1] + 
     (2*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SUNDelta[6, I3]*SUNDelta[I1, I2] + (2*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SUNDelta[6, I3]*SUNDelta[I1, I2] - 
     (2*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SUNDelta[6, I2]*SUNDelta[I1, I3] - (2*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SUNDelta[6, I2]*SUNDelta[I1, I3]))/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {(2*((-3*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[6, I3, k1]*SU3D[I1, I2, k1] - (3*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3D[6, I3, k1]*SU3D[I1, I2, k1] + 
     (3*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[6, I2, k1]*SU3D[I1, I3, k1] + (3*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3D[6, I2, k1]*SU3D[I1, I3, k1] - 
     3*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[I1, I3, k1]*SU3F[6, I2, k1] - 3*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3D[I1, I3, k1]*SU3F[6, I2, k1] + 
     3*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[I1, I2, k1]*SU3F[6, I3, k1] + 3*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3D[I1, I2, k1]*SU3F[6, I3, k1] - 
     3*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[6, I3, k1]*SU3F[I1, I2, k1] + 3*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3D[6, I3, k1]*SU3F[I1, I2, k1] - 
     (3*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3F[6, I3, k1]*SU3F[I1, I2, k1] + (3*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3F[6, I3, k1]*SU3F[I1, I2, k1] + 
     3*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[6, I2, k1]*SU3F[I1, I3, k1] - 3*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3D[6, I2, k1]*SU3F[I1, I3, k1] + 
     (3*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3F[6, I2, k1]*SU3F[I1, I3, k1] - (3*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SU3F[6, I2, k1]*SU3F[I1, I3, k1] - 
     6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SU3D[6, I1, k1]*SU3F[I2, I3, k1] - (6*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 16]*SU3F[6, I1, k1]*SU3F[I2, I3, k1] - 
     (2*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SUNDelta[6, I3]*SUNDelta[I1, I2] - (2*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SUNDelta[6, I3]*SUNDelta[I1, I2] + 
     (2*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 16]*
      SUNDelta[6, I2]*SUNDelta[I1, I3] + (2*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 17]*SUNDelta[6, I2]*SUNDelta[I1, I3]))/
   (3*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {((24*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I3, k1]*SU3D[I1, I2, k1] + (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, k1, k2]*SU3D[6, I3, k1]*
     SU3D[I1, I2, k2] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I3, k1]*SU3D[8, k1, k2]*
     SU3D[I1, I2, k2] - (12*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I2, k1]*SU3D[I1, I3, k1] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[6, k1, k2]*SU3D[8, I2, k2]*SU3D[I1, I3, k1] + 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[6, k1, k2]*SU3D[8, I2, k1]*SU3D[I1, I3, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I3, k1]*SU3D[6, I2, k2]*SU3D[I1, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[6, I2, k1]*SU3D[8, I3, k2]*SU3D[I1, k1, k2] - 
    (12*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I1, k1]*SU3D[I2, I3, k1] - (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I3, k1]*SU3D[6, I1, k2]*
     SU3D[I2, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I1, k1]*SU3D[8, I3, k2]*
     SU3D[I2, k1, k2] + (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, 6, k1]*SU3D[I1, I2, k2]*
     SU3D[I3, k1, k2] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, 8, k1]*SU3D[I1, I2, k2]*
     SU3D[I3, k1, k2] + 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[3, 6, k2] - 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, k1, k2]*SU3D[I1, I3, k2]*
     SU3F[3, I2, k1] + 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[3, I2, k2] + 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*
     SU3F[3, k1, k2] + 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, 8, k2] + 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 24*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 
    9*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[3, k1, k2]*SU3D[I2, I3, k1]*SU3F[6, I1, k2] - 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[3, k1, k2]*SU3D[I2, I3, k1]*SU3F[6, I1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[8, k1, k2]*SU3D[I2, I3, k1]*SU3F[6, I1, k2] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[8, k1, k2]*SU3D[I2, I3, k1]*SU3F[6, I1, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] - 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[3, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[3, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] - 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[8, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[8, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[8, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] - 
    9*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[3, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] - 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[3, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[8, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[8, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[I3, k1, k2]*SU3F[3, I2, k1]*SU3F[6, I1, k2] - 
    (9*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[I3, k1, k2]*SU3F[3, I2, k1]*SU3F[6, I1, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[I3, k1, k2]*SU3F[3, I2, k1]*SU3F[6, I1, k2] - 
    (9*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[I2, I3, k1]*SU3F[3, k1, k2]*SU3F[6, I1, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[I2, I3, k1]*SU3F[3, k1, k2]*SU3F[6, I1, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I3, k1]*SU3F[6, I2, k1] + 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[6, I2, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[8, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[6, I2, k2] - 48*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[I1, I2, k1]*SU3F[6, I3, k1] - 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 8]*
     SU3D[I1, I2, k1]*SU3F[6, I3, k1] - 24*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I2, k1]*SU3F[6, I3, k1] - 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, k1, k2]*SU3D[I1, I2, k1]*SU3F[6, I3, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, k1, k2]*SU3D[I1, I2, k1]*SU3F[6, I3, k2] + 
    24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[8, k1, k2]*SU3D[I1, I2, k1]*SU3F[6, I3, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[8, k1, k2]*SU3D[I1, I2, k1]*SU3F[6, I3, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, I2, k1]*SU3D[I1, k1, k2]*SU3F[6, I3, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[8, I2, k1]*SU3D[I1, k1, k2]*SU3F[6, I3, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, I1, k1]*SU3D[I2, k1, k2]*SU3F[6, I3, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[8, I1, k1]*SU3D[I2, k1, k2]*SU3F[6, I3, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[I2, k1, k2]*SU3F[3, I1, k1]*SU3F[6, I3, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[I1, k1, k2]*SU3F[3, I2, k1]*SU3F[6, I3, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[I1, k1, k2]*SU3F[3, I2, k1]*SU3F[6, I3, k2] - 
    (72*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[I1, I2, k1]*SU3F[3, k1, k2]*SU3F[6, I3, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I2, k1]*SU3F[3, k1, k2]*SU3F[6, I3, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[I1, I3, k1]*SU3F[3, I2, k2]*SU3F[6, k1, k2] - 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      5]*SU3D[I2, k1, k2]*SU3F[6, I3, k2]*SU3F[8, I1, k1] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, k1, k2]*SU3D[I1, I3, k2]*SU3F[8, I2, k1] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I2, k1] + 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      22]*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I2, k1] + 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      23]*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I2, k1] - 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      5]*SU3D[I1, k1, k2]*SU3F[6, I3, k2]*SU3F[8, I2, k1] + 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[I1, k1, k2]*SU3F[6, I3, k2]*SU3F[8, I2, k1] - 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, I3, k1]*SU3D[I1, k1, k2]*SU3F[8, I2, k2] - 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[I1, I3, k1]*SU3F[6, k1, k2]*SU3F[8, I2, k2] - 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I3, k1]*SU3D[I1, I2, k2]*SU3F[8, k1, k2] + 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      22]*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*SU3F[8, k1, k2] + 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      23]*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*SU3F[8, k1, k2] + 
    (24*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      5]*SU3D[I1, I2, k1]*SU3F[6, I3, k2]*SU3F[8, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[I1, I2, k1]*SU3F[6, I3, k2]*SU3F[8, k1, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I2, k1]*SU3F[I1, I3, k1] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 21]*SU3D[6, k1, k2]*SU3D[8, I2, k2]*
     SU3F[I1, I3, k1] + (12*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3F[6, I2, k1]*SU3F[I1, I3, k1] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, k1, k2]*SU3D[8, I2, k1]*SU3F[I1, I3, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, k1, k2]*SU3F[3, I2, k1]*SU3F[I1, I3, k2] - 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[3, I2, k1]*SU3F[6, k1, k2]*SU3F[I1, I3, k2] - 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[6, k1, k2]*SU3F[8, I2, k1]*SU3F[I1, I3, k2] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[6, k1, k2]*SU3F[8, I2, k1]*SU3F[I1, I3, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I3, k1]*SU3D[6, I2, k2]*SU3F[I1, k1, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I2, k1]*SU3D[8, I3, k2]*SU3F[I1, k1, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, I3, k1]*SU3F[3, I2, k2]*SU3F[I1, k1, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I3, k1]*SU3F[6, I2, k2]*SU3F[I1, k1, k2] - 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[8, I3, k1]*SU3F[6, I2, k2]*SU3F[I1, k1, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, I2, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      5]*SU3D[8, I2, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[3, I2, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] + 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[3, I2, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] + 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[6, I3, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] - 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[6, I3, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[6, I3, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I1, k1]*SU3F[I2, I3, k1] + (12*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3F[6, I1, k1]*SU3F[I2, I3, k1] + 
    (9*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[3, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[3, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      22]*SU3D[8, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1] - 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      23]*SU3D[8, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1] + 
    9*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[3, k1, k2]*SU3F[6, I1, k1]*SU3F[I2, I3, k2] + 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[3, k1, k2]*SU3F[6, I1, k1]*SU3F[I2, I3, k2] - 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[6, I1, k1]*SU3F[8, k1, k2]*SU3F[I2, I3, k2] - 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, k1]*SU3F[8, k1, k2]*SU3F[I2, I3, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I3, k1]*SU3D[6, I1, k2]*SU3F[I2, k1, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I1, k1]*SU3D[8, I3, k2]*SU3F[I2, k1, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[3, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[3, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] + 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      22]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      23]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, I1, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      5]*SU3D[8, I1, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[3, I1, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2] - 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[6, I3, k1]*SU3F[8, I1, k2]*SU3F[I2, k1, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, 6, k1]*SU3D[I1, I2, k2]*SU3F[I3, k1, k2] - 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, 8, k1]*SU3D[I1, I2, k2]*SU3F[I3, k1, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I2, k1]*SU3F[3, 6, k2]*SU3F[I3, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[I1, I2, k1]*SU3F[6, 8, k2]*SU3F[I3, k1, k2] - 
    (9*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[3, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[3, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] + 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      22]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] + 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      23]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[3, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] + 
    9*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[3, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] + 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[3, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[6, I1, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[6, I1, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] + 
    24*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[6, I2, I3]*SUNDelta[3, I1] + 72*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6]*SU3F[6, I2, I3]*SUNDelta[3, I1] + 
    24*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[6, I1, I3]*SUNDelta[3, I2] + 72*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6]*SU3F[6, I1, I3]*SUNDelta[3, I2] - 
    6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[6, I1, I3]*SUNDelta[3, I2] - 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[6, I1, I3]*SUNDelta[3, I2] - 
    (48*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I1, I2]*SUNDelta[3, I3] - 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, I2]*SUNDelta[3, I3] - 
    24*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, I2]*SUNDelta[3, I3] - 72*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 24]*SU3F[6, I1, I2]*SUNDelta[3, I3] - 
    (24*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I2, I3]*SUNDelta[6, I1] + (8*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[8, I2, I3]*SUNDelta[6, I1] - (24*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I1, I3]*SUNDelta[6, I2] + 
    (8*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[8, I1, I3]*SUNDelta[6, I2] + 
    (24*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I1, I2]*SUNDelta[6, I3] - (8*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[8, I1, I2]*SUNDelta[6, I3] - 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, I1, I2]*SUNDelta[6, I3] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[8, I1, I2]*SUNDelta[6, I3] - 8*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 5]*SU3F[6, I2, I3]*SUNDelta[8, I1] - 
    24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*
     SU3F[6, I2, I3]*SUNDelta[8, I1] - 8*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 5]*SU3F[6, I1, I3]*SUNDelta[8, I2] - 
    24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*
     SU3F[6, I1, I3]*SUNDelta[8, I2] + 2*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, I3]*SUNDelta[8, I2] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, I3]*SUNDelta[8, I2] + (16*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I1, I2]*SUNDelta[8, I3] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, I2]*SUNDelta[8, I3] + 
    8*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, I2]*SUNDelta[8, I3] + 24*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 24]*SU3F[6, I1, I2]*SUNDelta[8, I3] + 
    (16*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SUNDelta[6, I3]*SUNDelta[I1, I2] + 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, 6, I2]*SUNDelta[I1, I3] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[6, 8, I2]*SUNDelta[I1, I3] - (8*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SUNDelta[6, I2]*SUNDelta[I1, I3] - 
    6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[3, 6, I1]*SUNDelta[I2, I3] - 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[3, 6, I1]*SUNDelta[I2, I3] - 
    2*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[6, 8, I1]*SUNDelta[I2, I3] - 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 23]*SU3F[6, 8, I1]*SUNDelta[I2, I3] - 
    (8*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SUNDelta[6, I1]*SUNDelta[I2, I3])/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {((-12*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I3, k1]*SU3D[I1, I2, k1] - (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, k1, k2]*SU3D[8, I3, k2]*SU3D[I1, I2, k1] + 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[6, k1, k2]*SU3D[8, I3, k1]*SU3D[I1, I2, k2] + 
    (24*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I2, k1]*SU3D[I1, I3, k1] + (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, k1, k2]*SU3D[6, I2, k1]*
     SU3D[I1, I3, k2] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I2, k1]*SU3D[8, k1, k2]*
     SU3D[I1, I3, k2] - (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3D[6, I3, k2]*
     SU3D[I1, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I3, k1]*SU3D[8, I2, k2]*
     SU3D[I1, k1, k2] - (12*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I1, k1]*SU3D[I2, I3, k1] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, 6, k1]*SU3D[I1, I3, k2]*SU3D[I2, k1, k2] - 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[6, 8, k1]*SU3D[I1, I3, k2]*SU3D[I2, k1, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I2, k1]*SU3D[6, I1, k2]*SU3D[I3, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[6, I1, k1]*SU3D[8, I2, k2]*SU3D[I3, k1, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I3, k1]*SU3D[I2, k1, k2]*SU3F[3, 6, k2] - 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, k1, k2]*SU3D[I1, I2, k2]*SU3F[3, I3, k1] + 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3F[3, I3, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3F[3, k1, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, 8, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 
    24*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 9*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[3, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k2] - 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[3, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[8, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[8, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k2] - 9*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2] - 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[8, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[8, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2] + 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] - 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] - 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[8, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[8, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] + 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[8, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] - (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[I2, k1, k2]*SU3F[3, I3, k1]*
     SU3F[6, I1, k2] - (9*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[I2, k1, k2]*SU3F[3, I3, k1]*
     SU3F[6, I1, k2] - (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[I2, k1, k2]*SU3F[3, I3, k1]*
     SU3F[6, I1, k2] - (9*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[I2, I3, k1]*SU3F[3, k1, k2]*
     SU3F[6, I1, k2] - (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[I2, I3, k1]*SU3F[3, k1, k2]*
     SU3F[6, I1, k2] - 48*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[I1, I3, k1]*SU3F[6, I2, k1] - 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 8]*
     SU3D[I1, I3, k1]*SU3F[6, I2, k1] - 24*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I3, k1]*SU3F[6, I2, k1] - 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, k1, k2]*SU3D[I1, I3, k1]*SU3F[6, I2, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, k1, k2]*SU3D[I1, I3, k1]*SU3F[6, I2, k2] + 
    24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[8, k1, k2]*SU3D[I1, I3, k1]*SU3F[6, I2, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[8, k1, k2]*SU3D[I1, I3, k1]*SU3F[6, I2, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, I3, k1]*SU3D[I1, k1, k2]*SU3F[6, I2, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[8, I3, k1]*SU3D[I1, k1, k2]*SU3F[6, I2, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, I1, k1]*SU3D[I3, k1, k2]*SU3F[6, I2, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[8, I1, k1]*SU3D[I3, k1, k2]*SU3F[6, I2, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[I3, k1, k2]*SU3F[3, I1, k1]*SU3F[6, I2, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[I1, k1, k2]*SU3F[3, I3, k1]*SU3F[6, I2, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[I1, k1, k2]*SU3F[3, I3, k1]*SU3F[6, I2, k2] - 
    (72*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[I1, I3, k1]*SU3F[3, k1, k2]*SU3F[6, I2, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I3, k1]*SU3F[3, k1, k2]*SU3F[6, I2, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I2, k1]*SU3F[6, I3, k1] + 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*
     SU3F[6, I3, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[8, I2, k1]*SU3D[I1, k1, k2]*
     SU3F[6, I3, k2] + (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[I1, I2, k1]*SU3F[3, I3, k2]*
     SU3F[6, k1, k2] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[I3, k1, k2]*SU3F[6, I2, k2]*
     SU3F[8, I1, k1] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, k1, k2]*SU3D[I1, I2, k2]*
     SU3F[8, I3, k1] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*
     SU3F[8, I3, k1] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*
     SU3F[8, I3, k1] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*
     SU3F[8, I3, k1] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*
     SU3F[8, I3, k1] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*
     SU3F[8, I3, k1] - 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, I2, k1]*SU3D[I1, k1, k2]*
     SU3F[8, I3, k2] - (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[I1, I2, k1]*SU3F[6, k1, k2]*
     SU3F[8, I3, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*
     SU3F[8, k1, k2] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*
     SU3F[8, k1, k2] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*
     SU3F[8, k1, k2] + (24*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[I1, I3, k1]*SU3F[6, I2, k2]*
     SU3F[8, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I3, k1]*SU3F[6, I2, k2]*
     SU3F[8, k1, k2] + 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I3, k1]*SU3F[I1, I2, k1] - 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, k1, k2]*SU3D[8, I3, k2]*SU3F[I1, I2, k1] + 
    (12*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3F[6, I3, k1]*SU3F[I1, I2, k1] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 21]*SU3D[6, k1, k2]*SU3D[8, I3, k1]*
     SU3F[I1, I2, k2] + (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, k1, k2]*SU3F[3, I3, k1]*
     SU3F[I1, I2, k2] - 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, I3, k1]*SU3F[6, k1, k2]*
     SU3F[I1, I2, k2] - (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, k1, k2]*SU3F[8, I3, k1]*
     SU3F[I1, I2, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[6, k1, k2]*SU3F[8, I3, k1]*
     SU3F[I1, I2, k2] + 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3D[6, I3, k2]*
     SU3F[I1, k1, k2] + 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I3, k1]*SU3D[8, I2, k2]*
     SU3F[I1, k1, k2] - (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, I2, k1]*SU3F[3, I3, k2]*
     SU3F[I1, k1, k2] - (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[3, I3, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[8, I3, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2] - 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3F[3, I3, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2] + 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, I3, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2] + (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3F[6, I3, k2]*
     SU3F[I1, k1, k2] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[8, I2, k1]*SU3F[6, I3, k2]*
     SU3F[I1, k1, k2] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, I2, k1]*SU3F[8, I3, k2]*
     SU3F[I1, k1, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3F[6, I2, k1]*SU3F[8, I3, k2]*
     SU3F[I1, k1, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[6, I2, k1]*SU3F[8, I3, k2]*
     SU3F[I1, k1, k2] - 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I1, k1]*SU3F[I2, I3, k1] - 
    (12*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3F[6, I1, k1]*SU3F[I2, I3, k1] - (9*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[3, k1, k2]*SU3F[6, I1, k2]*
     SU3F[I2, I3, k1] - (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[3, k1, k2]*SU3F[6, I1, k2]*
     SU3F[I2, I3, k1] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[8, k1, k2]*SU3F[6, I1, k2]*
     SU3F[I2, I3, k1] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[8, k1, k2]*SU3F[6, I1, k2]*
     SU3F[I2, I3, k1] - 9*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[3, k1, k2]*SU3F[6, I1, k1]*
     SU3F[I2, I3, k2] - 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[3, k1, k2]*SU3F[6, I1, k1]*
     SU3F[I2, I3, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, k1]*SU3F[8, k1, k2]*
     SU3F[I2, I3, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[6, I1, k1]*SU3F[8, k1, k2]*
     SU3F[I2, I3, k2] + 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, 6, k1]*SU3D[I1, I3, k2]*
     SU3F[I2, k1, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, 8, k1]*SU3D[I1, I3, k2]*
     SU3F[I2, k1, k2] + (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I3, k1]*SU3F[3, 6, k2]*
     SU3F[I2, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I3, k1]*SU3F[6, 8, k2]*
     SU3F[I2, k1, k2] - (9*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[3, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] - (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[3, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] + 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] + 9*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[3, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] + 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[3, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] + 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[6, I1, k1]*SU3F[8, I3, k2]*
     SU3F[I2, k1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, k1]*SU3F[8, I3, k2]*
     SU3F[I2, k1, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[6, I1, k1]*SU3F[8, I3, k2]*
     SU3F[I2, k1, k2] + 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3D[6, I1, k2]*
     SU3F[I3, k1, k2] + 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I1, k1]*SU3D[8, I2, k2]*
     SU3F[I3, k1, k2] + (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] - (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[3, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] - (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[3, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] - (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[3, I1, k1]*SU3F[6, I2, k2]*
     SU3F[I3, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[8, I1, k1]*SU3F[6, I2, k2]*
     SU3F[I3, k1, k2] - 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3F[3, I1, k1]*SU3F[6, I2, k2]*
     SU3F[I3, k1, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3F[6, I2, k1]*SU3F[8, I1, k2]*
     SU3F[I3, k1, k2] - 24*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3F[6, I2, I3]*SUNDelta[3, I1] - 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*
     SU3F[6, I2, I3]*SUNDelta[3, I1] - (48*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I1, I3]*SUNDelta[3, I2] - 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[6, I1, I3]*SUNDelta[3, I2] - 24*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[6, I1, I3]*SUNDelta[3, I2] - 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 24]*
     SU3F[6, I1, I3]*SUNDelta[3, I2] + 24*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3F[6, I1, I2]*SUNDelta[3, I3] + 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*
     SU3F[6, I1, I2]*SUNDelta[3, I3] - 6*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, I2]*SUNDelta[3, I3] - 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, I2]*SUNDelta[3, I3] - (24*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, I3]*SUNDelta[6, I1] + 
    (8*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[8, I2, I3]*SUNDelta[6, I1] + 
    (24*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I1, I3]*SUNDelta[6, I2] - (8*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[8, I1, I3]*SUNDelta[6, I2] - 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, I1, I3]*SUNDelta[6, I2] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[8, I1, I3]*SUNDelta[6, I2] - (24*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I1, I2]*SUNDelta[6, I3] + 
    (8*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[8, I1, I2]*SUNDelta[6, I3] + 
    8*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[6, I2, I3]*SUNDelta[8, I1] + 24*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 6]*SU3F[6, I2, I3]*SUNDelta[8, I1] + 
    (16*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[6, I1, I3]*SUNDelta[8, I2] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[6, I1, I3]*SUNDelta[8, I2] + 8*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 23]*SU3F[6, I1, I3]*SUNDelta[8, I2] + 
    24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 24]*
     SU3F[6, I1, I3]*SUNDelta[8, I2] - 8*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 5]*SU3F[6, I1, I2]*SUNDelta[8, I3] - 
    24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*
     SU3F[6, I1, I2]*SUNDelta[8, I3] + 2*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, I2]*SUNDelta[8, I3] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, I2]*SUNDelta[8, I3] + 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, 6, I3]*SUNDelta[I1, I2] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[6, 8, I3]*SUNDelta[I1, I2] - (8*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SUNDelta[6, I3]*SUNDelta[I1, I2] + 
    (16*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SUNDelta[6, I2]*SUNDelta[I1, I3] - 6*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[3, 6, I1]*SUNDelta[I2, I3] - 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[3, 6, I1]*SUNDelta[I2, I3] - 2*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 22]*SU3F[6, 8, I1]*SUNDelta[I2, I3] - 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, 8, I1]*SUNDelta[I2, I3] - (8*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SUNDelta[6, I1]*SUNDelta[I2, I3])/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {((24*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I3, k1]*SU3D[I1, I2, k1] - (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, k1, k2]*SU3D[6, I3, k1]*
     SU3D[I1, I2, k2] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I3, k1]*SU3D[8, k1, k2]*
     SU3D[I1, I2, k2] - (12*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I2, k1]*SU3D[I1, I3, k1] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[6, k1, k2]*SU3D[8, I2, k2]*SU3D[I1, I3, k1] + 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[6, k1, k2]*SU3D[8, I2, k1]*SU3D[I1, I3, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I3, k1]*SU3D[6, I2, k2]*SU3D[I1, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[6, I2, k1]*SU3D[8, I3, k2]*SU3D[I1, k1, k2] - 
    (12*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I1, k1]*SU3D[I2, I3, k1] + (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I3, k1]*SU3D[6, I1, k2]*
     SU3D[I2, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I1, k1]*SU3D[8, I3, k2]*
     SU3D[I2, k1, k2] - (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, 6, k1]*SU3D[I1, I2, k2]*
     SU3D[I3, k1, k2] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, 8, k1]*SU3D[I1, I2, k2]*
     SU3D[I3, k1, k2] - 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[3, 6, k2] + 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, k1, k2]*SU3D[I1, I3, k2]*
     SU3F[3, I2, k1] - 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[3, I2, k2] - 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I3, k1]*SU3D[I1, I2, k2]*
     SU3F[3, k1, k2] + 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, 8, k2] + 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 24*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[I2, I3, k1]*SU3F[6, I1, k1] + 
    9*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[3, k1, k2]*SU3D[I2, I3, k1]*SU3F[6, I1, k2] + 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[3, k1, k2]*SU3D[I2, I3, k1]*SU3F[6, I1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[8, k1, k2]*SU3D[I2, I3, k1]*SU3F[6, I1, k2] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[8, k1, k2]*SU3D[I2, I3, k1]*SU3F[6, I1, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] + 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[3, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[3, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] - 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[8, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[8, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[8, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] + 
    9*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[3, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] + 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[3, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[8, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[8, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[I3, k1, k2]*SU3F[3, I2, k1]*SU3F[6, I1, k2] + 
    (9*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[I3, k1, k2]*SU3F[3, I2, k1]*SU3F[6, I1, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[I3, k1, k2]*SU3F[3, I2, k1]*SU3F[6, I1, k2] + 
    (9*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[I2, I3, k1]*SU3F[3, k1, k2]*SU3F[6, I1, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[I2, I3, k1]*SU3F[3, k1, k2]*SU3F[6, I1, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I3, k1]*SU3F[6, I2, k1] - 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[6, I2, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[8, I3, k1]*SU3D[I1, k1, k2]*
     SU3F[6, I2, k2] - 48*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[I1, I2, k1]*SU3F[6, I3, k1] - 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 8]*
     SU3D[I1, I2, k1]*SU3F[6, I3, k1] - 24*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I2, k1]*SU3F[6, I3, k1] + 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, k1, k2]*SU3D[I1, I2, k1]*SU3F[6, I3, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, k1, k2]*SU3D[I1, I2, k1]*SU3F[6, I3, k2] + 
    24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[8, k1, k2]*SU3D[I1, I2, k1]*SU3F[6, I3, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[8, k1, k2]*SU3D[I1, I2, k1]*SU3F[6, I3, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, I2, k1]*SU3D[I1, k1, k2]*SU3F[6, I3, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[8, I2, k1]*SU3D[I1, k1, k2]*SU3F[6, I3, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, I1, k1]*SU3D[I2, k1, k2]*SU3F[6, I3, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[8, I1, k1]*SU3D[I2, k1, k2]*SU3F[6, I3, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[I2, k1, k2]*SU3F[3, I1, k1]*SU3F[6, I3, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[I1, k1, k2]*SU3F[3, I2, k1]*SU3F[6, I3, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[I1, k1, k2]*SU3F[3, I2, k1]*SU3F[6, I3, k2] + 
    (72*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[I1, I2, k1]*SU3F[3, k1, k2]*SU3F[6, I3, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I2, k1]*SU3F[3, k1, k2]*SU3F[6, I3, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[I1, I3, k1]*SU3F[3, I2, k2]*SU3F[6, k1, k2] - 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      5]*SU3D[I2, k1, k2]*SU3F[6, I3, k2]*SU3F[8, I1, k1] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, k1, k2]*SU3D[I1, I3, k2]*SU3F[8, I2, k1] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I2, k1] + 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      22]*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I2, k1] + 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      23]*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I2, k1] - 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      5]*SU3D[I1, k1, k2]*SU3F[6, I3, k2]*SU3F[8, I2, k1] + 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[I1, k1, k2]*SU3F[6, I3, k2]*SU3F[8, I2, k1] - 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, I3, k1]*SU3D[I1, k1, k2]*SU3F[8, I2, k2] - 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[I1, I3, k1]*SU3F[6, k1, k2]*SU3F[8, I2, k2] - 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I3, k1]*SU3D[I1, I2, k2]*SU3F[8, k1, k2] + 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      22]*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*SU3F[8, k1, k2] + 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      23]*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*SU3F[8, k1, k2] + 
    (24*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      5]*SU3D[I1, I2, k1]*SU3F[6, I3, k2]*SU3F[8, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[I1, I2, k1]*SU3F[6, I3, k2]*SU3F[8, k1, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I2, k1]*SU3F[I1, I3, k1] - 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 21]*SU3D[6, k1, k2]*SU3D[8, I2, k2]*
     SU3F[I1, I3, k1] + (12*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3F[6, I2, k1]*SU3F[I1, I3, k1] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, k1, k2]*SU3D[8, I2, k1]*SU3F[I1, I3, k2] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, k1, k2]*SU3F[3, I2, k1]*SU3F[I1, I3, k2] + 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[3, I2, k1]*SU3F[6, k1, k2]*SU3F[I1, I3, k2] - 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[6, k1, k2]*SU3F[8, I2, k1]*SU3F[I1, I3, k2] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[6, k1, k2]*SU3F[8, I2, k1]*SU3F[I1, I3, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I3, k1]*SU3D[6, I2, k2]*SU3F[I1, k1, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I2, k1]*SU3D[8, I3, k2]*SU3F[I1, k1, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, I3, k1]*SU3F[3, I2, k2]*SU3F[I1, k1, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I3, k1]*SU3F[6, I2, k2]*SU3F[I1, k1, k2] - 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[8, I3, k1]*SU3F[6, I2, k2]*SU3F[I1, k1, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, I2, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      5]*SU3D[8, I2, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[3, I2, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] - 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[3, I2, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] + 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[6, I3, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] - 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[6, I3, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[6, I3, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I1, k1]*SU3F[I2, I3, k1] + (12*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3F[6, I1, k1]*SU3F[I2, I3, k1] - 
    (9*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[3, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1] - 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[3, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1] - 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      22]*SU3D[8, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1] - 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      23]*SU3D[8, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1] - 
    9*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[3, k1, k2]*SU3F[6, I1, k1]*SU3F[I2, I3, k2] - 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[3, k1, k2]*SU3F[6, I1, k1]*SU3F[I2, I3, k2] - 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[6, I1, k1]*SU3F[8, k1, k2]*SU3F[I2, I3, k2] - 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, k1]*SU3F[8, k1, k2]*SU3F[I2, I3, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I3, k1]*SU3D[6, I1, k2]*SU3F[I2, k1, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I1, k1]*SU3D[8, I3, k2]*SU3F[I2, k1, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[3, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[3, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] + 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      22]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      23]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, I1, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      5]*SU3D[8, I1, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[3, I1, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2] - 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[6, I3, k1]*SU3F[8, I1, k2]*SU3F[I2, k1, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, 6, k1]*SU3D[I1, I2, k2]*SU3F[I3, k1, k2] - 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, 8, k1]*SU3D[I1, I2, k2]*SU3F[I3, k1, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I2, k1]*SU3F[3, 6, k2]*SU3F[I3, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[I1, I2, k1]*SU3F[6, 8, k2]*SU3F[I3, k1, k2] + 
    (9*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3D[3, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[3, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] + 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      22]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] + 
    (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      23]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[3, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 
    9*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[3, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[3, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[6, I1, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] + 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[6, I1, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] + 
    6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] - 
    24*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[6, I2, I3]*SUNDelta[3, I1] - 72*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6]*SU3F[6, I2, I3]*SUNDelta[3, I1] - 
    24*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[6, I1, I3]*SUNDelta[3, I2] - 72*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 6]*SU3F[6, I1, I3]*SUNDelta[3, I2] + 
    6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[6, I1, I3]*SUNDelta[3, I2] + 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[6, I1, I3]*SUNDelta[3, I2] + 
    (48*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I1, I2]*SUNDelta[3, I3] + 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, I2]*SUNDelta[3, I3] + 
    24*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, I2]*SUNDelta[3, I3] + 72*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 24]*SU3F[6, I1, I2]*SUNDelta[3, I3] + 
    (24*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I2, I3]*SUNDelta[6, I1] + (8*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[8, I2, I3]*SUNDelta[6, I1] + (24*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I1, I3]*SUNDelta[6, I2] + 
    (8*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[8, I1, I3]*SUNDelta[6, I2] - 
    (24*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I1, I2]*SUNDelta[6, I3] - (8*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[8, I1, I2]*SUNDelta[6, I3] + 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, I1, I2]*SUNDelta[6, I3] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[8, I1, I2]*SUNDelta[6, I3] - 8*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 5]*SU3F[6, I2, I3]*SUNDelta[8, I1] - 
    24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*
     SU3F[6, I2, I3]*SUNDelta[8, I1] - 8*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 5]*SU3F[6, I1, I3]*SUNDelta[8, I2] - 
    24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*
     SU3F[6, I1, I3]*SUNDelta[8, I2] + 2*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, I3]*SUNDelta[8, I2] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, I3]*SUNDelta[8, I2] + (16*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I1, I2]*SUNDelta[8, I3] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, I2]*SUNDelta[8, I3] + 
    8*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, I2]*SUNDelta[8, I3] + 24*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 24]*SU3F[6, I1, I2]*SUNDelta[8, I3] + 
    (16*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SUNDelta[6, I3]*SUNDelta[I1, I2] - 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, 6, I2]*SUNDelta[I1, I3] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[6, 8, I2]*SUNDelta[I1, I3] - (8*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SUNDelta[6, I2]*SUNDelta[I1, I3] + 
    6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[3, 6, I1]*SUNDelta[I2, I3] + 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[3, 6, I1]*SUNDelta[I2, I3] - 
    2*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[6, 8, I1]*SUNDelta[I2, I3] - 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 23]*SU3F[6, 8, I1]*SUNDelta[I2, I3] - 
    (8*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SUNDelta[6, I1]*SUNDelta[I2, I3])/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {((-12*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I3, k1]*SU3D[I1, I2, k1] - (3*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, k1, k2]*SU3D[8, I3, k2]*SU3D[I1, I2, k1] + 
    (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      21]*SU3D[6, k1, k2]*SU3D[8, I3, k1]*SU3D[I1, I2, k2] + 
    (24*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I2, k1]*SU3D[I1, I3, k1] - (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, k1, k2]*SU3D[6, I2, k1]*
     SU3D[I1, I3, k2] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I2, k1]*SU3D[8, k1, k2]*
     SU3D[I1, I3, k2] + (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3D[6, I3, k2]*
     SU3D[I1, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I3, k1]*SU3D[8, I2, k2]*
     SU3D[I1, k1, k2] - (12*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I1, k1]*SU3D[I2, I3, k1] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, 6, k1]*SU3D[I1, I3, k2]*SU3D[I2, k1, k2] - 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[6, 8, k1]*SU3D[I1, I3, k2]*SU3D[I2, k1, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I2, k1]*SU3D[6, I1, k2]*SU3D[I3, k1, k2] + 
    (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[6, I1, k1]*SU3D[8, I2, k2]*SU3D[I3, k1, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I3, k1]*SU3D[I2, k1, k2]*SU3F[3, 6, k2] + 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, k1, k2]*SU3D[I1, I2, k2]*SU3F[3, I3, k1] - 
    18*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3F[3, I3, k2] - 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3F[3, k1, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, 8, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 
    24*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3D[I2, I3, k1]*SU3F[6, I1, k1] + 9*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[3, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k2] + 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[3, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[8, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[8, k1, k2]*SU3D[I2, I3, k1]*
     SU3F[6, I1, k2] + 9*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2] + 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[3, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[8, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[8, I3, k1]*SU3D[I2, k1, k2]*
     SU3F[6, I1, k2] - 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] + 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] + 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[3, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[8, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[8, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] + 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[8, I2, k1]*SU3D[I3, k1, k2]*
     SU3F[6, I1, k2] + (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[I2, k1, k2]*SU3F[3, I3, k1]*
     SU3F[6, I1, k2] + (9*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[I2, k1, k2]*SU3F[3, I3, k1]*
     SU3F[6, I1, k2] + (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[I2, k1, k2]*SU3F[3, I3, k1]*
     SU3F[6, I1, k2] + (9*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[I2, I3, k1]*SU3F[3, k1, k2]*
     SU3F[6, I1, k2] + (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[I2, I3, k1]*SU3F[3, k1, k2]*
     SU3F[6, I1, k2] - 48*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[I1, I3, k1]*SU3F[6, I2, k1] - 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 8]*
     SU3D[I1, I3, k1]*SU3F[6, I2, k1] - 24*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I3, k1]*SU3F[6, I2, k1] + 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, k1, k2]*SU3D[I1, I3, k1]*SU3F[6, I2, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, k1, k2]*SU3D[I1, I3, k1]*SU3F[6, I2, k2] + 
    24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[8, k1, k2]*SU3D[I1, I3, k1]*SU3F[6, I2, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[8, k1, k2]*SU3D[I1, I3, k1]*SU3F[6, I2, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, I3, k1]*SU3D[I1, k1, k2]*SU3F[6, I2, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[8, I3, k1]*SU3D[I1, k1, k2]*SU3F[6, I2, k2] + 
    36*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[3, I1, k1]*SU3D[I3, k1, k2]*SU3F[6, I2, k2] + 
    12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[8, I1, k1]*SU3D[I3, k1, k2]*SU3F[6, I2, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[I3, k1, k2]*SU3F[3, I1, k1]*SU3F[6, I2, k2] - 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[I1, k1, k2]*SU3F[3, I3, k1]*SU3F[6, I2, k2] + 
    (18*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[I1, k1, k2]*SU3F[3, I3, k1]*SU3F[6, I2, k2] + 
    (72*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3D[I1, I3, k1]*SU3F[3, k1, k2]*SU3F[6, I2, k2] + 
    (36*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I3, k1]*SU3F[3, k1, k2]*SU3F[6, I2, k2] + 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[I1, I2, k1]*SU3F[6, I3, k1] - 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3D[I1, k1, k2]*
     SU3F[6, I3, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[8, I2, k1]*SU3D[I1, k1, k2]*
     SU3F[6, I3, k2] - (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[I1, I2, k1]*SU3F[3, I3, k2]*
     SU3F[6, k1, k2] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[I3, k1, k2]*SU3F[6, I2, k2]*
     SU3F[8, I1, k1] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, k1, k2]*SU3D[I1, I2, k2]*
     SU3F[8, I3, k1] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*
     SU3F[8, I3, k1] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*
     SU3F[8, I3, k1] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*
     SU3F[8, I3, k1] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*
     SU3F[8, I3, k1] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*
     SU3F[8, I3, k1] - 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, I2, k1]*SU3D[I1, k1, k2]*
     SU3F[8, I3, k2] - (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[I1, I2, k1]*SU3F[6, k1, k2]*
     SU3F[8, I3, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I2, k1]*SU3D[I1, I3, k2]*
     SU3F[8, k1, k2] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*
     SU3F[8, k1, k2] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*
     SU3F[8, k1, k2] + (24*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[I1, I3, k1]*SU3F[6, I2, k2]*
     SU3F[8, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I3, k1]*SU3F[6, I2, k2]*
     SU3F[8, k1, k2] + 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I3, k1]*SU3F[I1, I2, k1] - 
    3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3D[6, k1, k2]*SU3D[8, I3, k2]*SU3F[I1, I2, k1] + 
    (12*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3F[6, I3, k1]*SU3F[I1, I2, k1] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 21]*SU3D[6, k1, k2]*SU3D[8, I3, k1]*
     SU3F[I1, I2, k2] - (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, k1, k2]*SU3F[3, I3, k1]*
     SU3F[I1, I2, k2] + 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, I3, k1]*SU3F[6, k1, k2]*
     SU3F[I1, I2, k2] - (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, k1, k2]*SU3F[8, I3, k1]*
     SU3F[I1, I2, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[6, k1, k2]*SU3F[8, I3, k1]*
     SU3F[I1, I2, k2] - 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3D[6, I3, k2]*
     SU3F[I1, k1, k2] + 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I3, k1]*SU3D[8, I2, k2]*
     SU3F[I1, k1, k2] + (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, I2, k1]*SU3F[3, I3, k2]*
     SU3F[I1, k1, k2] + (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[3, I3, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[8, I3, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2] + 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3F[3, I3, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2] - 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, I3, k1]*SU3F[6, I2, k2]*
     SU3F[I1, k1, k2] - (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3F[6, I3, k2]*
     SU3F[I1, k1, k2] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[8, I2, k1]*SU3F[6, I3, k2]*
     SU3F[I1, k1, k2] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3D[6, I2, k1]*SU3F[8, I3, k2]*
     SU3F[I1, k1, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3F[6, I2, k1]*SU3F[8, I3, k2]*
     SU3F[I1, k1, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[6, I2, k1]*SU3F[8, I3, k2]*
     SU3F[I1, k1, k2] - 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I1, k1]*SU3F[I2, I3, k1] - 
    (12*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3F[6, I1, k1]*SU3F[I2, I3, k1] + (9*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[3, k1, k2]*SU3F[6, I1, k2]*
     SU3F[I2, I3, k1] + (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[3, k1, k2]*SU3F[6, I1, k2]*
     SU3F[I2, I3, k1] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[8, k1, k2]*SU3F[6, I1, k2]*
     SU3F[I2, I3, k1] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[8, k1, k2]*SU3F[6, I1, k2]*
     SU3F[I2, I3, k1] + 9*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[3, k1, k2]*SU3F[6, I1, k1]*
     SU3F[I2, I3, k2] + 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[3, k1, k2]*SU3F[6, I1, k1]*
     SU3F[I2, I3, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, k1]*SU3F[8, k1, k2]*
     SU3F[I2, I3, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[6, I1, k1]*SU3F[8, k1, k2]*
     SU3F[I2, I3, k2] - 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, 6, k1]*SU3D[I1, I3, k2]*
     SU3F[I2, k1, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, 8, k1]*SU3D[I1, I3, k2]*
     SU3F[I2, k1, k2] - (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I3, k1]*SU3F[3, 6, k2]*
     SU3F[I2, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[I1, I3, k1]*SU3F[6, 8, k2]*
     SU3F[I2, k1, k2] + (9*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[3, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] + (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[3, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] + (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] - 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] - 9*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[3, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] - 18*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[3, I3, k1]*SU3F[6, I1, k2]*
     SU3F[I2, k1, k2] + 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[6, I1, k1]*SU3F[8, I3, k2]*
     SU3F[I2, k1, k2] + 3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, k1]*SU3F[8, I3, k2]*
     SU3F[I2, k1, k2] + 6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[6, I1, k1]*SU3F[8, I3, k2]*
     SU3F[I2, k1, k2] - 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3D[6, I1, k2]*
     SU3F[I3, k1, k2] + 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I1, k1]*SU3D[8, I2, k2]*
     SU3F[I3, k1, k2] - (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] + (18*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[3, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] + (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[3, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] - (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] + (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*
     SU3F[I3, k1, k2] + (36*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[3, I1, k1]*SU3F[6, I2, k2]*
     SU3F[I3, k1, k2] + (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3D[8, I1, k1]*SU3F[6, I2, k2]*
     SU3F[I3, k1, k2] + 36*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3F[3, I1, k1]*SU3F[6, I2, k2]*
     SU3F[I3, k1, k2] - 12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3F[6, I2, k1]*SU3F[8, I1, k2]*
     SU3F[I3, k1, k2] + 24*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3F[6, I2, I3]*SUNDelta[3, I1] + 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*
     SU3F[6, I2, I3]*SUNDelta[3, I1] + (48*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[6, I1, I3]*SUNDelta[3, I2] + 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[6, I1, I3]*SUNDelta[3, I2] + 24*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 23]*SU3F[6, I1, I3]*SUNDelta[3, I2] + 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 24]*
     SU3F[6, I1, I3]*SUNDelta[3, I2] - 24*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 5]*SU3F[6, I1, I2]*SUNDelta[3, I3] - 
    72*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*
     SU3F[6, I1, I2]*SUNDelta[3, I3] + 6*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, I2]*SUNDelta[3, I3] + 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, I2]*SUNDelta[3, I3] + (24*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I2, I3]*SUNDelta[6, I1] + 
    (8*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[8, I2, I3]*SUNDelta[6, I1] - 
    (24*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[3, I1, I3]*SUNDelta[6, I2] - (8*I)*Sqrt[3]*
     CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SU3D[8, I1, I3]*SUNDelta[6, I2] + 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, I1, I3]*SUNDelta[6, I2] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[8, I1, I3]*SUNDelta[6, I2] + (24*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SU3D[3, I1, I2]*SUNDelta[6, I3] + 
    (8*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[8, I1, I2]*SUNDelta[6, I3] + 
    8*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
     SU3F[6, I2, I3]*SUNDelta[8, I1] + 24*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 6]*SU3F[6, I2, I3]*SUNDelta[8, I1] + 
    (16*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
      9]*SU3D[6, I1, I3]*SUNDelta[8, I2] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
     SU3F[6, I1, I3]*SUNDelta[8, I2] + 8*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 23]*SU3F[6, I1, I3]*SUNDelta[8, I2] + 
    24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 24]*
     SU3F[6, I1, I3]*SUNDelta[8, I2] - 8*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 5]*SU3F[6, I1, I2]*SUNDelta[8, I3] - 
    24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*
     SU3F[6, I1, I2]*SUNDelta[8, I3] + 2*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, I2]*SUNDelta[8, I3] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, I1, I2]*SUNDelta[8, I3] - 12*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 21]*SU3F[3, 6, I3]*SUNDelta[I1, I2] + 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
     SU3F[6, 8, I3]*SUNDelta[I1, I2] - (8*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SUNDelta[6, I3]*SUNDelta[I1, I2] + 
    (16*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
     SUNDelta[6, I2]*SUNDelta[I1, I3] + 6*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 22]*SU3F[3, 6, I1]*SUNDelta[I2, I3] + 
    12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[3, 6, I1]*SUNDelta[I2, I3] - 2*Sqrt[3]*CouplingConstant[ChPTW3[2], 
      1]*CouplingConstant[ChPTW3[4], 22]*SU3F[6, 8, I1]*SUNDelta[I2, I3] - 
    4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
     SU3F[6, 8, I1]*SUNDelta[I2, I3] - (8*I)*CouplingConstant[ChPTW3[2], 1]*
     CouplingConstant[ChPTW3[4], 9]*SUNDelta[6, I1]*SUNDelta[I2, I3])/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {(2*((12*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I3, k1]*SU3D[I1, I2, k1] + (12*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I3, k1]*SU3D[8, k1, k2]*SU3D[I1, I2, k2] - 
     (6*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I2, k1]*SU3D[I1, I3, k1] + (3*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3D[6, k1, k2]*SU3D[8, I2, k2]*SU3D[I1, I3, k1] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       21]*SU3D[6, k1, k2]*SU3D[8, I2, k1]*SU3D[I1, I3, k2] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 9]*SU3D[6, I2, k1]*SU3D[8, I3, k2]*SU3D[I1, k1, k2] - 
     (6*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I1, k1]*SU3D[I2, I3, k1] - (12*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I1, k1]*SU3D[8, I3, k2]*SU3D[I2, k1, k2] + 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 9]*SU3D[6, 8, k1]*SU3D[I1, I2, k2]*SU3D[I3, k1, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[I1, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, 8, k2] + 
     6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 6*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22]*SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 
     12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
      SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
      SU3D[8, k1, k2]*SU3D[I2, I3, k1]*SU3F[6, I1, k2] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
      SU3D[8, k1, k2]*SU3D[I2, I3, k1]*SU3F[6, I1, k2] + 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[8, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
      SU3D[8, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       23]*SU3D[8, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
      SU3D[8, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
      SU3D[8, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] + 
     6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[I1, I3, k1]*SU3F[6, I2, k1] + 12*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[8, I3, k1]*SU3D[I1, k1, k2]*SU3F[6, I2, k2] - 
     24*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3D[I1, I2, k1]*SU3F[6, I3, k1] - 36*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 8]*SU3D[I1, I2, k1]*SU3F[6, I3, k1] - 
     12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[I1, I2, k1]*SU3F[6, I3, k1] - 24*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3D[8, k1, k2]*SU3D[I1, I2, k1]*SU3F[6, I3, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[8, k1, k2]*SU3D[I1, I2, k1]*SU3F[6, I3, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3D[8, I2, k1]*SU3D[I1, k1, k2]*SU3F[6, I3, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3D[8, I1, k1]*SU3D[I2, k1, k2]*SU3F[6, I3, k2] + 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 5]*SU3D[I2, k1, k2]*SU3F[6, I3, k2]*SU3F[8, I1, k1] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3D[6, k1, k2]*SU3D[I1, I3, k2]*SU3F[8, I2, k1] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 21]*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I2, k1] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       22]*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I2, k1] - 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       23]*SU3D[I3, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I2, k1] + 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 5]*SU3D[I1, k1, k2]*SU3F[6, I3, k2]*SU3F[8, I2, k1] - 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       21]*SU3D[I1, k1, k2]*SU3F[6, I3, k2]*SU3F[8, I2, k1] + 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3D[6, I3, k1]*SU3D[I1, k1, k2]*SU3F[8, I2, k2] + 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       21]*SU3D[I1, I3, k1]*SU3F[6, k1, k2]*SU3F[8, I2, k2] + 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I3, k1]*SU3D[I1, I2, k2]*SU3F[8, k1, k2] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       22]*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*SU3F[8, k1, k2] - 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       23]*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*SU3F[8, k1, k2] - 
     (24*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 5]*SU3D[I1, I2, k1]*SU3F[6, I3, k2]*SU3F[8, k1, k2] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 9]*SU3D[I1, I2, k1]*SU3F[6, I3, k2]*SU3F[8, k1, k2] + 
     6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I2, k1]*SU3F[I1, I3, k1] + 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3D[6, k1, k2]*SU3D[8, I2, k2]*SU3F[I1, I3, k1] + 
     (6*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3F[6, I2, k1]*SU3F[I1, I3, k1] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3D[6, k1, k2]*SU3D[8, I2, k1]*SU3F[I1, I3, k2] + 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       21]*SU3D[6, k1, k2]*SU3F[8, I2, k1]*SU3F[I1, I3, k2] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3F[6, k1, k2]*SU3F[8, I2, k1]*SU3F[I1, I3, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I2, k1]*SU3D[8, I3, k2]*SU3F[I1, k1, k2] + 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 9]*SU3D[8, I3, k1]*SU3F[6, I2, k2]*SU3F[I1, k1, k2] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 5]*SU3D[8, I2, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] - 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       21]*SU3D[6, I3, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] + 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3F[6, I3, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3F[6, I3, k1]*SU3F[8, I2, k2]*SU3F[I1, k1, k2] + 
     6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I1, k1]*SU3F[I2, I3, k1] + (6*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9]*SU3F[6, I1, k1]*SU3F[I2, I3, k1] + 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       22]*SU3D[8, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1] + 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       23]*SU3D[8, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1] + 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
      SU3F[6, I1, k1]*SU3F[8, k1, k2]*SU3F[I2, I3, k2] + 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
      SU3F[6, I1, k1]*SU3F[8, k1, k2]*SU3F[I2, I3, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I1, k1]*SU3D[8, I3, k2]*SU3F[I2, k1, k2] + 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 9]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       22]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 23]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 5]*SU3D[8, I1, k1]*SU3F[6, I3, k2]*SU3F[I2, k1, k2] + 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3F[6, I3, k1]*SU3F[8, I1, k2]*SU3F[I2, k1, k2] + 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, 8, k1]*SU3D[I1, I2, k2]*SU3F[I3, k1, k2] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 9]*SU3D[I1, I2, k1]*SU3F[6, 8, k2]*SU3F[I3, k1, k2] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       22]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       23]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       21]*SU3F[6, I1, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
      SU3F[6, I1, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
      SU3F[6, I1, k1]*SU3F[8, I2, k2]*SU3F[I3, k1, k2] - 
     (8*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       9]*SU3D[8, I2, I3]*SUNDelta[6, I1] - (8*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[8, I1, I3]*SUNDelta[6, I2] + (8*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[8, I1, I2]*SUNDelta[6, I3] - 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 21]*SU3F[8, I1, I2]*SUNDelta[6, I3] + 
     8*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3F[6, I2, I3]*SUNDelta[8, I1] + 24*Sqrt[3]*CouplingConstant[
       ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*SU3F[6, I2, I3]*
      SUNDelta[8, I1] + 8*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5]*SU3F[6, I1, I3]*SUNDelta[8, I2] + 
     24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*
      SU3F[6, I1, I3]*SUNDelta[8, I2] - 2*Sqrt[3]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, I3]*SUNDelta[8, I2] - 
     4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
      SU3F[6, I1, I3]*SUNDelta[8, I2] - (16*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I1, I2]*SUNDelta[8, I3] - 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, I2]*SUNDelta[8, I3] - 
     8*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
      SU3F[6, I1, I2]*SUNDelta[8, I3] - 24*Sqrt[3]*CouplingConstant[
       ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 24]*SU3F[6, I1, I2]*
      SUNDelta[8, I3] + (8*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9]*SUNDelta[6, I3]*SUNDelta[I1, I2] - 
     4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3F[6, 8, I2]*SUNDelta[I1, I3] - (4*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9]*SUNDelta[6, I2]*SUNDelta[I1, I3] + 
     2*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
      SU3F[6, 8, I1]*SUNDelta[I2, I3] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 23]*SU3F[6, 8, I1]*SUNDelta[I2, I3] - 
     (4*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SUNDelta[6, I1]*SUNDelta[I2, I3]))/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}, 
 {(2*((-6*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I3, k1]*SU3D[I1, I2, k1] + (3*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3D[6, k1, k2]*SU3D[8, I3, k2]*SU3D[I1, I2, k1] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       21]*SU3D[6, k1, k2]*SU3D[8, I3, k1]*SU3D[I1, I2, k2] + 
     (12*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I2, k1]*SU3D[I1, I3, k1] + (12*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I2, k1]*SU3D[8, k1, k2]*SU3D[I1, I3, k2] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 9]*SU3D[6, I3, k1]*SU3D[8, I2, k2]*SU3D[I1, k1, k2] - 
     (6*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I1, k1]*SU3D[I2, I3, k1] + (12*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, 8, k1]*SU3D[I1, I3, k2]*SU3D[I2, k1, k2] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 9]*SU3D[6, I1, k1]*SU3D[8, I2, k2]*SU3D[I3, k1, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[I1, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, 8, k2] + 
     6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 6*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22]*SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 
     12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
      SU3D[I2, I3, k1]*SU3F[6, I1, k1] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
      SU3D[8, k1, k2]*SU3D[I2, I3, k1]*SU3F[6, I1, k2] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
      SU3D[8, k1, k2]*SU3D[I2, I3, k1]*SU3F[6, I1, k2] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
      SU3D[8, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
      SU3D[8, I3, k1]*SU3D[I2, k1, k2]*SU3F[6, I1, k2] + 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[8, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
      SU3D[8, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       23]*SU3D[8, I2, k1]*SU3D[I3, k1, k2]*SU3F[6, I1, k2] - 
     24*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3D[I1, I3, k1]*SU3F[6, I2, k1] - 36*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 8]*SU3D[I1, I3, k1]*SU3F[6, I2, k1] - 
     12*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[I1, I3, k1]*SU3F[6, I2, k1] - 24*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3D[8, k1, k2]*SU3D[I1, I3, k1]*SU3F[6, I2, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[8, k1, k2]*SU3D[I1, I3, k1]*SU3F[6, I2, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3D[8, I3, k1]*SU3D[I1, k1, k2]*SU3F[6, I2, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3D[8, I1, k1]*SU3D[I3, k1, k2]*SU3F[6, I2, k2] + 
     6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[I1, I2, k1]*SU3F[6, I3, k1] + 12*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[8, I2, k1]*SU3D[I1, k1, k2]*SU3F[6, I3, k2] + 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 5]*SU3D[I3, k1, k2]*SU3F[6, I2, k2]*SU3F[8, I1, k1] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3D[6, k1, k2]*SU3D[I1, I2, k2]*SU3F[8, I3, k1] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 21]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I3, k1] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       22]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I3, k1] - 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       23]*SU3D[I2, k1, k2]*SU3F[6, I1, k2]*SU3F[8, I3, k1] + 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 5]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[8, I3, k1] - 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       21]*SU3D[I1, k1, k2]*SU3F[6, I2, k2]*SU3F[8, I3, k1] + 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3D[6, I2, k1]*SU3D[I1, k1, k2]*SU3F[8, I3, k2] + 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       21]*SU3D[I1, I2, k1]*SU3F[6, k1, k2]*SU3F[8, I3, k2] + 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I2, k1]*SU3D[I1, I3, k2]*SU3F[8, k1, k2] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       22]*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*SU3F[8, k1, k2] - 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       23]*SU3D[I2, I3, k1]*SU3F[6, I1, k2]*SU3F[8, k1, k2] - 
     (24*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 5]*SU3D[I1, I3, k1]*SU3F[6, I2, k2]*SU3F[8, k1, k2] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 9]*SU3D[I1, I3, k1]*SU3F[6, I2, k2]*SU3F[8, k1, k2] + 
     6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I3, k1]*SU3F[I1, I2, k1] + 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3D[6, k1, k2]*SU3D[8, I3, k2]*SU3F[I1, I2, k1] + 
     (6*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3F[6, I3, k1]*SU3F[I1, I2, k1] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3D[6, k1, k2]*SU3D[8, I3, k1]*SU3F[I1, I2, k2] + 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       21]*SU3D[6, k1, k2]*SU3F[8, I3, k1]*SU3F[I1, I2, k2] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3F[6, k1, k2]*SU3F[8, I3, k1]*SU3F[I1, I2, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I3, k1]*SU3D[8, I2, k2]*SU3F[I1, k1, k2] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 5]*SU3D[8, I3, k1]*SU3F[6, I2, k2]*SU3F[I1, k1, k2] + 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 9]*SU3D[8, I2, k1]*SU3F[6, I3, k2]*SU3F[I1, k1, k2] - 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       21]*SU3D[6, I2, k1]*SU3F[8, I3, k2]*SU3F[I1, k1, k2] + 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3F[6, I2, k1]*SU3F[8, I3, k2]*SU3F[I1, k1, k2] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 21]*
      SU3F[6, I2, k1]*SU3F[8, I3, k2]*SU3F[I1, k1, k2] - 
     6*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I1, k1]*SU3F[I2, I3, k1] - (6*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9]*SU3F[6, I1, k1]*SU3F[I2, I3, k1] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       22]*SU3D[8, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1] - 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       23]*SU3D[8, k1, k2]*SU3F[6, I1, k2]*SU3F[I2, I3, k1] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
      SU3F[6, I1, k1]*SU3F[8, k1, k2]*SU3F[I2, I3, k2] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
      SU3F[6, I1, k1]*SU3F[8, k1, k2]*SU3F[I2, I3, k2] + 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, 8, k1]*SU3D[I1, I3, k2]*SU3F[I2, k1, k2] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 9]*SU3D[I1, I3, k1]*SU3F[6, 8, k2]*SU3F[I2, k1, k2] - 
     (3*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       22]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       23]*SU3D[8, I3, k1]*SU3F[6, I1, k2]*SU3F[I2, k1, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       21]*SU3F[6, I1, k1]*SU3F[8, I3, k2]*SU3F[I2, k1, k2] - 
     3*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
      SU3F[6, I1, k1]*SU3F[8, I3, k2]*SU3F[I2, k1, k2] - 
     6*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
      SU3F[6, I1, k1]*SU3F[8, I3, k2]*SU3F[I2, k1, k2] - 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[6, I1, k1]*SU3D[8, I2, k2]*SU3F[I3, k1, k2] + 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 9]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 
     (6*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       22]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 23]*SU3D[8, I2, k1]*SU3F[6, I1, k2]*SU3F[I3, k1, k2] - 
     (12*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[
       ChPTW3[4], 5]*SU3D[8, I1, k1]*SU3F[6, I2, k2]*SU3F[I3, k1, k2] + 
     12*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3F[6, I2, k1]*SU3F[8, I1, k2]*SU3F[I3, k1, k2] - 
     (8*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       9]*SU3D[8, I2, I3]*SUNDelta[6, I1] + (8*I)*Sqrt[3]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SU3D[8, I1, I3]*SUNDelta[6, I2] - 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 21]*SU3F[8, I1, I3]*SUNDelta[6, I2] - 
     (8*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       9]*SU3D[8, I1, I2]*SUNDelta[6, I3] - 
     8*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3F[6, I2, I3]*SUNDelta[8, I1] - 24*Sqrt[3]*CouplingConstant[
       ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*SU3F[6, I2, I3]*
      SUNDelta[8, I1] - (16*I)*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9]*SU3D[6, I1, I3]*SUNDelta[8, I2] - 
     4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
      SU3F[6, I1, I3]*SUNDelta[8, I2] - 8*Sqrt[3]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 23]*SU3F[6, I1, I3]*SUNDelta[8, I2] - 
     24*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 
       24]*SU3F[6, I1, I3]*SUNDelta[8, I2] + 
     8*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5]*
      SU3F[6, I1, I2]*SUNDelta[8, I3] + 24*Sqrt[3]*CouplingConstant[
       ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6]*SU3F[6, I1, I2]*
      SUNDelta[8, I3] - 2*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 22]*SU3F[6, I1, I2]*SUNDelta[8, I3] - 
     4*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 23]*
      SU3F[6, I1, I2]*SUNDelta[8, I3] - 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 21]*SU3F[6, 8, I3]*SUNDelta[I1, I2] - 
     (4*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SUNDelta[6, I3]*SUNDelta[I1, I2] + (8*I)*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 9]*SUNDelta[6, I2]*SUNDelta[I1, I3] + 
     2*Sqrt[3]*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 22]*
      SU3F[6, 8, I1]*SUNDelta[I2, I3] + 4*Sqrt[3]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 23]*SU3F[6, 8, I1]*SUNDelta[I2, I3] - 
     (4*I)*CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 9]*
      SUNDelta[6, I1]*SUNDelta[I2, I3]))/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4)}}
