{{((64*I)*(3*SUNDelta[0, I3]*SUNDelta[I1, I2]*CouplingConstant[ChPT3[4], 6, 
       RenormalizationState[0]] + 3*SUNDelta[0, I1]*SUNDelta[I2, I3]*
      CouplingConstant[ChPT3[4], 7, RenormalizationState[0]] + 
     SU3D[I1, I2, I3]*CouplingConstant[ChPT3[4], 8, RenormalizationState[
        0]] + SUNDelta[0, I3]*SUNDelta[I1, I2]*CouplingConstant[ChPT3[4], 8, 
       RenormalizationState[0]] + SUNDelta[0, I1]*SUNDelta[I2, I3]*
      CouplingConstant[ChPT3[4], 8, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]}}
