{{(I*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 19]*
    (UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]]]] - UTrace1[FANonCommutative[
       UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]]]] + UTrace1[FANonCommutative[
       UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(I*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 19]*
    (UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]]]] + UTrace1[FANonCommutative[
       UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]]]] - UTrace1[FANonCommutative[
       UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(-I*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 19]*
    (UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]]]] + UTrace1[FANonCommutative[
       UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I1]]]] - UTrace1[FANonCommutative[
       UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(-I*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 20]*
    (UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]]]] + UTrace1[FANonCommutative[
       UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
       UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I3]]]] - UTrace1[FANonCommutative[
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(I/2*UCouplingConstant[ChPTW3[2], 1]*(UCouplingConstant[ChPTW3[4], 25]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] - (UCouplingConstant[ChPTW3[4], 20] + 
       UCouplingConstant[ChPTW3[4], 25] - UCouplingConstant[ChPTW3[4], 26])*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] - UCouplingConstant[ChPTW3[4], 20]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + UCouplingConstant[ChPTW3[4], 26]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + UCouplingConstant[ChPTW3[4], 25]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - UCouplingConstant[ChPTW3[4], 25]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + UCouplingConstant[ChPTW3[4], 20]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] - UCouplingConstant[ChPTW3[4], 26]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + UCouplingConstant[ChPTW3[4], 20]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - UCouplingConstant[ChPTW3[4], 26]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
     RenormalizationState[0]]^4}, 
 {(-I/2*UCouplingConstant[ChPTW3[2], 1]*
    (UCouplingConstant[ChPTW3[4], 25]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     (UCouplingConstant[ChPTW3[4], 20] - UCouplingConstant[ChPTW3[4], 25] + 
       UCouplingConstant[ChPTW3[4], 26])*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     UCouplingConstant[ChPTW3[4], 20]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     UCouplingConstant[ChPTW3[4], 26]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     UCouplingConstant[ChPTW3[4], 25]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     UCouplingConstant[ChPTW3[4], 25]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     UCouplingConstant[ChPTW3[4], 20]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     UCouplingConstant[ChPTW3[4], 26]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     UCouplingConstant[ChPTW3[4], 20]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     UCouplingConstant[ChPTW3[4], 26]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(-I*UCouplingConstant[ChPTW3[2], 1]*UCouplingConstant[ChPTW3[4], 20]*
    (UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]]]] + UTrace1[FANonCommutative[
       UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
       UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
       UMatrix[UGenerator[I2]]]] - UTrace1[FANonCommutative[
       UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
       UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(I/2*UCouplingConstant[ChPTW3[2], 1]*(UCouplingConstant[ChPTW3[4], 25]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + UCouplingConstant[ChPTW3[4], 25]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] - UCouplingConstant[ChPTW3[4], 25]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - UCouplingConstant[ChPTW3[4], 20]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - UCouplingConstant[ChPTW3[4], 25]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + UCouplingConstant[ChPTW3[4], 26]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - UCouplingConstant[ChPTW3[4], 20]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + UCouplingConstant[ChPTW3[4], 26]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + UCouplingConstant[ChPTW3[4], 20]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - UCouplingConstant[ChPTW3[4], 26]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + UCouplingConstant[ChPTW3[4], 20]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - UCouplingConstant[ChPTW3[4], 26]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]]))/DecayConstant[PseudoScalar[1], 
     RenormalizationState[0]]^4}, 
 {(-I/2*UCouplingConstant[ChPTW3[2], 1]*
    (UCouplingConstant[ChPTW3[4], 25]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     UCouplingConstant[ChPTW3[4], 25]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     UCouplingConstant[ChPTW3[4], 25]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     UCouplingConstant[ChPTW3[4], 20]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     UCouplingConstant[ChPTW3[4], 25]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UCouplingConstant[ChPTW3[4], 26]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     UCouplingConstant[ChPTW3[4], 20]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     UCouplingConstant[ChPTW3[4], 26]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     UCouplingConstant[ChPTW3[4], 20]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     UCouplingConstant[ChPTW3[4], 26]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     UCouplingConstant[ChPTW3[4], 20]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     UCouplingConstant[ChPTW3[4], 26]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(I/24*UCouplingConstant[ChPTW3[2], 1]*(12*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]]]]*
      (UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
       UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]) + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]]]]*
      (UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
       UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]) - 
     12*UCouplingConstant[ChPTW3[4], 24]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] - 12*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] - 12*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] + 8*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + 2*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + 8*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + 2*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] - 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] - 8*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - 8*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 4*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 2*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] + 4*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 2*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] + 6*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     3*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + 6*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     3*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] - 12*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - 12*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       21]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     6*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] - 3*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     6*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] - 3*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]]]] - 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       21]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] - 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       21]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + 12*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     12*UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       23]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] + 6*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
     12*UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 6*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 12*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     12*UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       23]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 6*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
     12*UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 6*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 6*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     6*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] - 3*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     6*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 3*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 6*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     6*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] - 3*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     6*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 3*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(-I/24*UCouplingConstant[ChPTW3[2], 1]*
    (12*UCouplingConstant[ChPTW3[4], 24]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]]]]*
      (UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
       UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]) - 
     12*UCouplingConstant[ChPTW3[4], 24]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]]]]*
      (-UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]) - 
     12*UCouplingConstant[ChPTW3[4], 24]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] - 12*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] - 8*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] - 2*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] - 8*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] - 2*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + 8*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 8*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 4*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] - 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] - 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - 2*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] - 4*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - 8*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 2*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] + 6*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     3*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] + 6*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     3*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] - 12*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - 12*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       21]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     6*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] - 3*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     6*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] - 3*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       21]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       21]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + 12*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     12*UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]]]] - 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       23]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] + 6*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
     12*UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 6*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 12*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     12*UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] - 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       23]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] + 6*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
     12*UCouplingConstant[ChPTW3[4], 23]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] + 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 6*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I3]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I3]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 6*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     6*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] - 3*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     6*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 3*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
     6*UCouplingConstant[ChPTW3[4], 22]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] - 12*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     12*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] + 6*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     6*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I1]]]] - 3*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     6*UCouplingConstant[ChPTW3[4], 21]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]]]] - 3*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[3]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}, 
 {(-I/12*UCouplingConstant[ChPTW3[2], 1]*
    (4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]]]]*
      (UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
       UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]) + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]]]]*
      (UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
       UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
         UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]]) - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 24]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] - 4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       24]*UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]]*UTrace1[FANonCommutative[
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] - 4*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] - UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]]]] - 4*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] - UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]]]] + 4*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] + 4*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 4*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] + 4*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 4*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 4*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 2*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] - 4*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]]]] - 4*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]]]] - UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] - 2*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - 4*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - 4*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]]]] + 2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 
       21]*UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I3]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I3]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[8]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I3]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 23]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     4*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] + 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] - 
     2*Sqrt[3]*UCouplingConstant[ChPTW3[4], 21]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]] - 
     Sqrt[3]*UCouplingConstant[ChPTW3[4], 22]*
      UTrace1[FANonCommutative[UMatrix[UGenerator[I3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]]))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^4}}
