{{(-2*Sqrt[2]*FermiConstant*(12*CouplingConstant[ChPTPhotonsLeptons3[4], 13, 
       RenormalizationState[0]] + 12*CouplingConstant[ChPTPhotonsLeptons3[4], 
       14, RenormalizationState[0]] + 
     10*CouplingConstant[ChPTPhotonsLeptons3[4], 17, RenormalizationState[
        0]] + 10*CouplingConstant[ChPTPhotonsLeptons3[4], 18, 
       RenormalizationState[0]] - 3*CouplingConstant[ChPTPhotonsLeptons3[4], 
       32, RenormalizationState[0]] - 
     9*CouplingConstant[ChPTPhotonsLeptons3[4], 33, RenormalizationState[0]])*
    DecayConstant[PseudoScalar[1], RenormalizationState[0]]*
    (VUD*SUNDelta[1, I3] + I*VUD*SUNDelta[2, I3] + 
     VUS*(SUNDelta[4, I3] + I*SUNDelta[5, I3]))*SUNDelta[J1, J2])/9}, 
 {(-8*Sqrt[2]*FermiConstant*CouplingConstant[ChPTPhotonsLeptons3[4], 4, 
     RenormalizationState[0]]*(VUD*SUNDelta[1, I3] + I*VUD*SUNDelta[2, I3] + 
     VUS*(SUNDelta[4, I3] + I*SUNDelta[5, I3]))*SUNDelta[J1, J2])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]}, 
 {(-8*Sqrt[2]*FermiConstant*(VUD*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*(SUNDelta[1, I3] + I*SUNDelta[2, I3]) + 
     CouplingConstant[ChPTPhotonsLeptons3[4], 4, RenormalizationState[0]]*
      (VUD*SUNDelta[1, I3] + I*VUD*SUNDelta[2, I3] + VUS*SUNDelta[4, I3] + 
       I*VUS*SUNDelta[5, I3]))*SUNDelta[J1, J2])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]}, 
 {(-8*Sqrt[2]*FermiConstant*(VUS*CouplingConstant[ChPTPhotonsLeptons3[4], 5, 
       RenormalizationState[0]]*(SUNDelta[4, I3] + I*SUNDelta[5, I3]) + 
     CouplingConstant[ChPTPhotonsLeptons3[4], 4, RenormalizationState[0]]*
      (VUD*SUNDelta[1, I3] + I*VUD*SUNDelta[2, I3] + VUS*SUNDelta[4, I3] + 
       I*VUS*SUNDelta[5, I3]))*SUNDelta[J1, J2])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]}}
