{{(-8*(3*SU3D[6, I1, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 9*I*SU3D[7, I1, I2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     3*Sqrt[3]*SU3D[6, I2, k1]*SU3D[8, I1, k1]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 5] + 3*Sqrt[3]*SU3D[6, I1, k1]*
      SU3D[8, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 3*I*Sqrt[3]*SU3D[8, I2, k1]*
      SU3F[6, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 3*I*Sqrt[3]*SU3D[8, I1, k1]*
      SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 3*I*Sqrt[3]*SU3D[6, I2, k1]*
      SU3F[8, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 3*Sqrt[3]*SU3F[6, I2, k1]*
      SU3F[8, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 3*I*Sqrt[3]*SU3D[6, I1, k1]*
      SU3F[8, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 3*Sqrt[3]*SU3F[6, I1, k1]*
      SU3F[8, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 2*Sqrt[3]*SU3Delta[6, I2]*
      SU3Delta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 2*Sqrt[3]*SU3Delta[6, I1]*
      SU3Delta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 6*Sqrt[3]*SU3Delta[6, I2]*
      SU3Delta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 6] + 6*Sqrt[3]*SU3Delta[6, I1]*
      SU3Delta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 6] + 9*SU3D[6, I1, I2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 8]))/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(-4*(6*SU3D[6, I1, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 9*SU3D[3, I2, k1]*SU3D[6, I1, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     9*SU3D[3, I1, k1]*SU3D[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 18*I*SU3D[7, I1, I2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
     3*Sqrt[3]*SU3D[6, I2, k1]*SU3D[8, I1, k1]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 5] - 3*Sqrt[3]*SU3D[6, I1, k1]*
      SU3D[8, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 9*I*SU3D[6, I2, k1]*SU3F[3, I1, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
     9*I*SU3D[6, I1, k1]*SU3F[3, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 9*I*SU3D[3, I2, k1]*SU3F[6, I1, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
     3*I*Sqrt[3]*SU3D[8, I2, k1]*SU3F[6, I1, k1]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 5] + 9*SU3F[3, I2, k1]*SU3F[6, I1, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     9*I*SU3D[3, I1, k1]*SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 3*I*Sqrt[3]*SU3D[8, I1, k1]*
      SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 9*SU3F[3, I1, k1]*SU3F[6, I2, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3F[8, I1, k1]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 5] - 3*Sqrt[3]*SU3F[6, I2, k1]*
      SU3F[8, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 3*I*Sqrt[3]*SU3D[6, I1, k1]*
      SU3F[8, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 3*Sqrt[3]*SU3F[6, I1, k1]*
      SU3F[8, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 6*SU3Delta[3, I2]*SU3Delta[6, I1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     6*SU3Delta[3, I1]*SU3Delta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 2*Sqrt[3]*SU3Delta[6, I2]*
      SU3Delta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 2*Sqrt[3]*SU3Delta[6, I1]*
      SU3Delta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 18*SU3Delta[3, I2]*SU3Delta[6, I1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6] + 
     18*SU3Delta[3, I1]*SU3Delta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 6] - 6*Sqrt[3]*SU3Delta[6, I2]*
      SU3Delta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 6] - 6*Sqrt[3]*SU3Delta[6, I1]*
      SU3Delta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 6] + 18*SU3D[6, I1, I2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 8]))/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {(-4*(24*SU3D[6, I1, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 9*SU3D[3, I2, k1]*SU3D[6, I1, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
     9*SU3D[3, I1, k1]*SU3D[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 3*Sqrt[3]*SU3D[6, I2, k1]*
      SU3D[8, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 3*Sqrt[3]*SU3D[6, I1, k1]*
      SU3D[8, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 9*I*SU3D[6, I2, k1]*SU3F[3, I1, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     9*I*SU3D[6, I1, k1]*SU3F[3, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 9*I*SU3D[3, I2, k1]*SU3F[6, I1, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
     3*I*Sqrt[3]*SU3D[8, I2, k1]*SU3F[6, I1, k1]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 5] - 9*SU3F[3, I2, k1]*SU3F[6, I1, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
     9*I*SU3D[3, I1, k1]*SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 3*I*Sqrt[3]*SU3D[8, I1, k1]*
      SU3F[6, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 9*SU3F[3, I1, k1]*SU3F[6, I2, k1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] + 
     3*I*Sqrt[3]*SU3D[6, I2, k1]*SU3F[8, I1, k1]*CouplingConstant[ChPTW3[2], 
       1]*CouplingConstant[ChPTW3[4], 5] - 3*Sqrt[3]*SU3F[6, I2, k1]*
      SU3F[8, I1, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] + 3*I*Sqrt[3]*SU3D[6, I1, k1]*
      SU3F[8, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 3*Sqrt[3]*SU3F[6, I1, k1]*
      SU3F[8, I2, k1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 6*SU3Delta[3, I2]*SU3Delta[6, I1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 5] - 
     6*SU3Delta[3, I1]*SU3Delta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 2*Sqrt[3]*SU3Delta[6, I2]*
      SU3Delta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 2*Sqrt[3]*SU3Delta[6, I1]*
      SU3Delta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 5] - 18*SU3Delta[3, I2]*SU3Delta[6, I1]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 6] - 
     18*SU3Delta[3, I1]*SU3Delta[6, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 6] - 6*Sqrt[3]*SU3Delta[6, I2]*
      SU3Delta[8, I1]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 6] - 6*Sqrt[3]*SU3Delta[6, I1]*
      SU3Delta[8, I2]*CouplingConstant[ChPTW3[2], 1]*
      CouplingConstant[ChPTW3[4], 6] + 18*SU3D[6, I1, I2]*
      CouplingConstant[ChPTW3[2], 1]*CouplingConstant[ChPTW3[4], 8]))/
   (9*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}}
