{{-((-10*SU3D[I1, I4, k1]*SU3Delta[6, I3]*SU3Delta[I2, k1] + 
      8*SU3D[6, I4, k1]*SU3Delta[I1, I3]*SU3Delta[I2, k1] - 
      8*I*SU3F[6, I4, k1]*SU3Delta[I1, I3]*SU3Delta[I2, k1] + 
      8*SU3D[I1, I4, k2]*SU3Delta[6, I3]*SU3Delta[I2, k2] - 
      6*I*SU3F[I1, I4, k2]*SU3Delta[6, I3]*SU3Delta[I2, k2] + 
      2*SU3D[6, I4, k2]*SU3Delta[I1, I3]*SU3Delta[I2, k2] + 
      2*I*SU3F[6, I4, k2]*SU3Delta[I1, I3]*SU3Delta[I2, k2] + 
      12*SU3D[I1, I4, k3]*SU3Delta[6, I3]*SU3Delta[I2, k3] + 
      12*SU3D[6, I1, k1]*SU3Delta[I2, k1]*SU3Delta[I3, I4] - 
      12*I*SU3F[6, I1, k1]*SU3Delta[I2, k1]*SU3Delta[I3, I4] - 
      2*SU3D[6, I1, k2]*SU3Delta[I2, k2]*SU3Delta[I3, I4] - 
      2*I*SU3F[6, I1, k2]*SU3Delta[I2, k2]*SU3Delta[I3, I4] - 
      10*SU3D[I1, I4, k1]*SU3Delta[6, I2]*SU3Delta[I3, k1] + 
      8*SU3D[6, I4, k1]*SU3Delta[I1, I2]*SU3Delta[I3, k1] - 
      8*I*SU3F[6, I4, k1]*SU3Delta[I1, I2]*SU3Delta[I3, k1] + 
      12*SU3D[6, I1, k1]*SU3Delta[I2, I4]*SU3Delta[I3, k1] - 
      12*I*SU3F[6, I1, k1]*SU3Delta[I2, I4]*SU3Delta[I3, k1] - 
      6*SU3D[6, k1, k7]*SU3D[I1, I4, k5]*SU3D[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I3, k1] - 9*SU3D[6, k1, k6]*SU3D[I1, I4, k7]*SU3D[k2, k6, k7]*
       SU3Delta[I2, k2]*SU3Delta[I3, k1] - 15*I*SU3D[I1, I4, k5]*
       SU3D[k2, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I2, k2]*SU3Delta[I3, k1] + 
      6*I*SU3D[6, k1, k6]*SU3D[k2, k5, k6]*SU3F[I1, I4, k5]*SU3Delta[I2, k2]*
       SU3Delta[I3, k1] + 3*SU3D[k2, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, I4, k5]*
       SU3Delta[I2, k2]*SU3Delta[I3, k1] - 9*I*SU3D[6, k1, k6]*
       SU3D[k2, k6, k7]*SU3F[I1, I4, k7]*SU3Delta[I2, k2]*SU3Delta[I3, k1] + 
      15*SU3D[I1, I4, k5]*SU3F[6, k1, k6]*SU3F[k2, k5, k6]*SU3Delta[I2, k2]*
       SU3Delta[I3, k1] + 3*I*SU3F[6, k1, k6]*SU3F[I1, I4, k5]*
       SU3F[k2, k5, k6]*SU3Delta[I2, k2]*SU3Delta[I3, k1] - 
      9*I*SU3D[6, k1, k7]*SU3D[I1, I4, k5]*SU3F[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I3, k1] + 6*I*SU3D[6, k1, k5]*SU3D[I1, I4, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k2]*SU3Delta[I3, k1] + 
      6*SU3D[6, k1, k5]*SU3F[I1, I4, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I3, k1] - 9*SU3D[6, k1, k6]*SU3F[I1, I4, k7]*SU3F[k2, k6, k7]*
       SU3Delta[I2, k2]*SU3Delta[I3, k1] - 4*SU3D[I4, k1, k2]*SU3Delta[6, I1]*
       SU3Delta[I2, k2]*SU3Delta[I3, k1] - 10*SU3D[6, k1, k2]*
       SU3Delta[I1, I4]*SU3Delta[I2, k2]*SU3Delta[I3, k1] - 
      10*I*SU3F[6, k1, k2]*SU3Delta[I1, I4]*SU3Delta[I2, k2]*
       SU3Delta[I3, k1] + 9*SU3D[6, k1, k7]*SU3D[I1, k5, k7]*SU3D[I4, k3, k5]*
       SU3Delta[I2, k3]*SU3Delta[I3, k1] + 3*SU3D[6, k1, k7]*SU3D[I1, k3, k5]*
       SU3D[I4, k5, k7]*SU3Delta[I2, k3]*SU3Delta[I3, k1] + 
      9*I*SU3D[I1, k5, k6]*SU3D[I4, k3, k5]*SU3F[6, k1, k6]*SU3Delta[I2, k3]*
       SU3Delta[I3, k1] + 3*I*SU3D[I1, k3, k5]*SU3D[I4, k5, k6]*
       SU3F[6, k1, k6]*SU3Delta[I2, k3]*SU3Delta[I3, k1] - 
      3*I*SU3D[6, k1, k6]*SU3D[I4, k5, k6]*SU3F[I1, k3, k5]*SU3Delta[I2, k3]*
       SU3Delta[I3, k1] + 3*SU3D[I4, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, k3, k5]*
       SU3Delta[I2, k3]*SU3Delta[I3, k1] - 9*I*SU3D[6, k1, k5]*
       SU3D[I4, k3, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k3]*SU3Delta[I3, k1] - 
      9*SU3D[I4, k3, k5]*SU3F[6, k1, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k3]*
       SU3Delta[I3, k1] - 9*I*SU3D[6, k1, k6]*SU3D[I1, k5, k6]*
       SU3F[I4, k3, k5]*SU3Delta[I2, k3]*SU3Delta[I3, k1] + 
      9*SU3D[I1, k5, k6]*SU3F[6, k1, k6]*SU3F[I4, k3, k5]*SU3Delta[I2, k3]*
       SU3Delta[I3, k1] - 3*SU3D[I1, k3, k5]*SU3F[6, k1, k6]*SU3F[I4, k5, k6]*
       SU3Delta[I2, k3]*SU3Delta[I3, k1] + 3*I*SU3F[6, k1, k6]*
       SU3F[I1, k3, k5]*SU3F[I4, k5, k6]*SU3Delta[I2, k3]*SU3Delta[I3, k1] + 
      3*I*SU3D[6, k1, k7]*SU3D[I1, k3, k5]*SU3F[I4, k5, k7]*SU3Delta[I2, k3]*
       SU3Delta[I3, k1] - 3*SU3D[6, k1, k6]*SU3F[I1, k3, k7]*SU3F[I4, k6, k7]*
       SU3Delta[I2, k3]*SU3Delta[I3, k1] + 2*SU3D[I4, k1, k3]*SU3Delta[6, I1]*
       SU3Delta[I2, k3]*SU3Delta[I3, k1] + 9*SU3D[6, k1, k7]*SU3D[I1, k5, k7]*
       SU3D[I4, k4, k5]*SU3Delta[I2, k4]*SU3Delta[I3, k1] + 
      9*SU3D[6, k1, k7]*SU3D[I1, k4, k5]*SU3D[I4, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I3, k1] + 9*I*SU3D[I1, k5, k6]*SU3D[I4, k4, k5]*
       SU3F[6, k1, k6]*SU3Delta[I2, k4]*SU3Delta[I3, k1] + 
      9*I*SU3D[I1, k4, k5]*SU3D[I4, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I2, k4]*
       SU3Delta[I3, k1] + 9*I*SU3D[6, k1, k6]*SU3D[I4, k5, k6]*
       SU3F[I1, k4, k5]*SU3Delta[I2, k4]*SU3Delta[I3, k1] - 
      9*SU3D[I4, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, k4, k5]*SU3Delta[I2, k4]*
       SU3Delta[I3, k1] - 9*I*SU3D[6, k1, k5]*SU3D[I4, k4, k7]*
       SU3F[I1, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I3, k1] - 
      9*SU3D[I4, k4, k5]*SU3F[6, k1, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I3, k1] + 9*I*SU3D[6, k1, k6]*SU3D[I1, k5, k6]*
       SU3F[I4, k4, k5]*SU3Delta[I2, k4]*SU3Delta[I3, k1] - 
      9*SU3D[I1, k5, k6]*SU3F[6, k1, k6]*SU3F[I4, k4, k5]*SU3Delta[I2, k4]*
       SU3Delta[I3, k1] - 9*I*SU3D[6, k1, k5]*SU3D[I1, k4, k7]*
       SU3F[I4, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I3, k1] - 
      9*SU3D[I1, k4, k5]*SU3F[6, k1, k7]*SU3F[I4, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I3, k1] + 9*SU3D[6, k1, k5]*SU3F[I1, k4, k7]*SU3F[I4, k5, k7]*
       SU3Delta[I2, k4]*SU3Delta[I3, k1] + 9*I*SU3F[6, k1, k6]*
       SU3F[I1, k4, k7]*SU3F[I4, k6, k7]*SU3Delta[I2, k4]*SU3Delta[I3, k1] + 
      8*SU3D[I1, I4, k2]*SU3Delta[6, I2]*SU3Delta[I3, k2] - 
      6*I*SU3F[I1, I4, k2]*SU3Delta[6, I2]*SU3Delta[I3, k2] + 
      2*SU3D[6, I4, k2]*SU3Delta[I1, I2]*SU3Delta[I3, k2] + 
      2*I*SU3F[6, I4, k2]*SU3Delta[I1, I2]*SU3Delta[I3, k2] - 
      2*SU3D[6, I1, k2]*SU3Delta[I2, I4]*SU3Delta[I3, k2] - 
      2*I*SU3F[6, I1, k2]*SU3Delta[I2, I4]*SU3Delta[I3, k2] - 
      6*SU3D[6, k1, k7]*SU3D[I1, I4, k5]*SU3D[k2, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I3, k2] - 9*SU3D[6, k1, k6]*SU3D[I1, I4, k7]*SU3D[k2, k6, k7]*
       SU3Delta[I2, k1]*SU3Delta[I3, k2] - 15*I*SU3D[I1, I4, k5]*
       SU3D[k2, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I2, k1]*SU3Delta[I3, k2] + 
      6*I*SU3D[6, k1, k6]*SU3D[k2, k5, k6]*SU3F[I1, I4, k5]*SU3Delta[I2, k1]*
       SU3Delta[I3, k2] + 3*SU3D[k2, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, I4, k5]*
       SU3Delta[I2, k1]*SU3Delta[I3, k2] - 9*I*SU3D[6, k1, k6]*
       SU3D[k2, k6, k7]*SU3F[I1, I4, k7]*SU3Delta[I2, k1]*SU3Delta[I3, k2] + 
      15*SU3D[I1, I4, k5]*SU3F[6, k1, k6]*SU3F[k2, k5, k6]*SU3Delta[I2, k1]*
       SU3Delta[I3, k2] + 3*I*SU3F[6, k1, k6]*SU3F[I1, I4, k5]*
       SU3F[k2, k5, k6]*SU3Delta[I2, k1]*SU3Delta[I3, k2] - 
      9*I*SU3D[6, k1, k7]*SU3D[I1, I4, k5]*SU3F[k2, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I3, k2] + 6*I*SU3D[6, k1, k5]*SU3D[I1, I4, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k1]*SU3Delta[I3, k2] + 
      6*SU3D[6, k1, k5]*SU3F[I1, I4, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I3, k2] - 9*SU3D[6, k1, k6]*SU3F[I1, I4, k7]*SU3F[k2, k6, k7]*
       SU3Delta[I2, k1]*SU3Delta[I3, k2] - 4*SU3D[I4, k1, k2]*SU3Delta[6, I1]*
       SU3Delta[I2, k1]*SU3Delta[I3, k2] - 10*SU3D[6, k1, k2]*
       SU3Delta[I1, I4]*SU3Delta[I2, k1]*SU3Delta[I3, k2] - 
      10*I*SU3F[6, k1, k2]*SU3Delta[I1, I4]*SU3Delta[I2, k1]*
       SU3Delta[I3, k2] - 6*SU3D[6, I4, k7]*SU3D[I1, k3, k5]*SU3D[k2, k5, k7]*
       SU3Delta[I2, k3]*SU3Delta[I3, k2] - 6*SU3D[6, I1, k7]*SU3D[I4, k3, k5]*
       SU3D[k2, k5, k7]*SU3Delta[I2, k3]*SU3Delta[I3, k2] - 
      6*I*SU3D[I4, k3, k5]*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3Delta[I2, k3]*
       SU3Delta[I3, k2] - 6*I*SU3D[I1, k3, k5]*SU3D[k2, k5, k6]*
       SU3F[6, I4, k6]*SU3Delta[I2, k3]*SU3Delta[I3, k2] + 
      6*I*SU3D[6, I4, k6]*SU3D[k2, k5, k6]*SU3F[I1, k3, k5]*SU3Delta[I2, k3]*
       SU3Delta[I3, k2] - 6*SU3D[k2, k5, k6]*SU3F[6, I4, k6]*SU3F[I1, k3, k5]*
       SU3Delta[I2, k3]*SU3Delta[I3, k2] + 6*I*SU3D[6, I1, k6]*
       SU3D[k2, k5, k6]*SU3F[I4, k3, k5]*SU3Delta[I2, k3]*SU3Delta[I3, k2] - 
      6*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3F[I4, k3, k5]*SU3Delta[I2, k3]*
       SU3Delta[I3, k2] + 6*I*SU3D[6, I4, k5]*SU3D[I1, k3, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k3]*SU3Delta[I3, k2] + 
      6*I*SU3D[6, I1, k5]*SU3D[I4, k3, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k3]*
       SU3Delta[I3, k2] + 6*SU3D[I4, k3, k5]*SU3F[6, I1, k7]*SU3F[k2, k5, k7]*
       SU3Delta[I2, k3]*SU3Delta[I3, k2] + 6*SU3D[I1, k3, k5]*SU3F[6, I4, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k3]*SU3Delta[I3, k2] + 
      6*SU3D[6, I4, k5]*SU3F[I1, k3, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k3]*
       SU3Delta[I3, k2] + 9*SU3D[6, I1, k5]*SU3F[I4, k3, k7]*SU3F[k2, k5, k7]*
       SU3Delta[I2, k3]*SU3Delta[I3, k2] + 6*I*SU3F[6, I4, k6]*
       SU3F[I1, k3, k7]*SU3F[k2, k6, k7]*SU3Delta[I2, k3]*SU3Delta[I3, k2] + 
      9*I*SU3F[6, I1, k6]*SU3F[I4, k3, k7]*SU3F[k2, k6, k7]*SU3Delta[I2, k3]*
       SU3Delta[I3, k2] - 4*SU3D[I4, k2, k3]*SU3Delta[6, I1]*SU3Delta[I2, k3]*
       SU3Delta[I3, k2] - 4*SU3D[I1, k2, k3]*SU3Delta[6, I4]*SU3Delta[I2, k3]*
       SU3Delta[I3, k2] - 4*I*SU3F[I1, k2, k3]*SU3Delta[6, I4]*
       SU3Delta[I2, k3]*SU3Delta[I3, k2] + 9*SU3D[6, I4, k7]*SU3D[I1, k4, k5]*
       SU3D[k2, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I3, k2] + 
      3*SU3D[6, I1, k7]*SU3D[I4, k4, k5]*SU3D[k2, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I3, k2] + 3*I*SU3D[I4, k4, k5]*SU3D[k2, k5, k6]*
       SU3F[6, I1, k6]*SU3Delta[I2, k4]*SU3Delta[I3, k2] + 
      9*I*SU3D[I1, k4, k5]*SU3D[k2, k5, k6]*SU3F[6, I4, k6]*SU3Delta[I2, k4]*
       SU3Delta[I3, k2] + 9*I*SU3D[6, I4, k6]*SU3D[k2, k5, k6]*
       SU3F[I1, k4, k5]*SU3Delta[I2, k4]*SU3Delta[I3, k2] - 
      9*SU3D[k2, k5, k6]*SU3F[6, I4, k6]*SU3F[I1, k4, k5]*SU3Delta[I2, k4]*
       SU3Delta[I3, k2] + 3*I*SU3D[6, I1, k6]*SU3D[k2, k5, k6]*
       SU3F[I4, k4, k5]*SU3Delta[I2, k4]*SU3Delta[I3, k2] - 
      3*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3F[I4, k4, k5]*SU3Delta[I2, k4]*
       SU3Delta[I3, k2] - 9*I*SU3D[6, I4, k5]*SU3D[I1, k4, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I3, k2] - 
      3*I*SU3D[6, I1, k5]*SU3D[I4, k4, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I3, k2] - 3*SU3D[I4, k4, k5]*SU3F[6, I1, k7]*SU3F[k2, k5, k7]*
       SU3Delta[I2, k4]*SU3Delta[I3, k2] - 9*SU3D[I1, k4, k5]*SU3F[6, I4, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I3, k2] + 
      9*SU3D[6, I4, k5]*SU3F[I1, k4, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I3, k2] + 9*I*SU3F[6, I4, k6]*SU3F[I1, k4, k7]*
       SU3F[k2, k6, k7]*SU3Delta[I2, k4]*SU3Delta[I3, k2] + 
      6*SU3D[I1, k2, k4]*SU3Delta[6, I4]*SU3Delta[I2, k4]*SU3Delta[I3, k2] - 
      6*I*SU3F[I1, k2, k4]*SU3Delta[6, I4]*SU3Delta[I2, k4]*
       SU3Delta[I3, k2] + 12*SU3D[I1, I4, k3]*SU3Delta[6, I2]*
       SU3Delta[I3, k3] + 9*SU3D[6, k1, k7]*SU3D[I1, k5, k7]*SU3D[I4, k3, k5]*
       SU3Delta[I2, k1]*SU3Delta[I3, k3] + 3*SU3D[6, k1, k7]*SU3D[I1, k3, k5]*
       SU3D[I4, k5, k7]*SU3Delta[I2, k1]*SU3Delta[I3, k3] + 
      9*I*SU3D[I1, k5, k6]*SU3D[I4, k3, k5]*SU3F[6, k1, k6]*SU3Delta[I2, k1]*
       SU3Delta[I3, k3] + 3*I*SU3D[I1, k3, k5]*SU3D[I4, k5, k6]*
       SU3F[6, k1, k6]*SU3Delta[I2, k1]*SU3Delta[I3, k3] - 
      3*I*SU3D[6, k1, k6]*SU3D[I4, k5, k6]*SU3F[I1, k3, k5]*SU3Delta[I2, k1]*
       SU3Delta[I3, k3] + 3*SU3D[I4, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, k3, k5]*
       SU3Delta[I2, k1]*SU3Delta[I3, k3] - 9*I*SU3D[6, k1, k5]*
       SU3D[I4, k3, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k1]*SU3Delta[I3, k3] - 
      9*SU3D[I4, k3, k5]*SU3F[6, k1, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I3, k3] - 9*I*SU3D[6, k1, k6]*SU3D[I1, k5, k6]*
       SU3F[I4, k3, k5]*SU3Delta[I2, k1]*SU3Delta[I3, k3] + 
      9*SU3D[I1, k5, k6]*SU3F[6, k1, k6]*SU3F[I4, k3, k5]*SU3Delta[I2, k1]*
       SU3Delta[I3, k3] - 3*SU3D[I1, k3, k5]*SU3F[6, k1, k6]*SU3F[I4, k5, k6]*
       SU3Delta[I2, k1]*SU3Delta[I3, k3] + 3*I*SU3F[6, k1, k6]*
       SU3F[I1, k3, k5]*SU3F[I4, k5, k6]*SU3Delta[I2, k1]*SU3Delta[I3, k3] + 
      3*I*SU3D[6, k1, k7]*SU3D[I1, k3, k5]*SU3F[I4, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I3, k3] - 3*SU3D[6, k1, k6]*SU3F[I1, k3, k7]*SU3F[I4, k6, k7]*
       SU3Delta[I2, k1]*SU3Delta[I3, k3] + 2*SU3D[I4, k1, k3]*SU3Delta[6, I1]*
       SU3Delta[I2, k1]*SU3Delta[I3, k3] - 6*SU3D[6, I4, k7]*SU3D[I1, k3, k5]*
       SU3D[k2, k5, k7]*SU3Delta[I2, k2]*SU3Delta[I3, k3] - 
      6*SU3D[6, I1, k7]*SU3D[I4, k3, k5]*SU3D[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I3, k3] - 6*I*SU3D[I4, k3, k5]*SU3D[k2, k5, k6]*
       SU3F[6, I1, k6]*SU3Delta[I2, k2]*SU3Delta[I3, k3] - 
      6*I*SU3D[I1, k3, k5]*SU3D[k2, k5, k6]*SU3F[6, I4, k6]*SU3Delta[I2, k2]*
       SU3Delta[I3, k3] + 6*I*SU3D[6, I4, k6]*SU3D[k2, k5, k6]*
       SU3F[I1, k3, k5]*SU3Delta[I2, k2]*SU3Delta[I3, k3] - 
      6*SU3D[k2, k5, k6]*SU3F[6, I4, k6]*SU3F[I1, k3, k5]*SU3Delta[I2, k2]*
       SU3Delta[I3, k3] + 6*I*SU3D[6, I1, k6]*SU3D[k2, k5, k6]*
       SU3F[I4, k3, k5]*SU3Delta[I2, k2]*SU3Delta[I3, k3] - 
      6*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3F[I4, k3, k5]*SU3Delta[I2, k2]*
       SU3Delta[I3, k3] + 6*I*SU3D[6, I4, k5]*SU3D[I1, k3, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k2]*SU3Delta[I3, k3] + 
      6*I*SU3D[6, I1, k5]*SU3D[I4, k3, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I3, k3] + 6*SU3D[I4, k3, k5]*SU3F[6, I1, k7]*SU3F[k2, k5, k7]*
       SU3Delta[I2, k2]*SU3Delta[I3, k3] + 6*SU3D[I1, k3, k5]*SU3F[6, I4, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k2]*SU3Delta[I3, k3] + 
      6*SU3D[6, I4, k5]*SU3F[I1, k3, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I3, k3] + 9*SU3D[6, I1, k5]*SU3F[I4, k3, k7]*SU3F[k2, k5, k7]*
       SU3Delta[I2, k2]*SU3Delta[I3, k3] + 6*I*SU3F[6, I4, k6]*
       SU3F[I1, k3, k7]*SU3F[k2, k6, k7]*SU3Delta[I2, k2]*SU3Delta[I3, k3] + 
      9*I*SU3F[6, I1, k6]*SU3F[I4, k3, k7]*SU3F[k2, k6, k7]*SU3Delta[I2, k2]*
       SU3Delta[I3, k3] - 4*SU3D[I4, k2, k3]*SU3Delta[6, I1]*SU3Delta[I2, k2]*
       SU3Delta[I3, k3] - 4*SU3D[I1, k2, k3]*SU3Delta[6, I4]*SU3Delta[I2, k2]*
       SU3Delta[I3, k3] - 4*I*SU3F[I1, k2, k3]*SU3Delta[6, I4]*
       SU3Delta[I2, k2]*SU3Delta[I3, k3] - 9*SU3D[6, I4, k7]*SU3D[I1, k5, k7]*
       SU3D[k3, k4, k5]*SU3Delta[I2, k4]*SU3Delta[I3, k3] - 
      6*SU3D[6, I1, k7]*SU3D[I4, k5, k7]*SU3D[k3, k4, k5]*SU3Delta[I2, k4]*
       SU3Delta[I3, k3] - 6*I*SU3D[I4, k5, k6]*SU3D[k3, k4, k5]*
       SU3F[6, I1, k6]*SU3Delta[I2, k4]*SU3Delta[I3, k3] - 
      9*I*SU3D[I1, k5, k6]*SU3D[k3, k4, k5]*SU3F[6, I4, k6]*SU3Delta[I2, k4]*
       SU3Delta[I3, k3] + 9*I*SU3D[6, I4, k5]*SU3D[k3, k4, k7]*
       SU3F[I1, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I3, k3] + 
      9*SU3D[k3, k4, k5]*SU3F[6, I4, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I3, k3] + 6*I*SU3D[6, I1, k5]*SU3D[k3, k4, k7]*
       SU3F[I4, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I3, k3] + 
      6*SU3D[k3, k4, k5]*SU3F[6, I1, k7]*SU3F[I4, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I3, k3] - 6*SU3D[I1, k3, k4]*SU3Delta[6, I4]*SU3Delta[I2, k4]*
       SU3Delta[I3, k3] - 6*I*SU3F[I1, k3, k4]*SU3Delta[6, I4]*
       SU3Delta[I2, k4]*SU3Delta[I3, k3] + 9*SU3D[6, k1, k7]*SU3D[I1, k5, k7]*
       SU3D[I4, k4, k5]*SU3Delta[I2, k1]*SU3Delta[I3, k4] + 
      9*SU3D[6, k1, k7]*SU3D[I1, k4, k5]*SU3D[I4, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I3, k4] + 9*I*SU3D[I1, k5, k6]*SU3D[I4, k4, k5]*
       SU3F[6, k1, k6]*SU3Delta[I2, k1]*SU3Delta[I3, k4] + 
      9*I*SU3D[I1, k4, k5]*SU3D[I4, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I2, k1]*
       SU3Delta[I3, k4] + 9*I*SU3D[6, k1, k6]*SU3D[I4, k5, k6]*
       SU3F[I1, k4, k5]*SU3Delta[I2, k1]*SU3Delta[I3, k4] - 
      9*SU3D[I4, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, k4, k5]*SU3Delta[I2, k1]*
       SU3Delta[I3, k4] - 9*I*SU3D[6, k1, k5]*SU3D[I4, k4, k7]*
       SU3F[I1, k5, k7]*SU3Delta[I2, k1]*SU3Delta[I3, k4] - 
      9*SU3D[I4, k4, k5]*SU3F[6, k1, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I3, k4] + 9*I*SU3D[6, k1, k6]*SU3D[I1, k5, k6]*
       SU3F[I4, k4, k5]*SU3Delta[I2, k1]*SU3Delta[I3, k4] - 
      9*SU3D[I1, k5, k6]*SU3F[6, k1, k6]*SU3F[I4, k4, k5]*SU3Delta[I2, k1]*
       SU3Delta[I3, k4] - 9*I*SU3D[6, k1, k5]*SU3D[I1, k4, k7]*
       SU3F[I4, k5, k7]*SU3Delta[I2, k1]*SU3Delta[I3, k4] - 
      9*SU3D[I1, k4, k5]*SU3F[6, k1, k7]*SU3F[I4, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I3, k4] + 9*SU3D[6, k1, k5]*SU3F[I1, k4, k7]*SU3F[I4, k5, k7]*
       SU3Delta[I2, k1]*SU3Delta[I3, k4] + 9*I*SU3F[6, k1, k6]*
       SU3F[I1, k4, k7]*SU3F[I4, k6, k7]*SU3Delta[I2, k1]*SU3Delta[I3, k4] + 
      9*SU3D[6, I4, k7]*SU3D[I1, k4, k5]*SU3D[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I3, k4] + 3*SU3D[6, I1, k7]*SU3D[I4, k4, k5]*SU3D[k2, k5, k7]*
       SU3Delta[I2, k2]*SU3Delta[I3, k4] + 3*I*SU3D[I4, k4, k5]*
       SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3Delta[I2, k2]*SU3Delta[I3, k4] + 
      9*I*SU3D[I1, k4, k5]*SU3D[k2, k5, k6]*SU3F[6, I4, k6]*SU3Delta[I2, k2]*
       SU3Delta[I3, k4] + 9*I*SU3D[6, I4, k6]*SU3D[k2, k5, k6]*
       SU3F[I1, k4, k5]*SU3Delta[I2, k2]*SU3Delta[I3, k4] - 
      9*SU3D[k2, k5, k6]*SU3F[6, I4, k6]*SU3F[I1, k4, k5]*SU3Delta[I2, k2]*
       SU3Delta[I3, k4] + 3*I*SU3D[6, I1, k6]*SU3D[k2, k5, k6]*
       SU3F[I4, k4, k5]*SU3Delta[I2, k2]*SU3Delta[I3, k4] - 
      3*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3F[I4, k4, k5]*SU3Delta[I2, k2]*
       SU3Delta[I3, k4] - 9*I*SU3D[6, I4, k5]*SU3D[I1, k4, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k2]*SU3Delta[I3, k4] - 
      3*I*SU3D[6, I1, k5]*SU3D[I4, k4, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I3, k4] - 3*SU3D[I4, k4, k5]*SU3F[6, I1, k7]*SU3F[k2, k5, k7]*
       SU3Delta[I2, k2]*SU3Delta[I3, k4] - 9*SU3D[I1, k4, k5]*SU3F[6, I4, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k2]*SU3Delta[I3, k4] + 
      9*SU3D[6, I4, k5]*SU3F[I1, k4, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I3, k4] + 9*I*SU3F[6, I4, k6]*SU3F[I1, k4, k7]*
       SU3F[k2, k6, k7]*SU3Delta[I2, k2]*SU3Delta[I3, k4] + 
      6*SU3D[I1, k2, k4]*SU3Delta[6, I4]*SU3Delta[I2, k2]*SU3Delta[I3, k4] - 
      6*I*SU3F[I1, k2, k4]*SU3Delta[6, I4]*SU3Delta[I2, k2]*
       SU3Delta[I3, k4] - 9*SU3D[6, I4, k7]*SU3D[I1, k5, k7]*SU3D[k3, k4, k5]*
       SU3Delta[I2, k3]*SU3Delta[I3, k4] - 6*SU3D[6, I1, k7]*SU3D[I4, k5, k7]*
       SU3D[k3, k4, k5]*SU3Delta[I2, k3]*SU3Delta[I3, k4] - 
      6*I*SU3D[I4, k5, k6]*SU3D[k3, k4, k5]*SU3F[6, I1, k6]*SU3Delta[I2, k3]*
       SU3Delta[I3, k4] - 9*I*SU3D[I1, k5, k6]*SU3D[k3, k4, k5]*
       SU3F[6, I4, k6]*SU3Delta[I2, k3]*SU3Delta[I3, k4] + 
      9*I*SU3D[6, I4, k5]*SU3D[k3, k4, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k3]*
       SU3Delta[I3, k4] + 9*SU3D[k3, k4, k5]*SU3F[6, I4, k7]*SU3F[I1, k5, k7]*
       SU3Delta[I2, k3]*SU3Delta[I3, k4] + 6*I*SU3D[6, I1, k5]*
       SU3D[k3, k4, k7]*SU3F[I4, k5, k7]*SU3Delta[I2, k3]*SU3Delta[I3, k4] + 
      6*SU3D[k3, k4, k5]*SU3F[6, I1, k7]*SU3F[I4, k5, k7]*SU3Delta[I2, k3]*
       SU3Delta[I3, k4] - 6*SU3D[I1, k3, k4]*SU3Delta[6, I4]*SU3Delta[I2, k3]*
       SU3Delta[I3, k4] - 6*I*SU3F[I1, k3, k4]*SU3Delta[6, I4]*
       SU3Delta[I2, k3]*SU3Delta[I3, k4] - 12*SU3D[6, I1, k1]*
       SU3Delta[I2, I3]*SU3Delta[I4, k1] + 12*I*SU3F[6, I1, k1]*
       SU3Delta[I2, I3]*SU3Delta[I4, k1] - 8*SU3D[6, I1, k2]*SU3Delta[I2, I3]*
       SU3Delta[I4, k2] - 8*I*SU3F[6, I1, k2]*SU3Delta[I2, I3]*
       SU3Delta[I4, k2])*UCouplingConstant[ChPTW3[2], 1])/
   (18*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {-((-10*SU3D[I1, I3, k1]*SU3Delta[6, I4]*SU3Delta[I2, k1] + 
      8*SU3D[6, I3, k1]*SU3Delta[I1, I4]*SU3Delta[I2, k1] - 
      8*I*SU3F[6, I3, k1]*SU3Delta[I1, I4]*SU3Delta[I2, k1] + 
      8*SU3D[I1, I3, k2]*SU3Delta[6, I4]*SU3Delta[I2, k2] - 
      6*I*SU3F[I1, I3, k2]*SU3Delta[6, I4]*SU3Delta[I2, k2] + 
      2*SU3D[6, I3, k2]*SU3Delta[I1, I4]*SU3Delta[I2, k2] + 
      2*I*SU3F[6, I3, k2]*SU3Delta[I1, I4]*SU3Delta[I2, k2] + 
      12*SU3D[I1, I3, k3]*SU3Delta[6, I4]*SU3Delta[I2, k3] + 
      12*SU3D[6, I1, k1]*SU3Delta[I2, k1]*SU3Delta[I3, I4] - 
      12*I*SU3F[6, I1, k1]*SU3Delta[I2, k1]*SU3Delta[I3, I4] - 
      2*SU3D[6, I1, k2]*SU3Delta[I2, k2]*SU3Delta[I3, I4] - 
      2*I*SU3F[6, I1, k2]*SU3Delta[I2, k2]*SU3Delta[I3, I4] - 
      10*SU3D[I1, I3, k1]*SU3Delta[6, I2]*SU3Delta[I4, k1] + 
      8*SU3D[6, I3, k1]*SU3Delta[I1, I2]*SU3Delta[I4, k1] - 
      8*I*SU3F[6, I3, k1]*SU3Delta[I1, I2]*SU3Delta[I4, k1] + 
      12*SU3D[6, I1, k1]*SU3Delta[I2, I3]*SU3Delta[I4, k1] - 
      12*I*SU3F[6, I1, k1]*SU3Delta[I2, I3]*SU3Delta[I4, k1] - 
      6*SU3D[6, k1, k7]*SU3D[I1, I3, k5]*SU3D[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I4, k1] - 9*SU3D[6, k1, k6]*SU3D[I1, I3, k7]*SU3D[k2, k6, k7]*
       SU3Delta[I2, k2]*SU3Delta[I4, k1] - 15*I*SU3D[I1, I3, k5]*
       SU3D[k2, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I2, k2]*SU3Delta[I4, k1] + 
      6*I*SU3D[6, k1, k6]*SU3D[k2, k5, k6]*SU3F[I1, I3, k5]*SU3Delta[I2, k2]*
       SU3Delta[I4, k1] + 3*SU3D[k2, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, I3, k5]*
       SU3Delta[I2, k2]*SU3Delta[I4, k1] - 9*I*SU3D[6, k1, k6]*
       SU3D[k2, k6, k7]*SU3F[I1, I3, k7]*SU3Delta[I2, k2]*SU3Delta[I4, k1] + 
      15*SU3D[I1, I3, k5]*SU3F[6, k1, k6]*SU3F[k2, k5, k6]*SU3Delta[I2, k2]*
       SU3Delta[I4, k1] + 3*I*SU3F[6, k1, k6]*SU3F[I1, I3, k5]*
       SU3F[k2, k5, k6]*SU3Delta[I2, k2]*SU3Delta[I4, k1] - 
      9*I*SU3D[6, k1, k7]*SU3D[I1, I3, k5]*SU3F[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I4, k1] + 6*I*SU3D[6, k1, k5]*SU3D[I1, I3, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k2]*SU3Delta[I4, k1] + 
      6*SU3D[6, k1, k5]*SU3F[I1, I3, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I4, k1] - 9*SU3D[6, k1, k6]*SU3F[I1, I3, k7]*SU3F[k2, k6, k7]*
       SU3Delta[I2, k2]*SU3Delta[I4, k1] - 4*SU3D[I3, k1, k2]*SU3Delta[6, I1]*
       SU3Delta[I2, k2]*SU3Delta[I4, k1] - 10*SU3D[6, k1, k2]*
       SU3Delta[I1, I3]*SU3Delta[I2, k2]*SU3Delta[I4, k1] - 
      10*I*SU3F[6, k1, k2]*SU3Delta[I1, I3]*SU3Delta[I2, k2]*
       SU3Delta[I4, k1] + 9*SU3D[6, k1, k7]*SU3D[I1, k5, k7]*SU3D[I3, k3, k5]*
       SU3Delta[I2, k3]*SU3Delta[I4, k1] + 3*SU3D[6, k1, k7]*SU3D[I1, k3, k5]*
       SU3D[I3, k5, k7]*SU3Delta[I2, k3]*SU3Delta[I4, k1] + 
      9*I*SU3D[I1, k5, k6]*SU3D[I3, k3, k5]*SU3F[6, k1, k6]*SU3Delta[I2, k3]*
       SU3Delta[I4, k1] + 3*I*SU3D[I1, k3, k5]*SU3D[I3, k5, k6]*
       SU3F[6, k1, k6]*SU3Delta[I2, k3]*SU3Delta[I4, k1] - 
      3*I*SU3D[6, k1, k6]*SU3D[I3, k5, k6]*SU3F[I1, k3, k5]*SU3Delta[I2, k3]*
       SU3Delta[I4, k1] + 3*SU3D[I3, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, k3, k5]*
       SU3Delta[I2, k3]*SU3Delta[I4, k1] - 9*I*SU3D[6, k1, k5]*
       SU3D[I3, k3, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k3]*SU3Delta[I4, k1] - 
      9*SU3D[I3, k3, k5]*SU3F[6, k1, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k3]*
       SU3Delta[I4, k1] - 9*I*SU3D[6, k1, k6]*SU3D[I1, k5, k6]*
       SU3F[I3, k3, k5]*SU3Delta[I2, k3]*SU3Delta[I4, k1] + 
      9*SU3D[I1, k5, k6]*SU3F[6, k1, k6]*SU3F[I3, k3, k5]*SU3Delta[I2, k3]*
       SU3Delta[I4, k1] - 3*SU3D[I1, k3, k5]*SU3F[6, k1, k6]*SU3F[I3, k5, k6]*
       SU3Delta[I2, k3]*SU3Delta[I4, k1] + 3*I*SU3F[6, k1, k6]*
       SU3F[I1, k3, k5]*SU3F[I3, k5, k6]*SU3Delta[I2, k3]*SU3Delta[I4, k1] + 
      3*I*SU3D[6, k1, k7]*SU3D[I1, k3, k5]*SU3F[I3, k5, k7]*SU3Delta[I2, k3]*
       SU3Delta[I4, k1] - 3*SU3D[6, k1, k6]*SU3F[I1, k3, k7]*SU3F[I3, k6, k7]*
       SU3Delta[I2, k3]*SU3Delta[I4, k1] + 2*SU3D[I3, k1, k3]*SU3Delta[6, I1]*
       SU3Delta[I2, k3]*SU3Delta[I4, k1] + 9*SU3D[6, k1, k7]*SU3D[I1, k5, k7]*
       SU3D[I3, k4, k5]*SU3Delta[I2, k4]*SU3Delta[I4, k1] + 
      9*SU3D[6, k1, k7]*SU3D[I1, k4, k5]*SU3D[I3, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I4, k1] + 9*I*SU3D[I1, k5, k6]*SU3D[I3, k4, k5]*
       SU3F[6, k1, k6]*SU3Delta[I2, k4]*SU3Delta[I4, k1] + 
      9*I*SU3D[I1, k4, k5]*SU3D[I3, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I2, k4]*
       SU3Delta[I4, k1] + 9*I*SU3D[6, k1, k6]*SU3D[I3, k5, k6]*
       SU3F[I1, k4, k5]*SU3Delta[I2, k4]*SU3Delta[I4, k1] - 
      9*SU3D[I3, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, k4, k5]*SU3Delta[I2, k4]*
       SU3Delta[I4, k1] - 9*I*SU3D[6, k1, k5]*SU3D[I3, k4, k7]*
       SU3F[I1, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I4, k1] - 
      9*SU3D[I3, k4, k5]*SU3F[6, k1, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I4, k1] + 9*I*SU3D[6, k1, k6]*SU3D[I1, k5, k6]*
       SU3F[I3, k4, k5]*SU3Delta[I2, k4]*SU3Delta[I4, k1] - 
      9*SU3D[I1, k5, k6]*SU3F[6, k1, k6]*SU3F[I3, k4, k5]*SU3Delta[I2, k4]*
       SU3Delta[I4, k1] - 9*I*SU3D[6, k1, k5]*SU3D[I1, k4, k7]*
       SU3F[I3, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I4, k1] - 
      9*SU3D[I1, k4, k5]*SU3F[6, k1, k7]*SU3F[I3, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I4, k1] + 9*SU3D[6, k1, k5]*SU3F[I1, k4, k7]*SU3F[I3, k5, k7]*
       SU3Delta[I2, k4]*SU3Delta[I4, k1] + 9*I*SU3F[6, k1, k6]*
       SU3F[I1, k4, k7]*SU3F[I3, k6, k7]*SU3Delta[I2, k4]*SU3Delta[I4, k1] + 
      8*SU3D[I1, I3, k2]*SU3Delta[6, I2]*SU3Delta[I4, k2] - 
      6*I*SU3F[I1, I3, k2]*SU3Delta[6, I2]*SU3Delta[I4, k2] + 
      2*SU3D[6, I3, k2]*SU3Delta[I1, I2]*SU3Delta[I4, k2] + 
      2*I*SU3F[6, I3, k2]*SU3Delta[I1, I2]*SU3Delta[I4, k2] - 
      2*SU3D[6, I1, k2]*SU3Delta[I2, I3]*SU3Delta[I4, k2] - 
      2*I*SU3F[6, I1, k2]*SU3Delta[I2, I3]*SU3Delta[I4, k2] - 
      6*SU3D[6, k1, k7]*SU3D[I1, I3, k5]*SU3D[k2, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I4, k2] - 9*SU3D[6, k1, k6]*SU3D[I1, I3, k7]*SU3D[k2, k6, k7]*
       SU3Delta[I2, k1]*SU3Delta[I4, k2] - 15*I*SU3D[I1, I3, k5]*
       SU3D[k2, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I2, k1]*SU3Delta[I4, k2] + 
      6*I*SU3D[6, k1, k6]*SU3D[k2, k5, k6]*SU3F[I1, I3, k5]*SU3Delta[I2, k1]*
       SU3Delta[I4, k2] + 3*SU3D[k2, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, I3, k5]*
       SU3Delta[I2, k1]*SU3Delta[I4, k2] - 9*I*SU3D[6, k1, k6]*
       SU3D[k2, k6, k7]*SU3F[I1, I3, k7]*SU3Delta[I2, k1]*SU3Delta[I4, k2] + 
      15*SU3D[I1, I3, k5]*SU3F[6, k1, k6]*SU3F[k2, k5, k6]*SU3Delta[I2, k1]*
       SU3Delta[I4, k2] + 3*I*SU3F[6, k1, k6]*SU3F[I1, I3, k5]*
       SU3F[k2, k5, k6]*SU3Delta[I2, k1]*SU3Delta[I4, k2] - 
      9*I*SU3D[6, k1, k7]*SU3D[I1, I3, k5]*SU3F[k2, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I4, k2] + 6*I*SU3D[6, k1, k5]*SU3D[I1, I3, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k1]*SU3Delta[I4, k2] + 
      6*SU3D[6, k1, k5]*SU3F[I1, I3, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I4, k2] - 9*SU3D[6, k1, k6]*SU3F[I1, I3, k7]*SU3F[k2, k6, k7]*
       SU3Delta[I2, k1]*SU3Delta[I4, k2] - 4*SU3D[I3, k1, k2]*SU3Delta[6, I1]*
       SU3Delta[I2, k1]*SU3Delta[I4, k2] - 10*SU3D[6, k1, k2]*
       SU3Delta[I1, I3]*SU3Delta[I2, k1]*SU3Delta[I4, k2] - 
      10*I*SU3F[6, k1, k2]*SU3Delta[I1, I3]*SU3Delta[I2, k1]*
       SU3Delta[I4, k2] - 6*SU3D[6, I3, k7]*SU3D[I1, k3, k5]*SU3D[k2, k5, k7]*
       SU3Delta[I2, k3]*SU3Delta[I4, k2] - 6*SU3D[6, I1, k7]*SU3D[I3, k3, k5]*
       SU3D[k2, k5, k7]*SU3Delta[I2, k3]*SU3Delta[I4, k2] - 
      6*I*SU3D[I3, k3, k5]*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3Delta[I2, k3]*
       SU3Delta[I4, k2] - 6*I*SU3D[I1, k3, k5]*SU3D[k2, k5, k6]*
       SU3F[6, I3, k6]*SU3Delta[I2, k3]*SU3Delta[I4, k2] + 
      6*I*SU3D[6, I3, k6]*SU3D[k2, k5, k6]*SU3F[I1, k3, k5]*SU3Delta[I2, k3]*
       SU3Delta[I4, k2] - 6*SU3D[k2, k5, k6]*SU3F[6, I3, k6]*SU3F[I1, k3, k5]*
       SU3Delta[I2, k3]*SU3Delta[I4, k2] + 6*I*SU3D[6, I1, k6]*
       SU3D[k2, k5, k6]*SU3F[I3, k3, k5]*SU3Delta[I2, k3]*SU3Delta[I4, k2] - 
      6*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3F[I3, k3, k5]*SU3Delta[I2, k3]*
       SU3Delta[I4, k2] + 6*I*SU3D[6, I3, k5]*SU3D[I1, k3, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k3]*SU3Delta[I4, k2] + 
      6*I*SU3D[6, I1, k5]*SU3D[I3, k3, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k3]*
       SU3Delta[I4, k2] + 6*SU3D[I3, k3, k5]*SU3F[6, I1, k7]*SU3F[k2, k5, k7]*
       SU3Delta[I2, k3]*SU3Delta[I4, k2] + 6*SU3D[I1, k3, k5]*SU3F[6, I3, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k3]*SU3Delta[I4, k2] + 
      6*SU3D[6, I3, k5]*SU3F[I1, k3, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k3]*
       SU3Delta[I4, k2] + 9*SU3D[6, I1, k5]*SU3F[I3, k3, k7]*SU3F[k2, k5, k7]*
       SU3Delta[I2, k3]*SU3Delta[I4, k2] + 6*I*SU3F[6, I3, k6]*
       SU3F[I1, k3, k7]*SU3F[k2, k6, k7]*SU3Delta[I2, k3]*SU3Delta[I4, k2] + 
      9*I*SU3F[6, I1, k6]*SU3F[I3, k3, k7]*SU3F[k2, k6, k7]*SU3Delta[I2, k3]*
       SU3Delta[I4, k2] - 4*SU3D[I3, k2, k3]*SU3Delta[6, I1]*SU3Delta[I2, k3]*
       SU3Delta[I4, k2] - 4*SU3D[I1, k2, k3]*SU3Delta[6, I3]*SU3Delta[I2, k3]*
       SU3Delta[I4, k2] - 4*I*SU3F[I1, k2, k3]*SU3Delta[6, I3]*
       SU3Delta[I2, k3]*SU3Delta[I4, k2] + 9*SU3D[6, I3, k7]*SU3D[I1, k4, k5]*
       SU3D[k2, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I4, k2] + 
      3*SU3D[6, I1, k7]*SU3D[I3, k4, k5]*SU3D[k2, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I4, k2] + 3*I*SU3D[I3, k4, k5]*SU3D[k2, k5, k6]*
       SU3F[6, I1, k6]*SU3Delta[I2, k4]*SU3Delta[I4, k2] + 
      9*I*SU3D[I1, k4, k5]*SU3D[k2, k5, k6]*SU3F[6, I3, k6]*SU3Delta[I2, k4]*
       SU3Delta[I4, k2] + 9*I*SU3D[6, I3, k6]*SU3D[k2, k5, k6]*
       SU3F[I1, k4, k5]*SU3Delta[I2, k4]*SU3Delta[I4, k2] - 
      9*SU3D[k2, k5, k6]*SU3F[6, I3, k6]*SU3F[I1, k4, k5]*SU3Delta[I2, k4]*
       SU3Delta[I4, k2] + 3*I*SU3D[6, I1, k6]*SU3D[k2, k5, k6]*
       SU3F[I3, k4, k5]*SU3Delta[I2, k4]*SU3Delta[I4, k2] - 
      3*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3F[I3, k4, k5]*SU3Delta[I2, k4]*
       SU3Delta[I4, k2] - 9*I*SU3D[6, I3, k5]*SU3D[I1, k4, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I4, k2] - 
      3*I*SU3D[6, I1, k5]*SU3D[I3, k4, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I4, k2] - 3*SU3D[I3, k4, k5]*SU3F[6, I1, k7]*SU3F[k2, k5, k7]*
       SU3Delta[I2, k4]*SU3Delta[I4, k2] - 9*SU3D[I1, k4, k5]*SU3F[6, I3, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I4, k2] + 
      9*SU3D[6, I3, k5]*SU3F[I1, k4, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I4, k2] + 9*I*SU3F[6, I3, k6]*SU3F[I1, k4, k7]*
       SU3F[k2, k6, k7]*SU3Delta[I2, k4]*SU3Delta[I4, k2] + 
      6*SU3D[I1, k2, k4]*SU3Delta[6, I3]*SU3Delta[I2, k4]*SU3Delta[I4, k2] - 
      6*I*SU3F[I1, k2, k4]*SU3Delta[6, I3]*SU3Delta[I2, k4]*
       SU3Delta[I4, k2] + 12*SU3D[I1, I3, k3]*SU3Delta[6, I2]*
       SU3Delta[I4, k3] + 9*SU3D[6, k1, k7]*SU3D[I1, k5, k7]*SU3D[I3, k3, k5]*
       SU3Delta[I2, k1]*SU3Delta[I4, k3] + 3*SU3D[6, k1, k7]*SU3D[I1, k3, k5]*
       SU3D[I3, k5, k7]*SU3Delta[I2, k1]*SU3Delta[I4, k3] + 
      9*I*SU3D[I1, k5, k6]*SU3D[I3, k3, k5]*SU3F[6, k1, k6]*SU3Delta[I2, k1]*
       SU3Delta[I4, k3] + 3*I*SU3D[I1, k3, k5]*SU3D[I3, k5, k6]*
       SU3F[6, k1, k6]*SU3Delta[I2, k1]*SU3Delta[I4, k3] - 
      3*I*SU3D[6, k1, k6]*SU3D[I3, k5, k6]*SU3F[I1, k3, k5]*SU3Delta[I2, k1]*
       SU3Delta[I4, k3] + 3*SU3D[I3, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, k3, k5]*
       SU3Delta[I2, k1]*SU3Delta[I4, k3] - 9*I*SU3D[6, k1, k5]*
       SU3D[I3, k3, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k1]*SU3Delta[I4, k3] - 
      9*SU3D[I3, k3, k5]*SU3F[6, k1, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I4, k3] - 9*I*SU3D[6, k1, k6]*SU3D[I1, k5, k6]*
       SU3F[I3, k3, k5]*SU3Delta[I2, k1]*SU3Delta[I4, k3] + 
      9*SU3D[I1, k5, k6]*SU3F[6, k1, k6]*SU3F[I3, k3, k5]*SU3Delta[I2, k1]*
       SU3Delta[I4, k3] - 3*SU3D[I1, k3, k5]*SU3F[6, k1, k6]*SU3F[I3, k5, k6]*
       SU3Delta[I2, k1]*SU3Delta[I4, k3] + 3*I*SU3F[6, k1, k6]*
       SU3F[I1, k3, k5]*SU3F[I3, k5, k6]*SU3Delta[I2, k1]*SU3Delta[I4, k3] + 
      3*I*SU3D[6, k1, k7]*SU3D[I1, k3, k5]*SU3F[I3, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I4, k3] - 3*SU3D[6, k1, k6]*SU3F[I1, k3, k7]*SU3F[I3, k6, k7]*
       SU3Delta[I2, k1]*SU3Delta[I4, k3] + 2*SU3D[I3, k1, k3]*SU3Delta[6, I1]*
       SU3Delta[I2, k1]*SU3Delta[I4, k3] - 6*SU3D[6, I3, k7]*SU3D[I1, k3, k5]*
       SU3D[k2, k5, k7]*SU3Delta[I2, k2]*SU3Delta[I4, k3] - 
      6*SU3D[6, I1, k7]*SU3D[I3, k3, k5]*SU3D[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I4, k3] - 6*I*SU3D[I3, k3, k5]*SU3D[k2, k5, k6]*
       SU3F[6, I1, k6]*SU3Delta[I2, k2]*SU3Delta[I4, k3] - 
      6*I*SU3D[I1, k3, k5]*SU3D[k2, k5, k6]*SU3F[6, I3, k6]*SU3Delta[I2, k2]*
       SU3Delta[I4, k3] + 6*I*SU3D[6, I3, k6]*SU3D[k2, k5, k6]*
       SU3F[I1, k3, k5]*SU3Delta[I2, k2]*SU3Delta[I4, k3] - 
      6*SU3D[k2, k5, k6]*SU3F[6, I3, k6]*SU3F[I1, k3, k5]*SU3Delta[I2, k2]*
       SU3Delta[I4, k3] + 6*I*SU3D[6, I1, k6]*SU3D[k2, k5, k6]*
       SU3F[I3, k3, k5]*SU3Delta[I2, k2]*SU3Delta[I4, k3] - 
      6*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3F[I3, k3, k5]*SU3Delta[I2, k2]*
       SU3Delta[I4, k3] + 6*I*SU3D[6, I3, k5]*SU3D[I1, k3, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k2]*SU3Delta[I4, k3] + 
      6*I*SU3D[6, I1, k5]*SU3D[I3, k3, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I4, k3] + 6*SU3D[I3, k3, k5]*SU3F[6, I1, k7]*SU3F[k2, k5, k7]*
       SU3Delta[I2, k2]*SU3Delta[I4, k3] + 6*SU3D[I1, k3, k5]*SU3F[6, I3, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k2]*SU3Delta[I4, k3] + 
      6*SU3D[6, I3, k5]*SU3F[I1, k3, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I4, k3] + 9*SU3D[6, I1, k5]*SU3F[I3, k3, k7]*SU3F[k2, k5, k7]*
       SU3Delta[I2, k2]*SU3Delta[I4, k3] + 6*I*SU3F[6, I3, k6]*
       SU3F[I1, k3, k7]*SU3F[k2, k6, k7]*SU3Delta[I2, k2]*SU3Delta[I4, k3] + 
      9*I*SU3F[6, I1, k6]*SU3F[I3, k3, k7]*SU3F[k2, k6, k7]*SU3Delta[I2, k2]*
       SU3Delta[I4, k3] - 4*SU3D[I3, k2, k3]*SU3Delta[6, I1]*SU3Delta[I2, k2]*
       SU3Delta[I4, k3] - 4*SU3D[I1, k2, k3]*SU3Delta[6, I3]*SU3Delta[I2, k2]*
       SU3Delta[I4, k3] - 4*I*SU3F[I1, k2, k3]*SU3Delta[6, I3]*
       SU3Delta[I2, k2]*SU3Delta[I4, k3] - 20*SU3D[6, I1, I3]*
       SU3Delta[I2, k3]*SU3Delta[I4, k3] + 4*I*SU3F[6, I1, I3]*
       SU3Delta[I2, k3]*SU3Delta[I4, k3] - 9*SU3D[6, I3, k7]*SU3D[I1, k5, k7]*
       SU3D[k3, k4, k5]*SU3Delta[I2, k4]*SU3Delta[I4, k3] - 
      6*SU3D[6, I1, k7]*SU3D[I3, k5, k7]*SU3D[k3, k4, k5]*SU3Delta[I2, k4]*
       SU3Delta[I4, k3] - 6*I*SU3D[I3, k5, k6]*SU3D[k3, k4, k5]*
       SU3F[6, I1, k6]*SU3Delta[I2, k4]*SU3Delta[I4, k3] - 
      9*I*SU3D[I1, k5, k6]*SU3D[k3, k4, k5]*SU3F[6, I3, k6]*SU3Delta[I2, k4]*
       SU3Delta[I4, k3] + 9*I*SU3D[6, I3, k5]*SU3D[k3, k4, k7]*
       SU3F[I1, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I4, k3] + 
      9*SU3D[k3, k4, k5]*SU3F[6, I3, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I4, k3] + 6*I*SU3D[6, I1, k5]*SU3D[k3, k4, k7]*
       SU3F[I3, k5, k7]*SU3Delta[I2, k4]*SU3Delta[I4, k3] + 
      6*SU3D[k3, k4, k5]*SU3F[6, I1, k7]*SU3F[I3, k5, k7]*SU3Delta[I2, k4]*
       SU3Delta[I4, k3] - 6*SU3D[I1, k3, k4]*SU3Delta[6, I3]*SU3Delta[I2, k4]*
       SU3Delta[I4, k3] - 6*I*SU3F[I1, k3, k4]*SU3Delta[6, I3]*
       SU3Delta[I2, k4]*SU3Delta[I4, k3] + 9*SU3D[6, k1, k7]*SU3D[I1, k5, k7]*
       SU3D[I3, k4, k5]*SU3Delta[I2, k1]*SU3Delta[I4, k4] + 
      9*SU3D[6, k1, k7]*SU3D[I1, k4, k5]*SU3D[I3, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I4, k4] + 9*I*SU3D[I1, k5, k6]*SU3D[I3, k4, k5]*
       SU3F[6, k1, k6]*SU3Delta[I2, k1]*SU3Delta[I4, k4] + 
      9*I*SU3D[I1, k4, k5]*SU3D[I3, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I2, k1]*
       SU3Delta[I4, k4] + 9*I*SU3D[6, k1, k6]*SU3D[I3, k5, k6]*
       SU3F[I1, k4, k5]*SU3Delta[I2, k1]*SU3Delta[I4, k4] - 
      9*SU3D[I3, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, k4, k5]*SU3Delta[I2, k1]*
       SU3Delta[I4, k4] - 9*I*SU3D[6, k1, k5]*SU3D[I3, k4, k7]*
       SU3F[I1, k5, k7]*SU3Delta[I2, k1]*SU3Delta[I4, k4] - 
      9*SU3D[I3, k4, k5]*SU3F[6, k1, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I4, k4] + 9*I*SU3D[6, k1, k6]*SU3D[I1, k5, k6]*
       SU3F[I3, k4, k5]*SU3Delta[I2, k1]*SU3Delta[I4, k4] - 
      9*SU3D[I1, k5, k6]*SU3F[6, k1, k6]*SU3F[I3, k4, k5]*SU3Delta[I2, k1]*
       SU3Delta[I4, k4] - 9*I*SU3D[6, k1, k5]*SU3D[I1, k4, k7]*
       SU3F[I3, k5, k7]*SU3Delta[I2, k1]*SU3Delta[I4, k4] - 
      9*SU3D[I1, k4, k5]*SU3F[6, k1, k7]*SU3F[I3, k5, k7]*SU3Delta[I2, k1]*
       SU3Delta[I4, k4] + 9*SU3D[6, k1, k5]*SU3F[I1, k4, k7]*SU3F[I3, k5, k7]*
       SU3Delta[I2, k1]*SU3Delta[I4, k4] + 9*I*SU3F[6, k1, k6]*
       SU3F[I1, k4, k7]*SU3F[I3, k6, k7]*SU3Delta[I2, k1]*SU3Delta[I4, k4] + 
      9*SU3D[6, I3, k7]*SU3D[I1, k4, k5]*SU3D[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I4, k4] + 3*SU3D[6, I1, k7]*SU3D[I3, k4, k5]*SU3D[k2, k5, k7]*
       SU3Delta[I2, k2]*SU3Delta[I4, k4] + 3*I*SU3D[I3, k4, k5]*
       SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3Delta[I2, k2]*SU3Delta[I4, k4] + 
      9*I*SU3D[I1, k4, k5]*SU3D[k2, k5, k6]*SU3F[6, I3, k6]*SU3Delta[I2, k2]*
       SU3Delta[I4, k4] + 9*I*SU3D[6, I3, k6]*SU3D[k2, k5, k6]*
       SU3F[I1, k4, k5]*SU3Delta[I2, k2]*SU3Delta[I4, k4] - 
      9*SU3D[k2, k5, k6]*SU3F[6, I3, k6]*SU3F[I1, k4, k5]*SU3Delta[I2, k2]*
       SU3Delta[I4, k4] + 3*I*SU3D[6, I1, k6]*SU3D[k2, k5, k6]*
       SU3F[I3, k4, k5]*SU3Delta[I2, k2]*SU3Delta[I4, k4] - 
      3*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3F[I3, k4, k5]*SU3Delta[I2, k2]*
       SU3Delta[I4, k4] - 9*I*SU3D[6, I3, k5]*SU3D[I1, k4, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k2]*SU3Delta[I4, k4] - 
      3*I*SU3D[6, I1, k5]*SU3D[I3, k4, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I4, k4] - 3*SU3D[I3, k4, k5]*SU3F[6, I1, k7]*SU3F[k2, k5, k7]*
       SU3Delta[I2, k2]*SU3Delta[I4, k4] - 9*SU3D[I1, k4, k5]*SU3F[6, I3, k7]*
       SU3F[k2, k5, k7]*SU3Delta[I2, k2]*SU3Delta[I4, k4] + 
      9*SU3D[6, I3, k5]*SU3F[I1, k4, k7]*SU3F[k2, k5, k7]*SU3Delta[I2, k2]*
       SU3Delta[I4, k4] + 9*I*SU3F[6, I3, k6]*SU3F[I1, k4, k7]*
       SU3F[k2, k6, k7]*SU3Delta[I2, k2]*SU3Delta[I4, k4] + 
      6*SU3D[I1, k2, k4]*SU3Delta[6, I3]*SU3Delta[I2, k2]*SU3Delta[I4, k4] - 
      6*I*SU3F[I1, k2, k4]*SU3Delta[6, I3]*SU3Delta[I2, k2]*
       SU3Delta[I4, k4] - 9*SU3D[6, I3, k7]*SU3D[I1, k5, k7]*SU3D[k3, k4, k5]*
       SU3Delta[I2, k3]*SU3Delta[I4, k4] - 6*SU3D[6, I1, k7]*SU3D[I3, k5, k7]*
       SU3D[k3, k4, k5]*SU3Delta[I2, k3]*SU3Delta[I4, k4] - 
      6*I*SU3D[I3, k5, k6]*SU3D[k3, k4, k5]*SU3F[6, I1, k6]*SU3Delta[I2, k3]*
       SU3Delta[I4, k4] - 9*I*SU3D[I1, k5, k6]*SU3D[k3, k4, k5]*
       SU3F[6, I3, k6]*SU3Delta[I2, k3]*SU3Delta[I4, k4] + 
      9*I*SU3D[6, I3, k5]*SU3D[k3, k4, k7]*SU3F[I1, k5, k7]*SU3Delta[I2, k3]*
       SU3Delta[I4, k4] + 9*SU3D[k3, k4, k5]*SU3F[6, I3, k7]*SU3F[I1, k5, k7]*
       SU3Delta[I2, k3]*SU3Delta[I4, k4] + 6*I*SU3D[6, I1, k5]*
       SU3D[k3, k4, k7]*SU3F[I3, k5, k7]*SU3Delta[I2, k3]*SU3Delta[I4, k4] + 
      6*SU3D[k3, k4, k5]*SU3F[6, I1, k7]*SU3F[I3, k5, k7]*SU3Delta[I2, k3]*
       SU3Delta[I4, k4] - 6*SU3D[I1, k3, k4]*SU3Delta[6, I3]*SU3Delta[I2, k3]*
       SU3Delta[I4, k4] - 6*I*SU3F[I1, k3, k4]*SU3Delta[6, I3]*
       SU3Delta[I2, k3]*SU3Delta[I4, k4])*UCouplingConstant[ChPTW3[2], 1])/
   (18*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}, 
 {((10*SU3D[I1, I2, k1]*SU3Delta[6, I4]*SU3Delta[I3, k1] - 
     8*SU3D[6, I2, k1]*SU3Delta[I1, I4]*SU3Delta[I3, k1] + 
     8*I*SU3F[6, I2, k1]*SU3Delta[I1, I4]*SU3Delta[I3, k1] - 
     12*SU3D[6, I1, k1]*SU3Delta[I2, I4]*SU3Delta[I3, k1] + 
     12*I*SU3F[6, I1, k1]*SU3Delta[I2, I4]*SU3Delta[I3, k1] - 
     8*SU3D[I1, I2, k2]*SU3Delta[6, I4]*SU3Delta[I3, k2] + 
     6*I*SU3F[I1, I2, k2]*SU3Delta[6, I4]*SU3Delta[I3, k2] - 
     2*SU3D[6, I2, k2]*SU3Delta[I1, I4]*SU3Delta[I3, k2] - 
     2*I*SU3F[6, I2, k2]*SU3Delta[I1, I4]*SU3Delta[I3, k2] + 
     2*SU3D[6, I1, k2]*SU3Delta[I2, I4]*SU3Delta[I3, k2] + 
     2*I*SU3F[6, I1, k2]*SU3Delta[I2, I4]*SU3Delta[I3, k2] - 
     12*SU3D[I1, I2, k3]*SU3Delta[6, I4]*SU3Delta[I3, k3] + 
     10*SU3D[I1, I2, k1]*SU3Delta[6, I3]*SU3Delta[I4, k1] - 
     8*SU3D[6, I2, k1]*SU3Delta[I1, I3]*SU3Delta[I4, k1] + 
     8*I*SU3F[6, I2, k1]*SU3Delta[I1, I3]*SU3Delta[I4, k1] - 
     12*SU3D[6, I1, k1]*SU3Delta[I2, I3]*SU3Delta[I4, k1] + 
     12*I*SU3F[6, I1, k1]*SU3Delta[I2, I3]*SU3Delta[I4, k1] + 
     6*SU3D[6, k1, k7]*SU3D[I1, I2, k5]*SU3D[k2, k5, k7]*SU3Delta[I3, k2]*
      SU3Delta[I4, k1] + 9*SU3D[6, k1, k6]*SU3D[I1, I2, k7]*SU3D[k2, k6, k7]*
      SU3Delta[I3, k2]*SU3Delta[I4, k1] + 15*I*SU3D[I1, I2, k5]*
      SU3D[k2, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I3, k2]*SU3Delta[I4, k1] - 
     6*I*SU3D[6, k1, k6]*SU3D[k2, k5, k6]*SU3F[I1, I2, k5]*SU3Delta[I3, k2]*
      SU3Delta[I4, k1] - 3*SU3D[k2, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, I2, k5]*
      SU3Delta[I3, k2]*SU3Delta[I4, k1] + 9*I*SU3D[6, k1, k6]*
      SU3D[k2, k6, k7]*SU3F[I1, I2, k7]*SU3Delta[I3, k2]*SU3Delta[I4, k1] - 
     15*SU3D[I1, I2, k5]*SU3F[6, k1, k6]*SU3F[k2, k5, k6]*SU3Delta[I3, k2]*
      SU3Delta[I4, k1] - 3*I*SU3F[6, k1, k6]*SU3F[I1, I2, k5]*
      SU3F[k2, k5, k6]*SU3Delta[I3, k2]*SU3Delta[I4, k1] + 
     9*I*SU3D[6, k1, k7]*SU3D[I1, I2, k5]*SU3F[k2, k5, k7]*SU3Delta[I3, k2]*
      SU3Delta[I4, k1] - 6*I*SU3D[6, k1, k5]*SU3D[I1, I2, k7]*
      SU3F[k2, k5, k7]*SU3Delta[I3, k2]*SU3Delta[I4, k1] - 
     6*SU3D[6, k1, k5]*SU3F[I1, I2, k7]*SU3F[k2, k5, k7]*SU3Delta[I3, k2]*
      SU3Delta[I4, k1] + 9*SU3D[6, k1, k6]*SU3F[I1, I2, k7]*SU3F[k2, k6, k7]*
      SU3Delta[I3, k2]*SU3Delta[I4, k1] + 4*SU3D[I2, k1, k2]*SU3Delta[6, I1]*
      SU3Delta[I3, k2]*SU3Delta[I4, k1] + 10*SU3D[6, k1, k2]*SU3Delta[I1, I2]*
      SU3Delta[I3, k2]*SU3Delta[I4, k1] + 10*I*SU3F[6, k1, k2]*
      SU3Delta[I1, I2]*SU3Delta[I3, k2]*SU3Delta[I4, k1] - 
     9*SU3D[6, k1, k7]*SU3D[I1, k5, k7]*SU3D[I2, k3, k5]*SU3Delta[I3, k3]*
      SU3Delta[I4, k1] - 3*SU3D[6, k1, k7]*SU3D[I1, k3, k5]*SU3D[I2, k5, k7]*
      SU3Delta[I3, k3]*SU3Delta[I4, k1] - 9*I*SU3D[I1, k5, k6]*
      SU3D[I2, k3, k5]*SU3F[6, k1, k6]*SU3Delta[I3, k3]*SU3Delta[I4, k1] - 
     3*I*SU3D[I1, k3, k5]*SU3D[I2, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I3, k3]*
      SU3Delta[I4, k1] + 3*I*SU3D[6, k1, k6]*SU3D[I2, k5, k6]*
      SU3F[I1, k3, k5]*SU3Delta[I3, k3]*SU3Delta[I4, k1] - 
     3*SU3D[I2, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, k3, k5]*SU3Delta[I3, k3]*
      SU3Delta[I4, k1] + 9*I*SU3D[6, k1, k5]*SU3D[I2, k3, k7]*
      SU3F[I1, k5, k7]*SU3Delta[I3, k3]*SU3Delta[I4, k1] + 
     9*SU3D[I2, k3, k5]*SU3F[6, k1, k7]*SU3F[I1, k5, k7]*SU3Delta[I3, k3]*
      SU3Delta[I4, k1] + 9*I*SU3D[6, k1, k6]*SU3D[I1, k5, k6]*
      SU3F[I2, k3, k5]*SU3Delta[I3, k3]*SU3Delta[I4, k1] - 
     9*SU3D[I1, k5, k6]*SU3F[6, k1, k6]*SU3F[I2, k3, k5]*SU3Delta[I3, k3]*
      SU3Delta[I4, k1] + 3*SU3D[I1, k3, k5]*SU3F[6, k1, k6]*SU3F[I2, k5, k6]*
      SU3Delta[I3, k3]*SU3Delta[I4, k1] - 3*I*SU3F[6, k1, k6]*
      SU3F[I1, k3, k5]*SU3F[I2, k5, k6]*SU3Delta[I3, k3]*SU3Delta[I4, k1] - 
     3*I*SU3D[6, k1, k7]*SU3D[I1, k3, k5]*SU3F[I2, k5, k7]*SU3Delta[I3, k3]*
      SU3Delta[I4, k1] + 3*SU3D[6, k1, k6]*SU3F[I1, k3, k7]*SU3F[I2, k6, k7]*
      SU3Delta[I3, k3]*SU3Delta[I4, k1] - 2*SU3D[I2, k1, k3]*SU3Delta[6, I1]*
      SU3Delta[I3, k3]*SU3Delta[I4, k1] - 9*SU3D[6, k1, k7]*SU3D[I1, k5, k7]*
      SU3D[I2, k4, k5]*SU3Delta[I3, k4]*SU3Delta[I4, k1] - 
     9*SU3D[6, k1, k7]*SU3D[I1, k4, k5]*SU3D[I2, k5, k7]*SU3Delta[I3, k4]*
      SU3Delta[I4, k1] - 9*I*SU3D[I1, k5, k6]*SU3D[I2, k4, k5]*
      SU3F[6, k1, k6]*SU3Delta[I3, k4]*SU3Delta[I4, k1] - 
     9*I*SU3D[I1, k4, k5]*SU3D[I2, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I3, k4]*
      SU3Delta[I4, k1] - 9*I*SU3D[6, k1, k6]*SU3D[I2, k5, k6]*
      SU3F[I1, k4, k5]*SU3Delta[I3, k4]*SU3Delta[I4, k1] + 
     9*SU3D[I2, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, k4, k5]*SU3Delta[I3, k4]*
      SU3Delta[I4, k1] + 9*I*SU3D[6, k1, k5]*SU3D[I2, k4, k7]*
      SU3F[I1, k5, k7]*SU3Delta[I3, k4]*SU3Delta[I4, k1] + 
     9*SU3D[I2, k4, k5]*SU3F[6, k1, k7]*SU3F[I1, k5, k7]*SU3Delta[I3, k4]*
      SU3Delta[I4, k1] - 9*I*SU3D[6, k1, k6]*SU3D[I1, k5, k6]*
      SU3F[I2, k4, k5]*SU3Delta[I3, k4]*SU3Delta[I4, k1] + 
     9*SU3D[I1, k5, k6]*SU3F[6, k1, k6]*SU3F[I2, k4, k5]*SU3Delta[I3, k4]*
      SU3Delta[I4, k1] + 9*I*SU3D[6, k1, k5]*SU3D[I1, k4, k7]*
      SU3F[I2, k5, k7]*SU3Delta[I3, k4]*SU3Delta[I4, k1] + 
     9*SU3D[I1, k4, k5]*SU3F[6, k1, k7]*SU3F[I2, k5, k7]*SU3Delta[I3, k4]*
      SU3Delta[I4, k1] - 9*SU3D[6, k1, k5]*SU3F[I1, k4, k7]*SU3F[I2, k5, k7]*
      SU3Delta[I3, k4]*SU3Delta[I4, k1] - 9*I*SU3F[6, k1, k6]*
      SU3F[I1, k4, k7]*SU3F[I2, k6, k7]*SU3Delta[I3, k4]*SU3Delta[I4, k1] - 
     8*SU3D[I1, I2, k2]*SU3Delta[6, I3]*SU3Delta[I4, k2] + 
     6*I*SU3F[I1, I2, k2]*SU3Delta[6, I3]*SU3Delta[I4, k2] - 
     2*SU3D[6, I2, k2]*SU3Delta[I1, I3]*SU3Delta[I4, k2] - 
     2*I*SU3F[6, I2, k2]*SU3Delta[I1, I3]*SU3Delta[I4, k2] + 
     2*SU3D[6, I1, k2]*SU3Delta[I2, I3]*SU3Delta[I4, k2] + 
     2*I*SU3F[6, I1, k2]*SU3Delta[I2, I3]*SU3Delta[I4, k2] + 
     6*SU3D[6, k1, k7]*SU3D[I1, I2, k5]*SU3D[k2, k5, k7]*SU3Delta[I3, k1]*
      SU3Delta[I4, k2] + 9*SU3D[6, k1, k6]*SU3D[I1, I2, k7]*SU3D[k2, k6, k7]*
      SU3Delta[I3, k1]*SU3Delta[I4, k2] + 15*I*SU3D[I1, I2, k5]*
      SU3D[k2, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I3, k1]*SU3Delta[I4, k2] - 
     6*I*SU3D[6, k1, k6]*SU3D[k2, k5, k6]*SU3F[I1, I2, k5]*SU3Delta[I3, k1]*
      SU3Delta[I4, k2] - 3*SU3D[k2, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, I2, k5]*
      SU3Delta[I3, k1]*SU3Delta[I4, k2] + 9*I*SU3D[6, k1, k6]*
      SU3D[k2, k6, k7]*SU3F[I1, I2, k7]*SU3Delta[I3, k1]*SU3Delta[I4, k2] - 
     15*SU3D[I1, I2, k5]*SU3F[6, k1, k6]*SU3F[k2, k5, k6]*SU3Delta[I3, k1]*
      SU3Delta[I4, k2] - 3*I*SU3F[6, k1, k6]*SU3F[I1, I2, k5]*
      SU3F[k2, k5, k6]*SU3Delta[I3, k1]*SU3Delta[I4, k2] + 
     9*I*SU3D[6, k1, k7]*SU3D[I1, I2, k5]*SU3F[k2, k5, k7]*SU3Delta[I3, k1]*
      SU3Delta[I4, k2] - 6*I*SU3D[6, k1, k5]*SU3D[I1, I2, k7]*
      SU3F[k2, k5, k7]*SU3Delta[I3, k1]*SU3Delta[I4, k2] - 
     6*SU3D[6, k1, k5]*SU3F[I1, I2, k7]*SU3F[k2, k5, k7]*SU3Delta[I3, k1]*
      SU3Delta[I4, k2] + 9*SU3D[6, k1, k6]*SU3F[I1, I2, k7]*SU3F[k2, k6, k7]*
      SU3Delta[I3, k1]*SU3Delta[I4, k2] + 4*SU3D[I2, k1, k2]*SU3Delta[6, I1]*
      SU3Delta[I3, k1]*SU3Delta[I4, k2] + 10*SU3D[6, k1, k2]*SU3Delta[I1, I2]*
      SU3Delta[I3, k1]*SU3Delta[I4, k2] + 10*I*SU3F[6, k1, k2]*
      SU3Delta[I1, I2]*SU3Delta[I3, k1]*SU3Delta[I4, k2] + 
     6*SU3D[6, I2, k7]*SU3D[I1, k3, k5]*SU3D[k2, k5, k7]*SU3Delta[I3, k3]*
      SU3Delta[I4, k2] + 6*SU3D[6, I1, k7]*SU3D[I2, k3, k5]*SU3D[k2, k5, k7]*
      SU3Delta[I3, k3]*SU3Delta[I4, k2] + 6*I*SU3D[I2, k3, k5]*
      SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3Delta[I3, k3]*SU3Delta[I4, k2] + 
     6*I*SU3D[I1, k3, k5]*SU3D[k2, k5, k6]*SU3F[6, I2, k6]*SU3Delta[I3, k3]*
      SU3Delta[I4, k2] - 6*I*SU3D[6, I2, k6]*SU3D[k2, k5, k6]*
      SU3F[I1, k3, k5]*SU3Delta[I3, k3]*SU3Delta[I4, k2] + 
     6*SU3D[k2, k5, k6]*SU3F[6, I2, k6]*SU3F[I1, k3, k5]*SU3Delta[I3, k3]*
      SU3Delta[I4, k2] - 6*I*SU3D[6, I1, k6]*SU3D[k2, k5, k6]*
      SU3F[I2, k3, k5]*SU3Delta[I3, k3]*SU3Delta[I4, k2] + 
     6*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3F[I2, k3, k5]*SU3Delta[I3, k3]*
      SU3Delta[I4, k2] - 6*I*SU3D[6, I2, k5]*SU3D[I1, k3, k7]*
      SU3F[k2, k5, k7]*SU3Delta[I3, k3]*SU3Delta[I4, k2] - 
     6*I*SU3D[6, I1, k5]*SU3D[I2, k3, k7]*SU3F[k2, k5, k7]*SU3Delta[I3, k3]*
      SU3Delta[I4, k2] - 6*SU3D[I2, k3, k5]*SU3F[6, I1, k7]*SU3F[k2, k5, k7]*
      SU3Delta[I3, k3]*SU3Delta[I4, k2] - 6*SU3D[I1, k3, k5]*SU3F[6, I2, k7]*
      SU3F[k2, k5, k7]*SU3Delta[I3, k3]*SU3Delta[I4, k2] - 
     6*SU3D[6, I2, k5]*SU3F[I1, k3, k7]*SU3F[k2, k5, k7]*SU3Delta[I3, k3]*
      SU3Delta[I4, k2] - 9*SU3D[6, I1, k5]*SU3F[I2, k3, k7]*SU3F[k2, k5, k7]*
      SU3Delta[I3, k3]*SU3Delta[I4, k2] - 6*I*SU3F[6, I2, k6]*
      SU3F[I1, k3, k7]*SU3F[k2, k6, k7]*SU3Delta[I3, k3]*SU3Delta[I4, k2] - 
     9*I*SU3F[6, I1, k6]*SU3F[I2, k3, k7]*SU3F[k2, k6, k7]*SU3Delta[I3, k3]*
      SU3Delta[I4, k2] + 4*SU3D[I2, k2, k3]*SU3Delta[6, I1]*SU3Delta[I3, k3]*
      SU3Delta[I4, k2] + 4*SU3D[I1, k2, k3]*SU3Delta[6, I2]*SU3Delta[I3, k3]*
      SU3Delta[I4, k2] + 4*I*SU3F[I1, k2, k3]*SU3Delta[6, I2]*
      SU3Delta[I3, k3]*SU3Delta[I4, k2] - 9*SU3D[6, I2, k7]*SU3D[I1, k4, k5]*
      SU3D[k2, k5, k7]*SU3Delta[I3, k4]*SU3Delta[I4, k2] - 
     3*SU3D[6, I1, k7]*SU3D[I2, k4, k5]*SU3D[k2, k5, k7]*SU3Delta[I3, k4]*
      SU3Delta[I4, k2] - 3*I*SU3D[I2, k4, k5]*SU3D[k2, k5, k6]*
      SU3F[6, I1, k6]*SU3Delta[I3, k4]*SU3Delta[I4, k2] - 
     9*I*SU3D[I1, k4, k5]*SU3D[k2, k5, k6]*SU3F[6, I2, k6]*SU3Delta[I3, k4]*
      SU3Delta[I4, k2] - 9*I*SU3D[6, I2, k6]*SU3D[k2, k5, k6]*
      SU3F[I1, k4, k5]*SU3Delta[I3, k4]*SU3Delta[I4, k2] + 
     9*SU3D[k2, k5, k6]*SU3F[6, I2, k6]*SU3F[I1, k4, k5]*SU3Delta[I3, k4]*
      SU3Delta[I4, k2] - 3*I*SU3D[6, I1, k6]*SU3D[k2, k5, k6]*
      SU3F[I2, k4, k5]*SU3Delta[I3, k4]*SU3Delta[I4, k2] + 
     3*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3F[I2, k4, k5]*SU3Delta[I3, k4]*
      SU3Delta[I4, k2] + 9*I*SU3D[6, I2, k5]*SU3D[I1, k4, k7]*
      SU3F[k2, k5, k7]*SU3Delta[I3, k4]*SU3Delta[I4, k2] + 
     3*I*SU3D[6, I1, k5]*SU3D[I2, k4, k7]*SU3F[k2, k5, k7]*SU3Delta[I3, k4]*
      SU3Delta[I4, k2] + 3*SU3D[I2, k4, k5]*SU3F[6, I1, k7]*SU3F[k2, k5, k7]*
      SU3Delta[I3, k4]*SU3Delta[I4, k2] + 9*SU3D[I1, k4, k5]*SU3F[6, I2, k7]*
      SU3F[k2, k5, k7]*SU3Delta[I3, k4]*SU3Delta[I4, k2] - 
     9*SU3D[6, I2, k5]*SU3F[I1, k4, k7]*SU3F[k2, k5, k7]*SU3Delta[I3, k4]*
      SU3Delta[I4, k2] - 9*I*SU3F[6, I2, k6]*SU3F[I1, k4, k7]*
      SU3F[k2, k6, k7]*SU3Delta[I3, k4]*SU3Delta[I4, k2] - 
     6*SU3D[I1, k2, k4]*SU3Delta[6, I2]*SU3Delta[I3, k4]*SU3Delta[I4, k2] + 
     6*I*SU3F[I1, k2, k4]*SU3Delta[6, I2]*SU3Delta[I3, k4]*SU3Delta[I4, k2] - 
     12*SU3D[I1, I2, k3]*SU3Delta[6, I3]*SU3Delta[I4, k3] - 
     9*SU3D[6, k1, k7]*SU3D[I1, k5, k7]*SU3D[I2, k3, k5]*SU3Delta[I3, k1]*
      SU3Delta[I4, k3] - 3*SU3D[6, k1, k7]*SU3D[I1, k3, k5]*SU3D[I2, k5, k7]*
      SU3Delta[I3, k1]*SU3Delta[I4, k3] - 9*I*SU3D[I1, k5, k6]*
      SU3D[I2, k3, k5]*SU3F[6, k1, k6]*SU3Delta[I3, k1]*SU3Delta[I4, k3] - 
     3*I*SU3D[I1, k3, k5]*SU3D[I2, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I3, k1]*
      SU3Delta[I4, k3] + 3*I*SU3D[6, k1, k6]*SU3D[I2, k5, k6]*
      SU3F[I1, k3, k5]*SU3Delta[I3, k1]*SU3Delta[I4, k3] - 
     3*SU3D[I2, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, k3, k5]*SU3Delta[I3, k1]*
      SU3Delta[I4, k3] + 9*I*SU3D[6, k1, k5]*SU3D[I2, k3, k7]*
      SU3F[I1, k5, k7]*SU3Delta[I3, k1]*SU3Delta[I4, k3] + 
     9*SU3D[I2, k3, k5]*SU3F[6, k1, k7]*SU3F[I1, k5, k7]*SU3Delta[I3, k1]*
      SU3Delta[I4, k3] + 9*I*SU3D[6, k1, k6]*SU3D[I1, k5, k6]*
      SU3F[I2, k3, k5]*SU3Delta[I3, k1]*SU3Delta[I4, k3] - 
     9*SU3D[I1, k5, k6]*SU3F[6, k1, k6]*SU3F[I2, k3, k5]*SU3Delta[I3, k1]*
      SU3Delta[I4, k3] + 3*SU3D[I1, k3, k5]*SU3F[6, k1, k6]*SU3F[I2, k5, k6]*
      SU3Delta[I3, k1]*SU3Delta[I4, k3] - 3*I*SU3F[6, k1, k6]*
      SU3F[I1, k3, k5]*SU3F[I2, k5, k6]*SU3Delta[I3, k1]*SU3Delta[I4, k3] - 
     3*I*SU3D[6, k1, k7]*SU3D[I1, k3, k5]*SU3F[I2, k5, k7]*SU3Delta[I3, k1]*
      SU3Delta[I4, k3] + 3*SU3D[6, k1, k6]*SU3F[I1, k3, k7]*SU3F[I2, k6, k7]*
      SU3Delta[I3, k1]*SU3Delta[I4, k3] - 2*SU3D[I2, k1, k3]*SU3Delta[6, I1]*
      SU3Delta[I3, k1]*SU3Delta[I4, k3] + 6*SU3D[6, I2, k7]*SU3D[I1, k3, k5]*
      SU3D[k2, k5, k7]*SU3Delta[I3, k2]*SU3Delta[I4, k3] + 
     6*SU3D[6, I1, k7]*SU3D[I2, k3, k5]*SU3D[k2, k5, k7]*SU3Delta[I3, k2]*
      SU3Delta[I4, k3] + 6*I*SU3D[I2, k3, k5]*SU3D[k2, k5, k6]*
      SU3F[6, I1, k6]*SU3Delta[I3, k2]*SU3Delta[I4, k3] + 
     6*I*SU3D[I1, k3, k5]*SU3D[k2, k5, k6]*SU3F[6, I2, k6]*SU3Delta[I3, k2]*
      SU3Delta[I4, k3] - 6*I*SU3D[6, I2, k6]*SU3D[k2, k5, k6]*
      SU3F[I1, k3, k5]*SU3Delta[I3, k2]*SU3Delta[I4, k3] + 
     6*SU3D[k2, k5, k6]*SU3F[6, I2, k6]*SU3F[I1, k3, k5]*SU3Delta[I3, k2]*
      SU3Delta[I4, k3] - 6*I*SU3D[6, I1, k6]*SU3D[k2, k5, k6]*
      SU3F[I2, k3, k5]*SU3Delta[I3, k2]*SU3Delta[I4, k3] + 
     6*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3F[I2, k3, k5]*SU3Delta[I3, k2]*
      SU3Delta[I4, k3] - 6*I*SU3D[6, I2, k5]*SU3D[I1, k3, k7]*
      SU3F[k2, k5, k7]*SU3Delta[I3, k2]*SU3Delta[I4, k3] - 
     6*I*SU3D[6, I1, k5]*SU3D[I2, k3, k7]*SU3F[k2, k5, k7]*SU3Delta[I3, k2]*
      SU3Delta[I4, k3] - 6*SU3D[I2, k3, k5]*SU3F[6, I1, k7]*SU3F[k2, k5, k7]*
      SU3Delta[I3, k2]*SU3Delta[I4, k3] - 6*SU3D[I1, k3, k5]*SU3F[6, I2, k7]*
      SU3F[k2, k5, k7]*SU3Delta[I3, k2]*SU3Delta[I4, k3] - 
     6*SU3D[6, I2, k5]*SU3F[I1, k3, k7]*SU3F[k2, k5, k7]*SU3Delta[I3, k2]*
      SU3Delta[I4, k3] - 9*SU3D[6, I1, k5]*SU3F[I2, k3, k7]*SU3F[k2, k5, k7]*
      SU3Delta[I3, k2]*SU3Delta[I4, k3] - 6*I*SU3F[6, I2, k6]*
      SU3F[I1, k3, k7]*SU3F[k2, k6, k7]*SU3Delta[I3, k2]*SU3Delta[I4, k3] - 
     9*I*SU3F[6, I1, k6]*SU3F[I2, k3, k7]*SU3F[k2, k6, k7]*SU3Delta[I3, k2]*
      SU3Delta[I4, k3] + 4*SU3D[I2, k2, k3]*SU3Delta[6, I1]*SU3Delta[I3, k2]*
      SU3Delta[I4, k3] + 4*SU3D[I1, k2, k3]*SU3Delta[6, I2]*SU3Delta[I3, k2]*
      SU3Delta[I4, k3] + 4*I*SU3F[I1, k2, k3]*SU3Delta[6, I2]*
      SU3Delta[I3, k2]*SU3Delta[I4, k3] + 20*SU3D[6, I1, I2]*SU3Delta[I3, k3]*
      SU3Delta[I4, k3] - 4*I*SU3F[6, I1, I2]*SU3Delta[I3, k3]*
      SU3Delta[I4, k3] + 9*SU3D[6, I2, k7]*SU3D[I1, k5, k7]*SU3D[k3, k4, k5]*
      SU3Delta[I3, k4]*SU3Delta[I4, k3] + 6*SU3D[6, I1, k7]*SU3D[I2, k5, k7]*
      SU3D[k3, k4, k5]*SU3Delta[I3, k4]*SU3Delta[I4, k3] + 
     6*I*SU3D[I2, k5, k6]*SU3D[k3, k4, k5]*SU3F[6, I1, k6]*SU3Delta[I3, k4]*
      SU3Delta[I4, k3] + 9*I*SU3D[I1, k5, k6]*SU3D[k3, k4, k5]*
      SU3F[6, I2, k6]*SU3Delta[I3, k4]*SU3Delta[I4, k3] - 
     9*I*SU3D[6, I2, k5]*SU3D[k3, k4, k7]*SU3F[I1, k5, k7]*SU3Delta[I3, k4]*
      SU3Delta[I4, k3] - 9*SU3D[k3, k4, k5]*SU3F[6, I2, k7]*SU3F[I1, k5, k7]*
      SU3Delta[I3, k4]*SU3Delta[I4, k3] - 6*I*SU3D[6, I1, k5]*
      SU3D[k3, k4, k7]*SU3F[I2, k5, k7]*SU3Delta[I3, k4]*SU3Delta[I4, k3] - 
     6*SU3D[k3, k4, k5]*SU3F[6, I1, k7]*SU3F[I2, k5, k7]*SU3Delta[I3, k4]*
      SU3Delta[I4, k3] + 6*SU3D[I1, k3, k4]*SU3Delta[6, I2]*SU3Delta[I3, k4]*
      SU3Delta[I4, k3] + 6*I*SU3F[I1, k3, k4]*SU3Delta[6, I2]*
      SU3Delta[I3, k4]*SU3Delta[I4, k3] - 9*SU3D[6, k1, k7]*SU3D[I1, k5, k7]*
      SU3D[I2, k4, k5]*SU3Delta[I3, k1]*SU3Delta[I4, k4] - 
     9*SU3D[6, k1, k7]*SU3D[I1, k4, k5]*SU3D[I2, k5, k7]*SU3Delta[I3, k1]*
      SU3Delta[I4, k4] - 9*I*SU3D[I1, k5, k6]*SU3D[I2, k4, k5]*
      SU3F[6, k1, k6]*SU3Delta[I3, k1]*SU3Delta[I4, k4] - 
     9*I*SU3D[I1, k4, k5]*SU3D[I2, k5, k6]*SU3F[6, k1, k6]*SU3Delta[I3, k1]*
      SU3Delta[I4, k4] - 9*I*SU3D[6, k1, k6]*SU3D[I2, k5, k6]*
      SU3F[I1, k4, k5]*SU3Delta[I3, k1]*SU3Delta[I4, k4] + 
     9*SU3D[I2, k5, k6]*SU3F[6, k1, k6]*SU3F[I1, k4, k5]*SU3Delta[I3, k1]*
      SU3Delta[I4, k4] + 9*I*SU3D[6, k1, k5]*SU3D[I2, k4, k7]*
      SU3F[I1, k5, k7]*SU3Delta[I3, k1]*SU3Delta[I4, k4] + 
     9*SU3D[I2, k4, k5]*SU3F[6, k1, k7]*SU3F[I1, k5, k7]*SU3Delta[I3, k1]*
      SU3Delta[I4, k4] - 9*I*SU3D[6, k1, k6]*SU3D[I1, k5, k6]*
      SU3F[I2, k4, k5]*SU3Delta[I3, k1]*SU3Delta[I4, k4] + 
     9*SU3D[I1, k5, k6]*SU3F[6, k1, k6]*SU3F[I2, k4, k5]*SU3Delta[I3, k1]*
      SU3Delta[I4, k4] + 9*I*SU3D[6, k1, k5]*SU3D[I1, k4, k7]*
      SU3F[I2, k5, k7]*SU3Delta[I3, k1]*SU3Delta[I4, k4] + 
     9*SU3D[I1, k4, k5]*SU3F[6, k1, k7]*SU3F[I2, k5, k7]*SU3Delta[I3, k1]*
      SU3Delta[I4, k4] - 9*SU3D[6, k1, k5]*SU3F[I1, k4, k7]*SU3F[I2, k5, k7]*
      SU3Delta[I3, k1]*SU3Delta[I4, k4] - 9*I*SU3F[6, k1, k6]*
      SU3F[I1, k4, k7]*SU3F[I2, k6, k7]*SU3Delta[I3, k1]*SU3Delta[I4, k4] - 
     9*SU3D[6, I2, k7]*SU3D[I1, k4, k5]*SU3D[k2, k5, k7]*SU3Delta[I3, k2]*
      SU3Delta[I4, k4] - 3*SU3D[6, I1, k7]*SU3D[I2, k4, k5]*SU3D[k2, k5, k7]*
      SU3Delta[I3, k2]*SU3Delta[I4, k4] - 3*I*SU3D[I2, k4, k5]*
      SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3Delta[I3, k2]*SU3Delta[I4, k4] - 
     9*I*SU3D[I1, k4, k5]*SU3D[k2, k5, k6]*SU3F[6, I2, k6]*SU3Delta[I3, k2]*
      SU3Delta[I4, k4] - 9*I*SU3D[6, I2, k6]*SU3D[k2, k5, k6]*
      SU3F[I1, k4, k5]*SU3Delta[I3, k2]*SU3Delta[I4, k4] + 
     9*SU3D[k2, k5, k6]*SU3F[6, I2, k6]*SU3F[I1, k4, k5]*SU3Delta[I3, k2]*
      SU3Delta[I4, k4] - 3*I*SU3D[6, I1, k6]*SU3D[k2, k5, k6]*
      SU3F[I2, k4, k5]*SU3Delta[I3, k2]*SU3Delta[I4, k4] + 
     3*SU3D[k2, k5, k6]*SU3F[6, I1, k6]*SU3F[I2, k4, k5]*SU3Delta[I3, k2]*
      SU3Delta[I4, k4] + 9*I*SU3D[6, I2, k5]*SU3D[I1, k4, k7]*
      SU3F[k2, k5, k7]*SU3Delta[I3, k2]*SU3Delta[I4, k4] + 
     3*I*SU3D[6, I1, k5]*SU3D[I2, k4, k7]*SU3F[k2, k5, k7]*SU3Delta[I3, k2]*
      SU3Delta[I4, k4] + 3*SU3D[I2, k4, k5]*SU3F[6, I1, k7]*SU3F[k2, k5, k7]*
      SU3Delta[I3, k2]*SU3Delta[I4, k4] + 9*SU3D[I1, k4, k5]*SU3F[6, I2, k7]*
      SU3F[k2, k5, k7]*SU3Delta[I3, k2]*SU3Delta[I4, k4] - 
     9*SU3D[6, I2, k5]*SU3F[I1, k4, k7]*SU3F[k2, k5, k7]*SU3Delta[I3, k2]*
      SU3Delta[I4, k4] - 9*I*SU3F[6, I2, k6]*SU3F[I1, k4, k7]*
      SU3F[k2, k6, k7]*SU3Delta[I3, k2]*SU3Delta[I4, k4] - 
     6*SU3D[I1, k2, k4]*SU3Delta[6, I2]*SU3Delta[I3, k2]*SU3Delta[I4, k4] + 
     6*I*SU3F[I1, k2, k4]*SU3Delta[6, I2]*SU3Delta[I3, k2]*SU3Delta[I4, k4] + 
     9*SU3D[6, I2, k7]*SU3D[I1, k5, k7]*SU3D[k3, k4, k5]*SU3Delta[I3, k3]*
      SU3Delta[I4, k4] + 6*SU3D[6, I1, k7]*SU3D[I2, k5, k7]*SU3D[k3, k4, k5]*
      SU3Delta[I3, k3]*SU3Delta[I4, k4] + 6*I*SU3D[I2, k5, k6]*
      SU3D[k3, k4, k5]*SU3F[6, I1, k6]*SU3Delta[I3, k3]*SU3Delta[I4, k4] + 
     9*I*SU3D[I1, k5, k6]*SU3D[k3, k4, k5]*SU3F[6, I2, k6]*SU3Delta[I3, k3]*
      SU3Delta[I4, k4] - 9*I*SU3D[6, I2, k5]*SU3D[k3, k4, k7]*
      SU3F[I1, k5, k7]*SU3Delta[I3, k3]*SU3Delta[I4, k4] - 
     9*SU3D[k3, k4, k5]*SU3F[6, I2, k7]*SU3F[I1, k5, k7]*SU3Delta[I3, k3]*
      SU3Delta[I4, k4] - 6*I*SU3D[6, I1, k5]*SU3D[k3, k4, k7]*
      SU3F[I2, k5, k7]*SU3Delta[I3, k3]*SU3Delta[I4, k4] - 
     6*SU3D[k3, k4, k5]*SU3F[6, I1, k7]*SU3F[I2, k5, k7]*SU3Delta[I3, k3]*
      SU3Delta[I4, k4] + 6*SU3D[I1, k3, k4]*SU3Delta[6, I2]*SU3Delta[I3, k3]*
      SU3Delta[I4, k4] + 6*I*SU3F[I1, k3, k4]*SU3Delta[6, I2]*
      SU3Delta[I3, k3]*SU3Delta[I4, k4])*UCouplingConstant[ChPTW3[2], 1])/
   (18*DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3)}}
