{{(-15*SU3D[I1, I4, k1]*SU3D[I2, I3, k1] - 15*SU3D[I1, I3, k1]*
     SU3D[I2, I4, k1] + 30*SU3D[I1, I2, k1]*SU3D[I3, I4, k1] + 
    9*SU3F[I1, I4, k1]*SU3F[I2, I3, k1] + 9*SU3F[I1, I3, k1]*
     SU3F[I2, I4, k1] - 10*SU3Delta[I1, I4]*SU3Delta[I2, I3] - 
    10*SU3Delta[I1, I3]*SU3Delta[I2, I4] + 20*SU3Delta[I1, I2]*
     SU3Delta[I3, I4])/(36*DecayConstant[PseudoScalar[1], 
     RenormalizationState[0]])}, 
 {(-15*SU3D[I1, I4, k1]*SU3D[I2, I3, k1] + 30*SU3D[I1, I3, k1]*
     SU3D[I2, I4, k1] - 15*SU3D[I1, I2, k1]*SU3D[I3, I4, k1] - 
    9*SU3F[I1, I4, k1]*SU3F[I2, I3, k1] + 9*SU3F[I1, I2, k1]*
     SU3F[I3, I4, k1] - 10*SU3Delta[I1, I4]*SU3Delta[I2, I3] + 
    20*SU3Delta[I1, I3]*SU3Delta[I2, I4] - 10*SU3Delta[I1, I2]*
     SU3Delta[I3, I4])/(36*DecayConstant[PseudoScalar[1], 
     RenormalizationState[0]])}, 
 {(30*SU3D[I1, I4, k1]*SU3D[I2, I3, k1] - 15*SU3D[I1, I3, k1]*
     SU3D[I2, I4, k1] - 15*SU3D[I1, I2, k1]*SU3D[I3, I4, k1] - 
    9*SU3F[I1, I3, k1]*SU3F[I2, I4, k1] - 9*SU3F[I1, I2, k1]*
     SU3F[I3, I4, k1] + 20*SU3Delta[I1, I4]*SU3Delta[I2, I3] - 
    10*SU3Delta[I1, I3]*SU3Delta[I2, I4] - 10*SU3Delta[I1, I2]*
     SU3Delta[I3, I4])/(36*DecayConstant[PseudoScalar[1], 
     RenormalizationState[0]])}}
