{{(CouplingConstant[ChPT3[4], 5, RenormalizationState[0]]*
     ((-16*SU3D[8, I1, I2])/Sqrt[3] - (8*SUNDelta[I1, I2])/3) - 
    8*CouplingConstant[ChPT3[4], 4, RenormalizationState[0]]*
     SUNDelta[I1, I2])/DecayConstant[PseudoScalar[1], 
    RenormalizationState[0]]}, 
 {(CouplingConstant[ChPT3[4], 5, RenormalizationState[0]]*
     (-8*SU3D[3, I1, I2] + (8*SU3D[8, I1, I2])/Sqrt[3] - 
      (8*SUNDelta[I1, I2])/3) - 8*CouplingConstant[ChPT3[4], 4, 
      RenormalizationState[0]]*SUNDelta[I1, I2])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]}, 
 {(CouplingConstant[ChPT3[4], 5, RenormalizationState[0]]*
     (8*SU3D[3, I1, I2] + (8*SU3D[8, I1, I2])/Sqrt[3] - 
      (8*SUNDelta[I1, I2])/3) - 8*CouplingConstant[ChPT3[4], 4, 
      RenormalizationState[0]]*SUNDelta[I1, I2])/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]}}
