{{(16*I*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 1, 
       RenormalizationState[0]] + SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 2, RenormalizationState[0]] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 2, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 3, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {(16*I*(2*SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 1, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 2, RenormalizationState[0]] + 
     SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 2, 
       RenormalizationState[0]] + SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 3, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {(16*I*(2*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 1, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 2, RenormalizationState[0]] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 2, 
       RenormalizationState[0]] + SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 3, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-8*I)/3*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       4, RenormalizationState[0]] + 2*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 4, RenormalizationState[0]] - 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 5, 
       RenormalizationState[0]] - 5*SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-8*I)/3*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       4, RenormalizationState[0]] + 2*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 4, RenormalizationState[0]] - 
     10*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 5, 
       RenormalizationState[0]] - 5*SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-8*I)/3*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       4, RenormalizationState[0]] - 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 4, RenormalizationState[0]] + 
     2*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]] - 
     5*SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 5, 
       RenormalizationState[0]] + SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((-8*I)/3*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       4, RenormalizationState[0]] - 10*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 4, RenormalizationState[0]] + 
     2*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]] - 
     5*SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 5, 
       RenormalizationState[0]] + SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((8*I)/3*(10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       4, RenormalizationState[0]] - 2*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 4, RenormalizationState[0]] - 
     2*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]] + 5*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]] - 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 5, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((8*I)/3*(10*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       4, RenormalizationState[0]] - 2*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 4, RenormalizationState[0]] - 
     2*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]] + 5*SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]] - 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 5, 
       RenormalizationState[0]] - SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}, 
 {((64*I)/3*(2*SUNDelta[I1, I4]*SUNDelta[I2, I3]*UCouplingConstant[ChPT2[4], 
       6, RenormalizationState[0]] + 2*SUNDelta[I1, I3]*SUNDelta[I2, I4]*
      UCouplingConstant[ChPT2[4], 6, RenormalizationState[0]] + 
     2*SUNDelta[I1, I2]*SUNDelta[I3, I4]*UCouplingConstant[ChPT2[4], 6, 
       RenormalizationState[0]] + SUNDelta[I1, I4]*SUNDelta[I2, I3]*
      UCouplingConstant[ChPT2[4], 8, RenormalizationState[0]] + 
     SUNDelta[I1, I3]*SUNDelta[I2, I4]*UCouplingConstant[ChPT2[4], 8, 
       RenormalizationState[0]] + SUNDelta[I1, I2]*SUNDelta[I3, I4]*
      UCouplingConstant[ChPT2[4], 8, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^4}}
