{{(((-4*I)/3)*CouplingConstant[ChPTW3[2], 1]*QuarkCondensate[
     RenormalizationState[0]]*(-6*CouplingConstant[ChPTW3[4], 11]*
      SUNDelta[0, I1]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]] - 4*CouplingConstant[ChPTW3[4], 12]*
      SUNDelta[0, I1]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]] + 3*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 3*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + Sqrt[3]*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
      SUNDelta[0, I1]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
     2*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*SUNDelta[0, I1]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] - 3*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - 2*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
      SUNDelta[0, I1]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
     2*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*SUNDelta[0, I1]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + CouplingConstant[ChPTW3[4], 13]*
      (3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
          UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] + 
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]]]]*
        (Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
            UMatrix[UGenerator[I2]]]] + 
         3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
            UMatrix[UGenerator[3]]]] + Sqrt[3]*UTrace1[NonCommutative[
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]) + 
       SUNDelta[0, I1]*(-6*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I2]]]] + 
         9*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
         3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
         9*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
         3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]])) - 
     3*CouplingConstant[ChPTW3[4], 11]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - 2*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 3*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     3*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     3*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] + 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     CouplingConstant[ChPTW3[4], 10]*
      (-2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       SUNDelta[0, I1]*(-4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I2]]]] + 
         6*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] + 
         2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
         6*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] + 
         2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]) - 
       2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[I2]]]] + 
       3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[I1]]]] + Sqrt[3]*
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[I2]]]] + Sqrt[3]*
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[I1]]]] + 
       3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[3]]]] + Sqrt[3]*UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
       3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[3]]]] + Sqrt[3]*UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}, 
 {(((4*I)/3)*CouplingConstant[ChPTW3[2], 1]*QuarkCondensate[
     RenormalizationState[0]]*(6*CouplingConstant[ChPTW3[4], 11]*
      SUNDelta[0, I1]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]] + 4*CouplingConstant[ChPTW3[4], 12]*
      SUNDelta[0, I1]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]]]] + 3*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 3*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]]]]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] - Sqrt[3]*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]]]]*
      UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
      SUNDelta[0, I1]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] - 
     2*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*SUNDelta[0, I1]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]]]] + 3*CouplingConstant[ChPTW3[4], 11]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 2*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]]]] + 6*CouplingConstant[ChPTW3[4], 12]*
      SUNDelta[0, I1]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] - 
     2*Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*SUNDelta[0, I1]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]]]] + CouplingConstant[ChPTW3[4], 13]*
      (3*UTrace1[NonCommutative[UMatrix[UGenerator[3]], 
          UMatrix[UGenerator[I2]]]]*UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]]]] - 
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]]]]*
        (Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[8]], 
            UMatrix[UGenerator[I2]]]] - 
         3*UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
            UMatrix[UGenerator[3]]]] + Sqrt[3]*UTrace1[NonCommutative[
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]) + 
       SUNDelta[0, I1]*(6*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I2]]]] + 
         9*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] - 
         3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
         9*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] - 
         3*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]])) + 
     3*CouplingConstant[ChPTW3[4], 11]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 2*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[I1]]]] + 3*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[3]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[8]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
     3*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] - 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
     3*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] - 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
        UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
     3*CouplingConstant[ChPTW3[4], 12]*UTrace1[NonCommutative[
        UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]]]] - 
     Sqrt[3]*CouplingConstant[ChPTW3[4], 12]*
      UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
        UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]] + 
     CouplingConstant[ChPTW3[4], 10]*
      (2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       SUNDelta[0, I1]*(4*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I2]]]] + 
         6*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]]]] - 
         2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
         6*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[3]]]] - 
         2*Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]]) + 
       2*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[3]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[I2]]]] + 
       3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[3]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[I1]]]] - Sqrt[3]*
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[I2]]]] - Sqrt[3]*
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[I1]]]] + 
       3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[3]]]] - Sqrt[3]*UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]] + 
       3*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[3]]]] - Sqrt[3]*UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}, 
 {(((4*I)/3)*CouplingConstant[ChPTW3[2], 1]*QuarkCondensate[
     RenormalizationState[0]]*(CouplingConstant[ChPTW3[4], 11]*
      (6*SUNDelta[0, I1]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I2]]]] + 2*Sqrt[3]*
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[8]]]]*(UTrace1[NonCommutative[
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
         UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
           UMatrix[UGenerator[I1]]]]) + 
       3*(UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]])) + 
     2*(CouplingConstant[ChPTW3[4], 13]*
        (Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I1]]]]*(UTrace1[NonCommutative[
             UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
           UTrace1[NonCommutative[UMatrix[UGenerator[I2]], 
             UMatrix[UGenerator[8]]]]) + 3*SUNDelta[0, I1]*
          (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I2]]]] + Sqrt[3]*
            (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[
                UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
             UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[
                UGenerator[I2]], UMatrix[UGenerator[8]]]]))) + 
       CouplingConstant[ChPTW3[4], 12]*
        (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
         2*SUNDelta[0, I1]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I2]]]] + Sqrt[3]*
            (UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[
                UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
             UTrace1[NonCommutative[UMatrix[UGenerator[6]], UMatrix[
                UGenerator[I2]], UMatrix[UGenerator[8]]]])) + 
         UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
         Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
            UMatrix[UGenerator[I1]]]] + Sqrt[3]*UTrace1[NonCommutative[
            UMatrix[UGenerator[6]], UMatrix[UGenerator[I1]], 
            UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
         Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
            UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
            UMatrix[UGenerator[8]]]] + Sqrt[3]*UTrace1[NonCommutative[
            UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
            UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]]]])) + 
     2*CouplingConstant[ChPTW3[4], 10]*
      (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]]]] + 
       2*SUNDelta[0, I1]*(UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
           UMatrix[UGenerator[I2]]]] + Sqrt[3]*
          (UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]]]] + 
           UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
             UMatrix[UGenerator[I2]], UMatrix[UGenerator[8]]]])) + 
       UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
         UMatrix[UGenerator[I2]], UMatrix[UGenerator[I1]]]] + 
       Sqrt[3]*UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[8]], UMatrix[UGenerator[I1]], 
          UMatrix[UGenerator[I2]]]] + Sqrt[3]*
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[8]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[I1]]]] + Sqrt[3]*
        UTrace1[NonCommutative[UMatrix[UGenerator[6]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[8]]]] + Sqrt[3]*UTrace1[NonCommutative[
          UMatrix[UGenerator[6]], UMatrix[UGenerator[I2]], 
          UMatrix[UGenerator[I1]], UMatrix[UGenerator[8]]]])))/
   DecayConstant[PseudoScalar[1], RenormalizationState[0]]^3}}
