{{(-16*I*(2*SUNDelta[0, I3]*SUNDelta[I1, I2]*CouplingConstant[ChPT2[4], 4, 
       RenormalizationState[0]] + SUNDelta[0, I3]*SUNDelta[I1, I2]*
      CouplingConstant[ChPT2[4], 5, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}, 
 {(-64*I*(2*SUNDelta[0, I3]*SUNDelta[I1, I2]*CouplingConstant[ChPT2[4], 6, 
       RenormalizationState[0]] + SUNDelta[0, I3]*SUNDelta[I1, I2]*
      CouplingConstant[ChPT2[4], 8, RenormalizationState[0]]))/
   DecayConstant[PseudoScalar[2], RenormalizationState[0]]^2}}
