(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Phi4",
  Authors -> {"Vladyslav Shtabovenko"},
  Institutions -> {"FeynCalc project"},
  Emails -> {""},
  Date -> "13.05.2026"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    PropagatorLabel -> "\[Phi]",
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mphi,
    Indices -> {} }
}


(*        Definitions       *)


mphi[ ___ ] := mphi;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] ] == {{0, (-I)*mphi^2*(-1 + Zmphi*Zphi)}, {0, (-I)*(-1 + Zphi)}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-I)*g, (-I)*g*(-1 + Zg*Zphi^2)}}

}

