(* ::Package:: *)

 


(* ::Section:: *)
(*PatchModelsOnly*)


(* ::Text:: *)
(*`PatchModelsOnly` is an option of `FAPatch`. When set to `True`, `FAPatch` will patch only the model files in the `"Models"` directory of the FeynArts installation. This is useful when you have added new custom models, e.g. generated by FeynRules.*)


(* ::Subsection:: *)
(*See also*)


(* ::Text:: *)
(*[Overview](Extra/FeynCalc.md), [FAPatch](FAPatch.md).*)


(* ::Subsection:: *)
(*Examples*)
