(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"QED",
  Authors -> {"Vladyslav Shtabovenko"},
  Institutions -> {"FeynCalc project"},
  Emails -> {""},
  Date -> "27.01.2026"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
F[2] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation]},
    QuantumNumbers -> {Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mlep },

V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\gamma",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} }
}


(*        Definitions       *)


Mlep[ 1 ] := FCGV["ME"];
Mlep[ 2 ] := FCGV["MM"];
Mlep[ 3 ] := FCGV["ML"];


TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[1] , V[1] ] == {{0, (-I)*(-1 + ZA)}, {0, (I*(ZA - Zxi))/(Zxi*FAGaugeXi[V[1]])}, {0, I*mxt^2*(-1 + ZAmxt)*(1 + ZAmxt)}, {0, I*(-1 + ZA)}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*FCGV["EL"]*IndexDelta[e1x2, e2x2], I*FCGV["EL"]*(-1 + Sqrt[ZA]*Ze*Zpsi)*IndexDelta[e1x2, e2x2]}, {I*FCGV["EL"]*IndexDelta[e1x2, e2x2], I*FCGV["EL"]*(-1 + Sqrt[ZA]*Ze*Zpsi)*IndexDelta[e1x2, e2x2]}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] ] == {{0, (-I)*(-1 + Zm*Zpsi)*IndexDelta[e1x2, e2x2]*Mlep[e1x2]}, {0, (-I)*(-1 + Zm*Zpsi)*IndexDelta[e1x2, e2x2]*Mlep[e1x2]}, {0, I*(-1 + Zpsi)*IndexDelta[e1x2, e2x2]}, {0, I*(-1 + Zpsi)*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}}

}

